### ISSUE TITLE
Is there a way to make certain dependencies always get treated as patch or greater?

### ISSUE THREAD

**Issue by Aghassi** [renovatebot/config-help#100]
Is there a way to always treat certain dependency groups or single dependencies as `fix/feat` or higher? For instance, if a main `dependency` comes in with a `patch` bump, can I make it treated as a `fix` always? There was an instance in which one of our `dependencies` came in with a patch, and it had fixes for a problem in the current repo. However, renovate treated it as a "chore". Would like to ensure that some dependencies are always treated as `fix` or higher.

**Comment by rarkins** [comment]
What are your current settings? If you extend “config:base” then anything in `dependencies` should always be a `fix`even if it’s a patch. So I assume you are either not using that preset or you have some other rule that is superseding it. Either way I need to know in order to answer your question for sure.

**Comment by Aghassi** [comment]
```
"default": {
      "extends": [
        ":separateMajorReleases",
        ":combinePatchMinorReleases",
        ":ignoreUnstable",
        ":prImmediately",
        ":renovatePrefix",
        ":updateNotScheduled",
        ":ignoreModulesAndTests",
        ":maintainLockFilesDisabled",
        ":autodetectPinVersions",
        ":prConcurrentLimit20",
        "group:monorepos",
        "helpers:disableTypesNodeMajor",
        "helpers:oddIsUnstablePackages",
        ":automergeDigest",
        ":automergePatch",
        ":pinAllExceptPeerDependencies"
      ],
      "semanticCommits": true,
      "respectLatest": true,
      "updateLockFiles": true,
      "prHourlyLimit": 0,
      "prConcurrentLimit": 0,
      "labels": [
        "dependency-update"
      ],
      "patch": {
        "labels": [
          "patch",
          "automerge",
          "dependency-update"
        ]
      },
      "minor": {
        "labels": [
          "minor",
          "dependency-update"
        ],
        "semanticCommitType": "feat",
        "automerge": false
      },
      "major": {
        "labels": [
          "major",
          "dependency-update"
        ],
        "semanticCommitType": "feat",
        "commitBody": "BREAKING CHANGE:",
        "automerge": false
      },
      "digest": {
        "labels": [
          "digest",
          "automerge",
          "dependency-update"
        ]
      },
      "packageRules": [
        {
          "packagePatterns": [
            "semantic-release"
          ],
          "groupName": "semantic-release"
        },
        {
          "automerge": true,
          "semanticCommitType": "chore",
          "depTypeList": [
            "devDependencies"
          ]
        }
      ]
    }
```

**Comment by rarkins** [comment]
The field that controls fix/feat/chore is [semanticCommitType](semanticCommitType), and it defaults to "chore".

Looking through your config, you specify it:
- minor and major updates of any type of dependency will have type "feat"
- `semantic-release` packages should have type "chore"

If you want to also treat all `dependencies` patches as `fix`, you can add this rule:

```json
"packageRules": [{
	"depTypeList": ["dependencies"],
	"updateTypes": ["patch"],
	"semanticCommitType": "fix"
}]
```

**Comment by Aghassi** [comment]
@rarkins Ok that's probably doable. I'm not sure why a `patch` wouldn't be `fix` by default. I will update the config and ensure it works.
