### ISSUE TITLE
Renovate app disabled on gitlab.com

### ISSUE THREAD

**Issue by cilefen** [renovatebot/config-help#1001]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitLab.com

### Have you checked the logs? Don't forget to include them if relevant

The very problem is that the logs are unreadable.

### What would you like to do?

First, thank you so much for this tool. The issue here is that renovatebot had been working on two repos and since about one day ago, simply reads "error" for every execution. If anything was logged, I cannot read it. When clicking on the log file list, the browser console reports a 404, for example, https://v1.renovateapi.com/gitlab/repos/cilefen/hspool/jobs/266653175/logs is a 404 that returns:

```json
{
    "message": "log file not found"
}
```

**Comment by viceice** [comment]
The renovate app is currently disabled for gitlab. We will provide more information later.

We currently suggest to configure a self-hosted renovate.

**Comment by viceice** [comment]
track https://github.com/renovatebot/renovate/issues/7843 for futher infos
