### ISSUE TITLE
disable automerge

### ISSUE THREAD

**Issue by rarkins** [renovatebot/config-help#1005]
Hi @rarkins, I'll ping you on this issue, but, if you prefer, I can create a new one. I have a similar problem, my `renovate.json` looks like this

```json
{
    "extends": [
        "config:base",
        ":semanticCommitTypeAll(fix)"
    ],
    "prConcurrentLimit": 0,
    "prHourlyLimit": 0,
    "automerge": true,
    "major": {
        "automerge": false
    },
    "masterIssue": true,
    "masterIssueAutoclose": true,
    "packageRules": [
        {
            "packagePatterns": ["^org.jetbrains.kotlin"],
            "groupName": "Kotlin packages",
            "automerge": false
        }
    ]
}
```

the MR with all the kotlin packages grouped together works as expected, however, the `automerge: false` doesn't. Am I doing something wrong?

_Originally posted by @gmariotti in https://github.com/renovatebot/config-help/issues/191#issuecomment-736338749_

**Comment by rarkins** [comment]
That looks to me like it should work. Do you mean the Kotlin packages are grouped as expected but automerge is still enabled for that PR?

**Comment by gmariotti** [comment]
I mean that. With this configuration I would expect the MR to be blocked but, instead, renovate merges it. My setup is Gitlab self hosted, renovate version 23.89.3

**Comment by rarkins** [comment]
The almost identical config you mention works as expected here: https://github.com/rarkins/automerge-test-1/pull/1

Maybe you have some bot-side config you've forgotten about or something like that?

**Comment by gmariotti** [comment]
The bot `config.js` looks like this, is it possible that the `packageRules` is the problem? I didn't find any reference of it in the documentation for self-hosted.

```javascript
module.exports = {
    // omited some sensitive fields
    platform: 'gitlab',
    logFileLevel: 'warn',
    logLevel: 'info',
    logFile: './renovate.log',
    onboarding: true,
    extends: ['config:base', ":semanticCommitTypeAll(fix)"],
    prHourlyLimit: 0,
    labels: [
        'renovate',
        'dependencies'
    ],
    trustLevel: 'high',
    npmrc: process.env.NPMRC_CONTENT,
    packageRules: [
      {
        "updateTypes": ["minor", "patch", "pin", "digest"],
        "automerge": true
      }
    ]
}
```

**Comment by rarkins** [comment]
Yes, that's the problem. Add `updateTypes` to your repository packageRules if you want them to have the same importance as the rule you have in your `config.js`.

**Comment by gmariotti** [comment]
What would happen if I just drop it from the `config.js` of the bot? Would renovate only use the configuration defined in each project?

**Comment by rarkins** [comment]
yes, that should fix your problem

**Comment by gmariotti** [comment]
Tried it now and I can confirm that it works successfully. Thank you so much @rarkins 🙇
