### ISSUE TITLE
Allow Dry Run Per Project

### ISSUE THREAD

**Issue by Gr33nbl00d** [renovatebot/config-help#1008]
Whenever adding renovate to a new project i usually have to do some exclusions and config adoptions per project.
It would be nice to have some kind of dry run per project.

The idea is that you could add dryRun:true to your project level renovate config.
And than an issue is created with a list of changes.
This way it would be easy to adopt the config as long as it takes till renovate does exactly what it should do

**Comment by rarkins** [comment]
There's no point in a dry run if you can't view the logs, so in that case the recommendation is definitely dependencyDashbordApproval
