### ISSUE TITLE
Is there a way to specific custom test command

### ISSUE THREAD

**Issue by bahmutov** [renovatebot/config-help#101]
My `npm test` command runs a short set of tests, but my CI usually runs many more test commands. It would be nice to
- run a custom command instead of `npm test`, something like `npm run test:ci` for example
- run a list of commands for clarity, something like `"test": ["npm run test1", "npm run test2"]`

**Comment by rarkins** [comment]
I’m confused as to how/where this would be run. Renovate just create branches with a single commit and it’s then up to the CI to “decide” which tests to run. 

I’m not sure how Renovate could influence that?

**Comment by bahmutov** [comment]
good, I got confused by what was going on, so my question does not make sense,
