### ISSUE TITLE
ignore Docusaurus v2.0.0-alpha.f37987f32 type PRs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/config-help#1014]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

I don't think the logs are relevant for now.

### Background

Docusaurus v2 are now publishing "canary" releases:
> Make new fixes accessible to power users as soon as they get merged, by publishing a npm version under the "canary" dist tag.

See [PR 3827, at the Docusaurus GitHub repo](https://github.com/facebook/docusaurus/pulls?q=is%3Apr+3827+is%3Aclosed) to get the inside view on what they're doing there.

### What I want

The new "canary" release process that Docusaurus uses causes Renovate to open a PR for those canary releases.
These PRs eat into my build minutes for the website, and I don't want to have really rough dev-work in production anyways.
I only want the mainline "human-approved" releases.

The pattern for the canary releases seems to be the same as for the normal releases, with the exception that they use a commit hash instead of a version number.

### Versions I want/don't want

| Yes please | No thanks|
| --- | --- |
| `v2.0.0-alpha.69` or `v2.0.0` | `v2.0.0-alpha.f37987f32` |

### Example wanted PR:
https://github.com/RoostingGeese/git-gosling/pull/90

### Example unwanted PRs:
https://github.com/RoostingGeese/git-gosling/pull/96
https://github.com/RoostingGeese/git-gosling/pull/95
https://github.com/RoostingGeese/git-gosling/pull/91

### Main question:

I guess I'm looking for a regex that can filter out the unwanted branches...

It would be way cleaner if I could tell the Renovate bot to ignore the npm "canary" dist tag versions, but I haven't found this in the docs. I'm thinking that the **ignore npm tagged version** thing might also warrant a proper feature request at the `renovatebot/renovate` repository... 😄 

### My current config:

Copy/pasted from https://github.com/RoostingGeese/git-gosling/blob/main/renovate.json

```json
{
  "extends": ["config:base"],
  "lockFileMaintenance": {
    "enabled": true
  },
  "dependencyDashboard": true
}
```

**Comment by rarkins** [comment]
You can define a package rule with allowedVersions to either allow only a pattern you want or disallow a pattern you don't.

**Comment by HonkingGoose** [comment]
## Regex problems

I've not been able to get the regex working, I think I'm doing something wrong. The Renovate bot was complaining as well. I'm trying to match only the `v2.0.0` release OR `v2.0.0-alpha.69` releases.

```json
{
  "extends": ["config:base"],
  "lockFileMaintenance": {
    "enabled": true
  },
  "dependencyDashboard": true,
  "packageRules": [
    {
      "packagePatterns": ["^@docusaurus"],
      "allowedVersions": "/v2.0.0(-alpha.(\d\d)|)"
    }
  ]
}
```

## dependencyDashboardApproval workaround

Because I could not get it working, I'm now using the `dependencyDashboardApproval` workflow for the Docusaurus packages instead:

```json
{
  "extends": ["config:base"],
  "lockFileMaintenance": {
    "enabled": true
  },
  "dependencyDashboard": true,
  "packageRules": [
    {
      "packagePatterns": ["^@docusaurus"],
      "dependencyDashboardApproval": true
    }
  ]
}
```

This is still not optimal, but it's the best that I could get going for now... 😞

**Comment by viceice** [comment]
wrong regex, try this:

```json
{
  "extends": ["config:base"],
  "lockFileMaintenance": {
    "enabled": true
  },
  "dependencyDashboard": true,
  "packageRules": [
    {
      "packagePatterns": ["^@docusaurus"],
      "allowedVersions": "/^v2.0.0(-alpha.(\d+))?$/"
    }
  ]
}
```

**Comment by viceice** [comment]
Maybe you should better use [followTag](https://docs.renovatebot.com/configuration-options/#followtag)

```json
{
  "extends": ["config:base"],
  "lockFileMaintenance": {
    "enabled": true
  },
  "dependencyDashboard": true,
  "packageRules": [
    {
      "packagePatterns": ["^@docusaurus"],
      "followTag": "lastest"
    }
  ]
}

**Comment by rarkins** [comment]
I think he's after `next` tag, not `latest`:

![image](https://user-images.githubusercontent.com/6311784/101159785-39242e00-362e-11eb-94c4-b770f0633c75.png)

Problem is you then need to switch back from that config later once it hits 2.0.0 stable.

A simpler allowVersions could be `!/(alpha|beta|rc)\.[a-z0-9]{7,}/`

**Comment by viceice** [comment]
nope, you are on wrong npm package, he has https://www.npmjs.com/package/@docusaurus/core and https://www.npmjs.com/package/@docusaurus/preset-classic where the latest points to 2.0.0-alpha.69 😉

**Comment by rarkins** [comment]
OK, that's some unfortunately tagging then. I'd recommend to stick to `allowedVersions` patterns considering that.

**Comment by viceice** [comment]
yeah, i think the [docusaurus v2](https://www.npmjs.com/package/docusaurus/v/2.0.0-alpha.66) package is a forward only package to pull in the new scoped packages

**Comment by HonkingGoose** [comment]
I'll try @viceice's better regex and see if that does the trick in filtering out the unwanted PRs. 🤞

**Comment by HonkingGoose** [comment]
I can confirm the new regex from @viceice is working. Jay! 🎉 

The Docusuaurus v2 project has made some new canary releases, and Renovate ignored those releases.

Closing this issue, as it seems to be resolved now. 😄 Thanks for all the help and input!
