### ISSUE TITLE
Code Artifact Configuration

### ISSUE THREAD

**Issue by jsrice7391** [renovatebot/config-help#1015]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub.com

### What would you like to do?

I am working on self-hosting Renovate Bot in order to scan my companies internal packages and dependencies. We are moving from JFrog to Code Artifact. Code Artifact writes its authentication tokens to ~/.config/pip/pip.conf. Optimally I have away to tell Renovate that the credentials file is in ~/config/pip/pip.conf. 

My second approach to this would be to use the AWS SDK and call a function to try and grab that authentication token and then place it within the `module.exports` object within my `config.js`

My question is: If I need to execute a function to do such a thing before calling `./node_modules/renovate/dist/renovate.js` how would I do such a thing?

**Comment by rarkins** [comment]
It sounds like you could achieve this easiest with `config.js` dynamically. e.g. it could do `fs.readFileSync('../.config/pip/pip.conf')` and then parse your file to generate `hostRules`. Just make sure you don't require any libaries which are not already in Renovate's `node_modules`.
