### ISSUE TITLE
Question: is there a renovate badge?

### ISSUE THREAD

**Issue by daKmoR** [renovatebot/config-help#103]
hey,

I really love renovate :) makes life so much easier :)
I wanna show that I use it - as I think it really improves the quality of a project (as it makes it 100% easier to stay up to date)

I couldn't find a badge and I couldn't find a better place to ask 🙈 

If there is no badge - I can just show the logo.

But a badge like this would be really nice :)

[ dependencies  | up-to-date ]
[ devDependencies  | up-to-date ]

**Comment by rarkins** [comment]
Thanks for your feedback!

There is currently no "dynamic" badge, just a static SVG that the Renovate repo uses: `[![Renovate enabled](https://img.shields.io/badge/renovate-enabled-brightgreen.svg)](https://renovatebot.com/)`

I have an issue open in the main repo about adding a dynamic badge, you can subscribe there to follow progress or offer your ideas: https://github.com/renovatebot/renovate/issues/534
