### ISSUE TITLE
Will `automerge` as `branch push` work with protected `master`?

### ISSUE THREAD

**Issue by Igmat** [renovatebot/config-help#104]
I configured `renovate` in such with a hope that it will push updates directly to `master` if version change is minor/patch and create PRs if it's major.
```JSON
{
  "extends": [
    "config:js-lib",
    ":automergeMinor",
    ":automergeBranchPush",
    ":automergeRequireAllStatusChecks",
    ":maintainLockFilesWeekly",
    ":unpublishSafe"
  ],
  "statusCheckVerify": true
}
```

But my `master` branch is configured as `protected` in github, so I'm not sure about it. Plus, I don't see any new commits, even though renovate branch was created and all checks have passed.

**Comment by Igmat** [comment]
Ok, seems that removing `Review Required` options works for me.

But I don't understand why [this PR](https://github.com/Igmat/metaf/pull/11) says:
> **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

Will it always ask me to merge `lock-file` updates by myself, or only initially?

**Comment by rarkins** [comment]
Assuming that there's no bug in that logic, it means that Renovate has not detected automerge as enabled for that branch.

Looking again at your config, I can see why. `:automergeMinor` literally just sets automerge true for updates of type 'minor', while lock file maintenance is of type 'lockFileMaintenance' so it doesn't get caught by that preset. I think though that it makes sense to update the preset to automerge for lockFileMaintenance too, if the user is happy to be merging minor updates anyway.

**Comment by rarkins** [comment]
I have patched that preset now, so the next time you see a lock file maintenance branch/PR it should be set to automerge.

**Comment by Igmat** [comment]
@rarkins, great -thank you very much:)
