### ISSUE TITLE
Renovate PRO: lockFileErrors without output

### ISSUE THREAD

**Issue by 0xR** [renovatebot/config-help#105]
I'm getting `lockFileErrors` for some public and private dependencies. It does not happen for all dependencies though. The `stderr` output is empty. I'm guessing the useful information was in the `stdout`. Maybe our private npm registry is unreliable?

I'm guessing I need better logging output first. And after that renovate might need to try to recover if the npm repo was unstable.

```
 WARN: lockFileErrors (repository=org/repo, dependencies=eslint-plugin-node, branch=renovate/eslint-plugin-node-7.0.x)
       "lockFileErrors": [{"lockFile": "package-lock.json", "stderr": ""}]
 INFO: Added comment (repository=org/repo, dependencies=eslint-plugin-node, branch=renovate/eslint-plugin-node-7.0.x)
       "issueNo": 266
 INFO: Setting branch status (repository=org/repo, dependencies=eslint-plugin-node, branch=renovate/eslint-plugin-node-7.0.x)
       "branchName": "renovate/eslint-plugin-node-7.0.x",
       "context": "renovate/lock-files",
       "state": "failure"
```

**Comment by rarkins** [comment]
That's strange as I'm pretty sure `npm` logging is usually in `stderr`. Running at LOG_LEVEL=debug could certainly help, as that includes both stdout and stderr.

> Maybe our private npm registry is unreliable?

It's a possible cause. In the next minor release of Pro it will come with dynamic rebasing support as exists in the hosted app already, e.g. you can rename a PR with "rebase!" prefix or add a "rebase" label and in either case it kicks Renovate into rebasing/retrying the branch. Doing that would mean you could soon see if it's failing every time or only sometimes.

**Comment by 0xR** [comment]
If I turn the logging to debug, will renovate try the PRs with a package-lock error again? Will I have to wait until the next scheduled run? Or do I even have to wait until a new package is updated?

Or is there a way to have renovate retry faster?

**Comment by rarkins** [comment]
Up to Pro 0.13.1, Lock files aren't retried until the branch needs to be rebased, e.g. if there's a conflict, or a newer version of the package being updated. Or if you configure `rebaseStalePrs=true` and then make a commit to `master` branch.

If you need the branch retried much faster than you need to (a) rename, and then (b) close the existing PR, which triggers Renovate to create a replacement.

In Pro 0.14.0, it will support manual rebase requests, where you can rename any open Renovate PR with a "rebase!" prefix and the resulting webhook triggers Renovate to run immediately and rebase/recreate the PR's commit. If this is important to you and you're ready to test deploy a new version, then I can cut a release sooner than I was planning, which was for next week.

**Comment by 0xR** [comment]
Trying to trigger a rebase might be good enough.
Which brings me to my next issue. I changed my rangeStrategy to bump causing me to get 30 branches. I quickly changed the concurrent pr limit to 5. However the branches are still there. If were to trigger a rebuild with rebaseStalePrs of 30 prs I will not make my teammates happy if they want to use the build server.

So I should rename and close all the PRs before I turn rebaseStatePrs to true?

**Comment by 0xR** [comment]
Tbh, I expected renovate to close the PRs because I decreased the PR limit.

**Comment by rarkins** [comment]
So question 1: If you configure a `prConcurrentLimit` that's less than the number of open PRs, should Renovate close the excess?

Right now Renovate doesn't autoclose them, and I think that's the correct behaviour by default. The rate limiting decision is made at the time of "should Renovate create this branch or not?" and not after.

*Usually*, once PRs are created then they may as well stay created. And we have some reasons why sometimes you legitimately have more open than the limit, for example we ignore schedules and limits if GitHub flags a vulnerability in the currently installed version of a package, so that you get the PR right away. I've also added a feature last week I'm calling "master issue" that gives you a kind of mini dashboard within an issue, listing all the PRs both open and pending. This specifically lets you click checkboxes to ignore rate limiting and force a PR. So to keep track of those special cases plus the limit would be challenging.

If you want to enable `rebaseStalePrs` then yes it will rebase all existing PRs if they are all stale, so the only way to stop that is to rename and close.

Due to the PR limit in place now, if you were to simply just rename and close a few of the existing PRs then you wouldn't see any replacements of them because the concurrent limit is met.

**Comment by rarkins** [comment]
Did you delete the branches?

**Comment by 0xR** [comment]
No, I should delete those as well, hmm

**Comment by rarkins** [comment]
Sorry that wasn’t clear from my description before. The pr limits are decided at branch creation so if an exact match branch already exists then that logic is bypassed.

**Comment by 0xR** [comment]
This is my debug logging. It's not that useful:
```
DEBUG: Processing existing PR (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
 INFO: Pull Request #262 does not need updating (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
 WARN: lockFileErrors (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
       "lockFileErrors": [{"lockFile": "package-lock.json", "stderr": ""}]
DEBUG: Getting comments for #262 (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
DEBUG: GET repos/ecg-marktplaats/syi-frontend/issues/262/comments?per_page=100 [retries=5] (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
DEBUG: Found 1 comments (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
DEBUG: Ensuring comment ":warning: Lock file problem" in #262 (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
DEBUG: Comment is already update-to-date (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
DEBUG: GET repos/ecg-marktplaats/syi-frontend/commits/bf02c08ce51647f8be556b5f2c2b7536ce4c821d/statuses [retries=5] (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
DEBUG: Updating status check state to failed (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
 INFO: Setting branch status (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
       "branchName": "renovate/ecg-marktplaats-webpack-config-0.10.x",
       "context": "renovate/lock-files",
       "state": "failure"
DEBUG: POST repos/ecg-marktplaats/syi-frontend/statuses/bf02c08ce51647f8be556b5f2c2b7536ce4c821d [retries=5] (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
DEBUG: processBranch with 1 upgrades (repository=ecg-marktplaats/syi-frontend, dependencies=@ecg-marktplaats/webpack-config, branch=renovate/ecg-marktplaats-webpack-config-0.10.x)
```

Ps: trigger 30 builds twice today blocking the entire company didn't get me more friends haha. Maybe renovate could have some conservative defaults here?

**Comment by rarkins** [comment]
The relevant log should be before that. Can you grep for terms like stdout, stderr and “package-lock.json”?

**Comment by 0xR** [comment]
Looks like this is it:
```
 INFO: lock file error (repository=company/repo, dependencies=@company/webpack-config, branch=renovate/company-webpack-config-0.10.x)
       "cmd": "node /usr/src/app/node_modules/npm/bin/npm-cli.js --version && node /usr/src/app/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit",
       "err": {
         "name": "ChildProcessError",
         "code": null,
         "childProcess": {},
         "stdout": "6.4.1\n",
         "stderr": ""
       },
       "stdout": undefined,
       "stderr": undefined,
       "type": "npm"
```

**Comment by rarkins** [comment]
I’ve never seen anything like it. It seems npm is found and prints its version yet the second part of the command produces zero output. Even if it were run in the wrong working directory there should be an error stating that. 

Is this definitely for all repositories or definitely only for some? Can you create a test repo with a most basic package.json (eg left-pad@1.0.0) and see if that produces the same result?

**Comment by 0xR** [comment]
ok I made some progress! I figured sometimes stdout/stderr could be nondeterministic, so I looked at all the instances to see if the output is always missing. It was not!

So I found 107 counts of `lock file error` and this is the count of the `stdout` and `stderr`

```
  75          "stderr": ""
   1          "stderr": "Killed\n"
   1          "stderr": "Unhandled rejection Error: ENOMEM: not enough memory, write\n"
  17          "stderr": "npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\n"
  13          "stderr": "npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nKilled\n"
 107          "stdout": "6.4.1\n",
```

So I got lucky, I got a `not enough memory`. I increased the memory limit of the docker container and I'm testing to see if that fixes it.

**Comment by 0xR** [comment]
That seems to have solved it! I had to rename, close and remove branch for all the existing PRs with lock file errors. Then renovate tried again and no more lock file errors showed up!

**Comment by rarkins** [comment]
That looks like a lucky - but skilled - catch. Thanks for sharing your finding. I’ve never run into out of memory errors on the hosted service so it wasn’t something I considered. 

Next release will make rebasing much simpler.
