### ISSUE TITLE
Rebasing a GitLab MR

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/config-help#106]
How do I tell renovate to rebase MRs? I would also like this to be done automatically as well.

In one of my MRs, it doesn't show any instructions for this:

![screenshot-gitlab com-2018 10 09-11-11-17](https://user-images.githubusercontent.com/253237/46662711-131cb380-cbb4-11e8-8054-576d27ae6596.png)

**Comment by rarkins** [comment]
Master issue, or rename issue with “rebase!” prefix and then run again.

**Comment by rarkins** [comment]
@joelmukuthu 	no, that hasn't been implemented yet. If you'd like it, please raise a PR in the main repo including relevant links to GitLab documentation.
