### ISSUE TITLE
Why did this PR automerged?

### ISSUE THREAD

**Issue by teppeis** [renovatebot/config-help#107]
https://github.com/teppeis-sandbox/renovate-demo-1/pull/7

This was created on 18 Jun and automerged 26 mins ago unexpectedly.
The config is https://github.com/teppeis/renovate-config.
Automerge for lockfile is disabled.
The config is not changed for recent 6 days.

- automerged log: https://renovatebot.com/dashboard#teppeis-sandbox/renovate-demo-1/23397569
- previous log: https://renovatebot.com/dashboard#teppeis-sandbox/renovate-demo-1/23391113

**Comment by rarkins** [comment]
It was merged as a result of this change to the automerge presets: https://github.com/renovatebot/presets/commit/89249a88658cb211882519d167f548f8d86f8662

This was as a result of someone being confused by `:automergeMinor` *wouldn't* merge lock file updates and I thought it was a good idea. However do you think it is undesirable and should be reverted?

**Comment by teppeis** [comment]
@rarkins OK. The change is reasonable for me. It doesn't have to be reverted.

But generally, updating builtin presets is probably a breaking change for existing users.
My idea is to enable to control the builtin presets version locally like `npm i @renovate/presets`.
This mechanism is also useful for shareable config.
Although this may be more complicated internally...
