### ISSUE TITLE
Not getting Dockerfile updates any more

### ISSUE THREAD

**Issue by warrenv** [renovatebot/config-help#109]
After updating the deafault config and moving it to `.renovaterc.json`, we are only getting nodejs upgrades for `.nvmrc`. Prior to this config change (ie, using the default renovate config), the
nodejs version upgrades were also being picked up in `Dockerfile`. Any idea why this has changed?
```json
{
  "extends": [
    "config:base"
  ],
  "labels": [
    "dependencies"
  ],
  "reviewers": ["poetapp/quality-engineering"],
  "schedule": [
    "after 2am",
    "before 4am"
  ],
  "patch": {
    "automerge": true
  },
  "devDependencies": {
    "minor": {
      "automerge": true
    }
  }
}
```

The PR is here: https://github.com/poetapp/node/pull/540

**Comment by rarkins** [comment]
As of right now there’s no 10.12.0 for node on Docker Hub: 
https://hub.docker.com/_/node

The PR is here: 
https://github.com/nodejs/docker-node/pull/872

Once it’s published there I’d expect it to get added to that PR. Please reopen if that doesn’t happen.

**Comment by warrenv** [comment]
Thanks for the explanation.
