### ISSUE TITLE
How to use presets with args

### ISSUE THREAD

**Issue by RyanZim** [renovatebot/config-help#110]
In `renovate-config-default`, there are a number of presets that use `{{arg0}}`, `{{arg1}}`, etc. For example: https://github.com/renovatebot/presets/blob/4f66d850c139fd197b4da54d9acee13fef01277f/packages/renovate-config-default/package.json#L414-L419

How would I go about using such presets?

**Comment by rarkins** [comment]
Like so: “:label(update)” or “:labels(update,deps)”

Ie do not quote the string(s) you pass as arguments, and separate them with commas.

Here’s an example: 
https://github.com/renovatebot/renovate/blob/373619d7812a8c4e395df0c669b06f37b68c7bf1/renovate.json#L6

**Comment by RyanZim** [comment]
Thanks a lot! Any chance this could get added to the docs?

**Comment by rarkins** [comment]
Done: https://github.com/renovatebot/renovate/pull/2640
