### ISSUE TITLE
Can I enable Renovate for a forked repository in GitHub App?

### ISSUE THREAD

**Issue by teppeis** [renovatebot/config-help#112]
I got this message in https://renovatebot.com/dashboard#teppeis/nock-back-mocha/23962251 .

> INFO: Repository is a fork and not manually configured - skipping

**Comment by rarkins** [comment]
Yes, you first need to add the `renovate.json` to master branch manually and include `renovateFork=true` in the config.

**Comment by teppeis** [comment]
@rarkins thanks!
