### ISSUE TITLE
never got onboarding PR

### ISSUE THREAD

**Issue by mobilemind** [renovatebot/config-help#113]
I never got the onboarding PR for <https://github.com/mobilemind/js2url>  but I see a dashboard entry– <https://renovatebot.com/dashboard#mobilemind/js2uri/24062588>

What do I do to get started? I have another repo with the same issue.

**Comment by rarkins** [comment]
I've added a patch to skip over non-string values. Once it's live in the app, you should get the onboarding PR for this repo.

**Comment by NullVoxPopuli** [comment]
I'm also not getting any feedback
https://gitlab.com/NullVoxPopuli/emberclear/
