### ISSUE TITLE
Configuration review for automerge of DefinitelyTyped packages

### ISSUE THREAD

**Issue by astorije** [renovatebot/config-help#115]
Hey there!

I would like to make our Renovate configuration automatically merge `@types/...` PRs (from https://github.com/DefinitelyTyped/DefinitelyTyped) if the PR status checks are green (they run our own Jenkins CI pipeline).
We do not run CI on branches, only PRs, so sadly PRs (and noise) have to be created before auto-merging.

Before I go with this, does this following configuration change illustrate the scenario above?

```diff
@ renovate.json:4 @
 {
-  "extends": ["config:base", ":rebaseStalePrs"]
+  "extends": ["config:base", ":rebaseStalePrs"],
+  "packageRules": [
+    {
+      "packagePatterns": ["^@types/"],
+      "automerge": true
+    }
+  ]
 }
```

Is it possible to restrict this to `devDependencies` packages only, in case we have some in prod `dependencies` for one reason or another, that we don't want to automerge?

Thanks!

**Comment by rarkins** [comment]
Yes, you can further restrict it with `depTypeList`:

```diff
@ renovate.json:4 @
 {
-  "extends": ["config:base", ":rebaseStalePrs"]
+  "extends": ["config:base", ":rebaseStalePrs"],
+  "packageRules": [
+    {
+      "depTypeList": ["devDependencies"],
+      "packagePatterns": ["^@types/"],
+      "automerge": true
+    }
+  ]
 }
```

The logic in the above is "and", i.e. must match devDependencies AND `@types/`

**Comment by astorije** [comment]
Awesome, thanks a lot @rarkins!
