### ISSUE TITLE
Renaming config file after onboarding

### ISSUE THREAD

**Issue by joelmukuthu** [renovatebot/config-help#117]
Hi,

I'd like to rename my config file from `renovate.json` to `.renovaterc.json` without acually making any config changes. Is it safe to do that with a single commit to the master branch without having to [reconfigure](https://renovatebot.com/docs/configure-renovate/)?

Many thanks,
Joel

**Comment by rarkins** [comment]
Yes, that's completely safe. Just rename it and commit it and everything should run exactly as it did previously.
