### ISSUE TITLE
Does Renovate support update Go_Repository?

### ISSUE THREAD

**Issue by lkumar-88** [renovatebot/config-help#118]
I have a Bazel workspace file which have go_repository instead of git_Repository and i need to check whether renovate support update of dependencies project whenever there is new commit or new tag in the dependencies repository...?

We require GO_Repository for gazelle to generate bazel build files for those repositories which doesn't have bazel build file.

go_repository(
        name = "com_github_bitly_go-nsq",
        importpath = "github.com/bitly/go-nsq",
        tag = "v1.0.7"
)

Will renovate support go_Repository like git_repository and http_archieve() as mentioned in the below link : 
https://renovatebot.com/docs/bazel/

**Comment by rarkins** [comment]
I think we can add this really easily because we already support go module lookups. Are your references mixed between GitHub ones and non-GitHub? Eg golang.org and gopkg.in?

**Comment by rarkins** [comment]
If you are using commits instead of tags for any, please provide an example here too.

**Comment by lkumar-88** [comment]
I am using both (Tag or commit) in Bazel WORKSPACE file, some go_repositories with tag mentioned as the example provided above and some with commit id as an example mentioned below :

go_repository(
   name = "com_github_google_uuid",
   importpath = "github.com/google/uuid",
   commit = "dec09d789f3dba190787f8b4454c7d3c936fed9e"
)

**Comment by lkumar-88** [comment]
@rarkins : Any update on this...?
Go_Repository is something needs to be update/change in Renovate code .. or can be done through other steps by us.

The Statements mentioned above is confusing : " I think we can add this really easily because we already support go module lookups.  "

like Renovate in bazel doesn't support Go_repository and also Renovate in Golang works with go.mod but it only works for Github dependencies as stated in the Renovate doc link ( https://renovatebot.com/docs/golang/ )

**Comment by rarkins** [comment]
It will need small changes to the bazel extract and update code blocks, cannot be some throufh config alone. But we already know how to do golang lookups so should be no extra lookup Code - just extract and update. 

Cc @kayoub5

**Comment by rarkins** [comment]
Closing this and will track it as a feature request here: https://github.com/renovatebot/renovate/issues/2733
