### ISSUE TITLE
How to override dockerfile fileMatch?

### ISSUE THREAD

**Issue by porridge** [renovatebot/config-help#119]
I added [this](https://github.com/porridge/dcos-commons/pull/1/files#diff-76e62915fba4048ac877a875e2e3b8d2R7) but [the log](https://renovatebot.com/dashboard#github/porridge/dcos-commons/26406724) still says `DEBUG: Using file match: (^|/)Dockerfile$ for manager dockerfile`. What am I doing wrong?

**Comment by rarkins** [comment]
Hi @porridge, that config *looks* to me to be correct, so maybe there's a bug. I'll try to reproduce it in a test repo and let you know what I find.

**Comment by rarkins** [comment]
Actually it's working as expected, because fileMatch *adds*/merges values and not replaces. Therefore it uses both:

```
{"msg":"Using file match: (^|/)Dockerfile$ for manager dockerfile","time":"2018-11-01T04:59:56.454Z"}
{"msg":"Using file match: (^|/)Dockerfile[^/]*$ for manager dockerfile","time":"2018-11-01T04:59:56.458Z"}
{"msg":"Matched 4 file(s) for manager dockerfile: Dockerfile, tools/Dockerfile, tools/kdc/Dockerfile, Dockerfile.base","time":"2018-11-01T04:59:56.459Z"}
```

Is this list not as expected? Any other files you were hoping to match/not-match with that regex?

**Comment by porridge** [comment]
What you pasted looks good, however:
* when I filed this issue, I the second line was not there. There was only the first line with the regex, and the last line had "Matched 3 file(s)".
* When I look at the log page now, it does not work, reload does not help:
```
Request URL: https://v1.renovateapi.com/github/repos/porridge/dcos-commons/jobs/26406724/logs
Request Method: GET
Status Code: 502 
```

**Comment by porridge** [comment]
Cool, looks like the problem was that the page which lists available logs was not refreshing, so I was always seeing a single log, thinking it is being replaced with the result of every job which ran.
Now I see plenty of logs and the latest one is as expected!
Thanks!

**Comment by rarkins** [comment]
Great. Sorry for any confusion and feel free to post any more questions! I am also considering whether to make your pattern the default for Dockerfile
