### ISSUE TITLE
python / pip support for "extras"

### ISSUE THREAD

**Issue by carlosfunk** [renovatebot/config-help#120]
Does python support for pip files handle extra requirements?  For example in one project I have Django set to also install argon2 and Celery to install Redis.  I haven't seen any PR's to upgrade Django or Celery despite there being newer versions...

For example in requirements.txt:

`Django[argon2]==2.0.8`
`celery[redis]==4.1.1`

**Comment by rarkins** [comment]
I think we don’t currently handle this extras syntax, but should be easy to add. I’ll close this help issue  and track it as a feature request in the main repo instead: https://github.com/renovatebot/renovate/issues/2720

**Comment by rarkins** [comment]
@carlosfunk this should now be working properly in the app. Can you confirm?

**Comment by carlosfunk** [comment]
@rarkins New version ran this morning and picked up the upgrade but unfortunately dropped the extra requirement...

```
-Django[argon2]==2.0.8
+Django==2.1.3
```
