### ISSUE TITLE
Config review

### ISSUE THREAD

**Issue by ScottRudiger** [renovatebot/config-help#124]
My goal for the config is to only update 2 packages `browserslist` and `caniuse-lite`.

```json
{
  "extends": [
    "config:base"
  ],
  "automerge": true,
  "major": {
    "automerge": false
  },
  "bumpVersion": "patch",
  "enabled": false,
  "packageRules": [
    {
      "packageNames": ["browserslist", "caniuse-lite"],
      "schedule": ["after 10pm on friday"],
      "enabled": true
    }
  ],
  "prCreation": "not-pending",
  "rangeStrategy": "bump",
  "timezone": "America/Los_Angeles"
}
```

However, the onboarding PR seems to not have been updated after changing the config file:

![screen shot 2018-11-24 at 9 12 33 pm](https://user-images.githubusercontent.com/26824724/48975789-cbe86600-f02d-11e8-95f6-76ac39cfdc89.png)

In case it helps to see the commit history: https://github.com/AsyncAF/AsyncAF/pull/133

**Comment by rarkins** [comment]
What's happening is that the `"enabled": false` causes Renovate to abort the repo and so the Onboarding PR you have is not getting updated. From the logs:

```
 INFO: Repository is disabled - skipping (repository=renovate-tests/AsyncAF)
```

(FYI you can view logs in future from https://renovatebot.com/dashboard)

Check out the refactor I did in to use a package rule to achieve the same: https://github.com/renovate-tests/AsyncAF/pull/1

Additional point: after 10pm on a Friday is unlikely to be enough time to (a) create the branch, (b) wait until branch is not pending and then create the PR, (c) automerge it. Typically Renovate will run once per hour on repos unless it detects an event like you changing your config. You might also want to consider doing a branch automerge too, if you're aiming for as little noise as possible.

**Comment by ScottRudiger** [comment]
Thanks! I was reading through the logs while you commented. Everything appears to be in order after taking your suggestions into account.

**Comment by ScottRudiger** [comment]
@rarkins Is there a way to have renovate add a tag when using `"bumpVersion": "patch"`? (e.g., renovate bumps the version from `1.0.0` to `1.0.1` with the same semantics as `npm version patch` resulting in a `1.0.1` commit tagged as `latest`).

I looked in the [configuration options](https://renovatebot.com/docs/configuration-options/) but didn't see what I was looking for.

**Comment by rarkins** [comment]
@ScottRudiger there is not currently. Can you create a feature request in the main repo, detailing your exact workflow? e.g. do you want *branches* tagged, or tagging after automerge, etc.
