### ISSUE TITLE
How to lock Docker version while allowing digest updates?

### ISSUE THREAD

**Issue by mastermatt** [renovatebot/config-help#125]
MariaDB is currently on 10.4, but I need to lock the version in one of my apps to 10.0 to match what is in production. Simply closing the update PR and having Renovate ignore the dep isn't right because the MariaDB 10.0 image is occasionally updated and gets a new SHA without a version bump. 

What's the right way to config this?

**Comment by rarkins** [comment]
You would do it using a packageRule like:

```
{
  "packageNames": ["mariadb"],
  "depTypeList": ["patch", "minor", "major"],
  "enabled": false
}
```

This should filter out any patch/minor/major updates that are found, but leave in digest ones.

Another possibility that is maybe a little more obvious to others who read it, but I haven't tried it out with Docker, is to use [allowedVersions](https://renovatebot.com/docs/configuration-options/#allowedversions) instead.

Something like this:
```
{
  "packageNames": ["mariadb"],
  "allowedVersions": "10.0",
}
```

**Comment by mastermatt** [comment]
Thanks. I'll play around with `allowedVersions` and see how it goes.
