### ISSUE TITLE
Is there a way to expand config to full options?

### ISSUE THREAD

**Issue by bjeanes** [renovatebot/config-help#128]
I am trying to understand exactly what rules are in effect. Is there a way to expand the presets into an "effective" config file so that I can tweak it or use it as a basis for a more explicit config file?

The reason I want to do this is that I don't see `docker-compose.yml` dependencies being updated even though `Dockerfile` ones are and the docs imply both are enabled. Maybe it isn't finding the location of those files but I'm not sure without seeing the full config exactly what it would otherwise be looking for.

I tried `renovate-config-validator` mentioned in https://github.com/renovatebot/config-help/issues/91#issuecomment-419611943 but it doesn't seem to have any obvious way to view the expanded config file (and no `-h` or `--help`, just validate that it is correct.

**Comment by rarkins** [comment]
The rule impacting you is actually part of the default Renovate behaviour, not any preset. Major updates for Docker are disabled by default so you need to opt in to them: https://github.com/renovatebot/renovate/blob/e726b47648af0e3256cd4b647a957c680df09934/lib/config/definitions.js#L1110

**Comment by bjeanes** [comment]
Nonetheless, that would likely have been clear if it were possible to print out the effective config file to make it eventually clear what options set and which took precedence in any given circumstance. What do you think?

**Comment by bjeanes** [comment]
It might be good to set `skipReason` (at least i think that's the name from memory) in the logs in that case. That also would have clarified it

**Comment by rarkins** [comment]
The reason we don't do it is because most "full" configs would be huge once you pull in all the monorepo rules, and we don't want to log it every time. Maybe we can add a dashboard debugging page that lets you fully expand a config there.

Right now `skipReason` is internal only and not exposed to config.

**Comment by bjeanes** [comment]
No bht skipReason is ont logs so setting it to "disabled by current config"
would be nice.

I'm not suggesting logging the full config necessarily, just some way to
view it. `renovate-config-validator --debug` for instance...

**Comment by rarkins** [comment]
I've now added this as part of the default renovate options, e.g. you can run the following:

```
renovate --print-config bjeanes/foo
```

And it will include a dump of the full, resolved config. Available in `renovate@13.46.0`

**Comment by bjeanes** [comment]
Is there anyway to run `renovate --print-config` against my local working copy? The need for this (for me) is to iterate on the actual config options and understand them, but the above seems to want a GitHub token and to fetch the committed version.

**Comment by rarkins** [comment]
I don’t think that’s possible right now. Set up a dummy repo with nothing but a Renovate.json?
