### ISSUE TITLE
unpkg.com

### ISSUE THREAD

**Issue by trendzetter** [renovatebot/config-help#129]
I am getting this error in the browser console when trying to log on to the dashboard (https://renovatebot.com/dashboard)

Failed to load resource: the server responded with a status of 503 ()
dashboard.js:3 Uncaught ReferenceError: netlify is not defined

unpkg.com is failing it seems.

**Comment by trendzetter** [comment]
I just clicked submit, did another refresh and now it's up.

**Comment by rarkins** [comment]
Thanks for notifying us. I'll take a look and consider self-hosting the JS if necessary.

**Comment by trendzetter** [comment]
thanks for your response, that was quick. just trying things out. I will keep you posted.

**Comment by rarkins** [comment]
unpkg was definitely slow - took me 26s to load that JS file when I tried it. I've moved that library to be self-hosted now and redeployed. Thanks again for the heads-up
