### ISSUE TITLE
Not getting pull requests

### ISSUE THREAD

**Issue by danielrozenberg** [renovatebot/config-help#131]
I activated the forking-renovate app on my repo, received the config PR (https://github.com/ampproject/amp-github-apps/pull/12) and approved it, and since then haven't seen any PRs.

I checked the dashboard, but I see no repos listed there at all. Any ideas where I took a wrong turn?

**Comment by rarkins** [comment]
@danielrozenberg 	thanks for getting in touch and sorry for the inconvenience. I'm pretty sure you did nothing wrong. It seems like the webhook telling Renovate's backend about the merged onboarding PR got lost, *and* for some reason the nightly sweep to check onboarding accounts also failed. I gave the ampproject org a manual run just now and it looks like it's creating PRs fine now: https://github.com/ampproject/amp-github-apps/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

FYI it's default is to limit to 2 per hour so as not to overload build systems after onboarding.

**Comment by danielrozenberg** [comment]
Thanks! Looks like it's working now :)
