### ISSUE TITLE
Renovate self hosted configuration branch.

### ISSUE THREAD

**Issue by meersschautarnaud** [renovatebot/config-help#133]
At the moment I'm using a self hosted configuration in Azure Devops to update the nuget packages, but the bot is running on master. Is there any way to set the branch in a self hosted configuration?

**Comment by rarkins** [comment]
Check out the "baseBranches" configuration option in the docs, e.g. `"baseBranches": ["dev"]`

**Comment by meersschautarnaud** [comment]
I created a renovate.json file with the following line, but still the same problem.
`{
  "baseBranches": ["development"]
}`

Is it correct that I created this file in the same repository as the self hosted configuration or should I create it in the repository where I run renovate?

**Comment by rarkins** [comment]
This configuration should be in the `renovate.json` of the repository you wish to have renovated. i.e. the target repo.
