### ISSUE TITLE
[Gradle] Allow only patch updates

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/config-help#134]
I'm testing out renovate, and would like to enable only patch updates right now. Unfortunately, I can't get it to respect these settings, and it's even opening PRs for unstable versions.

I've created a sample repo to reproduce the issue [`renovate-gradle-test`](https://github.com/JamieMagee/renovate-gradle-test). My [`renovate.json`](https://github.com/JamieMagee/renovate-gradle-test/blob/master/renovate.json) is:

```json
{
  "extends": [
    "config:base",
    ":prHourlyLimitNone"
  ],
  "minor": {
    "enabled": false
  },
  "major": {
    "enabled": false
  },
  "gradle": {
    "enabled": true
  },
  "separateMinorPatch": true
}
```
and the relevant part of my [`build.gradle`](https://github.com/JamieMagee/renovate-gradle-test/blob/master/build.gradle) is:

```groovy
dependencies {
    implementation 'com.google.code.gson:gson:2.6.1' // renovate should bump this to 2.6.2 even though 2.8.x is released
    implementation 'org.slf4j:slf4j-api:1.7.25' // renovate should not bump this (1.8 doesn't have a stable release)

    // Use JUnit test framework
    testImplementation 'junit:junit:4.12'
}
```

After running renovate it made [3 PRs](https://github.com/JamieMagee/renovate-gradle-test/pulls), bumping one dependency by a minor version, and the other 2 to unstable versions.

Is there some config that I'm missing, or is this a bug?

**Comment by rarkins** [comment]
@JamieMagee unfortunately this is a known limitation/bug. We are currently using a third party Gradle update tool that defaults to updating everything, and in the middle of rewriting it so we do it natively/internally and have complete control of major/minor/patch and stable/unstable like you expect in other languages.

Cc @corecanarias

**Comment by corecanarias** [comment]
I've already started the pr that will fix that issue https://github.com/renovatebot/renovate/pull/2973/ . When this get merged we will be able to use the renovate configuration to decide which versions do we want to update.

But of course taking in mind that many java libraries doesn't follow the semVer format and in those cases we would need to tune the current solution.

**Comment by JamieMagee** [comment]
Thanks for replying so quickly. Is there anything I can do to help with this work?

@corecanarias Some of the most common libraries that break that convention are:

- spring appends `.RELEASE` to every published version (`5.1.3.RELEASE`)
- guava appends `-jre` and `-android` to each release, depending on the intended use (`27.0.1-jre` & `27.0.1-android`)
- apache libraries omit the patch version for `x.x.0` releases (`3.8` instead of `3.8.0`)

**Comment by rarkins** [comment]
Our lib/versioning/loose should mostly handle this. We might want to wrap it as a new lib/versioning/gradle though (or should it be lib/versioning/Maven ?) that includes any specifics that we think are Gradle-only. The main challenge is to differentiate between suffixes that mean “unstable” (eg 1.0.0-beta.1) vs stable ones like 1.0.0.release or 1.0.0-jre

**Comment by JamieMagee** [comment]
Yeah, I think something gradle/maven specific would be a good idea. I haven't seen the `1.0.0.RELEASE` or `1.0.0-jre` style anywhere else. I'm sure there are also some other gradle/maven specific gotchas, but those were just the ones that sprung to mind. Looking at the [most popular maven libraries](https://mvnrepository.com/popular) would probably be a good place to start.

**Comment by corecanarias** [comment]
@rarkins We could see how the current loose version works. If we need this specifics, I would say it would be lib/versioning/java because the repositories we are currently supporting are the maven ones, but any other repository will still have the same versioning

**Comment by rarkins** [comment]
OK. I will close this issue because we can't solve it with config, and make sure we have the right open ones in the main repo.
