### ISSUE TITLE
Repository not being onboarded

### ISSUE THREAD

**Issue by estahn** [renovatebot/config-help#137]
We have onboarded a single public repository a while back and decided to add another public repo to the permission scope. We haven’t received an onboading ticket after doing so. I have uninstalled and installed renovatebot again this time giving permission to all repos. Still no onboarding ticket.

Repo: hipages/inceptum

**Comment by rarkins** [comment]
@estahn sorry for the delay, please expect it within the next hour. Let me know if there's any other repos affected

**Comment by estahn** [comment]
@rarkins Thanks for your quick response. I wondered if it’s just a queueing issue. Anyways, I’ll report if I have problems with our private repos (different org).

**Comment by rarkins** [comment]
Looks like it's there now: https://github.com/hipages/inceptum/pull/136

Normally you should see them immediately though, so feel free to ping me in future again if it ever seems slow. I needed to do some unscheduled maintenance just now, which slowed the queue to an almost halt, should be coming back now.
