### ISSUE TITLE
Same branch re-created every hour for Gradle but PR not created

### ISSUE THREAD

**Issue by teppeis** [renovatebot/config-help#139]
Branch to update gradle wrapper version from v4.10.2 to v4.10.3 is re-created every hour and the PR is not created.

- https://github.com/teppeis/clutz-npm/tree/renovate/gradle-4.x
- https://circleci.com/gh/teppeis/clutz-npm/tree/renovate%2Fgradle-4.x
- https://renovatebot.com/dashboard#github/teppeis/clutz-npm

Same for [gradle-5.x branch](https://github.com/teppeis/clutz-npm/blob/renovate/gradle-5.x/renovate.json)

My config is something wrong?

**Comment by rarkins** [comment]
This is actually a design fault/oversight with how Renovate is trying to be smart and *insert* the `distributionSha256Sum`. What happens is that every time it runs, it thinks it needs to update the existing branch (trying to add a second `distributionSha256Sum` line) and then rebases itself which then actually results in only one of those lines again. But the end result is, it keeps thinking it needs to rebase every time and never thinks it's ready to raise the PR. I'm going to remove the "insert distributionSha256Sum" capability for now to overcome this.

**Comment by teppeis** [comment]
thanks!
