### ISSUE TITLE
Does automerge support just using automergeComment?

### ISSUE THREAD

**Issue by Aghassi** [renovatebot/config-help#145]
```
"renovate-config": {
    "default": {
      "extends": [
        ":separateMajorReleases",
        ":combinePatchMinorReleases",
        ":ignoreUnstable",
        ":prImmediately",
        ":renovatePrefix",
        ":updateNotScheduled",
        ":ignoreModulesAndTests",
        ":maintainLockFilesDisabled",
        ":autodetectPinVersions",
        ":prConcurrentLimit20",
        "group:monorepos",
        "helpers:disableTypesNodeMajor",
        "helpers:oddIsUnstablePackages",
        ":automergeDigest",
        ":automergePatch",
        ":pinAllExceptPeerDependencies",
        ":semanticPrefixFixDepsChoreOthers"
      ],
      "semanticCommits": true,
      "respectLatest": true,
      "updateLockFiles": true,
      "prHourlyLimit": 0,
      "prConcurrentLimit": 0,
      "labels": [
        "dependency-update"
      ],
      "patch": {
        "labels": [
          "patch",
          "automerge",
          "dependency-update"
        ]
      },
      "minor": {
        "labels": [
          "minor",
          "dependency-update"
        ],
        "automerge": false
      },
      "major": {
        "labels": [
          "major",
          "dependency-update"
        ],
        "automerge": false
      },
      "digest": {
        "labels": [
          "digest",
          "automerge",
          "dependency-update"
        ]
      },
      "packageRules": [
        {
          "automerge": true,
          "depTypeList": [
            "devDependencies"
          ]
        }
      ]
    }
  },
```

Is it possible to combine automerge with `automergeComment` stand alone, and not combined? This link seems to state it only works with an `automergeType` https://renovatebot.com/docs/configuration-options/#automergecomment.

**Comment by Aghassi** [comment]
@rarkins I didn't go through the template on accident for this one, so you may not get auto tagged.

**Comment by rarkins** [comment]
`automergeComment` is only used once `automergeType` is set to `"pr-comment"`. It's for cases where you don't want Renovate to automerge itself, you just want it to leave a comment saying it's ok to automerge and another bot (usually [bors-ng](https://github.com/bors-ng/bors-ng)) manages merging.

**Comment by Aghassi** [comment]
@rarkins That's unfortunate. It would be nice to have the ability to say, on something that shouldn't be automerge (like a minor), post a comment like "merge when checks pass" or something and have it automerge for you.

**Comment by rarkins** [comment]
@Aghassi I'm confused by these two statements together:

> on something that shouldn't be automerge

and then

> and have it automerge for you

Can you describe what you mean?

If instead of automerging, you want Renovate to post a comment to the PR when tests pass, you can do that. It's still considered "automerge=true" but of type "automergeType=pr-comment".

**Comment by Aghassi** [comment]
Sorry let me clarify.

So let's say I get a `minor` change as a PR to a non critical dependency. My config makes it so that minors are not automerge. I'd like to know if there is a way for me to post to the pr and say "Renovate, merge when ready". The next time renovate runs, it then merges that PR for me.

Granted, the more I think about this the more it seems like I could just merge it. If I have a number of minors that aren't very impactful (say ESLint plugins and aws-sdk), I could also just bulk label them in GitHub as "ready to merge" and let renovate merge them on my behalf next run around.

That's more my question, I hope that is clearer.

**Comment by rarkins** [comment]
Yes, I understand the question now.

The challenge with enabling "automerge by command" or label is that we need to check carefully that the person trying to do it has the authority to commit to master themselves, then handle the error cases, etc. I'm not sure GitHub tells us which person applied the label, for example. It can no doubt be done, but is not supported right now due to lack of full specifications.
