### ISSUE TITLE
Resolving private libraries for golang

### ISSUE THREAD

**Issue by CodeHex** [renovatebot/config-help#148]
Hi, renovate works perfectly for our go apps if there are no dependencies on private repos. This includes updating private repos themselves. But when we get a renovate PR for an app that has a dependency on a private repo, the `go.mod` file is updated correctly but there is always a problem with the corresponding `go.sum` (Lock file problem). Looking at the docker output, all the private repos are reporting `unknown revision`, (we're using the GithubApp btw)

I was wondering if you had any recommendations for getting past this problem. Or if there is any configuration options available to allow this `go.sum` to be updated correctly using the github authentication already provided to access private repos. Thanks!

**Comment by rarkins** [comment]
A couple of questions:

1. Are the private repos part of the same GitHub account/org?
2. Is Renovate enabled on those repos already, or can it be?

**Comment by CodeHex** [comment]
1. Yes, the private repos are in the same Github organisation. We have renovate running on them separately as well, which is working great.
2. Yes, Renovate is currently updating these private repos without issue (as they don't have any private dependencies themselves)

**Comment by rarkins** [comment]
In that case it should be achievable - just using same token we already have for the working repo - but maybe the code is missing. I'll check it out.

**Comment by rarkins** [comment]
I've added a feature request here that you can subscribe to, to be informed when it's updated or solved: https://github.com/renovatebot/renovate/issues/3143
