### ISSUE TITLE
[Question] Package rule for release notes for Docker images

### ISSUE THREAD

**Issue by mxey** [renovatebot/config-help#151]
### Which Renovate are you using? CLI, App, or Pro

Renovate CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Gitlab

### What is your question?

I want to link to releases of Gitlab repositories that are the source of Docker images.

```js
        {
            "packagePatterns": ["^docker-registry\\.example\\.com/"],
            "prBodyDefinitions": {
                "Release Notes": "[Release Notes](https://gitlab.example.com/{{{depName}}}/releases)"
            },
        },
```

`depName` includes the registry, so this link will not work. Is there another field I can use in the template, or are there template function I can use to strip the registry from `depName`?

**Comment by rarkins** [comment]
@mxey 	do I understand correctly that you want a way to get the Docker repository name without the registry included? i.e. like the old `depName` was?

**Comment by rarkins** [comment]
@mxey FYI I'm considering if I can revert the change this week

**Comment by mxey** [comment]
@rarkins I think the change makes sense, TBH, because that’s how the dependencies are referenced in Dockerfile and so on. You should keep it, just add another field that contains the separate parts.

**Comment by rarkins** [comment]
This needs to be moved into the main repo as it requires a code change rather than config change

**Comment by rarkins** [comment]
@mxey 	I think this commit should help you once it's released: https://github.com/renovatebot/renovate/commit/1d9167b081476fa820095ece5ec2731d74a5a73c

Instead of `{{{depName}}}` can you try `{{{dockerRepository}}}`?

**Comment by mxey** [comment]
> Instead of `{{{depName}}}` can you try `{{{dockerRepository}}}`?

Tried this, it's apparently empty

**Comment by rarkins** [comment]
Sorry, I think I know why. We do a custom field mapping at one point, instead of just copying over every field. Some datasources returned too many additional fields so that's the reason. I'll work out an elegant way around it.

**Comment by mxey** [comment]
@rarkins Apparently it's still empty, at least my MRs did not change.

**Comment by mxey** [comment]
Works now! 👍
