### ISSUE TITLE
Automerge for protected master branches

### ISSUE THREAD

**Issue by sidharthachatterjee** [renovatebot/config-help#152]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub 

### Have you checked the logs? Don't forget to include them if relevant

Not relevant

### What is your question?

The documentation at https://renovatebot.com/docs/configuration-options/#automerge mentions
> Warning: GitHub currently has a bug where automerge won't work if a GitHub Organization has protected their master branch, and there is no way to configure around this. Hence, automerging will try and fail in such situations. This doc will be updated once that bug/limitation is fixed by GitHub.

Do we have an update or ETA on this? Protecting the `master` branch is fairly standard and this seems like a major limitation. 😞 I understand that it's a GitHub issue and probably not in your control.

**Comment by rarkins** [comment]
@sidharthachatterjee what type of branch protection do you have enabled?

**Comment by sidharthachatterjee** [comment]
@rarkins This is on https://github.com/gatsbyjs/gatsby/

![untitled](https://user-images.githubusercontent.com/7701981/52051990-30b6c400-257b-11e9-8c81-c6f916f349d5.jpg)

**Comment by sidharthachatterjee** [comment]
Thank you for your detailed review of our rules, @rarkins. We really appreciate this. 

> Out of curiosity, if we added the option for you to add @renovate-bot as someone allowed to push to master, would you use it? i.e. would the convenience advantage of letting the bot automerge be worth the "security risk" of adding a third party collaborator to the project?

We'd probably lean towards _not_ adding a third party collaborator to merge. At least not to core. This would make sense to our lower risk packages like our official starters (which we're exclusively setting up Renovate to test waters) but it's impossible to set granular user privileges for merge on a monorepo.

**Comment by rarkins** [comment]
@sidharthachatterjee I understand your position. I hold the same opinion and that's why I haven't prioritised adding that capability yet, although ultimately it's whatever the end users want that drive things. I'll close this issue as I think we've reached the end of this topic, feel free to open more. Thanks for checking out Renovate for Gatsby!

**Comment by sidharthachatterjee** [comment]
We now have Renovate running on Gatsby for official starters! Thank you for all your help, @rarkins

**Comment by rarkins** [comment]
That’s awesome! You’re welcome
