### ISSUE TITLE
Change to prHourlyLimit in renovate.json does not seem to take effect

### ISSUE THREAD

**Issue by sidharthachatterjee** [renovatebot/config-help#153]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Does not seem relevant

### What is your question?

`renovate.json` previouly had `prHourlyLimit` set to 2 and I removed the key in a later commit in https://github.com/sidharthachatterjee/gatsby/commit/b21c19c30b7f8a406f3b486c4754d101a685e551

I still seem to only be receiving 2 PRs per hour. Maybe there's an invalidation issue here?

**Comment by rarkins** [comment]
The “config:base” preset includes a limit of 2 per hour so that’s why you’re seeing it. Add `”prHourlyLimit”: 0` tomyour config to disable the limit. 

BTW it also includes a limit of 20 concurrent PRs

**Comment by sidharthachatterjee** [comment]
That makes sense. Thank you so much @rarkins
