### ISSUE TITLE
yarn.lock pinning

### ISSUE THREAD

**Issue by darkbasic** [renovatebot/config-help#154]
Hi,
For some time I was using `npm install --exact` in order to pin dependencies in package.json. Unfortunately that won't pin sub dependencies, thus I always ended up with broken dependencies on the long term.
That's why I started publishing `yarn.lock` to the git repo: `yarn.lock` will pin all the dependencies, including sub-dependencies.
If I delete `node_modules` and in `package.json` I have `"ts-node": "^7.0.0"`, while in `yarn.lock` I have
```
ts-node@^7.0.0:
  version "7.0.1"
```
then a `yarn install` won't install `8.0.0` (which is the latest and greatest) and not even `7.0.5` (which is the latest version accepted by `package.json`): instead it will install `7.0.1` which is the version pinned by `yarn.lock`.

If I use `yarn.lock` then it's not necessary anymore to pin packages in `package.json`, because they are already pinned. To see if there are updates available I can simply use `yarn outdated`, which will show the latest version accepted by `package.json` (`~` and `^`) as well as the latest and greatest available.
To update a dep is just a matter of using `yarn upgrade` (if you want to obey `package.json`) or `yarn add` (if you don't).
But why I don't want to do pinning in `package.json`? What is the advantage? If I don't pin packages in `package.json` I can suggest the user which upgrades would be considered safe and which won't.
For example I could suggest to not upgrade typescript over `~3.2.0` because I know that `3.3.x` will break Angular.
Of course I could use Continuous Integration to check if typescript 3.3 is compatible or not, but sometimes breakage is subtle and it's safer to stay on the safe side.

My question is: is renovate capable of working without pinning dependencies in `package.json`?
We could instruct Renovate to automatically update dependencies which fit `package.json` (if they pass Continuous Integration of course) while asking for manual intervention before merging PRs which don't.
In order to do so, if `package.json` asks for `"express": "~4.16.1"` then Renovate should update `yarn.lock` to use version `4.16.4`, but it shouldn't update `package.json`.
On the contrary if we merge a renovate PR which updates `express` to `5.0.0` it will have to update `package.json` to fit the version we installed.

**Comment by rarkins** [comment]
What you're probably looking for is the setting `"rangeStrategy": "lockfile-update"` but beware that it's a new feature and has a bug: https://github.com/renovatebot/renovate/issues/3123

I recommend subscribe to that and they switch to using it once it's reliable.
