### ISSUE TITLE
[Question] How can I get "lock file maintenance" only once a month?

### ISSUE THREAD

**Issue by teppeis** [renovatebot/config-help#156]
### Which Renovate are you using? CLI, App, or Pro

GitHub App

### What is your question?

Today, lock file maintenance runs 4 times for 9 hours.

```json
      "lockFileMaintenance": {
        "enabled": true,
        "schedule": [
          "before 9am on the first day of the month"
        ]
      },
```

https://github.com/teppeis/multimaps/pulls?q=is%3Apr+is%3Aclosed
https://renovatebot.com/dashboard#github/teppeis/multimaps

OK, I understand that 9 hours is too long.
So I should change the schedule to "before 1am" or "before 2am"? 1 hour is too short?
Or can I get another solution like `onlyOnceInSchedule`?

**Comment by rarkins** [comment]
@teppeis right now there's no way I can think of to make lockFileMaintenance run only once and never update. Narrowing the window reduces chances of multiples but also increases chances the bot might "miss" your repo during that hour.

We could maybe add a generic option like `rebaseAfterCreation` which if you set to `false` means that we never update a branch after it's been created, unless you manually rebase it. And such option could be useful for lockFileMaintenance.

Closing this issue, as unfortunately not solvable via config - feel free to raise a feature request.

**Comment by teppeis** [comment]
@rarkins thanks!
