### ISSUE TITLE
[Question] Why is Renovate updating to Django v2 despite "allowedVersions": "<2"?

### ISSUE THREAD

**Issue by nottrobin** [renovatebot/config-help#159]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

No - they're not there any more.

### What is your question?

Renovate filed [a PR to upgrade Django to v2](https://github.com/canonical-websites/developer.ubuntu.com/pull/406) even though [our `renovate.json` config](https://github.com/canonical-websites/developer.ubuntu.com/blob/renovate/django-2.x/renovate.json) states that we only want `"<2"`.

What did I do wrong?

``` json
  "packageRules": [
    {
      "managers": ["pip"],
      "packageNames": ["django"],
      "allowedVersions": "<2"
    },
```

**Comment by rarkins** [comment]
Change `pip` to `pip_requirements` and it will work
