### ISSUE TITLE
Run Renovate's Docker Image on specific repositories only

### ISSUE THREAD

**Issue by shirbr510** [renovatebot/config-help#161]
### Which Renovate are you using? CLI, App, or Pro
Dokcer 14.14 (via docker CLI)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab CE  11.7.5 

### Have you checked the logs? Don't forget to include them if relevant

Help Logs:
```
docker run renovate/renovate:latest --help | grep repositor                                                                                                             Usage: renovate [options] [repositories...]
  --include-forks [boolean]            Whether to process forked repositories or not. By default, all forked repositories are skipped over.
  --fork-mode [boolean]                Set to true to fork the source repository and create branches there instead
  --require-config [boolean]           Set to true if repositories must have a config to activate.
  --trust-level <string>               Set this to "high" if the bot should trust the repository owners/contents
  --platform <string>                  Platform type of repository
  --ignore-npmrc-file [boolean]        Whether to ignore any .npmrc file found in repository
  --autodiscover [boolean]             Autodiscover all repositories
```

Actual Run:
```
docker run renovate/renovate:latest --platform=gitlab --token=<my-token> --endpoint=<my-hosted-gitlab> --update-lock-files --require-config --dry-run <my-repo-url>

 WARN: No repositories found - did you want to run with flag --autodiscover?
 INFO: Renovate finished
```

### What is your question?
I am trying to run renovate on specific Repositories only, and it seems to fail.
I have read on the self-hosted documentation website that I should be able to add a `repositories` flag, but this seems to not find any repo.

I was trying to do the same by specifying the repositories at the end of the command and again, same result.

autodiscover is working, but this is not what I desire.

**Comment by rarkins** [comment]
Run it with `=true` for boolean ones, e.g.:

```
docker run renovate/renovate:latest --platform=gitlab --token=<my-token> --endpoint=<my-hosted-gitlab> --dry-run=true abc/def
```

There's no need for `--require-config` or `--update-lock-files` so I removed them.

**Comment by shirbr510** [comment]
wow, I'm feeling so silly 😓 

thank you very much 😅
