### ISSUE TITLE
How to configure requiredStatusChecks

### ISSUE THREAD

**Issue by sliverc** [renovatebot/config-help#163]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

My [configuration](https://github.com/projectcaluma/renovate-config/blob/master/renovate.json) looks like the following:

```json

{
  "extends": ["config:base"],
  "pip_requirements": {
    "fileMatch": ["requirements.*txt$"],
    "packageRules": [
      {
        "packageNames": ["django"],
        "allowedVersions": "<1.12"
      }
    ]
  },
  "docker": {
    "packageRules": [
      {
        "packageNames": ["python"],
        "allowedVersions": "3.6"
      },
      {
        "packageNames": ["postgres"],
        "allowedVersions": "9.6-alpine"
      }
    ],
    "pinDigests": true,
    "automergeType": "branch",
    "automerge": true
  }
}
```

What I would like to do is to automerge docker digest but only if all required Github Checks pass. As I understand when `requiredStatusChecks` is not configured automerging won't work. But it is unclear what I have to add into the list of checks if I want to automerge only if GitHub required checks or at least just Travis passes?

**Comment by rarkins** [comment]
Renovate's default behaviour is that it only automerges once a branch goes "green" (tests passed). You don't need to configure `requiredStatusChecks`.

If Renovate creates a branch and then there are no tests run, then GitHub reports it as "pending" forever. This can happen if either you have no tests at all, or if your tests on Travis only run for Pull Requests, not branches.

If there are tests run, and they pass, then Renovate will automerge. 

Can you describe what behaviour that you're seeing so far, or what log messages that make you concerned?

**Comment by sliverc** [comment]
That's what I expected it to behave but somehow might have misread following log messages:
```
DEBUG: branch status check result(dependencies=["projectcaluma/caluma"], branch="renovate/docker-projectcaluma-caluma-latest")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(dependencies=["projectcaluma/caluma"], branch="renovate/docker-projectcaluma-caluma-latest")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
```
that required check runs need to be configured.

When re-evaluating it seems the error was that either master changed or the docker image digest, renovate each time rebased the digest update branch and CI never got finished so Renovate could never automerge. If there is enough time in between it works (no changes for longer than 1 hour).

Hence, question got resolved. Thanks for your feedback.

**Comment by rarkins** [comment]
Thanks for sending your update. 

You may see log messages because we verify both "status checks" as well as "check runs", which are two different ways to report test results in GitHub. 

And you're right that if the base branch keeps updating more often than Renovate runs then it won't do the automerge because we always keep automerged branches up to date. It only merges if (a) the branch is up to date with master, and (b) the branch has passed tests
