### ISSUE TITLE
[Question] How to force existing any-version dependencies to pin?

### ISSUE THREAD

**Issue by Arcanemagus** [renovatebot/config-help#167]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

DEBUG: packageFiles with updates
```json
{
  "config": {
    "npm": [
      {
        "packageFile": "package.json",
        "manager": "npm",
        "deps": [
          {
            "depType": "dependencies",
            "depName": "bailey",
            "currentValue": "*",
            "datasource": "npm",
            "skipReason": "any-version",
            "prettyDepType": "dependency",
            "updates": []
          }
        ],
      }
    ]
  }
}
```

[Full logs](https://renovatebot.com/dashboard#github/AtomLinter/linter-bailey/45958773)

### What is your question?

When [configuring Renovate](https://github.com/AtomLinter/linter-bailey/pull/9) I specified a `rangeStrategy` of `pin`, however the above dependency wasn't pinned because the current value isn't actually a range, it simply was requesting _any_ version.

Is there a way to force **all** dependencies to be pinned? I caught this manually because it was such a small `package.json`, but it would be nice if there was a way to do this automatically in case I don't catch it next time.

**Comment by rarkins** [comment]
There’s not any way to do it currently. When I originally wrote the logic I thought that * was a special case that must be there for a reason and best not to change it. Until now every case I’ve seen backs this up, but if you want to raise a feature request in the main repo then I’m open to the idea. 

Closing this now as unfortunately there’s no config that can achieve it.

**Comment by Arcanemagus** [comment]
It's likely that's probably valid for where it's being used. The repo in question should never have been using `*` in the first place 😆.
