### ISSUE TITLE
[Question] Update to release candidates

### ISSUE THREAD

**Issue by nicksnyder** [renovatebot/config-help#168]
### Which Renovate are you using? CLI, App, or Pro

App.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub.

### Have you checked the logs? Don't forget to include them if relevant

https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph/46682218

### What is your question?

I would like our Docker tags to update to release candidates (e.g. `3.0.1` -> `3.1.0-rc.3`). I tried setting `"ignoreUnstable": false` but that didn't seem to work (https://github.com/sourcegraph/deploy-sourcegraph/pull/193/files).

I will try setting [unstablePattern](https://renovatebot.com/docs/configuration-options/#unstablepattern) next, but is there a way I can iterate on this quicker than 1 try per hour?

The readme implies that I can run renovate on the command line, but I didn't find instructions how to do so.

**Comment by nicksnyder** [comment]
I tried setting unstablePattern, but didn't find much documentation on how to use it. My naive attempt didn't work:
https://github.com/sourcegraph/deploy-sourcegraph/pull/195

**Comment by rarkins** [comment]
@nicksnyder I think it might work if you configure `versionScheme=semver` in a packageRule, along with `ignoreUnstable`. By default in Docker we assume anything after the hyphen is a compatibility suffix, such as `-alpine`. If you tell Renovate to use `semver` instead along with `ignoreUnstable=false` then it might work. I can test for you in a fork if you prefer to wait

**Comment by rarkins** [comment]
By the way you probably want to target this to one or more specific packages anyway, rather than put `ignoreUnstable=false` in your root config.

**Comment by rarkins** [comment]
Confirmed it works. Check out https://github.com/renovate-tests/docker-semver/pull/2 and the `renovate.json` inside

**Comment by rarkins** [comment]
PR: https://github.com/sourcegraph/deploy-sourcegraph/pull/197

**Comment by rarkins** [comment]
:boom: https://github.com/sourcegraph/deploy-sourcegraph/pull/198

**Comment by nicksnyder** [comment]
Thanks!
