### ISSUE TITLE
[Question] How to configure tag based updates with go_repository using commit hashes

### ISSUE THREAD

**Issue by prestonvanloon** [renovatebot/config-help#172]
### Which Renovate are you using? CLI, App, or Pro
app?

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What is your question?

Imagine we have 

```python
go_repository(
    name = "com_github_urfave_cli",
    importpath = "github.com/urfave/cli",
    commit = "cfb38830724cc34fedffe9a2a29fb54fa9169cd1",
)
```
And `cfb38830724cc34fedffe9a2a29fb54fa9169cd1` represents the tagged commit with tag `v1.20.0`. 

What I would like renovate to do is update the commit hash when a new version is released. 

What renovate is currently doing is replacing the `commit = "..."` with `tag = "v1.20.0"`. 

Our config is here: https://github.com/prysmaticlabs/prysm/blob/master/renovate.json.

My question: **how do I achieve the desired behavior?**

Thanks!

**Comment by rarkins** [comment]
I think we would need an enhancement to support this. I hadn't anticipated that there'd be a need to stay on commits after a dependency has adopted go modules. It actually took a bit of work to *suppress* the hash updates if we found a tag! 

Wouldn't this approach be a little risky in most cases to do so? I assume that Go module authors will starting committing like npm module authors now - i.e. commits to master between "releases" may actually be broken or incomplete, as they consider master branch to no longer be the public interface to the module - its tagged versions are.

**Comment by prestonvanloon** [comment]
Imagine a git log like this

```
MASTER
cfb388 <- tag v1, renovate update go_repository to cfb388
ab3fd3 -- normal commit, renovate do nothing
3ffd2a -- normal commit, renovate do nothing
ac3ddf <- tag v2, renovate update go_repository to ac3ddf
```

We don't want commits in between the release, but we want to pin the dependency to the commit hash rather than the tag name. We just had a major breakage where a series of 3rd party dependencies deleted all of their tags and renamed them. If we were pinning to a commit hash, then this wouldn't have been an issue.

**Comment by rarkins** [comment]
Thanks, that clarifies it more. I see why you want it as immutable as possible. 

However this then becomes a little more complex than I originally thought. It looks like you can't have both a tag and commit inside `go_repository`: https://github.com/bazelbuild/bazel-gazelle/blob/e1dfd3ef03eb8751a92374a249c2747a820faa1a/internal/go_repository.bzl#L34-L35

**Comment by rarkins** [comment]
How would you feel about an approach like this?

```
go_repository(
    name = "com_github_urfave_cli",
    importpath = "github.com/urfave/cli",
    commit = "cfb38830724cc34fedffe9a2a29fb54fa9169cd1", # v1.2.0
)
```

I've avoided using inline comments like this for Renovate until now, but I think it would make it easier for both Renovate as well as users like yourself if the commit includes a comment mentioning which version it maps to. Unless you have a better idea of how to correlate it, such as a custom field after `commit`.

**Comment by prestonvanloon** [comment]
@rarkins That's perfect! I really appreciate your effort here and quick solution. That would really solve our problem and provided more reliable builds.
