### ISSUE TITLE
Update Bazel git_repository to latest commit

### ISSUE THREAD

**Issue by alexeagle** [renovatebot/config-help#173]
https://github.com/renovatebot/renovate/blob/master/lib/manager/bazel/update.js#L18 suggests that either tag or commit should be renovated.

But the docs indicate only tag https://renovatebot.com/docs/bazel/#git_repository

I just set up for https://github.com/bazelbuild/rules_nodejs/ but I'm not getting a PR to update https://github.com/bazelbuild/rules_nodejs/blob/master/packages/karma/WORKSPACE#L34

(using forking-renovate)
thanks!

**Comment by rarkins** [comment]
@alexeagle I actually forget now, as bazel has a few permutations once you consider tags/releases/commits and http_archive as well as git_repository. I'll step through it in the debugger to verify.

**Comment by rarkins** [comment]
It wasn't supported, but essentially just needed one line of logic added. You should see a PR in your repo once the new feature reaches the app soon. Verified: https://github.com/renovate-tests/bazel4/pull/2

**Comment by rarkins** [comment]
PR: https://github.com/bazelbuild/rules_nodejs/pull/579

**Comment by alexeagle** [comment]
I don't know how you have the time to be so responsive and awesome every time we use Renovate ;)
