### ISSUE TITLE
[Question] How to force renovate to only target a specific package in a monorepo?

### ISSUE THREAD

**Issue by cowchimp** [renovatebot/config-help#174]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

Don't think it's relevant

### What is your question?

Hi.
I have a repo that is setup with a typical monorepo project managed with lerna.
The repo structure looks like this:

```bash
.
├── package.json
└── packages
    ├── alfa
    │   └── package.json
    ├── bravo
    │   └── package.json
    ├── charlie
    │   └── package.json
    └── delta
        └── package.json
```

How can I make renovate only send PRs to updates in the dependencies of `charlie`?
(in other words only send diffs on the contents of `packages/charlie/package.json`?)

The [FAQ](https://renovatebot.com/docs/faq/#selectively-enable-or-disable-renovate-for-specific-packagejson-files) mentions `packageFiles` but that parameter is not mentioned in https://renovatebot.com/docs/configuration-options.

Thank you.

**Comment by rarkins** [comment]
Try this:

``json
{
	"packageRules": [{
		"packagePatterns": ["*"],
		"enabled": false
	}, {
		"paths": ["packages/charlie/package.json"],
		"enabled": true
	}]
}
```

**Comment by cowchimp** [comment]
This works but I have a follow up question please:
how can i amend this to have renovate only suggest minor version updates? (and avoid major version update PRs)

I tried to amend your recommended configuration and added `updateTypes: ["minor"]`:


```diff
{ 
  "packageRules": [
    {
      "packagePatterns": ["*"],
      "enabled": false
    },
    {
      "paths": ["packages/yoshi/package.json"],
      "enabled": true,
+      "updateTypes": ["minor"]
    }
  ]
}
```

To my surprise this caused renovate to ignore all packages in `charlie`!
I debugged `lib/util/package-rules.js` and found this happens because in the second pass over the second `packageRule`, `updateTypes.length > 0` and `config.updateType == undefined`, and so in turn `!isMatch == true` and therefore `negativeMatch == true` which causes renovate to ignore the second `packageRule`.

**Comment by rarkins** [comment]
Try this:

```
{
	"packageRules": [{
		"packagePatterns": ["*"],
		"enabled": false
	}, {
		"paths": ["packages/charlie/package.json"],
		"enabled": true
	}, {
		"updateTypes": ["major"],
		"enabled": false
	}]
}
```

**Comment by cowchimp** [comment]
tried it. it works 👍 
thank you.

BTW, this also this works

```diff
{
  "enabledManagers": [
    "npm"
  ],
+  "major": {
+    "enabled": false
+  },
  "packageRules": [
    {
      "packagePatterns": [
        "*"
      ],
      "enabled": false
    },
    {
      "paths": [
        "packages/yoshi/package.json"
      ],
      "enabled": true
    }
  ]
}
```
