### ISSUE TITLE
Is there a way to configure the branch name for the onboarding PR?

### ISSUE THREAD

**Issue by tuckbick** [renovatebot/config-help#175]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github Enterprise

### Have you checked the logs? Don't forget to include them if relevant
Yep

### What is your question?
Is there a way to configure the branch name for the onboarding PR?

---

After a bit a research I see this here and it doesn't seem possible, even with setting `onboardingConfig`: https://github.com/renovatebot/renovate/blob/55257fff26f6400fd3448e74accfc815f8a08821/lib/config/app-strings.js#L13

But I want to make sure I'm not missing something. Any tips?

Thanks!

**Comment by rarkins** [comment]
Unfortunately no, it’s not possible in current code. It *used* to be configurable, but caused some problems so the feature was reverted. Please create a feature request in the main repo if it’s important to you, that way it’s not forgotten.
