### ISSUE TITLE
[Question] Renovate stopped suddenly after config change

### ISSUE THREAD

**Issue by ErisDS** [renovatebot/config-help#176]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yep, they just stopped appearing

https://renovatebot.com/dashboard#github/TryGhost/migrate
https://renovatebot.com/dashboard#github/TryGhost/Casper

### What is your question?

I started playing with renovate yesterday, trying to get the hang of the config and rules. It was all going swimmingly, and then suddenly it stopped running. 

I don't see any validation errors - and the logs show that branches were created and then deleted.

Can anyone shed some light on what I did wrong? Thanks!

**Comment by rarkins** [comment]
Renovate might have mistakenly marked the repo as disabled/dormant. I’ll give it a kick later today and see if I can figure out exactly why too. 

P.S. Ghost is great!

**Comment by ErisDS** [comment]
That would be fab. Thanks for the kind words, I have a feeling Renovate is going to be our new favourite toy - I can't believe how much it does! I'm working on rolling it out across a few side repos to get the hang of it, then I'll go for the big guns 😬

**Comment by rarkins** [comment]
I looked at the logs and can't see how/why the repo might have got disabled, as the last run ended successfully. Unfortunately the flight I'm on is blocking SSH and I realised I don't have an alternative way to bastion host in to AWS to manually force a job, so it will be about 5 hours or more until I can help get it started again.

**Comment by ErisDS** [comment]
@rarkins wow, really appreciate the transparency 👍 Not a problem, can focus on other repos/things and pick this up tomorrow.

**Comment by rarkins** [comment]
All working now. Actually, it seems that the account was just struggling to get priority in the job queue. When you *change* something in config, it reacts right away, but otherwise the hourly-scheduled jobs can sometimes get deferred a long time if there's a lack of capacity. I've added a manual override for TryGhost in addition to more capacity so shouldn't happen again.

**Comment by ErisDS** [comment]
@rarkins thanks so much for your help last week, and for the manual override 😳 

I'm back on getting renovate rolled out everywhere, so far even the noisy setup has been a delight compared to our previous experience with similar tools. The onboarding PR is 😍 

I have what I hope is a quick question about node and support policies. Which of these is correct?

```
travis": { "enabled": true },
"node": {
    "supportPolicy": ["lts_latest"]
},
```

```
"node": {
     travis": { "enabled": true },
    "supportPolicy": ["lts_latest"]
},
```

From the docs I got the idea that the travis thing was explicitly tied to supportPolicy and that belongs in node. I wasn't sure where the travis setting lives.

**Comment by rarkins** [comment]
`supportPolicy` can be defined at any level, but right now it's only ever looked at by the Travis function. It's definitely one of the things in Renovate I thought would be of more use/interest than it was, and I still think there's work to be done. Please be aware of #2443 and #3310

```
travis": { "enabled": true },
"node": {
    "supportPolicy": ["lts_latest"]
},
```

This one of yours will work, makes good logical sense to anyone reading it, and is "forwards compatible" for the day when it's used elsewhere, such as in engines or `.nvmrc` updates.
