### ISSUE TITLE
update CircleCI orb when available

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/config-help#177]
My current `renovate.json`:
```
{
  "commitMessagePrefix": "[renovate] ",
  "groupName": "all dependencies",
  "labels": [
    "renovate"
  ],
  "npmToken": "<redacted>",
  "packageRules": [
    {
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    }
  ],
  "rangeStrategy": "bump",
  "schedule": "before 3am on the first day of the month"
}
```

I want to:
- update `@dmx/` packages when available
- update other NPM packages only once a month (but if they're updated in a PR updating a `@dmx/` package, is OK)
- update CircleCI orb version when available
- update other docker dependencies (Node.js, MongoDB, Redis...) only once a month

My `.circleci/config.yml` starts with:
```
version: 2.1
orbs:
  dmx_base: dmx-io/base@1.10.127

```

And I want this `orbs.dmx_base` to be updated each time when a new version is published.

I guess I can type something like that in `renovate.json`:
```
  "docker": {
    "schedule": "at any time"
  },
```
But I don't know how to specify only orb to be published at any time. I cannot find such an example in https://renovatebot.com/docs/configuration-options/ .

**Comment by piotr-s-brainhub** [comment]
Btw. please let me know if the payments for the renovate app in `dmx-io` organization are configured properly.

Currently I see this:
<img width="1063" alt="screen shot 2019-03-06 at 20 37 33" src="https://user-images.githubusercontent.com/20856232/53909696-93a3eb00-4052-11e9-99a8-04cba0b31d11.png">

**Comment by rarkins** [comment]
You should be able to do it with one extra packageRule:

```
{
  "commitMessagePrefix": "[renovate] ",
  "groupName": "all dependencies",
  "labels": [
    "renovate"
  ],
  "npmToken": "<redacted>",
  "packageRules": [
    {
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    },
    {
      "managers": [
        "orb"
      ],
      "schedule": "at any time"
    }
  ],
  "rangeStrategy": "bump",
  "schedule": "before 3am on the first day of the month"
}
```

**Comment by piotr-s-brainhub** [comment]
@rarkins 

I tried this and renovate created an issue:


There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

File: `renovate.json`
Error type: The renovate configuration file contains some invalid settings
Message: `packageRules:
        You have included an unsupported manager in a package rule. Your list: orb. 
        Supported managers are: (ansible, bazel, buildkite, bundler, cargo, circleci, composer, docker-compose, dockerfile, github-actions, gitlabci, gomod, gradle, gradle-wrapper, kubernetes, maven, meteor, npm, nuget, nvm, pip_requirements, pip_setup, pipenv, terraform, travis).`

**Comment by rarkins** [comment]
Sorry! I mixed up manager and datasource there (orb is a datasource, not manager). For now, you'll need to replace `orb` with `circleci` in the rule I gave, although that will mean any non-orb Docker images will also get updated immediately too.

**Comment by piotr-s-brainhub** [comment]
@rarkins 

Thanks. Now it works. However it would be nice to provide a feature to specify config for only the orb.

**Comment by rarkins** [comment]
You can raise a feature request in the main repo to include `datasources` as a selector in `packageRules`

**Comment by piotr-s-brainhub** [comment]
@rarkins 

I created this https://github.com/renovatebot/renovate/issues/3359 feature request.
