### ISSUE TITLE
[Question] Processing multiple package.json files within the same repo

### ISSUE THREAD

**Issue by tanem** [renovatebot/config-help#179]
### Which Renovate are you using? CLI, App, or Pro

App.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub.

### Have you checked the logs? Don't forget to include them if relevant

Can include if asked, not sure they're relevant yet.

### What is your question?

I'm maintaining a few open source repos that contain examples built with Create React App. Each of those examples is a standalone app with it's own package.json file.

How can I get renovate to process those package.json files as well as the main repo package.json file?

The repo in question is [here](https://github.com/tanem/react-nprogress), and the examples I'm talking about are [here](https://github.com/tanem/react-nprogress/tree/master/examples). I've tried meddling with the renovate config as per #136, but to no avail. You can see the related open PR [here](tanem/react-nprogress#43).

Thanks 🙂

**Comment by rarkins** [comment]
Renovate natively supports multiple package files actually - the problem you're seeing is that the `config:base` preset includes the [:ignoreModulesAndTests](https://renovatebot.com/docs/presets-default/#ignoremodulesandtests) rule which ignores examples by default.

If you don't have any directories to ignore in your repo, you can add this to your config:

```json
  "ignorePaths": []
```

And this should result in your examples folders being included in PRs.

**Comment by tanem** [comment]
Oh right, thanks! I'll make some changes and will let you know how I get on.

**Comment by tanem** [comment]
Seems to be working well, thanks again for the prompt reply 🙏🏼
