### ISSUE TITLE
[Question] Prevent upgrade of a dependency within a subfolder

### ISSUE THREAD

**Issue by tanem** [renovatebot/config-help#180]
### Which Renovate are you using? CLI, App, or Pro

App.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub.

### Have you checked the logs? Don't forget to include them if relevant

Not relevant... yet.

### What is your question?

I'm maintaining a [repo](https://github.com/tanem/react-svg) which contains multiple standalone examples. In [the `typescript-2.x` example](https://github.com/tanem/react-svg/tree/master/examples/typescript-2.x), I'd like to fix [the TypeScript dev dependency](https://github.com/tanem/react-svg/blob/master/examples/typescript-2.x/package.json#L24) version to `< 3`.

How can I achieve that via the Renovate config? (I've fumbled around with the config in tanem/react-svg#228 to no avail 😅). 

Thanks!

**Comment by rarkins** [comment]
```json
{
  "packageRules": [{
	"paths": ["examples/typescript-2.x/package.json"],
    "packageNames": ["typescript"],
    "allowedVersions": ["<3"]
  }]
```

**Comment by tanem** [comment]
Ah nice, looks like I had it right 👍 

Thanks again!
