### ISSUE TITLE
single PR for package.json and Docker dependencies

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/config-help#181]
I would like renovate to open only 2 PRs per repo:
- upgrading major versions in `package.json`/`yarn.lock`
- upgrading minor/patch versions in `package.json`/`yarn.lock` + Docker dependencies (Node.js, MongoDB, Redis... (also shared orb) versions in CircleCI)

Is it possible to configure renovate in such a way?

**Comment by rarkins** [comment]
In general, I always recommend that you have one PR per major update. By definition they are often breaking, and it's hard to upgrade more than one breaking change in a single PR.

Also, are you meaning that you want all Docker updates upgraded in the same PR as npm updates, even if the Docker updates are major ones?

**Comment by piotr-s-brainhub** [comment]
@rarkins I’m not sure about major but IMO it’s ok to update in a single PR all NPM minor/ patch versions and all docker versions

**Comment by rarkins** [comment]
I would expect that a simple rule like this can capture all npm and Docker together. You can of course leave off the languages list if you don't have any others:

```json
  "packageRules": [{
    "languages": ["js", "docker"],
    "updateTypes": ["minor", "patch"],
    "groupName": "all minor/patch dependencies"
  }]
```

**Comment by piotr-s-brainhub** [comment]
@rarkins 

I tried this but it update only JS dependencies:
```
{
  "automerge": false,
  "commitMessagePrefix": "[renovate] ",
  "labels": [
    "renovate"
  ],
  "npmToken": "e5fcc145-8ebb-43a8-adab-b9cbdb3c350c",
  "packageRules": [
    {
      "automerge": true,
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    },
    {
      "automerge": true,
      "managers": [
        "circleci"
      ],
      "schedule": "at any time"
    },
    {
      "groupName": "all minor/patch dependencies",
      "languages": [
        "js",
        "docker"
      ],
      "updateTypes": [
        "minor",
        "patch"
      ]
    }
  ],
  "rangeStrategy": "bump",
  "schedule": "before 3am on the first day of the month"
}
```

**Comment by piotr-s-brainhub** [comment]
Currently there is no PR updating CircleCI orb.

**Comment by rarkins** [comment]
I have refactored the config a little to this:

```json
{
  "automerge": false,
  "commitMessagePrefix": "[renovate] ",
  "labels": ["renovate"],
  "npmToken": "<redacted>",
  "rangeStrategy": "bump",
  "schedule": "before 3am on the first day of the month",
  "packageRules": [
    {
      "languages": ["js", "docker"],
      "updateTypes": ["minor", "patch"],
      "managerBranchPrefix": "",
      "groupName": "all minor/patch dependencies"
    },
    {
      "packagePatterns": ["^@dmx/"],
      "groupName": null,
      "automerge": true,
      "schedule": "at any time"
    },
    {
      "managers": ["circleci"],
      "groupName": null,
      "automerge": true,
      "schedule": "at any time"
    }
  ]
}
```

General suggestions:
- Always put packageRules last
- Order packageRules in the order that you want them applied
- Within packageRules, put "selectors" (e.g. packageNames, updateTypes, languages) first, and then the config you wish to apply (e.g. automerge, schedule, groupName) last. It makes it more readable

Config bug fixes:
- We needed to set `managerBranchPrefix` to empty string so that Docker updates don't get grouped by themselves. This is the reason you are seeing the "docker-" part in the branchName, so we reset it to empty for all packages.
- We set groupName to null for your special cases of `@dmx` and CircleCI deps. That way they are not grouped with them and get raised separately without bringing al the others along too

**Comment by piotr-s-brainhub** [comment]
@rarkins 

Now it works, thanks.

<img width="1065" alt="Screen Shot 2019-03-15 at 22 13 30" src="https://user-images.githubusercontent.com/20856232/54462315-9c41a300-476f-11e9-8b64-3d297f693943.png">


btw. I would like JS objects to be like Python dictionaries - the key order doesn't matter because it's sorted on creation and adding new keys but that will probably never happen because it would break the backwards compatibility.
