### ISSUE TITLE
[Question] Unable to load private-key using self hosted

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/config-help#182]
### Which Renovate are you using? CLI, App, or Pro

CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Azure Devops

### Have you checked the logs? Don't forget to include them if relevant

Relevant section

```json
DEBUG: Found encrypted config (repository=MSE/mi-platform.jamagee)
       "config": {"npmToken": "***********"}
DEBUG: Trying default padding for npmToken (repository=MSE/mi-platform.jamagee)
DEBUG: Trying RSA_PKCS1_PADDING for npmToken (repository=MSE/mi-platform.jamagee)
 WARN: Error decrypting npmToken (repository=MSE/mi-platform.jamagee)
       "err": {
         "message": "error:0909006C:PEM routines:get_name:no start line",
         "stack": "Error: error:0909006C:PEM routines:get_name:no start line\n    at Object.privateDecrypt (internal/crypto/cipher.js:53:12)\n    at decryptConfig (/home/jamie/.npm/_npx/16615/lib/node_modules/renovate/lib/config/decrypt.js:28:18)\n    at mergeRenovateConfig (/home/jamie/.npm/_npx/16615/lib/node_modules/renovate/lib/workers/repository/init/config.js:112:27)\n    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
       }
```

### What is your question?

How do you correctly use the `--private-key` flag from the CLI? I generated a new keypair, and encrypted a string using the following commands

```sh
# Create a new private key
openssl genrsa -out private.pem 1024
# Extract public key
openssl rsa -in private.pem -out public.pem -outform PEM -pubout
# Encrypt the string
cat "..." > raw.txt
openssl rsautl -encrypt -inkey public.pem -pubin -in raw.txt -out encrypted.txt
cat encrypted.txt | base64 -w 0
```

I then put this in my config as 

```json
"encrypted": {
    "npmToken": "..."
  }
```

I've attempted to use `--private-key=~/private.pem`, as well as `--private-key="$(cat /home/jamie/private.pem)"` but I get the same error for both.

**Comment by rarkins** [comment]
When encrypting your tokens, I would suggest:
- Download https://renovatebot.com/encrypt
- Replace the public key there with your own
- Encrypt your secret that way

I would also recommend putting the private key into a bot's `config.js` too instead of by CLI, to eliminate one possible problem with CLI encoding/parsing.

Finally, is there any reason why you can't just put the npm token into your bot's config?

**Comment by JamieMagee** [comment]
Thank you I will try that.

I wanted to put as much of my configuration as possible into the `renovate.json` I share with my team. I agree it would be easier to just put the npm token in my `config.js`. I'll give that a go instead.

**Comment by rarkins** [comment]
You can also just copy an `.npmrc` into the bot's home directory (e.g. `/home/ubuntu/.npmrc`)
