### ISSUE TITLE
Limit update frequency for git-sourced dependencies

### ISSUE THREAD

**Issue by bjeanes** [renovatebot/config-help#186]
### Which Renovate are you using? CLI, App, or Pro

GH App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GH

### Have you checked the logs? Don't forget to include them if relevant

n/a

### What is your question?

We have some dependencies from Git (in both NPM and Bundler). I'd like to be able to restrict those to only open update PRs say once per week, as they tend to change very rapidly and by definition we're running pre-releases so these updates are not likely very stable (so I'd even only update once per month!)

My inclination here was to scope by `updateTypes`, but the docs aren't clear if there is a value here of "git" or something:

``` jsonc
{
  // ...
  "packageRules": [
    {
      "updateTypes": ["git"], // this a thing?
      "extends": ["schedule:monthly"]
    }
  ]
  /// ...
}
```

As far as I can tell, it's just `major`, `minor`, `patch`, and `pin`, though.

**Comment by rarkins** [comment]
Assuming it's not just easier to use `packageNames`, you could try the new `datasources` selector in packageRules, e.g. 

```
  "datasources": ["github"],
  "extends": ["schedule:monthly"]
```

I think it should work but haven't tried it.

**Comment by bjeanes** [comment]
Ah will that apply to NPM and Bundler packages sourced from Git then? Would that go inside `packageRules`?

**Comment by rarkins** [comment]
Yes, `managers` is based on the package manager while `datasources` is based on the source we query. For both npm and bundler that should be "github" if you reference github sources. There is no "git" supported.

**Comment by bjeanes** [comment]
I'm not sure how your internal model works and if it would be an easy change, but it would make sense to have some way to specify git as a `source` (even if it was kind of a "parent" source for github, bitbucket, etc). Fortunately, I think all my git sources are GH right now, but I have in the past pulled from a dedicated git host.

**Comment by rarkins** [comment]
Renovate won't update a non-github datasource anyway, so there's no non-github git right now. We need to use APIs to query the tags so there's no concept of a generic git datasource

**Comment by bjeanes** [comment]
Ack!

**Comment by bjeanes** [comment]
whoops early send.

I've added the changes to my config so we'll see if it takes effect. Thanks!

**Comment by rarkins** [comment]
@bjeanes have you been able to verify this working?
