### ISSUE TITLE
Renovate bot configuration with scoped NPM packages

### ISSUE THREAD

**Issue by patrickleet** [renovatebot/config-help#189]
### Which Renovate are you using? CLI, App, or Pro
When using a scoped npm registry config, renovate fails to fetch scoped packages

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yes - there is an unauthorized error - this token work when using the private registry format, but not the scoped private registry format

### What is your question?

Is this a known issue? Not sure why it wouldn't work if just copying the NPMRC as written into the root folder

**Comment by patrickleet** [comment]
```
{
  "extends": [
    "config:base"
  ],
  "encrypted": {
    "npmToken": "Y8Twm+sYFd5lleXElBKPs1jE3FtbR+Tdyfvq8rMOomAWvYKBxvbeJWr03BQGHuiq7NNvEAKg7KgwXUakrVOOgK/O+P3GWQq9Y4dJ3pAwLb+QJ1j74CTINGQ/cY2qjVWDfCX6g3TKOKD43Wb7jM7ls5fbrIoChU7EjHaJvK66i+Z/X/xV1QyTZMBWICKzpB6GGkyTnvWXOLVKhw5tjCoyr52Q1E9T+fYxwwMy4okMtlWYKE5sKra6Fo1U7TFR+9hBiIZO72kamTQvAx7eTtcjmWI5cNcnQsUgcGEaIfVwbSXl6dQu4ayZkYwy4iuM4NQN3HG3l3vsBc+xtSkIe/Ke3A=="
  },
  "npmrc": "registry=http://nexus.jx.xxx.services/repository/xxx-npm\n_auth=${NPM_TOKEN}"
}
```

works but fetched everything through nexus - not just scoped repos

**Comment by patrickleet** [comment]
When using this format however, which works locally - renovate cannot resolve the scoped modules
```
registry=https://registry.npmjs.org/
@xxx:registry=http://nexus.jx.group1001.services/repository/xxx-npm
//nexus.jx.xxx.services/repository/xxx-npm/:_authToken=${NPM_TOKEN}
```

works locally

**Comment by rarkins** [comment]
Are you using the app or the CLI?

**Comment by patrickleet** [comment]
I'm using the Github App

**Comment by patrickleet** [comment]
```
{
  "extends": [
    "config:base"
  ],
  "encrypted": {
    "npmToken": "Y8Twm+sYFd5lleXElBKPs1jE3FtbR+Tdyfvq8rMOomAWvYKBxvbeJWr03BQGHuiq7NNvEAKg7KgwXUakrVOOgK/O+P3GWQq9Y4dJ3pAwLb+QJ1j74CTINGQ/cY2qjVWDfCX6g3TKOKD43Wb7jM7ls5fbrIoChU7EjHaJvK66i+Z/X/xV1QyTZMBWICKzpB6GGkyTnvWXOLVKhw5tjCoyr52Q1E9T+fYxwwMy4okMtlWYKE5sKra6Fo1U7TFR+9hBiIZO72kamTQvAx7eTtcjmWI5cNcnQsUgcGEaIfVwbSXl6dQu4ayZkYwy4iuM4NQN3HG3l3vsBc+xtSkIe/Ke3A=="
  },
  "npmrc": "registry=https://registry.npmjs.org/\n@xxx:registry=http://nexus.jx.xxx.services/repository/xxx-npm\n//nexus.jx.xxx.services/repository/xxx-npm/:_authToken=${NPM_TOKEN}",
  "ignoreNpmrcFile": true
}
```

**Comment by rarkins** [comment]
i.e. test this alone just to verify that lookups go to the right location:

```
{
  "extends": [
    "config:base"
  ],
  "npmrc": "registry=https://registry.npmjs.org/\n@xxx:registry=http://nexus.jx.xxx.services/repository/xxx-npm",
  "ignoreNpmrcFile": true
}
```

**Comment by patrickleet** [comment]
@rarkins I can see in the log with my previous config that the lookups are coming from correct location - the default registry for most packages - and attempting to use the alternative registry for the scoped packages - just getting a 401 for the latter

**Comment by patrickleet** [comment]
I pushed with your suggested config for debugging - will post results in a minute

**Comment by patrickleet** [comment]
hm - oddly the config you suggested without npmToken seems to work... not sure how..

**Comment by rarkins** [comment]
Can you tell me the repo name or email it to support@renovatebot.com? We can continue discussion here but I want to be able to check the logs myself. That seems impossible that it would work without auth, I'm wondering if you're looking at the log from your prior config, because that config had seemed right to me.

**Comment by patrickleet** [comment]
sure - I'll email it to support

**Comment by patrickleet** [comment]
Misconfiguration of nexus on my end
