### ISSUE TITLE
Local linked dependencies in monoreps not recognised

### ISSUE THREAD

**Issue by JohannesMerz** [renovatebot/config-help#190]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Detecting Lerna and Yarn Workspaces
DEBUG: Found monorepo packages with base path .(packageFile="package.json")
```

### What is your question?

The artefact check does not recognise local repos that are linked together and tries to search for them on the yarn registry.

![Screenshot 2019-03-20 at 17 55 09](https://user-images.githubusercontent.com/11529353/54703632-75052000-4b39-11e9-9613-a123e68cab4f.png)

Config file:

```JSON
{
  "extends": [
    "config:base"
  ],
  "automerge": true,
  "major": {
    "automerge": false
  },
  "rebaseStalePrs": false,
  "reviewers": [
    "JohannesMerz", "tchock"
  ],
  "prConcurrentLimit": 10,
  "prHourlyLimit": 10,
  "packageRules": [
    {
      "extends": "monorepo:lerna",
      "groupName": "lerna monorepo"
    }
  ]
}
```

**Comment by rarkins** [comment]
That error is coming from when we run `yarn` itself. Is it a public repository that can be cloned, or can you reproduce it in a public repo?

Or in the meantime, can you paste in your lerna and yarn workspaces configs?

**Comment by JohannesMerz** [comment]
not public, will try to build a publich repo with the structure. Until then:

lerna JSON

```JSON
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*",
    "client/*",
    "server/*"
  ],
  "version": "0.0.2",
  "npmClient": "yarn"
}
```

root package.json

```JSON
{
	"devDependencies": {
		"lerna": "^2.9.0"
	},
	"private": true
}
```

**Comment by rarkins** [comment]
Are you using lerna + yarn but *without* Yarn workspaces? That may not be a scenario we've considered.

Also, do you have more than one lerna structure within the repo, or just a single one in the root?

**Comment by JohannesMerz** [comment]
Just the single one, and yes without workspaces as it caused a lot of troubles.

**Comment by rarkins** [comment]
OK, that's probably the root cause then - I don't think we handle the case where it's yarn + lerna but without workspaces. If you are able to reproduce the error in a minimal public repository with the same lerna and yarn setup then that would definitely help, otherwise I'm somewhat guessing.

**Comment by rarkins** [comment]
BTW if I've guessed right about the rep you're testing, Renovate's logs indicates it thinks that there are monorepo packages defined in `context/scripts-custom/package.json` too.

**Comment by JohannesMerz** [comment]
Are you looking at the right repo? I have enabled 2, the problematic one right now is https://github.com/tchock/bojagi
The file from above is in another one.

**Comment by JohannesMerz** [comment]
@rarkins recreated a basic setup here:
https://github.com/JohannesMerz/renovatebot-monorep-example/pull/2

**Comment by rarkins** [comment]
Thanks. To you knowledge, what is the correct way to update lock files in such a setup? i.e. do we need to run `lerna bootstrap` and let it delegate to `yarn`?

**Comment by JohannesMerz** [comment]
To my knowledge manually updating the package.json and bootstrap again is the only way. For it to update lockfiles correctly node_modules have to be removed first though.

**Comment by rarkins** [comment]
I've been able to confirm that `lerna bootstrap` works using your demo repo, thanks.

Todo:
- [ ] Detect when lerna/yarn are used without yarn workspaces
- [ ] In such cases, run `lerna bootstrap` from root instead of `yarn`

If it turns out to be simple, I might have it fixed tomorrow.

**Comment by JohannesMerz** [comment]
thats great news! Thanks for the quick response.

**Comment by JohannesMerz** [comment]
To add to this:

you also have to run yarn for the root package, as lernas way without workspaces is to do hoisting yourself.

On our Ci we run this for installation:

```
  yarn install --pure-lockfile
  lerna bootstrap -- --pure-lockfile
```

**Comment by rarkins** [comment]
If you have a `yarn.lock` for the root `package.json` then we'll use `yarn`, otherwise we default to `npm`. In your demo repo there'ss no `./yarn.lock`, so I installed using npm when testing manually but it doesn't really make a difference.

And in Renovate's case, we will run without `--pure-lockfile` because it's our intention to update the `yarn.lock` files if necessary.

In your above example, does your CI have `lerna` installed globally in order to run `lerna ....` ?

**Comment by JohannesMerz** [comment]
> In your above example, does your CI have lerna installed globally in order to run lerna .... ?

yes it has

**Comment by rarkins** [comment]
It should hopefully be fixed in the app now. If you tick the rebase/retry checkbox on existing PRs then you can confirm.

**Comment by JohannesMerz** [comment]
Seems like its all sorted out now! 👍
