### ISSUE TITLE
[Question] Can turn off automerge

### ISSUE THREAD

**Issue by hipstersmoothie** [renovatebot/config-help#191]
### Which Renovate are you using? CLI, App, or Pro

Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### What is your question?

Is it possible to turn off automerge from an extended config.

Right now I have something like:

```json
{
  // @appfabric has automerge set to true
  "extends": ["@appfabric"],
  "automerge": false,
  "packageRules": [
    {
      "automerge": false,
      "depTypeList": ["devDependencies"],
      "labels": ["dev-dependency", "dependency-update"]
    }
  ]
}
```

On PR descriptions it still says automerge is enabled. Any times?

**Comment by rarkins** [comment]
A packageRule like this should always overrule everything:

```json
{
  "packagePatterns": ["*"],
  "automerge": false
}
```

**Comment by gmariotti** [comment]
Hi @rarkins, I'll ping you on this issue, but, if you prefer, I can create a new one. I have a similar problem, my `renovate.json` looks like this

```json
{
    "extends": [
        "config:base",
        ":semanticCommitTypeAll(fix)"
    ],
    "prConcurrentLimit": 0,
    "prHourlyLimit": 0,
    "automerge": true,
    "major": {
        "automerge": false
    },
    "masterIssue": true,
    "masterIssueAutoclose": true,
    "packageRules": [
        {
            "packagePatterns": ["^org.jetbrains.kotlin"],
            "groupName": "Kotlin packages",
            "automerge": false
        }
    ]
}
```

the MR with all the kotlin packages grouped together works as expected, however, the `automerge: false` doesn't. Am I doing something wrong?
