### ISSUE TITLE
[Question] (github actions)Repository has changed during renovation - aborting

### ISSUE THREAD

**Issue by HaveF** [renovatebot/config-help#192]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant

The most relevant part is
```
DEBUG: Error commiting files(dependencies=["gatsby-remark-mermaid"], branch="renovate/pin-dependencies")
{
  "err": {
    "message": "To https://github.com/HaveF/havef.github.io.git\n ! [remote rejected] renovate/pin-dependencies -> renovate/pin-dependencies (refusing to allow an integration to create .github/main.workflow)\nerror: failed to push some refs to 'https://x-access-token:[**redacted**]@github.com/HaveF/havef.github.io.git'\n",
    "stack": "Error: To https://github.com/HaveF/havef.github.io.git\n ! [remote rejected] renovate/pin-dependencies -> renovate/pin-dependencies (refusing to allow an integration to create .github/main.workflow)\nerror: failed to push some refs to 'https://x-access-token:[**redacted**]@github.com/HaveF/havef.github.io.git'\n\n    at /home/ubuntu/renovateapp/node_modules/simple-git/promise.js:21:26\n    at Git. (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:953:21)\n    at Function.Git.fail (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1478:18)\n    at fail (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1436:20)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1445:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
DEBUG: Passing repository-changed error up(dependencies=["gatsby-remark-mermaid"], branch="renovate/pin-dependencies")
INFO: Repository has changed during renovation - aborting
```

### What is your question?
I know the `refusing to allow an integration to create .github/main.workflow` mean, but I don't know how to fix this. 
I notice there is a option called [github-actions](https://renovatebot.com/docs/configuration-options/#github-actions), but don't know how to config it. Have any example of this?
Thanks!

**Comment by rarkins** [comment]
This is unfortunately a bug on GitHub's side. They have acknowledged it but have not given a timeline for fix. They seem to be trying to protect against apps/integrations "hacking" a user by writing Actions, but they've implemented the logic too aggressively. You can guess from the error message that it thinks Renovate is trying to *add* a workflow file, but actually it is not - we're just creating a branch off master and your master branch contains a workflow file.

The good news is that I have a workaround for now, and have enabled it on your account so there's nothing you need to do. I'm going to modify the code so that I receive a warning on the server side when this happens

**Comment by HaveF** [comment]
rankins, thanks for your help.

I found another solustion, but it need [`git rm .github/main.workflow`](https://github.com/cclauss/Upgrade-to-Python3/issues/1), but I can't make renovate to do it.

Glade you found a workaround for now. It seems the github gay to fix this aggressive logic is the best solution.

Thanks again

**Comment by rarkins** [comment]
Yes, I suppose we could delete the workflow file but I doubt most users would be happy that we submit PRs proposing to remove their GitHub Actions for no reason :)
