### ISSUE TITLE
Only update major.minor, not patch

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/config-help#193]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I want to only receive updates for either major or minor updates. I was going through the documentation but I was not sure how I can disable patch updates, is this possible?

This is probably nicely documented but I'm just looking over it - Sorry for that!

**Comment by rarkins** [comment]
You can probably achieve it by:

1. Set `separateMinorPatch` to `true`
2. Add a packageRule to disable patch:

```
{
  "updateTypes": ["patch"],
  "enabled": false
}
```

Why would you want to do this?

**Comment by tomkerkhove** [comment]
THanks, I can try that one out!

I have a noisy dependency which updates for every commit (even if not code change) and is a bit annoying and was evaluating options. Thanks!
