### ISSUE TITLE
[Question] How to configure Go project with a private repository?

### ISSUE THREAD

**Issue by emman27** [renovatebot/config-help#194]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
```
go: github.com/visenze/govisenze@v0.0.0-20190315100807-dd3fbe95dce4: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /mnt/renovate/tmp/renovate/cache/go/pkg/mod/cache/vcs/fc09d6c192c9f6c4675e407ebb427b7de6b7614103f76c8cc0c22cdbd84121cc: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

### What is your question?
The repo mentioned above is our private repo containing some shared libraries. Wondering how we can grant renovate access to this so that you can pull the code and manage the dependencies, without exposing our credentials by putting them in plaintext in the repo.

**Comment by rarkins** [comment]
First step would be to make sure you’ve installed Renovate into that source directory too. That way the same token that GitHub grants the app will also grant it access to pull that repo. 

Second step is.. we need to enhance Renovate a little to make sure the `go` binary can access the use the token. This hopefully comes this week or next. 

Can you confirm the names of the two repos involved here? You can email them to support@renovatebot.com if you prefer to keep it confidential.

**Comment by emman27** [comment]
Hi @rarkins 

Thanks for responding. We've actually not installed Renovate into that repo, we can get this done, thanks!

Wondering if you have support for a private pip registry as well actually --- we're currently using one that's configured to whitelist our internal servers' IP addresses.

**Comment by emman27** [comment]
We've added the repo to Renovate, but this still doesn't work.

Here are the relevant logs:

```
go: github.com/visenze/govisenze@v0.0.0-20190315100807-dd3fbe95dce4: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /mnt/renovate/tmp/renovate/cache/go/pkg/mod/cache/vcs/fc09d6c192c9f6c4675e407ebb427b7de6b7614103f76c8cc0c22cdbd84121cc: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
go: error loading module requirements
 `docker run --rm -v /mnt/renovate/gh/visenze/rec-async-api:/mnt/renovate/gh/visenze/rec-async-api -v /mnt/renovate/tmp/renovate/cache/go:/mnt/renovate/tmp/renovate/cache/go -e GOPATH -e CGO_ENABLED=0 -w /mnt/renovate/gh/visenze/rec-async-api renovate/go go get` (exited with error code 1)
```

And the link to the PR https://github.com/visenze/rec-async-api/pull/41

Looks to me like the authentication in git isn't setup correctly in the containers - we use something like this locally, could we confirm that the same is set on your end?:
`git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"`

**Comment by rarkins** [comment]
@emman27 thanks for trying it out and your feedback. Indeed we are still researching the best way to do this. Please join the discussion here: https://github.com/renovatebot/renovate/issues/3202

**Comment by rarkins** [comment]
Let's close this one (it's not fixable via config and nor will it need to be eventually either) and track the issue in the main repo instead
