### ISSUE TITLE
freeze yarn version

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/config-help#198]
I want to freeze yarn version in `package.json` file, `engines` section.

Will this work?
```
{
  "packageRules": [
    {
      "allowedVersions": "1.13.0",
      "packageNames": [
        "yarn"
      ]
    }
  ]
}
```
I'm not sure whether it's correct because in this way NPM packages are handled.

**Comment by rarkins** [comment]
That should work

**Comment by piotr-s-brainhub** [comment]
Thanks.
It worked, though for some repos renovate closed PR updating yarn after a few hours.
