### ISSUE TITLE
Grouping dependency updates

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/config-help#202]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I have several dependencies which need to be updated in one PR and was wondering if I can configure those. If so, is [group](https://renovatebot.com/docs/configuration-options/#group) the good use-case for this? I'm not sure after reading the docs if that is the case.

For example [Microsoft.Azure.Management.Monitor.Fluent](https://github.com/tomkerkhove/promitor/pull/508) & [Microsoft.Azure.Management.Fluent](https://github.com/tomkerkhove/promitor/pull/507) should be updated in one PR but today I close one and do the update in the other PR manually. Would be great to have this automated as well.

Bonus points if I can do this for multiple update providers like NuGet & Docker.

**Comment by rarkins** [comment]
It sounds like these should be considered as part of a monorepo and put into shared presets for everyone.

Here is an example for some other microsoft packages: https://github.com/renovatebot/presets/blob/b1700cec7b216e7b47e28e52efacf74701bffd26/packages/renovate-config-monorepo/generate.js#L158-L160

You can submit a PR to that repo for any that you're aware of and they'll be picked up for anyone who is extending the `config:base` preset

**Comment by tomkerkhove** [comment]
Sure, I'm happy to help. What's the naming convention for this, because I see different flavors.

**Comment by rarkins** [comment]
Nothing too strict, so propose what you think suits best. Most people won't see the name as it's just a sub-preset of a larger one

**Comment by tomkerkhove** [comment]
Thanks for the help, I've opened a PR - https://github.com/renovatebot/presets/pull/112.

I presume this means I won't have to change my config for Promitor, is that correct?
https://github.com/tomkerkhove/promitor/blob/master/renovate.json

**Comment by tomkerkhove** [comment]
Closing as it should now be fixed, thanks!
