### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by landau** [renovatebot/config-help#204]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?

How can I configure Renovate to include all the dep version changes in the commit message for `packageRules`? For a single dep, commit messages are `Update dependency hot-shots to v6.2.0`, but multiple result as `Update non-major deps`. The latter commit message is not very useful in the git log, it also makes the usage of `semantic-release` less useful when appending to a `CHANGELOG.md`.

In other words:

1. Renovate updates > 1 non major deps in a single PR.
2. The commit message should look something like `fix(deps): Update dependency hot-shots to v6.2.0, koa to v5.1.0`. Alternatively, each dependency is in it's own semantic commit.

Thank you for your time. I've pasted my `renovate.json` below to aid in better understanding. Have a lovely day.

```json
{
  "extends": [
    "config:base"
  ],
  "ignoreUnstable": true,
  "devDependencies": {
    "automerge": true
  },
  "pinVersions": false,
  "respectLatest": true,
  "rebaseStalePrs": true,
  "prConcurrentLimit": 4,
  "schedule": [
    "after 8pm and before 9am on every weekday",
    "every weekend"
  ],
  "timezone": "America/New_York",
  "packageRules": [{
    "groupName": "Major dev deps",
    "packagePatterns": ["*"],
    "depTypeList": ["devDependencies"],
    "updateTypes": ["major"],
    "labels": ["UPDATE-MAJOR-DEV"]
  }, 
  {
    "groupName": "Non-major dev deps",
    "packagePatterns": ["*"],
    "depTypeList": ["devDependencies"],
    "updateTypes": ["minor", "patch"],
    "labels": ["UPDATE-NON-MAJOR-DEV"]
  },
  {
    "groupName": "Major deps",
    "packagePatterns": ["*"],
    "depTypeList": ["dependencies"],
    "updateTypes": ["major"],
    "labels": ["UPDATE-MAJOR"],
    "semanticCommits": true
  }, 
  {
    "groupName": "Non-major deps",
    "packagePatterns": ["*"],
    "depTypeList": ["dependencies"],
    "updateTypes": ["minor", "patch"],
    "labels": ["UPDATE-NON-MAJOR"],
    "semanticCommits": true
  }]
}
```

**Comment by rarkins** [comment]
I'm not sure you'd want to do this in the commit message line because in some cases it could cause length issues, but perhaps in the commit message *body* it could make more sense? I don't know if semantic-release picks up commit message body though.

So the key question is: is there a length of commit message that's too long? If so, what to do?

**Comment by landau** [comment]
Thanks for the quick response! 😄 

> I'm not sure you'd want to do this in the commit message line because in some cases it could cause length issues

Right. However, if the PR included multiple commits then this wouldn't be an issue. Is this a possible solution in a single PR.  

>  perhaps in the commit message body it could make more sense?

How can I configure `Renovate` such that every dependency upgraded is included in the body?

**Comment by rarkins** [comment]
I’m actually thinking of whether to include all updates in the commitMessageBody by default whenever we have a group. But I’d need to expose that data first internally before it could be implemented.

**Comment by landau** [comment]
Cool. It's not completely clear if `semantic-release` can derive the commit from body See parserOpts for https://github.com/semantic-release/commit-analyzer

That said, I think the best way to do this with groups would be to have an `packageRules` option like `individualCommits: true|false` which would create separate commits for each package.

**Comment by rarkins** [comment]
Individual commits will likely be supported in future but not in the short term. The single commit logic makes a lot of things simple

**Comment by landau** [comment]
Great. I appreciate your time. 😄

**Comment by landau** [comment]
I was thinking, would something like this work?

```
  "major": {
    "branchName": "{{{branchPrefix}}}{{{managerBranchPrefix}}}deps-major"
  },
  "minor": {
    "branchName": "{{{branchPrefix}}}{{{managerBranchPrefix}}}deps-minor-patch"
  },
  "patch": {
    "branchName": "{{{branchPrefix}}}{{{managerBranchPrefix}}}deps-minor-patch"
  },
```

or would Renovate be unappeased? 😆

**Comment by landau** [comment]
I tried it. Renovate used a single commit for 2 deps with a commit message of only 1 of the deps.  😆

**Comment by rarkins** [comment]
Yeah without explicit groupName defined it just uses the first commitMessage
