### ISSUE TITLE
Prod dependency not being updated

### ISSUE THREAD

**Issue by tanem** [renovatebot/config-help#206]
### Which Renovate are you using? CLI, App, or Pro

App.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub.

### Have you checked the logs? Don't forget to include them if relevant

Here's the latest `INFO` log, can attach `DEBUG` if required:

```
INFO: Renovating repository
INFO: Authenticated as user: renovate[bot]
INFO: Using renovate version: 15.14.0
INFO: Initialising git repository into /mnt/renovate/gh/tanem/react-svg
INFO: git clone completed
{
  "cloneSeconds": 2.3
}
INFO: Setting git author
{
  "gitAuthor": {
    "name": "Renovate Bot",
    "email": "bot@renovateapp.com"
  }
}
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "config:base",
      ":disableRateLimiting"
    ],
    "ignorePaths": [
      "**/node_modules/**"
    ],
    "packageRules": [
      {
        "paths": [
          "examples/typescript-2.x/package.json"
        ],
        "packageNames": [
          "typescript"
        ],
        "allowedVersions": ">=2 <3"
      }
    ]
  }
}
INFO: Found npm package files
INFO: Found nvm package files
INFO: Processing 3 branches: renovate/react-dom-16.x, renovate/rollup-1.x, renovate/rollup-plugin-node-resolve-4.x
INFO: Request stats
{
  "rateLimit": 5000,
  "requestCount": 8,
  "rateLimitRemaining": 4994
}
INFO: Finished repository
```

### What is your question?

In the [tanem/react-svg](https://github.com/tanem/react-svg) repo, renovate doesn't appear to be picking up new versions of [the `@tanem/svg-injector` dependency](https://github.com/tanem/react-svg/blob/master/package.json#L67). For example, here's what `npm outdated` is showing at the moment:

```
Package                     Current  Wanted  Latest  Location
@tanem/svg-injector          7.0.11  7.0.12  7.0.12  react-svg
```

I'm not sure if this is an issue for all prod dependencies in this repo, it's just that that particular dependency is the one I've noticed because I publish new versions fairly frequently.

One other piece of related info: When I first set renovate up on `react-svg`, I configured it to only allow specific versions of `@tanem/svg-injector`. This was then removed a while back, you can see the change [here](https://github.com/tanem/react-svg/commit/b4eaef7c0f56743e230635e31fc29597de6cb366#diff-76e62915fba4048ac877a875e2e3b8d2).

Any ideas what's happening here?

Thanks 🙏

**Comment by rarkins** [comment]
Your current version is `"@tanem/svg-injector": "^7.0.11"`, so 7.0.12 satisfies that, so Renovate doesn't need to change `package.json`.

You have a few options:
- If you want it bumped to the latest version every time, you probably could use an exact version instead. i.e. `7.0.11`, not `^7.0.11`
- If you want the package.json updated to `^7.0.12` then you should configure rangeStrategy=bump in renovate.json
- If you want package.json to stay at `^7.0.11` and just the `yarn.lock` to change, then configure rangeStrategy=lockfile-update

More on `rangeStrategy` here: https://renovatebot.com/docs/configuration-options/#rangestrategy

**Comment by tanem** [comment]
@rarkins oh right, yep that makes sense. Just tried `"rangeStrategy": "bump"`, and things look good now. Thanks again for such a prompt and helpful response :+1:
