### ISSUE TITLE
[Question] trying to seperate devDependencies and dependencies

### ISSUE THREAD

**Issue by vidarc** [renovatebot/config-help#208]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?

Trying to have my dependencies and devDependencies split. The following is what I am currently using. it still groups everything together with a separate PR for major releases

```json
{
  "extends": ["config:base"],
  "schedule": "before 3am on Monday",
  "semanticCommits": true,
  "groupName": "all dependencies",
  "groupSlug": "all",
  "packageRules": [
    {
      "packagePatterns": ["*"]
    },
    {
      "depTypeList": ["dependencies"],
      "groupName": "all dependencies"
    },
    {
      "depTypeList": ["devDependencies"],
      "groupName": "all devDependencies"
    }
  ]
}
```

Also, is there a way to test configs? Outside of waiting for package upgrades to become available.

**Comment by rarkins** [comment]
Remove group rules from the top level config if you’re also trying to define them in package rules. 

Your first package rule is pointless and can be removed. 

Your schedule will mean no new PRs will be created outside of it and this probably explains your confusion as you’re not “seeing results”.

Add `”masterIssue”: true` to your config and you will see a new issue created that lists all upcoming PRs. Should make it easier to debug.

**Comment by rarkins** [comment]
Also, set `"separateMajorMinor": false,` if you don't want a separate PR for major updates.
