### ISSUE TITLE
[Question] Set assignee depending on filepath

### ISSUE THREAD

**Issue by Fandekasp** [renovatebot/config-help#209]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
Follow-up to https://github.com/renovatebot/renovate/issues/3543

The [assignees doc](https://renovatebot.com/docs/configuration-options/#assignees) isn't easy to understand. Can you provide an example on how to set rules for assignees (eg member A is assigned to `package.json` PRs, while another member is assigned to `requirements*` PRs).

**Comment by rarkins** [comment]
Here's an example set of package rules that would set you as the assignee for `package.json` and me for any file starting with `requirements`:

```
{
  "packageRules": [
    {
      "paths": [
        "package.json"
      ],
      "assignees": [
        "Fandekasp"
      ]
    },
    {
      "paths": [
        "requirements*"
      ],
      "assignees": [
        "rarkins"
      ]
    }
  ]
}
```

`paths` is either an exact match string (`package.json`) or can also be a glob pattern (`requirements*`).

**Comment by Fandekasp** [comment]
Thanks for the clear example, makes sense now :)
