### ISSUE TITLE
[Question] Artifact update problem when ignoreNpmrcFile: true

### ISSUE THREAD

**Issue by cmschuetz** [renovatebot/config-help#211]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### Have you checked the logs? Don't forget to include them if relevant

Yes, important logs are included in this issue: https://github.com/renovatebot/renovate/issues/3551

### What is your question?

I added "ignoreNpmrcFile": true to our configuration but I am still receiving these errors.  For context, we've used the same `.npmrc` file with renovate for months without issue.  This started happening to us last week.

Is `ignoreNpmrcFile` a new configuration option?  Has anything around this changed recently?

**Comment by rarkins** [comment]
`ignoreNpmrcFile` is not new and I can't think of any change in functionality in this area recently.

Once you update your config, you need to tick the rebase/retry checkbox on each PR. You can also log into https://renovatebot.com/dashboard to view logs and confirm that the PR has been rebased. If the problem occurs, grep through those logs for any mention of "npmrc" too.

**Comment by rarkins** [comment]
@cmschuetz actually I just thought of a possible reason for a change in behaviour. I'll see if I can fix it on the server side but do keep the `ignoreNpmrcFile` setting there for now.

**Comment by cmschuetz** [comment]
Things seem to be working again now, thanks for the update!  Is the `ignoreNpmrcFile` config still needed?

**Comment by rarkins** [comment]
For your account, you no longer need it in your config because I added a manual override. For anyone else, it will be fixed once this commit goes live in the app: https://github.com/renovatebot/renovate/commit/3460dbe08ca0779ba9d0a7c6b4598a1765e7f6c9

There's a little explanation of the fix there.

Thanks for alerting me to the problem.
