### ISSUE TITLE
[Question] How are tests run with automerge is enabled?

### ISSUE THREAD

**Issue by openjck** [renovatebot/config-help#212]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

https://renovatebot.com/dashboard#github/openjck/domainspy/60478114

### What is your question?

Why didn't Renovate automerge [this pull request](https://github.com/openjck/domainspy/pull/38)? The logs show that Renovate correctly determined that automerge was enabled. The documentation mentions that tests must pass before a pull request is automerged, but I'm not sure what that means exactly. My `npm test` tests do pass but I'm not currently using a CI app. Does Renovate only automerge when a CI app indicates that tests have passed?

**Comment by rarkins** [comment]
Renovate doesn’t run tests itself - you need CI. Set `requiredStatusChecks=null` in config if you wish to ignore tests completely.
