### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by patryk** [renovatebot/config-help#213]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
```json
{
    "lineNumber": 8,
    "depName": "github.com/cloudflare/cloudflare-go",
    "depType": "require",
    "currentValue": "v0.0.0-20190409214620-92c75602c045",
    "depNameShort": "cloudflare/cloudflare-go",
    "datasource": "go",
    "currentDigest": "92c75602c045",
    "digestOneAndOnly": true,
    "multiLine": true,
    "updates": [{
        "fromVersion": "v0.0.0-20190409214620-92c75602c045",
        "toVersion": "v0.8.5",
        "newValue": "v0.8.5",
        "newMajor": 0,
        "newMinor": 8,
        "updateType": "minor",
        "isSingleVersion": true,
        "newDigest": "1f9007fbecae20711133c60519338c41cef1ffb4",
        "newDigestShort": "1f9007f"
    }],
    "warnings": [],
    "sourceUrl": "https://github.com/cloudflare/cloudflare-go",
    "releases": ["v0.7.2", "v0.7.3", "v0.7.4", "v0.8.0", "v0.8.1", "v0.8.2", "v0.8.3", "v0.8.4", "v0.8.5"]
}
```
### What is your question?
In the repo: https://github.com/terraform-providers/terraform-provider-cloudflare

We are using the library, https://github.com/cloudflare/cloudflare-go/, that recently didn't have any new releases, so basically what we need is convince renovate bot to create PRs against master branch, ignoring any release tags that are already there. Unfortunately, all my tries so far have always resulted with renovate doing a PR of type minor, or none at all.

My tries: https://github.com/patryk/terraform-provider-cloudflare/commits/master

**Comment by rarkins** [comment]
@patryk if I understand correctly, this library started cutting releases but then stopped, so now the latest release (v0.8.5) trails behind master by a long way and you want to keep using master?

We don't support this right now, but it sounds like something that would be beneficial. Can you raise a feature request for it in the main Renovate repo? It's unfortunately not solvable via config right now, so closing this question.
