### ISSUE TITLE
[Question] Update arbitrary dependecies using script

### ISSUE THREAD

**Issue by CyberShadow** [renovatebot/config-help#215]
### Which Renovate are you using? CLI, App, or Pro
None yet.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
Hi,

Not sure if Renovate is the right tool for the job. I'm looking for something to do essentially the following:

- Have a clone of the repository checked out
- Periodically, run a specified script in the repository
- If the script fails, complain (send an email)
- If the working directory is dirty after the script ran, commit and send as pull request
- If CI succeeds, merge the PR, otherwise make angry noises.

I'm guessing this is not possible with the hosted version as it involves arbitrary code execution. I don't mind self-hosting, would this still be possible without changing Renovate's source code? Any pointers towards how I could get started implementing this would be appreciated.

The reason for updating dependencies via a custom script is that the project is not using any specific PL stack, and is downloading essentially arbitrary tarballs (among other things) as part of CI.

Thanks!

**Comment by CyberShadow** [comment]
In the end I figured out how to implement all dependencies as renovate managers / data sources:
https://github.com/renovatebot/renovate/compare/master...CyberShadow:aconfmgr

It was a bit more roundabout but I got there in the end. Thanks for the nice project :)

**Comment by rarkins** [comment]
@CyberShadow you're very quick! I was planning to describe an idea similar to how you implemented.

If you're interested in discussing how to merge this into the mainline so you no longer need to maintain a fork or can use it via the app, drop an email to support@renovatebot.com referencing this thread and I'll invite you into our developer Slack channel to discuss.

In short:
- Allowing arbitrary script execution is definitely something far, far away for the hosted app
- Allowing arbitrary script execution is maybe something that will be an acceptable risk for some self-hosted bot admins
- Replacing such scripts with some custom datasources/managers like you've done is a great idea
