### ISSUE TITLE
[Question] requirements.txt inside test/ directory

### ISSUE THREAD

**Issue by hutchic** [renovatebot/config-help#216]
### Which Renovate are you using? CLI, App, or Pro

Renovate github app

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)test/requirements.txt$ for manager pip_requirements
```

### What is your question?

I can't seem to get renovate to pick up my requirements.txt file ( https://github.com/Kong/kong-build-tools/blob/master/test/requirements.txt )

I've tried a few ways of defining `pip_requirements` without any luck https://github.com/Kong/kong-build-tools/blob/master/renovate.json

**Comment by rarkins** [comment]
It's being ignored deliberately due to its "test/" prefix. i.e. we ignore test and examples directories by default.

If you don't want to ignore any paths in this repo, you should be able to override it with this setting:

```
  "ignorePaths": []
```

**Comment by hutchic** [comment]
that did it 👍
