### ISSUE TITLE
[Question] How to ignore Ruby versions

### ISSUE THREAD

**Issue by Arcanemagus** [renovatebot/config-help#217]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

The full logs can be found [here](https://renovatebot.com/dashboard#github/AtomLinter/linter-rubocop/62151613). What _appears_ to be the relevant snippets:
```
DEBUG: migrated config
{
  ...
    "ignorePaths": [
      "spec/fixtures/**"
    ]
  }
}
```
```
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Matched 2 file(s) for manager ruby-version: spec/fixtures/.ruby-version, spec/fixtures/yml2_2/.ruby-version
INFO: Found ruby-version package files
```

### What is your question?

How do I force Renovate to ignore these two configuration files, as it seems the `spec/fixtures/**` path isn't working for the `ruby-version` manager?

The [documentation for `ruby-version`](https://renovatebot.com/docs/configuration-options/#ruby-version) is... somewhat lacking, so I'm unsure how to simply disable it if that's an option. (Although I would love the Ruby versions in Travis/Circle CI to be tracked!)

**Comment by rarkins** [comment]
I just discovered that the `minimatch` glob library ignores dotfiles by default. I have added an option to override that in Renovate so your glob pattern should now work once renovate@16.5.5 goes live.

You could also disable `ruby-version` this way:

```json
{
  "ruby-version": { "enabled: false }
}
```

**Comment by rarkins** [comment]
The change I mentioned has now taken effect in your repo and the PR there is autoclosed. Thanks for bringing it to my attention

**Comment by Arcanemagus** [comment]
Thanks for fixing it so quickly as always!
