### ISSUE TITLE
[Question] Automerging - what makes a branch pending?

### ISSUE THREAD

**Issue by jeroenptrs** [renovatebot/config-help#219]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant
```
DEBUG: Checking if we can automerge branch(dependencies=["eslint-config-prettier"], branch="renovate/eslint-config-prettier-4.x")
DEBUG: mergeStatus=no automerge(dependencies=["eslint-config-prettier"], branch="renovate/eslint-config-prettier-4.x")
```

```
DEBUG: getBranchStatus(renovate/eslint-config-prettier-4.x)(dependencies=["eslint-config-prettier"], branch="renovate/eslint-config-prettier-4.x")
DEBUG: branch status check result(dependencies=["eslint-config-prettier"], branch="renovate/eslint-config-prettier-4.x")
{
  "state": "pending",
  "statuses": []
}
```

```
DEBUG: PR is configured for automerge(dependencies=["eslint-config-prettier"], branch="renovate/eslint-config-prettier-4.x")
INFO: PR is not ready for merge(dependencies=["eslint-config-prettier"], branch="renovate/eslint-config-prettier-4.x")
```

### What is your question?
I'm currently trying to set up automatic dependency management for my site/blog on Github, but I apparently can't seem to get Renovate PR's to merge by themselves. At the moment, there is no branch protection on the master branch, I've added the renovate approve bot and tried numerous things with my config, but I still can't seem to get PR's to merge.

Additionally, when I check the logs, the status of the branch appears to be pending. But there are no checks waiting whatsoever? I'm a bit lost now, so I hope you can help 🙌 

Btw: [this is my config](https://github.com/jeroenptrs/site/blob/master/renovate.json)

**Comment by rarkins** [comment]
Do you have any tests on the repo?

**Comment by jeroenptrs** [comment]
Nope

**Comment by rarkins** [comment]
Renovate defaults to cautious and only automerges of it finds passing tests. To override this, add `“requiredStatusChecks”: null` to your config

**Comment by jeroenptrs** [comment]
This did the trick! Thanks.
