### ISSUE TITLE
Order of matching against packageRules

### ISSUE THREAD

**Issue by andygnewman** [renovatebot/config-help#220]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I have a question about the order in which packagesRules are processed when they match against multiple package rules.

What I am trying to achieve is to group changes into the following grouped PRs;
- certain packages (abc components and related), whether they are dependencies or devDependencies, patches, minors or majors
- dependencies that are patch or minor
- all devDependencies

With all majors for dependencies as individual PRs.

Here is an example of my package rules in my config;
```
      "packageRules": [
        {
          "packagePatterns": [
            "^abc-components",
            "^@abc/",
            "^@abc-libs/"
          ],
          "groupName": "abc Components and Related",
          "groupSlug": "abc"
        },
        {
          "depTypeList": [
            "dependencies"
          ],
          "minor": {
            "groupName": "Minor and Patch Dependencies",
            "groupSlug": "minor-patch"
          }
        },
        {
          "depTypeList": [
            "devDependencies"
          ],
          "groupName": "Dev Dependencies",
          "groupSlug": "dev-dependencies"
        }
      ],
```

This is generally working with the exception that packages matching the `abc` packagePatterns have been included in the grouped devDependencies PR.

Does this mean that the packages get grouped into the last matching group rather than the first matching group? Or do I need to have exclude patterns in the other packageRules?

**Comment by rarkins** [comment]
All rules are applied, so this effectively means it’s the last matching group that takes effect in situations like this. 

I also recommend you use `”updateTypes”: [“minor”]` in your middle rule rather than the `”minor”: {}` syntax.

**Comment by andygnewman** [comment]
Thanks.
