### ISSUE TITLE
semanticCommitScope with parentDir not resolving (monorepo)

### ISSUE THREAD

**Issue by mcjfunk** [renovatebot/config-help#221]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
I have a monorepo and I'm trying to use `"semanticCommitScope": "{{parentDir}}"` but it is not resolving the parentDir value, resulting in `"chore():"`

packages look like:
```
packages/someModule1/package.json
packages/someModule2/package.json
```

Any thoughts?

Thanks again for the awesome product 👍

**Comment by rarkins** [comment]
@mcjfunk which version of Pro are you running? I first want to double check that its embedded Renovate version includes that `parentDir` option - it's possible it does not, but if so then I can cut a new build of Pro next week.

**Comment by mcjfunk** [comment]
We're at `0.15.3`

**Comment by rarkins** [comment]
According to git blame, it was added here: https://github.com/renovatebot/renovate/pull/3383

and release in renovate@14.51.0

Meanwhile Renovate Pro 0.15.3 includes renovate@14.19.1

I'll try to push out a new Renovate Pro in the coming week that includes this feature and everything else new.

**Comment by mcjfunk** [comment]
Thank you

**Comment by mcjfunk** [comment]
Hey @rarkins look like this was autoclosed. Could you reopen and close once complete? Thanks again.

**Comment by rarkins** [comment]
It would be better to track it now as an issue in the Pro repo though, as it relates to adding a feature to Pro rather than changing any config.
