### ISSUE TITLE
Avoid storing secrets for private maven repositories

### ISSUE THREAD

**Issue by tekumara** [renovatebot/config-help#222]
### Which Renovate are you using? CLI, App, or Pro
Renovate Bot (not sure if App or Pro)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### Have you checked the logs? Don't forget to include them if relevant

Here is my renovate.json
```
{
  "extends": [
    "config:base"
  ],
  "gradle": {
    "enabled": true
  }
}
```

My project uses some artefacts from our private maven repository, here is the relevant section in my build.gradle
 
```
buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            url 'https://artifactory.private/artifactory/libs'
            credentials {
                username artifactoryUsername
                password artifactoryPassword
            }
        }
    }
}
```
 

gradle is failing in renovate because the artificatoryUsername and artifcatoryPassword have not been specified:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/renovate/gh/tekumara/pipeline/build.gradle' line: 8

* What went wrong:
A problem occurred evaluating root project 'pipeline'.
> Could not get unknown property 'artifactoryUsername' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
```

### What is your question?

I believe it is possible to provide private repository credentials in `renovate.json`as per [Custom registry support, and authentication](https://github.com/renovatebot/renovate/blob/master/website/docs/java.md#custom-registry-support-and-authentication) but this requires storing secrets in source control which I would like to avoid. 

Is there a way to avoid storing secrets in source control, for example, configuring renovate to ignore my private repo, and therefore only detect updates from dependencies that are available on public repos?

**Comment by rarkins** [comment]
Unfortunately in this case, Gradle's behaviour is different compared to our other managers and this may not be possible. We use a Gradle plugin that we call via child process and it appears to be the one that's failing. It's possible this won't be fixable until this is implemented: https://togithub.com/renovatebot/renovate/issues/3608

BTW it's possible to *encrypt* secrets in your renovate config, that way it's pretty much impossible that anyone with access to your repo would also have access to Renovate's private key. But even still that would not help Gradle as it currently stands.

Could you also help me understand, when you are running your project locally or on CI, how are the values of `artifactoryPassword` configured/defined?

**Comment by tekumara** [comment]
Thanks @rarkins I wasn't aware that secrets could be encrypted (although you mention it's not yet possible with gradle).

When we run the build in CI we provide the username and password as project properties on the command line, with the password coming from an environment variable eg:
```
./gradlew -PartifactoryUsername=alice -PartifactoryPassword=$ARTIFACTORY_PASSWORD
```
When we run the build locally on our laptops, we have these values configured in `~/.gradle/gradle.properties`

**Comment by rarkins** [comment]
Thanks for this info. I have added it to the above issue. Regretfully, I need to close this issue for now, because it is not solvable by config.
