### ISSUE TITLE
[Question] masterApprovalIssue isn't triggering as expected

### ISSUE THREAD

**Issue by zephraph** [renovatebot/config-help#224]
### Which Renovate are you using? 

Pro

### Which platform are you using? 

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yep

### What is your question?

I'm wanting to trial the `masterIssueApproval` workflow on one of our smaller repos, but I haven't been able to get it to trigger yet. 

Here's the relevant bits from our shared config: [artsy/renovate-config](https://github.com/artsy/renovate-config/blob/master/package.json#L26-L48)

And the [repo](https://github.com/artsy/detect-responsive-traits) where it's [used](https://github.com/artsy/detect-responsive-traits/blob/874f2561ca75da4ac136581ece679d51a3f50589/renovate.json#L3). 

The master approval issue isn't showing up though and I didn't see anything about it in the log. I'm not sure if I have something miss configured.

**Comment by rarkins** [comment]
@zephraph could you add `"masterIssue": true` to the root of your config too? Although I didn't intend this to be needed, I want to first make sure that you get the master issue once you do that.

The next step would be seeing if the approval works for those npm dependencies you've included in the package rules.

One possibility is that masterIssueApproval isn't triggering the master issue when it is defined in package rules. Another possibility (please confirm if it's possible) is that it's not triggering it because there's no *updates* and hence branches matching masterIssueApproval true.

**Comment by zephraph** [comment]
I added `masterIssue` to the root, whenever that runs. 

When I run `yarn outdated` I get...

```
@types/jest 23.3.9  23.3.14 24.0.11 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git
@types/node 10.12.9 10.14.6 11.13.8 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git
danger      6.1.4   6.1.13  7.1.3   devDependencies https://github.com/danger/danger-js#readme
husky       1.1.4   1.3.1   2.1.0   devDependencies https://github.com/typicode/husky#readme
jest        23.6.0  23.6.0  24.7.1  devDependencies https://jestjs.io/
lint-staged 8.0.5   8.1.5   8.1.5   devDependencies https://github.com/okonet/lint-staged#readme
prettier    1.15.2  1.17.0  1.17.0  devDependencies https://prettier.io
ts-jest     23.10.4 23.10.5 24.0.2  devDependencies https://kulshekhar.github.io/ts-jest
ts-node     7.0.1   7.0.1   8.1.0   devDependencies https://github.com/TypeStrong/ts-node
tslint      5.11.0  5.16.0  5.16.0  devDependencies https://palantir.github.io/tslint
```

and one of the dependencies from renovate's dashboard

```json
{
   "depType":"devDependencies",
   "depName":"@types/node",
   "currentValue":"^10.12.9",
   "datasource":"npm",
   "prettyDepType":"devDependency",
   "lockedVersion":"10.12.9",
   "updates":[
      {
         "updateType":"pin",
         "isPin":true,
         "newValue":"10.12.9",
         "newMajor":10
      },
      {
         "fromVersion":"10.12.9",
         "toVersion":"10.14.6",
         "newValue":"10.14.6",
         "newMajor":10,
         "newMinor":14,
         "updateType":"minor",
         "isSingleVersion":true,
         "releaseTimestamp":"2019-04-26T19:39:25.546Z",
         "canBeUnpublished":true,
         "blockedByPin":true
      }
   ]
}
```

**Comment by zephraph** [comment]
Looks like the master issue was created: https://github.com/artsy/detect-responsive-traits/issues/27

**Comment by rarkins** [comment]
@zephraph there was indeed a bug in the logic, now fixed:

![image](https://user-images.githubusercontent.com/6311784/56859735-4461a300-698f-11e9-9586-da717f6f6eea.png)

**Comment by zephraph** [comment]
Awesome, thanks. So to confirm, now `mastersIssue` isn't needed globally?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rarkins** [comment]
Confirmed
