### ISSUE TITLE
[Question] How to change default revonate.json for all my repos

### ISSUE THREAD

**Issue by zce** [renovatebot/config-help#225]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub App

### What is your question?

Now, when I installed renovate app in GitHub, All my repos will receive a 
"Configure Renovate" onboarding PR to add `renovate.json`:

```json
{
  "extends": [
    "config:base"
  ]
}
```

How to change this default revonate.json for all my repos at the same time?

**Comment by rarkins** [comment]
It's not possible automatically yet, but I can assign this for you manually. Let me know your preferred default config and which account(s) to apply it to.

**Comment by zce** [comment]
GitHub Account: zce

preferred default config:

```json
{
  "extends": [
    "zce"
  ]
}
```

**Comment by rarkins** [comment]
This change is now done and will take effect in the next 5 minutes

**Comment by zce** [comment]
One last question, how to let renovatebot re submit the "Configure Renovate" PR

**Comment by rarkins** [comment]
Rename the existing PR, then close them and delete the branch right away. The next time Renovate runs, it should be fooled into thinking that the repository is fresh. By default, onboarding repositories are checked daily. But you can also edit the existing PRs directly, it's probably easier.

**Comment by zce** [comment]
OK
Thanks
