### ISSUE TITLE
PRs missing release notes section for monorepo

### ISSUE THREAD

**Issue by mcjfunk** [renovatebot/config-help#226]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
We have a monorepo that I recently published a couple of packages from. There is a repo that consumes those packages and renovate generated the appropriate PRs. In those PRs, I'm not seeing the collapsible "Release Notes" section or the "Source" link. I'm wondering if I need to change something in the monorepo to make that resolve correctly.

The individual monorepo packages have the "repository" setting in the package.json files that looks like this:
```
"repository": {
    "type": "git",
    "url": "https://ourEnterpriseGithub.com/someGitOrg/someRepoName/tree/master/packages/someModule"
}
```
Any help would be greatly appreciated.

**Comment by rarkins** [comment]
What type of changelog is there Eg a shared one or one per package subdirectory? And does Renovate include a correct “source” link in the PR body for those packages?

**Comment by mcjfunk** [comment]
We're using lerna and it is creating a CHANGELOG.md in each package subdirectory. No the PRs do not show the "source" link.

**Comment by rarkins** [comment]
The "official" way you should point to subdirectories for monorepos is like this example from Jest's monorepo: https://github.com/facebook/jest/blob/05b8382751b06c08113d81de757976740d4d32bf/packages/babel-jest/package.json#L5-L9

**Comment by rarkins** [comment]
Docs: https://docs.npmjs.com/files/package.json#repository

**Comment by mcjfunk** [comment]
Ok, that looks good. Sadly `npm repo babel-jest` only resolves to the base url, not to the directory. I like to point folks to the `npm repo` command for a variety of things. But truthfully, with Renovate, that is less necessary. I'll give that a try. I think the trade off is worth it. Thanks!

**Comment by rarkins** [comment]
Which version of npm? It was only supported by npm in 6.8 or 6.9 I think, although it’s possible they forgot about the repo command
