### ISSUE TITLE
Not picking up all packages in monorepo

### ISSUE THREAD

**Issue by mcjfunk** [renovatebot/config-help#228]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I have a monorepo with this structure:
```
packages/moduleA/package.json
packages/moduleB/package.json
test/harness/package.json
```
Renovate is recognizing the packages in the "packages" directory, but not finding the one in "test/harness". I've tried a variety of things such as includePaths and packageRules for that specific path without luck. Any thoughts?

Thanks again!

**Comment by rarkins** [comment]
If you use the "config:base" preset then it includes a sub-preset that ignores the most common test and examples directories. You can reset the ignorePaths back to nothing with this config: `"ignorePaths": []` (or override its contents with strings if there are some paths you still want to ignore).

**Comment by mcjfunk** [comment]
Thank you, sir.
