### ISSUE TITLE
Ignore Paths

### ISSUE THREAD

**Issue by mskian** [renovatebot/config-help#229]
I want to Ignore Renovate bot to update `Deps` on `package.json` inside the Folder /plugins/manifest/  (`package.json` File inside the manifest folder)

so add like this on `renovate.json`

which one is correct

```json
"ignorePaths": [
      "plugins/manifest/"
  ],
```

```json
"ignorePaths": [
      "plugins/manifest/package.json"
  ],
```

**Comment by rarkins** [comment]
Either should work, I recommend the second one. It can be either a string match or a glob match.

**Comment by mskian** [comment]
Thanks working...
