### ISSUE TITLE
[Question] On Prem Gitlab Go Setup

### ISSUE THREAD

**Issue by alexcurtin** [renovatebot/config-help#230]
### Which Renovate are you using?
 App or Pro, how can I tell for sure?

### Which platform are you using?
 On Prem hosted Gitlab + Bot running in K8s

### What is your question?

I cannot find a guide for setting up the bot to run for Golang projects in an on-prem GitLab installation. I also want to know if our organization is using the Pro or App version.

**Comment by rarkins** [comment]
If you're running on-prem then technically it's neither Pro nor the App - you're using Renovate OSS, I'm guessing through the `renovate/renovate` Docker Hub image?

The self-hosting guide is here: https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md

Renovate supports Go Modules out of the box - you just need to point it at a repo that's got a `go.mod`.

More details on its capabilities here: https://github.com/renovatebot/renovate/blob/master/website/docs/golang.md

**Comment by alexcurtin** [comment]
@rarkins thanks for the info - so to setup the bot to talk to our on prem github we can just configure as such https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md#gitlab-ceee ?

````
apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  renovate-platform: 'github'
# gitlab?
  renovate-endpoint: 'https://github.company.com/api/v3'
# gitlab endpoint?
  renovate-token: 'your-GITLAB?-enterprise-renovate-user-token'
  github-token: 'any-personal-user-token-for-github-com-for-fetching-changelogs'
# what about this ^
  renovate-autodiscover: 'true'```

**Comment by rarkins** [comment]
renovate-platform: set to 'gitlab'
renovate-endpoint: point it to your GitLab CE
renovate-token: personal access token of your "Renovate Bot" user
github-token: personal access token of any github.com user. If you don't have this, GitHub's API will rate limit you when you try to fetch changelogs

**Comment by alexcurtin** [comment]
but in this case, can I ignore or leave github-token blank (as i'm configuring it for gitlab?)

**Comment by rarkins** [comment]
No you can't skip it, because:

> GitHub's API will rate limit you when you try to fetch changelogs

Changelogs nearly always need to be fetched from github.com repositories

**Comment by alexcurtin** [comment]
@rarkins thanks for the help, another quick question: for `golang` go.mod updates, is there a way to tell the bot not to make PRs for Major updates (e.g. 1.0.0 -> 2.0.0) and stick to only minor/patch?

**Comment by rarkins** [comment]
Instead of disabling them completely I'd recommend putting them behind an approval step. Configure this:

```json
{
  "masterIssue": true,
  "packageRules": [{
    "managers": ["gomod"],
    "updateTypes": ["major"],
    "masterIssueApproval": true
  }]
}
```

Docs: https://renovatebot.com/blog/master-issue

**Comment by alexcurtin** [comment]
This is awesome thanks @rarkins one last question I promise! After creating the onboarding PR renovate made a blank renovate.json file to merge into the master. If I wanted to enable this before merging that, can I configure these settings on the bot side (running in Kubernetes)? Or would I adjust that renovate.json in the PR with those settings?

**Comment by rarkins** [comment]
To configure a default `renovate.json` in onboarding PRs, configure the `onboardingConfig` object in your bot's config, e.g in `config.js` or a stringified object in env variable `RENOVATE_ONBOARDING_CONFIG`. e.g. for config.js:

```js
module.exports = {
  extends: ['config:base']
}
```
