### ISSUE TITLE
How can I force pinning a specific npm dependency?

### ISSUE THREAD

**Issue by mdlavin** [renovatebot/config-help#231]
I'd like to build a shared config for projects targeting AWS Lambda Node 8.10 runtimes. The first rule I tried to implement was to pin the `aws-sdk` package at the version that is included inside the AWS Lambda Node 8.10 runtime. Here is the rule I tried:

```json
{
  "packageRules": [
    {
      "packageNames": [ "aws-sdk" ],
      "allowedVersions": "2.290.0",
      "rangeStrategy": "pin"
    }
 ]
}
```

My hope was that it would take whatever version of aws-sdk was being used by the project, reset it to 2.290.0 and then pin it at that version. However, it took the version currently used by the project and pinned the version that was already used. Is there a way to achieve what I want?

**Comment by rarkins** [comment]
I could reproduce this and "fix" it: https://github.com/renovatebot/renovate/pull/3656

But I still need to think if it will have any unintended consequences before I merge.

**Comment by rarkins** [comment]
Here's the working PR: https://github.com/renovate-tests/pinallow/pull/4

**Comment by mdlavin** [comment]
> But I still need to think if it will have any unintended consequences before I merge.

I had the thought that it would be nice to have a database of configurations, maybe anonymized, so that you could see the impact of a change
