### ISSUE TITLE
[Question] How to pickup new version of Guava that is tagged "*-jre"?

### ISSUE THREAD

**Issue by jamesmmchugh** [renovatebot/config-help#232]
### Which Renovate are you using? CLI, App, or Pro
OSS Docker image

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
Renovate is picking up my maven pom correctly and is suggesting version updates for most packages correctly. However, the Guava package is tagged with either '*-jre' or '*-android' depending on the target platform (i.e. https://mvnrepository.com/artifact/com.google.guava/guava). It seems like it should be possible to configure renovate to detect this (perhaps using the unstable / followtag related config options) but i cannot figure out a working example. Any help would be appreciated.

An interesting side point is that the maven versions plugin picks up the newer version of Guava correctly (I had assumed renovate would be using this under the hood, but perhaps that assumption is wrong).

**Comment by rarkins** [comment]
This is interesting. Ironically, our docker versioning might actually work on this. But I'm interested in first understanding the problem at its cause. Are you aware of anything in the Maven spec that indicates the `-jre` or `-android` suffix indicates compatibility? We implemented from scratch according to the Maven spec.

I'm *wondering* if the compatibility is not truly in the name but contained within metadata about each release in the maven registry, and maybe we need to filter on that before evaluating versions. Is there anything else in your `pom.xml` that indicates that JRE packages would be compatible and Android ones not, apart from the suffix in the guava version?

**Comment by rarkins** [comment]
Seems like there was a big discussion here: https://github.com/google/guava/issues/2914

**Comment by rarkins** [comment]
Are you using jre or android?

**Comment by jamesmmchugh** [comment]
Hi @rarkins i'm using the jre variant.

**Comment by jamesmmchugh** [comment]
And in answer to your previous question; in our pom there is nothing else to denote compatibility but i haven't checked the metadata of the dependency itself to see if there's anything there. Interestingly this issue seems to have been raised before, but for gradle: https://github.com/renovatebot/renovate/issues/2838

The PR is closed but not really explained well in the comments from what I can see.

**Comment by rarkins** [comment]
In short it looks like Google are doing Maven versioning "wrong" for guava. The [doc](https://docs.google.com/document/d/1NYGbfz56C0Oh4IGymXjeQUVK4FcRiqDbpc4vGLnDMrY/edit#) linked to in that issue confirms that "x.y.z-jre" is indeed the "latest" in Maven-speak, so it's no surprise if a Renovate user with Android currently gets changed to JRE. My only surprise is how the versions plugin is handling it.

I wouldn't expect to see you getting switched from jre to android if both exist with the same version.

Also, more info hinted at here in the maven versions plugin: https://github.com/mojohaus/versions-maven-plugin/issues/157

**Comment by jamesmmchugh** [comment]
@rarkins sorry, i think I have explained poorly. I am not getting switched from -jre to -android. It's that it is not picking up the latest version regardless. i.e. in my pom I have version `27.0-jre` and renovate is not picking it up for upgrade to `27.1-jre`, which is the latest version.

**Comment by jamesmmchugh** [comment]
This is my pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.4.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.test.renovate</groupId>
	<artifactId>renovate-test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>renovate-test</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>27.0-jre</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.1</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

```

And this is what renovate picks up for upgrading:

`Update dependency com.google.code.gson:gson to v2.8.5`

But is missing Guava.

**Comment by jamesmmchugh** [comment]
And just to verify, this is the mvn version plugin output:

```
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   com.google.code.gson:gson ............................. 2.8.1 -> 2.8.5
[INFO]   com.google.guava:guava .......................... 27.0-jre -> 27.1-jre
[INFO]   io.projectreactor:reactor-test ............. 3.2.8.RELEASE -> 3.3.0.M1
[INFO]
[INFO] artifact org.springframework.boot:spring-boot-maven-plugin: checking for updates from gamesys-pe-maven
[INFO] artifact org.springframework.boot:spring-boot-maven-plugin: checking for updates from gamesys-snapshots
[INFO] artifact org.springframework.boot:spring-boot-maven-plugin: checking for updates from all-external-maven
[INFO] The following dependencies in pluginManagement of plugins have newer versions:
[INFO]   org.springframework.boot:spring-boot-maven-plugin ...
[INFO]                                                2.1.4.RELEASE -> 2.2.0.M2
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19:02 min
[INFO] Finished at: 2019-05-13T12:52:47+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by jamesmmchugh** [comment]
I managed to get it to detect the update by adding the following:

```
"packageRules": [
    {
      "managers": ["maven"],
      "packageNames": ["com.google.guava:guava"],
      "ignoreUnstable": false
    }
  ]
```

It's not a great solution though as potentially it will pickup the `-android` builds (and any future odd builds) also, depending on what order they are tagged in. It would be nice if renovate had an option like  `stablePattern` to complement `unstablePattern` (which is also just for docker atm). Or if it used the same detection as the mvn versions plugin for updates.

**Comment by rarkins** [comment]
OK yes, in that case I recommend ignoreUnstable as a pretty reliable fix for now considering how they are doing their versioning. Although -android will be picked up in the list of "candidate" upgrades, the -jre ones should always be sorted higher and picked instead. This would not work for someone who's using -android.

**Comment by jamesmmchugh** [comment]
@rarkins Are there any plans to expose a way to configure a custom version schema (i.e. using regex) going forward?

**Comment by jamesmmchugh** [comment]
As it would be pretty easy to express such i.e. `(?<major>\d+)/.(?<minor>\d+)-jre`

**Comment by rarkins** [comment]
I wouldn't say there's plans, but I am hoping to use named regexes like this for version scheme as well as datasources too (probably datasources first, as it's a far more common use case).

Out of interest, does your example work if you use our "docker" versioning?

```json
"packageRules": [
    {
      "managers": ["maven"],
      "packageNames": ["com.google.guava:guava"],
      "versionScheme": "docker"
    }
  ]
```

It will explicitly match -jre to -jre, same way docker images match -alpine to -alpine

**Comment by jamesmmchugh** [comment]
@rarkins the docker schema seems to work also. Datasources + named regexes would be very nice, great tool in general by the way.

**Comment by rarkins** [comment]
Thanks for confirming! Would you believe that Guava came up in a discussion this morning about versioning in Maven and I was able to say "Yes, I'm familiar with that one"?
