### ISSUE TITLE
[Question] Custom versionScheme for docker images

### ISSUE THREAD

**Issue by pyaillet** [renovatebot/config-help#235]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### What is your question?
Hi, thank you for making renovate, it's awesome :)

We're using some custom tag version policy for packaging build or middleware images, as such:
```
docker/jdk/production/jdk:X.Y.Z-P-B
X, Y, Z: Major, Minor, Patch of the packaged software
P: Patch of our embedded tooling/integration
B: Build number
```
What would be the best way to make renovate support such scheme ?
1. Is there an extension mechanism to add custom versioning scheme ?
2. Could we add a custom version scheme and make it usable via config ?
3. Should we fork renovate and customize docker versioning scheme to suit our needs ?
I'm not a big fan of this last one... :\

I know we should remove the `-P-B` part of your versioning to make it fit with renovate scheme. We could for the build part, but it's not an option for our own patch integration as some project relies on it, and we want to keep track of what's used.

WDYT ?

**Comment by rarkins** [comment]
You can change the default version scheme for a package using packageRules. The list of ones we support are here: https://github.com/renovatebot/renovate/tree/master/lib/versioning

You could try using the maven versioning for this, it might work:

```json
{
  "packageRules": [{
	"packageNames": ["docker/jdk/production/jdk"],
    "versionScheme": "maven"
  }]
}
```

I'm not sure if that package name is right btw

**Comment by pyaillet** [comment]
I'll try that ! Thanks a lot :)

**Comment by pyaillet** [comment]
It works 👍

**Comment by rarkins** [comment]
Awesome!
