### ISSUE TITLE
[Question] How to setup more than one host for the same platform ?

### ISSUE THREAD

**Issue by pyaillet** [renovatebot/config-help#240]
### Which Renovate are you using? CLI, App, or Pro
renovate cli

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
gitlab

### Have you checked the logs? Don't forget to include them if relevant
with this in my config.js:
```json
  hostRules: [
    {
      platform: 'docker',
      host:     'myregistry.internal:4567',
      username: 'piail',
      password: '<password>',
    },
    {
      platform: 'docker',
      host:     'docker.io',
    },
  ],
```

I end up with this in platforms object (used in host-rules, I added logs):
```json
       "platforms": {
         "docker": {"platform": "docker", "host": "docker.io"},
         "gitlab": {
           "gitlab.internal": {
             "name": "GitLab",
             "endpoint": "https://gitlab.internal/api/v4/",
             "platform": "gitlab",
             "username": null,
             "password": null,
             "token": "<TOKEN>",
             "default": true
           }
         }
       }
```

### What is your question?
How to setup more than one host for the same platform ?
I want to use different credentials for docker platform for different host.

Thank you !

**Comment by rarkins** [comment]
Why define the docker.io one at all if you don't add username/password?

**Comment by pyaillet** [comment]
If I don't define it, it uses credentials of my internal registry instead of using anonymous access.

**Comment by rarkins** [comment]
It shouldn't do that if you've defined a host for the one you add to hostRules. It's a bug if so

**Comment by pyaillet** [comment]
I opened an issue #3743 and the corresponding PR #3744

**Comment by rarkins** [comment]
@pyaillet let's discuss in https://github.com/renovatebot/renovate/issues/3743
