### ISSUE TITLE
[Question] Artifact update problem resurfaced

### ISSUE THREAD

**Issue by cmschuetz** [renovatebot/config-help#242]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yes, new logs are looking similar to the ones specified in these issues:

https://github.com/renovatebot/renovate/issues/3551
https://github.com/renovatebot/config-help/issues/211

### What is your question?

Have there been any recent changes that could be causing this?  Any changes required on my end?  Is the cause the same as the previous issues?

**Comment by rarkins** [comment]
What type of artifacts?

**Comment by cmschuetz** [comment]
Here's a screenshot of the comment:

![DeepinScreenshot_select-area_20190520131758](https://user-images.githubusercontent.com/4479762/58042987-b9914580-7b01-11e9-9ce3-f2e9e7c32900.png)

Checking the logs, it errors out at that same spot, `"Failed to replace env in config: ${NPM_TOKEN}"`.  These symptoms look identical to the ones observed in the linked issues

**Comment by rarkins** [comment]
Thanks for the extra details, I'll take a look

**Comment by rarkins** [comment]
Can you email support@renovatebot.com and let me know which repository to look at and what the approximate *commit time* was for this artifact problem? You can hover over the "an hour ago" text on GitHub and see a timestamp.

**Comment by cmschuetz** [comment]
Yup, will do

**Comment by rarkins** [comment]
I think this is now resolved
