### ISSUE TITLE
[Question] Remove labels from an inherited config?

### ISSUE THREAD

**Issue by funkadelic** [renovatebot/config-help#243]
### Which Renovate are you using? CLI, App, or Pro
pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
github enterprise

### What is your question?
Our config is extended from a common config that places labels on the PR, eg.

```
      "patch": {
        "labels": [
          "patch",
          "automerge",
          "dependency-update"
        ]
      }
```

Is there a way for my repo-specific config to remove say the `automerge` label? Do I just copy the config and simply remove `automerge` like so from the `labels` array -- will this overwrite the parent config or is it merged with the parent array?

```
      "patch": {
        "labels": [
          "patch",
          "dependency-update"
        ]
      }
```

**Comment by rarkins** [comment]
@funkadelic yes, you should be able to overwrite them the way you describe. The `labels` config option is not defined as "mergeable", meaning that it overwrites, but you need to make sure that the *specificity* of your overwriting matches that which you're inheriting. If you try the way you suggest and it doesn't work, please let us know.
