### ISSUE TITLE
[Question] Config.js ignored

### ISSUE THREAD

**Issue by Rahe** [renovatebot/config-help#244]
Hello ,

### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket cloud

### Have you checked the logs? Don't forget to include them if relevant
Here is my config.js file :
```
module.exports = {
  platform: 'bitbucket',
  username: 'username'
  password:'password'
  logFileLevel: 'warn',
  logLevel: 'info',
  logFile: '/Users/nicolasjuen/renovate.log',
  onboarding: true,
  gitAuthor: "Renovate Bot <bot@renovateapp.com>"
  onboardingConfig: {
    extends: ['config:base'],
  },
  repositories: [ 'company/rep-name' ],
};
```

When I run on the folder containing the config.js file :
`renovate`
I have
`FATAL: You must configure a GitHub personal access token`

If I run 
`RENOVATE_CONFIG_FILE=/Users/nicolasjuen/.renovate/config.js renovate`
I have
`FATAL: You must configure a GitHub personal access token`

The only way I have this working is to specify 
--password
--username
--platform
and the repo at the end...

Why is my file ignored ?

**Comment by rarkins** [comment]
Hi @Rahe, I think what you need is to configure `GITHUB_COM_TOKEN` in env. See https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md#githubcom-token-for-release-notes for details

In short: your config is not ignored, it's just that you need a GitHub token *in addition* in order to be able to fetch release notes reliably.

**Comment by Rahe** [comment]
Hi @rarkins ,

Thank you for the quick response.
But i'm not using github but bitbucket here.

If i'm running
`renovate --password=password --username=username --platform=bitbucket user/repository`

This is working :)

**Comment by rarkins** [comment]
@Rahe if you copy/pasted that `config.js` in then it's probably because you're missing commas at the ends of the username, password, and gitAuthor lines. I had assumed those were just copy/paste errors when you sanitized it but please check your original file that all lines have commas.

**Comment by Rahe** [comment]
Hello,

I was really missing ',' at the end ! but no effect...
Is there any "verbose" or "debug" mode ? that can display all the steps done by the cli ?

I have followed this documentation https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md#usage, followed some parts here https://renovatebot.com/blog/bitbucket-cloud

**Comment by rarkins** [comment]
Please paste your updated `config.js` here with complete care that the only modifications you make are to the password. For now, remove all log configuration elements from your config and instead run with `LOG_LEVEL=debug renovate ...` for DEBUG logging.

**Comment by Rahe** [comment]
Hello,

Here is the complete file

```
module.exports = {
  platform: 'bitbucket',
  username: 'rahe',
  password:'password',
  onboarding: true,
  gitAuthor: "Renovate Bot <bot@renovateapp.com>"
  onboardingConfig: {
    extends: ['config:base'],
  },
  repositories: [ 'beapi/deploy-test' ],
};
```

Here what the bash is returning
```
ls
config.js*
nicolasjuen@MacBook-Pro-de-Nicolas-2:~/.renovate $ LOG_LEVEL=debug renovate
DEBUG: Initializing Renovate internal cache into /var/folders/ks/lc8_fxv96j5ddt2ldrf5pkkh0000gn/T/renovate/renovate-cache-v1
DEBUG: Parsing configs
DEBUG: No config file found on disk - skipping
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": [], "logLevel": "debug"}
DEBUG: Combined config
       "config": {"hostRules": [], "logLevel": "debug"}
FATAL: You must configure a GitHub personal access token
```

**Comment by Rahe** [comment]
With de config file forced 
```
LOG_LEVEL=debug RENOVATE_CONFIG_FILE="/Users/nicolasjuen/.renovate/config.js" renovate
DEBUG: Initializing Renovate internal cache into /var/folders/ks/lc8_fxv96j5ddt2ldrf5pkkh0000gn/T/renovate/renovate-cache-v1
DEBUG: Parsing configs
DEBUG: No config file found on disk - skipping
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {"hostRules": [], "logLevel": "debug"}
DEBUG: Combined config
       "config": {"hostRules": [], "logLevel": "debug"}
FATAL: You must configure a GitHub personal access token
```

**Comment by rarkins** [comment]
You're still missing a comma at the end of the `gitAuthor` line

**Comment by Rahe** [comment]
oh :( my IDE haven't even considered to point that out...
Is this on the roadmap to have error on bad syntax ?

I'm glad this is a PEBKAC, shame on me ! ^^

Thank you for the support !

**Comment by rarkins** [comment]
Right now we just try/catch requiring the file, so it doesn’t distinguish between file existing or not existing. I think we should halt and error if it exists but can’t be read.

**Comment by Rahe** [comment]
This can be useful yes, thank you again ;)

**Comment by mountainash** [comment]
I was getting this same error, but for the following "bad" JSON in my "config.js"

```js
onboardingConfig: {
		{
			extends: ['gitlab>renovate-bot/shared-config']
		}
	}
```

Adding validation for "config" would be helpful to catch theses issues + remove the confusing when the error message from @renovatebot doesn't match what they actual error is. In my case "token" was set - but the error message was telling me it wasn't.
