### ISSUE TITLE
Provide a preset via the bot configuration

### ISSUE THREAD

**Issue by eladchen** [renovatebot/config-help#246]
**What would you like Renovate to be able to do?**
Allow defining a preset via the "Self Hosted Configuration" - as opposed to having to publish the preset to some registry / repository.

**Describe the solution you'd like**
Right now, the only way to use a preset, is to to publish it somewhere.
If "Self Hosted Configuration" was added with another config, say "preset"
And that preset is a simple object literal, it could merged to any renovate.json (or its variants) ONLY if such file exists in the processed repository — Otherwise the "requireConfig" breaks.

**Additional context**
Using the solution above, might provide a lot less overhead.
* Publishing a preset is a project on it own.
* Solves the chicken-egg problem, where a preset with secrets cannot be retrieved.

**Comment by eladchen** [comment]
@rarkins 

Well apparently the repo I was using for testing had a ".npmrc" with bad values, and that is what caused the confusion.

I appreciate the time you took for looking into this !

P.S - In such cases where the repo has a file & the bot has an "npmrc" config
Should the repo one prevail? Perhaps it should be merged..?

**Comment by rarkins** [comment]
There is an ignoreNpmrcFile setting you can enable if you want Renovate to ignore the file in the repo. I would have expected the configured one to override the repo one though

**Comment by eladchen** [comment]
If there is such a config, it makes more sense the way it works now, as it allows a find-grain controller over the behaviour.

**Comment by rarkins** [comment]
Ideally we automate where we can though. For instance if your npmrc in the repo contains variables then we ignore it implicitly. Anyway, I will close this now. Good luck
