### ISSUE TITLE
I manually added the renovate.json file to my repo, no PR's yet

### ISSUE THREAD

**Issue by veronicacuello** [renovatebot/config-help#247]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant

no logs yet

### What is your question?
I manually added the renovate.json file to my repo, Why am I not seeing any PRs from renovate yet?

**Comment by rarkins** [comment]
Perhaps related: https://www.githubstatus.com/incidents/nf4gcjtcsqdb

**Comment by rarkins** [comment]
Actually, the Renovate backend has no record of any repositories belonging to you. Did you install the app via https://github.com/apps/renovate ?

**Comment by veronicacuello** [comment]
It is working now, maybe was a delay as you mentioned. Thanks
