### ISSUE TITLE
[Question] How to skip "reviewed" status check on GitHub when auto-merging

### ISSUE THREAD

**Issue by jamesmmchugh** [renovatebot/config-help#248]
### Which Renovate are you using? CLI, App, or Pro
Docker OSS

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I have a GitHub repo that requires several status checks: sonarqube, branch build and requires review. I want to configure Renovate to honour the sonarqube and branch build checks, but ignore the review (or do a self review) when deciding to auto-merge or not. Is this possible?

**Comment by jamesmmchugh** [comment]
One thing of note "requires review" is part of GitHub's protected branch feature - it's not strictly a status check. I can't find any config relevant to this in Renovate's docs.

**Comment by rarkins** [comment]
Install GitHub.com/renovate-approve

**Comment by jamesmmchugh** [comment]
@rarkins thanks, are there any instructions for how to do this against GitHub Enterprise?

**Comment by rarkins** [comment]
Oh sorry, I forgot you were self hosted. The source code is here in case you want to try hosting it yourself: https://github.com/renovatebot/renovate-approve-bot

BTW no user/bot has the authority to ignore branch protection unless they’re a repo admin, so we haven’t added the option to automerge without approval.

**Comment by jamesmmchugh** [comment]
@rarkins thanks, i'll give it a go and close this for now.
