### ISSUE TITLE
[Question] What classifies a 'pending' branch?

### ISSUE THREAD

**Issue by jamesmmchugh** [renovatebot/config-help#249]
### Which Renovate are you using? CLI, App, or Pro
Docker OSS

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

`INFO: PR is not ready for merge (branch status is pending) (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)`

### What is your question?
I am seeing the log above when running renovate, however on the PR I see the following:
![Screenshot 2019-05-23 at 14 36 48](https://user-images.githubusercontent.com/8694232/58257280-8ac8d880-7d68-11e9-81db-c284286a442b.png)
![Screenshot 2019-05-23 at 14 36 15](https://user-images.githubusercontent.com/8694232/58257301-94524080-7d68-11e9-961b-b7b4f11d36c6.png)

It appears to me that all status checks have passed, the PR has been reviewed and is ready for merge, and yet Renovate won't do the auto-merge. Am i missing something in my config? What is the definition of a pending branch in Renovate's domain?

**Comment by jamesmmchugh** [comment]
Current config:

```
{
  "extends": [
    "config:base",
    "schedule:nonOfficeHours",
    ":prHourlyLimitNone"
  ],
  "packageRules": [
    {
      "managers": [
        "maven",
        "dockerfile",
        "docker-compose"
      ],
      "automerge": true
    }
  ]
}
```

**Comment by rarkins** [comment]
Of you log at debug level you should see some info about why the status checks were pending

**Comment by jamesmmchugh** [comment]
@rarkins this is as much info as I can see in logs:

```
DEBUG: branch status check result (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
       "state": "pending",
       "statuses": []
DEBUG: Processing existing PR (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
DEBUG: getBranchStatus(renovate/org.apache.maven.plugins-maven-rar-plugin-2.x) (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
DEBUG: branch status check result (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
       "state": "pending",
       "statuses": []
DEBUG: getBranchStatus() result (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
       "branchStatus": "pending",
       "branchName": "renovate/org.apache.maven.plugins-maven-rar-plugin-2.x"
DEBUG: Pull Request #3 does not need updating (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
DEBUG: Checking #3 for automerge (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
 INFO: PR is not ready for merge (repository=REDACTED/redacted, dependencies=org.apache.maven.plugins:maven-rar-plugin, branch=renovate/org.apache.maven.plugins-maven-rar-plugin-2.x)
```

It's still not clear to me why the status is pending, looks like `status:[]` should mean it's ok to merge. Any ideas?

**Comment by rarkins** [comment]
empty statuses could also mean that your CI system hasn’t yet posted a pending status when the build starts. For instance yesterday there was a backlog of webhooks from GitHub which would have meant empty statuses for many repos that normally have them.

If you have no status checks and want to automerge without them, add `requiredStatusChecks: null` to your config. It means we don’t even check statuses before automerging.

**Comment by jamesmmchugh** [comment]
This repo has no status checks, so it's definitely not CI system not posting them. It seems like a bug to me.

I'm hesitant to use `requiredStatusChecks: null` because if we add status checks in the future we will have to remember to remove this.

**Comment by rarkins** [comment]
It’s a deliberate feature. Renovate won’t automerge branches with empty status checks unless you tell it to. Even if we introduced a “ignore empty status checks” feature instead then it would still be risky because all branches start with empty status checks and you may see them merged before tests start. 

Closing this now as the config solution has been given. Please raise a feature request to the main repo if you would like to suggest a new way to do things.

**Comment by jamesmmchugh** [comment]
Feature request with suggestion: https://github.com/renovatebot/renovate/issues/3802

**Comment by rarkins** [comment]
Thanks
