### ISSUE TITLE
[Question] Scope update PRs to NPM org?

### ISSUE THREAD

**Issue by mwickett** [renovatebot/config-help#251]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
This might be an unusual use case, but wondering if it's possible to limit Renovate update PRs to a specific NPM organization.

**Comment by rarkins** [comment]
Sure, can you give more details? e.g. do you mean you only want to update dependencies that are like `@foo/*` ?

**Comment by mwickett** [comment]
Yes, exactly that.

**Comment by rarkins** [comment]
I think this should work:

```json
{
	"enabledManagers": ["npm"],
	"packageRules": [{
		"excludedPackagePatterns": ["^@foo/"],
		"enabled": false
	}]
}
```

It first of all disables all managers except npm, and then it disables all packages except the ones starting with `@foo/`

**Comment by mwickett** [comment]
Thanks!

**Comment by mwickett** [comment]
Do I need to `extend:base` with the above rules? Or is that the entire config?

**Comment by rarkins** [comment]
config:base won't make much functional difference to you if you're only updating your own scope's dependencies. The only real effect it would have is to rate limit you to 2 new PRs per hour and 20 concurrently.

**Comment by mwickett** [comment]
That's what I thought, thanks for confirming. 

So I've created a shared config here: https://github.com/hashicorp/renovate-configs/blob/master/only-hashicorp.json and am consuming it in a project (private repo) like this:

`renovate.json`:

```
{
  "extends": ["github>hashicorp/renovate-configs:only-hashicorp"]
}
```

But the repo has received a number of PRs for other packages that are not scoped to `@hashicorp`. I'm not clear on why this isn't working, and would really appreciate any thoughts. Thanks!

**Comment by rarkins** [comment]
Sorry, can you try that again with `excludePackagePatterns` rather than `excludedPackagePatterns`? What I gave you has a one character typo (extra `d`)

**Comment by mwickett** [comment]
Ah, that's on me for not verifying. Thanks for the PR 👍🏻
