### ISSUE TITLE
[Question] Burning through github rate limit

### ISSUE THREAD

**Issue by QuentinMoss** [renovatebot/config-help#252]
### Which Renovate are you using? CLI, App, or Pro
Self hosted kubernetes

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
We are slowly onboarding more teams to renovate and i'm noticing with 21 repos we are burning through the 5000 request/hr in githubs api. I'm just wondering if there a configuration issue, or if renovate is really generating that many requests each call. 

I'm running the cron every 5 minutes because teams would like the automated rebasing to happen more frequently. 

Do you have any suggestions?

Here's my config

```
{
..
  },
  "scripts": {
    "validate": "renovate-config-validator"
  },
  "renovate-config": {
    "default": {
      "extends": [
        "config:base",
        ":preserveSemverRanges",
        ":rebaseStalePrs",
        ":semanticCommits",
        ":semanticCommitTypeAll(chore)",
        ":prHourlyLimit4"
      ],
      "major": {
        "enabled": false
      },
      "prConcurrentLimit": 3,
      "schedule": [
        "before 6am every weekday"
      ],
      "timezone": "America/Los_Angeles",
      "rangeStrategy": "bump",
      "dockerfile": {
        "enabled": false
      },
      "circleci": {
        "ignoreDeps": [
          "circleci/node"
        ]
      },
      "packageRules": [
        {
          "datasources": [
            "orb"
          ],
          "enabled": false
        },
        {
          "packageNames": [
            "@org/package"
          ],
          "updateTypes": [
            "major"
          ],
          "enabled": false
        },
        {
          "depTypeList": [
            "dependencies"
          ],
          "semanticCommitType": "fix"
        },
        {
          "depTypeList": [
            "devDependencies"
          ],
          "groupName": "devDependencies",
          "separateMajorMinor": false,
          "separateMinorPatch": false
        }
      ],
      "patch": {
        "groupName": "patchReleases"
      },
      "separateMinorPatch": true
    }
  },
  "dependencies": {},
  "devDependencies": {
    "renovate": "^17.7.9"
  }
}
```

**Comment by wyardley** [comment]
Also, I assume if we used the `gitFs` backend option, that should reduce the number of API calls?

**Comment by rarkins** [comment]
5 minute intervals will definitely burn through your API limit.

`gitFs` will reduce the number of API calls, and it's actually about to be made the default and only option in v18 of Renovate next week.

But otherwise I would of course recommend you consider [Renovate Pro](https://renovatebot.com/pro) if you have teams interested in responsiveness to webhooks.

**Comment by QuentinMoss** [comment]
@rarkins thanks for the info. Also, we are looking at Renovate Pro ;)
