### ISSUE TITLE
Is it possible to point at a renamed package.json file?

### ISSUE THREAD

**Issue by tanem** [renovatebot/config-help#254]
### Which Renovate are you using? CLI, App, or Pro

App.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub.

### Have you checked the logs? Don't forget to include them if relevant

Yes, can see Renovate is not picking up my hacky attempts to get this to work.

### What is your question?

I maintain [a Yeoman generator](https://github.com/tanem/generator-typescript-react-lib), and it contains a template for a `package.json` file called [`_package.json`](https://github.com/tanem/generator-typescript-react-lib/blob/master/generators/app/templates/_package.json).

Is it possible to get Renovate to maintain that `_package.json` file?

Renovate is already maintaining the main `package.json` file, but I'm hoping it can maintain both. [I tried using `paths`](https://github.com/tanem/generator-typescript-react-lib/blob/master/renovate.json#L6), but to no avail.

FWIW I'm still not completely sure if this is a good idea, but am curious if this is possible :wink:

Thanks!

**Comment by rarkins** [comment]
Yes, check `fileMatch`

**Comment by rarkins** [comment]
```
{
  “npm”: {
    “fileMatch”: [“package\\.json$”]
  }
}
```

This might work

**Comment by tanem** [comment]
Thanks, I'll try that when I'm back home later tonight :+1:

**Comment by tanem** [comment]
@rarkins your suggestion seems to be working nicely, thanks! :tada:

**Comment by rarkins** [comment]
By the way that fileMatch pattern is intended to catch any file ending in `package.json` so that if you have any actual `package.json` files then they're still included, along with the `_package.json`
