### ISSUE TITLE
[Question] Private npm repository for docker

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/config-help#255]
### Which Renovate are you using? CLI, App, or Pro
Docker

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant
```
 INFO: Failed to look up dependency @redacted/redacted-plugin-interface (repository=redacted/redacted-angular, packageFile=package.json, dependency=@redacted/redacted-plugin-interface)
 INFO: Dependency lookup failure: not found (repository=redacted/redacted-angular)
       "depName": "@redacted/configs"
 INFO: Failed to look up dependency @redacted/configs (repository=redacted/redacted-angular, packageFile=package.json, dependency=@redacted/configs)
```

### What is your question?
I'm assuming the reason it `failed to look up dependency` is because the packages in question are stored on a private artifactory server instead of the public npm.

When using the docker image option (https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md) how do you configure npm to point to your private npm server instead of the public one?

**Comment by rarkins** [comment]
You do this by adding a `npmrc` option to your config. If the private Artifactory should apply to ever repository then add it to a `config.js` (mounted inside your container) or via env `RENOVATE_NPMRC`. Do you also need auth for the server?

**Comment by k2snowman69** [comment]
I would probably need auth for the server as well. I believe I found the documentation here
https://renovatebot.com/docs/private-modules/#addauthenticate-the-renovate-npm-user-to-your-private-npm-modules

Let me give this a shot and I'll re-open if I need to. Thanks @rarkins!
