### ISSUE TITLE
[Question] Confused about priority and config preset/merging strategy

### ISSUE THREAD

**Issue by gremo** [renovatebot/config-help#257]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
Not relevant in this case.

### What is your question?
I'm a lot confused about presets, configuration options and merging strategy. What I'm trying to accomplish here is:

- Only pin **dependencies**
- For **devDependencies**, version should be updated like I would do manually: i.e. `^1.1.0` -> `^1.2.0` (it should be the "bump" option); both `package.json` and `package-lock.json` should be updated
- For **peerDependencies**, renovate should be disabled
- Patch version should always be automatically merged without human intervention (boh for **dependencies** and **devDependencies**)
- PR must be opened after 24h of the new dependency version

```json
{
  "extends": [
    "config:base",
    ":automergePatch",
    ":disablePeerDependencies"
  ],
  "packageRules": [
    {
      "depTypeList": ["devDependencies"],
      "rangeStrategy": "bump"
    }
  ]
}
```

If I understand how renovate works my renovate.json:

1. Extends [config:base](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-config/package.json#L16) which contains some defaults [presets](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-default/package.json#L15)
2. I'm adding `:automergePatch` and `:disablePeerDependencies` which takes precedence over the base configuration
3. Anything after extend will take precedence over the resulting configuration

**Comment by rarkins** [comment]
`config:base` contains a few embedded rules about dep types, so it can sometimes be a good idea to remove it and replace it with the sub-presets inside it that you need.

Importantly, config:base defaults to rangeStrategy=auto, which actually means pinning *devDependencies* and not *dependencies*, unless we can be sure that your `package.json` is for an app not library. I think it would be easiest for you to put a package rule for each to make it explicit.

To achieve `PR must be opened after 24h of the new dependency version` I'd recommend a combination of `:unpublishSafe` and `prNotPending` to achieve the same. It means:
- Renovate will add a "pending" status check to all commits if they contain an update that is < 24 hours old
- Renovate won't open PRs until PRs are no longer pending

Note though:
- If your tests fail for an update, then it's no longer pending - it's "failed" - and so the PR will be created < 24 hours after the publish
- If a newer version of the dependency being updated is released *after* the PR is created, the PR/branch will go back to "pending" status but not be closed

Here is the result:

```
{
  "extends": [
    "config:base",
    ":automergePatch",
    ":disablePeerDependencies",
    ":unpublishSafe",
    ":prNotPending"
  ],
  "packageRules": [
    {
      "depTypeList": ["dependencies"],
      "rangeStrategy": "pin"
    },
    {
      "depTypeList": ["devDependencies"],
      "rangeStrategy": "bump"
    }
  ]
}
```
