### ISSUE TITLE
Config validator not triggering?

### ISSUE THREAD

**Issue by spalger** [renovatebot/config-help#258]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: PR has renovate files
{
  "prNo": 37606,
  "title": "Renovate - define renovate specific labels",
  "renovateFiles": [
    "renovate.json5"
  ]
}
INFO: branch no longer exists - aborting
{
  "branchName": "f7e27f76d8b626543331998e1b84d0f7b4120fd5"
}
INFO: branch no longer exists - aborting
{
  "branchName": "configure-renovate"
}
INFO: Cannot access PR files to check them
```

from https://renovatebot.com/dashboard#github/elastic/kibana/69968193
re https://github.com/elastic/kibana/pull/37606

### What is your question?

Is there something wrong with the way I've formatted my issue that is preventing renovatebot from spotting it and validating the updated config it contains? Maybe it's because I'm using the `renovate.json5` filename?

**Comment by spalger** [comment]
I think this might be because I'm reusing an old branch?

**Comment by rarkins** [comment]
It might be because the PR is coming from a fork of the repo and not from a branch within the repo. This is something we *tried* to code around originally but may not still be working now that we've migrated to a more git-based file retrieval approach rather than API. I'll take a look at the logic and try to work out if that's the cause.

**Comment by rarkins** [comment]
Confirmed. Sorry, for now it's essentially "expected behaviour" and is going to require this to be fixed/implemented: https://github.com/renovatebot/renovate/issues/3851
