### ISSUE TITLE
[Question] How can I set opts.pageLimit

### ISSUE THREAD

**Issue by vinicius-tona** [renovatebot/config-help#259]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
Not necessary

### What is your question?
Is there a way I can set this value? with the current default value of 10 the autodiscovery only analyzes up to 1000 repositories  

https://github.com/renovatebot/renovate/blob/master/lib/platform/github/gh-got-wrapper.js#L53

**Comment by rarkins** [comment]
set `process.env.RENOVATE_PAGINATE_ALL=true` and it should skip the 10 page pagination limit.

**Comment by vinicius-tona** [comment]
That's true! Thanks for the update I completely missed it
