### ISSUE TITLE
[Question] Renovate doesn't update yarn.lock, what am I doing wrong?

### ISSUE THREAD

**Issue by deiga** [renovatebot/config-help#261]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yeah, couldn't see anything relevant

### What is your question?

We can't get Renovate to add yarn.lock updates to our PR's. 
Could you take a look at our config? https://github.com/wunderdogsw/proem/blob/master/renovate.json

**Comment by rarkins** [comment]
Hi @deiga, thanks for trying out Renovate. I believe that https://github.com/wunderdogsw/proem/pull/114 should fix the problem. Can you merge it and then rebase a PR after that to check?

I'll try to later add a check to Renovate's lerna logic to detect this scenario too because it's the second time I've seen it.

**Comment by deiga** [comment]
@rarkins Thank you!
In a sense that was the issue! It made us notice that the lerna config was a leftover :)

**Comment by deiga** [comment]
Now that the initial hitches have been solved Renovatebot looks awesome! We've been having pains with Dependabot as it wasn't able to group PR's.

Based on this issue, it would have been great if Renovatebot could have somehow told us which all files it had detected that affected its behaviour.

**Comment by rarkins** [comment]
There's really too much logic going on to put it all in a PR without confusing everyone, but if you check out https://renovatebot.com/dashboard you can see the debug logs for every run and it often helps. In this case: I'm not sure it did! But sometimes it does..

And yes, you can group as much as you want. Feel free to ask for confirmations here though, so you don't shoot yourself in the foot (with great configurability always comes great chances of messing up configuration)
