### ISSUE TITLE
[Question] Configure renovate to whitelist a module of a maven multi module project

### ISSUE THREAD

**Issue by fsemrau22** [renovatebot/config-help#263]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant
-

### What is your question?
I'm trying to set up renovate to monitor a react project. This react project is part of a multi module maven build and resides in a folder called `test/maven-module-name-here//src/main/resources/static-resources`. This is also the place where I have placed `.npmrc` file which points to a custom registry setting. 
In my first onboarding pull request I can see that renovate made a lot of suggestions about maven dependencies in my project, but it did not pick up my project under the `test` folder.
I am only interested in my react app at the moment, is there a way to whitelist folders to scan? I would be very grateful if you could point me in the right direction on how to set this up. 
Thanks!

**Comment by rarkins** [comment]
Try `”ignorePaths”: []`.

Renovate ignores test and example folders by default

**Comment by rarkins** [comment]
By the way, if you do want to ignore certain other paths, you can list them in "ignorePaths". There are multiple way to ignore or enable paths and managers though. If you can describe in more detail then I can try to recommend the cleanest way, but for now if you reset the `ignorePaths` array to empty as shown above then at least you should get the test maven module detected to begin with.
