### ISSUE TITLE
[Question] Configuration Options Docs for most Object types provide no info

### ISSUE THREAD

**Issue by jamesdh** [renovatebot/config-help#264]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
Yes

### What is your question?
Looking at most Config Options, for example https://renovatebot.com/docs/configuration-options/#gradle, no information on the object is provided. It's not clear at all what configuration  is possible. No idea where to go from here. 

In addition, that same Gradle object lists "releaseStatus beta" but I don't see any way to enable beta status, and hence my build.gradle is not being detected.

**Comment by rarkins** [comment]
When something is an object like that, you can configure usually any of the other string/boolean/list options inside it. It’s essentially a short cut for defining Gradle-specific config rather than global config. 

In your case to enable Gradle:

```json
  “gradle”: { “enabled”: true }
```

**Comment by rarkins** [comment]
Do you have any non-Gradle package files already being detected?

**Comment by jamesdh** [comment]
> @rarkins part of the problem is that the docs don't list any other string/boolean/list options inside them, so it's not clear what is even possible.

Rather, that's 95% of the problem.

**Comment by jamesdh** [comment]
Also, I just tried your suggestion with 
```
"gradle": { "enabled": true}
```
and pushed it on the `renovate/configure` branch, but after re-running the job, it still did nothing for gradle files.

**Comment by rarkins** [comment]
Re: "it still did nothing", can you log in at https://renovatebot.com/dashboard and check what the latest run says? Double check that the latest run did pick up your config changes too. You should see that it no longer says "gradle is disabled" although there's the possibility that it fails to detect your dependencies.

Re:
> the docs don't list any other string/boolean/list options

It's everything that's an array, boolean or string here: https://renovatebot.com/docs/configuration-options/

Re: your docker compose files, you want to use the [fileMatch](https://renovatebot.com/docs/configuration-options/#filematch) option.

If you go to https://github.com/renovatebot/renovate/blob/master/lib/config/definitions.js and search the page for instances of `fileMatch:` you can see some examples of patterns that can be used. The [kubernetes](https://renovatebot.com/docs/configuration-options/#kubernetes) object docs include some good examples of customising too

**Comment by jamesdh** [comment]
This is the main thing I see re: gradle that is probably the problem: 

```
DEBUG: Matched 2 file(s) for manager gradle: back/build.gradle, back/gradle.properties
WARN: No root build.gradle found - skipping
```

**Comment by rarkins** [comment]
Sorry, this is a limitation we are trying to address before we can classify it as out of beta. Right now it only looks in the root of the repo.

**Comment by jamesdh** [comment]
Even when configuring it with a `fileMatch` option?

**Comment by rarkins** [comment]
Yes, it's because we're using a Gradle plugin run via child process to extract dependencies and it looks only for `build.gradle`.
