### ISSUE TITLE
[Question] Apply `baseBranches` to a specific version

### ISSUE THREAD

**Issue by hiroppy** [renovatebot/config-help#269]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

no

### What is your question?

Currently, our configuration is below.

```
{
  "extends": ["config:base", ":semanticCommitTypeAll(chore)"],
  "labels": ["renovate"],
  "minor": {
    "groupName": "all minor dependencies"
  },
  "patch": {
    "groupName": "all patch dependencies"
  },
  "separateMinorPatch": true,
  "rangeStrategy": "bump",
  "packageRules": [
    {
      "depTypeList": ["peerDependencies"],
      "enabled": false
    }
  ]
}
```

And we have this problem like this.

https://github.com/webpack/webpack-dev-server/pull/2013

Because our next version's branch is `next`, not `master`.
So, we want to change the base branch when a deps is major version.
As far as I read, renovate has only `config.baseBranches`, but can we set a brnach option to `config.major`?

**Comment by rarkins** [comment]
Sorry @hiroppy, I somehow missed this when you raised it.

I see that the repo's default branch is `master`. Do I understand correctly that you want minor and patch updates to target `master`, and major updates to target `next`? Or do you want next to get minor and patch updates as well?

**Comment by hiroppy** [comment]
Thank you for your reply. Yes, the patch and minor versions will be merged to the `master` branch, but the major version will be merged to the `next` branch. The `next` branch is always rebased from the `master` branch.

**Comment by rarkins** [comment]
OK, I will think how to achieve that and then suggest to you a config.

**Comment by hiroppy** [comment]
Thanks!

**Comment by rarkins** [comment]
I think this config should work:

```
{
  "extends": ["config:base", ":semanticCommitTypeAll(chore)"],
  "baseBranches": ["master", "next"],
  "labels": ["renovate"],
  "minor": {
    "groupName": "all minor dependencies"
  },
  "patch": {
    "groupName": "all patch dependencies"
  },
  "separateMinorPatch": true,
  "rangeStrategy": "bump",
  "packageRules": [
    {
      "depTypeList": ["peerDependencies"],
      "enabled": false
    },
	{
	  "baseBranchList": ["master"],
      "updateTypes": ["major"],
      "enabled": false
	},
	{
	  "baseBranchList": ["next"],
      "updateTypes": ["digest", "pin", "patch", "minor"],
      "enabled": false
	}
  ]
}
```

I tested it against a fork, please confirm if the results are as you expect: https://github.com/renovate-tests/webpack-dev-server/pulls

You can see that all the major updates are targeted to `next` while the sole minor update (`webpack`) is targeted to `master`.

**Comment by hiroppy** [comment]
Wow, thank you for the lovely answer! I'll modify the renovate config.

**Comment by hiroppy** [comment]
I'll close this issue. @rarkins I'm really thankful to you.

**Comment by rarkins** [comment]
You're welcome, and sorry I missed your question earlier

**Comment by hiroppy** [comment]
No problem;)

**Comment by hiroppy** [comment]
@rarkins sorry, I want to ask 1 more question. 

If we want to submit to the `master` and `next` branches if a library is a major version.  Is below correct?

```diff
	{
-	  "baseBranchList": ["master"],
+	  "baseBranchList": ["master", "next'],
      "updateTypes": ["major"],
      "enabled": false
	},
```

Thanks

**Comment by rarkins** [comment]
This would disable major updates for both. Can you summarise again what you want for each base branch?

**Comment by hiroppy** [comment]
sometimes, we want to merge to the master branch even if a library is a major version. So, we want to change renovate process like below.

minor, patch -> master
major -> master, next

**Comment by rarkins** [comment]
So master gets all types and next gets only major?

**Comment by hiroppy** [comment]
yep

**Comment by rarkins** [comment]
In that case you can just remove the second rule altogether

**Comment by hiroppy** [comment]
```diff
-	{
-	  "baseBranchList": ["master"],
-      "updateTypes": ["major"],
-      "enabled": false
-	},
```

ok, so I'll delete this area. Is my understanding correct?

**Comment by rarkins** [comment]
Yes. It’s only purpose was to disable major updates for master

**Comment by hiroppy** [comment]
Makes sense. Thank you so much 🙇

**Comment by hiroppy** [comment]
I merged this config. Let's see how it goes.

**Comment by hiroppy** [comment]
fmm... sorry, but may I ask that this setting is correct? renovate doesn't seem to send a pr to the next branch. 🤔 
https://github.com/webpack/webpack-dev-server/pull/2035#issuecomment-502379524

**Comment by rarkins** [comment]
Can you check the logs in case it’s the 2 PR’s/hr limit causing it to be delayed?

**Comment by hiroppy** [comment]
oh, sorry. I don't have the right to check the logs. Currently, we receive only master https://github.com/webpack/webpack-dev-server/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

ok, I will be waiting to receive a pr submitting to the next for a few days.

**Comment by hiroppy** [comment]
@rarkins A pr submitting to the next branch came to our repository. Thank 🙏 
https://github.com/webpack/webpack-dev-server/pull/2043

**Comment by rarkins** [comment]
Great! FYI, the "config:base" preset you extend is the one that includes a PR hourly limit of 2. If you ever want to increase it, you can configure something like `"prHourlyLimit": 4`. This limit is not there to protect Renovate from overload, it's there to protect your CI from overload, so feel free to raise it.

I can also recommend you add `"masterIssue": true` to your config so that you can get a mini dashboard of all PRs - both open as well as pending. You can read more about that feature here: https://renovatebot.com/blog/master-issue

**Comment by hiroppy** [comment]
Thank you for the information 🙇
