### ISSUE TITLE
[Question] major version pull requests are not assigned

### ISSUE THREAD

**Issue by BigMichi1** [renovatebot/config-help#271]
### Which Renovate are you using? CLI, App, or Pro
renovate-cli

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
self hosted GitLab

### Have you checked the logs? Don't forget to include them if relevant
checked the logs and i've not seen an obvious error or failure

### What is your question?
I'm using the following configfor my project

```
{
  "extends": [
    "config:base",
    ":assignAndReview(BigMichi1)",
    ":labels(depedendencies,devops)",
    ":rebaseStalePrs",
    ":automergeMinor",
    ":maintainLockFilesWeekly",
    ":timezone(Europe/Berlin)",
    ":disableRateLimiting"
  ],
  "gradle": {
    "enabled": true
  },
  "maven": {
    "enabled": true
  },
  "php": {
    "enabled": true
  }
}
```

what i'm struggeling with is that new pull requests, that are not merged automatically because of a major version upgrade are not assigned to my user which is specified in ```":assignAndReview(BigMichi1)",```, for me it looks like there is something broken in my configuration but could not figure out what. the confuration itself works fine like adding labels or automerging minor version upgrades. is it possible that i should not use a special combination of these extends?

**Comment by rarkins** [comment]
For one thing, assigning is only done at the time of MR creation. So you can only test this working or non-working if you rename/delete MRs to trigger their replacement. If you are able to reproduce this with a simple public gitlab.com repo and same config, it would definitely speed up my ability to debug it.

**Comment by BigMichi1** [comment]
you can check it here https://github.com/BigMichi1/renovate-config

**Comment by BigMichi1** [comment]
its a new repository with exact the same content like i have it in gitlab and its also not assigning the reviewer and assignee

**Comment by rarkins** [comment]
Thanks, I'll take a look

**Comment by rarkins** [comment]
@BigMichi1 Renovate skips assigning PRs if they are schedule for automerge. They only get assigned if tests fail. This explains why the PR in BigMichi1/renovate-config is not assigned. If you want to reproduce the problem then you'll need a major update (non-automerging) in your example repo.

**Comment by BigMichi1** [comment]
ok, so that actually means the currently open pr will only get merged when a test build is successfull or will renovate merge it when it runs the next time

**Comment by rarkins** [comment]
By default will only merge when tests have been detected. Otherwise an outage of webhooks or CI could cause unwanted merges. If you want to automerge without tests then set `”requiredStatusChecks”: null` in config.

**Comment by BigMichi1** [comment]
thank you, now i understand how it works
