### ISSUE TITLE
[Question] Is requiredStatusChecks supposed to allow null?

### ISSUE THREAD

**Issue by fshauge** [renovatebot/config-help#273]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
Not relevant

### What is your question?
I've been using `renovate-schema.json` to help with autocompleting the configuration file. I noticed that `requiredStatusChecks` do not allow `null` (because the type is set to `array` in the schema).

![image](https://user-images.githubusercontent.com/1189327/59553643-cafe2e00-8f97-11e9-967d-9b87da7d5965.png)

Is this is a bug, or a limitation in some of the tooling that uses the schema?

**Comment by rarkins** [comment]
It is intended that you can use null, so the schemes is technically incomplete.
