### ISSUE TITLE
Reusing `gitAuthor` in ``commitBody`

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/config-help#275]
### Which Renovate are you using? CLI, App, or Pro
cli

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### What is your question?
Since we first started using Renovate I've had a config which is essentially adding the `Signed-off-by:` suffix into the commit message:

```json
    "commitBody": "Signed-off-by: {{{gitAuthor}}}",
    "gitAuthor": "RenovateBot <renovate-bot@engineering.digital.dwp.gov.uk>",
```

Recently however it has stopped including the value of `gitAuthor` in the output, and is instead leaving it blank.

Has something changed in the handlebars compilation that means this configuration now longer works?  Or is there a different preferred approach?

Thanks.

**Comment by rarkins** [comment]
`gitAuthor` got removed from the config during initialization once its use was over. I hadn't realised anyone might use it in templates, so will restore it back.

**Comment by adam-moss** [comment]
Awesome, thank you 😄
