### ISSUE TITLE
[Question] Is Renovate's "stable" tag used and up-to-date?

### ISSUE THREAD

**Issue by attekemppila** [renovatebot/config-help#276]
### Which Renovate are you using? CLI, App, or Pro

CLI

### What is your question?

(This is not really config question. Trying my luck here after no answer in gitter.)

Question about renovate's release policy. I searched but didn't find any info about it.
Renovate's "stable" is several major versions behind "latest" version: https://www.npmjs.com/package/renovate?activeTab=versions

I'm currently using "stable" because, at the time, 14.x crashed my build, and I reverted back to "stable". But now I'm wondering, is "stable" tag going to be updated at some point? Or is it old version because "stable" tag is not actively used anymore?

Updating to newer version is not problem per se. Just seeking clarification.

**Comment by rarkins** [comment]
The "stable" tag hasn't been kept up to date, although I may reintroduce it again. At the time, it was an indication of what was used for Renovate Pro. For now, please use "latest" - it's certainly not intended to be "unstable".

BTW the gitter channel hasn't been used for a long time. Where did you find the reference to it?

**Comment by attekemppila** [comment]
\*facepalm\* 

I guess multi-tasking is not my thing. I was looking at problems in another project, and asked my question in that project's gitter. No wonder I got not answers. Uh...

Anyway, thanks for clarifying "stable" situation.
