### ISSUE TITLE
[Question] running Renovate on itself?

### ISSUE THREAD

**Issue by ilyalavrenov** [renovatebot/config-help#277]
### Which Renovate are you using? CLI, App, or Pro
CLI (`renovate/renovate` container on GKE, self-hosted)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
is there a recommended way to run Renovate on itself to handle version updates automatically? here's my config, it doesn't seem to trigger any nightly updates against my base renovate configuration. ideally i'd like to track the latest version of the app.
```
{
  "name": "org",
  "version": "1.1.2",
  "scripts": {
    "validate": "renovate-config-validator"
  },
  "renovate-config": {
    "default": {
      "extends": [
        "config:base",
        ":preserveSemverRanges",
        ":rebaseStalePrs",
        ":semanticCommits",
        ":semanticCommitTypeAll(chore)",
        ":prHourlyLimit4"
      ],
      "major": {
        "enabled": true,
        "schedule": "before 6am on the first day of the month"
      },
      "prConcurrentLimit": 3,
      "schedule": [
        "before 6am every weekday"
      ],
      "rangeStrategy": "bump",
      "dockerfile": {
        "enabled": true
      },
      "packageRules": [
        {
          "packageNames": [
            "renovate",
            "renovate/renovate"
          ],
          "groupName": "renovatebot",
          "separateMajorMinor": false,
          "separateMinorPatch": false,
          "schedule": "at any time"
        },
        {
          "depTypeList": [
            "dependencies"
          ],
          "semanticCommitType": "fix"
        },
        {
          "depTypeList": [
            "devDependencies"
          ],
          "groupName": "devDependencies",
          "separateMajorMinor": false,
          "separateMinorPatch": false
        }
      ],
      "patch": {
        "groupName": "patchReleases"
      },
      "separateMinorPatch": true
    }
  },
  "dependencies": {},
  "devDependencies": {
    "renovate": "^17.7.9"
  }
}
```

**Comment by rarkins** [comment]
Sorry @ilyalavrenov, I just saw this now. Can I still help you with it?

**Comment by rarkins** [comment]
At a very high level, I'd recommend:
- Pin to an exact version of Renovate
- Take updates at most weekly, potentially monthly - otherwise Renovate updates potentially 5+ times per day

Also consider potentially branch automerging patch updates. e.g. if you're on 17.7.9 and 17.7.10 is released then it should be a low-risk bug fix which is fairly safe to take.

**Comment by ilyalavrenov** [comment]
thanks @rarkins! we updated to a more recent version and everything seemed to start working as expected. thanks for the guidance.
