### ISSUE TITLE
[Question] Turn on renovate globally _without_ cutting onboarding PRs

### ISSUE THREAD

**Issue by nevir** [renovatebot/config-help#280]
### Which Renovate are you using? CLI, App, or Pro

App (for the convoyinc organization)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub (convoyinc organization)

### Have you checked the logs? Don't forget to include them if relevant

Relevant example logs:
https://renovatebot.com/dashboard#github/convoyinc/badging-service/75469597

### What is your question?

I am trying to get release notes to work for private npm packages published via my organization. Renovate attempts to pull them via the GitHub API (`getChangeLogJSON`), but that fails for most (404 from GitHub; which smells like authorization).

My current assumption is that this is because we have the renovate app scoped to a few of our repositories (and that token, rightly, can't access the other private repos on the org that we might be publishing dependencies from).

If that assumption holds: I'd like to give renovate access to all of our repos. _However_, I don't want to cause mass confusion by having an intro PR cut for every one of them (hundreds of repos). Is there a way that I can configure renovate to _not_ send intro PRs by default for repos in my organization?

**Comment by rarkins** [comment]
@nevir you are right that Renovate needs to be "installed" for each of those repos you want to retrieve release notes from, otherwise GitHub returns a 404.

Do I understand correctly that your proposed solution is to disable onboarding for all repos, meaning that you'll need to manually configure a `renovate.json` for any in future you do want to activate?

**Comment by nevir** [comment]
> Do I understand correctly that your proposed solution is to disable onboarding for all repos, meaning that you'll need to manually configure a renovate.json for any in future you do want to activate?

Correct! My main concern is that I want to be able to _consume_ the output of other teams' repositories, without forcing the onboarding noise of renovate PRs on them (at least for now)

**Comment by nevir** [comment]
> @nevir you are right that Renovate needs to be "installed" for each of those repos you want to retrieve release notes from, otherwise GitHub returns a 404.

Alternative approach: if the CHANGELOG.md were included in the built packages, would renovate pick up on that?

**Comment by rarkins** [comment]
@nevir we don't currently have the ability to fetch `CHANGELOG.md` from the published tarballs, although it sounds technically achievable one day.

I think the solution here is:
- Add an admin option to Renovate - if I can't work out a way with existing options - to disable onboarding and *skip* repositories that are not
- I will then set this flag manually for `convoyinc` on the server side of the hosted app

**Comment by rarkins** [comment]
I think this logic may already handle this, but I need to test to confirm: https://github.com/renovatebot/renovate/blob/ae80bf443894b48cb76752fdfe394b8b0b97a05d/lib/workers/repository/onboarding/branch/check.js#L60-L64

**Comment by nevir** [comment]
Awesome, thanks for this! If it helps for testing, I can turn on a few more
repos

**Comment by rarkins** [comment]
I've implemented this and tested it.
- Newly installed repos won't get any onboarding
- If you add a `renovate.json` manually then the repo will be activated
- Any existing onboarding PRs won't be updated if you edit them

I suggest you start by manually "Selecting" one or two repos to confirm it's as I described before you select "All repos". It should take maximum 2-3 hours after adding a repo before downstream repos should see the updated release notes

**Comment by nevir** [comment]
Works, thanks!

**Comment by evanstoddard23** [comment]
> I've implemented this and tested it.
> 
> * Newly installed repos won't get any onboarding
> * If you add a `renovate.json` manually then the repo will be activated
> * Any existing onboarding PRs won't be updated if you edit them
> 
> I suggest you start by manually "Selecting" one or two repos to confirm it's as I described before you select "All repos". It should take maximum 2-3 hours after adding a repo before downstream repos should see the updated release notes

@rarkins How can I enable this feature? I don't see any setting related to this in the GItHub app config.

**Comment by ViceIce** [comment]
@evanstoddard23 You can configure it on the app config page on github. There you can enable it for some repos of an organization or for all repos of an org-

**Comment by rarkins** [comment]
Actually I will need to add a server side setting for the org that’s currently not user-configurable. @evanstoddard23 what’s your org?

**Comment by evanstoddard23** [comment]
@rarkins thanks! It's `opploans`

**Comment by rarkins** [comment]
This setting should now be live for `opploans` too. Please test with a single repository to verify, just to be sure.

If anyone finds this in future and needs the same, please raise a new request in https://github.com/renovatebot/app-support so that the existing people on this issue aren't forever-notified.
