### ISSUE TITLE
[Question] Renovate Pro Kubernetes Template

### ISSUE THREAD

**Issue by QuentinMoss** [renovatebot/config-help#282]
### Which Renovate are you using? CLI, App, or Pro

Currently using Renovate self-hosted on kubernetes, but we're going to start evaluating Renovate Pro. 

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I was wondering if you had a kubernetes file that was configured for Renovate pro. Something similar to https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md

but as a stateful set with Postgres.

If not, I can create one and contribute upstream, but it would save me some time if you already have an example / template.

**Comment by QuentinMoss** [comment]
Also, is it possible to use self-hosted Renovate Pro with Github.com? I see there is a few environment variables specific to GH enterprise that are not optional.

**Comment by rarkins** [comment]
It's possible. You can enter `https://api.github.com/` as the endpoint and I think in such cases it's possible to skip the `GITHUB_COM_TOKEN`. Things like app id/secret and webhook secret are not GHE-specific.

**Comment by rarkins** [comment]
The closest we have to a k8s example for Pro is this Pull Request adding example Helm charts: https://github.com/renovatebot/pro/pull/41

**Comment by QuentinMoss** [comment]
Thanks! I'll use https://api.github.com/ - and thanks for the Helm reference
