### ISSUE TITLE
[Question] Renovate Pro: passing in list of repos to maintain

### ISSUE THREAD

**Issue by QuentinMoss** [renovatebot/config-help#283]
### Which Renovate are you using? CLI, App, or Pro
Renovate Pro - Self hosted Kubernetes

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
I have finished creating the kubernetes configuration we discussed earlier, but I'm noticing that our old method of passing in a list of repos we want to maintain with renovate is no longer working. 

kubernetes.yaml
```
...
  ...
   args:
     - honeyscience/repo1
     - honeyscience/repo2
```

If this isn't working with pro, what is the suggested way to feed Renovate a list of repos that should be watched.

**Comment by QuentinMoss** [comment]
Unrelated to this ticket, but feedback for renovate - Consolidation of documentation would help _greatly_

**Comment by rarkins** [comment]
Renovate Pro runs as an app. You can then “Select repositories” through the GitHub UI (as part of installation) rather than needing to list them in config

**Comment by QuentinMoss** [comment]
Does this apply to self hosting renovate pro? Is there a webUI with the self hosted option?

**Comment by rarkins** [comment]
It’s how all apps on GitHub work. You provision the app and at first it has zero repositories. Then someone who is an admin “installs” the app and they pick whether to install it for “all” or for “selected”

**Comment by QuentinMoss** [comment]
Ah, I see what you mean. I'll try this out tomorrow! Thanks!

The Honey Science team really appreciates the Renovate project, and your responsiveness

**Comment by QuentinMoss** [comment]
Would you like the kubernetes file (not helm) contributed upstream? I can clean it up and make it general purpose if you think it will provide value.

**Comment by QuentinMoss** [comment]
@rarkins Can you point me in the right direction to get the Github App ID? I see I can create and app, but I believe that requires me to have the service running, but it won't start without the env var.
