### ISSUE TITLE
[Question] Excluding Orbs appears to be ignored

### ISSUE THREAD

**Issue by QuentinMoss** [renovatebot/config-help#285]
### Which Renovate are you using? CLI, App, or Pro
Renovate pro. Self-hosted, Kubernetes (GKE)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github.com

### What is your question?
We originally rolled out Renovate OSS and have had good luck creating a configuration that meets the orgs needs. 

Now that we are considering moving to Pro, we are doing some testing to make sure everything is running smoothly.
One thing that I noticed is that in our shared Renovate config we have an exclusion for `type: orb`, but after I deployed renovate pro, it opened a PR to bump an orb. Here is our config: 

```
{
...
  "version": "1.2.3",
  "description": "Renovate bot configs for Honey",
  "author": "The Honey Team",
  "license": "UNLICENSED",
  "homepage": "...",
  "repository": {
    "type": "git"
     ....
  },
  "scripts": {
    "validate": "renovate-config-validator"
  },
  "renovate-config": {
    "default": {
      "extends": [
        "config:base",
        ":preserveSemverRanges",
        ":rebaseStalePrs",
        ":semanticCommits",
        ":semanticCommitTypeAll(chore)",
        ":prHourlyLimit4"
      ],
      "major": {
        "enabled": true,
        "schedule": "before 6am on the first day of the month"
      },
      "prConcurrentLimit": 3,
      "schedule": [
        "before 6am every weekday"
      ],
      "timezone": "America/Los_Angeles",
      "rangeStrategy": "bump",
      "dockerfile": {
        "enabled": false
      },
      "bundler": {
        "enabled": true
      },
      "sbt": {
        "enabled": true
      },
      "circleci": {
        "ignoreDeps": [
          "circleci/node"
        ]
      },
      "packageRules": [
        {
          "datasources": [
            "orb"
          ],
          "enabled": false
        },
        {
          "packageNames": [
            "@honeyscience/honey-dev-tools"
          ],
          "updateTypes": [
            "major"
          ],
          "enabled": false
        },
        {
          "packageNames": [
            "renovate",
            "renovate/renovate"
          ],
          "groupName": "renovatebot",
          "separateMajorMinor": false,
          "separateMinorPatch": false,
          "schedule": [
            "before 6am on the 1st day of the month",
            "before 6am on the 15th day of the month"
          ]
        },
        {
          "depTypeList": [
            "dependencies"
          ],
          "semanticCommitType": "fix"
        },
        {
          "depTypeList": [
            "devDependencies"
          ],
          "groupName": "devDependencies",
          "separateMajorMinor": false,
          "separateMinorPatch": false
        }
      ],
      "patch": {
        "groupName": "patchReleases"
      },
      "separateMinorPatch": true
    }
  },
  "dependencies": {},
  "devDependencies": {
    "renovate": "^18.21.0"
  }
}
```

<img width="809" alt="Screen Shot 2019-07-03 at 2 02 12 PM" src="https://user-images.githubusercontent.com/350409/60624872-38350000-9d9b-11e9-9424-51d240df99fb.png">

Is it possible that Pro is not picking up our shared config in the same way?  Thanks again for your time.

**Comment by QuentinMoss** [comment]
I confirmed that deployment can at least query npm for the package. 

```
ubuntu@renovate-pro-......:$ npm info @honeyscience/renovate-config

@honeyscience/PACKAGE@1.2.3 | UNLICENSED | deps: none | versions: 29
```


Our shared configs:
```
{
  "extends": [
    "@honeyscience"
  ],
  "kubernetes": {
    "fileMatch": ["^kubernetes.yaml$"]
  }
}
```

Should I be explicit about the package name in `extends`?

**Comment by rarkins** [comment]
Try to confirm first if the config is being picked up at all. Eg confirm that one of the other rules is being activated, Eg like enabling bundler. 

And log at debug level and save those logs for analysis.

**Comment by rarkins** [comment]
I've worked out the problem. Renovate Pro @ 0.15.5 runs a version of Renovate prior to the "datasources" field being supported in packageRules. By design we only backport fixes to each minor release rather than features. Sorry about that!

Can you try running with `renovate/pro:0.16.0-pre.2`?

I haven't promoted it from pre-release to release yet as the Release Notes are a WIP. You can see here though: https://github.com/renovatebot/pro/pull/51/files

**Comment by QuentinMoss** [comment]
No worries @rarkins! I'm out of the office today but I"ll give this a shot on Friday and let you know.

**Comment by QuentinMoss** [comment]
Looks like it fixed the issue. I'll keep an eye out for the release!
