### ISSUE TITLE
[Question] How to configure for pythoh project using --extra-index-url on a private URL?

### ISSUE THREAD

**Issue by emman27** [renovatebot/config-help#287]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
How do I configure renovate to use a private pip registry? We're using Gemfury as our internal pip registry, where they have some secret URL ot be used. Is there a way to configure this URL without commiting it into the codbase config file?

**Comment by rarkins** [comment]
Right now we only parse the index url. I assume you have both?

**Comment by rarkins** [comment]
Being worked on in https://github.com/renovatebot/renovate/pull/4056
