### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by mastermatt** [renovatebot/config-help#289]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub Enterprise 

### What is your question?
What is the correct way to group all Docker image digest updates?

I've tried adding a `groupName` key to the `digest` object with no luck.

**Comment by rarkins** [comment]
I would have expected that to work, but you could also try:

```json
{
  "packageRules": [{
    "updateTypes": ["digest"],
    "groupName": "Docker digests"
  }]
}
```

**Comment by mastermatt** [comment]
Your suggestion resulted in the same output as adding `groupName` to the `digest` object, there was a change, but it wasn't the desired results. So let me try to break down what I have here.

I currently have a repo with outstanding updates to the Node and Memcached Docker image digests.
Previously, without any attempt at grouping, Renovate made two PRs:

on branch `renovate/node-10-alpine`

| Package | Type | Update | Change |
|---|---|---|---|
| [node](https://github.com/nodejs/node) | final | digest | `0b9999c` -> `07897ec` |
| [node](https://github.com/nodejs/node) |  | digest | `0b9999c` -> `07897ec` |

(Two updates, a Dockerfile and a docker-compose.yaml)

and on branch `renovate/docker-memcached-1.5-alpine`

| Package | Update | Change |
|---|---|---|
| memcached | digest | `ba0429a` -> `248f02f` |

(memcached is only in the docker-compose.yml in this repo)

----

When attempting to group them, using both config options, the results were the same. The two existing PRs were closed and two new ones were opened with the same changes, however, the branch names are now `renovate/docker-images` for the Node updates and `renovate/docker-docker-images` for the memcached update.
Note that for both configs I set `groupName` to `"Docker Images"`.

Thoughts on why the memcached is getting `docker` twice in the branch name?

Here is the full config:
```json
{
  "extends": [
    "config:base",
    "default:maintainLockFilesMonthly",
    "default:prHourlyLimitNone",
    "default:rebaseStalePrs",
    "default:pinAllExceptPeerDependencies"
  ],
  "labels": [
    "dependency"
  ],
  "semanticCommits": false,
  "pinDigests": true,
  "node": {
    "supportPolicy": [
      "lts_latest"
    ]
  },
  "bundler": {
    "enabled": true
  },
  "packageRules": [
    {
      "depTypeList": [
        "dependencies"
      ],
      "minor": {
        "groupName": "Prod Non-major Dependencies",
        "groupSlug": "prod-minor-patch"
      }
    },
    {
      "depTypeList": [
        "devDependencies"
      ],
      "groupName": "Dev Dependencies"
    },
    {
      "updateTypes": [
        "digest"
      ],
      "groupName": "Docker Images"
    }
  ]
}
```

**Comment by rarkins** [comment]
I think I understand now. We “namespace” `docker-` to avoid conflicts between docker image names and others, particularly npm. So seeing that is expected. 

But we have a special case for Node.js where we deliberately remove the namespacing to group docker node updates with other node updates. This is causing your split group. If you had 12 digests updating you should see 11 of them together and node on its own. 

To restore the grouping, you could add `”managerBranchPrefix”: “”` to the package rule I gave earlier.

**Comment by mastermatt** [comment]
That did the trick. Thanks.
