### ISSUE TITLE
Fuzzy matching not supported for NPM packages that resolve to a monorepo

### ISSUE THREAD

**Issue by mikeewhite** [renovatebot/config-help#290]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
NPM packages that are sourced from a monorepo and are specified in the `package.json` with a fuzzy matched semver pattern are not updated.

**Did you see anything helpful in debug logs?**
For the following NPM dependency (which resolves to [this monorepo](https://github.com/bugsnag/bugsnag-js/tree/next/packages)):
`"@bugsnag/js": "^6.2.0"`
There should be at least 4 newer releases (at the time that this issue was created) that match that semver pattern, whereas the logs show that no releases were matched:
```
"deps": [
{
  "depType": "dependencies",
  "depName": "@bugsnag/js",
  "currentValue": "^6.2.0",
  "datasource": "npm",
  "prettyDepType": "dependency",
  "lockedVersion": "6.2.0",
  "updates": [],
  "warnings": [],
  "sourceUrl": "https://github.com/bugsnag/bugsnag-js",
  "homepage": "https://www.bugsnag.com/",
  "releases": []
},
```
Whereas, when exact matching is used, e.g. 
`"@bugsnag/js": "6.2.0"`
Then the expected releases are discovered:
```
{
  "depType": "dependencies",
  "depName": "@bugsnag/js",
  "currentValue": "6.2.0",
  "datasource": "npm",
  "prettyDepType": "dependency",
  "lockedVersion": "6.2.0",
  "updates": [
    {
      "fromVersion": "6.2.0",
      "toVersion": "6.3.2",
      "newValue": "6.3.2",
      "newMajor": 6,
      "newMinor": 3,
      "updateType": "minor",
      "isSingleVersion": true,
      "releaseTimestamp": "2019-06-27T20:43:36.019Z",
      "canBeUnpublished": false
    }
  ],
  "warnings": [],
  "sourceUrl": "https://github.com/bugsnag/bugsnag-js",
  "homepage": "https://www.bugsnag.com/",
  "releases": [
    "6.2.0",
    "6.3.0",
    "6.3.1",
    "6.3.2"
  ]
}
```

**To Reproduce**
See this example repository:
https://github.com/mikeewhite/renovate-monorepo-issue

**Expected behavior**
Renovate should create the expected update PR when newer versions are available.

**Comment by mikeewhite** [comment]
OK - thanks, your explanation makes sense. However renovates handling of semver ranges seems inconsistent to me.

For example, I've added `"@grpc/proto-loader": "^0.3.0"` to my example repository and renovate has created [this PR](https://github.com/mikeewhite/renovate-monorepo-issue/pull/2/) to update the dependency to `^0.5.0` even though that repository should be using the default `rangeStrategy= replace` and that update doesn't fall outside of the range.

Am I misinterpreting something?

**Comment by mikeewhite** [comment]
Actually I've realised why - it's because its version 0.

**Comment by rarkins** [comment]
Yes, 0.5.0 is not within range ^0.3.0
