### ISSUE TITLE
[Question] cannot see initial PR on my GitHub repo

### ISSUE THREAD

**Issue by bryndyment** [renovatebot/config-help#291]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

yes … it says `no-plan`

### What is your question?

How can I get started?  I signed up for a 14-day free trail.  Also, I work at Unity and they have a paid plan.  Although I am trying to set it up for my separate repos that are unrelated to my Unity work.  I am happy to pay the $1/month subscription.

The repos that I'm trying to set up are both private repos.

Help!

**Comment by bryndyment** [comment]
One more detail … in an attempt to get my initial PR issued, I added a `renovate.js` file to my root-level directory, with the following content:

```
{
  "extends": ["config:base"],
  "baseBranches": ["develop"],
  "automerge": true,
  "major": {
    "automerge": false
  }
}
```

**Comment by rarkins** [comment]
@bryndyment I'll take a look. How long ago (e.g. minutes, hours, days?) did you activate the free trial?

**Comment by bryndyment** [comment]
> @bryndyment I'll take a look. How long ago (e.g. minutes, hours, days?) did you activate the free trial?

About an hour ago.

I suspect that the problem is because I had existing access to Renovate through Unity (on the same GitHub account), but wanted to set up a separate, private, paid account.

**Comment by bryndyment** [comment]
Seeing stuff now!  Was it something I did wrong?  Just curious …

**Comment by rarkins** [comment]
Nothing wrong, they should have showed up within the next hour. Marketplace plans are sync'd hourly (yours was already detected when I checked the DB), and then repositories are queued up after that.

**Comment by bryndyment** [comment]
That would be a great thing to add to the online information 👍.

**Comment by rarkins** [comment]
Where would you have looked for that info?

FYI we give a few days grace period after installation for private repos. i.e. if you install the app without a plan and then add a private repo, you *will* get an onboarding PR, but with a header saying you'll need to sign up for a plan for continued service. So in that case it's pretty clear. Where it has this silent hour or so like you saw is if you installed with public repos-only days or weeks ago and then add a private repo. GitHub's billing and app interfaces are entirely independent so they don't warn you.

**Comment by bryndyment** [comment]
I think what confused me was … I was already set up via Unity.

Maybe in the widget where I added/removed new repos and hit `Save`.  At that point, a help message saying `Please wait for up to two hours for your PR to appear.` or something like that?

**Comment by rarkins** [comment]
That interface is a GitHub one that we have no control over. And as I tried to explain, there is no link/awareness between GitHub's "installation" interface (where you add/remove repos) and their marketplace interface.

**Comment by bryndyment** [comment]
Gotcha!

![image](https://user-images.githubusercontent.com/7953560/60948060-0b4d9380-a32d-11e9-8dde-b689bee05933.png)

Maybe a message right above that link that takes me into the GitHub world?  I guess this couldn't be "intelligent" but it would be nice to see something.

Anyway, thanks for the scary-fast response!
