### ISSUE TITLE
[Question] How to add a few weeks of delay before upgrading to the latest version?

### ISSUE THREAD

**Issue by mkarp** [renovatebot/config-help#292]
### Which Renovate are you using? CLI, App, or Pro

Pro.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub.

### Have you checked the logs? Don't forget to include them if relevant

Yeap.

### What is your question?

Hey there!

Our team uses many third party dependencies. We are concerned that some malicious code can appear in the latest version of a dependency, and dependabot will automatically merge it for us on the next day, without us paying attention to it. Sometimes stories about a popular dependency getting malicious code go viral on the internet. Our team reads security-related news and might notice such cases early, but perhaps not earlier than the dependency will be merged by Renovatebot.

So we thought if we could configure Renovatebot to update not to the latest version by default, but to a version that's lagging a bit behind (for example, a condition like "version should be at least two weeks old"). I know we can configure every dependency's version range separately, but that's tedious.

Thank you!

**Comment by rarkins** [comment]
@mkarp This will require a code change, work is in progress. Please follow https://github.com/renovatebot/renovate/issues/3897 and https://github.com/renovatebot/renovate/pull/3925
