### ISSUE TITLE
change default config file from config.js to renovate-config.js or similar?

### ISSUE THREAD

**Issue by bryndyment** [renovatebot/config-help#294]
**What would you like Renovate to be able to do?**

`config.js` is a very generic default name to include at the root of a repo … could we make the default more renovate-specific?

**Describe the solution you'd like**

E.g. `renovate.js`, `renovate-config.js`, etc.

**Describe alternatives you've considered**

none

**Additional context**

N/A

**Comment by rarkins** [comment]
You can define `RENOVATE_CONFIG_FILE` and point it at any alternative path/file name. 

Example:

```
export RENOVATE_CONFIG_FILE="/home/user/renovate-config.js"
```
