### ISSUE TITLE
[Question]  npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Illyism** [renovatebot/config-help#296]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Using npm: node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --ignore-scripts --no-audit(dependencies=["auth0-js","babel-core","babel-eslint","babel-jest","babel-loader","babel-plugin-transform-runtime","babel-preset-env","babel-preset-es2015","babel-preset-stage-2","cross-env","css-loader","eslint","eslint-plugin-import","eslint-plugin-json","eslint-plugin-vue","extract-text-webpack-plugin","fastclick","html-webpack-plugin","jest","node","node-sass","optimize-css-assets-webpack-plugin","page","parallel-webpack","portal-vue","raven-js","sass-loader","style-loader","uglifyjs-webpack-plugin","vue","vue-clickaway","vue-i18n","vue-jest","vue-loader","vue-material-design-icons","vue-meta","vue-resource","vue-template-compiler","webpack","webpack-merge"], branch="renovate/pin-dependencies")
INFO: lock file error(dependencies=["auth0-js","babel-core","babel-eslint","babel-jest","babel-loader","babel-plugin-transform-runtime","babel-preset-env","babel-preset-es2015","babel-preset-stage-2","cross-env","css-loader","eslint","eslint-plugin-import","eslint-plugin-json","eslint-plugin-vue","extract-text-webpack-plugin","fastclick","html-webpack-plugin","jest","node","node-sass","optimize-css-assets-webpack-plugin","page","parallel-webpack","portal-vue","raven-js","sass-loader","style-loader","uglifyjs-webpack-plugin","vue","vue-clickaway","vue-i18n","vue-jest","vue-loader","vue-material-design-icons","vue-meta","vue-resource","vue-template-compiler","webpack","webpack-merge"], branch="renovate/pin-dependencies")
{
  "cmd": "node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js",
  "args": "install --ignore-scripts --no-audit",
  "err": {
    "name": "ChildProcessError",
    "code": 1,
    "childProcess": {},
    "stdout": "",
    "stderr": "npm WARN tar ENOENT: no such file or directory, open '/mnt/renovate/gh/officient/officient-reseller-panel/node_modules/.staging/auth0-js-

...

npm WARN tar ENOENT: no such file or directory, open '/mnt/renovate/gh/officient/officient-reseller-panel/node_modules/.staging/lodash-a8f00c5d/last.js'
npm WARN tar ENOENT: no such file or directory, open '/mnt/renovate/gh/officient/officient-reseller-panel/node_modules/.staging/lodash-a8f00c5d/lastIndexOf.js'
npm WARN tar ENOENT: no such file or directory, open '/mnt/renovate/gh/officient/officient-reseller-panel/node_modules/.staging/lodash-a8f00c5d/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/mnt/renovate/gh/officient/officient-reseller-panel/node_modules/.staging/lodash-a8f00c5d/lodash.js'
npm ERR! Maximum call stack size exceeded
....

DEBUG: No updated lock files in branch
```

### What is your question?

- How do I figure out what's causing the issue?
- What are the nnpm WARN tar ENOENT: no such file or directory in .staging?

**Comment by rarkins** [comment]
Have you seen it happen more than once?

If you tick the rebase/retry checkbox for this PR, do you get the same error reproduced?

**Comment by Illyism** [comment]
Hi @rarkins

Yes, it happens on every PR and also when I rebase.

**Comment by rarkins** [comment]
Has it happened ever since you started using Renovate, or it started happening after some time?

Can you tell me a job ID where such a failure occurs?

**Comment by Illyism** [comment]
It's happening for a new repo. Here is a job ID: 79301232 / 79295144

**Comment by rarkins** [comment]
Your `package.json` includes `file:` references, and `npm` CLI has a bug where `npm i --package-lock-only` generates invalid `package-lock.json` files when `file:` references are in use, so Renovate switches to do "full" node_modules installs when updating lock files.

I'm not sure of why the `npm install` fails this way, but this is the explanation for why it's attempting a full install rather than just updating the lock file only.

**Comment by rarkins** [comment]
This seems related, although it is classified as resolved: https://github.com/npm/cli/pull/86

**Comment by rarkins** [comment]
@Illyism how big is the `node_modules` after you do a full install locally?

**Comment by Illyism** [comment]
@rarkins It's 335MB

**Comment by rarkins** [comment]
That size definitely should not cause any disk space problems.

In the npm cli issue reference above, a lot of people said they resolved it by deleting `node_modules` and `package-lock.json` and reinstalling, but it's not clear exactly why that works and if it's a one-time thing or recurring. 

Could you try doing that one time for your master branch? i.e.
- change to `master` branch
- remove `node_modules`
- remove `package-lock.json`
- run `npm install`
- commit the updated `package-lock.json` to `master` and push
- rebase one of the Renovate PRs afterwards

**Comment by Illyism** [comment]
@rarkins Yes that fixed it.

But it causes  4,972 additions and 6,469 deletions in the lock file and many sub-dependencies to be updated. I can't review all the changes in each of those dependencies individually so I'll have to revert. But I think it's clear that the issue is on my side and we could close this issue if you want.

**Comment by vinay030901** [comment]
Just do npm rebuild 
It solved my problem
