### ISSUE TITLE
How to group updates of a monorepo packages together

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#299]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

We're considering to switch from GreenKeeper to Renovate and I'm not sure how to reproduce the grouping feature that GK has in Renovate. I am aware of the Renovate grouping feature which GreenKeeper [also has](https://greenkeeper.io/docs.html#monorepo-dependencies), but I'd need to do something slightly different. I have a monorepo managed with lerna and I would like multiple packages living in the monorepo to be updated together, which in GreenKeeper works as documented [here](https://greenkeeper.io/docs.html#monorepo).

Any idea how to accomplish something like this with Renovate?

**Comment by rarkins** [comment]
In Renovate you don’t need to explicitly configure your monorepo’s package files. Grouping - if desired - is done using package rules. Can you share your config?

**Comment by simoneb** [comment]
Thanks for the quick answer. I don't have a config yet, I am just trying to figure out how to reproduce the GreenKeeper behavior so that packages of my monorepo get updates at the same time. One of the reasons is that some of them need to work together, and as a consequence would benefit from having the same dependency versions. I thought that in Renovate, grouping was targeting the dependencies in the mono-repository's package.json files, whereas what I'm trying to do here is grouping my own packages so that they receive PRs at the same time.

**Comment by rarkins** [comment]
You can truly group any way you want, it’s ridiculously configurable. I just am not sure what exactly you’re after without an example or longer description.

**Comment by rarkins** [comment]
Search the online docs for `groupName` if you’re after some inspiration. Pretty sure that whatever you need can be done.

**Comment by simoneb** [comment]
Ok sure I'll play around with it. I think what I'm after is mostly an understanding about what is the target of "grouping" in Renovate. I understand that it can group **target packages** (the ones in my package.json files) together, but can it group **my monorepo packages** updates together instead?

**Comment by rarkins** [comment]
Yes you can group using the `paths` selector in `packageRules`, also in combination with the `packageNames` and `packagePatterns` selectors. 

If you want to provide some real examples, I’d be happy to save you some time and suggest a config too.

**Comment by rarkins** [comment]
Were you able to group as desired?

**Comment by simoneb** [comment]
Yes, it does work even though I'm still confused as to how the logic works. Conceptually in a monorepo I have 2 kinds of packages: the packages in my monorepo and the packages that the packages in my monorepo depend on (to complicate things, among the latter there may be both packages in the npm registry and packages in the monorepo). Hence, I don't quite understand how these rules apply to both categories. It does work, I just find it a little confusing.

**Comment by rarkins** [comment]
When Lerna is in use, Renovate does not attempt to update "internal" packages in other `package.json` files as those versions are managed by Lerna itself. Therefore you should only see Renovate updating your packages' external dependencies

**Comment by simoneb** [comment]
What I was trying to do is something different though. I was trying to group my monorepo packages into groups so that their dependencies are updated in the same PRs. I'm not sure if I achieved that via grouping because I didn't get PRs from Renovate yet, but based on the description of the onboarding PR that must have worked. Still confused though that grouping applies both to my monorepo packages and to their dependencies.

**Comment by rarkins** [comment]
Grouping applies however granularly you want it, or how broad. If it doesn't work as you anticipate then you can reopen the issue and provide an example config to look at

**Comment by simoneb** [comment]
I'm good now, thanks for your help.
