### ISSUE TITLE
[Question] Orb major updates not being opened

### ISSUE THREAD

**Issue by zephraph** [renovatebot/config-help#300]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

https://renovatebot.com/dashboard#github/artsy/reaction/80584650

### What is your question?

Recently I've noticed that our circleci orbs are no longer updating. I'm wondering if it's a config issue from a renovate change or if there are other errors. 

Here's the [orb section](https://github.com/artsy/renovate-config/blob/master/package.json#L111-L119) of our shared renovate config. 

Looking at the logs above, it does detect the orb...

```
orb.getPkgReleases()
{
  "lookupName": "artsy/yarn"
}
```

Looking at the `packageFiles with updates` section..

```json
{
  "config": {
    "circleci": [
      {
        "packageFile": ".circleci/config.yml",
        "manager": "circleci",
        "deps": [
          {
            "depType": "orb",
            "depName": "yarn",
            "currentValue": "1.1.1",
            "lineNumber": 3,
            "datasource": "orb",
            "lookupName": "artsy/yarn",
            "commitMessageTopic": "{{{depName}}} orb",
            "versionScheme": "npm",
            "rangeStrategy": "pin",
            "updates": [
              {
                "fromVersion": "1.1.1",
                "toVersion": "2.1.0",
                "newValue": "2.1.0",
                "newMajor": 2,
                "newMinor": 1,
                "updateType": "major",
                "isSingleVersion": true
              }
            ],
            "warnings": [],
            "sourceUrl": null,
            "homepage": "https://circleci.com/orbs/registry/orb/artsy/yarn",
            "releases": [
              "1.1.1",
              "2.0.0",
              "2.1.0"
            ]
          }
        ]
      }
    ]
}
```

So the latest version is _definitely_ detected. There's no PR triggering for the update though. We do have the master issue approval workflow enabled, but not specifically for this step. Even if this was caught up in it, I'm not seeing that update show up in the [list](https://github.com/artsy/reaction/issues/2400). 

Advice? cc @eessex

**Comment by rarkins** [comment]
Sounds like it is extracted and looked up ok, but perhaps not updated ok. Is there any mention of its branch in the logs?

**Comment by zephraph** [comment]
No, there's no mention of the branch.

**Comment by zephraph** [comment]
It look like is _has_ updated on some repos: https://github.com/artsy/fresnel/pull/92. That's the only one I could find specifically. 

We've had other orbs update recently https://github.com/artsy/metaphysics/pull/1815. 

Here's the last time the `yarn` orb was updated on that repo: https://github.com/artsy/reaction/pull/2436

**Comment by rarkins** [comment]
I think I guessed what it is. The `circleci` manager inherits `docker` settings, which includes this: https://github.com/renovatebot/renovate/blob/855d5fbae32a6bd116a67524480ebd8b40799374/lib/config/definitions.js#L1391

That rule should be removed one day, and also *orbs* should not be restricted by *docker* settings anyway, but in the meantime you can fix it this way:

```json
  "packageRules": [{
    "datasources": ["orb"],
    "major": { "enabled": true }
  }]
```

Verified here: https://github.com/renovate-tests/reaction/pull/3

**Comment by zephraph** [comment]
Ohh... interesting...

I'll try this. I'm still surprised that some would work when others didn't.

**Comment by rarkins** [comment]
@zephraph I think all *major* orb updates would have been disabled, anything else worked. e.g. 2.0.0 -> 2.1.0 was not major

**Comment by zephraph** [comment]
Sorry, this is fixed! I'm gonna close. Thanks for the help. We might want to update the docs on this.
