### ISSUE TITLE
[Question] No logs found after updating marketplace payment

### ISSUE THREAD

**Issue by scrtree** [renovatebot/config-help#301]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

I can't see logs.

<img width="1226" alt="スクリーンショット 2019-07-17 16 03 16" src="https://user-images.githubusercontent.com/2096658/61354226-aa820600-a8ac-11e9-8527-6bdf1d661d8d.png">

<img width="1608" alt="スクリーンショット 2019-07-17 16 06 27" src="https://user-images.githubusercontent.com/2096658/61354385-ffbe1780-a8ac-11e9-8bf6-d187d639f254.png">

https://renovatebot.com/dashboard#github/ikyucom/spa2/80705782

### What is your question?

Hi @rarkins,
Renovate doesn't work after failing to pay on Github.
I have updated my github payment.
What should I do to restart it?

**Comment by rarkins** [comment]
It can take 1-2 hours for marketplace plans to sync. How long has it been?

**Comment by scrtree** [comment]
It was yesterday that payment update to github was completed.
I have been waiting for about a day.

**Comment by rarkins** [comment]
Unfortunately GitHub's backend is not showing any plan. Can you email a screenshot of the ikyucom marketplace plan confirmation screen to support@renovatebot.com?

**Comment by scrtree** [comment]
OK, @rarkins. But I don't know where the screen.
How can I move to that screen? 🙇

**Comment by scrtree** [comment]
OK, @rarkins. I sent an email.
