### ISSUE TITLE
Including arbitrarily located package.json files

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#302]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

Hi, I have a repository with a root package.json and another one located in an arbitrary nested folder. Renovate does not pick up the nested one, probably because the file system structure doesn't resemble that of a monorepo. How do I make Renovate pick it up too?

**Comment by rarkins** [comment]
It should pick up any `package.json` in any folder so long as that folder doesn’t match a default ignore path (tests, examples, etc). What’s the exact path?

**Comment by simoneb** [comment]
@rarkins it is indeed in a subfolder of a folder named `test`

**Comment by rarkins** [comment]
Search past issues in this repo for “ignorePaths” for how to fix that

**Comment by simoneb** [comment]
cool, thanks
