### ISSUE TITLE
Ability to make Renovate a required status check in GitHub

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#304]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

Hi, I'd like to understand if it would be possible to use renovate to prevent merging a PR (not necessarily created by Renovate) in case Renovate detects a package containing a security vulnerability. Basically requiring a Renovate PR which addresses the security vulnerability, which I assume must have been already created by Renovate meanwhile, until the other PRs haven't rebased/merged the commit where the security vulnerability has been addresses.

I'm not entirely sure it's a good idea to do anything like that, but I'm just exploring the possibilities.

**Comment by rarkins** [comment]
Nothing like that possible currently, sorry. If you get some more solid ideas on how it could work then please raise a feature request in the main repo with the idea.
