### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by cfra** [renovatebot/config-help#307]
### Which Renovate are you using? CLI, App, or Pro

We are using the GitHub app for renovate.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

We are using GitHub.

### What is your question?

We are using Python and CircleCI. For both we would like to ignore Python 3.8 as it is currently still in beta.

For that purpose, we have added the following in our configuration:

```json
{
  "packagenames": ["circleci/python", "python"],
  "allowedversions": "<=3.7"
}
```

Currently, we are at Python 3.7.1. I would expect renovate to open a PR for 3.7.4. However, it keeps the PR for 3.8.0b1 open. Looking at the log I am confused why it only lists the update for 3.8, but not for 3.7.4:

```json
      {
            "depName": "circleci/python",
            "currentValue": "3.7.1",
            "datasource": "docker",
            "depType": "docker",
            "managerData": {
              "lineNumber": 8
            },
            "updates": [
              {
                "fromVersion": "3.7.1",
                "toVersion": "3.8.0b1",
                "newValue": "3.8.0b1",
                "newMajor": 3,
                "newMinor": 8,
                "updateType": "minor",
                "isSingleVersion": true,
                "newVersion": "3.8.0b1"
              }
            ],
            "warnings": [],
            "sourceUrl": null,
            "dockerRegistry": "https://index.docker.io",
            "dockerRepository": "circleci/python",
            "releases": [
              "3.7.1",
              "3.7.2",
              "3.7.3",
              "3.7.4",
              "3.8.0b1"
            ]
          }
```

What did I configure incorrectly? Any idea how I can fix this?

**Comment by rarkins** [comment]
First up, it's `allowedVersions` with capital `V` and not `allowedversions`.

The main challenge with Docker is "guessing" the versioning scheme used. Unlike with npm or python registries, where you can already know which versioning scheme is used (semver and pep440 respectively), with Docker it's a mix - some use semver, some use a quasi-semver (e.g. `1.2.0-alpine`), but they can use anything they want. In this case, do these images follow pep440 versioning? You could try this for example, to see if it's enough to get it to work:

```
{
  "packagenames": ["circleci/python", "python"],
  "versionScheme": "pep440"
}
```

If it works as I hope, it will use pep440 versioning to evaluate updates, which will mean it will skip the unstable `3.8.0b` versions without needing any `allowedVersions` rule.

**Comment by keimlink** [comment]
@rarkins Thanks for the suggestions! 🙇 After @cfra also capitalized the "n" in `packageNames` everything works like a charm. 😄

**Comment by cfra** [comment]
Indeed it does. Thank you. :+1:

**Comment by cfra** [comment]
On closer inspection, it seems like we were subject to premature enthusiasm. :wink:
The pull request for 3.8b1 disappeared with the following configuration:

```json
      {
        "packageNames": ["circleci/python", "python"],
        "versionScheme": "pep440"
      }
```

However, no pull request to update 3.7.1 to 3.7.4 showed up either. When inspecting the logs, I found the following:

```text
DEBUG: Dependency circleci/python has unsupported value 3.7.1
...
   {
            "depName": "circleci/python",
            "currentValue": "3.7.1",
            "datasource": "docker",
            "depType": "docker",
            "managerData": {
              "lineNumber": 8
            },
            "updates": [],
            "warnings": [],
            "skipReason": "unsupported-value"
          }
```

So apparently, the version cannot be parsed as `pep440`. :thinking:

**Comment by rarkins** [comment]
Hmm.. 

I think it’s because pep440 expects `=3.7.1`. I’m not sorry we can massage that with any rules or tricks currently. 

Next idea is to use either “semver” or “loose” as the versionScheme and then also allowedVersions to rule out the unstable 3.8, but I’m not sure that either will definitely work. Semver may reject 3.8.0b1 as an invalid version although maybe that would “accidentally” solve things for you if you’re not interested in unstable docker images anyway. 

Perhaps can you create a test repo to experiment with if you don’t want to keep experimenting in production?

**Comment by keimlink** [comment]
Another option may be to allow only specific update types:

```json
{
  "docker": {
    "packageRules": [
      {
        "packageNames": ["circleci/python", "python"],
        "updateTypes": ["patch", "pin", "digest"]
      }
    ]
  }
}
```

Minor updates would have to be done either manually or by temporary adding `minor` to `updateTypes`.

**Comment by cfra** [comment]
The test repository is actually a great idea.
It turns out, if you do it right, it actually works.
Both https://github.com/cfra/python-update-test/blob/master/renovate.json and https://github.com/cfra/python-update-test/blob/2aa00ac4116b8612878fff1b9142fdb50c4b6664/renovate.json lead to a PR being opened for 3.7.4.

**Comment by rarkins** [comment]
Thanks for sharing!
