### ISSUE TITLE
Onboarding PR description not updated

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#308]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

Just enabled Renovate on a repo, got the onboarding PR, made changes to it to reduce the number of PRs created by Renovate once merged (including bumping some package versions manually by changing package.json and yarn.lock file, changing the Renovate configuration file to ignore packages, ...).

Renovate doesn't seem to reflect those changes in the PR description, which is what we use to assess the outcome of our changes in terms of what PRs Renovate will create once enabled.

The last job run is 82617282

**Comment by rarkins** [comment]
This repository is being skipped as your Org shows up as having no active plan. The plan was detected as removed at `2019-07-24 01:25:25.651771+00`.

**Comment by simoneb** [comment]
Thanks @rarkins. Do you know if it was the trial that has ended or something else? Because at approximately the same time as when the trial was due to end we also experienced an outage and some of our repositories where disabled on GitHub.

**Comment by rarkins** [comment]
It looks like it happened right around the time of the free trial ending. According to the last record we sync'd from GitHub before the trial ended, `"free_trial_ends_on": "2019-07-23T00:00:00.000Z"`. Then our hourly sync process detected the removal of your account about an hour later (`2019-07-24 01:25:25.651771+00`). GitHub's Marketplace API just "disappears" accounts from the list of valid accounts without explanation, this is why we keep our own sync'd records so at least we can see what it looked like before it disappeared.

**Comment by rarkins** [comment]
Maybe the Renovate trial ending triggered an attempted credit card charge by GitHub, and then that charge failed for some reason, which caused (a) Marketplace entry removal, and (b) the other disabling you saw?

**Comment by simoneb** [comment]
Ok thanks for the additional info @rarkins, I'll try to figure out what happened.

**Comment by rarkins** [comment]
If the owner of the org visits https://github.com/marketplace/renovate, and makes sure to select the org account and not their personal account, it *should* show no plan is active for the org and *should* let you select a plan again, although presumably this time it will say you've already used up a free trial so the billing will start immediately.

**Comment by simoneb** [comment]
> If the owner of the org visits https://github.com/marketplace/renovate, and makes sure to select the org account and not their personal account, it _should_ show no plan is active for the org and _should_ let you select a plan again, although presumably this time it will say you've already used up a free trial so the billing will start immediately.

Once we do this, will we have to do anything else or the existing repositories we onboarded already will go back to a working state in terms of Renovate creating PRs for them?

**Comment by rarkins** [comment]
It should continue working after that. May take 2 hours to fully recover

**Comment by jerrymccollom** [comment]
So attempting to do this, I'm told "Unfortunately, invoiced customers cannot purchase paid plans on the GitHub Marketplace.".   We just changed over to enterprise billing yesterday.   What route do we go to purchase renovate?

**Comment by rarkins** [comment]
That's right, unfortunately GitHub doesn't support Marketplace payments once you switch to invoicing. They are meant to let you know this and provide contact details with the vendor(s) like us in such situations though.

Anyway, we support direct payment for Renovate plans via credit card (using Stripe). Please email billing@renovatebot.com and confirm the following details for sending the invoice/payment request:

- Company name for the invoice
- Name and email of the billing contact to send the invoice to

Once you send these we'll generate an invoice to that person and the email will contain a link for payment.
