### ISSUE TITLE
[Question] Python update for wagtail doesn't show up

### ISSUE THREAD

**Issue by cfra** [renovatebot/config-help#311]
### Which Renovate are you using? CLI, App, or Pro

This is happening on the GitHub app.
We are using Poetry and `pyproject.toml`.

### Have you checked the logs? Don't forget to include them if relevant

```json
     {
            "depName": "wagtail",
            "depType": "dependencies",
            "currentValue": "2.4",
            "managerData": {
              "nestedVersion": false
            },
            "datasource": "pypi",
            "updates": [],
            "warnings": [],
            "sourceUrl": null,
            "homepage": "http://wagtail.io/",
            "releases": []
          }
```

### What is your question?

There is a release 2.5.1 of wagtail: https://pypi.org/project/wagtail/#history

Why is it not picked up?

**Comment by rarkins** [comment]
Do you have any custom config relating to python/poetry?

**Comment by cfra** [comment]
Our general config is maintained here: https://github.com/picturepipe/renovate-config

Inside of the repository there is the following config:

```json

{
  "docker": {
    "packageRules": [
      {
        "packageNames": ["circleci/python", "python"],
        "allowedVersions": "<=3.7.3"
      }
    ]
  },
  "extends": ["github>PicturePipe/renovate-config"],
  "packageRules": [
    {
      "automerge": false,
      "depTypeList": ["devDependencies"]
    }
  ]
}
```

**Comment by rarkins** [comment]
Thanks, I'll see if I can reproduce the problem first.

**Comment by rarkins** [comment]
Were wagtail 2.5.2 or 2.6 picked up?
