### ISSUE TITLE
[Question] Encrypted NPM Token, published preset in private repo (github package registry) reporting as missing

### ISSUE THREAD

**Issue by ajcann** [renovatebot/config-help#313]
### Which Renovate are you using? CLI, App, or Pro

App (Org 25 Repo Plan)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yes, relevant section of log as follows:

```
DEBUG: Found package.json config file
INFO: package.json>renovate config
{
  "config": {
    "extends": [
      "@binxhealth"
    ],
    "encrypted": {
      "npmToken": "***********"
    },
    "npmrc": "***********"
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "@binxhealth"
    ],
    "encrypted": {
      "npmToken": "***********"
    },
    "npmrc": "***********"
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "@binxhealth"
    ],
    "encrypted": {
      "npmToken": "***********"
    },
    "npmrc": "***********"
  }
}
DEBUG: Found encrypted config
{
  "config": {
    "npmToken": "***********"
  }
}
DEBUG: Trying default padding for npmToken
DEBUG: Trying RSA_PKCS1_PADDING for npmToken
INFO: Decrypted npmToken
INFO: Migrating npmToken to npmrc
{
  "decryptedToken": "83************************************0a"
}
DEBUG: Replacing ${NPM_TOKEN} with decrypted token
DEBUG: Found npmrc in decrypted config - setting
DEBUG: Setting npmrc
DEBUG: Preset fetch error
{
  "err": {
    "message": "preset renovate-config not found",
    "stack": "Error: preset renovate-config not found\n    at Object.getPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/npm/presets.js:11:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
INFO: Throwing preset error
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Preset package is missing a renovate-config entry (@binxhealth)"
  }
}
```

### What is your question?

We've recently switched from self-hosted to the paid github app plan. Our repo's are configured as such.

An application's package.json has a dev dependency for @binxhealth/renovate-config": "^2.0.7"
and a renovate section

```
"renovate": {
    "extends": [
      "@binxhealth"
    ],
    "encrypted": {
      "npmToken": "[encrypted token]"
    },
    "npmrc": "@binxhealth:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}"
  }
```

The published package @binxhealth/renovate-config has a renovate-config section in it's package.json that looks like :

```
"renovate-config": {
    "default": {
      "extends": [
        ":combinePatchMinorReleases",
        ":ignoreUnstable",
        ":renovatePrefix",
        ":ignoreModulesAndTests",
        ":onlyNpm",
        ":prHourlyLimit1",
        ":noUnscheduledUpdates"
      ],
      "rangeStrategy": "bump",
      "suppressNotifications": [
        "prIgnoreNotification",
        "prEditNotification"
      ],
      "packageRules": [
        {
          "packagePatterns": [
            "^@binxhealth"
          ],
          "packageNames": [
            "husky",
            "@ianwalter/eslint-config",
            "@ianwalter/eslint-config-vue",
            "@packtracker/webpack-plugin"
          ],
          "automerge": true,
          "prHourlyLimit": 0
        },
        {
          "packagePatterns": [
            "^vue"
          ],
          "groupName": "Vue packages"
        },
        {
          "packagePatterns": [
            "^@ianwalter/bff"
          ],
          "groupName": "bff packages"
        },
        {
          "packagePatterns": [
            "^@babel"
          ],
          "groupName": "Babel packages"
        }
      ]
    }
  },
  "renovate": {
    "extends": [
      "@binxhealth"
    ],
```

Not sure if the package is being pulled down at all, but at the very least it appears the npm token is being decrypted correctly. Thanks for any help!

**Comment by rarkins** [comment]
Presets need to have a “renovate-config” Key/object in package.json and not “renovate”. Can you try renaming that section within the preset?

Btw using a private GitHub repo to host your preset rather than private non module may simplify things for you too.

**Comment by ajcann** [comment]
Hi @rarkins thank you for the response. Unless I'm mistaken you'll see there is a 'renovate-config' key/object in @binxhealth/renovate-config module. There is also a renovate section, however that's for the package's own renovate config.

The application being renovated has 
```
"renovate": {
    "extends": [
      "@binxhealth"
    ],
    "encrypted": {
      "npmToken": "[encrypted token]"
    },
    "npmrc": "@binxhealth:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}"
  }
```
in package.json. and @binxhealth/renovate-config's package.json has

```
"renovate-config": {
    "default": {
      "extends": [
        ":combinePatchMinorReleases",
        ":ignoreUnstable",
        ":renovatePrefix",
        ":ignoreModulesAndTests",
        ":onlyNpm",
        ":prHourlyLimit1",
        ":noUnscheduledUpdates"
      ],
      "rangeStrategy": "bump",
      "suppressNotifications": [
        "prIgnoreNotification",
        "prEditNotification"
      ],
      "packageRules": [
        {
          "packagePatterns": [
            "^@binxhealth"
          ],
          "packageNames": [
            "husky",
            "@ianwalter/eslint-config",
            "@ianwalter/eslint-config-vue",
            "@packtracker/webpack-plugin"
          ],
          "automerge": true,
          "prHourlyLimit": 0
        },
        {
          "packagePatterns": [
            "^vue"
          ],
          "groupName": "Vue packages"
        },
        {
          "packagePatterns": [
            "^@ianwalter/bff"
          ],
          "groupName": "bff packages"
        },
        {
          "packagePatterns": [
            "^@babel"
          ],
          "groupName": "Babel packages"
        }
      ]
    }
  }
```

**Comment by rarkins** [comment]
@ajcann Renovate's preset logic has not been tested against GPR and possibly there is an incompatibility if the data GPR returns is not close enough to npm's structure. We have not yet been invited into the beta program so therefore have no way of troubleshooting it. I recommend you try using a github private repo instead of private module for config as that is tested and works without problem (make sure that Renovate is installed in the preset repo though).

**Comment by rarkins** [comment]
By the way, the message `preset renovate-config not found` implies that Renovate *did* retrieve the metadata for this private module, but that the metadata doesn't contain a `renovate-config` section. Is it possible that GPR strips it out because it's non-standard?

**Comment by rarkins** [comment]
If you can use the access token and manually query the GitHub package registry (e.g. using curl, Postman, etc) to confirm what the resulting JSON looks like, it would help to know for sure what went wrong.

**Comment by jfairley** [comment]
@rarkins FWIW, I downloaded a GPR-deployed `renovate-config` package and the `"renovate-config"` entry in the `package.json` was still in there.

I'm getting this same error, btw. Scratching my head.

**Comment by jfairley** [comment]
Can you point me to the documentation for the private repo config? I'd like to try that.

**Comment by jfairley** [comment]
Ah. Found it. https://docs.renovatebot.com/config-presets/#github-hosted-presets
