### ISSUE TITLE
[Question] Possible onboarding issue with a repo

### ISSUE THREAD

**Issue by acmcelwee** [renovatebot/config-help#316]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
The renovate dashboard shows the repo, but the job history is empty.

### What is your question?
I'm in the process of onboarding a lot of our repos, and I initially created the onboarding PR for a repo (https://github.com/datadotworld/dev-tools) with the docker image and a GH access token. After creating that one, I setup the GH app for our org (https://github.com/datadotworld), and granted access to the repo via the app settings in GH. 

In trying to re-trigger the bot to reprocess our GitHub-hosted shared config (https://github.com/datadotworld/renovate-config/), I closed the PR, ended up deleting the branch, but then restoring the branch and re-opening the PR. Shortly after that, Renovate commented on the onboarding PR and stated that it was disabled because of missing config.

I've been unable to get renovate to run again for the onboarding PR, but I did merge it 3 hours ago to see if the `renovate.json` being present in the default branch would get Renovate to start generating the changes initially outlined in the onboarding PR. The repo shows up in our Renovate dashboard (https://renovatebot.com/dashboard#github/datadotworld/dev-tools), but the job log is still empty. I've tried removing the authorization for that repo in the GH app settings, waiting a few minutes until it disappeared from the renovatebot.com/dashboard, and then re-authorizing the app to ensure that it re-appears in the dashboard.

Is it possible that this repo has some stuck state somewhere from all of the manual intervention I did on the initial onboarding PR?

### Next, related question
I saw in https://github.com/renovatebot/config-help/issues/225 that there's currently no self-service support for defaulting the proposed `renovate.json` for a new onboarding, but that you handled it manually, by request. Would it be possible to have a setting updated on our GitHub org to default to this config for all new repos that we authorize? That would greatly speed up our onboarding process as we look to add all of our repos in the next few weeks.

```json
{
  "extends": [
    "github>datadotworld/renovate-config"
  ]
}
```

**Comment by rarkins** [comment]
There *are* logs for this repo present on our backend and the logs report 20 branches are required. 4 have been created while the rest are rate limited (perhaps this is a setting in your config?)

**Comment by acmcelwee** [comment]
Yeah, I ended up removing the repo again, waiting a while and re-adding. It was our first repo to merge the onboarding PR, so I was unsure what to expect, as far as when the bot would start submitting PRs. I merged a couple more onboarding PRs around the same time, and they also took a while to get started, so maybe there was just a large backlog of tasks? Either way, our first wave of repos is onboarded, and I've merged a few rounds of the initial upgrade PRs.

After the first wave of successful onboards yesterday, we're ready to make another big push and get another 20+ onboarded. Any chance we could get our organization's default config updated to the contents at the end of the original issue summary?

**Comment by rarkins** [comment]
I've added the following on the server side, will be active within 5 minutes:

```
    if (repository.startsWith('datadotworld/')) {
      repoConfig.onboardingConfig = {
        extends: ['github>datadotworld/renovate-config'],
      };
    }
```

**Comment by acmcelwee** [comment]
Thanks, @rarkins
