### ISSUE TITLE
[Question] How to pin to minor versions

### ISSUE THREAD

**Issue by TheKevJames** [renovatebot/config-help#318]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
What would be the config stanza I need to enable pinning to minor versions? I specifically care with respect to CircleCI orbs, but I imaging the same answer would apply globally.

For example, I have the following snippet in my CircleCI config:
```
orbs:
  aws-cli: circleci/aws-cli@0.1
```

I am currently trying to configure Renovate for the first time, and its trying to pin to `circleci/aws-cli@0.1.13`. I have the following config set for Renovate:
```
...
  "packageRules": [{
    "datasources": ["orb"],
    "patch": {
      "enabled": false
    }
  }],
...
```

And the sample configuration commit tells me it will open:
```
chore(deps): pin docker digests
    Schedule: "at any time"
    Branch name: renovate/docker-digests-pin
    Pin aws-cli to 0.1.13
```

**Comment by TheKevJames** [comment]
I've pushed a similar config to an OSS project to replicate this:
- [Renovate PR for pinning to a minor version](https://github.com/TheKevJames/web/pull/83)
- [Renovate configuration for that repo, disabling patches](https://github.com/TheKevJames/web/blob/master/.github/renovate.json#L9-L14)

**Comment by rarkins** [comment]
Renovate defaults to pinning enabled for Orbs: https://github.com/renovatebot/renovate/blob/628b66ffbfc58f0c0fb453b895c7a942c9155a28/lib/manager/circleci/extract.ts#L35

To override that requires changing `rangeStrategy` 

Please try this packageRule:
```
{
  "datatypes": ["orb"],
  "rangeStrategy": "replace"
}
```

**Comment by TheKevJames** [comment]
@rarkins that indeed seems to have avoided pinning to a minor version, but it also does not seem to enforce pinning to minors. Would there be any way to enforce that middle ground? eg. I would like to have `foo@x` pin to `foo@x.y`.

**Comment by rarkins** [comment]
No, we don’t have support for that type of partial pinning. You need to set your master branch to the level of precision you desire initially and then after that it will stay as-is.

**Comment by TheKevJames** [comment]
Gotcha. Alrighty, that works for me :+1: Thanks for all the help!
