### ISSUE TITLE
[Question] Why does `ignoreUnstable=true` for docker images pull beta versions?

### ISSUE THREAD

**Issue by TheKevJames** [renovatebot/config-help#319]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I've set [`"ignoreUnstable": true`](https://github.com/TheKevJames/web/blob/master/.github/renovate.json#L4), but Renovate is still trying to update my Python docker image to `3.8.0b1` (which I would expect to be disabled by this rule): [Renovate PR](https://github.com/TheKevJames/web/pull/89). Do beta's not count as unstable?

**Comment by rarkins** [comment]
This thread contains some relevant info on how versioning works in Docker: https://github.com/renovatebot/config-help/issues/307

In short: Docker versioning is arbitrary and Renovate can't automatically guess everything.

I suggest trying this packageRule:
```
{
  "packagenames": ["python"],
  "versionScheme": "pep440"
}
```

**Comment by TheKevJames** [comment]
Hmm, unfortunately `pep440` seems to disable all processing entirely if you use `-alpine` or any other such specifier. Is there any way to create a custom `versionScheme`? Docker versioning is indeed arbitrary, but it seems like as a general rule the popular packages tend to be at least consistent -- if we could share custom version schemes for the popular packages, that could be extremely useful.

**Comment by rarkins** [comment]
The package rule suggested would only apply to python specifically as you showed python without specifiers in your question. If you are using specifiers like -alpine then it’s not the same question or answer. 

There’s no possibility to combine pep440 versioning with specifiers so you probably need to stick with the default docker versioning and close PRs to ignore them any time there’s an unstable upgrade proposed.

**Comment by TheKevJames** [comment]
Gotcha. Ok, I'd be happy enough to implement this myself. I'll play around with what support for this would look like for the `renovate` package. Thanks for the help!

**Comment by rarkins** [comment]
For your reference, everything is under lib/versioning.

pep440 - should be strictly compliant with the spec (we ported it)
docker - this is a custom scheme we invented that follows the “typical” docker versioning approach (semver-ish with optional specifiers) 

You’d want to probably start by copying docker and call it something like pep440-docker and then replace any semver assumptions or functions there with the equivalent in pep440

Thanks!

**Comment by TheKevJames** [comment]
Thanks for the tips! I've got the beginnings of a more generalizable solution [here](https://github.com/TheKevJames/renovate/tree/add-regex-versioner) and I've already reached out to support@ with a question -- I suspect y'all wouldn't be too willing to merge something which only works for "how the python maintainers happen to version their docker images", but hopefully this more general solution can help for a good number of these "slightly different" versioning schemes.

**Comment by rarkins** [comment]
Could you create an issue in the main repo to discuss requirements and then also your proposed solution?

I took a quick look at your branch but wasn't 100% sure of everything going on. I saw a lot of refactoring to use `scheme.x` that increases the diff amount - are those mandatory or a matter of style? I usually prefer to separate refactoring from new features so that there's less chance of human error missing something.

**Comment by TheKevJames** [comment]
Unfortunately, those are mandatory (as far as I can tell -- I admit I'm somewhat of a novice at Typescript); it seems that the previous spreading we were doing was breaking usage of `this` in the versioning API. Once the branch is ready for human eyes / review, I'll certainly be splitting it into more digestible pieces.

[Created an issue](https://github.com/renovatebot/renovate/issues/4264)
