### ISSUE TITLE
[Question] Understanding the 'Pin dependencies' strategy

### ISSUE THREAD

**Issue by jeromelachaud** [renovatebot/config-help#322]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### What is your question?
There is something I don't understand about pinning dependencies :
I have pinned all the dependencies in the `package.json` but RB open pull requests which, as far as I understand, would have be opened, should I have chosen to add the caret.
For exemple : `react (source) dependencies minor 16.7.0 -> 16.8.6`
So my question is : what is the difference between pining dependencies and using semver with the caret in such case?
Many thanks.

**Comment by jeromelachaud** [comment]
I am updating this issue now as I can see RB opening requests for major changes
ie : `babel-eslint devDependencies major 8.2.6 -> 10.0.2`

**Comment by rarkins** [comment]
Have you seen https://renovatebot.com/dependency-pinning/ ?

The goal of pinning is not to ignore them - instead it’s to gain more predictability. Ignoring is a separate concept we also support, both temporarily (close any PR to ignore it) or permanently (`ignoreDeps`)

**Comment by jeromelachaud** [comment]
yes, I read it :)
I understand your answer about the ignoring concept.
Still not catch thought the concept of predictability as I don't understand how different the PRs would have been if I hadn't pinned the dependencies.

**Comment by jeromelachaud** [comment]
Maybe they wouldn't have been different at all, as pinning deps is just a strategy you want to apply in your project or not. Am I getting this right? 😄

**Comment by rarkins** [comment]
Kind of. If you use a range then developers need to dig into the lock file to know exactly what version is in use. Also the exact version used may change non-intuitively, Eg an update to direct dependency X may change the locked version of direct dependency Y if Y is a transitive dependency of X. Such “accidental” updating of Y wouldn’t happen if you pinned Y

**Comment by jeromelachaud** [comment]
Makes sense. Thanks for your time.
