### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#324]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

If we set a default, root level schedule different from the default one, will it override the schedule for vulnerability alerts? We would like to keep them coming in as soon as possible, of course.

**Comment by rarkins** [comment]
Yes that’s fine, vulnerability PRs bypass all scheduling and grouping

**Comment by simoneb** [comment]
Thanks! It may be worth specifying this in the docs, because it's definitely a sensible choice but not necessarily an obvious one.
