### ISSUE TITLE
Renovate no longer detecting updates needed

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/config-help#325]
**What Renovate type are you using?**
Renovate Docker via GitLab CI

**Describe the bug**
It seems as though Renovate is no longer creating any update MRs or commits in any of my projects, no config has changed to cause this.

**Did you see anything helpful in debug logs?**
Here is a full debug log of the last run, I can't see anything of interest:

https://gist.github.com/Jamesking56/4eb498039ef7084bd373037c15c352c3

**To Reproduce**

_No idea_

**Expected behavior**
I'm expecting Renovate to find some updates, as several of the projects definitely have outdated Composer dependencies

**Comment by rarkins** [comment]
The first thing you need to do is enable patch-only updates for that package:

```json
  {
    "packageNames": ["laravel/framework"],
    "separateMinorPatch": true
  }
```

Then, disable minor/major:

```json
  {
    "packageNames": ["laravel/framework"],
    "updateTypes": ["minor", "major"],
    "enabled": false
  }
```

I don't recall if we do "digest" updates for PHP though.

**Comment by Jamesking56** [comment]
I've now got:

```
{
    "extends": [
        "config:base",
        ":preserveSemverRanges",
        ":automergeDigest",
        ":automergePatch",
        ":pinSkipCi",
        ":assignAndReview(Jamesking56)",
        ":rebaseStalePrs",
        "preview:dockerCompose"
    ],
    "packageRules": [
        {
            "packageNames": ["laravel/framework"],
            "updateTypes": ["minor", "major"],
            "enabled": false
        },
        {
            "packageNames": ["phpunit/phpunit"],
            "updateTypes": ["minor", "major"],
            "enabled": false
        },
        {
            "packageNames": ["node-sass"],
            "updateTypes": ["minor", "major"],
            "enabled": false
        }
    ],
    "dockerfile": {
        "enabled": false
    },
    "gitlabci": {
        "enabled": false
    }
}
```

Is this valid config?

**Comment by rarkins** [comment]
Looks ok but without separating minor from patch as I suggested then you won’t see any patches as they get classified as minor and then disabled too. By default Renovate treats patches and minor as the same.
