### ISSUE TITLE
Go Modules Vendor Configuration

### ISSUE THREAD

**Issue by alexcurtin** [renovatebot/config-help#326]
### Which Renovate are you using? CLI, App, or Pro
App
### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Gitlab
### What is your question?

The renovate bot is opening/closing many many MRs a day for a project that uses go modules and a vendor folder. Thats because it checks all the vendor/ go.mod files and is constantly updating MRs as those projects release new versions (like 50 PRs a day). Can I configure Renovate for Go module projects but configure it to ignore the vendor folder and only focus on the root go.mod?

**Comment by rarkins** [comment]
Add `:ignoreModulesAndTests` to your `extends` array. It comes as part of `config:base` but I’m guessing you’re not using that? Search for it by name here: https://renovatebot.com/presets-default/

**Comment by alexcurtin** [comment]
Hi @rarkins thanks for the prompt reply, that link 404s. My renovate config is just `{}` at the moment

**Comment by rarkins** [comment]
That URL got strangely messed up when I copied/pasted it from mobile. Here's the deep link: https://renovatebot.com/docs/presets-default/#ignoremodulesandtests

I suggest you take a look at what the `config:base` preset includes, such as the monorepo groupings: https://renovatebot.com/docs/presets-config/#configbase
