### ISSUE TITLE
[Question] How not to pin versions in sub folder `package.json`s?

### ISSUE THREAD

**Issue by simison** [renovatebot/config-help#328]
### Which Renovate are you using? CLI, App, or Pro
— _Don't know from top of my head but I can figure this out if need._

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?

We have a monorepo which contains multiple `package.json` files.

We’ve pinned versions in our root [`package.json`](https://github.com/Automattic/wp-calypso/blob/062d878aea5d7a0d34d3795401c8ae8befb09452/package.json) but then we have two separate folders ([1](https://github.com/Automattic/wp-calypso/tree/062d878aea5d7a0d34d3795401c8ae8befb09452/apps), [2](https://github.com/Automattic/wp-calypso/tree/062d878aea5d7a0d34d3795401c8ae8befb09452/packages)) for NPM packages that we’re publishing from that folder. Dependency versions on those folders should most of the time _not_ be pinned ([example](https://github.com/Automattic/wp-calypso/blob/062d878aea5d7a0d34d3795401c8ae8befb09452/apps/full-site-editing/package.json#L32-L48)), although sometimes we might choose to do so.

We [had two months running PR](https://github.com/Automattic/wp-calypso/pull/33615) where Renovate bot was trying to pin versions... :-D

I looked at config docs but nothing specifically stood out as a way to relax rules only for one subfolder.

Thoughts? :-) Thanks in advance!

cc @flootr,  @jsnajdr

**Comment by rarkins** [comment]
[packageRules](https://renovatebot.com/docs/configuration-options/#packagerules) can solve most of these types of things.

You can hopefully solve it like this:

```json
  "packageRules": [{
    "paths": ["apps/full-site-editing/package.json"],
    "rangeStrategy": "replace"
  }]
```
