### ISSUE TITLE
automerging with a merging commit

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/config-help#329]
I need renovate to automerge PRs with a merging commit.
I used to have `"automergeType": "pr",` (the default value) so it was automerging but without pushing a merging commit.

I thought `"automergeType": "pr-comment",` will work but it just posts a comment with `automergeComment` message which looks strange.

The third possible value (https://renovatebot.com/docs/configuration-options/#automergetype) is `branch` but I guess it won't work in my preferred way as well.

The merging commit is important for me because I have a script checking changed files in the last merged PR so without the merging commit we have only some commits but we cannot see the merging in the commits history.

**Comment by rarkins** [comment]
Renovate will attempt whichever type of commits are allowed in the repo, starting with Rebase, then Squash, then Merge Commit. Have you considered disallowing Rebase and Squash merges in the repo altogether?

Internally we use the option `mergeMethod` but this is not currently exposed via config.

**Comment by piotr-s-brainhub** [comment]
Thanks. I would like to have a possibility of squashing. However I can either squash locally and force push or allow squashing temporarily.

However disallowing rebase and allowing squash could be satisfactory because AFAIK renovate won’t merge if there are any my commits.

**Comment by rarkins** [comment]
Renovate should never automerge on its own if any developer has added commits. So the discussion of merge/squash/rebase only applies to PRs thatvhave a single commit (Renovate’s)

**Comment by gjoseph** [comment]
I was also looking for this -- while I want to allow rebase and squash merges on the repo, I would like to configure Renovate to use merge commits when it does automerge.
(although I don't have a huge argument as to why other than force of habit)
