### ISSUE TITLE
[Question] Update just one package

### ISSUE THREAD

**Issue by EnderDev** [renovatebot/config-help#330]
### Have you checked the logs? Don't forget to include them if relevant
N/A

### What is your question?
How would I only update 'electron' when an update is available for it. I don't want any other package, just electron.

**Comment by rarkins** [comment]
This should work:

```json
{
  "packageRules": [{
    "excludePackageNames": ["electron"],
    "enabled": false
  }]
}
```

**Comment by EnderDev** [comment]
Thank you!
