### ISSUE TITLE
Lock File Maintenance in Monorepos

### ISSUE THREAD

**Issue by sidharthachatterjee** [renovatebot/config-help#333]
Not sure if this should be opened here or in https://github.com/renovatebot/config-help

Apologies if I opened this in the wrong repo. 

We just enabled Renovate for all packages in the [gatsbyjs](https://github.com/gatsbyjs/gatsby) monorepo

One thing that isn't clear currently is lock file maintenance for the root `yarn.lock` 

It doesn't seem to be updated in every PR (for example in https://github.com/gatsbyjs/gatsby/pull/16783) 

https://github.com/renovatebot/renovate/blob/master/website/docs/configuration-options.md#lockfilemaintenance does mention that it will get updated once a week but we would prefer if this is updated per PR. Is this possible and if yes how would I enable it? 🙂 

Thank you so much for Renovate once again!

**Comment by rarkins** [comment]
Turns out it was config after all. Check out https://github.com/gatsbyjs/gatsby/pull/16816 for a resolution.

Example PR from fork: https://github.com/renovate-tests/gatsby-1/pull/8/files

**Comment by sidharthachatterjee** [comment]
@rarkins You're fantastic! Thank you so much for the quick resolution and for opening the PR. We really really appreciate this! 💜

**Comment by rarkins** [comment]
@sidharthachatterjee you're welcome! Check out your new Master Issue for some nice visibility into your 200+ dependency updates pending :D

https://togithub.com/gatsbyjs/gatsby/issues/16840

**Comment by sidharthachatterjee** [comment]
This is amazing! 💃
