### ISSUE TITLE
[Question] Why Node.js updates only proposed for Docker images but not for .nvmrc and engines field?

### ISSUE THREAD

**Issue by keimlink** [renovatebot/config-help#337]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
Yes

### What is your question?
Why Node.js updates only proposed for Docker images but not for `.nvmrc` and `engines` field?

#### Background information

We have a project that's uses Node.js. On development machines the Node.js version is configured with npm/nvm, on CircleCI it's configured as Docker tag.

When Renovate creates a pull request to update the Node.js version, it only does this for the Docker tag. It ignores `.nvmrc` and `engines` field.

When the CircleCI configuration is not present, updates to `.nvmrc` and `engines` field are proposed.

#### Resources

- [Example repository](https://github.com/PicturePipe/renovate-test)
- Our [Preset Config](https://github.com/PicturePipe/renovate-config)
- [Onboarding pull request](https://github.com/PicturePipe/renovate-test/pull/1)
    - Proposed updates to `.nvmrc` and `engines` field
    - At this time the [repository](https://github.com/PicturePipe/renovate-test/tree/d6de6dbb21c36b84200153782e1c4fa336e941df) did not contain a CircleCI configuration
    - [Renovate log](https://renovatebot.com/dashboard#github/PicturePipe/renovate-test/89853849)
- [Pull request #3](https://github.com/PicturePipe/renovate-test/pull/3) to update Node.js to v12.9.0
    - At this time a CircleCI configuration had been added to the [repository](https://github.com/PicturePipe/renovate-test/tree/1fe91f7e8ae5a5a33f5d2238fd61869d0c50299f)
    - [Renovate log](https://renovatebot.com/dashboard#github/PicturePipe/renovate-test/89859099)
- Adding `supportPolicy` with `lts_latest` to [`renovate.json`](https://github.com/PicturePipe/renovate-test/blob/4a1cd81db8b1f61c9c3839b6e825921ebcec84ae/renovate.json#L4) does not change the behavior
    - Only the title of pull request #3 has been [updated](https://github.com/PicturePipe/renovate-test/pull/3#event-2582870903) to "chore(deps): update node.js to v12.9.0"
    - [Renovate log](https://renovatebot.com/dashboard#github/PicturePipe/renovate-test/90571231)

**Comment by rarkins** [comment]
This might be a bug.

```
         "nvm": [
           {
             "packageFile": ".nvmrc",
             "manager": "nvm",
             "deps": [
               {
                 "depName": "node",
                 "currentValue": "12.8.1",
                 "datasource": "github",
                 "lookupName": "nodejs/node",
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": "https://github.com/nodejs/node",
                 "releases": ["v12.9.0"]
               }
             ]
           }
         ]
```

Updates is empty but releases is not. I'll debug it deeper.

**Comment by rarkins** [comment]
This is weird. The same `.nvmrc` on its own works fine: https://github.com/renovate-tests/nvm7/pull/2

**Comment by rarkins** [comment]
But then adding in your preset closes it. So at least now we've narrowed it down.

**Comment by rarkins** [comment]
With the default preset, it checks https://api.github.com/repos/nodejs/node/git/refs/tags/v12.9.0 whereas with your preset Renovate checks for https://api.github.com/repos/nodejs/node/git/refs/tags/12.9.0 and fails. Next step is to try to work out why.

**Comment by rarkins** [comment]
See https://github.com/PicturePipe/renovate-config/pull/36

It would be very challenging to fix this with code right now.

Example PR: https://github.com/renovate-tests/renovate-test-1/pull/2/files

**Comment by keimlink** [comment]
Thank you so much for debugging and providing a quick fix! 🙇

Everything works now as expected. 💯
