### ISSUE TITLE
Default or catch-all packageRule

### ISSUE THREAD

**Issue by mhalmagiu** [renovatebot/config-help#339]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
We're trying to get renovate to update our JS packages. What I'd like is a structure where there are a number of defined rules and if none of these rules match, then some default is applied.

Specifically, we'd like to group our own packages together and update them all the time, update React packages once a day as a group and then as a catch-all, update all other packages once a day in a group called "3rd Party Deps".

I noticed that in your design decisions documentation, you mention that there is a cascading configuration model: https://github.com/renovatebot/renovate/blob/master/docs/design-decisions.md Could this be used to implement this?

How would I go about implementing this? What I have looks like this:

```
{
  "extends": [
    "config:base"
  ],
  "enabledManagers": ["npm"],
  "timezone" : "Europe/Helsinki",
  "prHourlyLimit" : 5,
  "packageRules": [{
    "packagePatterns": ["^@MyCompany"],
    "groupName": "MyCompany Libs"
  } {
    "packagePatterns": ["^react"],
    "schedule": ["after 10pm every weekday, before 5am every weekday"],
    "groupName": "React Packages"
  }, {
    "managers" : ["npm"],
    "schedule": ["after 10pm every weekday, before 5am every weekday"],
    "groupName": "Third Party Dependencies"
  }]
}
```

But this just ends up matching all packages and ignoring both the react groups and the MyCompany group. 

If we place the ``` "managers" : ["npm"]``` block at the top, it seems to do what we want, but I can't find this documented anywhere, so I don't feel safe depending on it.

cc: @cy6erskunk

**Comment by rarkins** [comment]
Put the least important package rule first. Renovate will test matching *all* rules and not stop once it matches one. So you need your default rule first and then ones after it essentially "override" the ones before.

**Comment by mhalmagiu** [comment]
Is this documented somewhere? The way you put it is quite logical, but it would be nice to know that I can depend on this behavior going forward.

**Comment by rarkins** [comment]
I updated the docs to officially document this.

**Comment by mhalmagiu** [comment]
Thank you, kind sir!
