### ISSUE TITLE
Disable nvm version bumps

### ISSUE THREAD

**Issue by robinvdvleuten** [renovatebot/config-help#34]
Hi there! I am using Renovate on a couple of repos and was wondering if it's possible to disable version bumps on `.nvmrc` files.

**Comment by rarkins** [comment]
Yes, you can. To disable `.nvmrc` renovation:

```
  "nvm": {
    "enabled": false
  }
```

**Comment by robinvdvleuten** [comment]
@rarkins thanks! I couldn't find anything about it in the docs

**Comment by rarkins** [comment]
You can also use the `enabledManagers` config option if you wish to only "opt in" to certain managers (e.g. `npm` only).
