### ISSUE TITLE
Reconfigure Renovate PR checking on Bitbucket Server

### ISSUE THREAD

**Issue by pkey** [renovatebot/config-help#341]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket

### Have you checked the logs? Don't forget to include them if relevant
-

### What is your question?
How does reconfiguring Renovate option (https://docs.renovatebot.com/reconfigure-renovate/) actually work? I have tried making PR with "Renovate" name, branch with 'renovate' name in it (not in the prefix, obviously) and also putting "Renovate" into the commit name. Nothing seems to have any effect. 

In the description, it says that renovate should run some kind of validation.

**Comment by rarkins** [comment]
I suspect this feature might not be possible for Bitbucket. Are you using Cloud or self-hosted Server?

**Comment by pkey** [comment]
@rarkins It's self-hosted.

**Comment by rarkins** [comment]
Unfortunately it seems like we don't have all the pieces together for this to work for Bitbucket yet. This capability has actually been quite challenging so I am considering deprecating it for all platforms. Renovate installed via npm comes with a `renovate-config-validator` command that you can possibly use in your CI to check PRs too.
