### ISSUE TITLE
[Question] Doesn't respect allowedVersion for angular 1.5

### ISSUE THREAD

**Issue by deiga** [renovatebot/config-help#342]
### Which Renovate are you using? 
App

### Which platform are you using? 
GitHub

### What is your question?

We have 
```
    {
      "packageNames": ["angular", "angular-mocks", "angular-resource"],
      "allowedVersions": "< 1.6"
    }
```

in our rules, but still Renovate wants to make a PR for upgrading angular to 1.6

![Screenshot 2019-08-30 at 15 10 35](https://user-images.githubusercontent.com/27202/64023330-59666280-cb38-11e9-8f29-5ba8013dd0ff.png)

That the last rule in our `packageRules`, so I'm not entirely sure why it still offers to make that PR?

**Comment by rarkins** [comment]
Can you reproduce the same behaviour in a public repo if you have only that rule?

**Comment by deiga** [comment]
@rarkins Unfortunately, I can https://github.com/deiga/ayling

**Comment by rarkins** [comment]
That’s because the vulnerability/security rule is taking highest precedence. What version does the vulnerability alert say to upgrade to? Eg is there a 1.5.x that’s non vulnerable?

**Comment by deiga** [comment]
@rarkins Okay, that's a nice idea, definitely. The problem here is that major or minor upgrades are very problematic, even though security ones.

Unfortunately, no patch version exists for that vulnerability.

**Comment by rarkins** [comment]
In this case I think you need to close that security PR to ignore it. We need security updates to remain as the highest priority to override other rules like grouping and schedule.
