### ISSUE TITLE
unable to find option to control which GitHub user creates the Renovate PRs

### ISSUE THREAD

**Issue by bryndyment** [renovatebot/config-help#344]
I have two GitHub repos, and Renovate is opening its PRs with the `renovate` user on one of them, and a (human) developer on the other.  Note that it's an automated process in both cases.

I was responsible for installing Renovate on the first PR, and it appears that `renovate` is the default user for its PRs.

I'm trying to determine which configuration option controls this setting so that I can change it in the other repo.

I don't see a setting in the config for either of these two repos, and reading about the various config options only mentions PR assignees and reviewers.

Help?

**Comment by bryndyment** [comment]
I think this is a GitHub API limitation?

**Comment by rarkins** [comment]
The user is always tied to the token that's being used. If you've installed the app, then PRs will come from the "renovate" bot account. But if you run it yourself using a personal access token, they will show up as your own PRs. You need to (a) stop running it yourself on the second repo, and then (b) install the app into the second repo.

**Comment by bryndyment** [comment]
> The user is always tied to the token that's being used. If you've installed the app, then PRs will come from the "renovate" bot account. But if you run it yourself using a personal access token, they will show up as your own PRs. You need to (a) stop running it yourself on the second repo, and then (b) install the app into the second repo.

^ @anchan828
