### ISSUE TITLE
[Question] Allow PR to be opened only on passing CI test

### ISSUE THREAD

**Issue by selfrefactor** [renovatebot/config-help#345]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

I expected Renovate PR to be opened only if the tests in CI is passing. 
As you can see in [https://github.com/selfrefactor/rambda/pull/244](https://github.com/selfrefactor/rambda/pull/244) that is not the case. I am wondering if this can be set with config settings.

**Comment by rarkins** [comment]
See [prCreation](https://docs.renovatebot.com/configuration-options/#prcreation). You probably want to consider `not-pending` instead of `status-success` though.
