### ISSUE TITLE
Update non-pinned private packages

### ISSUE THREAD

**Issue by fwal** [renovatebot/config-help#35]
I would like to get updates to non-pinned private packages but so far to no avail. If I pin the packages then they get updated. This only seem to affect private packages.

Example config:
```javascript
module.exports = {
  extends: ['config:base', 'docker:disable', ':semanticCommits', ':preserveSemverRanges'],
}

```

**Comment by rarkins** [comment]
First point let's solve is private vs non-private. All behaviour about pinning or not pinning should be completely independent of whether a package is private or not.

1. Are the packages private (requires login/password) or just scoped?
2. If they are private, it doesn't look like you've set up any authentication if the above is your entire config

**Comment by rarkins** [comment]
BTW you say that if you pin them then they get updated. This implies that either (a) you have configured auth, or (b) they are not actually private. Please let me know which it is and how the auth is configured if so.

**Comment by fwal** [comment]
They require login, I've configured .npmrc

**Comment by fwal** [comment]
I might very well trip on the semantic versioning... If package.json states `^1.1.4` for a package then I should receive version `1.2.0` if it exists (or am I missing something?)

**Comment by fwal** [comment]
Oh it was the case that the public packages that worked was actually pinned or I received major bumps.

**Comment by fwal** [comment]
Ah nice! Thank you! Yeah, we're currently having debates over ranges so I wanted it to be minimal fiction at first when introducing Renovate and improve from there. 🙂

**Comment by rarkins** [comment]
I understand that. Introducing Renovate at "unrestricted speed" can be overwhelming for some team members. However.. if you enable `upgradeInRange` then you're still going to see just as many updates as if you had pinned in the first place.

An alternative if you're using lock files and want to keep `package.json` as untouched as possible is to enable weekly lock file maintenance, that way your lock file gets refreshed to the latest versions once a week while your ranges in `package.json` stay as they are.
