### ISSUE TITLE
Setup automerge on a protected branch

### ISSUE THREAD

**Issue by terodox** [renovatebot/config-help#351]
[Redacted]

**Comment by terodox** [comment]
Found answer

**Comment by rarkins** [comment]
Anything you could add to the documentation?

**Comment by terodox** [comment]
I opened a new PR to help with the documentation question.  See #352 for more information.

I basically realized I needed an approval for auto-merging based on our current setup. I found a lot of references to renovate-approval-bot, but I don't see instructions on it's actual use!
