### ISSUE TITLE
Renovate-approve-bot

### ISSUE THREAD

**Issue by terodox** [renovatebot/config-help#352]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
I'm looking to use the renovate-approve-bot, but I don't see it in the marketplace. What is the magic needed to take advantage of the renovate-approve-bot?

**Comment by rarkins** [comment]
It’s free so not in marketplace. See https://github.com/apps/renovate-approve-bot

**Comment by terodox** [comment]
Whoa, AWESOME. Thank you! I clicked this link half a dozen times yesterday and got 404s, today ✨ 

Thanks for all the help!

**Comment by floristenhove** [comment]
We're looking for something similar for our Gitlab.com MRs. We're using approval rules and require a minimum number of approvals on MRs but this does mean that automerging Renovate bot MRs can not be automatically merged. Is there a solution already out there that I may have missed?

_Sorry for hijacking this issue, please let me know if I should open a new issue._
