### ISSUE TITLE
Dismiss stale pull requests and renovate-approve-bot

### ISSUE THREAD

**Issue by terodox** [renovatebot/config-help#354]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
Everything works wonderfully for a single PR that is opened, CI passes, renovate-approve-bot approves, and it auto-merges.

BUT when there are multiple PRs, it goes more like this:
10 PRs are opened
All CI runs and passes
Renovate-approve-bot approves all PRs
First PR merges
All other PRs auto-rebase
Initial approval is invalidated because it's now stale (This is a branch protection rule)
The other 9 PRs can no longer auto-merge

I'm hoping there's a potential answer to this issue, because it's a very common occurrence for me.

This is the rule in question that is important to us (we work in a pretty bug org):
![image](https://user-images.githubusercontent.com/4835893/64829833-f21aca80-d59b-11e9-9a1c-b5fb5deec900.png)

Any information you can provide would be awesome!

Thanks!

**Comment by rarkins** [comment]
It's an open issue here, please follow/comment it instead: https://github.com/renovatebot/renovate-approve-bot/issues/10
