### ISSUE TITLE
How to configure pure git tags

### ISSUE THREAD

**Issue by micheelengronne** [renovatebot/config-help#356]
Following the issue https://github.com/renovatebot/renovate/issues/3886

pure git-tags support seems implemented. But there is no doc on how to use it.

My usecase is simple. I would like to ensure immutability of the repository https://github.com/kubernetes-sigs/kubespray in my projects.

The only tagging system consistent for that project is git tagging. It does not provide neither a pip package nor a Docker image.

Thanks.

**Comment by rarkins** [comment]
What type of package manager / package file is this repository defined in? i.e. what exactly in your own repo do you need to keep up to date?

**Comment by micheelengronne** [comment]
In no package manager. It's a pure git repo.

If you know a way to `git clone` from a file, I am interested. Otherwise this bash script do the trick:

```
#!/usr/bin/env bash
set -e

repos=$(cat requirements-git.txt)

IFS='\n' read -a tagsplit <<< "${repos}"

for repoelement in $repos
do
    IFS='@' read -a tagsplit <<< "${repoelement}"
    IFS='/' read -a foldersplit <<< "${tagsplit[0]}"
    IFS='.' read -a foldername <<< "${foldersplit[-1]}"

    echo "Cleaning old repo"
    mkdir -p gitrepos
    rm -Rf gitrepos/${foldername[0]}

    echo "Repo added"
    echo ${tagsplit[0]}

    cd gitrepos
    git clone ${tagsplit[0]}

    echo "With tag"
    echo ${tagsplit[1]}
    echo "on folder"
    echo ${foldername[0]}

    cd ${foldername[0]}
    git checkout ${tagsplit[1]}

    cd ../../
done
```

with this `requirements-git.txt`:

```
https://github.com/kubernetes-sigs/kubespray.git@v2.11.0
https://github.com/renovatebot/renovate.git@19.43.1
```

The idea is to have a reference somewhere and do a simple `git clone` from this reference.

**Comment by rarkins** [comment]
The limitation here is that we don't have a way to renovate values in arbitrary files, so unfortunately this is not solvable just yet. Please subscribe to https://github.com/renovatebot/renovate/issues/1938 for updates. It's something I hope to have ready pretty soon.
