### ISSUE TITLE
[Question] group updates by package instead of dependencies in a monorepo

### ISSUE THREAD

**Issue by iamdey** [renovatebot/config-help#359]
### Which Renovate are you using? CLI, App, or Pro

cli

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

gitlab

### What is your question?

It is probably not recommended but I would l like to have one MR with several updates for each packages of a monorepo.

_(The reason are the current state of our CI and the ownership of those packages, but well it can changes)_

For I am configuring the repo like this using a whitelist of packages to manage:

```
{
  "extends": [
    ":preserveSemverRanges"
  ],
  "includePaths": [
    "libs/acl/*",
    "libs/authentication/*",
     …
  ]
 }
```

The onboarding PR is updating with that kind of info:

> With your current configuration, Renovate will create 57 Merge Requests:
> Update dependency chai-enzyme to ^0.8.0
> Update dependency colors to v1.3.3
> …

Is it possible to have {N} MRs instead of those 57, N corresponding to the number of detected packages.

I try to find answer into #299 and others but I wasn't able to find what to add in the `packageRules`:

```
{
  …
  "packageRules": [
    {
      "paths": ["libs/**"],
      "packagePatterns": ".*"
    }
  ]
}
```

**Comment by iamdey** [comment]
you are right, it is more like `nb MRs <= nb packages`

**Comment by iamdey** [comment]
the important thing is not the number of MRs or packages.  
I need to leave the responsibility of merging updates to each package maintainers.

**Comment by rarkins** [comment]
Sorry but I still don’t understand what you mean. Do you mean each package within a monorepo needs it’s own group?

**Comment by iamdey** [comment]
I think yes.

**Comment by rarkins** [comment]
How many separate packages do you have?

**Comment by iamdey** [comment]
about 60

**Comment by rarkins** [comment]
So if something like eslint is updated you want 60
separate MRs for it?

**Comment by iamdey** [comment]
I know it is a bad idea, but the current state of our argonization, packages, CI (and technical debts) requires a fine tune. So yep, I need to know if it is possible.

Of course it's the first step in order to have an up-to-date environment.

For now I have whitelisted some of the packages to limit to ~10 separated MRs.

**Comment by rarkins** [comment]
If you were to do this manually, you'd need packageRules for each separate group you have, e.g.

```json
  "packageRules": [{
    "paths": ["libs/acl/*"],
    "branchPrefix": "renovate/acl-",
    "commitMessageSuffix": "(acl)"
  }]
```

Can you manually add a couple of rules like this and verify if this is what you had in mind?

**Comment by iamdey** [comment]
I'll try that asap. many thanks.

**Comment by iamdey** [comment]
ok it's a start:

> With your current configuration, Renovate will create 92 Merge Requests
> Update dependency flow-bin to ^0.108.0 (acl)
> Update dependency flow-bin to ^0.108.0 (sse-poller)
> Update dependency flow-bin to v0.108.0
> Update dependency enzyme to v3 (acl)
> …

Now I need to combine all {packageName} MRs into one.  
I've tweaked a bit the config, but it still doesn't combine by {packageName}:

```
{
  "extends": [
    ":preserveSemverRanges"
  ],
  "includePaths": [
    "libs/acl/*",
    "libs/sse-poller/*",
    // …  some other package I want to enable later
  ],
  "packageRules": [
    // disable all by default
    {
      "paths": ["**/*"],
      "enabled": false
    },
   // current enabled packages
    {
      "paths": ["libs/acl/*"],
      // It looks like it has no effects
      "packagePatterns": [".*"],
      "branchPrefix": "renovate/acl-",
      "commitMessageSuffix": "(acl)",
      "enabled": true
    },
    {
      "paths": ["libs/sse-poller/*"],
      "packagePatterns": [".*"],
      "branchPrefix": "renovate/sse-poller-",
      "commitMessageSuffix": "(sse-poller)",
      "enabled": true
    }
  ],
  "schedule": "at any time"
}
```

and so the result:

> With your current configuration, Renovate will create 33 Merge Requests:
> Update dependency flow-bin to ^0.108.0 (acl)
> Update dependency flow-bin to ^0.108.0 (sse-poller)
> Update dependency enzyme to v3 (acl)
> …

**Comment by iamdey** [comment]
Woot, It seems I've missed `groupName` wich has an important mission! 
It looks pretty good now:

> With your current configuration, Renovate will create 4 Merge Requests:
> Update acl deps (acl)
> Update dependency flow-bin to ^0.108.0 (sse-poller)
> Update acl deps (acl) (major)
> Update sse-poller deps (sse-poller) (major)

Config:

```
{
  "extends": [
    ":preserveSemverRanges"
  ],
  "includePaths": [
    "libs/acl/*",
    "libs/sse-poller/*",
    // …  some other package I want to enable later
  ],
  "packageRules": [
    // disable all by default
    {
      "paths": ["**/*"],
      "enabled": false
    },
   // current enabled packages
    {
      "paths": ["libs/acl/*"],
      // It looks like it has no effects
      "packagePatterns": [".*"],
      "groupName": "acl deps",
      "branchPrefix": "renovate/acl-",
      "commitMessageSuffix": "(acl)",
      "enabled": true
    },
    {
      "paths": ["libs/sse-poller/*"],
      "packagePatterns": [".*"],
       "groupName": "sse-poller deps",
      "branchPrefix": "renovate/sse-poller-",
      "commitMessageSuffix": "(sse-poller)",
      "enabled": true
    }
  ],
  "schedule": "at any time"
}
```

I'm not sure about the usefulness of `branchPrefix` and `commitMessageSuffix`, but it looks way better.

Thanks for your time @rarkins , thanks for renovate. I hope we will use it internally now.

**Comment by rarkins** [comment]
True, if you are adding a groupName then you could remove the branchPrefix and commitMessageSuffix from the rules. They were only necessary if you wanted separate MRs for each dependency per-package.
