### ISSUE TITLE
How to use the docker image

### ISSUE THREAD

**Issue by guillaumebriday** [renovatebot/config-help#360]
### Which Renovate are you using? CLI, App, or Pro
Docker image

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Whatever

### What is your question?
I want to self host my renovate bot. I found [this](https://github.com/renovatebot/renovate#self-hosting) in the documentation. But I think it's not clear.

How could I specify options or plateform? Via .env? Via config file? How to upgrade?

When I run `docker run renovate/renovate`, of course I got an error message `FATAL: You must configure a GitHub personal access token`.

I don't know what to do next.

Thank you in advance, renovate is awesome!

**Comment by rarkins** [comment]
Renovate does not support `.env` files so if you want to pass in environment variables to the Docker container then you need to do it the usual way for docker. You can also map in a `config.js` file if you prefer.

More info here: https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md

**Comment by guillaumebriday** [comment]
Ok it was hard to find this one. Thank you! I will check it out.

I submitted a PR to add the link in the readme.
