### ISSUE TITLE
[Question] weekday of month schedule syntax

### ISSUE THREAD

**Issue by jzempel** [renovatebot/config-help#361]
### Which Renovate are you using? CLI, App, or Pro
app

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?

I'd like to configure for a renovate run "every third Friday of the month". My goal is to reduce renovate clumping that we get across repos by spreading the PRs. i.e.
- `react-containers` = first Wednesday of the month
- `react-components` = second Thursday of the month
- `css-components` = third Friday of the month

We're already successfully using renovate on https://github.com/zendeskgarden; we just need to reduce the noise a bit. I haven't committed these changes, but I'm getting syntax errors whenever I try to parse various text phrases via `later` – I've tried loads of phrases. The only two I'm getting no error on are:
- "every 4 weeks on Friday" (which doesn't ensure I'm spreading the PRs)
- "every 4 weeks starting on the 3rd week" (I'm not really sure what this even means – 3rd week of what?)

What is the schedule syntax I need to do this? Or what is a syntax that gets me close to the same result?

**Comment by rarkins** [comment]
We're pretty dependent on the `latest` library for this. Apart from what's in the tests in https://github.com/renovatebot/renovate/blob/master/test/workers/branch/schedule.spec.js, I haven't really touched it.

As an aside, is this something you can express in a cron definition?

**Comment by jzempel** [comment]
@rarkins thanks for the test links – I'll have a look and see if there are valid schedule phrases that might shed some light on what I'm trying to do.

**Comment by jzempel** [comment]
btw, I think I found valid syntax that works the way I want it to, allowing me to spread out schedules like this:
- `on Wednesday every 4 weeks of the year starting on the 2nd week`
- `on Thursday every 4 weeks of the year starting on the 3rd week`
- `on Friday every 4 weeks of the year starting on the 4th week`
