### ISSUE TITLE
renovate.json empty

### ISSUE THREAD

**Issue by mcourant** [renovatebot/config-help#364]
### Which Renovate are you using? CLI, App, or Pro
Self-hosted in gitlab-ci.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Gitlab

### Have you checked the logs? Don't forget to include them if relevant
Repository config (repository=xxxxx)
       "configFile": "renovate.json",
       "config": {}

### What is your question?
Why when i accept the MR, i can't see any change in my repo. Renovate.json is empty.
How i can solve it ? 

Thanks a lot.

**Comment by rarkins** [comment]
`onboardingConfig`
