### ISSUE TITLE
[Question] docs.renovatebot.com/configuration-options is inaccessible

### ISSUE THREAD

**Issue by kjin** [renovatebot/config-help#365]
### Which Renovate are you using? CLI, App, or Pro
N/A

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
N/A

### Have you checked the logs? Don't forget to include them if relevant
N/A

### What is your question?
I got ERR_TOO_MANY_REDIRECTS when navigating to https://docs.renovatebot.com/configuration-options. I've tried multiple browsers and devices so I think it might be a server problem.

**Comment by JamieMagee** [comment]
Do you have cURL installed? Can you run this command and paste the output? `curl -s -L -D - https://docs.renovatebot.com/configuration-options -o /dev/null -w '%{url_effective}'`

It will follow the redirects, and print out each step. This is what I get:

```sh
$ curl -s -L -D - https://docs.renovatebot.com/configuration-options -o /dev/null -w '%{url_effective}'
HTTP/2 301 
cache-control: public, max-age=0, must-revalidate
content-type: text/html; charset=UTF-8
date: Tue, 24 Sep 2019 20:26:53 GMT
etag: "9b261cd452f1612ce4e050a186531866-ssl"
strict-transport-security: max-age=31536000
age: 0
server: Netlify
x-nf-request-id: 409e554d-d6ed-4c7a-be3b-23af895cc8ae-888641
location: /configuration-options/

HTTP/2 200 
cache-control: public, max-age=0, must-revalidate
content-type: text/html; charset=UTF-8
date: Tue, 24 Sep 2019 20:26:54 GMT
etag: "9b261cd452f1612ce4e050a186531866-ssl"
strict-transport-security: max-age=31536000
age: 1
server: Netlify
x-nf-request-id: 409e554d-d6ed-4c7a-be3b-23af895cc8ae-889168

https://docs.renovatebot.com/configuration-options/
```

**Comment by kjin** [comment]
Oh, it works now. Thanks!

For the record, I get similar results when running that command.
