### ISSUE TITLE
[Question] Python managers

### ISSUE THREAD

**Issue by djmitche** [renovatebot/config-help#367]
### Which Renovate are you using? CLI, App, or Pro

App (forking)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: Matched 1 file(s) for manager pip_requirements: requirements.txt
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup
DEBUG: Matched 1 file(s) for manager pip_setup: setup.py
```
```
DEBUG: packageFiles with updates
{
  "config": {
    "pip_setup": [
...
    ]
  }
}
```

### What is your question?

I have a pretty simple Python lib with a `setup.py` and a `requirements.txt`, using `pip-tools` to keep them in sync (so `setup.py` specifies a range, and `requirements.txt` pins things for consistency in CI).  I just have the base config.

In the logs, I see it detect both of these, but it only seems to load `pip_setup`.  A few questions then:

1. https://docs.renovatebot.com/python/ suggests that `setup.py` support is in beta, yet it seems to be running by default.
1. the same docs suggest that pip is the default Python engine, yet it seems not to find anything.

The result is that Renovate makes PRs like https://github.com/taskcluster/tc-admin/pull/16, in which it bumped `pytest<4` to `pytest<6` but didn't touch `requirements.txt` meaning that nothing actually changed.

I understand that Python packaging is kind of a disaster zone, so maybe this won't ever work smoothly, but I'd like to at least understand what's going on.  What am I missing?

**Comment by rarkins** [comment]
Unfortunately it's because of our lack of hashes support in `requirements.txt`. Feature request to track is here: https://github.com/renovatebot/renovate/issues/2444

**Comment by djmitche** [comment]
Got it, thanks!
