### ISSUE TITLE
[Question] Allow only path updates for dockerfile

### ISSUE THREAD

**Issue by NoUseFreak** [renovatebot/config-help#368]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket

### Have you checked the logs? Don't forget to include them if relevant
Yes

### What is your question?
I have a repo with multiple docker images. We use them as base images for our apps. 
Because we maintain multiple versions (different minor versions) in this repo, I want to make sure renovate only updates the patch version.

I've tried the following, but it seems to keep suggesting multiple images.

```
{
  "extends": [
    "github>sparkcentral/renovate-config"
  ],
  "packageRules": [
    {
      "managers": ["dockerfile"],
      "updateTypes": ["patch"]
    }
  ]
}
```

Any suggestions on how to resolve this?

**Comment by NoUseFreak** [comment]
As an example, it's currently suggesting the following:

Package | Type | Update | Change
-- | -- | -- | --
php | final | patch | 7.3.9-fpm -> 7.3.10-fpm
php | final | minor | 7.0.33-fpm -> 7.3.10-fpm

I want to make sure it does not suggest `7.0.33-fpm -> 7.3.10-fpm`

**Comment by rarkins** [comment]
`updateTypes` is a selector, not an instruction. i.e. it tells Renovate to match the rule against patches, not that it should limit itself to only patches.

You need to do this:
1. Tell Renovate to generate separate updates for patch and minor updates (this is not default behaviour)
2. Disable all updates except patch

```
  "packageRules": [{
	"managers": ["dockerfile"],
    "separateMinorPatch": true
  },{
    "managers": ["dockerfile"],
    "updateTypes": ["minor", "major"],
    "enabled": false
  }]
```

**Comment by NoUseFreak** [comment]
Thanks so much for the quick response!
