### ISSUE TITLE
[Question] Not working on Gitlab

### ISSUE THREAD

**Issue by PolGuixe** [renovatebot/config-help#369]
### Which Renovate are you using? CLI, App, or Pro
Renovate Bot user in Gitlab

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Gitlab

### Have you checked the logs? Don't forget to include them if relevant
I can't access them. Job #99049002 it displays an `error` tag.

### What is your question?

I configured the renovate bot on one of our repositories in Gitlab. However, it hasn't created any Merge Request yet. The `renovate.json`  config file has been merged to `master`. However, the target branch os to `develop`. Is this an issue?

**Comment by rarkins** [comment]
How did you “install”? Eg is Renovate a developer you added to the project manually?

**Comment by PolGuixe** [comment]
@rarkins yes I added it as a developer and it generated an initial MR with the config file.

**Comment by PolGuixe** [comment]
Now the bot has turned off. Says configuration missing. 

Still can't access the logs.

**Comment by rarkins** [comment]
You need a `renovate.json` in your default branch. If your default branch is `developer`, then that's where the `renovate.json` should be. Last time Renovate ran it found no config in `develop` so disabled the repository. Disabled repositories are only checked ~weekly.

**Comment by PolGuixe** [comment]
@rarkins I have merged the `renovate.json` config branch into `develop` as well. Then I have to wait 1 week approx for the bot to check it again? 
Is there a way to trigger it before? Otherwise no worries.

**Comment by rarkins** [comment]
I've updated the repository in our DB manually so it should be picked up within the next 1-3 hours maximum. Please let me know if not

**Comment by PolGuixe** [comment]
@rarkins it has been working since then! Thanks!
