### ISSUE TITLE
"automergeType": "branch-push" in circleci

### ISSUE THREAD

**Issue by teppeis** [renovatebot/config-help#37]
I specified `"automerge": true` and `"automergeType": "branch-push"` but a PR was created. Why?
- renovate.json: https://github.com/teppeis-sandbox/renovate-circleci-test-4/blob/e7f6d07d4104dbd207e650049668bccb1c5d774e/renovate.json
- created PR: https://github.com/teppeis-sandbox/renovate-circleci-test-4/pull/2

Previously, in another repo that has same renovate.json, automergeType worked well without creating PR.
- https://github.com/teppeis-sandbox/renovate-circleci-test-3/blob/master/renovate.json
- https://github.com/teppeis-sandbox/renovate-circleci-test-3/pulls?utf8=%E2%9C%93&q=is%3Apr
- https://github.com/teppeis-sandbox/renovate-circleci-test-3/commits/master

**Comment by rarkins** [comment]
Usually it’s because of a failed status check reported by GitHub. If you go to renovatebot.com/dashboard, locate the repository and the job that finished around the exact time the PR was created. You’ll probably be able to see which status check failed in that log.

**Comment by teppeis** [comment]
@rarkins Thanks! CI has not been set up in the repo, sorry.

Finally, I found the dashboard! Amazing!
I can debug my repo without creating these issues. Thank you!
