### ISSUE TITLE
[Question] reviewers based on change

### ISSUE THREAD

**Issue by NoUseFreak** [renovatebot/config-help#370]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket cloud

### Have you checked the logs? Don't forget to include them if relevant
Not relevant

### What is your question?
Hi,

I was wondering if it's possible to have reviewers set for a project and for example different in case a docker image gets updated?

**Comment by rarkins** [comment]
Yes, you can configure reviewers just like any other option - e.g based on path or language or package manager. Example:

```
  "dockerfile": {
    "reviewers": ["karen"]
  }
```

**Comment by NoUseFreak** [comment]
Thanks so much! I've been having some issues interpreting the documentation, although thorough, the possible combinations may need some examples. I may create a PR with some examples at some point.
