### ISSUE TITLE
[Question] scheduling syntax/testing

### ISSUE THREAD

**Issue by zoywongus** [renovatebot/config-help#371]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
I am wondering if there is syntax I can use to check for updates for a package every 3 months. I read some previous issues and looked up the `later` library.

I think the syntax based off of that library is `on the first day of the month every 3 month`, but I am wondering does renovatebot support this syntax, since according to the docs, it supports 'only its concepts of "days", "time_before", and "time_after"'

Cannot find anything online to confirm that the every 3 month syntax I plan to use is correct. And I guess the best way to test if all this works?

**Comment by zoywongus** [comment]
The config we have right now is:
```{
  "description": "config for renovate-bot",
  "extends": ["config:base", ":pinAllExceptPeerDependencies"],
  "prConcurrentLimit": 4,
  "masterIssue": true,

  "labels": ["dependencies"],
  "vulnerabilityAlerts": {
    "labels": ["dependencies", "vulnerability"]
  },
  "packageRules": [
    {
      "packageNames": ["@types/node", "lerna"],
      "groupName": "Update Node/Lerna",
      "schedule": ["on the first day of the month every 3 month"]
    },
    {
      "packagePatterns": ["^@?babel(/|-)"],
      "groupName": "Update Babel packages",
      "schedule": ["on the first day of the month every 3 month"]
    }
  ] 
}```

**Comment by rarkins** [comment]
Sorry, right now our use of `later` extends only to monthly, so 3 month schedules is not possible.
