### ISSUE TITLE
Renovate seems to have stopped working

### ISSUE THREAD

**Issue by Lughino** [renovatebot/config-help#372]
**What Renovate type are you using?**
Hosted app in open-source project

**Describe the bug**
It seems it has stopped working. Until 18 days ago everything was working properly, now I noticed that I have a lot of devDependencies out of sync.
e.g.:
```json
{
            "depType": "devDependencies",
            "depName": "@typescript-eslint/eslint-plugin",
            "currentValue": "^2.0.0",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "2.0.0",
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/typescript-eslint/typescript-eslint",
            "sourceDirectory": "packages/eslint-plugin"
          },
          {
            "depType": "devDependencies",
            "depName": "@typescript-eslint/parser",
            "currentValue": "^2.0.0",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "2.0.0",
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/typescript-eslint/typescript-eslint",
            "sourceDirectory": "packages/parser"
          },
```

**Did you see anything helpful in debug logs?**
I've checked the logs, the service seems to check with the same frequency as before but it's not catching anymore new dependencies

**Expected behavior**
Raise a PR with a new dep bump

**Comment by rarkins** [comment]
In your first example, your current value is `^2.0.0`. Latest version is `2.3.2` which is in range, which means no update is required.

Check out [rangeStrategy](https://docs.renovatebot.com/configuration-options/#rangestrategy) for more options.

- If you want to be bumped to `^2.3.2` (which is probably a bad idea and you shouldn't be using ranges) then you want rangeStrategy=bump
- If you want to remain at `^2.0.0` and have the lock file version increased, you want rangeStrategy=update-lockfile
