### ISSUE TITLE
[Question] how to pin a specific library

### ISSUE THREAD

**Issue by hiroppy** [renovatebot/config-help#373]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

no

### What is your question?

issue: https://github.com/webpack/webpack-dev-server/pull/2252#discussion_r330144492

We want to prevent to update some libraries but I don't know how to change our config. 

Thanks.

**Comment by rarkins** [comment]
You could maybe just tell Renovate to ignore this library?

```json
  "ignoreDeps": ["http-proxy-middleware"]
```

**Comment by hiroppy** [comment]
Oops, thanks. I'll try it.
