### ISSUE TITLE
[Question] What are the available managers?

### ISSUE THREAD

**Issue by djmitche** [renovatebot/config-help#376]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GtHub

### What is your question?

I see that `enabledManagers` can be used to disable managers by omitting them from the list.  But I added ["node"](https://github.com/taskcluster/taskcluster/blob/d0049791c4687a7c888949af6b94baa7cdc2378a/package.json#L196) to that list and it seems to have [closed](https://github.com/taskcluster/taskcluster/pull/1435#event-2689305011) all of my open renovate PRs.

I don't see a list of managers anywhere in the docs, so I'm not sure what I should enable.

**Comment by rarkins** [comment]
Sorry, we need to document this better. Please use this list: https://github.com/renovatebot/renovate/blob/24a9e290fdc5da476b3d22652fa111a52f308b63/lib/manager/index.ts#L12-L49
