### ISSUE TITLE
[Question] angular / conventional commits for onboarding PR

### ISSUE THREAD

**Issue by wyardley** [renovatebot/config-help#377]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
Sorry in advance if this is documented somewhere, but is there a way to configure the onboarding PR to use angular / conventional commit format for the onboarding PR? Or to hardcode the title / commit message at installation level, or have it use the current “guessing” strategy for the onboarding PR itself?

**Comment by rarkins** [comment]
Sorry, it's currently not possible. Checking for a past onboarding PR is one of the first things that Renovate does, and it looks directly for "Configure Renovate". Happy to accept a feature request to the main repo for it though, but we will need to think through if there's any unintended consequences.

**Comment by wyardley** [comment]
Also, I realized that GH uses the commit message when squash merging a PR with only one commit, so probably it works fine as-is.
