### ISSUE TITLE
@fortawesome group

### ISSUE THREAD

**Issue by jfairley** [renovatebot/config-help#38]
I'd like to configure my repos to update `@fortawesome` dependencies in bulk, but I'm not 100% sure that I understand the config options. 

Is this correct?

```
"packageRules": [
  {
    "groupName": "fortawesome",
    "packagePatterns": [
      "^@fortawesome/"
    ]
  }
]
```

My dependencies are:

```
"@fortawesome/angular-fontawesome": "0.1.0-7",
"@fortawesome/fontawesome-free-brands": "5.0.10",
"@fortawesome/fontawesome-pro-light": "5.0.10",
"@fortawesome/fontawesome-pro-regular": "5.0.10",
"@fortawesome/fontawesome-pro-solid": "5.0.10",
"@fortawesome/fontawesome-svg-core": "1.2.0-11",
```

Thanks!

**Comment by rarkins** [comment]
Yes, that should work fine

**Comment by jfairley** [comment]
Great!

One more question: if I currently have open PRs for font-awesome upgrades, should I just close them, and renovate will reopen a new PR.

**Comment by rarkins** [comment]
Renovate will autoclose them and delete the branches, so leave them as is for maximum convenience

**Comment by jfairley** [comment]
This config worked great!
