### ISSUE TITLE
[Question] Monorepo workflow: Pull request per package.json

### ISSUE THREAD

**Issue by maciej-gurban** [renovatebot/config-help#380]
### Which Renovate are you using? CLI, App, or Pro
Using self-hosted version

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
In a project with multiple package.json files, is there a way to create separate Pull Request for each package.json in that repository? Perhaps through something to the style of Github code owners file?

My use case:
In a code repository, different teams own different pieces of the codebase, i.e. Team Foo owns whatever is in `src/foo` directory, but not what's in `src/bar` which belongs to Team Bar. If both of these directories contain a `package.json`, Renovate will create a single pull request which will attempt to update dependencies in both files at the same time. However, neither Team Foo nor Team Bar does not wants to update each others dependencies - because they might not have time to test these changes, work in a different geo, because they deploy their code separately etc.

**Comment by rarkins** [comment]
Do you want a single PR ("Update all dependencies") per package.json? Or separate PRs (one for eslint, one for react, etc) per package.json? Also, how many separate package.json/teams do you have?

**Comment by maciej-gurban** [comment]
I'm after having a separate PR for each dependency (or dependency group more likely) per package.json.

Long term I'm expecting 10-15 package.json files and 10 or so teams. I'm hoping that with correct scheduling and labelling the PR list wouldn't get too tedious to manage. Each package.json (except for one) will only include dependencies, and no dev dependencies.

**Comment by rarkins** [comment]
In that case, please take a look at https://github.com/renovatebot/config-help/issues/359 and see if you can work out a config that works for you. If not, please post your progress back here and I'll take a look.

Because you don't want to group all updates per package manager, you will want to use something like this:

```
    {
      "paths": ["packages/foo/*"],
      "branchPrefix": "renovate/foo-",
      "commitMessageSuffix": "(foo)",
      "assignees": ["foo-member"] // or let code owners do its job automatically?
    }
```
