### ISSUE TITLE
Helm requirements.yaml updater - option to specify credentials

### ISSUE THREAD

**Issue by Morishiri** [renovatebot/config-help#384]
**What would you like Renovate to be able to do?**
I'm very happy now that https://github.com/renovatebot/renovate/pull/3805 is implemented and seems to work! Problem is that when you're using private (auth protected) repository, there is no way to specify the credentials. I would love to see that feature, becuase our internal company helm repo is protected and currently cannot be used with renovate..

**Describe the solution you'd like**
Be able to provide credentials to chart repository in renovate config/env variables.

**Describe alternatives you've considered**
Whitelisting renovate runner IP addresses, but that's not exactly what we implemented auth for.

**Additional context**
N/A

**Comment by rarkins** [comment]
Can you try this?

```
  "hostRules": [{
    "hostName": "your.helm.repo",
    "username": "hello",
    "password": "world"
  }]
```

I'm assuming you are self-hosted. This config could be put either in the `renovate.json` of the repository itself, if you don't mind exposing the password, or you could configure it in a `config.js` on the bot "server side" so that it's exposed only to the Renovate admin.

**Comment by Morishiri** [comment]
It seem to work! I was not aware of generic mechanism in this place. Thank you for your help!
