### ISSUE TITLE
how to disable renovate/pin-dependencies

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#387]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I started playing with renovate CLI and the on boarding PR indicates branch renovate/pin-dependencies will be created and it will try to pin all my top level dependencies, even when my package.json uses ranges.  Is that something that can be disabled so, that I get PR's for new versions detected but not pinning the dependencies?

thanks

**Comment by rarkins** [comment]
Yes, set [rangeStrategy](https://docs.renovatebot.com/configuration-options/#rangestrategy) to `replace` or `update-lockfile`.

I recommend you read https://docs.renovatebot.com/dependency-pinning/ though.

**Comment by rvillane** [comment]
thanks, I read the link you provided, but there are no pointers to the rangeStrategy setting, thanks for the help

**Comment by insidewhy** [comment]
@rarkins I added this file to the root of my git repo:

```
% cat .renovaterc.json 
{
  "rangeStrategy": "replace"
}
```

Then a minute later I got a PR from renovate bot that tried to pin all dev dependencies again.

**Comment by 00imvj00** [comment]
@insidewhy you can use `:preserveSemverRanges` preset. just add this in `extends` array.

**Comment by rarkins** [comment]
@insidewhy if you'd like us to look into it, please replicate in a public repo that we can test against, and please create a new issue instead of adding to old ones
