### ISSUE TITLE
renovate rejecting personal access token

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#388]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
renovate is failing with this error:

```
FATAL: You must configure a GitHub personal access token
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "msg": "You must configure a GitHub personal access token"
         }
       ]
```

it ran fine a first time using the token from my config.js, but now when I try to run it a second time is complaining about the personal access token.

any ideas ?

**Comment by rvillane** [comment]
in case it helps, I deleted the initial PR created in my first execution and deleted the branch as I just experimenting with settings.

**Comment by rarkins** [comment]
Run with LOG_LEVEL=debug and check what it tells you about config, config.js, etc.

**Comment by rvillane** [comment]
I added the following on my config.js

  logFileLevel: 'debug',
  logLevel: 'debug',

and set env var LOG_LEVEL=debug but don't see any extra, either at the console or at the log file (which is empty)

**Comment by rarkins** [comment]
If the problem is Renovate not detecting your config.js then adding extra config to it won't help, so stop that approach. LOG_LEVEL=debug must be added to env before you run Renovate, and after that you should see `DEBUG:` log messages. Please paste your entire log including the command you run into here so I can take a look.

**Comment by rvillane** [comment]
command:

```
RENOVATE_CONFIG_FILE="/Users/crmar/Documents/renovate/renovate-config.js"
LOG_LEVEL=debug

echo $RENOVATE_CONFIG_FILE
renovate  --print-config true
```

log output :
```
/Users/crmar/Documents/renovate/renovate-config.js
FATAL: You must configure a GitHub personal access token
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "msg": "You must configure a GitHub personal access token"
         }
       ]
```

**Comment by rarkins** [comment]
That doesn’t look like you’re exporting env correctly. Put it all in the one command if in doubt (renovate comes last)

**Comment by rarkins** [comment]
No multiple lines, no echo’ing, etc. just a single line command including all the env you need

**Comment by rvillane** [comment]
found the problem, I added an extra element on my config.js but forgot to add the comma, the syntax error caused renovate to ignore my invalid config file.

thanks for your help.
