### ISSUE TITLE
excluding a subset of devDependencies

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#389]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I have the following configuration where I'm trying to exclude some packages under devDependencies:

```
  enabledManagers: ['npm'],
  rangeStrategy: 'pin',
  separateMajorMinor: false,
  stabilityDays: 7,
  prCreation:'not-pending',
  packageRules: [{
      baseBranchList: ['master'],
      depTypeList: ['dependencies'],
      enabled: true
  },{
      baseBranchList: ['master'],
      depTypeList: ['devDependencies'],
      packagePatterns: ['*'],
      excludePackagePatterns: ['^eslint','^es6-plato','^minimatch','^tap-colorize'],
      enabled: true
  }]
```

and the following dependencies on package.json:

```
  "dependencies": {
    "@google-cloud/trace-agent": "4.2.1",
    "big.js": "^5.2.2",
    "@hapi/hapi": "^18.4.0",
    "@hapi/joi": "^15.1.1",
    "jwt-lib-node": "1.4.0",
    "moment": "^2.24.0",
    "mongoose": "5.7.1",
    "request-promise": "^4.2.4",
    "uuid": "^3.3.3",
    "xml2js": "^0.4.22"
  },
  "devDependencies": {
    "coverify": "^1.5.0",
    "es6-plato": "^1.0.16",
    "eslint": "^5.4.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.7.0",
    "minimatch": "^3.0.4",
    "mongodb": "^3.3.2",
    "mongodb-memory-server": "^5.2.3",
    "nyc": "^13.0.1",
    "proxyquire": "^2.0.1",
    "tap-colorize": "^1.2.0",
    "tape": "^4.9.0"
  }
```

However, the onboarding PR is indicating the following changes:

```
What to Expect
With your current configuration, Renovate will create 7 Pull Requests:

Pin dependencies
Branch name: renovate/pin-dependencies
Merge into: master
Pin @google-cloud/trace-agent to 3.6.1. <====== downgrading from 4.2.1 to 3.6.1
Pin @hapi/hapi to 18.4.0
Pin coverify to 1.5.1
Pin es6-plato to 1.2.3
Pin eslint to 4.19.1. <===== downgrading from 5.4.0 to 4.19.1
Pin eslint-config-airbnb to 15.1.0
Pin eslint-plugin-import to 2.18.2
Pin eslint-plugin-jsx-a11y to 5.1.1
Pin eslint-plugin-react to 7.16.0
Pin jwt-lib-node to 1.4.0
Pin minimatch to 3.0.4
Pin mongodb to 3.3.3
Pin mongodb-memory-server to 5.2.8
Pin nyc to 11.9.0
Pin proxyquire to 2.1.3
Pin request-promise to 4.2.4
Pin tap-colorize to 1.2.0
Pin tape to 4.11.0
Pin tv4 to 1.3.0
Pin tv4-formats to 3.0.3
Update dependency mongoose to v5.7.5
Update dependency @google-cloud/trace-agent to v4
Update dependency eslint to v6
Update dependency eslint-config-airbnb to v18
Update dependency eslint-plugin-jsx-a11y to v6
Update dependency nyc to v14
```

Can you help me understand why the pin-dependencies branch is in some cases downgrading versions ?  And also why the packages I'm trying to exclude under devDependencies are getting updated to the latest version?

thanks

**Comment by rarkins** [comment]
Packages are enabled by default. You should be disabling them with a package rule rather than selectively enabling. Ie switch your includes / excludes logic and then enabled: false.

**Comment by rvillane** [comment]
I tried multiple combinations to exclude the subset of devDependencies but couldn't get the expected results.  Using "ignoreDeps" is providing much better results.

config:
```
  onboarding: true,
  onboardingConfig: {
    extends: ['config:base'],
  },
  automerge: false,
  enabledManagers: ['npm'],
  rangeStrategy: 'pin',
  reviewers: ['crmar@llbean.com'],
  separateMajorMinor: false,
  stabilityDays: 7,
  prCreation:'not-pending',
  ignoreDeps: ['eslint','coverify', 'eslint-config-airbnb', 'eslint-plugin-import', 'eslint-plugin-jsx-a11y', 'eslint-plugin-react','es6-plato','minimatch','tap-colorize'],
  packageRules: [{
      baseBranchList: ['master'],
      depTypeList: ['dependencies','devDependencies']
  }]
```

results:

What to Expect
With your current configuration, Renovate will create 4 Pull Requests:

- Pin dependencies
Branch name: renovate/pin-dependencies
Merge into: master
Pin @google-cloud/trace-agent to 3.6.1
Pin @hapi/hapi to 18.4.0
Pin mongodb to 3.3.3
Pin mongodb-memory-server to 5.2.8
Pin nyc to 11.9.0
Pin proxyquire to 2.1.3
Pin request-promise to 4.2.4
Pin tape to 4.11.0
Pin tv4 to 1.3.0
Pin tv4-formats to 3.0.3

- Update dependency mongoose to v5.7.5
- Update dependency @google-cloud/trace-agent to v4
- Update dependency nyc to v14

Pinning is updating package.json to the latest minor.patch version and then every major updates comes in separate PR's and I don't see any downgrades as in the previous setup.

Is it possible to have just one PR with all changes included?  I added "separateMajorMinor: false" with no luck.

**Comment by rarkins** [comment]
Look at group:allNonMajor in https://docs.renovatebot.com/presets-group/

**Comment by rvillane** [comment]
Ok, I removed separateMajorMinor field and added groupName:'All' with the intention to have a single PR with all the changes:

```
  automerge: false,
  enabledManagers: ['npm'],
  rangeStrategy: 'pin',
  reviewers: ['crmar@llbean.com'],
  stabilityDays: 7,
  prCreation:'not-pending',
  groupName:'All',
  labels: [
    'renovate'
  ],
  ignoreDeps: ['eslint','coverify','eslint-plugin-security','eslint-plugin-node','eslint-config-airbnb', 'eslint-plugin-import','eslint-plugin-promise', 'eslint-plugin-jsx-a11y', 'eslint-plugin-react','es6-plato','minimatch','tap-colorize'],
  packageRules: [{
      baseBranchList: ['master'],
      depTypeList: ['dependencies','devDependencies']
  }]
```

however, this setup is going to generate 3 PR's:

Pin dependencies
- Branch name: renovate/pin-dependencies
- Merge into: master
- Pin @google-cloud/trace-agent to 3.6.1
- Pin @hapi/hapi to 18.4.0
- Pin jwt-lib-node to 1.4.0
- Pin llb-ocs-logger to 1.4.0
- Pin llb-ocs-utilities to 2.1.0
- Pin mongodb to 3.3.3
- Pin mongodb-memory-server to 5.2.8
- Pin nyc to 11.9.0
- Pin proxyquire to 2.1.3
- Pin request-promise to 4.2.4
- Pin tape to 4.11.0
- Pin tv4 to 1.3.0
- Pin tv4-formats to 3.0.3

Update dependency mongoose to v5.7.5
- Branch name: renovate/all
- Merge into: master
- Upgrade mongoose to 5.7.5

Update All (major)
- Branch name: renovate/major-all
- Merge into: master
- Upgrade @google-cloud/trace-agent to 4.2.2
- Upgrade nyc to 14.1.1

I'm particularly scratching my head why a separate PR for mongoose since current version is 5.7.1  and this new PR is just to upgrade to 5.7.5.

**Comment by rarkins** [comment]
Check out the branch names. You see one is `renovate/all` and the other is `renovate/major-all`. I *really* recommend you don't group all updates including major ones into the same PR, because you're guaranteed to have breaking changes in most PRs, which will hold you back from being able to merge safe patches and minor updates. I recommend at most that you group together all minor/patch but then have one PR per major update, so that you can check and address breaking changes one by one.

**Comment by rvillane** [comment]
Ok, your recommendation about keeping major dependencies as separate PR's makes a lot of sense. To align with this advice I changed groupName from 'all' to 'allNonMajor', however, I'm getting very similar results, with just different branch names:

What to Expect
With your current configuration, Renovate will create 3 Pull Requests:

Pin dependencies
- Branch name: renovate/pin-dependencies
- Merge into: master
- Pin @google-cloud/trace-agent to 3.6.1
- Pin @hapi/hapi to 18.4.0
- Pin jwt-lib-node to 1.4.0
- Pin llb-ocs-logger to 1.4.0
- Pin llb-ocs-utilities to 2.1.0
- Pin mongodb to 3.3.3
- Pin mongodb-memory-server to 5.2.8
- Pin nyc to 11.9.0
- Pin proxyquire to 2.1.3
- Pin request-promise to 4.2.4
- Pin tape to 4.11.0
- Pin tv4 to 1.3.0
- Pin tv4-formats to 3.0.3

Update dependency mongoose to v5.7.5
Branch name: renovate/allnonmajor
Merge into: master
- Upgrade mongoose to 5.7.5

Update allNonMajor (major)
Branch name: renovate/major-allnonmajor
Merge into: master
- Upgrade @google-cloud/trace-agent to 4.2.2
- Upgrade nyc to 14.1.1

The behavior I'm observing is this:

1. one PR grouping all major changes - this is expected
2. one PR to update and pin dependencies to the latest minor-patch version, this is expected
3. a separate PR to update mongoose from 5.7.1 to 5.7.5 , this is not expected.

**Comment by rarkins** [comment]
The name is purely cosmetic, so changing itwon't change Renovate's behaviour. You need something like this:

```
  extends: ['group:allNonMajor'],
  enabledManagers: ['npm'],
  rangeStrategy: 'pin',
  reviewers: ['crmar@llbean.com'],
  stabilityDays: 7,
  prCreation:'not-pending',
  labels: [
    'renovate'
  ],
  ignoreDeps: ['eslint','coverify','eslint-plugin-security','eslint-plugin-node','eslint-config-airbnb', 'eslint-plugin-import','eslint-plugin-promise', 'eslint-plugin-jsx-a11y', 'eslint-plugin-react','es6-plato','minimatch','tap-colorize']
```

Note I removed groupName and replaced it with a preset that already does what you want. Also I removed the packageRule because it achieves nothing as-is.

**Comment by rvillane** [comment]
Ok, I tried that exact setup and that is helping to understand the special treatment for mongoose.  Mongoose is already pinned on the current package.json, then I'm guessing is not included as part of the renovate/pin-dependencies branch, then the update to the latest minor-patch version is completed in the renovate/all-minor-patch branch instead.

Update dependency mongoose to v5.7.5
Branch name: renovate/all-minor-patch
Merge into: master
Upgrade mongoose to 5.7.5

**Comment by rvillane** [comment]
@rarkins , thanks a lot for your patience and help, I'm all set with my configuration.

**Comment by rarkins** [comment]
You're welcome, good luck!
