### ISSUE TITLE
renovate-config preset published to private npm repository

### ISSUE THREAD

**Issue by jfairley** [renovatebot/config-help#39]
I attempted to build a shareable configuration tonight, but when I referenced it in a repo, I got the following error:

> There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.
> 
> Error type: Cannot find preset's package (@levelsbeyond)

After following the [documentation](https://renovatebot.com/docs/config-presets/), my `package.json` for `@levelsbeyond/renovate-config` looks like:

```json
  "name": "@levelsbeyond/renovate-config",
  "renovate-config": {
    "default": {
      "extends": [
        "config:base",
        "schedule:nonOfficeHours"
      ],
      "packageRules": [
        {
          "groupName": "fortawesome",
          "packagePatterns": [
            "^@fortawesome/"
          ]
        },
        {
          "groupName": "levelsbeyond",
          "packagePatterns": [
            "^@levelsbeyond/"
          ]
        },
        {
          "groupName": "typescript",
          "packageNames": [
            "tslint",
            "typescript"
          ]
        },
        {
          "groupName": "webpack",
          "packagePatterns": [
            "webpack",
            "-loader$"
          ]
        }
      ],
      "rebaseStalePrs": true,
      "timezone": "America/Denver"
    }
  },
  ...
```

I am attempting to reference this configuration like:

```json
{
  "extends": [
    "@levelsbeyond"
  ],
  "npmrc": "<redacted>"
}
```

I know my `"npmrc"` value is good. I cannot spot any errors in my configuration.

- Can a shareable configuration be pulled from a private NPM?
- Can you spot any syntactical errors in my JSON?
- Can you think of anything I should try?

Thanks!

**Comment by rarkins** [comment]
This might be a tricky edge case. Is the `npmrc` encrypted, or raw/unencrypted?

**Comment by jfairley** [comment]
raw/unencrypted

**Comment by rarkins** [comment]
Ok I’ll see if I can fix it on the server side

**Comment by rarkins** [comment]
I made a server-side change to set the `.npmrc` after decryption but before preset resolution and now get a 401 error from an Artifactory server.

Are you attempting to store the preset on that Artifactory server, or on npmjs? I only planned for using the npmjs namespace.

**Comment by jfairley** [comment]
`_authToken` doesn't work. That is what private NPM wants, but Artifactory wants `_auth` and `email`. I've tried a bunch of different combinations of values in my `.npmrc` since the jfrog documentation isn't the clearest. This with these key/value configuration is the only setup that I've seen work.

https://www.jfrog.com/confluence/display/RTF/Npm+Registry

Towards the end of that documentation, they also reference a Basic Auth configuration using "username" and "_password", but I actually wasn't able to get that working either.

**Comment by rarkins** [comment]
Sounds like Renovate needs to massage `_auth` to `_authToken` to see if that works. Otherwise the npm library we're using to extract auth from the `.npmrc` is not returning anything in your case.

**Comment by rarkins** [comment]
.. AND it seems like we need to use `Basic` and not `Bearer`.

**Comment by jfairley** [comment]
The issue created on my repo autoclosed. Does that mean it's working?

I'm not sure what I can do to "force" an action short of changing my "schedule" and hoping there currently a new version of something out in the world. 😛 Any suggestions?

**Comment by jfairley** [comment]
Oh, 2 hours ago, in addition to the autoclosed issue, my open PRs were rebased on passed CI. So maybe things _are_ working. I'll keep an eye out for a new dependency update coming in.

**Comment by jfairley** [comment]
Ok, definitely working! I merged one and 3 others rebased themselves.

![](https://media.giphy.com/media/a0Lgc1JvbfS4o/giphy.gif)

**Comment by rarkins** [comment]
Thanks for your help too! I'm sure you won't be the only one stuck with `_auth=` tokens so it's good to get that use case supported

**Comment by ianwalter** [comment]
@rarkins We're having the same issue with @binxhealth except we're using GitHub Package Registry instead of Artifactory.

**Comment by rarkins** [comment]
@ianwalter 	can you create a new issue in the main renovate repo, e.g. "GitHub Package Registry support"? I haven't been granted access to it yet so haven't been able to test.
