### ISSUE TITLE
Change separateMinorPatch for combined node PRs

### ISSUE THREAD

**Issue by SpainTrain** [renovatebot/config-help#391]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What is your question?

The default config causes renovate to open a PR at the minor version level which includes package.json engines, docker (via circleci), and @types.  How does one update the default such that `separateMinorPatch` is `true` for this package group?  I cannot seem to find this group in the presets.

Thanks!!

**Comment by rarkins** [comment]
I think in this case the best approach is to try a packageRule catching all the node ones you have. Hopefully something like this:

```json
  "packageRules": [{
    "packageNames": ["node"],
    "packagePatterns": [".*/node"],
    "separateMinorPatch": true
  }]
```

I'm not 100% certain on that pattern though. I forget if it needs a `\` before the `/` or not.
