### ISSUE TITLE
Closed P.R.  re-spawns

### ISSUE THREAD

**Issue by kvor** [renovatebot/config-help#392]
### Which Renovate are you using? CLI, App, or Pro
Renovate App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant
Build 105777450

[node13.txt](https://github.com/renovatebot/config-help/files/3754399/node13.txt)

### What is your question?
We close a PR. However same PR reopens even there is no update.

**Comment by rarkins** [comment]
Need more information. Please provide description and screenshots

**Comment by kvor** [comment]
PR closed 4 hours ago:
![Screenshot 2019-10-22 at 10 41 19](https://user-images.githubusercontent.com/5127910/67270267-9ad01a00-f4b8-11e9-9a9d-320bc8e42bf6.png)
PR re-opened
![Screenshot 2019-10-22 at 10 41 31](https://user-images.githubusercontent.com/5127910/67270278-a15e9180-f4b8-11e9-99b4-17ec832acc7b.png)

PR info:
![Screenshot 2019-10-22 at 10 42 37](https://user-images.githubusercontent.com/5127910/67270316-b76c5200-f4b8-11e9-9be5-ae1e5a9b0016.png)

**Comment by rarkins** [comment]
The PR titles are different, so they are treated as different PRs. One uses regular commits and the second uses angular conventional commits. If you are using inconsistent commit formats within a project then Renovate can't autodetect which you're using and may flip back and forth.

Set [semantiCommits](https://docs.renovatebot.com/configuration-options/#semanticcommits) to true or false in your config to fix which commit style you want.

**Comment by kvor** [comment]
Those PRs are not coming from us (it should be from Travis). 

Setting semantiCommits  to true could block other PRs?

**Comment by rarkins** [comment]
> Those PRs are not coming from us (it should be from Travis).

I don't understand what you mean. These appear to be Renovate PRs coming from the Renovate App.

> Setting semantiCommits to true could block other PRs?

Why do you think that?

**Comment by kvor** [comment]
> > Those PRs are not coming from us (it should be from Travis).
> 
> I don't understand what you mean. These appear to be Renovate PRs coming from the Renovate App.
> 
Since we do not do the commits on this PR, how we can control it? Or it was just an explanation of the problem?

Should we just set semanticCommits to true to address this issue?

> > Setting semantiCommits to true could block other PRs?
> 
> Why do you think that?
Just to make sure that this will not happen.

**Comment by rarkins** [comment]
You should set semantic commits to true or false to prevent "flapping". Select whichever suits your ideal project style.
