### ISSUE TITLE
Lock file maintenance not working anymore

### ISSUE THREAD

**Issue by Marsup** [renovatebot/config-help#393]
**What Renovate type are you using?**

Self-hosted with github repos.

**Describe the bug**

We're using `:maintainLockFilesWeekly`, but a while ago (can't pinpoint which version exactly), it stopped working. Or rather it happens at most once per repo.

**Did you see anything helpful in debug logs?**

The logs are full of `Merged PR is blocking this branch`, my guess is it's because both the branch name (`renovate/-.x`) and the PR name (`Update dependency to`) are identical.

**To Reproduce**

It seems simple to reproduce (all our repos do that) but I'm not sure if it's specific to our environment or not.

**Comment by rarkins** [comment]
Please post your full config

**Comment by Marsup** [comment]
```js
{
  logLevel: 'info',
  onboarding: false,
  requireConfig: false,
  force: {
    "extends": [
      "config:base",
      ":maintainLockFilesWeekly",
      ":disableRateLimiting",
      "group:definitelyTyped",
      ":masterIssue",
    ],
    "labels": ['renovate'],
    "node": {
      "supportPolicy": ["active"]
    },
    "postUpdateOptions": ['yarnDedupeHighest'],
    "gradle": {
      "enabled": false,
    },
    "packageRules": [
      {
        "packagePatterns": ["*"],
        "extends": ["schedule:daily"]
      },
      {
        "groupName": "Test packages",
        "packagePatterns": [
          "^eslint",
          "^@typescript-eslint\/",
          "^ava$",
          "^jest$",
          "^nyc$",
          "^sinon$",
          "^ts-jest$",
        ],
      },
      {
        "groupName": "TypeScript packages",
        "packagePatterns": [
          "^@types\/",
          "^ts-config-paths$",
          "^ts-node$",
          "^ts-node-dev$",
          "^ts-jest$",
          "^typescript$",
        ],
      },
      {
        "groupName": "Fastify packages",
        "packagePatterns": [
          "^fastify"
        ]
      },
      {
        "groupName": "Moment packages",
        "packagePatterns": [
          "^moment$",
          "^moment-",
        ]
      },
      {
        "groupName": "Mongo packages",
        "packagePatterns": [
          "^@types/mongoose",
          "^mongodb$",
          "^mongoose$",
          "^mongoose-",
        ]
      },
      {
        "groupName": "Promises packages",
        "packagePatterns": [
          "^p-.+"
        ]
      },
      {
        "updateTypes": ["major"],
        "labels": ["update-major"],
      }
    ],
    "docker": {
      "packageRules": [
        {
          "groupName": "Unstable odd images",
          "packageNames": ["mongo"],
          "extends": ["helpers:oddIsUnstable"]
        }
      ]
    },
    "rangeStrategy": 'bump',
  },
  repositories: [
    ...
  ],
};

```

**Comment by rarkins** [comment]
Sorry, the config is too complicated to be able to know what's going wrong, so you will need to reproduce this in a public repo so that it can be debugged. Alternatively, if you can pinpoint in which Renovate version it stopped working, then there's a good chance we can debug based on that. Based on your first post, the branch name and PR title are wrong and that's causing the blocking, but it's not clear why they are wrong.

FYI the "force" config is not meant to be used as you're doing though, and I recommend you remove it or work out the minimal force config necessary. It's only meant to be used one-rule deep, and not to have nested packageRules, etc.

**Comment by Marsup** [comment]
> FYI the "force" config is not meant to be used as you're doing though, and I recommend you remove it or work out the minimal force config necessary. It's only meant to be used one-rule deep, and not to have nested packageRules, etc.

As we want a single config for all our repos, we figured it might be written like that. Should we just bring all that config one level up and drop the force key ?

**Comment by rarkins** [comment]
Yes, force is just like a "force override". Generally, Renovate uses a "cascading" config approach, e.g. config in the repo can override the bot's defaults, etc. And config within an element like 'javascript' will override the same option at root level, etc.

When you use force, it just means that the forced config is always dumped over the top of the cascaded merge. It should only be used as a last resort and for individual config options like `semanticCommits`, `branchPrefix`, etc, etc.

**Comment by rarkins** [comment]
BTW I triggered a lock file maintenance PR on the main Renovate repo to double check this and it works fine: https://togithub.com/renovatebot/renovate/pull/4704

**Comment by Marsup** [comment]
It seems to go a whole lot better without force, I didn't think it would have such an influence, it also solved some other minor issues we had. Thank you so much!
