### ISSUE TITLE
Question about how to use bitbucket with rennovate

### ISSUE THREAD

**Issue by Whispers12** [renovatebot/config-help#394]
### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket.

### What is your question?
Hi, thanks for a great service. Can you point me where in docs info how to connect it with Bitbucket?

**Comment by rarkins** [comment]
Start here: https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md

**Comment by Whispers12** [comment]
@rarkins  Thank you for help and fast response, I very appreciate it
