### ISSUE TITLE
[Question] About use case

### ISSUE THREAD

**Issue by Mansalu** [renovatebot/config-help#396]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant
No

### What is your question?
Hello! I have been exploring the documentation an experimenting with the tool. 

I want to know if it would be possible to configure renovate to pull container image source updates from multiple different repositories? 

I want to have Docker image sources as sub directories within a larger application catalog. Our system builds these images locally during deployment. Currently, we have to manually pull in upstream source changes. Does this seem out of scope for Renovate?

Thank you for entertaining my question!

**Comment by rarkins** [comment]
Can you describe your use case in more detail? I'm not sure I understand it. e.g. I don't understand "Docker image sources as sub directories". Do you mean you put the image name/tag as the subdirectory name?

**Comment by Mansalu** [comment]
Sure! Thank you for the response.

We have an application catalog which has docker image sources as part of each application. As there are multiple applications in our catalog we have many image sources some of which come from upstream projects.

By image source I mean the Dockerfile, and associated files/directories needed during the docker build process. Our deployment system builds the image locally before it is run.

We want to use renovate to synchronize each application with its upstream source.

**Comment by rarkins** [comment]
What's an application catalog? By that do you mean "repository"? "applications" and "catalogs" seem to be your internal terms so they don't help me to understand it. We deal with repositories, files, etc..

**Comment by Mansalu** [comment]
Sorry.

Our "catalog" is a single repository on GitHub with multiple sub directories each containing an "application" which is typically made of a Docker image source and a corresponding Helm chart.

We want to look at renovate for synchronizing a single repository with multiple upstream Docker sources.

**Comment by rarkins** [comment]
Renovate works with subdirectories.

**Comment by Mansalu** [comment]
I'm wondering if we can configure Renovate to synchronize an entire image source such as a Dockerfile and various supplementary files that are being copied into the image during a docker build.

**Comment by rarkins** [comment]
Renovate doesn't currently support "file" synchronisation. I have created a feature request in the main repo to track this: https://github.com/renovatebot/renovate/issues/4759

Please describe your use case in large detail there, as it will help us form the requirements for the feature implementation. Examples would be very helpful.
