### ISSUE TITLE
Lock file problem with Cookiecutter

### ISSUE THREAD

**Issue by keimlink** [renovatebot/config-help#40]
I'm using Renovate with a repository that contains a [Cookiecutter](https://github.com/audreyr/cookiecutter) project template for reveal.js. Because Cookiecutter also uses file names as templates the renovate bot says there is a [problem with the lock file's path](https://github.com/keimlink/cookiecutter-reveal.js/pull/8#issuecomment-388077012):

> {{cookiecutter.repo_name}}/yarn.lock
>
> error package.json: Name contains illegal characters

Is there a way to configure the project to avoid this?

**Comment by rarkins** [comment]
Is there an example public repo or can you create one I can use to test against? If it’s technically possible to solve then I’m happy to do it.

**Comment by keimlink** [comment]
@rarkins Thanks for the quick reply!

[keimlink/cookiecutter-reveal.js](https://github.com/keimlink/cookiecutter-reveal.js) contains a structure with a `{{cookiecutter.repo_name}}/yarn.lock` file.

**Comment by rarkins** [comment]
It's actually `yarn install` that's throwing that error, not Renovate. But I'll see if we can massage the package.json "name" field before writing it to disk to work around `yarn`.

**Comment by rarkins** [comment]
Here's their validation code: https://github.com/yarnpkg/yarn/blob/e177c3732e6cd2adb468427d06a3bbcd2a5e4356/src/util/normalize-manifest/validate.js#L25-L40

**Comment by rarkins** [comment]
@keimlink I think this may be solvable, but via a Renovate feature rather than config, so I will close this.

Can you instead create a feature request in the main Renovate repo asking that Renovate detects invalid `name` fields within `package.json` and massages them to something valid before generating lock files?
