### ISSUE TITLE
[Question]  GOPRIVATE

### ISSUE THREAD

**Issue by dethtron5000** [renovatebot/config-help#400]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant
```Command failed: docker run --rm -v /mnt/renovate/gh/nbcnews/frs:/mnt/renovate/gh/nbcnews/frs -v /tmp/renovate-cache/others/go:/tmp/renovate-cache/others/go -e GOPATH -e GOPROXY -e CGO_ENABLED=0 -w /mnt/renovate/gh/nbcnews/frs renovate/go bash -c "git config --global url.\"https://x-access-token:**redacted**@github.com/\".insteadOf \"https://github.com/\" && go get -d ./..."
go: finding github.com/streadway/amqp edfb9018d271
go: github.com/nbcnews/goutils@v0.0.0-20160304172125-8bed90746421: invalid version: git fetch -f https://github.com/nbcnews/goutils refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/renovate-cache/others/go/pkg/mod/cache/vcs/a8a5f807de0b0279565bc2c9e39df1fb359b449089e00be0c9333b07c3fc331f: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://x-access-token:**redacted**@github.com/nbcnews/goutils/' not found
```

### What is your question?
We have a go repository that uses a couple of private libraries.  When we deploy, we set the `GOPRIVATE` environment variable to allow Go Mod to access these.  When we update our repository using Renovate Bot, the artifact creation fails.  

Can we set the GOPRIVATE env var when we run Renovate Bot? If not how can we access private Go repositories so that Renovate will work?

**Comment by rarkins** [comment]
In the app we run Go within Docker, using this Dockerfile: https://github.com/renovatebot/docker-go/blob/master/Dockerfile

I would have hoped your scenario would work, so long as the source repo also has Renovate "installed" and is within the same GitHub org as the downstream repo. The 404 it's getting implies that Renovate has not been granted access to the repo, can you check?

**Comment by dethtron5000** [comment]
That resolved it, thanks!
