### ISSUE TITLE
[Question] How to set concurrent limit per manager?

### ISSUE THREAD

**Issue by lephuongbg** [renovatebot/config-help#402]
### Which Renovate are you using? CLI, App, or Pro

CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Bitbucket Cloud

### What is your question?

Is it possible to set PR concurrent limit per manager? 

We are using poetry and npm. With poetry, if there are two PRs and as soon as one is automerged, the other one's `poetry.lock` will be conflicted and can not be automerged. This doesn't happen with npm since `package-lock.json` don't have the same problem.

That is why we would like to be able to set concurrent limit of poetry to just 1 while allowing npm's concurrent limit to be more than 1.

**Comment by rarkins** [comment]
Unfortunately Renovate doesn't have this feature currently. If you're interested, please raise a feature request in the main repo, including details about how you propose the configuration would work. It will be a bit complicated to specify, because we don't limit PRs to being of one manager type.
