### ISSUE TITLE
[Question] Release notes for a group

### ISSUE THREAD

**Issue by sjparkinson** [renovatebot/config-help#403]
### Which Renovate are you using? CLI, App, or Pro

GitHub App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

https://app.renovatebot.com/dashboard#github/Financial-Times/next-epaper/107904904

### What is your question?

We have defined a group for a monorepo that we publish as individual packages.

```json
    {
      "packagePatterns": [
        "^@financial-times/dotcom-"
      ],
      "rangeStrategy": "auto",
      "masterIssueApproval": false,
      "groupName": "page kit monorepo",
      "groupSlug": "page-kit"
    }
```

https://github.com/Financial-Times/renovate-config-next/blob/master/renovate.json#L91-L99

The PR's opened (e.g. on Financial-Times/next-epaper) don't include any release notes.

The release notes are published in the GitHub release on the Financial-Times/dotcom-page-kit repository (which is private for now).

Is there anything we can do to get the release notes appearing on the Renovate PRs?

**Comment by rarkins** [comment]
Looks like it could potentially be the same issue as https://github.com/renovatebot/renovate/issues/4724

Can you read through it’s discussion and see? Eg do you have nested changelog files?
