### ISSUE TITLE
[Question] problems writing config for package grouping

### ISSUE THREAD

**Issue by 454de6e** [renovatebot/config-help#404]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: ensureIssueClosing(Action Required: Fix Renovate Configuration)
```
Not clear what is wrong with config.

### What is your question?

I'm trying to configure `renovate.json` to group certain packages by repo URL. The repo is this one: https://github.com/UNDataForum/gatsby-themes/blob/master/renovate.json

Renovate bot does not group the packages as expected with above config.

My main issue is that I am having a hard time making sense of the docs (https://docs.renovatebot.com/configuration-options/#packagerules). E.g. for `packageRules` the docs show the properties that go inside, e.g. `sourceUrlPrefixes`. But `groupName` is not listed to go inside `packageRules` yet in the examples it goes inside.

In above `renovate.json` I copied an example from the docs and modified the `sourceUrlPrefixes` for the monorepo whose package I want grouped, but it does not work. 

I seem to be missing something fundamental and am also wondering what is the best way to read up on how Renovate configs work.

**Comment by rarkins** [comment]
There doesn't appear to be anything wrong with your Renovate config. However, the `sourceUrlPrefixes` relies on the source repositories being tagged correctly in the upstream packages. I looked at one and it is invalid: https://github.com/UNDataForum/design-system/blob/8300b9ffb48f6d94335c1f0e7693230ace20fa04/packages/components/package.json#L15

See https://docs.npmjs.com/files/package.json for instructions on how the "repository" field should look.

Notably:
![image](https://user-images.githubusercontent.com/6311784/67987170-0c346900-fc2d-11e9-871f-c7c4e052cec7.png)
