### ISSUE TITLE
[Question] Does allowedVersions work for .ruby-version?

### ISSUE THREAD

**Issue by ndbroadbent** [renovatebot/config-help#406]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitLab

### Have you checked the logs? Don't forget to include them if relevant

Some logs from https://app.renovatebot.com/dashboard:

#### Config

```
DEBUG: Found renovate.json config file
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "dockerfile": {
      "enabled": false
    },
    "docker-compose": {
      "enabled": false
    },
    "bundler": {
      "enabled": true
    },
    "ruby-version": {
      "allowedVersions": "<=2.5"
    },
...
    "automerge": true,
    "automergeType": "pr",
    "major": {
      "automerge": false
    },
    "vulnerabilityAlerts": {
      "enabled": true
    },
    "lockFileMaintenance": {
      "enabled": true
    },
    "packageRules": [
...
```

#### Other logs:

```
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Matched 1 file(s) for manager ruby-version: .ruby-version
INFO: Found ruby-version package files
...
"ruby-version": [
      {
        "packageFile": ".ruby-version",
        "manager": "ruby-version",
        "deps": [
          {
            "depName": "ruby",
            "currentValue": "2.5.7",
            "datasource": "rubyVersion",
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/ruby/ruby",
            "homepage": "https://www.ruby-lang.org"
          }
        ]
      }
    ]
```

### What is your question?

Is this Renovate Bot config correct?

```
    "ruby-version": {
      "allowedVersions": "<=2.5"
    },
```

I want to stay on Ruby 2.5, but apply any patch updates. (I rely on some proprietary libraries that often take a long time to add support for new major and minor versions.) 

The [allowedVersions](https://docs.renovatebot.com/configuration-options/#allowedversions) documentation wasn't very clear about this, and I couldn't find anything else in the docs that confirmed this. The Ruby version is not really a "package", so I got the feeling that `.ruby-version` might handled in a special way.

### Additional Context

It's a great idea to stay up to date with the latest Ruby patch version, since this includes a lot of bug fixes and performance improvements.

I manually download and compile Ruby in my base Docker image. The idea is to use Renovate Bot to open a new MR where the `.ruby-version` is updated, so I will receive a notification that a new Ruby version is available. The MR will fail until I manually build and push a new Docker image for my CI tests, so I can manually fix the branch and then merge it in. (Eventually I should automate the Docker builds on a cloud server, but I haven't figured that out yet.)

**Comment by rarkins** [comment]
It should work for any manager however the strong used should be compatible with the versionScheme in use. I need to dig into that for ruby versions. We fall back to Semver so potentially <= 2.5.0 works but I have doubts. We would need to check if any of our existing version schemes supports “<= 2.5” syntax

**Comment by ndbroadbent** [comment]
Thank you! I would like to use any patch version for `2.5.x`. Does the Ruby version scheme support `~> 2.5.7`?

**Comment by rarkins** [comment]
Sorry, needed to look that up. Confirmed that the `ruby-version` manager uses the `ruby` versionScheme by default: https://github.com/renovatebot/renovate/blob/c102ffa1d3a21256b250d2151a9a3481f8197976/lib/config/definitions.ts#L1423

So this means that yes, the Ruby range syntax is what you should be trying.

**Comment by ndbroadbent** [comment]
Thanks, that’s great! Thanks very much for your help!
