### ISSUE TITLE
[Question] Reviewers not applied for path

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/config-help#407]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yes, couldn't find anything relevant.

### What is your question?

We configured reviewers by path:

https://github.com/sourcegraph/sourcegraph/blob/241532d621979940d3901ac1f92a8620f710d4f2/renovate.json#L15-L18

But they don't get applied: https://github.com/sourcegraph/sourcegraph/pull/5804

Other team reviewers without `paths` get applied correctly: https://github.com/sourcegraph/sourcegraph/pull/6394

Is the glob in `paths` wrong? What should it be?

**Comment by rarkins** [comment]
Have you found the “team:” prefix for reviews working ok elsewhere? Ie without paths?

**Comment by felixfbecker** [comment]
Yes, see the second PR linked

**Comment by rarkins** [comment]
Thanks, sorry I missed that. I’ll check the glob and see if it’s meant to be single `*`

**Comment by rarkins** [comment]
It seems that both single and double star in the glob should work fine then: 
![image](https://user-images.githubusercontent.com/6311784/68699985-f716de80-0538-11ea-9738-4972571e7757.png)
