### ISSUE TITLE
[Question] Standalone usage (CLI)

### ISSUE THREAD

**Issue by strarsis** [renovatebot/config-help#408]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
None (for the question/code)

### What is your question?
I want to use the `composer.json` dependencies upgrade feature of `renovate` by just invoking `renovate` CLI on a directory that contains a `composer.json` (and a `composer.lock`). 
Can `renovate` be used like that or does it always have to clone + check out + branch a repository?

**Comment by rarkins** [comment]
Sorry, Renovate only works with a remote platform like GitHub, GitLab, etc.
