### ISSUE TITLE
[Question] Remove flag "Immortal" from specific upgrade

### ISSUE THREAD

**Issue by johannesleander** [renovatebot/config-help#409]
### Which Renovate are you using? CLI, App, or Pro
* CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
* GitLab

### Have you checked the logs? Don't forget to include them if relevant

* Not relevant

### What is your question?
* Upgrading [Babel](https://www.npmjs.com/package/@babel/cli) 7.4.4 -> 7.6.4 causes errors that are too severe for my organization to focus on right now and we'd like to to make the upgrade "mortal" in order to clear it from our queue of merge requests. How would I achieve such a change?

**Comment by rarkins** [comment]
Immortal happens when there’s a grouping of packages without a common version so Renovate can’t be specific in the PR title. Did you apply any custom groupings or just the defaults?

**Comment by johannesleander** [comment]
We have no custom groupings configured.

**Comment by rarkins** [comment]
Can you screenshot the PR body containing the list of upgrades?

**Comment by johannesleander** [comment]
![image](https://user-images.githubusercontent.com/5199716/68217952-d227e600-ffe3-11e9-9a4a-52f5c870dede.png)

**Comment by rarkins** [comment]
Thanks. The challenge here is the non-synchronised version numbers. As you can see, it wouldn't be accurate to name the PR "Update babel monorepo to v7.6.4", so we fall back to "Update babel monorepo" which then makes it immortal as there's no way to differentiate it in future when checking the history.

If Renovate didn't perform this grouping for you automatically, would you still want them altogether, would you want them all separate, or would you have something like 3-4 groups?

**Comment by johannesleander** [comment]
Thanks for the feedback. I do believe Renovate does this grouping automatically since we currently have no custom grouping rules in place.

I'm not entirely sure why Renovate would create this particular grouping. Can we control the way it groups updates?

**Comment by rarkins** [comment]
Renovate comes with a list of default presets, including monorepo groupings, that you are inheriting by including `config:base` in your config. If you remove that preset then the babel grouping goes away along with all the others.

It's possible to configure Renovate to discard that grouping altogether, but you probably want *some* grouping of Babel, which is why I asked this part:

> If Renovate didn't perform this grouping for you automatically, would you still want them altogether, would you want them all separate, or would you have something like 3-4 groups?

**Comment by rarkins** [comment]
If you add `"ignorePresets": ["group:babelMonorepo"]` to your config then the automatic grouping of babel should go away - you'll get one PR per dependency - and they will no longer be immortal.

The short answer is that unfortunately there's no way to "remove" an immortal flag once it's there though, so I will close this as a config question. If you have any ideas you are welcome to raise a feature request in the main repo.
