### ISSUE TITLE
[Question]  Does the Renovate GitHub App only run on a schedule for npm modules or is it also listening for package publishing events and running when those happen

### ISSUE THREAD

**Issue by ajcann** [renovatebot/config-help#411]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
Does the Renovate GitHub App only run on a schedule for npm modules or is it also listening for package publishing events and running when those happen? Same question re: docker registry publish events.

Thanks!

**Comment by rarkins** [comment]
The app enqueues up every onboarded repo each hour, although the queue is not always drained hourly depending on many new PRs there are. The app also has an npm listener and enqueues each repo that depends on any newly published package. I'm not aware of there being any similar ability to listen to a global feed of Docker registry publish events like npm supports.

**Comment by ajcann** [comment]
Thank you for the information @rarkins ! Does the app's npm listener listen to private as well as public npm registries?

**Comment by rarkins** [comment]
npm's global feed doesn't include private repositories (for security reasons).

**Comment by ajcann** [comment]
Got it - thanks!
