### ISSUE TITLE
[Question] Does renovatebot have an api endpoint for notifying of private releases like dependabot?

### ISSUE THREAD

**Issue by ajcann** [renovatebot/config-help#412]
### Which Renovate are you using? CLI, App, or Pro
GitHub App

### What is your question?
Dependabot has the ability to kick off real-time updates for consumers of privately published dependencies by hitting an api endpoint when a private package is published. Does renovatebot have a similar feature or plan to support the feature?

Reference - https://github.com/dependabot/api-docs#notify-dependabot-of-a-private-dependency-release

**Comment by rarkins** [comment]
We don't have support for this currently. Considered it in the past especially for npm (which has the ability to define webhook receivers for private repository publishes) but as Renovate already runs hourly then it hasn't been considered high priority. What was your planning for how you would trigger such a notification? e.g. as part of your CI build, post-publish?

**Comment by ajcann** [comment]
Generally we're looking to use a dependency bot to actively push updates to packages to downstream consumers upon release of those packages. I.e. Applications a, b, c, ..., n have private package X as dependency and we would like to push the update of the package via PRs to those applications without each application needing to be known by X. 

The thought with an endpoint as noted above would be the ability to force a dependency scan on known consumers of a privately published packagedby hitting the endpoint in CI after publishing the package.

**Comment by rarkins** [comment]
Assuming an hourly schedule, the current expectation would be that downstream repos would get a PR from Renovate on an average of 30 minutes +/- 30 minutes. In your case, you're hoping for something like 5-10 minutes after update?

**Comment by ajcann** [comment]
Our aim is to have a push rather than scheduled system as our current workflow (CI/CD) is driven by these updates. That being said, 5-10 minutes would probably be nearly indistinguishable from a push.

**Comment by rarkins** [comment]
And right now are you looking at private npm modules on npmjs.org, or Docker Hub too?

**Comment by ajcann** [comment]
We're publishing our private npm modules to Github Package Registry and our docker images to Google Container Registry. In theory the dependabot scheme of notifying about a specific release, for a specific registry/package manager which kicks off a shallow check of all repos that the PAT has access to within an organization would be exactly the aim, but unfortunately the feature doesn't seem to really work.

**Comment by rarkins** [comment]
It's also important to consider all the security and DDoS angles too. Someone flooding an endpoint like that with random/fake PAT's could induce the receiving endpoint to flood GitHub's API with failing authentication requests and get itself blocked, which could then have much wider implications. Even legitimate PAT's could result in the bot running non-stop on accounts and exhausting limits if safeguards aren't in place.
