### ISSUE TITLE
Set prPriority for external monorepo definitions?

### ISSUE THREAD

**Issue by blowery** [renovatebot/config-help#414]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant
Nope, not relevant

### What is your question?
In https://github.com/Automattic/wp-calypso/pull/37445 we're trying to up the priority for certain packages. Is it possible to set the prPriority for a monorepo definition defined elsewhere? See https://github.com/Automattic/wp-calypso/pull/37445/files#r344200198

Thanks!

**Comment by rarkins** [comment]
You should be able to, but the [wordpress monorepo definition](https://github.com/renovatebot/presets/blob/2cda948b40835151157e778ccb3f96387b7974eb/packages/renovate-config-monorepo/package.json#L482-L487) is only one line anyway. But the packageRule would be like this:

```json
{
  "extends": ["monorepo:wordpress"],
  "prPriority": 5
}
```

**Comment by rarkins** [comment]
I don't recommend mixing and matching it with other package patterns - keep them in a different rule

**Comment by blowery** [comment]
> I don't recommend mixing and matching it with other package patterns - keep them in a different rule

I'm not sure I follow, maybe an example would make it clear. 

Are you saying it should look more like:
```
{ 
  packageRules: [
    { 
      extends: [ "monorepo:wordpress" ],
      prPriority: 2
    },
    { 
      extends: [ "monorepo:babel" ],
      prPriority: 1
    },
    { 
      extends: [ "monorepo:react" ],
      prPriority: 1
    },
    { 
      extends: [ "monorepo:lodash" ],
      prPriority: 1
    },
    { 
      extends: [ "monorepo:redux" ],
      prPriority: 1
    },
  ]
}
```
?

**Comment by rarkins** [comment]
@blowery yeah, that was what I meant. It's not *mandatory* but some of the monorepo presets are not compatible with combining together (if one type is based on sourceUrl and another is based on package scope), so it can be easier to just define separate rules than bother with the "research" to check.

**Comment by blowery** [comment]
Thank you!
