### ISSUE TITLE
Problems pinning dependencies

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#415]
### Which Renovate are you using? CLI, App, or Pro
CLI
 
### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub
 
### Have you checked the logs? Don't forget to include them if relevant
 
```
DEBUG: packageFiles with updates (repository=CTAgile/pubsub-browser)
"config": {
  "npm": [
    {
      "packageFile": "package.json",
      "manager": "npm",
      "deps": [
        {
          "depType": "dependencies",
          "depName": "commander",
          "currentValue": "^4.0.0",
          "datasource": "npm",
          "prettyDepType": "dependency",
          "updates": [],
          "warnings": [],
          "sourceUrl": "https://github.com/tj/commander.js"
        },
        {
          "depType": "dependencies",
          "depName": "@google-cloud/pubsub",
          "currentValue": "^1.0.0",
          "datasource": "npm",
          "prettyDepType": "dependency",
          "updates": [],
          "warnings": [],
          "sourceUrl": "https://github.com/googleapis/nodejs-pubsub"
        }
      ],
      "packageJsonName": "pubsub-browser",
      "packageJsonVersion": "1.1.0",
      "packageJsonType": "library",
      "npmrc": "***********",
      "skipInstalls": true
    }
  ]
}
```
 
### What is your question?
 
I'm using the following configuration options, explicitly pinning dependencies
 
```
  autodiscover: true,
  autodiscoverFilter: 'CTAgile/pubsub-browser',
  requireConfig: true,
  automerge: false,
  extends: ['group:allNonMajor'],
  enabledManagers: ['npm','gradle'],
  rangeStrategy: 'pin',
  recreateClosed: true,
  reviewers: ['hmarr'],
  stabilityDays: 7,
  prCreation:'not-pending',
```
 
however, the on boarding PR didn't include a "pinning dependencies" PR under the "what to expect" section 

```
What to Expect

With your current configuration, Renovate will create 3 Pull Requests:

Update dependency @google-cloud/pubsub to ^0.32.0
Schedule: "at any time"
Branch name: renovate/all-minor-patch
Merge into: master
Upgrade @google-cloud/pubsub to ^0.32.0

Update dependency @google-cloud/pubsub to v1
Schedule: "at any time"
Branch name: renovate/google-cloud-pubsub-1.x
Merge into: master
Upgrade @google-cloud/pubsub to ^1.0.0

Update dependency commander to v4
Schedule: "at any time"
Branch name: renovate/commander-4.x
Merge into: master
Upgrade commander to ^4.0.0

```

For example, @google-cloud/pubsub was updated from "^0.30.0" to "^1.0.0" while "1.1.5" is the latest version available.  

Package | Type | Update | Change
-- | -- | -- | --
@google-cloud/pubsub | dependencies | major | ^0.20.0 -> ^1.0.0

Any idea why dependencies are not getting pinned ?

**Comment by rarkins** [comment]
It’s strange. Can you replicate it in a public repo so I can debug? Eg as little as one dependency and a minimal config.js. I assume you’re already sure that the config.js is being read?

**Comment by rvillane** [comment]
yes, I'm positive the config.js is being read by the bot. I certainly can add a repo to replicate this issue, can you clarify what needs to be added ?  I'm not clear if you want the target repo that I'm trying to update the dependencies for, or the bot config.

**Comment by rarkins** [comment]
I would need both a config.js + public repository that show the same behaviour as you're seeing. Ideally it should be as minimal as possible to reproduce the problem and not a full copy.

**Comment by rvillane** [comment]
please let me know if https://github.com/rvillane/renovate-pinning has everything you need

**Comment by rarkins** [comment]
It seems to pin fine using the config you gave: https://github.com/renovate-tests/renovate-pinning/pull/1

But note that the reproduction you gave does not match with your description earlier, e.g. you already have a renovate.json there so there was no onboarding PR to review.

**Comment by rarkins** [comment]
I deleted the renovate.json to confirm that it does not reproduce the problem. Pinning is as expected:

![image](https://user-images.githubusercontent.com/6311784/68535561-6d9ebb00-0344-11ea-8777-44c1198713bc.png)

**Comment by rvillane** [comment]
I tried myself and got the same results you report, including the expected pin dependencies PR.  Now I'm scratching my head why using the same package.json and the same config.js does not pin dependencies when executed in GitHub Enterprise.
