### ISSUE TITLE
[Question] Automerge not working, would like help verifying my config

### ISSUE THREAD

**Issue by usmanity** [renovatebot/config-help#416]
### Which Renovate are you using? CLI, App, or Pro
I'm using the renovate bot on github (with a paid plan if that matters)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant
Yes, but didn't find anything relevant enough: [logs](https://app.renovatebot.com/dashboard#github/usmanity/stocks-chrome-extension/111029586)

### What is your question?
I have automerge enabled on my repository, [link to repo](https://github.com/usmanity/stocks-chrome-extension/pulls) but I don't see any PRs being auto-merged. I can see in the PR description that the automerge feature is enabled but I'm not sure what I'm missing here...would like any help debugging this issue!

**Comment by rarkins** [comment]
The logs have a lot of help here:

```
{"level":20,"branch":"renovate/pin-dependencies","msg":"PR is configured for automerge","time":{}}
{"level":20,"branch":"renovate/pin-dependencies","msg":"getBranchStatus(renovate/pin-dependencies)","time":{}}
{"level":20,"branch":"renovate/pin-dependencies","state":"pending","statuses":[],"msg":"branch status check result","time":{}}
{"level":20,"branch":"renovate/pin-dependencies","result":{"total_count":0,"check_runs":[]},"msg":"No check runs found","time":{}}
{"level":30,"branch":"renovate/pin-dependencies","msg":"PR is not ready for merge (branch status is pending)","time":{}}
```

The last line tells you that the PR is not ready for merge because status is pending. The lines above show that it's pending because this repo has no tests.

Add `requiredStatusChecks=null` to your config if you want automerge to happen even though there's no testing.

**Comment by usmanity** [comment]
@rarkins thanks so much! I didn't know the `pending` status was related to lack to tests. This is very helpful!
