### ISSUE TITLE
[Question] Best practices for config

### ISSUE THREAD

**Issue by adamdiy** [renovatebot/config-help#419]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
Hello, I was speaking to someone at Renovatebot and they advised that our config could be improved by: 
1) separating out major version change PRs
2) not automerging major version PRs

our current config looks like this:
```{
	"groupName": "deps",
	"extends": ["config:base"],
	"bumpVersion": "patch",
	"automerge": true,
	"automergeType": "pr",
	"major": {
		"automerge": false
	},
	"prHourlyLimit": 4,
	"prConcurrentLimit": 10,
	"prCreation": "status-success",
	"schedule": [
		"before 10am on Tuesday",
		"before 10am on Wednesday",
		"before 10am on Thursday"
	],
	"updateNotScheduled": false,
	"node": {
		"enabled": false
	}
}
```
My reading of the docs (and limited experience with Renovate) has indicated that the `major: {automerge: false` would prevent automerge of the major version bumps. I got that idea here: https://docs.renovatebot.com/configuration-options/#automerge.  Is this doc no longer accurate?

It was also not our intention to group all updates into a single PR. can we avoid this by deleting the line ` 	"groupName": "deps",  ` ? 

Thanks for your help.

**Comment by rarkins** [comment]
Yes, `"groupName": "deps",` will group all updates into a single PR so delete that line to revert back to normal behaviour.

You are right though that your current config for automerging only non-major PRs is correct. It wasn't really correct while you had the grouping option, but once you remove it then it should behave how you want. You could simplify your config by adding the [`:automergeMinor`](https://docs.renovatebot.com/presets-default/#automergeminor) preset to your `extends` array.

**Comment by adamdiy** [comment]
thanks @rarkins !
