### ISSUE TITLE
[Question] Exclude dep from group

### ISSUE THREAD

**Issue by ElPicador** [renovatebot/config-help#420]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Repository has invalid config
{
  "error": {
    "configFile": "renovate.json",
    "validationError": "The renovate configuration file contains some invalid settings",
    "validationMessage": "Invalid regExp for packageRules[1].packagePatterns: `^react-(?!native).*$`"
  }
}

```

### What is your question?

Our repo contains both react and react-native dependencies. 
We are trying to have 2 groups of dependencies, one only for react (and related) the other for react-native (and related). So we did this:

```
{
  "extends": ["config:base"],
  "packageRules": [
    {
      "groupName": "react/redux",
      "packagePatterns": ["^react-(?!native).*$", "^redux"],
      "schedule": ["every weekend"]
    },
    {
      "groupName": "mobile",
      "packagePatterns": ["^react-native"],
      "schedule": ["every month"]
    }
  ]
}
```

As all react-native deps are named `react-native` we added the regex `["^react-native"]`
All react deps are named `react-`, but we didn't want to match `react-native` so we used the regex `"^react-(?!native).*$"` which matches `react-*` *but* `react-native`.

It seems the regex engine renovate uses doesn't support this notation. But it's JS valid.

How can we achieve this?

**Comment by rarkins** [comment]
We use the `re2` package for safe handling of regex. I recommend you use the `excludePackageNames` field within the same rule - will probably be easier for others to understand anyway. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ElPicador** [comment]
Sorry I missed you message. I've just tried it

**Comment by rarkins** [comment]
Something like this:

```json
{
  "extends": ["config:base"],
  "packageRules": [
    {
      "groupName": "react/redux",
      "packagePatterns": ["^react", "^redux"],
      "excludePackagePatterns": ["^react-native"],
      "schedule": ["every weekend"]
    },
    {
      "groupName": "mobile",
      "packagePatterns": ["^react-native"],
      "schedule": ["every month"]
    }
  ]
}
```

**Comment by ElPicador** [comment]
Thanks! I've just checked renovate opened a bunch of PRs 👍 
Thanks for your help.
