### ISSUE TITLE
[Question] Possible to have commits come from different user without brackets?

### ISSUE THREAD

**Issue by patrickleet** [renovatebot/config-help#423]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yes - renovate bot is running fine.

### What is your question?

My automated tests fail in Jenkins because the commits come from `renovate[bot]`

https://github.com/jenkins-x/jx/issues/3369

This seems like something that should be fixed downstream, but hasn't been, so I'm hoping to find a workaround. 

Is it possible to configure commits to come from a different bot user that doesn't use the `[bot]` suffix such as `renovatebot` or something?

**Comment by rarkins** [comment]
I think you should find that the *commit* itself is actually from @renovate-bot while the PR is created by `renovate[bot]`. Can you confirm? We need to work out exactly which field they’re choking on

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patrickleet** [comment]
it's a regex that doesn't like the [bot] brackets

the hyphen should be fine.

Here are the logs:

```
error: unable to parse requirement: invalid label value: "renovate[bot]": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

script returned exit code 1
````

You are correct that the commit is from `renovate-bot` and the PR is from `renovate[bot]`.

Guess they are actually getting caught up on the PR Author?

**Comment by rarkins** [comment]
Yes, it looks like it's the PR author that's being tripped up. This is not something to easily change because it's GitHub itself that sets the name when we create the PR using the bot's credentials. i.e. we do not have control over the name, so the only way would be to have a different account create the PR, but if it were a private repo then that would be impossible as only the bot has been granted access. Even if public, we'd face a risk of exhausting the other account's API limit if it does this too often.

**Comment by patrickleet** [comment]
Yea I figured it'd be tough or impossible to deal with on this end, but also figured it was worth asking! 

Maybe the user could provide a username/personal access token that could be used?

**Comment by rarkins** [comment]
I think that would probably risk adding too much complexity to simply work around a mistake in someone else’s system.
