### ISSUE TITLE
[Question] How to group patch version of all packages into one PR?

### ISSUE THREAD

**Issue by lephuongbg** [renovatebot/config-help#424]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket Cloud

### What is your question?
I would like to combine new patch versions of all packages into one PR, while still having separate PR for each package when updating minor/major version. Is it possible?

**Comment by rarkins** [comment]
First, you need to tell Renovate to separate minor and patch updates. Next, tell Renovate to group all patches:

```json
{
  "separateMinorPatch": true,
  "patch": {
    "groupName": "all patch updates"
  }
}
```

**Comment by lephuongbg** [comment]
Many thanks.
