### ISSUE TITLE
How to force override the base branch and define custom packageRules?

### ISSUE THREAD

**Issue by pkey** [renovatebot/config-help#425]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket

### What is your question?
I'm trying to override `renovate.json` configuration (more specifically: the base branch and some package rules) present in the default branch by using `config.js` config file and `force` option. `config.js` looks something like this: 

```
module.exports = {
  persistRepoData: true,
  repositories: ["some/repo"],
  platform: "bitbucket-server",
  logLevel: "debug",
  endpoint: "https://custom.bitbucket.net/",
  force: {
    baseBranches: ['test'],
    packageRules: [
      {
        packagePatterns: ['^@some-package'],
        followTag: 'some-tag',
        baseBranchList: ['test'],
        groupName: 'group-name'
      }
    ]
  }
};
```

The problem is, that even though the config from `config.js` file is picked up by renovate (I can see that from the logs), it still uses configuration defined in `renovate.json` and sets the base branch to the `master` branch instead of `test` branch.

Is there something I am missing here?

**Comment by rarkins** [comment]
Renovate always takes the `renovate.json` from the default branch. Using force won’t change that behaviour. Is there a problem to define your confit in the default branch even if your PRs target a different base branch?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pkey** [comment]
@rarkins In my use case, I want to have one config in `renovate.json` in the default branch, and a completely different configuration for other branches (release branches).

My idea was to generate a separate `config.js` and inject it to a running instance of Renovate, which would then ignore `renovate.json` from the default branch and act on anything that is defined in `config.js`.

**Comment by rarkins** [comment]
The idea you have is not currently supported but you can subscribe to this issue to track it: https://github.com/renovatebot/renovate/issues/2496

In the meantime, as a workaround you can still achieve separate configurations per base branch by using the `baseBranchList` inside `packageRule`. i.e. define one rule per base branch.

**Comment by pkey** [comment]
Subscribed! Thanks for the reply 👌🏻
