### ISSUE TITLE
[Question] Renovate looking for updated Java libraries in Private Artifactory 

### ISSUE THREAD

**Issue by markbsb** [renovatebot/config-help#426]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
DEBUG: Looking up com.xxxx:lib-one in repository #0 - https://yyyy.jfrog.io/zzzz/rrrr/
WARN: Dependency lookup unauthorized. Please add authentication with a hostRule

### What is your question?
I am trying to get renovate to warn about updated Java libs in our private Artifactory. I have added the following additional credentials, but it doesn't seem to be able to access the private libraries: 

```
  "gradle": {
    "enabled": true
  },
  "hostRules": [{
      "hostType": "gradle",
      "endpoint": "https://yyyy.jfrog.io/zzzz/rrrr/",
      "username": "user",
      "encrypted": {
        "password": "encryptedpassword"
      }
  }],
  "packageRules": [
    {
      "packagePatterns": [ "org.springframework" ],
      "groupName": "spring"
    },
    {
      "managers": ["gradle"],
      "registryUrls": [
        "https://yyyy.jfrog.io/zzzz/rrrr/",
        "https://other.other/"
      ]
    }
  ],
```

I have tried the encrypted password and encrypted apikey, as the password in the encrypted structure, but neither appears to work.

**Comment by rarkins** [comment]
Try to keep the hostRules as simple as possible, e.g.

```json
  "hostRules": [{
      "hostName": "yyyy.jfrog.io",
      "username": "user",
      "encrypted": {
        "password": "encryptedpassword"
      }
  }],
```

I think the `hostType` is probably the problem with your current config because it is technically a `maven` datasource, not `gradle`. Test the above and then make it more specific if you have a need.

**Comment by markbsb** [comment]
Thanks.  Removing the `hostType` and changing `endpoint` to be `hostName` seems to have done the trick. Thanks for the help.

**Comment by Xendar** [comment]
Okay, I made it work this way:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "onboardingConfig": {
    "extends": [
      "config:base"
    ]
  },
  "hostRules": [
    {
      "hostType": "maven",
      "hostName": "https://repository.mycompany.net/mvn-public/"
    }
  ],
  "java": {
    "packageRules": [
      {
        "packagePatterns": [
          "^com.mycompany."
        ],
        "registryUrls": [
          "https://repository.mycompany.net/mvn-public/"
        ]
      },
      {
        "packagePatterns": [
          "^com.mycompany.mytool"
        ],
        "enabled": false
      }
    ]
  }
}
```

1. Declaring a custom hostRule with private Artifactory
2. First package rule to declare that all packages starting with the company's groupId would be searched with the custom registry
3. Second package rule to disable the search for the tool's own artifacts

All confirmed in debug mode 👍
