### ISSUE TITLE
How to handle composer dependencies through Private Packagist?

### ISSUE THREAD

**Issue by Jchedev** [renovatebot/config-help#427]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: manager.fetchUpdates()
INFO: Unauthorized Packagist repository
{
  "regUrl": "https://repo.packagist.com/my-company/"
}
INFO: Failed to look up dependency awobaz/compoships (awobaz/compoships)(packageFile="composer.json", dependency="awobaz/compoships")
INFO: Unauthorized Packagist repository
{
  "regUrl": "https://repo.packagist.com/my-company/"
}

...

DEBUG: packageFiles with updates

...

{
  "depType": "require",
  "depName": "awobaz/compoships",
  "currentValue": "^1.1",
  "datasource": "packagist",
  "lockedVersion": "1.1.14",
  "updates": [],
  "warnings": [
  {
    "updateType": "warning",
    "message": "Failed to look up dependency awobaz/compoships"
  }
]   

...
```

### What is your question?

I am using Private Packagist to host my composer dependencies. My composer.json file : 
```
"repositories": [
        {
            "type": "composer",
            "url": "https://repo.packagist.com/my-company/"
        },
        {
            "packagist.org": false
        }
    ],
```

I tried all the options possibles in renovate.json but no luck !

**Comment by rarkins** [comment]
You should use `hostRules` to configure authentication for that host, usually combined with `encrypted` secrets. Is it username/password or a bearer token?

**Comment by Jchedev** [comment]
I tried many examples with hostRules but without success.

Should i use `hostType:packagist` ? 

Private Packagist uses the word "token" but i am not 100% sure it is a Bearer one. Otherwise, to log i need to do : 
```
composer config --global --auth http-basic.repo.packagist.com token 9cfc8ba2319115......61f6330.....470ccf222
```

Something like this didn't work for me :  

```
hostRules: [
 {
  hostType: "packagist"
  username: "token",
  encrypted: {
    password: "Token encrypted"
 }
}
]
```

**Comment by rarkins** [comment]
If it still doesn't work then we need you to confirm an exact `curl` command that works with your token first, so we can be sure. i.e. you send a curl request to your packagist how and get back a response.

You probably want something like this though:

```
hostRules: [
 {
  "hostName": "repo.packagist.com",
  "encrypted": {
    "token": "Token encrypted"
 }
}
]
```
