### ISSUE TITLE
automerge with packageRules

### ISSUE THREAD

**Issue by tsido** [renovatebot/config-help#43]
Question about the `automerge` option and how it is being applied when multiple packages are being merged in a single PR:

We have a `renovate.json` config of the following form:

```
"automerge": false,
  "devDependencies": {
    "automerge": true,
    "major": {
      "automerge": false
    }
  },
...
  "packageRules": [
    {
      "packagePatterns": ["^angular"],
      "groupName": "angular packages"
    },
   ...
  ],
  ...
```

from which renovate created a pull request with the following changes, as expected:

-   [angular-mocks](https://github.com/angular/angular.js) (`devDependencies`): from `1.6.10` to `1.7.0`
-   [angular-sanitize](https://github.com/angular/angular.js) (`dependencies`): from `1.6.10` to `1.7.0`
-   [angular-route](https://github.com/angular/angular.js) (`dependencies`): from `1.6.10` to `1.7.0`
-   [angular-resource](https://github.com/angular/angular.js) (`dependencies`): from `1.6.10` to `1.7.0`
-   [angular-cookies](https://github.com/angular/angular.js) (`dependencies`): from `1.6.10` to `1.7.0`
-   [angular](https://github.com/angular/angular.js) (`dependencies`): from `1.6.10` to `1.7.0`

But I would not have expected the PR to be automerged, since the top level `automerge` option was false, but renovate did automerge the PR. I assume this is because the `angular-mocks` package was a `devDependency`, for which the `automerge` option was set to `true`. 

Is this expected behaviour? Should we exclude any `devDependency` packages form the angular package group?

**Comment by rarkins** [comment]
Hi @tsido, thanks for your question.

In short: if you want to disable automerge for this group then you'll need to add `"automerge": false` to the `angular packages` rule you defined. If you wish to get the angular devDependencies automerged independently of angular dependencies then you'd want to break these into two groups/package rules.

I'm guessing though that your ideal behaviour would be like this?

- Automerge the angular group if all packages inside it have automerge=true
- Don't automerge if any of the packages inside have automerge=false

This makes sense to me, but it's not the way it works currently. Currently we assume the PR package settings are "homogenous" and so take the automerge setting from whatever is the first package in the PR, and it seems like that was angular-mocks.

If you would like this behaviour, please raise a feature request in the main Renovate repo so it can be added to our todo list.

**Comment by tsido** [comment]
Thanks for the quick answer!

> I'm guessing though that your ideal behaviour would be like this?

> - Automerge the angular group if all packages inside it have automerge=true
> - Don't automerge if any of the packages inside have automerge=false

Yes, this is what I was expecting. I'll make a feature request about it. For now I'll just disable automerging in our config for this particular group that has both devDependencies and prod dependencies.

**Comment by teppeis** [comment]
ref: https://github.com/renovatebot/renovate/issues/1999
