### ISSUE TITLE
Any env var available to support the list of reviewers ?

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#433]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
is there any environment variable to support the list of reviewers?  I'm running the CLI using the docker image in kubernetes and would like to avoid having the reviewers hardcoded in the config file

thanks

**Comment by rarkins** [comment]
Try `RENOVATE_REVIEWERS` with comma separated values

**Comment by rvillane** [comment]
thanks
