### ISSUE TITLE
Windows docker container update 

### ISSUE THREAD

**Issue by irrandon** [renovatebot/config-help#435]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Gitlab

### Have you checked the logs? Don't forget to include them if relevant

```
"config": {
  "dockerfile": [
    {
      "packageFile": "base-windows/Dockerfile",
      "manager": "dockerfile",
      "deps": [
        {
          "depName": "windows/servercore",
          "currentValue": "10.0.14393.3144",
          "datasource": "docker",
          "managerData": {
            "lineNumber": 0,
            "fromPrefix": "FROM",
            "fromSuffix": ""
          },
          "depType": "final",
          "updates": [
            {
               "fromVersion": "10.0.14393.3144",
               "toVersion": "10.0.18363.476",
               "newValue": "10.0.18363.476",
               "newMajor": 10,
               "newMinor": 0,
               "updateType": "patch",
               "isSingleVersion": true,
               "newVersion": "10.0.18363.476"
            }
          ],
          "warnings": [],
          "sourceUrl": null,
          "dockerRegistry": "https://docker.artifactory.example.com",
          "dockerRepository": "windows/servercore"
        }
      ]
    }
  ]
}
```

### What is your question?

We want that renovate just update the Windows update and not the whole build

From
windows/servercore:10.0.14393.3144
to
windows/servercore:10.0.14393._**3326**_
not to
windows/servercore:10.0._**18363**_.476

Is it possible to configure renovate like that?

Alternative to this version schema would this also be possible:

1607-KB4512517
to
1607-KB4525236	

[Windows container version compatibility](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-1909%2Cwindows-10-1909)

**Comment by rarkins** [comment]
Do you mean that Microsoft publish two different tag schemes (10.* and 1607-*) and you could use either?

Also, do you mean that you'll never want to upgrade the "patch" part of the version with an automated PR? 

We don't have native 4-part support for versions although we might possibly be able to meet your requirement via a workaround.

I raised this feature request to consider first-class support in Renovate for 4-part version numbers: https://github.com/renovatebot/renovate/issues/4860

**Comment by alclonky** [comment]
> Do you mean that Microsoft publish two different tag schemes (10.* and 1607-*) and you could use either?

yes

> Also, do you mean that you'll never want to upgrade the "patch" part of the version with an automated PR?

if we upgrade 10.0.14393.3326 to 10.0.18363.476 or 1607-KB4512517 to 1803-KB4525237 that would be a major upgrade including updating the nodes where we want to use the images.
But if you can use hyper-v you can to the major upgrade without upgrading the nodes. So there has to be the option if you want to do it or not.

**Comment by rarkins** [comment]
This rule should work for you:

```json
  "packageRules": [{
    "packageNames": ["mcr.microsoft.com/windows/servercore"],
    "versionScheme": "regex:^10\\.0\\.(?<major>\\d+)\\.(?<minor>\\d+)$"
  }]
```

It ignores the `10.0.` in versions and treats the third part as major and the fourth part as minor. By default major updates are ignored for Docker, so you just see one PR, e.g.

![image](https://user-images.githubusercontent.com/6311784/69492457-5bc02a80-0ea3-11ea-9f6a-0fb198c86f50.png)

**Comment by irrandon** [comment]
It works :)
Thank you
