### ISSUE TITLE
[Question] Specifying versionScheme for only nuget packages

### ISSUE THREAD

**Issue by nyctef** [renovatebot/config-help#436]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

```
...
         {
            "depType": "nuget",
            "depName": "Foo.Library",
            "currentValue": "5.6.1.2326-prerelease-text",
            "managerData": {
              "lineNumber": 13
            },
            "datasource": "nuget",
            "skipReason": "not-version",
            "updates": []
          },
...
```

Full log is at https://app.renovatebot.com/dashboard#github/red-gate/RedgateChangeControl/114361119 in case that's visible/useful

### What is your question?

From https://github.com/renovatebot/renovate/pull/4749 :

What's the best way to use the new nuget version scheme for only nuget packages? I've tried setting 
```
{
  "nuget": {
    "versionScheme": "nuget"
    ...
  }
  ...
}
```
but that didn't seem to work - I'm still seeing `"skipReason": "not-version"` on some nuget packages in the job log. I could try setting `versionScheme: nuget` at the top level config, but that'd probably be a bad idea for us since we're also using npm and other package types in the same repo.

In the past I've tried something like 
```
  ...
  "nuget": {
    "packageRules": [
      {
        "packageNames": ["Foo.Library"],
        "versionScheme": "loose"
      }
    ],
    ...
```

based on a suggestion here: https://github.com/renovatebot/config-help/issues/235 but that didn't seem to work either.

**Comment by rarkins** [comment]
The problem you're seeing is at the "extract" phase. i.e. Renovate will normally:
- File match
- Extract each file to get dependencies
- Look up versions
- Apply updates

Because it's happening at extract time, a package rule based on `packageNames` won't help, because it happens too late (after extraction). We need the extraction step to already know to use the `nuget` `versionScheme`. I would have expected your simple config approach would work, so need to debug it to determine why.

**Comment by rarkins** [comment]
I located the bug that was presenting your preferred way of configuring from working. This should now work:

```json
{
  "nuget": {
    "versionScheme": "nuget"
  }
}
```

**Comment by mark-raymond** [comment]
Which release of Renovate was this fixed in?

**Comment by rarkins** [comment]
`19.67.10`
