### ISSUE TITLE
[Question] Elegantly Group Different Managers

### ISSUE THREAD

**Issue by emmercm** [renovatebot/config-help#438]
### Which Renovate are you using? CLI, App, or Pro

App, previously pro but now free.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub.

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What is your question?

I have a project that looks similar to:

```
.
├── Dockerfile
├── app
│   ├── index.js
│   ├── package-lock.json
│   └── package.json
├── docker-compose.yml
└── terraform
    ├── main.tf
    ├── outputs.tf
    └── variables.tf
```

and I'm hoping to group those 4 different managers into separate groups / PRs without doing a config like:

```json
{
    "extends": [
        "config:base"
    ],

    "docker-compose": {
        "groupName": "docker-compose"
    },
    "dockerfile": {
        "groupName": "dockerfile"
    },
    "npm": {
        "groupName": "npm"
    },
    "terraform": {
        "groupName": "terraform"
    }
}
```

Is that currently possible with some combo of `branchName`/`branchPrefix`/`branchTopic` or similar? I'm looking to make a clean example for my organization which may get used by other languages such as PHP, Ruby, and Go.

**Comment by rarkins** [comment]
I'll have a think and get back to you, but something you may want to think about in the meantime is to use a shared "preset" for your org so that you can have centralized configuration. That even if your config is a bit lengthy like the above then at least you only configure it in one place and not in every repo. Have you looked into that approach before?

**Comment by emmercm** [comment]
That's a good point, I hadn't considered a shared preset. Couple of questions:

- The majority of the organization's repositories are private, so the Renovate config repo would be, too. Based on documentation, this is fine as long as the GitHub app has been installed to both the private config repo and the private code repos, right?
- In the config repo, can I still use a non-default but supported name like `renovate.json5`? Having comments would be valuable for other org members.
- In the shared preset, is there a way to define "base" presets like `:separateMajorReleases` that can be selectively used by the "child" repos? I see bit about `default` in the "How to Publish Preset Configs" section but it's not entirely explained.

Thank you so much for the thoughtful response!

**Comment by rarkins** [comment]
- Right
- I think currently only `.json` is supported in a preset directory. Nothing fundamentally preventing it though
- Yes, you can define multiple configs inside different presets within the parent preset config repository. For example you can put them each into different `.json` files and then identify them that way. If no filename is given then Renovate looks for `default.json` and then `renovate.json`

**Comment by rarkins** [comment]
BTW one other thing to consider re: grouping specifically is that you most likely do not want to group major updates together. i.e. group only patch and minor, to reduce the chances of one one breaking update holding up a PR

**Comment by emmercm** [comment]
Got it, so I could have a preset repository `abc/foo` with the files:

`./default.json`:

```json
{
    "extends": [
        "config:base"
    ]
}
```

`./schedule.json`:

```json
{
    "timezone": "America/Detroit",
    "schedule": "before 9am on the first day of the month",
    "vulnerabilityAlerts": {
        "schedule": "at any time"
    }
}
```

and then reference them in a separate repository like:

```json
{
    "extends": [
        "github>abc/foo",
        "github>abc/foo:schedule"
    ]
}
```

right? Just to clarify. Appreciate you taking the time to walk through this with me.

**Comment by emmercm** [comment]
And you're absolutely right, I would want to separate major and minor, and possibly even separate major depending on the language/manager.

Something like:

```json
{
    "extends": [
        "config:base"
    ],

    "npm": {
        "minor": {
            "groupName": "npm"
        }
    }
}
```

**Comment by emmercm** [comment]
Addition to the above about `default.json` and `schedule.json` - can the preset repo reference other presets in the same repo? Say we edit the `default.json` so it becomes:

```json
{
    "extends": [
        "config:base"
        "github>abc/foo:schedule"
    ]
}
```

any reason that wouldn't work?

**Comment by rarkins** [comment]
> any reason that wouldn't work?

In theory that should work (i.e. references into the same preset repository). If not, we would track it as a bug.

**Comment by rarkins** [comment]
A key point is make sure that all your code repos extend your own presets and not any that we distribute. e.g. you might find that `config:base` is perfect for you now as a base, but later you might not want a certain behaviour. If your code repos all included `config:base` then you have a challenge to push overrides out to them all, whereas if those repos extended one of your own presets (each of which may extend `config:base` initially) then you have control to make centralized changes later that propagate almost instantly.

**Comment by emmercm** [comment]
I'll give that self-reference a shot and see how it works for us.

Good call about `config:base`. Even though it looks like most of its config follows Renovate defaults, we probably don't want a surprise change in our organization.

Thank you for all the help! This can probably be closed now.
