### ISSUE TITLE
[Question] mariadb minor update 

### ISSUE THREAD

**Issue by zeug-it** [renovatebot/config-help#439]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Gitlab-CE

### What is your question?
I have my global renovate bot running great with one backdraw, it creates merge requests for mariadb upgrade from 10.1.37 -> 10.4.10 and not to 10.1.43.
Is it possible to define a max versin in the individual renovate.json in the project repository?

Many thanks,
Martin

**Comment by rarkins** [comment]
By default Renovate combines/collapses patches and minor updates together. i.e. if there exists both a patch and a minor update, then you'll get only the minor one. You could also think of this as that Renovate's default is to create at most 1 non-major update per package.

Change this by setting `separateMinorPatch` to `true` either globally or per-package using `packageRules`. You *can* use the `allowedVersions` option in `packageRules` too, if you want to manually control the versions.

**Comment by zeug-it** [comment]
Many thanks - this works great.
Greetings,
Martin
