### ISSUE TITLE
"Lock file problem" with local (on desk) packages

### ISSUE THREAD

**Issue by ahmedelgabri** [renovatebot/config-help#44]
node module resolution allows for doing this

```json
{
  "foo": "file:./path/to/foo/folder",
  "bar": "file:./path/to/bar/folder",
}
```

but `npm` will only accept this if you have a `package.json` file in each of these directories, while `yarn` will happily work without any problems.

We use `yarn` but renovate keeps having problems with `yarn.lock` which causes lots of noise in the PR with this type of message:

> ### Lock file problem
>
> Renovate failed when attempting to generate a lock file. This is usually happens when you have private modules but have not added configuration for [private module support](https://renovateapp.com/docs/deep-dives/private-modules). It is strongly recommended that you do not merge this PR as-is.
>
> Renovate **will not retry** generating a lockfile for this PR unless either (a) the `package.json` in this branch needs updating, or (b) you rename then delete this PR unmerged, so that it can be regenerated.
>
> The output from `stderr` is included below:
>
> ##### yarn.lock
>
> ```
> error An unexpected error occurred: "Package \"foo\" refers to a non-existing file '\"/tmp/tmp-302VAClp2yPICJ/path/to/foo/folder\"'.".
>
>```

So how can I tell the app to ignore these packages or mark them safe or skip them? Keeping in mind that I already added them to `ignoreDeps` but that didn't change anything.

```json
{
  "ignoreDeps": [
    "foo",
    "bar"
  ]
}
```

**Comment by rarkins** [comment]
The error comes from yarn so adding a renovate ignore therefore does nothing as it’s not an instruction relevant to yarn.

Renovate doesn’t download entire repos and instead picks up just the package files it detects via API. Therefore there’s nothing in that directory that it’s looking for. If you had package.json files then it would probably work with the help of `copyLocalLibs` setting.

I don’t think there’s any way to resolve this with config without some additional feature. 

How many files are in these directories you’re referencing?

**Comment by ahmedelgabri** [comment]
> The error comes from yarn so adding a renovate ignore therefore does nothing as it’s not an instruction relevant to yarn.

I dunno, but I don't get any errors from `yarn`, locally I have the latest version & in our app we deploy using `1.5.1` also no errors.

> Renovate doesn’t download entire repos and instead picks up just the package files it detects via API. Therefore there’s nothing in that directory that it’s looking for. If you had package.json files then it would probably work with the help of `copyLocalLibs` setting.

Might give this a try

> How many files are in these directories you’re referencing?

A lot, it's a directory that has many directories inside, for legacy reasons we can't move it around so we aliased it through `package.json` to make things easier to deal with.

**Comment by rarkins** [comment]
Are you using GitHub Enterprise? Familiar with Docker?

**Comment by rarkins** [comment]
There might still be a way though. Do you know what `yarn` actually *does* with that directory without `package.json`? e.g. maybe we just need to make sure the directory exists, and it could be empty. The contents of the `yarn.lock` for that package might give a hint at that too.

**Comment by ahmedelgabri** [comment]
So, with `file:<path>`

- `npm` will symlink the path inside `node_modules`
- `yarn` will copy the path inside `node_modules`

`yarn.lock` contents in this case looks like this

```
"foo@file:./path/to/foo":
  version "0.0.0"
```

There is also `link:<path>` 

- `npm` doesn't support it
- `yarn` will symlink the path inside `node_modules`

`yarn.lock` contents in this case looks like this

```
"foo@link:./path/to/foo":
  version "0.0.0"
  uid ""
```

**Comment by rarkins** [comment]
Is that "0.0.0" coming from anywhere inside your repository, or is it a placeholder version that `yarn` inserts for these types of dependencies?

**Comment by ahmedelgabri** [comment]
I think it's a placeholder because I have only one `package.json` file in the whole repo & even that has a version `1.0.0`

**Comment by rarkins** [comment]
On that case I may be able to solve this merely by writing an empty directory matching what yarn expects. Is the affected repo using the official GitHub app?

________________________________

**Comment by ahmedelgabri** [comment]
No, we self-host the app

**Comment by rarkins** [comment]
In that case, you could try editing the code around `copyLocalLibs` (https://github.com/renovateapp/renovate/blob/2167eeba119c04246cdced4184515ec63e5249d2/lib/manager/npm/post-update/index.js#L137) to instead just write an empty directory in the case where no `package.json` is found. Currently it just skips over that case. If that solution works, you're welcome to submit a PR back to the main project to get the functionality included in the mainline releases.

I'll close this issue now as unfortunately this is not solvable via config alone.

**Comment by ahmedelgabri** [comment]
Thanks, will try to do this & see how it goes.
