### ISSUE TITLE
Direct renovate to update docker image references to use a Semver tag

### ISSUE THREAD

**Issue by fullstackzach** [renovatebot/config-help#440]
### Which Renovate are you using? CLI, App, or Pro
Self-hosted CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab self hosted

### What is your question?

Hello! I'm working on setting up renovate to update docker image references.

Our own private base-images we create publish a semver tag based upon the node version it's including. eg 'nodejs10:10.16.3'. It also publishes the same image on another tag using a git commit sha as the tag. 

One barrier to adoption is most of our repos have Dockerfiles set up to use the git commit sha tag because this is how we enforced immutability in the past (even though it's technically mutable). Eg. a typical FROM directive would look like

`FROM privateregistry.com/repo:ae1d9fb46aa2b07ee9836d49862ec4e2c46fbbba`

This is an issue when renovate goes to pin it and it would change to something like

`FROM privateregistry.com/repo:ae1d9fb46aa2b07ee9836d49862ec4e2c46fbbba@sha256:0d2a23e9a7407ab0d979fbd982d8e0b62a504ba6681c84c3df396f0eba4ee61d` 

But, then it would never update again because I'm guessing renovate doesn't know what's next to version to. So it seems that a manual step (or a script to do a one time update) to switch to use the semver based tag is needed.

I was hoping to accomplish this via renovate though. Is there a way to configure a packageRules rule enforce using the semver tag instead?

**Comment by rarkins** [comment]
You can use both semver tags and sha256 pinning within Docker. Check out https://renovate.whitesourcesoftware.com/blog/overcoming-dockers-mutable-image-tags/ but particularly the "Insure against breaking Docker tags" section.

Something like `nodejs10:10.16.3@sha256:abcdefg........`

Renovate would then send you a PR if either you updated the build hash or if you published an incremented semver tag.

**Comment by fullstackzach** [comment]
Thanks @rarkins for your prompt response, I always appreciate it! Yes I am working towards that ideal state, but many of our repos do not have a semver tag already. For example most Dockerfile FROM instructions have a format like

`privateregistry.com/repo:nonsemvertag`

Renovate pins the digest on the end with a pinning MR and that becomes

`privateregistry.com/repo:nonsemvertag@sha256:abcdefg...`

But, Renovate does not update that image any further since the tag is not in a semver format.  I'm thinking because that digest is the latest available for that tag. Our docker registry does have a semver format version tags published and available though.  I would like to be able to have renovate pick the latest semver tag available and move our docker FROM lines to use that. so an image like

`privateregistry.com/repo:nonsemvertag`

would turn into 

`privateregistry.com/repo:10.16.3@sha256:abcdefg...`

**Comment by rarkins** [comment]
I'm not 100% sure that I understand your requirement, but if it's your goal that Renovate "upgrades" `privateregistry.com/repo:nonsemvertag` to `privateregistry.com/repo:10.16.3` then unfortunately it's not something we support or probably would be likely to support. For images that do have semver tags I think you need to kick it off by setting them in the `Dockerfile` yourself initially and then letting Renovate pin the hash and keep the image updated afterwards.

**Comment by fullstackzach** [comment]
Thanks. Yes it sounds like that is what I’m looking to do. We have a large number of repos using a nonsemver format tag we wish to move to a versioned tag so renovate can keep them up to date.

I suppose we could update them as we encounter them over time, or create a script to open PRs for those that don’t match a semver format
