### ISSUE TITLE
[Question] Different commit message based on type of Gradle dependency

### ISSUE THREAD

**Issue by gmariotti** [renovatebot/config-help#442]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.
Self-Hosted

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### Have you checked the logs? Don't forget to include them if relevant
/

### What is your question?
Hi, is there any property that allows to set the commit message for Gradle plugins updates to `chore` while for dependencies in the `dependencies {}` block to `fix`? Even more, would it be possible to do it based on the configuration in which each dependency is set, for example, `implementation` dependencies have a commit message `fix` while others have `chore`?

**Comment by rarkins** [comment]
I think this would require us to add support for `depTypes` to Gradle.

**Comment by rarkins** [comment]
Yes, confirmed. Unfortunately not possible using config currently. Please follow this feature request in the main repo instead: https://github.com/renovatebot/renovate/issues/4316

**Comment by gmariotti** [comment]
Cool, thanks, I will open a feature request
