### ISSUE TITLE
[Question] semanticCommitType doesn't seem to work

### ISSUE THREAD

**Issue by iangregsondev** [renovatebot/config-help#443]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

Github

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### What is your question?

i have the following renovate.json

```
{
  "timezone": "Europe/Madrid",
  "semanticCommitType": ":arrow_up:",
  "semanticCommitScope": null,
  "packageRules": [
    {
      "updateTypes": ["lockFileMaintenance", "pin"],
      "semanticCommitType": ":pushpin:"
    },
    {
      "updateTypes": ["rollback"],
      "semanticCommitType": ":arrow_down:"
    },
    {
      "updateTypes": ["digest", "bump"],
      "semanticCommitType": ":bookmark:"
    }
  ]
}

```

but the pull requests that arrive don't have the emojis etc

Here is an example pull request

https://github.com/iangregsondev/instant-accounts/pull/13

also instead of just updating the json.. i created a pull request with title Reconfigure Renovate

and it said it passed the tests and then I merged - then the above PR arrived but it doesn't seem to have the :arrow_up:

Can you help ?

**Comment by rarkins** [comment]
I suspect you need to add `"semanticCommits": true` to your config.

> and it said it passed the tests and then I merged - then the above PR arrived but it doesn't seem to have the ⬆️

It's verifying the syntax of your config, that's all. It can't verify if your config does what you intend to do, as such a check would be too inaccurate.

**Comment by iangregsondev** [comment]
ok - thanks, actually I initially added this before but then all that arrived was a

(chore) .....

but no prefix of the arrow_up

I will try again.

I suppose the correct way of doing this, is per the instructions.. ie..

i create a pull request and once passing the tests - then i merge it ?

If I modify the renovate.json directly in the master branch and push, does this mean that renovatw knows nothing about it ?

**Comment by iangregsondev** [comment]
ah wait :-) Maybe I got it wrong

Should it be   "commitMessagePrefix": ":arrow_up:", instead of semanticCommitType

**Comment by rarkins** [comment]
Please try testing again and paste your full config. It's often the case that people try multiple things and don't realise they never tested the exact combination that would work. Use `semantic`-prefixed options not `commitMessage` ones although it's likely you could get either to work.

**Comment by iangregsondev** [comment]
Hi,

I finally got it to work. Using the following, I will close this but leave it here in case somebody else needs it 

```
{
  "extends": ["config:base"],
  "timezone": "Europe/Madrid",
  "commitMessagePrefix": ":arrow_up:",
  "packageRules": [
    {
      "updateTypes": ["pin"],
      "commitMessagePrefix": ":pushpin:"
    },
    {
      "updateTypes": ["rollback"],
      "commitMessagePrefix": ":arrow_down:"
    },
    {
      "updateTypes": ["digest", "bump"],
      "commitMessagePrefix": ":bookmark:"
    }
  ]
}

```
