### ISSUE TITLE
[Question] Automerging (rebasing instead of merging ?)

### ISSUE THREAD

**Issue by iangregsondev** [renovatebot/config-help#446]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

github

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

github

### What is your question?

I have everything working great but i would like to enable autoMerge but i would like to REBASE via github rather than merging - is this possible ?

**Comment by rarkins** [comment]
Renovate *should* rebase as its first preference on GitHub, so long as it hasn't been disabled for the repo by admins: https://github.com/renovatebot/renovate/blob/ad0f7c027efdc94422611b1e2a4487549d906546/lib/platform/github/index.ts#L286-L296

**Comment by iangregsondev** [comment]
Ok thank you
