### ISSUE TITLE
Question - How bot works when scheduling is not enabled ?

### ISSUE THREAD

**Issue by nimmoadam** [renovatebot/config-help#448]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.
Self-Hosted CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?

PS - Instead of creating 4 different issues, am asking my queries in a single issue. 

Q1) How long will it take for Pull Request to open when I haven't added any configuration for scheduling my updates? 

Q2) Let's say I have merged the onboarding PR. Then it immediately creates multiple PRs for the dependency updates. Assume, I have checked them and merged all those PRs. Since I haven't configured my bot to run in any schedule  - What happens next? If there is a new version for any package, how will bot know and create Pull Request? 

Q3) I see an issue with pom.xml. 

```
INFO: Found package lookup warnings in onboarding (repository=NK/REPO1)
       "warnings": [
         "Failed to look up dependency com.path1.path2:operational-cache-cos",
         "Failed to look up dependency com.path1.path2:mdmx-oc-cos",
         "Failed to look up dependency com.path1.path2:analytics-api-persistence-utilities"
       ],
       "warningFiles": ["FOLDER1/pom.xml", "FOLDER2/pom.xml", "pom.xml"]
```

Q4) My Config is : 

```
{
	"extends": ["config:base"],
	"reviewers": ["nk"],
	"baseBranches": ["master"],
	"automerge": true,
	"major": {
		"automerge": false
	},
	"timezone": "Europe/Berlin"
}
```

in the logs I see 

![image](https://user-images.githubusercontent.com/5639452/69801713-dec3e680-11fd-11ea-94d6-dcc4a259a99a.png)

**Comment by rarkins** [comment]
Q1-2) Renovate CLI runs as often as you tell it to run. e.g. if you cron it for every hour, it will run once per hour. Each time it runs, it will check each repository once. If your scheduling is too frequent then they'll overlap and potentially start causing errors as they conflict with each other.

Q3) it means it can't find them. Are they public, e.g. on maven central?

Q4) seems it could not look up the package. You need to run at DEBUG level for a start, to get more info to troubleshoot

**Comment by rarkins** [comment]
In future it's preferred if you don't group unrelated questions into one issue - it's better to separate them.
