### ISSUE TITLE
Prevent Renovate from updating Docker Ubuntu base image to an unsupported version

### ISSUE THREAD

**Issue by lawtancool** [renovatebot/config-help#449]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.
GitHub App

I currently have a Dockerfile which defines `ubuntu:18.04@sha256:134c7fe821b9d359490cd009ce7ca322453f4f2d018623f849e580a89a685e5d` as the base image.

Now, Renovate wants to upgrade to `ubuntu:18.10` even though this version is end-of-life and is not supported. 18.04 is the latest LTS version, and I would like to stay on 18.04.

How would I force Renovate to stop upgrading the Ubuntu version? I want it to update when a new digest is released, but I don't want it to upgrade to the next _version_.

**Comment by rarkins** [comment]
Assuming that the PR says something like "Update Ubuntu to v18.10" then if you close it you should get a message saying you won't be prompted about 18.10 again. You'll still get digest updates for 18.04 though.

**Comment by lawtancool** [comment]
Ah, I see the ignore notification in my email now. Thanks!

**Comment by pbrisbin** [comment]
:wave: sorry for the late reply, Google brought me here...

Is there a way to tell renovate bot about LTS? I'm about to close my own 18.04->18.10 PR, but ideally renovate would open me an 18.04 -> 20.04 PR instead.

**Comment by viceice** [comment]
@pbrisbin  nope, sorry. you can use `masterIssueApproval` to don't open pr for this, or you can use [`allowedVersions`](https://docs.renovatebot.com/configuration-options/#allowedversions) with a regex.

**Comment by rarkins** [comment]
See https://github.com/renovatebot/renovate/issues/6060 for a feature request to follow
