### ISSUE TITLE
extending from a shareable config no longer allows layering assignees etc?

### ISSUE THREAD

**Issue by Aghassi** [renovatebot/config-help#45]
We started using renovate in one GHE repo, and as we have grown it we started a shared config. However, things like assignees and such per repo can change. So that is not part of the default config. 

Our default config is in `package.json` and published to the registry under a scoped module.

```json
  "renovate-config": {
    "default": {
      "extends": [
        "config:base"
      ],
      "endpoint": "enterpriseEndPoint/api/v3",
      "semanticCommits": true,
      "respectLatest": true,
      "rebaseStalePrs": true,
      "updateLockFiles": true,
      "prHourlyLimit": 0,
      "prConcurrentLimit": 0,
      "labels": ["dependency-update"],
      "circleci": {
        "automerge": true
      },
      "devDependencies": {
        "automerge": true
      },
      "patch": {
        "labels": ["patch", "dependency-update"],
        "automerge": true
      },
      "minor": {
        "labels": ["minor", "dependency-update"]
      },
      "major": {
        "labels": ["major", "dependency-update"]
      }
    }
  }
```

This is then added as an NPM module to the repo that builds on top of it (I know, this may be unecessary). We use to have a `config.js` file that we specified using the `RENOVATE_CONFIG_FILE` variable, but clearly that doesn't work because `extends` only works with `json`. So in the `json` config we now have the below. I've sanitized it a bit for confidentiality reasons, but you get the gist. 

```json
{
    "extends": [
        "@internal"
    ],
    "assignees": ["daghassi", "otherOwner"],
    "packageRules": [
        {
          "packagePatterns": [ "apollo", "^graphql-tag$" ],
          "groupName": "apollo",
          "reviewers": ["corpId"]
        }
    ],
    "ignoreDeps": [
        "bower",
        "dcl",
        "handlebars",
        "grunt",
        "load-grunt-config",
        "time-grunt"
    ]
}
```

Essentially, prior to this change we were getting people assigned automatically per PR. After this change, that never happens. Not for reviewers, and not for assignees. However, ignore is still working. What am I missing here?

**Comment by rarkins** [comment]
If you run with `LOG_LEVEL=debug` set in env then you will get much more logs that may give you an indication of what's going wrong. Some settings in your "@internal" preset are using deprecated fields but those should be migrated to the new ones automatically and not impacting it. 

Be aware that assignees and reviewers are set at time of PR *creation* only, so you would want to capture the log when a new PR is created.

**Comment by rarkins** [comment]
As far as I can recall - and a git blame check might confirm - we’ve skipped assignees and reviewers from almost the very beginning of automerge and nothing is changed intentionally recently. We should assign *if* tests fail or still haven’t passed after 24 hours. Of course, assigning immediately or not could be made into a configurable option (eg `assignWhenAutomerging`) but I think you might prefer less notifications about PRs.

**Comment by rarkins** [comment]
You could also consider setting a schedule outside of normal working hours (using cron or Renovate’s embedded capability) so that you’re less likely to get updates to master happening between Renovate runs.

**Comment by Aghassi** [comment]
So I'm seeing it is assigning now. I removed the `rebaseStalePrs` value, so maybe that was it. I wasn't clear on that by default. But now my configs are the same as above, but without that and it works. If I have other issues, I'll reach out. Thank you for being so helpful and accomodating!

**Comment by rarkins** [comment]
Is it assigning them immediately, or only "stale" ones that haven't passed after 24 hours? I'm very surprised if it's assigning PRs as soon as they're created if they are set for `automerge`. If you think anything is still fishy, feel free to hit me up again with logs etc.
