### ISSUE TITLE
"Fixing" pull requests after misconfiguration

### ISSUE THREAD

**Issue by jmac105** [renovatebot/config-help#450]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.
CLI (19.71.6)

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket server

### Have you checked the logs? Don't forget to include them if relevant
Yes

### What is your question?
We have just enabled renovate bot running against our bitbucket server instance, as it's only just been enabled we currently have quite a high number (>100) pull requests open from renovate. Unfortunately due to a misconfiguration on the 2nd scheduled run through renovate picked up all its previously opened PRs as having been edited and as such will no longer make any updates to them. 
I think I have resolved the misconfiguration by adding `gitAuthor` to our config.js, the problem was that the git commits were showing up as coming from a different user than the renovate bot which I believe was caused by having a global git config on the server which the CLI ran from. 
My question is: assuming that `gitAuthor` will prevent this issue from happening again, what can we do with the pull requests we have open which renovate has stopped watching? I understand with github I could apply a label to them but this isn't a feature supported by bitbucket server 😕

**Comment by rarkins** [comment]
Can you try renaming an existing PR to start with `rebase!` i.e. prepend it to the existing title, and then see if Renovate rebases when it runs.

Ref: https://github.com/renovatebot/renovate/blob/b6336d3a88915826363675590b9107efc4f5895d/lib/workers/branch/index.ts#L47

**Comment by jmac105** [comment]
Yep that seems to have worked, will put together a script to rename them all. Cheers!
