### ISSUE TITLE
[Question] How to update only specific tagged dependencies ignoring all the rest?

### ISSUE THREAD

**Issue by pkey** [renovatebot/config-help#453]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Bitbucket Server

### What is your question?

I am trying to configure Renovate to update only specific dependencies (in this case, internal dependencies) with a specific tag to one of the base branches. By specific dependencies, I mean only the ones that match the pattern and ignoring all the rest.

My current config: 

```
{
  "baseBranches": ["master", "next"],
  "packageRules": [
    {
      "excludePackagePatterns": ["^@dep1", "^@dep2"],
      "enabled": false,
      "baseBranchList": ["next"]
    },
    {
      "packagePatterns": ["^@dep1", "^@dep2"],
      "followTag": "next",
      "baseBranchList": ["next"],
      "groupName": "dep"
    }
  ]
}
```

Is this the correct way to do it? Or is there a better approach?

**Comment by rarkins** [comment]
You don't have any merge rules in your config, so I wonder if there's a confusion about that. Renovate raises PRs by default and does not merge anything itself unless you tell it to. Can you double check your question and edit it to make it clearer about what you're trying to do?

Right now:
- master branch will have regular behaviour
- You disable dep1 and dep2 packages from updating at all on next branch
- Then you try to group those same packages together, but they are already disabled so it won't do anything

And none of the above has anything to do with merging.

**Comment by pkey** [comment]
Hello! Sorry for the confusion. I meant updating, or processing, the dependencies - not merging.

But looking at your description of what my config should do, it seems that it is not the case. What it does now:

1. Same as you said
2. `dep1 and dep2` are under `excludePackagePatterns`, so what it actually does, is that it disables all other packages EXCEPT `dep1` and `dep2`. Tested.
3. As all packages OTHER than `dep1` and `dep2` are disabled, tag rules are applied and they have grouped accordingly.

When I try to have all of this configuration under one object - then nothing works.

**Comment by rarkins** [comment]
The next question is: why do you have `"followTag": "next"`? Does every package you want to update have a `next` tag defined in the registry? It's a pretty rare setting, so wonder if that's causing the problem.

**Comment by pkey** [comment]
I guess I could expand my use case: 

```
{
  "baseBranches": ["master", "next1", "next2"],
  "packageRules": [
    {
      "excludePackagePatterns": ["^@dep1", "^@dep2"],
      "enabled": false,
      "baseBranchList": ["next1", "next2"]
    },
    {
      "packagePatterns": ["^@dep1", "^@dep2"],
      "followTag": "next1",
      "baseBranchList": ["next1"],
      "groupName": "dep-next1"
    },
   {
      "packagePatterns": ["^@dep1", "^@dep2"],
      "followTag": "next2",
      "baseBranchList": ["next2"],
      "groupName": "dep-next2"
    }
  ]
}
```

Basically, I want to simultaneously follow specific dependencies based on release tag, in this case, `next1` and `next2`, and open PRs to respective branches.

**Comment by rarkins** [comment]
So dep1 and dep2 package are all published with both `next1` and `next2` tags to an npm registry? `followTag` will keep you pinned to whatever that tag is on the registry, and it will cause problems if you don't use it. The functionality was created for someone who wanted to stick to the bleeding edge in `typescript`, which has these tags:

![image](https://user-images.githubusercontent.com/6311784/70130093-3dff7c00-1680-11ea-8ffa-8d713072c920.png)

Assuming you're sure about it, but your config doesn't produce the results you expect, then you need to run renovate with LOG_LEVEL=debug and capture those logs. I can't help you very much though considering it's all private.

**Comment by pkey** [comment]
@rarkins Yes, exactly. `dep1` (and `dep2`) can both have `next1`, `next2`, `next3` tags and so on. And then I only open PRs to respective branches, based on that tag.

The config actually produces the result I need - I just wanted to know if there was a better way to configure it :)

**Comment by rarkins** [comment]
In that case, I can't think of any better way to configure it than you already have. Just beware that `followTag` is pretty strict in how it behaves, so make sure the tag always exists and is correct. For example I notice a lot of project (including some of mine) sometimes publish a `next` tag at some point but then forget about it and it falls behind `latest`. Renovate will dutifully keep following `next`. Or for example `typescript@rc` or `typescript@beta` in the above screenshot is another example where a tag that was once ahead falls behind.

**Comment by pkey** [comment]
I see. Well, `followTag` behaving strictly is what we need :)

Thanks for clarifying things!
