### ISSUE TITLE
[Question] Exclude package names for semverAllMontyly PR

### ISSUE THREAD

**Issue by nescalante** [renovatebot/config-help#454]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

Renovate On prem

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

I have the following configuration:

```json
{
  "extends": [
    "config:semverAllMonthly",
    ":pinOnlyDevDependencies"
  ],
  "packageRules": [{
    "excludePackageNames": ["winston", "winston-syslog"]
  }]
}
```

However, in the monthly Renovate PR, it is still including updates for winston and winston-syslog. Is that expected? How can I ignore updates for winston and winston-syslog?

**Comment by rarkins** [comment]
The packageRule you added doesn't actually do anything right now. `excludePackageNames` is used to match against packages and not as an instruction - i.e. it means "don't match against". If you want to ignore those packages then the simplest way is with `"ignoreDeps": ["winston", "winston-syslog"]`. If you wanted to ignore them via a package rule you'd do this:

```json
  "packageRules": [{
    "packageNames": ["winston", "winston-syslog"],
    "enabled": false
  }]
```

**Comment by nescalante** [comment]
thanks @rarkins ! will try that
