### ISSUE TITLE
[Question] Group updates by language

### ISSUE THREAD

**Issue by openjck** [renovatebot/config-help#455]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

GitHub app

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

Is it possible to group updates by language? We'd like Renovate to open one pull request each week for all JavaScript updates and a separate pull request each week for all Python updates.

I haven't been able to find an answer to this question in the documentation. I figured this configuration might work, but it's unclear from the documentation.

```json
{
  "extends": ["config:base"],
  "js": {
    "extends": ["group:all"]
  },
  "python": {
    "extends": ["group:all"]
  }
}
```

**Comment by openjck** [comment]
I'm going to create a repository to test this configuration. I'll report back with the results, hoping that this issue is useful to others. Maybe the docs can be updated, too.

**Comment by openjck** [comment]
My configuration doesn't appear to work. In my [test repository](https://github.com/openjck/sandbox-test-renovate-platform-grouping-config), Renovate groups all updates into one pull request.

Is there another way to achieve our desired result?

**Comment by rarkins** [comment]
Can you try this?

```
{
  "extends": ["config:base"],
  "js": {
    "managerBranchPrefix": ["js-"]
  },
  "python": {
    "managerBranchPrefix": ["python-"]
  }
}
```

**Comment by openjck** [comment]
That raised a validation error about how *managerBranchPrefix* should have a single string as a value. I updated it to this:

```json
{
  "extends": ["config:base"],
  "js": {
    "managerBranchPrefix": "js-"
  },
  "python": {
    "managerBranchPrefix": "python-"
  }
}
```

which caused packages to be updated individually:

![Screenshot_2019-12-03 openjck sandbox-test-renovate-platform-grouping-config](https://user-images.githubusercontent.com/933396/70091260-c2eb8680-15e9-11ea-9b8b-792bdd072b1d.png)

The JS packages aren't updated, but maybe that's just because of a delay.

**Comment by openjck** [comment]
The results can be seen [in this repo](https://github.com/openjck/sandbox-test-renovate-platform-grouping-config/pulls), but fair warning, I've been deleting and re-creating the repo to trigger Renovate.

**Comment by rarkins** [comment]
Sorry, I made a mess of that when copy/pasting. Here's my new suggestion:

```
{
  "extends": ["config:base", "group:all"],
  "js": {
    "managerBranchPrefix": "js-"
  },
  "python": {
    "managerBranchPrefix": "python-"
  }
}
```

I believe this should have the effect of grouping together but splitting it into separate groups. BTW you may want to consider grouping only non-major together and keeping major updates into separate PRs, regardless of language.

**Comment by openjck** [comment]
Yes, it looks like that did the trick. It put a security update into its own PR, but I think that's fine. Thank you!

![](https://user-images.githubusercontent.com/933396/70171498-d3106e00-169c-11ea-8898-00ba226e2a40.png)

**Comment by rarkins** [comment]
Yes, security updates have a setting so that they bypass any grouping or schedule set.
