### ISSUE TITLE
Hardcoded npmrc when npmToken specified

### ISSUE THREAD

**Issue by wywfalcon** [renovatebot/config-help#456]
**What Renovate type are you using?**

Irrelevant.

**Describe the bug**

https://github.com/renovatebot/renovate/blob/master/lib/config/massage.ts#L25

**Did you see anything helpful in debug logs?**

N/A

**To Reproduce**

N/A

**Additional context**

When `npmToken` is specified, npmrc is overriden with `//registry.npmjs.org`. It should be reinterpreted with `_authToken=<value_from_npmToken>`.

**Comment by rarkins** [comment]
I've transferred this issue to the config-help repository for now.

![image](https://user-images.githubusercontent.com/6311784/70111938-201c2200-1654-11ea-8fe9-f1d72a7960e5.png)

Please answer this and describe exactly how you'd like to deploy Renovate. I can't answer you further without more details of your setup.

> Moreover on this design pattern, the requirement for the on-boarding renovate.json is a particular blocker and is quite impractical for organizations with hundreds of repositories.

There are other organizations with hundreds of repositories who prefer using onboarding. You're free to have an opinion on how you want to configure things for your organization but please be polite and avoid speaking for others you don't know. It's quite possible you would be able to avoid it but until you describe your usage I can't answer you for sure.
