### ISSUE TITLE
Monorepo PRs

### ISSUE THREAD

**Issue by joonarahko** [renovatebot/config-help#457]
### Which Renovate are you using?
Self-hosted Renovate

### Which platform are you using?
Github

### What is your question?
We are currently setting up an architecture for a monorepo where we have packages that get published from within the repository. Each package has its own package.json file and I was wondering if there is a way to scope a renovate PR to a specific package within the same repository. Currently renovate creates a single PR for the same dependency, but this is not-ideal for us because we might not want to migrate each package to a new version at once (especially if it is a breaking change).

**Comment by rarkins** [comment]
If it’s a JS monorepo and you use Lerna or Yarn Workspaces to manage it then Renovate won’t actually generate PRs for internal packages. Are you doing it an alternate way?

**Comment by joonarahko** [comment]
Sorry for getting back to this issue so late and thanks for taking the time to reply. It is a JS monorepo and we use lerna to manage it. 

This is how to PR looks like in our repo that the renovate bot creates. When I look at the diff, it is updating the package.json and lock files under each package.

<img width="688" alt="Screen Shot 2019-12-12 at 11 41 36 AM" src="https://user-images.githubusercontent.com/28296253/70743424-906e1780-1cd4-11ea-8a29-918f510ab68f.png">

<img width="1670" alt="Screen Shot 2019-12-12 at 11 44 05 AM" src="https://user-images.githubusercontent.com/28296253/70743515-c3b0a680-1cd4-11ea-97a1-d1cf04b4d008.png">
<img width="1669" alt="Screen Shot 2019-12-12 at 11 43 57 AM" src="https://user-images.githubusercontent.com/28296253/70743516-c3b0a680-1cd4-11ea-921f-030a69057029.png">

**Comment by rarkins** [comment]
Our templating includes two generated fields `parentDir` and `baseDir` that might be useful here. In the above example, `parentDir` would be `acquire`. You could try this to split PRs completely between their parent directories:

```json
{
	"npm": {
		"branchName": '{{{branchPrefix}}}{{{parentDir}}}-{{{branchTopic}}}'
	}
}
```

I recommend you probably test it against a fork first, to be sure - and make sure you have `includeForks` set to `true` in your bot config if so.

You should see that the combined PRs are now split, but there may still be some work to be done on PR title + further grouping if you desire. Let's try to verify this part first.

**Comment by joonarahko** [comment]
Thanks a lot @rarkins We will try this out later this week :)
