### ISSUE TITLE
Group PRs that match semver range

### ISSUE THREAD

**Issue by MarcusNoble** [renovatebot/config-help#46]
I'm currently using the CLI tool to run renovate against some of our repos. We've currently got it set to group all to reduce on noise but I noticed this morning that major releases (not matching the semver range specified in the package.json) are being included. We don't want this as these could potentially have breaking changes we're not aware of and would like to test these in isolation. 

Our current config is:
```
renovate --token $GITHUB_TOKEN --npm-token $NPM_TOKEN \
	--ignore-npmrc-file=true --expose-env --upgrade-in-range=true \
	--labels renovate --group-name=all $REPO_NAME
```

I think I may have misunderstood what `--upgrade-in-range` was for as I thought this caused renovate to respect the semver ranges specified.

Is this currently possible?

For example:
Today I had a repo that had 3 npm dependencies to update. 

package1 from `^8.10.15` to `^10.1.2` (should have been to `^8.10.17` if matching semver range)
package2 from `^2.2.1` to `^3.0.0`
package3 `^6.0.1` to `^6.0.2`

What I'd have liked was a PR with package1 upgraded to `^8.10.17` and package3 updated to `^6.0.2`

**Comment by rarkins** [comment]
As you suspected, `upgradeInRange` doesn't do what you think it does. I have recently renamed and combined a few settings to hopefully make it more understandable. It's now renamed "bump" strategy and you can read about it and others here: https://renovatebot.com/docs/configuration-options/#rangestrategy

I think you just want "replace" though, which is default behaviour for any regular/simple range like `^1.0.0`.

Ultimately it sounds like your requirement is fairly simple though: don't include major updates in your all group. I've created a preset just now that hopefully does the trick, although it can be a little challenging to define via CLI so perhaps you can start by adding it to `renovate.json` instead. You need to add:

```
  "extends": ["group:allNonMajor"]
```

I haven't tried this approach myself but you could attempt stringified JSON via CLI if you really want: `--renovate-extends='{"extends":["group:allNonMajor"]}'`.

The end result should be as you expect - the "all" PR contains only minor and patch updates, while each major update gets its own PR so you can test it in isolation.

**Comment by MarcusNoble** [comment]
>Ultimately it sounds like your requirement is fairly simple though: don't include major updates in your all group.

That's not strictly true. That's desired at least but ultimately we want updates to be within the specified semver range. Would adding `"extends": ["group:allNonMajor"]` achieve that?

It actually sounds like `bump` is what I want. Is that correct? Can I specify this to the CLI?

**Comment by rarkins** [comment]
Why use semver ranges at all if you just bump them to the latest?

**Comment by rarkins** [comment]
i.e. what's the point of a range of the range has a length of 1?

**Comment by MarcusNoble** [comment]
We're using renovate to make sure our dependencies are kept up to date with any bug fixes (patch releases). This is done automatically against all our repos daily. 

We may have specifically chosen a specific range (because a later version changes how something was implemented) so we wouldn't want renovate to update out of that range but it could still be possible to get bug fixes.

Does that make sense?

**Comment by rarkins** [comment]
I understand what you're saying and need to think about it more to think if `bump` meets all your requirements. Certainly it's the closest for now. I think you probably also want the `group:allNonMajor` preset as well though.

In theory you use ranges if you have downstream dependencies and need to support a wide range of versions, and you use exact if you're an app or your downstream dependencies don't need ranges. For many years though people have used ranges as a kind of "I'm feeling lucky automatic update service" but ultimately the number of "works on my machine" problems becomes too high if your team is larger than one. So then we got lock files, but the problem with them is that the lock file stays locked and potentially missing important patch updates unless you make enough changes to `package.json` to trigger a regeneration of the relevant sections of the lock file.

> We may have specifically chosen a specific range (because a later version changes how something was implemented) so we wouldn't want renovate to update out of that range but it could still be possible to get bug fixes.

You seem to be describing an example where you specify `^1.0.0` or maybe `^1.5.2` and although 2.x exists you don't want to update to it. Most common example of that is `angular` - there aren't many other packages that backport fixes to old major ranges. Usually you need to take the major upgrades if you want to get the subsequent fixes.

You could:
- Disable all major upgrades using Renovate.. but see the above for why that's a bad idea
- Disable major upgrades for any *specific* packages that you know you don't want to update to
- Allow Renovate to raise major update PRs for all dependencies but then just close those unmerged. This tells Renovate that you want to ignore that major version and not to try to update to it again.

**Comment by MarcusNoble** [comment]
You make a lot of good points. I understand what you're saying.

I'll have a play around with bump and `group:allNonMajor` to see if we can come up with a solution that works for our team. 

Thanks you for taking the time to talk through this with me. :) I very much appreciate it.

**Comment by MarcusNoble** [comment]
Yeah I get that. It's very flexible.
