### ISSUE TITLE
[Question] Why does not renovate recognize schedule config?

### ISSUE THREAD

**Issue by exKAZUu** [renovatebot/config-help#461]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

GitHub app

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

https://app.renovatebot.com/dashboard#github/WillBooster/plantuml-visualizer/119753351

> DEBUG: Checking schedule(at any time, Asia/Tokyo)(branch="renovate/typescript-eslint-monorepo")
> DEBUG: No schedule defined(branch="renovate/typescript-eslint-monorepo")
> 

### What is your question?

Renovate created & merged https://github.com/WillBooster/plantuml-visualizer/pull/372 4 hours ago (from now). The PR includes the following statements.

> Renovate configuration
> 📅 Schedule: At any time (no schedule defined).

However, my config (https://github.com/WillBooster/willbooster-configs/blob/master/packages/renovate-config/package.json) uses `schedule:weekly`, so I expected it occurred only on early Mondays. Why did Renovate ignore this config?

**Comment by rarkins** [comment]
I wonder if it's failing to import your preset due to this line being wrong: https://github.com/WillBooster/willbooster-configs/blob/87817c9a9255a47ff280b02e1dd27d031df9dc17/packages/renovate-config/package.json#L22

Can you correct it first and then we check again?

**Comment by rarkins** [comment]
Actually the main cause is something else. You need to extend `@willbooster` and not `willbooster` if you want it to look up `@willbooster/renovate-config` instead of `willbooster-renovate-config`.

**Comment by exKAZUu** [comment]
Thank you so much!
