### ISSUE TITLE
[Question] Excluding packages that start with @angular / @nrwl ?

### ISSUE THREAD

**Issue by iangregsondev** [renovatebot/config-help#462]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

Github

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

github

### What is your question?

Hi,

Any package that starts with @nrwl or @angular should not be upgrades automaticaly becasue there is a tool to run that may or may not (depending on rules) do more that just upgrade the package i.e. change angular.json - change nx.json

I would like to know how to Ignore packages that start with @nrwl or @angular - so that I am able to do these locally.

I am having an issue of understanding or to perform this.

Can you lend a hand ?

My current renovate is 

```
{
  "extends": ["config:base"],
  "timezone": "Europe/Madrid",
  "commitMessagePrefix": ":arrow_up:",
  "packageRules": [
    {
      "updateTypes": ["pin"],
      "commitMessagePrefix": ":pushpin:"
    },
    {
      "updateTypes": ["rollback"],
      "commitMessagePrefix": ":arrow_down:"
    },
    {
      "updateTypes": ["digest", "bump"],
      "commitMessagePrefix": ":bookmark:"
    }
  ]
}
```

**Comment by rarkins** [comment]
Try this package rule:

```json
{
  "packagePatterns": ["^@nrlw\/", "^@angular\/"],
  "enabled": false
}
```

BTW you might be interested in this discussion: https://github.com/renovatebot/renovate/issues/4256

**Comment by iangregsondev** [comment]
great! Thank you. I will disable for the time being.
