### ISSUE TITLE
[Question] Is possible to configure custom path for .gitlab-ci.yml

### ISSUE THREAD

**Issue by gmelillo** [renovatebot/config-help#464]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitLab EE

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Repo is not onboarded
INFO: Repository has no package files - skipping
INFO: Finished repository
```

### What is your question?

I got a repository in GitLab that have a folder named `gitlab` with inside a bunch of templates that gets imported from other repositories to extends their pipeline.

When I try to connect renovate on that is not creating an onboarding PR because is not able to find anything to renovate.

It is possible to place a `renovate.json` file in order to specify that all the yml files in the `gitlab` folder are to be treated as gitlab-ci files?

**Comment by rarkins** [comment]
Try something like this:

```json
{
  "gitlabci": {
    "fileMatch": ["^gitlab/*.yml$"]
  }
}
```

**Comment by gmelillo** [comment]
looks not working on the `renovate.json` in the repository, is possible to have a specific rule in the main config to add that file match only on a list of repositories?

**Comment by gmelillo** [comment]
Nevermind is working :)
I've added this:

```json
"gitlabci": {
    "fileMatch": [
        "^gitlab/.*\\.yml$",
        "^gitlab/.*\\.yaml$",
        "^\\.gitlab-ci\\.yml$"
    ]
  }
```
