### ISSUE TITLE
[Question] Updated to support automerging but all my pull requests are still there 

### ISSUE THREAD

**Issue by iangregsondev** [renovatebot/config-help#465]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

github
### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
github

### What is your question?

Just updated my renovate.json and it seems to work as a pull request starting @nrwl was closed (I have elected to ignore these)..

But my pull requests are still open.

I know if there is a merge conflict then a PR is created but I think everything is fine..

I am extending my config - which is how I am supporting automerge and automergebranch i.e

```
  "extends": ["config:base", ":automergeMinor", ":automergeBranch"],
```

heres the full config, any ideas ?

Do I just need to wait - its been about 4 hours so far. If I close the PRs then they will not be asked for again.

```
{
  "extends": ["config:base", ":automergeMinor", ":automergeBranch"],
  "timezone": "Europe/Madrid",
  "commitMessagePrefix": ":arrow_up:",
  "packageRules": [
    {
      "packagePatterns": ["^@nrwl/", "^@angular/"],
      "enabled": false
    },
    {
      "updateTypes": ["pin"],
      "commitMessagePrefix": ":pushpin:"
    },
    {
      "updateTypes": ["rollback"],
      "commitMessagePrefix": ":arrow_down:"
    },
    {
      "updateTypes": ["digest", "bump"],
      "commitMessagePrefix": ":bookmark:"
    }
  ]
}
```

**Comment by rarkins** [comment]
Does your repository have tests that run on branch commits? Eg is Travis or CircleCI being triggered?

**Comment by rarkins** [comment]
Does your repository have tests that run on branch commits? Eg is Travis or CircleCI being triggered? Renovate won’t by default merge unless GitHub reports the branch as being “green”, which only happens if there are passed tests.

**Comment by iangregsondev** [comment]
Hi, thanks for the response. No, i have no tests (right now) and travis and CircleCi are not involved..

Here are the links to the PRs (still open)

https://github.com/iangregsondev/instant-accounts/pulls

and the latest renovate.json on master

https://github.com/iangregsondev/instant-accounts/blob/master/renovate.json

Here is an example PR https://github.com/iangregsondev/instant-accounts/pull/28

I tried clicking the checkbox on all of them..

```
 If you want to rebase/retry this PR, check this box
```

**Comment by iangregsondev** [comment]
actually each PR states

```
This branch has no conflicts with the base branch
Merging can be performed automatically.
```

**Comment by rarkins** [comment]
Clicking the checkbox does nothing except recreate the PR. It's not merging.

Renovate by default will - for very good reasons - not merge a PR that hasn't passed any tests. "This branch has no conflicts with the base branch" is not a test. It's simply telling you that there are no git conflicts.

You need to add `"requiredStatusChecks": null` to your config if you want to tell Renovate to ignore status checks and merge anyway. Just be aware that you may end up with broken software if you upgrade without any testing.

**Comment by iangregsondev** [comment]
Thanks, yes, its my plan to write tests soon :-)

I am going to add travis or something which I think should be sufficient - need to do a little investgation in this area :-)

In the meantime, i will just add this line.

**Comment by iangregsondev** [comment]
Seems to be working now, i will close this, thanks again for all your help
