### ISSUE TITLE
The `config:base` preset does not work correctly

### ISSUE THREAD

**Issue by frbuceta** [renovatebot/config-help#466]
**What Renovate type are you using?**

Platform: Bitbucket Cloud

**Describe the bug**

When I create the pull requests and one of them is based on ": separateMajorReleases" and they are dependencies (not devDependencies) it does not meet the other property ": semanticPrefixFixDepsChoreOthers"

![Screenshot 2019-12-10 at 14 03 51](https://user-images.githubusercontent.com/13822438/70532001-6a226d80-1b56-11ea-8f51-c4207c38b60e.png)

**To Reproduce**

A project with dependencies that change to a larger version and that in the renew file is the "config:base"

**Additional context**

**Comment by frbuceta** [comment]
I upload an example when I have some time

**Comment by frbuceta** [comment]
thats weird! in github it works, but in bitbucket it doesn't

See: https://github.com/frbuceta/renovatebot-issue-466

In github I am running it through the app for github and in bitbucket as terminal, can that be the problem?

**Comment by rarkins** [comment]
This type of thing should be the same for both. Do you have a public Bitbucket Cloud repo it reproduces in?
