### ISSUE TITLE
Renovate won't sign commits

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/config-help#470]
**What Renovate type are you using?**

Docker image via GitLab

**Describe the bug**

When providing a private GPG key to sign commits, renovate still says it won't sign the commits in the debug log.

**Did you see anything helpful in debug logs?**

`DEBUG: No git private key present - commits will be unsigned (repository=REDACTED)`

**To Reproduce**

`docker run renovate/renovate:latest --platform gitlab --timezone Europe/London --token $RENOVATE_TOKEN --autodiscover --git-author 'REDACTED_EMAIL' --private-key "$PGP_KEY" --log-level debug --dry-run`

**Additional context**

GPG keypair has been added to GitLab account I use for renovate which matches the `--git-author`, so I can't see why its not wanting to sign commits.

**Comment by Jamesking56** [comment]
How do I do the out-of-band commands using the docker image?

**Comment by Jamesking56** [comment]
Also I changed the command line `--private-key` to `--git-private-key` and got an error:

`error: unknown option '--git-private-key'`

**Comment by rarkins** [comment]
You can set it using RENOVATE_GIT_PRIVATE_KEY in env.

Re: how to do the out of band commands, you will need to work out the best way that suits your process. You could for example build your own image based off Renovate and add the key + `RUN` the commands, or you could use the regular Renovate image but mount a wrapper startup script that runs the git commands before running the usual entrypoint/command, etc.

**Comment by Jamesking56** [comment]
OK I'm now getting `Git private key configured, but not being set` - What does that mean?

**Comment by rarkins** [comment]
It just means that Renovate isn’t setting the key itself. Ie what I described earlier.

**Comment by Jamesking56** [comment]
Tested and commits are now signed, thanks for the help @rarkins :+1:
