### ISSUE TITLE
Extends won't take rangeStrategy from extended config

### ISSUE THREAD

**Issue by DiegoRBaquero** [renovatebot/config-help#472]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [x] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

Yes

https://app.renovatebot.com/dashboard#github/DiegoRBaquero/testing/120911880
https://app.renovatebot.com/dashboard#github/DiegoRBaquero/testing/120911873

### What would you like to do?

if I add `rangeStrategy` to my repo config (https://github.com/DiegoRBaquero/testing/blob/master/package.json#L23), it works, but if I don't, it's not extended from: https://github.com/DiegoRBaquero/renovate-config/blob/master/default.json

What am I doing wrong?

Thank you!

**Comment by rarkins** [comment]
I can't see the testing repo. Is it private? Can you reproduce the "non working" version using a public repo?

**Comment by DiegoRBaquero** [comment]
My bad,

Just made it public!

Thank you for the quick response

**Comment by rarkins** [comment]
And what do the logs say?

**Comment by rarkins** [comment]
[pinVersions](https://github.com/DiegoRBaquero/renovate-config/blob/bf02b95c7de5deb5e2f66c113b4531fd6db713dd/default.json#L5) is a deprecated setting, that will be converted to `rangeStrategy=replace`. Please remove that line in your config and I think it should work as expected.

**Comment by DiegoRBaquero** [comment]
It it, thank you so much!!
