### ISSUE TITLE
How to get the renovate-approve bot to approve PRs?

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#475]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [X] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

I would like the renovate-approve bot to approve the PRs created by Renovate. I have enabled the bot on the repository but I'm not getting any approvals by the bot on Renovate PRs.

**Comment by rarkins** [comment]
First check: have you installed the approve bot for all repos? https://github.com/apps/renovate-approve

i.e. it's a second standalone bot, not the same as WhiteSource Renovate

**Comment by simoneb** [comment]
@rarkins yes

![image](https://user-images.githubusercontent.com/20181/70987397-1a94f200-20c0-11ea-8c9a-f205d9008587.png)

**Comment by rarkins** [comment]
It will only approve PRs marked as configured for automerge, and also that are created after you install the approve bot.

**Comment by simoneb** [comment]
> It will only approve PRs marked as configured for automerge, and also that are created after you install the approve bot.

ha! this explains then. automerge is what I was missing, I thought it would approve anyway

**Comment by rarkins** [comment]
Glad we worked it out. I updated the app description to be more clear too.

**Comment by DalderupMaurice** [comment]
Is there a possibility to add this to the docs of renovate "reducing noise".
I was unable to figure out how to automerge the PRs and I couldn't find any reference as of how renovate handles PRs that need approval.

**Comment by rarkins** [comment]
Of course. The doc is in the main repo so you can PR it
