### ISSUE TITLE
How to ignore all patch updates

### ISSUE THREAD

**Issue by kevinsimper** [renovatebot/config-help#477]
How to ignore all patch updates? I can't find any option to disregard any patch updates from all packages. I only want Major and Minor. Patch updates for npm are often documentation, [types](https://github.com/copenhagenjs/copenhagenjs.dk/pull/408) or test releases, which does not influence any code that is actually running. And if there is a security issue, there are other tools that will notify about that.

```
{
  "extends": [
    "config:base"
  ],
  "separateMinorPatch": true,
  "patch": {
    // how to ignore all
  }
}
```

I search this repo and the [renovate](https://github.com/renovatebot/renovate) repo and couldn't find a similar issue.

**Comment by rarkins** [comment]
Add `”enabled”: false` within that `patch` object

**Comment by kevinsimper** [comment]
@rarkins Thank you, that worked! 😄
