### ISSUE TITLE
go mod tidy not running

### ISSUE THREAD

**Issue by jmhodges** [renovatebot/config-help#479]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [x] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

Yep.

### What would you like to do?

Have `go mod tidy` run after every update of my lekube codebase. I have it in the config, I thought, but it doesn't seem to be applying. Here's the config: https://github.com/jmhodges/lekube/blob/53ec89ebc9b584c838bc8d06791f7d5b70100bcb/.github/renovate.json

I went off the docs on https://docs.renovatebot.com/configuration-options/ but perhaps they aren't clear about where that `postUpdateOptions` key is supposed to live? It seemed like a top-level key, but there's no examples, and I can't figure it out from context.

**Comment by rarkins** [comment]
What's an example job ID when a go.mod/go.sum was updated, and can you paste the logs from the section where `go` is called to do the updating?

**Comment by jmhodges** [comment]
How do I find the logs for a specific pull request? There's no links in the PRs and there's _lots_ of jobs in the dashboard. For instance, this PR should have done a tidy, but didn't:  https://github.com/jmhodges/lekube/pull/84/files

**Comment by jmhodges** [comment]
(Link for the logs that seem to not have a "search by PR" mechanism: https://app.renovatebot.com/dashboard#github/jmhodges/lekube . Let me know if there's another page I can use to find that info!)

**Comment by jmhodges** [comment]
Arggggh, a top-level config got added but not deleted. PEBCAK

**Comment by jmhodges** [comment]
(I had a .github/renovate.json and a renovate.json and the top-level one was, of course, given priority)
