### ISSUE TITLE
Auto-refresh lock file maintenance PRs

### ISSUE THREAD

**Issue by dword-design** [renovatebot/config-help#482]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [x] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

Hey,

I'm using the lock file maintenance feature of the Renovate App and I haven't found a solution yet to auto-refresh a lock file maintenance PR. I know there is the "If you want to rebase/retry this PR, check this box" checkbox, but it's a bit tedious do do this manually for all repositories.

Thanks already!

**Comment by rarkins** [comment]
This is not supported because it would require us to do a computationally intensive lock file generation ever single run. You’d also be likely to see 10+ commits per day creating lots of work in your CI.

**Comment by dword-design** [comment]
Ah ok I see
