### ISSUE TITLE
Escaping comma in args

### ISSUE THREAD

**Issue by Djaler** [renovatebot/config-help#483]
### Which Renovate are you using? x the right box:

- [x] Renovate Open Source CLI
- [ ] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [ ] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [x] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

I need to use string with comma as an arg in preset. But renovate recognize it as a list of args. How can I escape comma in that case?

**Comment by rarkins** [comment]
It might need an enhancement to support. What’s the field and which string or example string?

**Comment by Djaler** [comment]
We use customized conventional commis specification with ability to use many scopes in commit. And I tried to configure something like `:semanticCommitScope(frontend,deps)`, where `frontend,deps` should be one arg

**Comment by rarkins** [comment]
I don’t think this will work as-is, as our parsing has very simple. I think you’ll need to skip using presets for such fields unfortunately
