### ISSUE TITLE
How to set hourly in my schedule?

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/config-help#485]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [x] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [ ] GitHub.com
- [ ] GitHub Enterprise
- [x] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

Set my schedule to only run hourly. My current schedule configuration:

```json
"schedule": [
    "after 4pm and before 11:59pm every weekday",
    "after 9am and before 11:59pm every weekend"
],
```

Where can I put the `hourly` keyword?

The reason for me doing this is that MRs are creating/updating too quickly (sometimes every 15 minutes), causing me to burn through my GitLab CI minutes.

**Comment by rarkins** [comment]
Renovate doesn't support this concept, and nor does the hosted service. The *service* will schedule jobs hourly, but if webhooks are received that cause Renovate to run (e.g. updates in master to a file it cares about, or merged MRs) then it will run more than once per hour. It will then push changes if it thinks they're required (e.g. if they are conflicted, or if you have configured `rebaseStalePrs=true`).

**Comment by Jamesking56** [comment]
Right OK, I have `rebaseStalePrs` set.

I might turn down the amount of MRs renovate can have open in a repo from 10 -> 5 and see if that calms down the CI usage.

**Comment by Jamesking56** [comment]
@rarkins I've found the source of my high CI minute usage and I've created a bug for it: https://github.com/renovatebot/renovate/issues/5074

**Comment by rarkins** [comment]
Great, let's discuss there instead. We should resolve the churn issue.

**Comment by Jamesking56** [comment]
Thanks @rarkins :+1:
