### ISSUE TITLE
Docker updates to beta version

### ISSUE THREAD

**Issue by Tanuel** [renovatebot/config-help#486]
**What Renovate type are you using?**

self-hosted

**Describe the bug**

The dockerimage got updated to a beta version:
```
- FROM python:3.7.5-alpine
+ FROM python:3.8.0b1-alpine
```

**Did you see anything helpful in debug logs?**

not relevant

**To Reproduce**

1. Create a Docker image `FROM python:3.7.5-alpine`
2. Let renovate update the tag to `python:3.8.0b1-alpine`

**Additional context**

-

**Comment by rarkins** [comment]
You can define a custom [versionScheme](https://docs.renovatebot.com/configuration-options/#versionscheme) for cases when Renovate's default guessing at versions doesn't work. 

This example in the docs solves what you need:

```
{
  "versionScheme": "regex:^(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(?<prerelease>[^.-]+)?(-(?<compatibility>.*))?$"
}
```

**Comment by Tanuel** [comment]
For some reason, renovate will not update to python:3.8.1-alpine

v3.8.0b1 is not even listed in [docker hub](https://hub.docker.com/_/python) anymore.

I tried to rollback to 3.7.5 but it would update to the beta version again and is stuck there.

A different project actually updated from 3.7.5 directly to 3.8.1 so i have no idea what this is about. (using the exact same configuration, but possible different versions of renovate)


```json
renovate.json in project:
{
  "extends": [
    "config:base",
    ":semanticCommitScopeDisabled",
    "docker:enableMajor"
  ],
  "semanticCommitType": "PATCH",
  "semanticCommitScope": null,
  "semanticCommits": true,
  "automerge": true,
  "separateMinorPatch": true,
  "gitLabAutomerge": true,
  "minor": {
    "semanticCommitType": "FEATURE"
  },
  "major": {
    "semanticCommitType": "BREAKING"
  }
}
```

```js
//config.js for renovate bot
module.exports = {
  endpoint: 'internal-gitlab,
  platform: 'gitlab',
  repositories, // get generated and shuffled above
  logFileLevel: 'info',
  logLevel: 'info',
  autodiscover: false,
  onboarding: true,
  separateMultipleMajor: true,
  commitMessagePrefix: "PATCH:",
  semanticCommitScope: null,
  semanticCommits: true,
  rebaseStalePrs: false,
  prCommitsPerRunLimit: 7,
  gitLabAutomerge: true,
  onboardingConfig: {
    extends: ['config:base', ':semanticCommitScopeDisabled', 'docker:enableMajor'],
    prHourlyLimit: 2,
    automerge: true,
    major: {
      automerge: false
    },
  },
  packageRules: [
    {
      "packagePatterns": ["aws-sdk"],
      "schedule": ["before 7am on Monday"],
    }
  ]
}
```

**Comment by rarkins** [comment]
Please see if you can reproduce it in a public repo and then create a new issue to discuss there
