### ISSUE TITLE
Remove subset of packages from group

### ISSUE THREAD

**Issue by stefee** [renovatebot/config-help#489]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [x] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

I have not.

### What would you like to do?

I'd like to remove a specific subset of packages from a wildcard group and have them open their own PRs individually.

So if I set a `groupName` for a set of packages 

e.g.
```
"packagePatterns": ["*"],
"groupName": "deps"
```

and then set `groupName` to `null` for a subset of those packages

e.g.
```
"packageNames": ["webpack"],
"groupName": null
```

Does this remove them from the group?

**Comment by rarkins** [comment]
Yes, that would work. Although you might find it more readable to write a single rule like this:

```
"packagePatterns": ["*"],
"excludePackageNames": ["webpack"],
"groupName": "deps"
```

**Comment by stefee** [comment]
Thanks! In my case I am overriding a shared preset.

**Comment by stefee** [comment]
This worked like a charm. Cheers.
