### ISSUE TITLE
Odd `allowedVersions` Behavior

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovatebot/config-help#49]
I am using the `allowedVersions` feature of Renovate - https://renovatebot.com/docs/configuration-options/#allowedversions

I have the following configuration in my `renovate.json` file - https://github.com/destroyerofbuilds/angular-test/blob/22c89d13a36163f972eee19becaced7a57f9eb35/renovate.json#L4

However, I'm seeing a pull request from Renovate to upgrade `angular` to version 1.7 - https://github.com/destroyerofbuilds/angular-test/pull/1

**Comment by destroyerofbuilds** [comment]
It looks like `allowedVersions` was lost in a refactor 2 days ago - https://github.com/renovateapp/renovate/commit/addf184473687bee0bf9a89df1423a7794534ad8#diff-78baec4409801753437c184edb7285b9L137

**Comment by destroyerofbuilds** [comment]
Is there an alternative to `allowedVersions`, or should I re-file this as a bug/feature request against the main `renovate` repository?

**Comment by rarkins** [comment]
Bug, and thanks for catching it
