### ISSUE TITLE
How to group extra packages with monorepo deps?

### ISSUE THREAD

**Issue by kuangp** [renovatebot/config-help#494]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [x] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

My current renovate config: https://github.com/kuangp/test/pull/1

I'm trying to group together the `@types/jest` package along with the `jest` monorepo packages in the same PR but the expected outcome stated by the onboarding PR description is not producing the result I expect. 

I've tried the following configs: 
```
{
  "packageRules": [
    {
      "extends": "monorepo:jest",
      "packageNames": [
        "@types/jest"
      ],
      "groupName": "jest"
    }
  ]
}
```
```
{
  "packageRules": [
    {
      "extends": "group:jestMonorepo",
      "packageNames": [
        "@types/jest"
      ],
      "groupName": "jest"
    }
  ]
}
```
```
{
  "packageRules": [
    {
      "sourceUrlPrefixes": [
        "https://github.com/facebook/jest"
      ]
      "packageNames": [
        "@types/jest"
      ],
      "groupName": "jest"
    }
  ]
}
```

Renovate shows that I would get 2 PRs, one for `@types/jest` & `jest` and one for `jest-cli` or `jest` & `jest-cli` and `@types/jest`.

I would like to have all these under one PR. Is there some way to specify that in the config that I'm missing?

**Comment by rarkins** [comment]
For reference, here is the original preset we're discussing: https://github.com/renovatebot/presets/blob/cc7f74286b2d9ed7641176be955c88177ecf9671/packages/renovate-config-group/package.json#L514-L522

Instead of duplicating the existing preset, I recommend that you first of all extend either `group:jestMonoRepo` or instead `config:base`.

Then you're just left with the task: how to also include `@types/jest`? This should hopefully do it:

```json
{
  "extends": ["config:base"],
  "packageRules": [{
    "packageNames": ["@types/jest"],
    "groupName": "jest monorepo"
  }]
}
```

Reproduction/success shown here: https://github.com/renovate-tests/test/pull/1

**Comment by kuangp** [comment]
Hi @rarkins,

Thanks for the advice! 
I'm also curious why the configs I attempted did not produce the result I expected? Are those not supported configurations? 
Is it not possible to extend a preset within `packageRules`? Also does this mean it's not possible to override a set `groupName` from a preset?

**Comment by rarkins** [comment]
The problem in all three cases is the same: if you mix `sourceUrlPrefixes` and `packageNames` then it's treated as an AND condition and not OR. i.e. it says "if packages are named X and from source URL Y, then give them group name Z". Instead you were after "if packages are named X or from source URL Y, then give them group name Z". For "or" conditions you need separate packageRules.

**Comment by kuangp** [comment]
Ah, I see. Thank you for the explanation. I was under the impression it would work the same way as `packageNames` + `packagePatterns` Might I recommend including this detail in https://docs.renovatebot.com/configuration-options/#sourceurlprefixes for future users that might make the same assumption.

Thanks again for your help. I appreciate the clarification.
