### ISSUE TITLE
I have configured auto merge but it's not automerging

### ISSUE THREAD

**Issue by MeStrak** [renovatebot/config-help#495]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [x ] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [ x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

I have tried to configure automerge for minor updates on my repository at https://github.com/mestrak/catkin, but the branches don't seem to be merging automatically.

I have a monorepo with frontend and backend in the same repo. Global renovate.json in the root folder, which I have also copied to backend and frontend folders to try to get it to work but it still doesn't work.

Is it possible for somebody to take a look at the config file in my repo please?

Thanks!

**Comment by rarkins** [comment]
More information required

**Comment by MeStrak** [comment]
@rarkins added more info as you left your comment :) I'm on my phone and tapped the wrong button and created the issue before typing anything into it.

**Comment by rarkins** [comment]
Here is why it's blocked from merging:

![image](https://user-images.githubusercontent.com/6311784/72368107-b33d8280-36fd-11ea-8ff2-8e4cbec10cbe.png)

No app can bypass the GitHub branch protection that you have enabled.

However if you add the helper app https://github.com/apps/renovate-approve then it is programmed to do just one thing: instantly approve all of the WhiteSource Renovate app's PRs.

**Comment by MeStrak** [comment]
@rarkins it's obvious now that you've explain it, I should have thought of that.

I've installed renovate-approve - that is an awesome feature, thanks!

Do I need to approve the outstanding unapproved requests or will it pick them up?

Also regarding my renovate.config - do I need to have a copy in each subfolder (frontend/backend), or is it enough at the root level?

**Comment by rarkins** [comment]
You’ll need to manually approve the existing PRs but new ones should get approved. You could try renaming then closing an existing one to test. It should result in a new replacement PR created with approval done. 

You only need renovate config at the root level. It’s not supported at other levels anyway.

**Comment by MeStrak** [comment]
I just approved those ones manually, only 3 of them. All sorted now, I assume the new MRs will be merged automatically and I've also removed the unnecessary config files from the sub folders.

Thanks a lot for your help :)

**Comment by MeStrak** [comment]
@rarkins some things have automerged overnight, but there's a patch which hasn't: https://github.com/MeStrak/catkin/pull/49

I have  ":automergePatch" in my config file so I thought it would work. Something I missed?

**Comment by rarkins** [comment]
The only thing you missed was patience - the PR is less than 30 minutes old. The next time Renovate runs on that repo (scheduled once per hour) it should merge if it's "green".

**Comment by MeStrak** [comment]
Oh thanks, I actually didn't check the time, I only just got up and assumed it was overnight sometime.
