### ISSUE TITLE
[Question] How are overlapping package rules applies

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#497]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [X] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [X] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

Understand if my assumption about how renovate works when package rules overlap is correct.

Here's an example config:

```
{
  "extends": ["config:base"],
  "schedule": ["every tuesday"],
  "stabilityDays": 7,
  "packageRules": [
    {
      "packagePatterns": ["^@acme"],
      "stabilityDays": 0,
      "schedule": ["every monday"]
    },
    {
      "packageNames": ["@acme/boom"],
      "schedule": ["at any time"]
    }
  ]
}
```

Here are the questions:

- What is the `stabilityDays` for package `@acme/boom`? I expect 0, because even though the global one is 7, it is overridden in the first rule, which I would expect to also apply to `acme/boom` because it uses a pattern to match packages
- What is the `schedule` for package `@acme/boom`? I would expect `at any time` because it overrides the root one and the one set on the first rule, because this one has higher specificity

Is my understanding correct? In general I'd like to understand better how overlapping rules work.

**Comment by rarkins** [comment]
Rules are applied in the array order they're defined in. Each rule is applied if it matches. I believe the answers should be as you expect.

**Comment by simoneb** [comment]
Thanks for your answer @rarkins . Does that mean that if the two rules were inverted the behavior would be different? Or, in other words, it's not specificity that counts but order?

So, if the two rules were in the opposite order I would get for the above questions:

- `stabilityDays: 0`, as before
- `schedule: ["every monday"]` because the `^@acme` pattern rule would apply later and override the `at any time` settings of the `@acme/boom` rule?

**Comment by rarkins** [comment]
Yes, order counts, not specificity. We used to have a mix but it was very confusing.

**Comment by simoneb** [comment]
Awesome, thanks for the clarification. I don't remember coming across this in the docs (though I may have missed it). If it's not there, I suggest you document it.

**Comment by rarkins** [comment]
There is a mention of this in the [docs for `packageRules`](https://docs.renovatebot.com/configuration-options/#packagerules):

![image](https://user-images.githubusercontent.com/6311784/72432540-96ee2400-3797-11ea-917d-8a66cf89fc10.png)

Also it would be an appropriate to share this:

![image](https://user-images.githubusercontent.com/6311784/72432606-c13fe180-3797-11ea-9086-10a3928b432e.png)

**Comment by simoneb** [comment]
I missed that part of the docs. I guess it explains it already :)
