### ISSUE TITLE
authenticate to private npm registry with encrypted token/password

### ISSUE THREAD

**Issue by sumanapotturu** [renovatebot/config-help#498]
### Which Renovate are you using? x the right box:
- [X] WhiteSource Renovate App

### Which platform are you using? x the right box:
- [X] GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant
 Logs do not provide much information on authentication failures to the private registry. 

```
{
  "cmd": "node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js",
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "bash -l -c \"node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\"",
    "stdout": "yarn install v1.21.1\ninfo No lockfile found.\n[1/4] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n",
    "stderr": "error Couldn't find package \"<PRIVATE PKG>\" on the \"npm\" registry.\n",
    "message": "Command failed: bash -l -c \"node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\"\nerror Couldn't find package \"<PRIVATE PKG>\" on the \"npm\" registry.\n",
    "stack": "Error: Command failed: bash -l -c \"node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\"\nerror Couldn't find package \"<PRIVATE PKG>\" on the \"npm\" registry.\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  },
  "type": "yarn"
}
```

### What would you like to do?
Authenticate to private npm module - artifactory using encrypted token/password.

Working Config: I am unable to encrypt the token because the token is too long. 
```
{
  "npmrc": "always-auth=true\n//<private-registry-url>/:_authToken=<token>"
}
```

Can I use host rules to authenticate to Artifactory endpoint. I tried the below config but this didn't seem to work. 
```
{
  "hostRules": [
    {
      "baseUrl": "<private-registry-url>",
      "username": "<username>",,
      "encrypted": {
         "password": "<encrypted password>"
      }
    }
  ]
}
```

**Comment by rarkins** [comment]
Unfortunately with npm there needs to be an `.npmrc` instead of hostRules. We don't yet have `hostRules` -> `.npmrc` conversion concepts.

Were you trying to encrypt only your **token** or instead encrypting the full `.npmrc` including token?

**Comment by sumanapotturu** [comment]
I am encrypting only the token. But with artifactroy, access tokens size is over 800+ characters

**Comment by rarkins** [comment]
Renovate has quite a few artifactory users who I'm assuming have managed this somehow. I'm not a user directly so don't have first hand knowledge. For my info, can you tell me if this is a hosted/SaaS artifactory, or your own self-hosted instance?

Can you check if there are any ways to generate shorter token lengths, or perhaps is it possible to supply username/password instead if the password is shorter? Unfortunately this is a limit of our encryption
