### ISSUE TITLE
Number of PRs created are less than what it should be?

### ISSUE THREAD

**Issue by ahmedelgabri** [renovatebot/config-help#50]
Is there is any limit on the number of PRs created by default?

There are lots of dependencies that are outdated but Renovate didn't create PRs for them, any reason for this?

Here is `renovate.json`

```json
{
  "extends": ["config:base", ":pinAllExceptPeerDependencies", "schedule:nonOfficeHours"],
  "enabledManagers": ["npm"],
  "labels": ["upgrade", "bot"],
  "timezone": "Europe/Amsterdam",
  "copyLocalLibs": true,
  "ignoreDeps": ["gulp-sass", "node-sass", "sass-loader", "query-string", "coffee-script", "coffee-loader"]
}
```

**Comment by rarkins** [comment]
The `config:base` preset comes with limits of maximum 2 new PRs per hour and maximum 20 open PRs at a time. Would that explain it?

**Comment by ahmedelgabri** [comment]
Yes, makes sense. Thanks 👍

**Comment by rarkins** [comment]
For yourself or anyone else finding this in future, those two settings are `prHourlyLimit` and `prConcurrentLimit`. PRs are prioritised in this order too: pin, patch, minor, major. i.e. to try to make the "easy" ones first.
