### ISSUE TITLE
Configure Renovate with self hosted GitLab where repository lives behind gateway

### ISSUE THREAD

**Issue by reppiee** [renovatebot/config-help#501]
### Which Renovate are you using? x the right box:

- [x] Renovate Open Source CLI
- [ ] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [ ] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [x] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant
```
968 latest: Pulling from renovate/renovate
969 Digest: sha256:fecc03761b06d41ecb92e91661ef7a78b0afcea0593eeca581d5d1812fb3dd35
970 Status: Image is up to date for renovate/renovate:latest
971 docker.io/renovate/renovate:latest
972 $ docker run renovate/renovate:latest --platform gitlab --timezone Europe/London --token $CI_BOT_TOKEN --autodiscover --log-level debug --print-config true --dry-run true --endpoint https://gitlab-internal.example.com/api/v4
973 DEBUG: File config
974        "config": {}
975 DEBUG: CLI config
976        "config": {
977          "dryRun": true,
978          "printConfig": true,
979          "logLevel": "debug",
980          "timezone": "Europe/London",
981          "platform": "gitlab",
982          "endpoint": "https://gitlab-internal.example.com/api/v4",
983          "token": "***********",
984          "autodiscover": true
985        }
986 DEBUG: Env config
987        "config": {"hostRules": []}
988 DEBUG: Combined config
989        "config": {
990          "hostRules": [],
991          "dryRun": true,
992          "printConfig": true,
993          "logLevel": "debug",
994          "timezone": "Europe/London",
995          "platform": "gitlab",
996          "endpoint": "https://gitlab-internal.example.com/api/v4",
997          "token": "***********",
998          "autodiscover": true
999        }
1000 DEBUG: Adding trailing slash to endpoint
1001  INFO: Using platform gitAuthor: BotUser <bot@example.com>
1002 DEBUG: Using baseDir: /tmp/renovate
1003 DEBUG: Using cacheDir: /tmp/renovate/cache
1004 DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
1005  INFO: Autodiscovering GitLab repositories
1006  INFO: Discovered 40 project(s)
1007  INFO: Discovered 40 repositories
1008 DEBUG: Limits.init enter method
1009 DEBUG: Limits.init prCommitsPerRunLimit processing
1010 DEBUG: Limits.init prCommitsPerRunLimit variable is not set. Ignoring prCommitsPerRunLimit
1011  INFO: Renovating repository (repository=example/group/gitlab-artifacts)
1012        "renovateVersion": "19.102.2"
1013 DEBUG: Using localDir: /tmp/renovate/repos/gitlab/example/group/gitlab-artifacts (repository=example/group/gitlab-artifacts)
1014 DEBUG: example/group/gitlab-artifacts default branch = master (repository=example/group/gitlab-artifacts)
1015 DEBUG: Bot email=bot@example.com (repository=example/group/gitlab-artifacts)
1016 DEBUG: Enabling Git FS (repository=example/group/gitlab-artifacts)
1017 DEBUG: example/group/gitlab-artifacts http URL = https://gitlab.example.com/example/group/gitlab-artifacts.git (repository=example/group/gitlab-artifacts)
1018  INFO: Initialising git repository into /tmp/renovate/repos/gitlab/example/group/gitlab-artifacts (repository=example/group/gitlab-artifacts)
1019 DEBUG: git clone error (repository=example/group/gitlab-artifacts)
1020        "err": {
1021          "message": "Cloning into '.'...\nfatal: unable to access 'https://**redacted**@gitlab.example.com/example/group/gitlab-artifacts.git/': Failed to connect to gitlab.example.com port 443: Connection timed out\n",
1022          "stack": "Error: Cloning into '.'...\nfatal: unable to access 'https://**redacted**@gitlab.example.com/example/group/gitlab-artifacts.git/': Failed to connect to gitlab.example.com port 443: Connection timed out\n\n    at toError (/usr/src/app/node_modules/simple-git/promise.js:90:14)\n    at /usr/src/app/node_modules/simple-git/promise.js:61:36\n    at Git.<anonymous> (/usr/src/app/node_modules/simple-git/src/git.js:214:18)\n    at Function.Git.fail (/usr/src/app/node_modules/simple-git/src/git.js:1474:18)\n    at fail (/usr/src/app/node_modules/simple-git/src/git.js:1432:20)\n    at /usr/src/app/node_modules/simple-git/src/git.js:1441:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
1023        }
1024 DEBUG: Caught initRepo error (repository=example/group/gitlab-artifacts)
1025        "err": {
1026          "message": "platform-failure",
1027          "stack": "Error: platform-failure\n    at Storage.initRepo (/usr/src/app/dist/platform/git/storage.js:138:23)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
1028        }
1029  INFO: Unknown GitLab initRepo error (repository=example/group/gitlab-artifacts)
1030        "err": {
1031          "message": "platform-failure",
1032          "stack": "Error: platform-failure\n    at Storage.initRepo (/usr/src/app/dist/platform/git/storage.js:138:23)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
1033        }
1034  INFO: Platform error - skipping (repository=example/group/gitlab-artifacts)
1035  INFO: Finished repository (repository=example/group/gitlab-artifacts)
```

### What would you like to do?
I want to set up a GitLab project with renovate that scans our repositories on a schedule and creates merge requests for package updates.

### Question
Our GitLab setup is somewhat strange. The public URL's used to clone repositories are different than the ones GitLab uses internally. For example: I would clone using `git clone git@gitlab.example.com` whereas the CI would use `git clone git@gitlab-internal.example.com`.

When running renovate, we specify the endpoint as `gitlab-internal.example.com`, but during execution it tries to clone the repositories using `gitlab.example.com`.

We realise this is an oddity in our setup, but is there a way to somehow override the git clone URL with our internal URL?

**Comment by rarkins** [comment]
Please include debug logs

**Comment by reppiee** [comment]
Okay - Added logs to the original comment.

**Comment by rarkins** [comment]
Here's the relevant code: https://github.com/renovatebot/renovate/blob/1ef2fc2af0902b79cc5ff257898fc612165b7173/lib/platform/gitlab/index.ts#L221-L224

It seems like `http_url_to_repo` is set to http://gitlab.example.com

If you manually curl https://gitlab-internal.example.com/example/group/gitlab-artifacts, does the response include the "gitlab-internal.example.com" URL anywhere at all, or only the gitlab.example.com?

**Comment by reppiee** [comment]
Yeah the `http_url_to_repo` is set to gitlab.example.com, unfortunately the response does not contain the gitlab-internal.example.com URL anywhere.

Changing the `http_url_to_repo` for that project might be possible, but might lead to other functions not working correctly anymore as they currently rely on that being `gitlab.example.com`. 

Looking at the relevant code, it's not possible to override the repository URL it uses (except by changing the `http_url_to_repo` that the API returns).

Would it be an idea to add options to override that URL through `hostRules`?

**Comment by rarkins** [comment]
Can you try running renovate@19.103.3 and setting GITLAB_IGNORE_REPO_URL=yes in env? This is an experiment to see if ignoring that http_url_to_repo response works.

**Comment by reppiee** [comment]
Thanks for looking into it!

I've currently defined the job in our `gitlab-ci.yml` as such:
```
renovate:
  image: 
    name: renovate/renovate:19.103.3
    entrypoint: [""]
  before_script:
    - cp config.js /usr/src/app/config.js
    - export RENOVATE_TOKEN=$BOT_TOKEN
    - export GITLAB_IGNORE_REPO_URL=yes
  script:
    - node /usr/src/app/dist/renovate.js $(cat repositories.txt | xargs)
```

Would it be possible to push 19.103.3 to docker hub? If not, I'll look into how we can run renovate using that specific branch and report back once thats up and running.

**Comment by rarkins** [comment]
It will auto-build soon. You may be able to use `renovate/renovate:19.103.3-slim` just for the purpose of this testing. It usually builds much faster.

**Comment by reppiee** [comment]
Ah cool, thanks! Yeah it was available now. Got a GitLab initRepo error, which looks similar to the one I got originally, though I don't see any reference to the repository URL it was trying to use.

```
INFO: Using platform gitAuthor: BotUser <bot@example.com>
INFO: Renovating repository (repository=top_group%2fgroup%2fgitlab_artifacts)
      "renovateVersion": "19.103.3"
INFO: Initialising git repository into /tmp/renovate/repos/gitlab/top_group%2fgroup%2fgitlab_artifacts (repository=top_group%2fgroup%2fgitlab_artifacts)
INFO: Unknown GitLab initRepo error (repository=top_group%2fgroup%2fgitlab_artifacts)
      "err": {
        "message": "platform-failure",
        "stack": "Error: platform-failure\n    at Storage.initRepo (/usr/src/app/dist/platform/git/storage.js:138:23)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
      }
INFO: Platform error - skipping (repository=top_group%2fgroup%2fgitlab_artifacts)
INFO: Finished repository (repository=top_group%2fgroup%2fgitlab_artifacts)
INFO: Renovate finished
```

With this job setup:
```
renovate:
  image: 
    name: renovate/renovate:19.103.3-slim
    entrypoint: [""]
  before_script:
    - cp config.js /usr/src/app/config.js
    - export RENOVATE_TOKEN=$BOT_TOKEN
    - export GITLAB_IGNORE_REPO_URL=yes
  script:
    - node /usr/src/app/dist/renovate.js $(cat repositories.txt | xargs)
```

And the content of repositories.txt is:
```
top_group%2fgroup%2fgitlab_artifacts
```

**Comment by rarkins** [comment]
Please log at DEBUG level and paste in the result

```
- export LOG_LEVEL=debug
```

**Comment by reppiee** [comment]
Ah! It does use `gitlab-internal.example.com` now. Seems to trigger a redirect, which is a problem on our end that we can probably fix with a different authentication strategy.

```
message": "Cloning into '.'...\nfatal: unable to update url base from redirection:\n  asked for: https://**redacted**@gitlab-internal.example.com/top_group%2fgroup%2fgitlab_artifacts.git/info/refs?service=git-upload-pack\n redirect: https://example.okta.com/login/login.htm
```

**Comment by Willianvdv** [comment]
> Ah! It does use `gitlab-internal.example.com` now. Seems to trigger a redirect, which is a problem on our end that we can probably fix with a different authentication strategy.
> 
> ```
> message": "Cloning into '.'...\nfatal: unable to update url base from redirection:\n  asked for: https://**redacted**@gitlab-internal.example.com/top_group%2fgroup%2fgitlab_artifacts.git/info/refs?service=git-upload-pack\n redirect: https://example.okta.com/login/login.htm
> ```

It turned out this error was caused by a typo in our `repositorities.txt`, instead of `/` we used `%2f`. The error page redirected to redirect to our public instance which can't be reached from this machine resulting in the error @reppiee posted.

Long story short; it works now!

**Comment by rarkins** [comment]
@Willianvdv so you still need `GITLAB_IGNORE_REPO_URL=yes`, right?

**Comment by Willianvdv** [comment]
> @Willianvdv so you still need `GITLAB_IGNORE_REPO_URL=yes`, right?

yes
