### ISSUE TITLE
Artifact update problem since 20 Jan 2020

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#502]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [X] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [X] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

I scanned some of the job logs (Renovate doesn't include the job ID in the PR so it's hard to figure out which job it is that generated the error), bu I couldn't find anything relevant. A possibly Relevant one is 133438468

### What would you like to do?

I'm getting this message:

![image](https://user-images.githubusercontent.com/20181/72793191-719b6300-3c3a-11ea-9df6-c6de6e1b389a.png)

And the package-lock.json file is not updated, which it should.

**Comment by rarkins** [comment]
Could you tick the rebase/retry box and check if it succeeds? I believe this was as temporary problem but await your confirmation

**Comment by simoneb** [comment]
Trying, and actually found something relevant in the job logs of another repo. But I guess you already know what's going on. I'll let you know what happens after rebasing.

**Comment by rarkins** [comment]
And BTW we are working on having job IDs embedded in PRs to make it easier to troubleshoot in future

**Comment by simoneb** [comment]
> And BTW we are working on having job IDs embedded in PRs to make it easier to troubleshoot in future

That would be great!

Meanwhile, rebasing seems to do the trick. Thanks. Closing
