### ISSUE TITLE
Correct name of the renovate-approve BOT in CODEOWNERS

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#504]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [X] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [X] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

As documented [here](https://github.com/apps/renovate-approve/), we've been using `app/renovate-approve` to identify the approve BOT in our CODEOWNERS files, but after a conversion with GitHub support we've been told that the right name is the one prefixed with `@`, so `@app/renovate-approve`. If you think that's correct, I think the documentation should be updated to reflect that.

**Comment by rarkins** [comment]
Sure, if it works and also it’s recommended by GitHub then let’s update the docs

**Comment by simoneb** [comment]
Let me confirm that first, we've just done the change in our CODEOWNERS files but haven't had a chance to test it yet.
