### ISSUE TITLE
How to force a branch/PR creation ahead of scheduled update?

### ISSUE THREAD

**Issue by rfgamaral** [renovatebot/config-help#509]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I have setup Renovate to bump my dependencies every Monday but I'm now looking for a way to trigger the branch/PR creation without a) waiting for next Monday or b) change `renovate.json` schedule option to trigger updates "now" (and then change that back).

I'm coming from dependabot, which had a "bump now" button on the dashboard. Is there something like this in Renovate? If not, how can I workaround this situation?

**Comment by rarkins** [comment]
@rfgamaral I suggest adding `"masterIssue': true` to your config. This will open up a "master issue" within your repo that lists all PRs - opened, closed, pending. For pending ones (e.g. due to scheduling) you have the option to tick a checkbox to force the PR to open ahead of schedule.

**Comment by rfgamaral** [comment]
This solved it, thank you 🙇
