### ISSUE TITLE
Automerge is disabled even though automerge presets are used

### ISSUE THREAD

**Issue by SevenOutman** [renovatebot/config-help#51]
Hi team, first off thanks for the great tool!

I ran into a problem that my config uses `:automergeMinor` and `:automergeBranchPush` presets, but auto merge feature is simply disabled.

Here's my [`renovate.json`](https://github.com/SevenOutman/vue-aplayer/blob/develop/renovate.json) config:
```json
{
  "extends": [
    "config:js-lib",
    ":autodetectPinVersions",
    ":automergeMinor",
    ":automergeBranchPush",
    "schedule:daily"
  ]
}
```

Here's the [configuration PR](https://github.com/SevenOutman/vue-aplayer/pull/58), in which the bot says
```
Disable automerging feature - wait for humans to merge all PRs
```

And here is the [first pin PR](https://github.com/SevenOutman/vue-aplayer/pull/60), which I believe should have been a push.

**Comment by rarkins** [comment]
The configuration PR unfortunately describes things incompletely - it's basically just reading through the list of presets. so if you have one preset that contradicts or overrides another then you see both messages. In this case the disabled one is coming from the `config:js-lib` preset but is then overridden by `automergeMinor`. So let's ignore that for now.

"pin" PRs are considered a special type of PR and not actually described by "minor". i.e. we classify javascript PRs as major, minor, patch, or pin. So I think this is the reason why you're not seeing this pin one be automerged. 

However, it seems logical to me that if you are willing to automerge minor updates (e.g. 1.1.0 -> 1.2.0) then you would also be happy/expecting to automerge pin PRs (e.g. ^1.1.0 -> 1.2.0). I will update the `automergeMinor` preset (source is at https://github.com/renovatebot/presets/blob/f00353b32cef2e317c4339be7d8ea3d19f93a946/packages/renovate-config-default/package.json#L216) to explicitly include pin. If you don't mind waiting to watch then the bot should hopefully then automerge the PR.

**Comment by SevenOutman** [comment]
@rarkins Thanks for your reply. Looking forword to the updates. :)

**Comment by rarkins** [comment]
Actually I see that you merged the pin already, so we won't be able to observe that. Any future pin PRs with same config should be automerged. I'll close this for now, please reopen if you find that you are not seeing automerges for other PRs.

Notes:
1. You have daily schedule set, so Renovate will create branches only on that schedule
2. If GitHub reports any status checks failed for the branch then you will see PR raised instead
