### ISSUE TITLE
Why isn't Renovate bumping monorepo dependencies to the same latest version?

### ISSUE THREAD

**Issue by rfgamaral** [renovatebot/config-help#510]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

Renovate created https://github.com/rfgamaral/eslint-config-typescript-unified/pull/75 pull request for me based on this configuration:

```json
{
  "extends": [
    "config:base",
    ":enableVulnerabilityAlertsWithLabel(security)",
    ":label(dependencies)",
    ":masterIssue",
    ":prConcurrentLimit10",
    ":prHourlyLimit4",
    ":timezone(Europe/Lisbon)",
    "schedule:earlyMondays"
  ],
  "postUpdateOptions": [
    "yarnDedupeHighest"
  ]
}
```

However, I don't understand why this is happening:

![image](https://user-images.githubusercontent.com/96476/73435224-266f0780-4340-11ea-8d97-c8f07ec519ca.png)

I mean, one dependency is being bumped to `8.3.5`, another to `8.3.4` and both should be bumped to `8.3.5`, the latest for both packages.

Am I missing something?

**Comment by rarkins** [comment]
8.3.5 wasn’t published for the conventional config package: https://www.npmjs.com/package/@commitlint/config-conventional

**Comment by rfgamaral** [comment]
Hum, good point. Thanks.
