### ISSUE TITLE
Multiple base branches on a bitbucket server results in updates to a branch being ignored

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/config-help#512]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

Yes - Not relavant

### What would you like to do?

Run renovate on two branches on the same repo. I'm mostly opening this as I'm tempted to edit `branchName` and the documentation says:
```
    You are hopefully mistaken, and there's a better approach you should use, so ask here or
    You have a use case we didn't anticipate and we should have a feature request from you to add it to the project
```
So hopefully I'm mistaken.

Given a config with `baseBranches: ['master', 'next']` I'm finding that renovate creates a branch in master (e.g. `renovate/highlight.js-9.x`) but then when it goes to next, it tries to recreate the same branch and then skips it because the branch exists but targeting a different base branch. 

This also happens on a partner's team where every sprint they change their base branch (e.g. `r/week#`). So when the weeks change, any existing PRs block the new prs on the next week's branch from being created.

Hopefully I'm wrong and something weird is just up with our setup.

**Comment by rarkins** [comment]
When base branches are configured, you should see Renovate extending the branch prefix to be like `renovate/master-` and `renovate/next-`. The logs here are relevant - please capture them at debug level and then search for any mention of "baseBranch" in particular.
