### ISSUE TITLE
Can "commitMessageXXX" use backtick/quote?

### ISSUE THREAD

**Issue by SnO2WMaN** [renovatebot/config-help#513]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I use Renovate for personal development and write my commit message in my native language, Japanese.

On GitHub, the part enclosed by the backquote of the commit message is highlighted and displayed, so I am trying to use this in the commit message by Renovate Bot ...

Excerpt of my configuration file.
```json
{
  "commitMessage": "{{commitMessagePrefix}} {{commitMessageTopic}}を{{commitMessageExtra}}に{{commitMessageAction}}",
  "commitMessagePrefix": "⬆️",
  "commitMessageAction": "更新",
  "commitMessageTopic": "`{{depName}}`",
  "commitMessageExtra": "{{#if isMajor}}v{{{newMajor}}}{{else}}{{#if isSingleVersion}}v{{{toVersion}}}{{else}}{{{newValue}}}{{/if}}{{/if}}",
}
```

Actual output commit message.
```
⬆️ &#x60;eslint-plugin-unicorn&#x60;をv16に更新
```

Expected output commit message
```
⬆️ `eslint-plugin-unicorn`をv16に更新
```

This can be fixed manually on GitHub, but is there any way?

**Comment by rarkins** [comment]
If it's allowed, then we can try to let it pass through. I'm actually not sure where/why it is being translated. Can you reproduce it in a simple public repository I can clone to test?

**Comment by SnO2WMaN** [comment]
I'm sorry, I've fixed it manually, and I'll get another pull request in the future, so I'll post it here at that time.

**Comment by SnO2WMaN** [comment]
https://github.com/SnO2WMaN/zihanki/pull/6

Screenshot
![image](https://user-images.githubusercontent.com/15155608/74105530-21ad1d80-4ba2-11ea-899c-76bcbca6ab82.png)

**Comment by rarkins** [comment]
Unfortunately that doesn't quality as a reproduction because the inclusion of commercial Fort Awesome packages means I can't fork and run Renovate against it successfully. Please isolate the minimum necessary code into a new repo that can be forked and tested against.
