### ISSUE TITLE
Renovate recreating PR's for closed custom groups even when none of the modules have been updated.

### ISSUE THREAD

**Issue by dylang** [renovatebot/config-help#515]
**What Renovate type are you using?**

Self-hosted v19.119.0

**Describe the bug**

When we close PR for upgrades for a custom group, Renovate recreates a new PR with the same dependency updates. 

My expectation is that it would not create a new PR unless one of the dependencies in that group had a new version compared to when I last closed it.

**Did you see anything helpful in debug logs?**

https://gist.github.com/dylang/eb9e1b2f7d6e8cbf93eb5d9759500f8f

**To Reproduce**

I'm currently experiencing this with a custom group. I'm trying to hold off on Jest 25. The monorepo `jest` group doesn't include all of the Jest-related packages we rely on.

```json
{
  "$schema": "http://json.schemastore.org/renovate",
  "extends": [
    "config:base",
    ":rebaseStalePrs",
    ":semanticCommits",
    ":automergeAll",
    ":maintainLockFilesWeekly",
    ":prHourlyLimitNone",
    "schedule:nonOfficeHours"
  ],
  "timezone": "America/New_York",
  "commitMessage": "{{commitMessagePrefix}} NGR-2825 - {{commitMessageAction}} {{commitMessageTopic}} {{commitMessageExtra}} {{commitMessageSuffix}}",
  "postUpdateOptions": ["yarnDedupeFewer"],
  "updateNotScheduled": false,
  "ignoreDeps": [ "puppeteer", "@types/puppeteer", "@types/ejs", "d3", "@types/react-transition-group" ],
  "lockFileMaintenance": {
    "enabled": true,
    "schedule": [
      "every weekend"
    ]
  },
  "packageRules": [
    {
      "groupName": "Types",
      "packagePatterns": ["^@types/"]
    },
    {
      "groupName": "Monthly Updates",
      "packageNames": ["caniuse-lite", "aws-sdk"],
      "extends": ["schedule:monthly"]
    },
    {
      "groupName": "Jest",
      "packageNames": ["jest", "@types/jest", "ts-jest", "babel-jest", "jest-circus", "jest-jasmine2"]
    }
  ]
}
```

**Additional context**

What's up with "Updated 155 lock files"?

**Comment by ViceIce** [comment]
Use following `packageRule` to add more packages to jest monorepo. You only have to add package names, which aren't already included
```json
{
  "packageRules": [
    {
      "groupName": "jest monorepo",
      "packageNames": ["@types/jest", "ts-jest", "jest-circus", "jest-jasmine2"]
    }
  ]
}
```

we are using it too:
https://github.com/renovatebot/renovate/blob/master/renovate.json#L50-L53

**Comment by ViceIce** [comment]
Also a group name should not match a package name, so use `jest packages` or `jest monorepo` ...

**Comment by dylang** [comment]
I'll try renaming the `groupName` - I didn't realize it couldn't overlap a package name.

Meanwhile, this is for @rarkins question above:
<img width="745" alt="Screen Shot 2020-02-05 at 11 37 14 AM" src="https://user-images.githubusercontent.com/51505/73861977-e0b4b200-480b-11ea-9f76-878fc6009567.png">

**Comment by rarkins** [comment]
Strange, I would have expected it to add `to v25` into the PR title. You might want to consider using Renovate's "master issue" for major updates. We do that in the main Renovate repo to hold them back by default and open only on demand.
