### ISSUE TITLE
[Question] Rule(s) for detecting unusual versioning patterns

### ISSUE THREAD

**Issue by gmariotti** [renovatebot/config-help#516]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

Not yet

### What would you like to do?

The [SonarQube Gradle Plugin](https://github.com/SonarSource/sonar-scanner-gradle/releases) uses a strange versioning scheme that, apparently, does not create any problem for renovate when the plugin is used in the `plugins {}` block but it does when it is used in the `dependencies {}`. For example, the latest plugin version is `2.8` with the previous version being `2.8.0.1969`. With the plugin set in the `dependencies` block, renovate opened a MR for a patch upgrade from `2.8` -> `2.8.0.1969`. Any idea how to filter out this kind of update?

**Comment by rarkins** [comment]
According to Maven versioning, `2.8.0.1969` is more recent than `2.8`, but if you close the MR, it should be ignored forever.

**Comment by gmariotti** [comment]
I'm actually surprised that I didn't get that update request for sonarqube in the `plugin` block. Is there any way to filter out this kind of version?

**Comment by ViceIce** [comment]
Currently there is no options to filter, but you can try to use the regex versioning scheme for this.

**Comment by rarkins** [comment]
There's also an `allowedVersions` field in `packageRules`, but I'm not sure you want to manually add a rule for every bad version of every package that numbers incorrectly.

**Comment by gmariotti** [comment]
Thanks, I'll probably end up with a regex. Hopefully, sonarqube is the only one with this problem
