### ISSUE TITLE
How to have PR of dependency with new peerDependencies install those dependencies?

### ISSUE THREAD

**Issue by voxpelli** [renovatebot/config-help#52]
See eg. this PR: https://github.com/voxpelli/node-micropub-express/pull/26

It updates some eslint configs and the configs in those new major version require some new eslint plugins, but as the PR only adds the new major versions, and not their new additional requirement, the tests of course fail and merging the PR would result in a broken `master`.

How would one go about solving this?

**Comment by rarkins** [comment]
Do you mean that additional lines/dependencies need to be added to your `package.json` to solve this?

**Comment by voxpelli** [comment]
@rarkins Yes, version 8 of `eslint-config-standard` added two new peer dependencies:

`eslint-plugin-node` in https://github.com/standard/eslint-config-standard/commit/62fd746aabf46137da770ea6542446940a585a29#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
`eslint-plugin-import` in https://github.com/standard/eslint-config-standard/commit/b174d83f4313232a10b09dba2265e002dcffaaa6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

And the Travis CI job fails as it tries to run the linting using plugins that are not there: https://travis-ci.org/voxpelli/node-micropub-express/builds/388885714
