### ISSUE TITLE
Unable to go get private repo even with hostRules

### ISSUE THREAD

**Issue by mimol91** [renovatebot/config-help#521]
**What Renovate type are you using?**
Self hosted (k8s)+ Github

**Describe the bug**
Unable to fetch private github go-modules

go.mod include some private go-modules. 

**Additional context**
I can see that logic to fetch private go-mod using Github token is available at 
https://github.com/renovatebot/renovate/blob/52a7519f3419210bed6269a066eb3f9ca5035211/lib/manager/gomod/artifacts.ts#L23

When I am trying to set binarySource to docker (and running slim image) I got error

` INFO: Failed to update go.sum (repository=my-repo/portfolio-service, branch=renovate/github.com-spf13-viper-1.x)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "docker pull renovate/go",
         "stdout": "Using default tag: latest\n",
         "stderr": "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n",
         "message": "Command failed: docker pull renovate/go\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n",
         "stack": "Error: Command failed: docker pull renovate/go\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\n    at ChildProcess.exithandler (child_process.js:295:12)\n    at ChildProcess.emit (events.js:210:5)\n    at ChildProcess.EventEmitter.emit (domain.js:476:20)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)"
       }
`

**Comment by rarkins** [comment]
It looks like you configured Renovate to use binarySource=docker but did not provide it a Docker socket in order to be able to do that.

**Comment by mimol91** [comment]
I am using kubernetes, its already 'in docker', Is it possible to find some workaround with `binarySource: auto`?

**Comment by ViceIce** [comment]
You need to tell renovate where the docker daemon lives.

**Comment by mimol91** [comment]
I cant, as renovate is running as container, and I cant install docker w/o modifying renovate image

**Comment by ViceIce** [comment]
you can map the host socket

**Comment by ViceIce** [comment]
or you have to use the full image

or you take the slim image as base  and add go yourself

**Comment by mimol91** [comment]
yeah, you are right however I would like to not mount host socket.

It's fine to use full image, however `preCommand` wont be run :(

**Comment by rarkins** [comment]
> Is it possible to add `GOSUMDB` env?

You can try adding it just like any other ENV in the container. The proxy/DB are disabled by default: https://github.com/renovatebot/renovate/blob/8e7eec636207cb30f37eeddff488c7a8db1684cc/Dockerfile#L125

**Comment by mimol91** [comment]
https://github.com/renovatebot/renovate/blob/52a7519f3419210bed6269a066eb3f9ca5035211/lib/manager/gomod/artifacts.ts#L57
Seems it wont be picked ?

**Comment by rarkins** [comment]
> [renovatebot/renovate:lib/manager/gomod/artifacts.ts@`52a7519`#L57](https://github.com/renovatebot/renovate/blob/52a7519f3419210bed6269a066eb3f9ca5035211/lib/manager/gomod/artifacts.ts#L57)
> Seems it wont be picked ?

Can you explain more about what you are trying to and what you mean by this?

**Comment by mimol91** [comment]
I am using go lang with `go mod` as package dep. 
Some of dependencies are private (hosted on github), so to fetch them I need to use ssh key / token

Go mod allows to generate go.sum file with package checksum


Renovate bot throws an error while trying to generate 'artefact' (go.sum file)

```
INFO: Failed to update go.sum (repository=my-repo/portfolio-service, branch=renovate/github.com-spf13-viper-1.x)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "go get -d ./...",
         "stdout": "",
         "stderr": "go: github.com/secret-organization/go-lib@v1.1.4-0.20200129141956-49b36d5e2539: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/87c5639d241c62d0a3b766453a0cc5bf4ce6ab7fb6102d919b42cc26d97bd455: exit status 128:\n\tfatal: could not read Username for 'https://github.com': terminal prompts disabled\n",
         "message": "Command failed: go get -d ./...\ngo: github.com/secret-organization/go-lib@v1.1.4-0.20200129141956-49b36d5e2539: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/87c5639d241c62d0a3b766453a0cc5bf4ce6ab7fb6102d919b42cc26d97bd455: exit status 128:\n\tfatal: could not read Username for 'https://github.com': terminal prompts disabled\n",
         "stack": "Error: Command failed: go get -d ./...\ngo: github.com/secret-organization/go-lib@v1.1.4-0.20200129141956-49b36d5e2539: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/87c5639d241c62d0a3b766453a0cc5bf4ce6ab7fb6102d919b42cc26d97bd455: exit status 128:\n\tfatal: could not read Username for 'https://github.com': terminal prompts disabled\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       }
```

One way to 'avoid' this problem is to set `GOSUMDB=off `

**Comment by rarkins** [comment]
> Some of dependencies are private (hosted on github),

Just to clarify: You're running against a self-hosted GitHub Enterprise, but these private dependencies are on github.com, right?

> so to fetch them I need to use ssh key / token

Do you need both, or either?

> One way to 'avoid' this problem is to set `GOSUMDB=off` (Because private repo won't be in go public checksum DB)

I'm not familiar with exactly how go is working in this case, but should be off already, according to our Dockerfile. Do you think that's not the case?

**Comment by mimol91** [comment]
> Just to clarify: You're running against a self-hosted GitHub Enterprise, but these private dependencies are on github.com, right?

Correct.

> Do you need both, or either?

Either, in case of ssh, i can mount keys, but I will need to execute
` echo -e '[url "ssh://git@github.com/my-repo"]\n        insteadOf = https://github.com/my-repo' >> ~/.gitconfig`

>I'm not familiar with exactly how go is working in this case, but should be off already, according to our Dockerfile. Do you think that's not the case?

I've run it via kubernetes job and it didn't work.
I will try to run it locally tomorrow and confirm it

Thanks for great-support

**Comment by ViceIce** [comment]
You can mount an external gitconfig with your changes to `/home/ubuntu/.gitconfig`.

**Comment by rarkins** [comment]
By the way, I'm wondering whether we should run the `insteadOf` pre command even when the global `go` is being run. As pointed out by @mimol91, we are only running it for Docker today. I had held off running that type of command locally in case it interfered with anyone's local setup, but maybe we should assume that the server Renovate runs on is Renovate's to use and pollute?

**Comment by mimol91** [comment]
@rarkins 
After mounting .gitconfig file with token it seems that it solve the issue.

Regarding the question, renovate pollute `/tmp` anyway. However as you mention amending .gitconfig is a little bit more intrusive, so making good decision won't be easy.

Thanks for helping!

**Comment by rarkins** [comment]
> renovate pollute `/tmp` anyway

Should just be `/tmp/renovate/` though? And if so is there really any alternative?

**Comment by mimol91** [comment]
Personally I think you made good decision, It has to be stored somewhere so /tmp/renovate makes perfect sense.
I would however do not modify .gitconfig or any 'user' files. As it might be quite confusing for them.

**Comment by rarkins** [comment]
Thanks for the feedback. I had also thought we should avoid modifying 'user' files in case people are not running it in a container. Maybe one day is there's too many constraints because that then we need to change our requirements.
