### ISSUE TITLE
Adding {{fromVersion}} to commit messages on groups

### ISSUE THREAD

**Issue by JordanJLopez** [renovatebot/config-help#524]
### Which Renovate are you using?

renovate/pro:0.18.5

Renovate Pro

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

I don't believe they're relevant.

### What would you like to do?

I would like the {{fromVersion}} to appear in the commit message/PR title of new pull requests that update groups.

I've noticed that I can configure the "commitMessageTopic" such that the old version is present:

```json
  
{
  "extends": [myCompanyRenovateConfig],
  "commitMessageTopic": "dependency {{depName}} from v{{fromVersion}}"
}
```

This results in pull requests like this one:

> Fix: Update dependency DEPENDENCY from v1.0.0 to v1.1.0

However, it doesn't seem to apply to grouped **Maven** dependencies based on Maven properties. I still see:

>  Fix: Update OTHER-DEPENDENCY.version to v2.1.0 (`OTHER-DEPENDENCY:a`, `OTHER-DEPENDENCY:b`)

I'd like to be able to instead see

> Fix: Update OTHER-DEPENDENCY.version _from v2.0.0_ to v2.1.0 (`OTHER-DEPENDENCY:a`, `OTHER-DEPENDENCY:b`)

**Comment by rarkins** [comment]
First of all, put the `fromVersion` in `commitMessageExtra` and not `commitMessageTopic`.

I'm not sure that will fix the grouping as you'd like it though. Note that sometimes groups can have multiple `fromVersion` values.

If unable to get it to work, a reproduction in a public repo would be required to experiment with.

**Comment by JordanJLopez** [comment]
Hi @rarkins , adding the `fromVersion` to `commitMessageExtra` worked, even for the grouped items in my original post! Thanks a bunch.
