### ISSUE TITLE
nodejs LTS docker image not updated

### ISSUE THREAD

**Issue by prymitive** [renovatebot/config-help#530]
**What Renovate type are you using?**

GitHub app

**Describe the bug**

Renovate doesn't seem to pick up nodejs docker updates, I have `12.15.0-alpine` in Dockerfile while `12.16.0-alpine` is avaiable

**Did you see anything helpful in debug logs?**

looking at logs it seems that renovate only considers 13.8 (current version) and doesn't notice updated LTS (12.16) version

https://app.renovatebot.com/dashboard#github/prymitive/karma/141123561
```
DEBUG: packageFiles with updates
{
  "config": {
    "dockerfile": [
      {
        "packageFile": "Dockerfile",
        "manager": "dockerfile",
        "deps": [
          {
            "depName": "node",
            "currentValue": "12.15.0-alpine",
            "datasource": "docker",
            "commitMessageTopic": "Node.js",
            "managerData": {
              "lineNumber": 0,
              "fromPrefix": "FROM",
              "fromSuffix": "as nodejs-builder"
            },
            "depType": "stage",
            "updates": [
              {
                "fromVersion": "12.15.0",
                "toVersion": "13.8.0",
                "newValue": "13.8.0-alpine",
                "newMajor": 13,
                "newMinor": 8,
                "updateType": "major",
                "isSingleVersion": true,
                "newVersion": "13.8.0"
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/nodejs/node",
            "dockerRegistry": "https://index.docker.io",
            "dockerRepository": "library/node"
          },
```

**To Reproduce**

https://github.com/prymitive/karma/blob/master/Dockerfile

**Additional context**

**Comment by prymitive** [comment]
But that means other dependencies won’t get major version automerge. Is there a way to avoid that?
Seems like the problem comes down to the fact that node version selection is additionally restricted by the lts policy, which auto merge isn’t aware of?
Also: how would that work if new node current and lts versions were different but on the same major version? I would have to reduce the setting to only patch level?

**Comment by rarkins** [comment]
> But that means other dependencies won’t get major version automerge. Is there a way to avoid that?

Use package rules to define automerge and exclude `node` specifically. I don't recommend automerging major updates in general though.

> Seems like the problem comes down to the fact that node version selection is additionally restricted by the lts policy, which auto merge isn’t aware of?

Renovate is not aware of Node/docker LTS policies in general.

> Also: how would that work if new node current and lts versions were different but on the same major version?

I don't think that's possible to happen.

**Comment by prymitive** [comment]
Thanks, forgot I can specify custom settings just for node.

> Renovate is not aware of Node/docker LTS policies in general.

But it doesn’t upgrade 12.15.0 to the latest current (13.x) as it defaults to lts on
https://docs.renovatebot.com/node/

**Comment by rarkins** [comment]
It's actually a lot simpler than it looks. By default it skips major upgrades altogether :)

**Comment by prymitive** [comment]
Is this the correct way of overriding automerge settings just for node?

```
  "automerge": true,
  "packageRules": [
    {
      "packageNames": ["node"],
      "updateTypes": ["major"],
      "automerge": false
    },
    {
      "packageNames": ["node"],
      "updateTypes": ["minor", "patch"],
      "automerge": true
    }
  ]
```

**Comment by ViceIce** [comment]
@prymitive You can omit the second rule, as you have `automerge` enabled globally

**Comment by rarkins** [comment]
I'm not 100% sure this will fix the problem though. At the time of lookup, Renovate will still see `automerge: true` for `node` too. With everything in packageRules:

```json
  "packageRules": [
    {
      "excludePackageNames": ["node"],
      "automerge": true
    },
    {
      "packageNames": ["node"],
      "updateTypes": ["minor", "patch"],
      "automerge": true
    }
  ]
```

**Comment by prymitive** [comment]
^^ that did it, thanks!
