### ISSUE TITLE
Multiple config files on a single execution

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#531]
### Which Renovate are you using?
Renovate Open Source CLI
Docker Image (renovate/renovate:slim) running in Kubernetes

### Which platform are you using?
GitHub Enterprise

### What would you like to do?
Hi, I have an scenario where multiple teams might want to use the same pod running renovate docker image, but each having their own config file, each team has different needs and keeping everything on a single config file could be a challenge.  Is there any option to provide multiple config files that renovate can use on every execution?

something like RENOVATE_CONFIG_FILE="config1.js, config2.js, config3.js"

or will need to run separate pods with a specific config file on each one?

thanks

**Comment by rarkins** [comment]
I don't think there's any way to achieve this. Logically it would need to be the same as running Renovate 3 times in a row with the three different configs, so maybe you could work out a wrapper to add to your pod to do that, if it's easier than running separate pods?
