### ISSUE TITLE
allowedVersions does not work on monorepo presets

### ISSUE THREAD

**Issue by sarunint** [renovatebot/config-help#532]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I have my custom configuration here:

https://github.com/sarunint/renovate-config/blob/6cd8f806ada8f75782a0c9f8059617afe4dc8ef8/package.json#L49-L81

My intention was to hold the upgrade of Angular packages from v8 to v9 while I solve some bugs.

I have my repository here https://github.com/ivaothai/whazzup-tracker/issues/2

But Renovate still create PR that update Angular to v9. Why is this happening?

**Comment by rarkins** [comment]
What do you see in the logs when searching for `allowedVersions`? Do you see it attempting to limit them?

**Comment by sarunint** [comment]
Hmm let me check.
