### ISSUE TITLE
non-latest version in package.json of renovate PR

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/config-help#539]
**What Renovate type are you using?**

GitHub App

**Describe the bug**
Renovate opened https://github.com/brainhubeu/react-carousel/pull/261 with `"@brainhubeu/react-carousel": "^1.11.0",` in package.json and resolving `"@brainhubeu/react-carousel@^1.11.0":` with `version "1.11.1"` in `yarn.lock`

**Expected behavior**
I'd like to have `"@brainhubeu/react-carousel": "^1.11.1",` in `package.json`.

**Screenshot**
<img width="1118" alt="Screenshot 2020-02-19 at 14 53 54" src="https://user-images.githubusercontent.com/20856232/74840683-b1339880-5327-11ea-94f4-577187d411eb.png">

**Comment by rarkins** [comment]
Set [rangeStrategy](https://docs.renovatebot.com/configuration-options/#rangestrategy) to "bump"

**Comment by piotr-s-brainhub** [comment]
@rarkins 

I have this already https://github.com/brainhubeu/react-carousel/blob/master/renovate.json#L6

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/74844694-21ddb380-532e-11ea-92f1-826db6f73650.png)

Latest tag for the package is `1.11.1-cdn`. According to SemVer, `1.11.1` is later than `1.11.1-cdn`, which means Renovate ignores it (unless you configure `ignoreLatest=true`).

However I looked and if you specify `^1.11.0` in a `package.json` and use both npm or yarn then they both install `1.11.1` into `node_modules`. If you simply `npm install @brainhubeu/react-carousel` then you get `1.11.1-cdn`. Their behaviour doesn't seem logical either.

I'm not sure if we should change anything in Renovate. My advice is that using a suffix like `-cdn` for a stable release is not a good idea.
