### ISSUE TITLE
Rerun Onboarding PR

### ISSUE THREAD

**Issue by Crashthatch** [renovatebot/config-help#54]
I've been using renovate for a few weeks, and I want to experiment some more with my config.

Before I started to use renovate I could push changes to `renovate.json` on the `renovate/configure` branch, and after a minute or so, renovate updated the onboarding PR to show me the results of what PRs would be created etc, if that config were to be merged.

I liked that behaviour and would like to use it for the changes I'm considering making to the config now (It's much faster than waiting for renovate to actually create PRs, especially as I have the schedule set so that renovate only runs overnight). Is there a way to run the "onboarding" PR from another branch?

I tried to recreate the renovate/configure branch, but he noticed and immediately closed & deleted it.

**Comment by rarkins** [comment]
Yes, the bot "owns" its namespace of `renovate/*` so will close any branch it finds that it doesn't need open.

I plan to offer "reconfigure" functionality one day, but it's not ready yet. For now here are the steps to restart your config (do them in this order):

1. Find the original "Configure Renovate" PR and rename it, e.g. to "Configure Renovate - old"
2. Take a copy of your config - if you need it - and then delete the `renovate.json` in your repo

The above two steps make your repo look non-onboarded to the bot and should trigger a new "Configure Renovate" PR that you can interactively edit like before. Note that any open/existing PRs might get autoclosed though, and then created again later (as applicable) once you finish onboarding the second time.

**Comment by Crashthatch** [comment]
Ok, that's helpful, thanks. :+1:
