### ISSUE TITLE
Ignore packages by pattern

### ISSUE THREAD

**Issue by qstyler** [renovatebot/config-help#540]
Hi, everyone!
I'm trying to configure my renovate script so it will work with only specific groups of dependencies and ignore all the rest.
For that I tried to use negative lookahead pattern in the packageRules and “enabled:false”, but it didn't work since RE2 does not support regex lookaheads.

Is there a chance I can have several groups like “angular”, “graphql”, “apollo” and ignore all the rest?

And if it isn't possible, maybe there's an option to NOT use RE2?

Thanks!

**Comment by rarkins** [comment]
Please edit your question to use the template: https://github.com/renovatebot/config-help/issues/new?labels=&template=config-help.md&title=
