### ISSUE TITLE
Renovate doesn't raise PR after manual downgrade

### ISSUE THREAD

**Issue by y0zg** [renovatebot/config-help#541]
### Which Renovate are you using?
WhiteSource Gitlab Renovate 

### Which platform are you using?
GitLab.com

### config
renovate.js configuration

```
{
  "extends": [
    "config:base",
    "schedule:daily"
  ]
}
```

### What would you like to do?

I successfully onboarded renovate bot and it created PR request with proposed higher versions.
Then I intentionally downgraded some version to previous value for testing purpose.
It passed more than 24 hour but I don't see a new PR request with new versions from renovate bot. Please elaborate what I missed

I referenced to to this file for schedule config:
https://github.com/renovatebot/presets/blob/master/packages/renovate-config-schedule/package.json

**Comment by rarkins** [comment]
Renovate assumes you downgraded for a reason and deliberately skips repeating the same upgrade. Rename the previous PR title and you should get a replacement.

**Comment by y0zg** [comment]
Thank you, @rarkins !
Should this picture work? Is there any option to have schedule less than 1 day? (I know about tips for removing/onboarding renovate, but I'd like to test normal way how bot works without manual intervention.
![Screenshot from 2020-02-20 15-40-07](https://user-images.githubusercontent.com/6439757/74938800-608b7080-53f7-11ea-8952-371951935d8a.png)

**Comment by rarkins** [comment]
That should work and you should see a scheduled job within 1-2 hours. Alternatively make any edit to your config or package file and you should get a job immediately.

**Comment by y0zg** [comment]
above solution works!
