### ISSUE TITLE
How to use renovate which is deployed using the provided kubernetes file?

### ISSUE THREAD

**Issue by pjeyabalan** [renovatebot/config-help#543]
Hi,

We have deployed the kubernetes config cron job and the secret config file ..The cron job starts a pod and its expecting some input from us. We have provided all the secrets like the renovate token  , github enterprise token ...but not sure how to tell the cron job as which repo to look at to create pull request ..can you help us if we are missing any other config file which needs to be provided as input ?

**Comment by rarkins** [comment]
The last step might be telling Renovate to "autodiscover" the repositories on GHE it has access to. e.g. in env: `RENOVATE_AUTODISCOVER=true`

**Comment by pjeyabalan** [comment]
Okay ...we have true already provided for RENOVATE_AUTODISCOVER in the secret.yaml file but after successful creation of container we are seeing this below screenshot which looks like its expecting some parameter from user [
![MicrosoftTeams-image](https://user-images.githubusercontent.com/11905575/75050417-8cf3cb00-5491-11ea-9f48-0da292636801.png)
](url)

**Comment by viceice** [comment]
looks like you pass some invalid  cli parameter. can you show use your configs?

**Comment by pjeyabalan** [comment]
We passed only 2 yaml files one is the cronJob and other is the secret.yaml file ...secret.yaml files looks like below ...if we need to use config file for cli too for kubernetes deployment please point me to the link where i can copy from a config file and replace my values 
<img width="307" alt="Screen Shot 2020-02-21 at 10 19 33 AM" src="https://user-images.githubusercontent.com/11905575/75051625-d8a77400-5493-11ea-9045-eb941b9d05ca.png">

**Comment by viceice** [comment]
and the cron config?

**Comment by pjeyabalan** [comment]
attached the cron job config
<img width="712" alt="Screen Shot 2020-02-21 at 10 45 27 AM" src="https://user-images.githubusercontent.com/11905575/75053688-56b94a00-5497-11ea-8afe-b230df52afd9.png">

**Comment by viceice** [comment]
You should use a newer renovate image version.

**Comment by pjeyabalan** [comment]
Okay will update to latest version and try...But is there a way to restrict to a particular repo instead of running for all the repos and orgs?

**Comment by viceice** [comment]
`RENOVATE_AUTODISCOVER=false`

add repo as cli arg. `org/repo`

**Comment by pjeyabalan** [comment]
Awesome ...can you please show me the exact parameter as where to add the org/repo? in secret.yaml or the cronjob.yaml , i made the RENOVATE_AUTODISCOVER as false

**Comment by viceice** [comment]
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
```yml
         containers:
            - name: renovate
              image: renovate/renovate:13.153.0
             args: ["org/repo"]
`

**Comment by viceice** [comment]
@rarkins We should update https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#kubernetes to include such samples and update the image version

**Comment by viceice** [comment]
alternative `RENOVATE_REPOSITORIES=org/repo,orgb/repo2` env should do it too

**Comment by pjeyabalan** [comment]
Thanks a lot for your immediate suggestions

**Comment by viceice** [comment]
should also work with secrets, see https://docs.renovatebot.com/self-hosted-configuration/
for more options.
