### ISSUE TITLE
Renovate PR's do not trigger alerts

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#544]
Hi, I'm using CLI version in GHE, PR's get created as expected and it has reviewers assigned as expected. However, reviewers do not get a notification about the generated PR, in a normal situation, reviewers get an email for each PR.  Is there any setting in renovate that influence those PR notifications ?

thanks

**Comment by rarkins** [comment]
No, to my knowledge Renovate has no influence over that. I haven't heard of this feedback before either. Normally people complain about too many notifications from bots!
