### ISSUE TITLE
Does renovate look into real new versions available?

### ISSUE THREAD

**Issue by y0zg** [renovatebot/config-help#545]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitLab.com

### What would you like to do?

Please let me know the algorithm how renovate look for new versions to be upgraded to? Is that a simple increment or renovate bot does really look into available apps versions?

**Comment by rarkins** [comment]
Renovate queries the relevant datasource for all versions (including old ones, including newer unstable ones) and then applies an algorithm to decide which updates are valid for the user, including their custom configuration. 

You can look into the algorithm, but it's pretty complex: https://github.com/renovatebot/renovate/blob/master/lib/workers/repository/process/lookup/index.ts

By default Renovate will raise PRs for the latest minor release and latest major release, with the occasional exception (e.g. docker major upgrades are disabled by default).
