### ISSUE TITLE
Eslint commit convention for renovate bot

### ISSUE THREAD

**Issue by y0zg** [renovatebot/config-help#546]
### Which Renovate are you using?
WhiteSource Renovate App

### Which platform are you using?
GitLab.com

### What would you like to do?
Hello. My repo uses eslint format commit convention and based on documentation it seems renovate bot should have detected this. In fact I see  the following in the commit for renovate bot:
`chore(deps): update dependency @typescript-eslint/eslint-plugin to v2`

Is it possible to follow eslint semver convention for renovate bot?
https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint

```
Fix - for a bug fix.
Update - either for a backwards-compatible enhancement or for a rule change that adds reported problems.
New - implemented a new feature.
Breaking - for a backwards-incompatible enhancement or feature.
Docs - changes to documentation only.
Build - changes to build process only.
Upgrade - for a dependency upgrade.
Chore - for refactoring, adding tests, etc. (anything that isn't user-facing).
```

I found this info useful but didn't get answer to my question:
https://docs.renovatebot.com/semantic-commits/#manually-enabling-or-disabling-semantic-commits

**Comment by rarkins** [comment]
Renovate doesn't have native support for the eslint standard yet - it would need to be added in order to automatically work.

However you might be able to achieve it manually using a config like this:

```json
{
  "semanticCommits": false,
  "commitMessagePrefix": "Upgrade:"
}
```

The first line should disable any automatic angular commits, and the second line configures a fixed prefix for each commit.
