### ISSUE TITLE
Token encryption with own TLS cert

### ISSUE THREAD

**Issue by micheelengronne** [renovatebot/config-help#548]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

I am a bit confused. I wanted to add a github auth token to my self-installed renovatebot and following the [doc](https://docs.renovatebot.com/install-gitlab-app/#configuring-a-token-for-githubcom-hosted-release-notes) I had to encrypt it using [renovatebot encrypt](https://renovatebot.com/encrypt) website.

Is there a possibility to do it myself with a shell command and my own TLS key/cert ?

Thanks.

**Comment by viceice** [comment]
Can you please fill the issue [template](https://github.com/renovatebot/config-help/issues/new?labels=&template=config-help.md&title=)

**Comment by micheelengronne** [comment]
Done.

**Comment by viceice** [comment]
You don't have to encrypt it, simply add it as environment variable `GITHUB_COM_TOKEN=xxxxxx`

see [githubcom-token-for-release-notes](https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#githubcom-token-for-release-notes)

**Comment by micheelengronne** [comment]
Ok, thanks. Can it also be added in the configuration file ?

**Comment by viceice** [comment]
Yes, you need to configure a [`hostRule`](https://docs.renovatebot.com/configuration-options/#hostrules).

Or add it to the `config.js` like 
```js
process.env.GITHUB_COM_TOKEN = 'xxxxxx';

module.exports = {
  // settings
};
```

But do not commit the token to a repository!

**Comment by micheelengronne** [comment]
Of course, I will never commit a crypto on a repo. Ok, and in the case of the `hostRules` it doesn't need to be encrypted ?

**Comment by viceice** [comment]
right 👍
