### ISSUE TITLE
How to ignore a certain dependency in one of the modules

### ISSUE THREAD

**Issue by alexey-anufriev** [renovatebot/config-help#552]
I have tried to do the following to ignore one dependency in a specific module
```
"packageRules": [
    {
      "paths": [
        "my-sub-module/**"
      ],
      "ignoreDeps": [
        "org.springframework:spring-aop"
      ]
    },
    ...
```
After this change in the log of the job I see that dependency was ignored but in the onboarding PR in "What to Expect" section I still see a suggestion to update `spring-aop`.

**Comment by viceice** [comment]
Thanks, can you please merge the onbaarding pr, to see if renovate will try to update the ignored dependency? Then we can see it there is a bug or not.

BTW: Please fill our issue [template](https://github.com/renovatebot/config-help/issues/new?labels=&template=config-help.md&title=)

**Comment by rarkins** [comment]
`ignoreDeps` needs to be at the top level, e.g.

```
"ignoreDeps": [
        "org.springframework:spring-aop"
],
"packageRules": [
    ...
```

If you want it as part of `packageRules`, please use this approach instead:

```
"packageRules": [
    {
      "paths": [
        "my-sub-module/**"
      ],
      "packageNames": [
        "org.springframework:spring-aop"
      ],
      "enabled": false
    },
    ...
```

**Comment by alexey-anufriev** [comment]
@rarkins , I did it now the same way as you recommended, onboarding PR still has suggestions to update, but in the job log I see `Dependency is disabled (org.springframework:spring-aop)`

Shall I try to merge?

**Comment by rarkins** [comment]
The log message you see is a good sign, but if it's still telling you that there will be a PR then there probably will be, so that's a bad sign. Do you have that dependency anywhere else in the repository?

**Comment by alexey-anufriev** [comment]
yes, I have two modules with this dependency, like this:
- my-spring-support (with 5.0.0)
- my-spring-support-test (with 5.X.X - almost the latest BUT not the latest)

I suspect the second module may be a cause for this problem.

**Comment by rarkins** [comment]
I don't understand why you think it's a problem. You have the dependency twice, and you're ignoring only one of them. Wouldn't you expect to still see a PR predicted?

**Comment by rarkins** [comment]
The names you list there are not the same as in your packageRules above. I suggest you either merge the onboarding and just see what it creates, or alternative fork/copy the project and onboard the copy with same config to see.

**Comment by alexey-anufriev** [comment]
sorry, you are right, it could be not a problem, it is just unclear to me which module is affected by the upgrade, but I agree, the best would be to try it out

**Comment by alexey-anufriev** [comment]
awesome, it works as expected!
thank you for help.
