### ISSUE TITLE
Memory/cpu limits for running docker container

### ISSUE THREAD

**Issue by albuch** [renovatebot/config-help#554]
### Which Renovate are you using?

Rennovate Open Source CLI 

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

yes, nothing specifically to see there.

### What would you like to do?

I would like to know what the memory and cpu limits configuration for running the Docker image on kubernetes should look like as we're facing intermittent OOMKills with our current configuration (500Mi memory, 1000m cpu)
As far as I can see there are no nodejs memory/heap restrictions defined in the docker image node process which makes it difficult to find reasonable limits.

**Comment by rarkins** [comment]
The production app runs on `m3.medium` servers with 3.75GB RAM. The amount used per-repo varies greatly, but usually not over approximately half. I'd recommend minimum 1GB, and 2GB ideally and see if that reduces errors.

**Comment by albuch** [comment]
Thanks @rarkins , I'll give it a go with 2 GB and will add a heap restriction for the node process as well.
