### ISSUE TITLE
Ignoring docker digests

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/config-help#556]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

I have `pinDigests` set globally for immutability however for certain, extremely limited, use cases pinning the digest is undesirable.

Using the config how would one apply a rule "pin all digests _except_ for this particular image/list of images"?

**Comment by rarkins** [comment]
I think something like this:

```json
{
  "packageRules": [{
    "datasources": ["docker"],
    "excludePackageNames": ["foo", "bar"],
    "pinDigests": true
  }]
}
```

**Comment by adam-moss** [comment]
Nice one, I will give that a try thank you.  I didn't realise package names could incorpate docker images also 😊

**Comment by rarkins** [comment]
Yes, `packageNames` and `excludePackageNames` will match against the `depName` you see in the logs, so could be like `node`, `amd64/node`, or `quay.io/foo/node`, etc. Same thing goes for `packagePatterns` and `excludePackagePatterns`.

**Comment by adam-moss** [comment]
Right, I got this working, had to remove the global "pinDigests": true as that overrides the package rule seemingly, so it was still be recreated.  Thanks for this.

**Comment by rarkins** [comment]
Could you reproduce that problem in a GitHub.com repository? The package rule should override any default setting

**Comment by adam-moss** [comment]
I'll give it a go, sure, no problem

**Comment by adam-moss** [comment]
Actually thinking about it what it has done is correct.

If the global config is essentially:

```
    "pinDigests": true
```

And the repo has a `renovate.json` with a package rule:

```
    "packageRules": [{
        "datasources": ["docker"],
        "excludePackageNames": ["foo", "bar"],
        "pinDigests": true
    }]
```

Then it isn't actually going to do anything, since the merged config would be:

```
    "pinDigests": true,
    "packageRules": [{
        "datasources": ["docker"],
        "excludePackageNames": ["foo", "bar"],
        "pinDigests": true
    }]
```

In other words "pinDigests" is never false.

Reversing that, so it is more like:

```
   "pinDigests": true,
    "packageRules": [{
        "datasources": ["docker"],
        "packageNames": ["foo", "bar"],
        "pinDigests": false
    }]
```

Is a more accurate reflection 🤦‍♂

**Comment by rarkins** [comment]
Yes, you’re right. I left the root pinDigests out in my original suggestion but missed the difference today
