### ISSUE TITLE
Automated Pull Request Not getting created

### ISSUE THREAD

**Issue by pjeyabalan** [renovatebot/config-help#559]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub.com (Enterprise Version)

### Have you checked the logs? Don't forget to include them if relevant

Attached the Pod( successful log)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/11905575/75803174-9d366080-5d43-11ea-89e4-95fdeee7c78b.png)

### What would you like to do?

1.First time renovate bot created  renovate.json successfully.

2.But we are not seeing any pull request upgrading any packages after that.

3. Below are the list of dependencies i have added in my package.json , or please provide a dependency for which i can get a bumper version of a package.

"dependencies": {
    "execa": "0.11.0",
    "axios": "0.19.0",
    "execa": "^3.4.0",
    "formik": "2.0.4",
    "moment": "2.24.0",
    "react": "16.10.0",
    "react-app-polyfill": "1.0.4",
    "react-dom": "16.10.0",
    "react-redux": "7.1.3",
    "react-router-dom": "5.1.2",
    "react-scripts": "3.2.0",
    "redux": "4.0.4",
    "redux-thunk": "2.3.0",
    "styled-components": "4.4.1",
    "yup": "0.27.0"
  }

**Comment by viceice** [comment]
Please run again with `--log-level debug`

**Comment by pjeyabalan** [comment]
@viceice  can you please provide me the exact place as where to mention the --log-level debug

as of now we just use `oc apply -f renovate.yaml`

**Comment by rarkins** [comment]
Or define `LOG_LEVEL=debug` in your env

**Comment by pjeyabalan** [comment]
@rarkins  

in my env meaning in the secret.yaml file? or in the renovate.yaml file ...when we try to add to the secret.yaml file its throwing some error

**Comment by rarkins** [comment]
Those are k8s concepts and not Renovate, so I can’t answer you. By env I mean environment variables. I recommend you troubleshoot using CLI and not within k8s if you’re not an expert on either - best to reduce the unknowns.

**Comment by pjeyabalan** [comment]
@rarkins okay ...but from the package.json file which i provided am i expected to get a version update or does something look wrong in that itself. only renovate.json file created successfully first time

**Comment by rarkins** [comment]
What did the onboarding PR predict would happen? And what dependencies in that list do you expect need updating?

**Comment by pjeyabalan** [comment]
Below is the screenshot of the onboarding ....all the dependancies in the package.json file is from 2018

<img width="643" alt="Screen Shot 2020-03-03 at 1 53 05 PM" src="https://user-images.githubusercontent.com/11905575/75813904-70d80f80-5d56-11ea-8131-561afa83ee3b.png">

**Comment by rarkins** [comment]
So after seeing that, you thought the best way to describe your problem was the following?

![image](https://user-images.githubusercontent.com/6311784/75815215-4f494900-5d93-11ea-8fc9-404344c122d0.png)

**Comment by pjeyabalan** [comment]
Hmmm :) ...yeah because every time am trying to downgrade the packages to lower version but still they weren't bumped to higher once ....we tried to onboard a different app with lower versions and but still it says all packages are upto date.

**Comment by pjeyabalan** [comment]
@viceice  attached the DEBUG logs too , passed the LOG_LEVEL as environment variable ...we dont see any connection timeout or error in the logs though ...Is it because of the registry url? 

[renovate.log](https://github.com/renovatebot/config-help/files/4283754/renovate.log)

**Comment by rarkins** [comment]
The custom registry you defined is causing the lookups to fail, and after that nothing can work.

**Comment by pjeyabalan** [comment]
@rarkins  But in the debug logs ...it doesn't show any kind of error or throw exception be it connection timed out or not able to talk to the registry url. can you please let us know as how did you find out its because of the custom registry url

**Comment by viceice** [comment]
@pjeyabalan Please check your  `renovate.yaml`. if you just copied it from our docu, you have to update the docker image to a newer version. See https://hub.docker.com/r/renovate/renovate/tags for most recent tags.

**Comment by viceice** [comment]
@pjeyabalan Have you configured the `npmrc` property? So you need to add credentials for your custom npm registry. Also check if the ssl certificate of registry is using accepted by nodejs.
