### ISSUE TITLE
How to change PR rate limit and limit?

### ISSUE THREAD

**Issue by voxpelli** [renovatebot/config-help#56]
I'm attempting this:

```
{
  "extends": [
    "<our internal app default>"
  ],
  "schedule": [],
  "prHourlyLimit": 0,
  "prConcurrentLimit": 10
}
```

Although the initial configuration PR still says that PR:s are rate limited and that the PR limit is at 20. Am I doing it wrong?

**Comment by voxpelli** [comment]
Looks like it suddenly fixed itself in one of my repos – and it opened about 8 PR:s at once – just like I wanted. So perhaps the issue here is some kind of cache/delay rather than a config issue?

(Or the issue is just with the description in the config PR, not with the actual config?)

**Comment by rarkins** [comment]
Yes, the onboarding PR unfortunately doesn’t/ can’t perfectly describe custom config yet. It iterates through the presets and outputs their descriptions so any custom overrides wont get described.

**Comment by voxpelli** [comment]
Right, thanks!
