### ISSUE TITLE
Dockerfile skipped because stage contains variable

### ISSUE THREAD

**Issue by dalberto** [renovatebot/config-help#562]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```json
{
        "packageFile": "services/postgres/Dockerfile",
        "manager": "dockerfile",
        "deps": [
          {
            "skipReason": "contains-variable",
            "datasource": "docker",
            "managerData": {
              "lineNumber": 3,
              "fromPrefix": "FROM",
              "fromSuffix": "AS postgres"
            },
            "depType": "final",
            "updates": []
          }
        ]
      },
```

### What would you like to do?

I'd like for Renovate to manage Dockerfile updates. Renovate detects the files ok but refuses to update them, with something akin to the above logs. How can I get around this issue or configure Renovate appropriately?

For reference, one of the Dockerfiles in question looks like this:

```Dockerfile
ARG POSTGRES_VERSION=11.5

FROM postgres:${POSTGRES_VERSION}-alpine AS postgres

COPY psqlrc /root/.psqlrc

COPY docker-entrypoint-initdb.d/* /docker-entrypoint-initdb.d/

COPY health-check.sh /usr/local/bin

HEALTHCHECK --interval=5s --timeout=3s \
        CMD health-check.sh
```

**Comment by rarkins** [comment]
This is unfortunately a functionality limitation currently. Subscribe to https://github.com/renovatebot/renovate/issues/5626 to see when it can be supported.
