### ISSUE TITLE
Upstream proxies and lock files

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/config-help#565]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

For efficiency and resilience we proxy upstream dependencies using Nexus Repository Manager.

One of the identified challenges with this is lock files such as node's `package-lock.json` then get populated with the URL for Nexus, rather than the true upstream, e.g. npmjs.com

This then causes downstream issues if we open source something, since we need to replace those URLs throughout the git history.

We've been looking at a post upgrade task to automatically replace these URLs (basically a simple `sed` find replace) to avoid this during the renovation process however this is rather brutal, and needs extra massaging for legitimate private dependencies we only publish internally.

What would you recommend here? Is this a situation you've encountered and if so how did you go about solving it?

Thanks!

**Comment by rarkins** [comment]
I'm not aware of any solution to this. I think if you replace the URLs with npmjs URLs then that will mean every developer or CI system that then runs `npm install` or `npm ci` will attempt to directly download from npmjs and bypass your Nexus.

Perhaps for things you open source, do a one time search/replace and then stick with npmjs after that, and for everything else stick with Nexus?
