### ISSUE TITLE
PRs created even though stabilityDays have not elapsed but prCreation="not-pending"

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#566]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Example job: 150155812

### What would you like to do?

I would expect that with this configuration:

```
"stabilityDays": 7,
"prCreation": "not-pending",
```

PRs are not created until the stability days have elapsed. Yet, we're seeing that sometimes PRs are created anyway. Here's one such job: 150155812 (or earlier jobs in the same repository).

I can understand that this may be caused by:

- a PR being created because stability days have elapsed
- the package releasing a new version before we have a chance to merge the PR
- Renovate keeping the PR open, updating it to the latest version released, and marking it as "pending" because now the stability days have not elapsed

I just wanted to check if all the cases we're encountering are because of the situation described above or maybe a bug in Renovate

**Comment by viceice** [comment]
Which managers are you using?

**Comment by simoneb** [comment]
> Which managers are you using?

What are managers?

**Comment by viceice** [comment]
what type of packages do you want to update by renovate? `npm`, `nuget`, `docker` ...

**Comment by simoneb** [comment]
> what type of packages do you want to update by renovate? `npm`, `nuget`, `docker` ...

Ah I see what you mean. This is npm.

**Comment by viceice** [comment]
Which packages are causing the pr? Are you using a custom package registry?

**Comment by simoneb** [comment]
> Which packages are causing the pr? Are you using a custom package registry?

Yes. Note though that the behavior seems to be correct in some cases (in the sense that PRs are not created until the stability days have elapsed) and wrong in others.

**Comment by rarkins** [comment]
> * a PR being created because stability days have elapsed
> * the package releasing a new version before we have a chance to merge the PR
> * Renovate keeping the PR open, updating it to the latest version released, and marking it as "pending" because now the stability days have not elapsed

This is expected behavior. If you want to check if that explains everything, check to see if the PR description says "Edited". If you click the Edited button, you can look at the earlier descriptions to confirm if they had an earlier version.

**Comment by simoneb** [comment]
One PR I'm looking at, which I can't share because it's in a private repository, has not been edited and it's trying to bump [this package](https://github.com/pinojs/pino-pretty) from the current 3.6.0 to 3.6.1, which was indeed released ~7 days ago but maybe not quite exactly > 7 days ago. So it doesn't seem to fall into the case above (the earlier version was more than 20 days ago). So I'm wondering, could it be a timezone issue instead? Or maybe Renovate checking the number of days in a loose way somewhere and in a more strict way elsewhere? Because the PR is created but it says "pending" in the status check.

**Comment by rarkins** [comment]
Actually, I might know what happened. We had a couple of days where we were setting branch statuses incorrectly, which was fixed here: https://github.com/renovatebot/renovate/commit/a8e1979edc6e12e348d9a45b5497f10e40f9592a

It's possible that the "pending" status that Renovate should have set was not done properly and that lead to it being created.

**Comment by simoneb** [comment]
That would make sense, I would like to mention that this is a behavior we've been experiencing for some time, just took the time to report it now. Let's assume that that issue was the cause and close this, I'll reopen it in case it happens again.
