### ISSUE TITLE
excluding archived repos

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#569]
### Which Renovate are you using?
Renovate Open Source CLI

### Which platform are you using?
GitHub Enterprise

### What would you like to do?
Is there a way that we can exclude any archived repo when renovate is running ?

**Comment by rarkins** [comment]
It should detect and ignore them already. Is it not happening?

**Comment by rvillane** [comment]
I haven't tried, will confirm

**Comment by rvillane** [comment]
ok, yes, I can confirm is working as expected, thanks
