### ISSUE TITLE
Renovate fails to auto-merge due to "Artifact update failure" on Bitbucket Pipelines

### ISSUE THREAD

**Issue by lephuongbg** [renovatebot/config-help#574]
**What Renovate type are you using?**

Self-hosted on Bitbucket Pipelines (slim image)

**Describe the bug**

Renovate can create a pull request successfully for new version of poetry dependency, but fail to auto-merge in subsequent run due to "Artifact update problem".

**Did you see anything helpful in debug logs?**

This is the error in the comment for "Artifact update problem":

```
docker: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR and its subdirectories.
See 'docker run --help'.
```

**To Reproduce**

1. Run Renovate on a project that uses poetry, to create a PR for a dependency.
2. Run Renovate again, see that "Artifact update problem" was posted as a comment to that PR.

**Additional context**

Renovate seems to try to use docker to update the poetry.lock file on existing PR. There are two problems:

+ Our image (based on renovate-slim) already has poetry binary included, and we configured it to use global binary. Why on subsequent runs does it use docker?
+ Bitbucket Pipelines does not allow to mount directory outside of current project, so Renovate should not do that to be able to run correctly on Bitbucket Pipelines.

<details>
<summary>Our config</summary>

```json
{
    "extends": ["config:base", ":automergePatch"],
    "rangeStrategy": "bump",
    "binarySource": "global",
    "prConcurrentLimit": 3,
    "prHourlyLimit": 0,
    "includePaths": [
        "api/**",
        "web/**"
    ],
    "enabledManagers": ["npm", "poetry"],
    "node": {
        "enabled": false
    },
    "separateMinorPatch": true,
    "packageRules": [
        {
            "updateTypes": ["patch"],
            "excludePackagePatterns": ["^vuetify"],
            "groupName": "all patch updates"
        },
        {
            "packagePatterns": ["^vuetify"],
            "groupName": null
        },
        {
            "depTypeList": [
                "engines"
            ],
            "enabled": false
        }
    ]
}
```
</details>

**Comment by rarkins** [comment]
You are using the slim image, which has binary source set to Docker: https://github.com/renovatebot/renovate/blob/7ce4f24c00210b0aae6072fe2a6efed234ce1e80/Dockerfile#L62

If you are creating your own custom image based off slim, then you need to override that variable too, because environment takes precedence over config files.

**Comment by viceice** [comment]
Simply add `ENV RENOVATE_BINARY_SOURCE=gloval` to your `Dockerfile`

**Comment by lephuongbg** [comment]
`ENV RENOVATE_BINARY_SOURCE=global` seems to fix it.
