### ISSUE TITLE
NPM client config not working

### ISSUE THREAD

**Issue by pyrostew** [renovatebot/config-help#576]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Azure DevOps Server

### Have you checked the logs? Don't forget to include them if relevant

[renovate.log](https://github.com/renovatebot/config-help/files/4342620/renovate.log)

### What would you like to do?

I am trying to setup Renovate on a repository on an internally hosted Azure DevOps Server, The aim at the moment is simply to get Renovate to onboard the repository before I start to working out how I want it to work.

It seems that Renovate is able to communicate correctly with the server as I get a new on boarding branch each time I run it. However Renovate seems to be unable to download the default configs from NPM.

There are some configurations that need to be applied to the NPM client to get it to work on my network:
[NPMConfig.npmrc](https://github.com/renovatebot/config-help/files/4342696/NPMConfig.txt)

But I have been unable to configure Renovate with these settings to get them to work. I have tried adding the .npmrc to the repository and adding the npmrc section to the Renvoate client config. Neither seems to work.

**Comment by rarkins** [comment]
> However Renovate seems to be unable to download the default configs from NPM.

Can you clarify what you mean by "download the default configs"?

**Comment by pyrostew** [comment]
Towards the end of the log Renovate seems to be trying to download some sort of config file from NPM:
![image](https://user-images.githubusercontent.com/45209147/76899458-7b82c080-688f-11ea-8308-18c4d450d9ba.png)

My understanding is that this will be the default config file that is put into the repository during the onboarding.

**Comment by rarkins** [comment]
Maybe it’s your Zscaler MITM that’s causing the request errors. Possibly your custom certificate setup hasn’t taken effect?

**Comment by pyrostew** [comment]
So that was causing an issue with the standalone NPM client, but with the settings in the .npmrc the standalone client works fine now, so how do I get Renovate to make use of those settings?

**Comment by viceice** [comment]
I think it's the ssl certificate, which is not accepter by renovate (renovate doe not use the settings from npmrc to fetch packages). 

Renovate supports proxy setting since [13.140.0](https://github.com/renovatebot/renovate/releases/tag/13.140.0)

**Comment by pyrostew** [comment]
Okay, what is the [npmrc](https://docs.renovatebot.com/configuration-options/#npmrc) section used for in the renovate config?

**Comment by viceice** [comment]
for the lockfile updates by npm / yarn / pnpm

**Comment by pyrostew** [comment]
ahh, I see, okay I think I'm going to have to change tack. Thanks for the help.
