### ISSUE TITLE
[Question] Deprecated version still visible in PRs

### ISSUE THREAD

**Issue by louiscloutierdakis** [renovatebot/config-help#577]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant
 "updates": [
              {
                "fromVersion": "0.5.19",
                "toVersion": "0.6.7",
                "newValue": "^0.6.7",
                "newMajor": 0,
                "newMinor": 6,
                "updateType": "minor",
                "isSingleVersion": false,
                "isRange": true,
                "releaseTimestamp": "2015-09-10T06:29:03.335Z",
                "canBeUnpublished": false
              },
              {
                "fromVersion": "0.5.19",
                "toVersion": "1.1.0",
                "newValue": "^1.1.0",
                "newMajor": 1,
                "newMinor": 1,
                "updateType": "major",
                "isSingleVersion": false,
                "isRange": true,
                "releaseTimestamp": "2020-03-17T18:19:23.020Z",
                "canBeUnpublished": true
              }
            ],

### What would you like to do?

Hi, renovate try to update a dependency to a deprecated version: https://www.npmjs.com/package/react-images/v/0.6.7
![image](https://user-images.githubusercontent.com/8480459/76973625-95131f00-6906-11ea-9bc8-517fbeafc52d.png)

In the log we can see 2 updates ^0.6.7 and ^1.1.0. We should only have ^1.1.0 since ^0.6.7 is deprecated. Is this behavior normal? Do we have to add a new config to ignore deprecated version?

**Comment by rarkins** [comment]
This happens because the current version is also deprecated. Renovate won't upgrade from non-deprecated to deprecated, but it will propose upgrades from deprecated to deprecated. I think this is the correct behaviour (e.g. for people who can't upgrade to 1.x yet) but maybe we should indicate in the PR that both are deprecated.

**Comment by louiscloutierdakis** [comment]
ok thanks
