### ISSUE TITLE
Is it possible to FORCE ON-DEMAND to commit package-lock.json if there is not an existing one on the repository?

### ISSUE THREAD

**Issue by dominguezcelada** [renovatebot/config-help#578]
### Which Renovate are you using?
Renovate Open Source CLI
Self hosted one, with Docker: https://hub.docker.com/r/renovate/renovate/

### Which platform are you using?
GitHub.com

### What would you like to do?
We are calling programatically renovate bot everytime a release of a package is done. A Jenkins job hosting this Docker image with renovate is called with the proper parameters. We would like to call it and, if the repository we want to  upgrade its dependencies does not have a package-lock.json, generate it and commit it to renovate's PR. Once it's generated, rest of the times can work as usual.

We've been playing with `renovate.json` -> `"lockFileMaintenance": { "enabled": true }` but what we found in issues is that is triggered periodically and the max frequency I found is daily which is not enough.

Is there a way to bump the package-lock.json only once?

Here is the config we are using:
```json
{
	"enabled": true,
	"packageRules": [{
		"bumpVersion": "patch",
		"commitMessagePrefix": "build(renovate) ",
		"groupName": "@dummy-dependencies",
		"ignoreUnstable": true,
		"ignoreNpmrcFile": true,
		"labels": ["dependencies", "merge"],
		"packagePatterns": ["^@dummy"],
		"rangeStrategy": "update-lockfile",
  		"lockFileMaintenance": { "enabled": true }
	}]
}
```
Thanks

**Comment by rarkins** [comment]
Renovate is not intended to add a `package-lock.json` if it wasn't already found. If lock file maintenance does that, it was unintended.

**Comment by dominguezcelada** [comment]
Thanks for the quick answer! We didn’t get a chance to see lockMaintainance in action. So... there is not a way through renovatebot to generate it right?

Thanks for your help

**Comment by rarkins** [comment]
No, there is currently no way for Renovate to *create* a lock file - only to update them. But you could see repositories with essentially empty lock files and that would be enough.

**Comment by dominguezcelada** [comment]
Awesome!

Thanks for your help! :)
