### ISSUE TITLE
What is the order of execution of `postUpdateOptions` and `postUpgradeTasks`?

### ISSUE THREAD

**Issue by vidavidorra** [renovatebot/config-help#580]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I couldn't find this in the docs, but what would be the execution order of `postUpdateOptions` and `postUpgradeTasks`? We need to do `go mod download` and `go mod tidy`, in that order.

Now, `postUpdateOptions` be configured to `gomodTidy` to run `go mod tidy`, so I need to configure `postUpdateOptions` to just run `go mod download` **only** the execution order is as follows. Otherwise I'll use `postUpdateOptions` to run both commands.

1. `postUpgradeTasks`
2. `postUpdateOptions`

**Comment by rarkins** [comment]
`postUpgradeTasks` aren't supported in the app for security reasons.

For tidying, you can check out the source code here to see how the logic works: https://github.com/renovatebot/renovate/blob/master/lib/manager/gomod/artifacts.ts

Renovate runs `go get -d ./...` before `go mod tidy` (if enabled).

**Comment by vidavidorra** [comment]
@rarkins Thanks for the quick response again. I'll have a look at that, thanks.

So `postUpgradeTasks` would only apply to self-hosted runners right? Is that the case for all items with the following? Then I know that I don't have to ask when I see some feature with a note about the `trustLevel` :)

> This is only available on Renovate instances that have a trustLevel of 'high'

**Comment by rarkins** [comment]
Yes, the app never has trustLevel high, so it's only if (a) you host it yourself, and (b) you set trustLevel to high
