### ISSUE TITLE
PRs marked with "Automerge: Enabled." not being automatically merged.

### ISSUE THREAD

**Issue by NickyMeuleman** [renovatebot/config-help#581]
### Which Renovate are you using?

WhiteSource Renovate App (github)

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Yes, especially this part seems relevant
```
DEBUG: Checking #57 for automerge(branch="renovate/gatsby-monorepo")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
```

### What would you like to do?

Automatically merge PRs that have `Automerge: Enabled.`

example:
https://github.com/NickyMeuleman/nicky-blog/pull/58

**Comment by rarkins** [comment]
There should be additional logs that indicate why it can’t automerge. Check through all debug messages for the same branch

**Comment by NickyMeuleman** [comment]
<details>
<summary>Relevant logs</summary>
DEBUG: Found PR #57(branch="renovate/gatsby-monorepo")
DEBUG: Returning from graphql open PR list(branch="renovate/gatsby-monorepo")
DEBUG: Found existing PR(branch="renovate/gatsby-monorepo")
DEBUG: Removing duplicate release notes(branch="renovate/gatsby-monorepo")
{
  "depName": "gatsby-plugin-google-analytics"
}
DEBUG: Removing duplicate release notes(branch="renovate/gatsby-monorepo")
{
  "depName": "gatsby-plugin-manifest"
}
DEBUG: Removing duplicate release notes(branch="renovate/gatsby-monorepo")
{
  "depName": "gatsby-plugin-netlify"
}
DEBUG: Removing duplicate release notes(branch="renovate/gatsby-monorepo")
{
  "depName": "gatsby-plugin-react-helmet"
}
DEBUG: Removing duplicate release notes(branch="renovate/gatsby-monorepo")
{
  "depName": "gatsby-plugin-sitemap"
}
DEBUG: getBranchStatus(renovate/gatsby-monorepo)(branch="renovate/gatsby-monorepo")
DEBUG: branch status check result(branch="renovate/gatsby-monorepo")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/gatsby-monorepo")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
DEBUG: Processing existing PR(branch="renovate/gatsby-monorepo")
DEBUG: getBranchStatus(renovate/gatsby-monorepo)(branch="renovate/gatsby-monorepo")
DEBUG: branch status check result(branch="renovate/gatsby-monorepo")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/gatsby-monorepo")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
DEBUG: getBranchStatus() result(branch="renovate/gatsby-monorepo")
{
  "branchStatus": "yellow",
  "branchName": "renovate/gatsby-monorepo"
}
DEBUG: Pull Request #57 does not need updating(branch="renovate/gatsby-monorepo")
DEBUG: Checking #57 for automerge(branch="renovate/gatsby-monorepo")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/gatsby-monorepo")
DEBUG: getBranchStatus(renovate/gatsby-monorepo)(branch="renovate/gatsby-monorepo")
DEBUG: branch status check result(branch="renovate/gatsby-monorepo")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/gatsby-monorepo")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
DEBUG: PR is not ready for merge (branch status is yellow)(branch="renovate/gatsby-monorepo")
</details>

Is it trying to run checks eventhough I don't have any?

The docs say:
> Note: if you have no tests but still want Renovate to automerge, you need to add "requiredStatusChecks": null to your configuration.

However, my editor won't let me set `"requiredStatusChecks"` to anything other than an array type because of the JSON-schema it is checking against.
This one: https://docs.renovatebot.com/renovate-schema.json

For that reason I set `"requiredStatusChecks": []`, are those equivalent?
Should I try setting it to `null` anyway?

**Comment by rarkins** [comment]
Right, set then to `null`

**Comment by NickyMeuleman** [comment]
Thanks!

The PRs with "Automerge: Enabled." in the PR text are now automatically merged (tested by temporarily removing the schedule)

Is that schema available opensource to edit?
I'd like to modify it to take `null` as valid value and not throw an error.

**Comment by rarkins** [comment]
Our JSON schema is automatically generated from this code: https://github.com/renovatebot/renovate/blob/5fdd261d5ab0a182955b3c166a1454ee8bf001f3/lib/config/definitions.ts#L1141-L1149

The generation code is here: https://github.com/renovatebot/renovate/blob/master/bin/create-json-schema.js

A PR would be welcome. If any non-trivial changes are required, please create an issue in the main repo to discuss.
