### ISSUE TITLE
[GitLab] renovate-bot keeps renaming MRs

### ISSUE THREAD

**Issue by tehshane** [renovatebot/config-help#582]
It seems that poor renovate-bot can't make up its mind on what to title its merge requests in GitLab. It's waffling between conventional commit syntax and not.

![image](https://user-images.githubusercontent.com/3360089/77461777-537beb80-6dc0-11ea-8db0-31a6bc869f0e.png)

This isn't overly disruptive to us, but figured it was worth bringing up as it is generating a fair bit of noise in the MR history. Is this by design for some purpose?

**Comment by tehshane** [comment]
If this is the wrong repo to post to, please let me know and I'll repost at renovatebot/renovate

**Comment by rarkins** [comment]
If left to defaults, it checks the last 10 commits and if more than 3 of them have conventional commits then it uses them (numbers are from memory..). You can turn it on or off permanently with `semanticCommits` setting

**Comment by tehshane** [comment]
Thanks, I'll add `:semanticCommits` to my `extends` array as [the docs suggest](https://docs.renovatebot.com/semantic-commits/) and see if that quiets it down.
