### ISSUE TITLE
BitBucket Server - Fork Repo provided in config vs CLI

### ISSUE THREAD

**Issue by alexhancock** [renovatebot/config-help#583]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

Yes - logs included in the section below.

### What would you like to do?

I want to run the `renovate` command for a list of repositories and have the log output related to each repository go to a separate file.

This list will contain forks of repositories under people's personal namespace on our Bitbucket Server (ie...  `https://BITBUCKET_SERVER_HOSTNAME/users/USERNAME/repos/REPONAME/browse`) as well as repositories under other "project keys" which are shared inside our company.

I had a setup working where I had all repositories listed under a `repositories` key in the object exported by `config.js` but I could not figure out how to have the logs for each repo go to a separate log file on disk.

To solve this, I reworked my solution to loop over the array of repositories and call the `renovate` command once per repo passing a different filename to the `--log-file` option and passing the repo name at the end of the command. When I did this, renovate stopped working for repositories which are forks under an individual bitbucket user's account. I confirmed the bitbucket user it is authenticating as has access to the fork with the "admin" level of permissions.

So to recap: for a repo `https://BITBUCKET_HOSTNAME/users/alexhancock/repos/foo/browse` having...

```
...
repositories: ['~alexhancock/foo']
...
```

... in `config.js` and running `renovate` works. When I run...

```
renovate --log-file=foo-logs.log ~alexhancock/foo
```

I get the following error...

```
{"name":"renovate","hostname":"REDACTED","pid":95010,"level":20,"logContext":"NnGG4AV5A","repository":"alexhancock/foo","err":{"message":"fatal: remote error: Repository not found\nThe requested repository does not exist, or you do not have permission to\naccess it.\n","stack":"Error: fatal: remote error: Repository not found\nThe requested repository does not exist, or you do not have permission to\naccess it.\n\n    at toError (/REDACTED/node_modules/simple-git/promise.js:90:14)\n    at REDACTED/node_modules/simple-git/promise.js:61:36 ... }
```

**Comment by viceice** [comment]
Currently renovate dosn't support splitting logfiles.

I think you need to escape the  `~`, so try run 
```sh
renovate --log-file=foo-logs.log '~alexhancock/foo'
```

**Comment by alexhancock** [comment]
That did it - thank you @viceice!
