### ISSUE TITLE
Self Hosted Renovate

### ISSUE THREAD

**Issue by piclemx** [renovatebot/config-help#586]
### Which Renovate are you using?

Renovate Container image

### Which platform are you using?

GitLab EE self-hosted

### Have you checked the logs? Don't forget to include them if relevant

Yes

### What would you like to do?

We have our own Container Image Registry, Nexus Repository, etc.

I take a look at the default preset.

Just wanna know what is the recommend way to do it if I deploy for now Renovate inside k8s with the cronjob.

I will like to put our eslint config also in the renovate.

**Comment by viceice** [comment]
I think, you should read the [general](https://docs.renovatebot.com)  and the [self-hosting](https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md) docs.

And then please ask clear Questions. It's not clear what you are trying to do.

**Comment by piclemx** [comment]
I read both and don't find anything clear to me how to configure the container image to make what I want.

I don't have anything special. I don't see anything interesting for the container image. How do we configure renovate with that.

If I want to have configure it. The recommend way is to do it with the `config.js`?

We got our own nexus for java executable. We have our own container images repository.

I want to put those rules in all of my repository without to have to do in each repository.
It is possible?

**Comment by viceice** [comment]
Ok, as you want to use kubernetes you can try our brand new [helm-chart](https://github.com/renovatebot/helm-charts).

Otherwise you have to map the `config.js` or `config.json` to `/usr/src/app/` folder inside the running container.

Also be sure, to not somply copy the kubernets cronjob. You have to update the image version to a recent version, otherwise you will get into errors because of api changes.

**Comment by viceice** [comment]
@JamieMagee  is able to help you, if you have any trouble with the helm-chart. 🙃

**Comment by piclemx** [comment]
I'm using  Pulumi to deploy but yeah great to know that has changed :)

Could it be possible to let secret like api token in env variable and put the other things in the `config.json`?

**Comment by piclemx** [comment]
I'm using the newer version of renovate 😄 . I saw the one in the example is quite old lol.

**Comment by viceice** [comment]
You can use env variables, see [usage](https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#usage)

The cronjob contains sample for using secrets as env vars.

**Comment by piclemx** [comment]
Could I used both that was more the question.

**Comment by viceice** [comment]
sure, you can mix env, cli and config file.  They will merged in following order:


1. default values
2. config file
3. cli args
4. env vars

**Comment by piclemx** [comment]
Awesome!

For the maven things. If we got the our own nexus. Should it be possible to put it in the renovate config instead of each repo?

**Comment by viceice** [comment]
which maven things do you mean? You can add [`hostRules`](https://docs.renovatebot.com/configuration-options/#hostrules) to add auth data for nexus host.

**Comment by piclemx** [comment]
On each repo on only in the renovate config?

**Comment by rarkins** [comment]
Any configuration options in https://docs.renovatebot.com/configuration-options/ can also be defined in the bot's `config.js` config too

**Comment by piclemx** [comment]
Do you know what that means the `WARN: Config needs migrating` when putting my `config.json`?

**Comment by viceice** [comment]
Check the debug logs, they will show you the required changes.

**Comment by rarkins** [comment]
Actually it should tell him below that exact WARN. @piclemx read the full message, and do a diff if you need.

**Comment by piclemx** [comment]
Yeah I did the things with the diff... wasn't really obvious initially.

I added a host rule

```
"hostRules": [
        {
            "hostType": "maven",
            "baseUrl": "endpoint"
        }
    ],
```

But It seems that is not take into account.? Any Idea?

**Comment by rarkins** [comment]
That hostrule doesn’t do anything. You probably mean to set `registryUrls` instead of `endpoint`?
