### ISSUE TITLE
Configuring Immortal PRs / Configuring versions Renovate upgrades

### ISSUE THREAD

**Issue by 9to5grind** [renovatebot/config-help#587]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Cloud

### Have you checked the logs? Don't forget to include them if relevant

I dont think its relevant to this issue

### What would you like to do?

Hi, We have been trying to get setup with this software and have got to the point where renevate has created many branches and pull requests.

Some of those pull requests are set as immortal. I understand this is due to grouping of dependency updates. For instance when it has tried to update symfony 3 to 5, it also wanted to upgrade swiftmailer, and phpunit-bridge.

Currently due to our workflow it is not practical for us to take on such a large major framework update and we would like to close this pull request however it sais **"Immortal: This PR will be recreated if closed unmerged. Get config help if that's undesired."**. If possible we would not like this to be re-opened everytime the repository is scanned as updating a major version we feel is a manual job. as their could be some code changes too. Can immortal pull requests be somewhat disabled or changed in the config?

In the spirit of that more importantly, can the config be changed so that Renovate only upgrades dependencies minor / bugfix versions instead of major versions as then that would solve the above issue aswell and leave us the manual job of upgrading a major change of moving symfony 3 - 5 for instance.

Any config examples you can throw our way would be helpful, thanks very much.

**Comment by viceice** [comment]
You can use a simple [`packageRules`](https://docs.renovatebot.com/configuration-options/#packagerules):

```json
"packageRules": [
  {
    "packageNames": ["symfony", "swiftmailer", "phpunit-bridge"],
    "extends": [":disableMajorUpdates"]
  }
]
```

or completly disable major updates

```json
"extends": [":disableMajorUpdates"]
```

**Comment by 9to5grind** [comment]
Thanks very much :)
