### ISSUE TITLE
Range strategy auto

### ISSUE THREAD

**Issue by GuillaumeRahbari** [renovatebot/config-help#588]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitLab.com

### Have you checked the logs? Don't forget to include them if relevant

I checked the log but did not find what I was looking for in it.
Here is an example if it helps https://app.renovatebot.com/dashboard#gitlab/live-makers-team/live-maker/157247250

### What would you like to do?

I would like to know how the range strategy auto works https://docs.renovatebot.com/configuration-options/#rangestrategy
In particular this line "Pin dependencies if we detect that it's an app and not a library"

How do you "detect". I have some projects that I consider "app" but are considered "library" by renovate.
So I'd like to know how renovate make the choice (in order to correct my project configuration)

**Comment by viceice** [comment]
See https://github.com/renovatebot/renovate/blob/5ce5ef39c190153e56cdac3915604d6cfa8595af/lib/manager/npm/extract/type.ts#L3-L16

**Comment by viceice** [comment]
and
https://github.com/renovatebot/renovate/blob/5ce5ef39c190153e56cdac3915604d6cfa8595af/lib/manager/npm/range.ts#L6-L44

**Comment by GuillaumeRahbari** [comment]
Oh great thank you ! I understand now !
