### ISSUE TITLE
git-tags http auth on same host as endpoint

### ISSUE THREAD

**Issue by micheelengronne** [renovatebot/config-help#589]
### Which Renovate are you using?

Renovate Open Source CLI (self-hosted)

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

I would like to use git-tags manager with a private git repository on the same gitlab that provides the endpoint.

It works when I hardcode the git credentials (like https://username:password@gitlab.example.com) but I would like to provide these credentials as a hostRule in my config.js.

How can I achieve that ?

I tried to add that in my hostRules:

```
   {
     hostType: 'gitlab',
     hostName: 'gitlab.example.com',
     username: 'gitlab-ci-token',
     password: 'PASSWORD',
   },

```
with the following permissions (very wide):

```
api, read_repository, write_repository, read_registry
```
but the log gives (for every repository):

```
         {
           "name": "renovate",
           "level": 50,
           "logContext": "LOGCONTEXT",
           "repository": "Example/repository",
           "msg": "Repository is not found"
         },

```
I suppose it is a conflict with the endpoint.

**Comment by micheelengronne** [comment]
Note, I prefer to use git-tags in place of gitlab-tags to ensure a better portability. I plan to migrate from gitlab.

**Comment by micheelengronne** [comment]
When I configure my hostRules that way (like Github):

```
   {
     hostType: 'gitlab',
     hostName: 'gitlab.example.com',
     token: 'PASSWORD',
   },

```

Then the endpoint works. But the repository that uses git-tags gives:

```
 INFO: Repository started (repository=Example/repository)
       "renovateVersion": "19.181.1"
 INFO: Extraction statistics (repository=Example/repository)
       "stats": {
         "managers": {
           "gitlabci": {"fileCount": 1, "depCount": 6},
           "regex": {"fileCount": 1, "depCount": 1}
         },
         "fileCount": 2,
         "depCount": 7
       }
fatal: could not read Username for 'https://gitlab.example.com': No such device or address
```

**Comment by viceice** [comment]
you can't use `git-tags` datasource, as it's currently designed to work on the local repository only.

So you have to use `gitlab-tags` or `github-tags` for now

**Comment by micheelengronne** [comment]
Ok. How do I do when I migrate to gitea ?

**Comment by micheelengronne** [comment]
BTW, `git-tags` datasource works like a charm when the auth credentials are hardcoded in the repository.

**Comment by micheelengronne** [comment]
It also works well when a repository is public (no auth). I fetched some github dependencies with it.

**Comment by viceice** [comment]
yes, i've look at the code now. Currently there is no possibillity to setup `hostRules` for that.

Feel free to open a [feature request](https://github.com/renovatebot/renovate/issues/new?template=4-Feature_request.md)

**Comment by micheelengronne** [comment]
Ok
