### ISSUE TITLE
package-lock.json causes error when creating PR's

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#591]
### Which Renovate are you using?
Renovate Open Source CLI using the renovate/renovate:slim docker image

### Which platform are you using?
GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Branch updated (repository=CTAgile/direct-order-correction-service, branch=renovate/pin-dependencies)
      "commitHash": "666c535"
INFO: PR updated (repository=CTAgile/direct-order-correction-service, branch=renovate/pin-dependencies)
      "pr": 31,
      "prTitle": "Pin dependency llb-ocs-utilities to 3.1.0"
WARN: artifactErrors (repository=CTAgile/direct-order-correction-service, branch=renovate/pin-dependencies)
      "artifactErrors": [
        {
          "lockFile": "package-lock.json",
          "stderr": "docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.\n"
        }
      ]

```

### What would you like to do?
Since I enabled package-lock.json on my repos and added lockFileMaintenance option on the renovate config file, I get the following error on logs when PR's are created:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock
```

and the PR email notification says the following:

```
⚠️ Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻️ Renovate will retry this branch, including artifacts, only when one of the following happens:

any of the package files in this branch needs updating, or
the branch becomes conflicted, or
you check the rebase/retry checkbox if found above, or
you rename this PR's title to start with "rebase!" to trigger it manually
The artifact failure details are included below:

File name: package-lock.json

docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

See 'docker run --help'.
```

config file is the following:
```
module.exports = {
  endpoint: 'https://gh.llbean.com/api/v3/',
  platform: 'github',
  logFile: '/dist/renovate.log',
  onboarding: true,
  onboardingConfig: {
    extends: ['config:base']
  },
  autodiscover: true,
  autodiscoverFilter: 'CTAgile/+(*ticket-manager|*failure-checker|*document-server)',
  requireConfig: true,
  automerge: false,
  extends: ['group:allNonMajor'],
  enabledManagers: ['npm'],
  rangeStrategy: 'pin',
  recreateClosed: true,
  stabilityDays: 7,
  prCreation:'not-pending',
  lockFileMaintenance: { enabled: true },
  labels: [
    'renovate'
  ]
};
```

Before I added package-lock.json, PR's were created just fine.  Any ideas what could be causing this issue ?

**Comment by viceice** [comment]
Did you read the error message? It clearly says that docker service isn't available.

The slim image needs a docker service to run artifact updates. So you need to mount the docker socket to the renovate slim container. 

If this isn't possible for you, you need to use the full renovate image or build your own.

**Comment by rvillane** [comment]
thanks @viceice for the quick response, yes, I did read the error message, but my lack of understanding of how this overall feature works makes it hard to fully digest what the error message means.

Just by chance do you have any example of how to mount the docker socket to the renovate slim container?  I'm a bit clueless how that is done, if you can point me in the right direction here is highly appreciated.

thanks

**Comment by viceice** [comment]
`docker run ... -v /var/run/docker.sock:/var/run/docker.sock renovate/renovate:slim`

**Comment by rvillane** [comment]
OK, I'm now using the full renovate docker image running as a pod in Kubernetes, and the "Cannot connect to the Docker daemon at unix:///var/run/docker.sock" error is gone, however, PR's still get an error related to package-lock.json, logs show the indication that some error occurred , however, doesn't include any error message describing what is going on.

"artifactErrors": [{"lockFile": "package-lock.json", "stderr": ""}]

any suggestions about next steps?

**Comment by rarkins** [comment]
Option 1: run at full debug or even trace level. Do this on a run where a (failed) lock file is updated. e.g. tick the rebase/retry box

Option 2: simplify. troubleshoot it outside k8s first, in case that's contributing to the problem

**Comment by rvillane** [comment]
I gave option #1 a quick try and just by changing LOG_LEVEL env var from "info" to "debug" , I didn't get the package-lock.json error and I see package.lock was adjusted as expected.  I will conduct further testing later, as this result is unexpected.

**Comment by rvillane** [comment]
I can confirm the odd behavior previously described, if log level is debug , package-lock.json is updated as expected, but If log level is info, then PR’s get the error trying to update the lock file. 

While the workaround to overcome this issue was casually discovered troubleshooting, it feels like some buggy behavior is happening here.

**Comment by rarkins** [comment]
It would be extraordinary if the log level changed the functional behavior. Are you certain of this? e.g.
- Run on info, it fails
- Run on debug, it works
- Run again on info, it fails
- Run again on debug, it works

**Comment by rvillane** [comment]
false alarm, another execution today with logging level on debug failed again, this time logs provide extra details about the potential root cause:


```
DEBUG: Generating package-lock.json for . (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
DEBUG: Spawning npm install to create /tmp/renovate/repos/github/CTAgile/atpservice/package-lock.json (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
DEBUG: No locally installed npm found (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
DEBUG: Could not find globally nested npm (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
DEBUG: Using npm: node /usr/lib/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
DEBUG: Executing command (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
       "command": "node /usr/lib/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit"
DEBUG: lock file error (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
       "cmd": "node /usr/lib/node_modules/npm/bin/npm-cli.js",
       "args": "install --package-lock-only --no-audit",
       "err": {
         "killed": false,
         "code": null,
         "signal": "SIGKILL",
         "cmd": "node /usr/lib/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit",
         "stdout": "",
         "stderr": "",
         "message": "Command failed: node /usr/lib/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\n",
         "stack": "Error: Command failed: node /usr/lib/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:311:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:311:20)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at Pipe.<anonymous> (net.js:668:12)"
       },
       "stdout": "",
       "stderr": "",
       "type": "npm"
DEBUG: No updated lock files in branch (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
DEBUG: Branch timestamp: 2020-04-02T13:13:35.912Z (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
DEBUG: PR is older than a day, raise PR with lock file errors (repository=CTAgile/atpservice, branch=renovate/all-minor-patch)
```

After running a quick experiment, this could associated to running renovate full docker image in Kubernetes.  I ran renovate as the standalone cli tool on my local machine and package-lock.json file is getting generated properly.  The main reason why we execute renovate as a kubernetes pod is because we can expose the GHE PAT as a secret, PAT is never revealed in plain text or stored in source control.

Any recommendations on how to fix this ?

**Comment by rvillane** [comment]
Do you have any ideas on next steps here ?

**Comment by rarkins** [comment]
It says that the command failed due to a `SIGKILL`, which indicates that it was terminated. Does anything in your kubernetes look for child processes and kill them, maybe as a security measure?

**Comment by rvillane** [comment]
I'm troubleshooting to try to figure out what is going on.  Just by chance has this user case be tested before?  running renovate as a k8s pod and having package-lock.json enabled ?

**Comment by rarkins** [comment]
I haven't used it myself, but I had the impression that others were running Renovate within k8s.

**Comment by rvillane** [comment]
No doubt, it worked fine for me until I enabled package-lock

**Comment by leschdom** [comment]
I just skimmed through the previous messages, but wanted to share what I did to workaround:

> Renovate Open Source CLI using the renovate/renovate:slim docker image
I also got the error message "docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.\n"

When I switched the image from `renovate/renovate:slim` to just `renovate/renovate` I didn't get the error 
```
"artifactErrors": [
        {
          "lockFile": "package-lock.json",
          "stderr": "docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.\n"
        }
      ]
```
any longer. Don't know exactly why - but maybe docker isn't available in the :slim image?

**Comment by viceice** [comment]
yes, you need to mout the host docker socket to the renovate container if you'r running the slim version

**Comment by rvillane** [comment]
quick update, if I run renovate as a standalone CLI tool, it works just fine without any issues with package-lock.  I'm moving away from running renovate as a Kubernetes pod.
