### ISSUE TITLE
Automerge patch updates

### ISSUE THREAD

**Issue by adamu** [renovatebot/config-help#597]
# Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I want to auto-merge patch updates. I followed the instructions for [automerge](https://docs.renovatebot.com/configuration-options/#automerge) and created the following config:

```
"packageRules": [
  {
    "updateTypes": ["patch"],
    "automerge": true
  }
]
```

However, 20 minutes later, a `patch` PR was created with the comment:

> | Package | Update | Change |
> |---|---|---|
> | [com.amazonaws:aws-java-sdk-bom](https://aws.amazon.com/sdkforjava) | patch | `1.11.755` -> `1.11.757` |
> 
> ---
> 
> ### Renovate configuration
> 
> :vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

How can I configure renovate to automerge only patch updates?

**Comment by viceice** [comment]
Have you checked the debug logs? Is there any other package rule after the automerge, which overrides?

**Comment by adamu** [comment]
Here is part of the log:

```
DEBUG: Created Pull Request #XX(branch="renovate/aws-java-sdk-monorepo")
DEBUG: Checking #XX for automerge(branch="renovate/aws-java-sdk-monorepo")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/aws-java-sdk-monorepo")
```

And the config (abbreviated):


```
{
  "configFile": ".github/renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "automerge": false,
    "packageRules": [
      {
        "updateTypes": [
          "patch"
        ],
        "automerge": true
      }
    ]
  }
}
```

**Comment by rarkins** [comment]
Add `separateMinorPatch=true` to your config. By default Renovate classifies updates as either major or non-major and does not split patch and minor updates separately.

**Comment by adamu** [comment]
`separateMinorPatch` fixed it, thanks @rarkins!
