### ISSUE TITLE
How to correctly generate public/private key pair

### ISSUE THREAD

**Issue by fgreinacher** [renovatebot/config-help#598]
### Which Renovate are you using?
Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

We want to use Renovate's `encrypted` functionalty in our self-hosted setup (similar to what you mentioned in https://github.com/renovatebot/config-help/issues/331#issuecomment-522551925) and are struggling to generate a public/private key pair that works both for renvoate itself and also the encryption site.

Could you provide a snippet on how to generate the keys correctly? Once we got it working I'll open a PR against https://docs.renovatebot.com/self-hosted-configuration/#privatekey.

**Comment by rarkins** [comment]
I did it once, and it was long ago, so unfortunately I need to retrace this myself.

Looking at the source of https://renovatebot.com/encrypt, here's the public key for the Renovate App:

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0u6+kZ7yoy1IMUjfoDY+
WwaTtfaQyLmYM/bs/CtekvDFbSQnOHIunnLKFo8OQW/PeLBur+BIcfzS5spVpXB5
07P3yzf/mUYwX3sdy1Zu3JdcWKKho793niIAdKNQg48xipCniVg6J5l3WK5816KB
Dc2+Bjwer2z5cE9G1pUPRnK3m0uHrVsFxmMnk38RZcZnGmokoBzMjUa/2w1kCHuD
Eq3kdSHvLBmmo5bP9OHHV9F4KVlB8cDp3TSc74U0BVEUDe3BBf9VgXfvqhjDTRJh
lpC+QxgdBj958K/h8BnRB6vkW3l5OXirowyXg4ZAWQn0XJ+lby5w7yCg4HetyYH5
0QIDAQAB
-----END PUBLIC KEY-----
```

It uses the JSEncrypt library like so:
```
var crypt = new JSEncrypt();
crypt.setKey(publicKey);
const encrypted = crypt.encrypt(input);
```

JSEncrypt includes information on generating a keypair using `openssl`, although I'm not sure if I used 1024 or something lower.

On the Node.js side, this is the code that is executed:

```
              decryptedStr = crypto
                .privateDecrypt(
                  {
                    key: privateKey,
                    padding: crypto.constants.RSA_PKCS1_PADDING,
                  },
                  Buffer.from(eVal, 'base64')
                )
                .toString();
```

I would suggest to try:
- Generate a private/public 1024 bit key as per the JSEncrypt example
- Save a copy of Renovate's encrypt.html locally and edit it
- Replace the public key with the one you generated
- Try encrypting using this new key
- See if you can test using the unit tests we have in lib/config/decrypt.spec.ts

**Comment by fgreinacher** [comment]
Thanks, we got it working by following the steps from the JSEncrypt website. I'll update the docs
