### ISSUE TITLE
Allow filtering Managers without autoclosing existing PRs (self-hosted)

### ISSUE THREAD

**Issue by Tanuel** [renovatebot/config-help#600]
**What would you like Renovate to be able to do?**

We are running (selfhosted) Renovate across a lot of projects. Now we want to implement a new level of automation into our pipelines.

We have a set of Portals hosted in the Cloud, rolled out with Terraform. Those modules will be tagged with Semantic Release on each push.

We then want renovate to run across said projects but only enable the Terraform Manager. This can be achieved through the GitLab Pipeline API, which sets an env variable FILTER_MANAGERS

We use a construct in `config.js` as follows:

```javascript
let enabledManagers = undefined;
if ('FILTER_MANAGERS' in process.env) {
  enabledManagers = process.env.FILTER_MANAGERS.split(",");
  console.info("Restricting managers to", process.env.FILTER_MANAGERS);
}

module.exports = {
  enabledManagers,
  //... rest of config
}
```

**The Problem** 

Now the Problem here is that this will autoclose all existing PRs from other Managers. Those PRs will not be recreated in subsequent runs and those dependencies will not be updated by renovate until a new version for that is released. This closed roughly 60 PRs that were waiting for manual merge.

**Describe the solution you'd like**

Provide a new Configuration Variable `filterManagers` that is available for self-hosted.
Unlike `enabledManagers`, this will not close existing PRs, but rather ignore those completely

Changing the logic of enabledManagers feels wrong as it seems to be the desired behaviour
The differences in behaviour between those options should documented and link to the respective other option

**Describe alternatives you've considered**

I thought maybe `packageRules` could get something like this done, however it feels very hacky and unintuitive.

**Additional context**

As i have contributed before, i will provide an implementation if you would accept this Feature  Request.

Our Goal is to use renovate to update specific projects asap when a dependency gets tagged in a new version.

**Comment by Tanuel** [comment]
Okay, i guess that solves my Problem. I still think that having such an option/behaviour would be helpful, but i guess it would be very complicated to implement.

Thanks for the heads up!

**Comment by Tanuel** [comment]
Maybe i was too fast with closing this issue... Now some PRs will be duplicated. Once by the first renovate instance which runs everything, and then again by the second instance that runs only terraform specifically. This will increase ci noise and obsolete PRs will possibly not be closed properly.

![renovate-duplicates](https://user-images.githubusercontent.com/28950300/78539281-92fbfc00-77f2-11ea-9de3-bccfc18ed02b.png)

Any Ideas on how to resolve this issue?

**Comment by rarkins** [comment]
So you want both your regularly-scheduled Renovate as well as your on-demand Renovate to both manage the same Terraform PRs?

Back to your original approach, what if you run the on-demand Renovate using the flag `pruneStaleBranches: false` in additional setting `enabledManagers`?

**Comment by Tanuel** [comment]
Yes, i would want to run renovate regularly, but also have the possibility to filter on specific criteria (managers, package names, etc). I think `pruneStaleBranches` was what i was looking for all along, but couldn't find it.

looking good: ` INFO: PRUNING-DISABLED: Would deleting orphan branch renovate/node-12.x`

However, now also the onboarding branches will be updated to remove all information about what is going to be updated  e.g. for npm dependencies. This is not too big of a deal, but it will spam the "Merge Requests" Tab from GitLab with updates

We use `autodiscover: true` and i would like to only run renovate on onboarded branches, so i guess `onboarding: false` will not help here. Maybe i can simply do `requireConfig: true` and not onboarded branches will be skipped?

![renovate-mr-updated2](https://user-images.githubusercontent.com/28950300/78541928-b2952380-77f6-11ea-8488-8c6bedb4ac33.png)

**Comment by rarkins** [comment]
I’m not sure what combination of onboarding settings would or might work - you’d need to test to be sure. As a general rule for your situation - don’t delay onboarding merge or close if you can help it.

**Comment by Tanuel** [comment]
Okay so this setting works:
```javascript
{
  enabledManagers: ['terraform'],
  pruneStaleBranches: false,
  autodiscover: true,
  onboarding: false,
  requireConfig: true, // default value anyways
}
```
Will be generated at runtime in config.js depending on certain parameters :+1: 

The only thing that doesn't work here is autoclosing of PRs that are covered by the enabledManagers, but that can then be done on the scheduled runs.

We only recently started activating autodiscover for all projects in our team space with over 100 projects, so checking if all projects are actually eligible takes some time :D 

Thanks a lot for the help!
