### ISSUE TITLE
Private npm module Release Notes not displayed in PRs

### ISSUE THREAD

**Issue by bensbigolbeard** [renovatebot/config-help#607]
### Which Renovate are you using?

Renovate Pro

Other (please write below)

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

No logs are output. The package updates work as expected, the release notes are just absent from the PR description.
### What would you like to do?

I'm trying to get Renovate to include release notes for our packages hosted on our internal npm. 

Currently, with `GITHUB_COM_TOKEN` set, Renovate successfully pulls in publicly available package release notes, but release notes from internally hosted packages are not included.

Examples:
One private, one public. Only public package release notes included. Private package missing link to source:
![Screen Shot 2020-04-14 at 9 16 02 AM](https://user-images.githubusercontent.com/2208816/79243750-a97e0500-7e3b-11ea-9b04-53d825332a66.png)
One private package, with link back to source:
![Screen Shot 2020-04-14 at 10 32 19 AM](https://user-images.githubusercontent.com/2208816/79243849-c7e40080-7e3b-11ea-8915-f289f418012d.png)
I included the examples with and without links to the source on the off-chance that helps narrow down possible causes.

**Are there configuration options that I should check that might control whether Renovate finds release notes from internally hosted packages?**

Is there an additional token, similar to `GITHUB_COM_TOKEN`, that's needed specifically for fetching release notes?

Some additional context:
 - each package has an accompanying `CHANGELOG.md` and uses GH Releases 
 - each package follows semantic release format
 - Renovate is properly updating outdated packages, so our auth tokens for the private registry seem to be working properly

Let me know what additional information you need and I'll try to find it.

**Comment by bensbigolbeard** [comment]
Anything jump out as a possible explanation or place to look, @rarkins? Any info would be helpful. Thanks.

**Comment by rarkins** [comment]
> Private package missing link to source

This indicators that Renovate can't find the source URL in the package metadata. Is this package hosted on npmjs.org or a private registry? Can you manually retrieve its registry data and check for if/where the source URL is included?

> One private package, with link back to source

In theory this one should be possible to retrieve release notes. Is the hostname in the source link identical to the RENOVATE_ENDPOINT you configure?

**Comment by bensbigolbeard** [comment]
> Is this package hosted on npmjs.org or a private registry?
It's private

> Can you manually retrieve its registry data and check for if/where the source URL is included?
I can run `npm info [package] --json` to see the `repository.url` for the the repo's git url (as a note in case it matters, i'm seeing them all as the `https` urls, not `ssh`). 

Is this what you're referencing or are you expecting different registry data that would output a property `source/sourceUrl`?

> Is the hostname in the source link identical to the RENOVATE_ENDPOINT you configure?
This I can check on. I didn't set up the configuration, so I'll track down where this key is set and verify.

Thanks for the suggestions. This gives me some threads to pull!

**Comment by rarkins** [comment]
Renovate parses the raw manifest for each package so we need that to be sure what’s wrong. Npm itself may have superior parsing/transforming for example. 

If you find the package.json in source though then we can probably infer what’s on the registry

**Comment by bensbigolbeard** [comment]
Ok, @rarkins. I was finally able to narrow down the likely cause to the fact that `endpoint` (and subsequently `githubApiBaseURL`) is `undefined` when the changelog is processed

![Screen Shot 2020-04-17 at 5 15 13 PM](https://user-images.githubusercontent.com/2208816/79618371-72278680-80cf-11ea-809f-53399d81ea05.png)

The `endpoint` defined in `/platform/github/index`, however, gets set correctly:

![Screen Shot 2020-04-17 at 5 21 46 PM](https://user-images.githubusercontent.com/2208816/79618787-a5b6e080-80d0-11ea-9d53-5d289d58c196.png)

So, it seems that `upgrade` is not populated with `endpoint` for some reason. 

**Do you know how to ensure this value gets populated?** Should this value be coming from `RENOVATE_ENDPOINT` or from the GitHub response itself? I dont see it getting directly assigned outside of `/platform/github/index`

**Comment by rarkins** [comment]
`endpoint` should be populated from `RENOVATE_ENDPOINT` and present in every config passed. BTW did you test this by running Renovate using the CLI instead?

**Comment by bensbigolbeard** [comment]
@rarkins pardon my delay. I got pulled into another issue this week.

I ran the docker image that we use in our renovate deployment in local debug-mode to test this. Would running the CLI produce different results?

As far as having access to `endpoint`, it seems we lose it beginning at `writeUpdates`, where we pass in `branch` to `processBranch`. After that point, we try to pull `endpoint` from `branch.upgrades[{endpoint}]`, which isn't ever populated (in `generateBranchConfig`)

At this point, i'm not sure how endpoint would ever be populated. Any ideas?
<details>
<summary>Here's the full chain that I've been stepping through in pictures:</summary>

`writeUpdates` calling `processBranch`:

![Screen Shot 2020-04-22 at 2 11 34 PM](https://user-images.githubusercontent.com/2208816/80024269-690a3100-84a4-11ea-8668-3076128cb9c6.png)

`processBranch`, spreading `branch/branchConfig` into a new `config`:

![Screen Shot 2020-04-21 at 5 58 08 PM](https://user-images.githubusercontent.com/2208816/80024438-b4bcda80-84a4-11ea-8647-d1d120b244dc.png)

`processBranch` calling `ensurePr`:

![Screen Shot 2020-04-21 at 5 57 18 PM](https://user-images.githubusercontent.com/2208816/80024494-cb633180-84a4-11ea-9a6c-d16181a7ca96.png)

`ensurePr` calling `getChangeLogJSON`:

![Screen Shot 2020-04-22 at 2 16 10 PM](https://user-images.githubusercontent.com/2208816/80024799-3876c700-84a5-11ea-88b3-30e4475b9078.png)

`getChangeLogJSON` calling `getChangeLogJSON` with `args`:

![Screen Shot 2020-04-22 at 2 16 36 PM](https://user-images.githubusercontent.com/2208816/80025328-15004c00-84a6-11ea-81f9-d19863d2e5f6.png)

`getChangeLogJSON` where we expect to have `endpoint` from the `args` argument:

![Screen Shot 2020-04-22 at 2 17 03 PM](https://user-images.githubusercontent.com/2208816/80025419-3d884600-84a6-11ea-8a98-7007ff62b5c9.png)
</details>

**Comment by bensbigolbeard** [comment]
@rarkins just bumping so the issue isn't auto-closed

**Comment by bensbigolbeard** [comment]
@rarkins can you let me know your thoughts on my previous comment?

**Comment by rarkins** [comment]
@bensbigolbeard sorry for the delay in getting back to you. We are planning a v1.0.0 release of the rebranded "WhiteSource Renovate" that will include an updated version of Renovate.

Are you able to test if the current CLI version of Renovate produces the same (lack of) results?

**Comment by tuckbick** [comment]
Hey @rarkins - @bensbigolbeard is handing over this issue to me now to look into. I'll take a look at testing this with the CLI. Is [this](https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md) the recommended guide for getting started with it?

**Comment by tuckbick** [comment]
I was able to run the CLI and get PRs submitted against the repo. Unfortunately I'm still not seeing release notes show up. I'll keep digging to see if it's for the same reasons as noted above ^ by Ben.

**Comment by tuckbick** [comment]
Looks like it's a problem here for similar reasons. Working the call stack backwards:

* `endpoint` is undefined in [`getChangeLogJSON()` of `source-github.ts`](https://github.com/renovatebot/renovate/blob/53ca91301f6a36c0c87e7d6b06b1bd8c9ec1b283/lib/workers/pr/changelog/source-github.ts#L48)
* `endpoint` is undefined in [`branchifyUpgrades ()` of `branchify.ts`](https://github.com/renovatebot/renovate/blob/53ca91301f6a36c0c87e7d6b06b1bd8c9ec1b283/lib/workers/repository/updates/branchify.ts#L64).
* `endpoint` is not added to the update in [`flattenUpdates` of `updates/flatten.ts`](https://github.com/renovatebot/renovate/blob/53ca91301f6a36c0c87e7d6b06b1bd8c9ec1b283/lib/workers/repository/updates/flatten.ts). It exists on the provided `config` arg, but the resulting array of renovate configs does not contain `endpoint`.

**Comment by rarkins** [comment]
@tuckbick thanks for the help troubleshooting this. I found that `endpoint` was defined with `"stage": "repository"` which I suspect is what is causing it to get filtered out. I've removed that now, so can you test again once the next release is out and confirm if anything is different?

**Comment by tuckbick** [comment]
Looks like that took care of it! Thanks so much for this. Now, since we're not using the CLI, I presume we'll need to wait for the 1.0.0 release in order to get this update?

**Comment by rarkins** [comment]
Hi, we're aiming for by end of this month (May)
