### ISSUE TITLE
Using a default shared config without onboarding

### ISSUE THREAD

**Issue by mountainash** [renovatebot/config-help#609]
### Which Renovate are you using?
Renovate Open Source CLI (through the offical Docker image)
### Which platform are you using?
GitLab self-hosted
### What would you like to do?

Currently using the following in our self-hosted `config.js`:
```js
module.exports = {
    platform: 'gitlab',
    autodiscover: false,
    repositories: [
        'renovate-bot/renovate',
        ...
    ],
    requireConfig: false,
    onboarding: false,
    onboardingConfig: { "extends": ["local>renovate-bot/shared-config"] }
};
```

I'd like to **not** have to create a `renovate.json` in each repository that is scanned, but still have the additional rules in our [shared config](https://github.com/Init7/renovate-shared-config) (mirrored also on GitHub - but [moving local now it's supported](https://github.com/renovatebot/renovate/issues/3019) used when Renovate runs.

Is there something similar to "extends" that would work to set a default config for non-onboarded repositories?

>### extends
>Configuration presets to use/extend. Note: does not work if configured in config.js

Source: https://docs.renovatebot.com/configuration-options/#extends

**Comment by rarkins** [comment]
I haven't tried it, but does it work if you just have the `extends` as part of the bot config?

```js
module.exports = {
    platform: 'gitlab',
    autodiscover: false,
    repositories: [
        'renovate-bot/renovate',
        ...
    ],
    requireConfig: false,
    onboarding: false,
    extends: ["local>renovate-bot/shared-config"]
};
```

Failing that you can put all the config from that shared config into the bot itself (i.e. the `module.exports`).

**Comment by mountainash** [comment]
Running with `extends: ["local>renovate-bot/shared-config"]` errors with:
```log
renovate    | DEBUG: Preset fetch error
      "err": {
        "message": "Cannot read property 'platform' of undefined",
        "stack": "TypeError: Cannot read property 'platform' of undefined\n    at Object.getPreset (/usr/src/app/dist/config/presets/local.js:14:27)\n    at getPreset (/usr/src/app/dist/config/presets/index.js:124:58)\n    at Object.resolveConfigPresets (/usr/src/app/dist/config/presets/index.js:176:43)\n    at Object.parseConfigs (/usr/src/app/dist/config/index.js:48:40)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.start (/usr/src/app/dist/workers/global/index.js:62:22)\n    at async /usr/src/app/dist/renovate.js:16:24"
      }
INFO: Throwing preset error
renovate    | FATAL: Fatal error: config-validation
      "err": {
        "message": "config-validation",
        "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/usr/src/app/dist/config/presets/index.js:185:35)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
      }
INFO: Renovate is exiting with a non-zero code due to the following logged errors
```

**Comment by mountainash** [comment]
Running with `extends: ["github>Init7/renovate-shared-config"],` works. It looks like the new local shared config options are being used here in the `config.js`.

**Comment by viceice** [comment]
I'll have a look

**Comment by viceice** [comment]
It will fail, because on initial config stage we do not have a `baseConfig`
https://github.com/renovatebot/renovate/blob/6dea8e919c3f5d912fb747ccf142cb4bb1fb4fe1/lib/config/index.ts#L51

@rarkins I'm not really sure how to fix that, as we currently loading the config. an option can be passing `inputConfig` if `baseConfig` is missing
https://github.com/renovatebot/renovate/blob/6dea8e919c3f5d912fb747ccf142cb4bb1fb4fe1/lib/config/presets/index.ts#L185

**Comment by mountainash** [comment]
So to get by until `extends: ["local>renovate-bot/shared-config"]` works, we are still using the public GitHub hosted reference: `extends: ["github>Init7/renovate-shared-config"]`, but we think that in [that config](https://github.com/Init7/renovate-shared-config/blob/master/renovate.json) the `"docker:enableMajor"` Preset is no longer been read/evaluated.

When running v19.190.1 all our MRs for Docker Major changes were autoclosed. I've just run v19.211.1 and they haven't been updated.

**Comment by viceice** [comment]
@mountainash you can also use `extends: ["gitlab>renovate-bot/shared-config"]` to use gitlab hosted config. It should use your configured endpoint

**Comment by mountainash** [comment]
That doesn't work on v19.211.3
```
DEBUG: Failed to retrieve renovate.json from repo
       "err": {
         "name": "HTTPError",
         "hostname": "gitlab.com",
```
Remember, we have a self-hosted install of GitLab.

Using `extends: ['local>renovate-bot/shared-config']` gives
```
DEBUG: Checking for config file in /usr/src/app/config
DEBUG: Preset fetch error
       "err": {
         "message": "Cannot read property 'platform' of undefined",
         "stack": "TypeError: Cannot read property 'platform' of undefined\n    at Object.getPreset (/usr/src/app/dist/config/presets/local.js:14:27)\n    at getPreset (/usr/src/app/dist/config/presets/index.js:124:58)\n    at Object.resolveConfigPresets (/usr/src/app/dist/config/presets/index.js:176:43)\n    at Object.parseConfigs (/usr/src/app/dist/config/index.js:48:40)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.start (/usr/src/app/dist/workers/global/index.js:62:22)\n    at async /usr/src/app/dist/renovate.js:16:24"
```
`local>renovate-bot/shared-config` is still an internal copy of https://github.com/Init7/renovate-shared-config

**Comment by mountainash** [comment]
Go away bot. It’s still an issue  maybe.

**Comment by mountainash** [comment]
It's still an issue. I've just checked against the latest pull (**19.213.4**) and using `local>` in the `config.js` `extends` gives the following error (this also means the [documentation](https://docs.renovatebot.com/config-presets/#local-presets) is now incorrect).
```
"Cannot read property 'platform' of undefined"
```

Using `gitlab>` gives a **404** as the it's looking up the public GitLab hosted service, not the local self-hosted version.

**Comment by viceice** [comment]
@rarkins I think this is a bug, because we don't pass our known `platform` and `endpoint` to initial shared-config resolution

**Comment by rarkins** [comment]
Let’s transfer it to the main repo

**Comment by mountainash** [comment]
I just tried `local>` & `gitlab>` with `v19.216.6` of Renovate and had the same results as [3 days ago](https://github.com/renovatebot/config-help/issues/609#issuecomment-616365577).

@rarkins Did you want me to raise a new issue in the [main repo](https://github.com/renovatebot/renovate/) or should [Allow self-hosted presets
#3019](https://github.com/renovatebot/renovate/issues/3019) be reopened?

**Comment by rarkins** [comment]
@mountainash please raise a new issue (feature request) with the topic "Support local presets in bot admin config"
