### ISSUE TITLE
Trouble with semantic type 

### ISSUE THREAD

**Issue by Hartorn** [renovatebot/config-help#61]
Hi!
I have some trouble with my config : I tried to have different semantic if the update is a patch, a minor version or a major version.

I would have liked to have chore for patch, fix for minor, and feat for major.

My config does not seem to work : [see here](https://github.com/thc-tools/webpack-react/blob/master/renovate.json) 

What am I doing wrong?

**Comment by rarkins** [comment]
I think the problem is because `config:base` includes some `packageRules` about semantic commits, and packageRules are evaluated/applied after the major/minor/patch rules. I need to fix some of the logic so that it doesn't happen, but in the meantime I think the following should work instead:

```json
  "major": {
    "packageRules": [{
      "packagePatterns": [".*"],
      "semanticCommitType": "feat",
      "labels": ["dependencies", "dep:major"]
	}]
  },
  "minor": {
    "packageRules": [{
      "packagePatterns": [".*"],
      "semanticCommitType": "fix",
      "labels": ["dependencies", "dep:minor"]
    }]
  },
  "patch": {
    "packageRules": [{
      "packagePatterns": [".*"],
      "semanticCommitType": "chore",
      "labels": ["dependencies", "dep:patch"]
    }]
  }
```

**Comment by Hartorn** [comment]
Indeed, it is working with this config.
Thanks for the help, and keep up the good work !
