### ISSUE TITLE
Create upgrade PRs on top of each other

### ISSUE THREAD

**Issue by hisener** [renovatebot/config-help#610]
### Which Renovate are you using?

Renovate Open Source CLI (using the docker image `renovate/renovate:19.208.2-slim`)

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

We have two internal dependencies we want to upgrade them first and then create all other upgrades on top of those branches.

Let's say, I have internal `parent` and `commons` dependencies. What I want to achieve is the following: if there is an upgrade for both, then create `parent` upgrade PR first and then create `commons` upgrade PR targeting `renovate/parent`. And all other upgrades should target `renovate/commons`.

I've tried the following:
```
    {
      packagePatterns: ['^parent$'],
      groupName: 'Parent',
      prPriority: 2
    },
    {
      packagePatterns: ['^commons$'],
      groupName: 'Commons',
      baseBranches: ['renovate/parent'],
      prPriority: 1
    },
    {
      packagePatterns: ['.*'],
      excludePackagePatterns: ['^(parent|commons)$'],
      baseBranches: ['renovate/commons', 'renovate/parent']
    },
```

But IIUC, renovate creates some sort plan for the execution and then starts creating upgrade PRs and while preparing the plan there is no `renovate/parent` branch. So, it just falls back to the default branch.

Most probably, I can solve it running it 3 times with 3 different configurations but I am wondering if there is a solution to do it in one go.

**Comment by rarkins** [comment]
Sounds like https://github.com/renovatebot/renovate/issues/5573

Are you using GitLab?

We *could* implement the same kind of logic ourselves, but it would be quite a lot of work!

**Comment by hisener** [comment]
Nope, we use GitHub. The feature/solution I described should be platform-independent.

**Comment by rarkins** [comment]
OK, I created https://github.com/renovatebot/renovate/issues/6011 to track. I think this would be quite challenging to implement though.

**Comment by hisener** [comment]
Thanks!
