### ISSUE TITLE
Disable `Renovate` if package update is `patch`

### ISSUE THREAD

**Issue by selfrefactor** [renovatebot/config-help#611]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I need to disable `Renovate` when there is patch bump in my dependencies.

This is my config:

```json
{
  "extends": [
    "config:base"
  ],
  "ignorePaths": [
    "lazy-helpers",
    "tuna-player",
    "maided"
  ],
  "packageRules": [{
    "depTypeList": ["devDependencies"],
    "enabled": false
  }]
}
```

I use it over a `Lerna` monorepo, so in fact there are like 10 different `package.json` inside. 

As I don't care in this context for the patch upgrades, it will be very convenient if I can simply say 'Please don't run if the update is a patch`. Thanks in advance.

**Comment by rarkins** [comment]
Try this:

```json
{
  "extends": [
    "config:base"
  ],
  "ignorePaths": [
    "lazy-helpers",
    "tuna-player",
    "maided"
  ],
  "separateMinorPatch": true,
  "packageRules": [{
    "depTypeList": ["devDependencies"],
    "enabled": false
  }, {
    "updateTypes": ["patch"],
    "enabled": false
  }]
}

**Comment by selfrefactor** [comment]
Thank you so much @rarkins 

This seems right and I am sure it will work.
