### ISSUE TITLE
autodiscoverFilter for managers

### ISSUE THREAD

**Issue by augi** [renovatebot/config-help#614]
**What would you like Renovate to be able to do?**
It would be great if there was an option for self-hosted deployment that would allow to filter out project based on manager used. Now, it is possible over the project name only ([autodiscoverFilter](https://docs.renovatebot.com/self-hosted-configuration/#autodiscoverfilter)).

**Describe the solution you'd like**
It would be great to have also `autodiscoverManagerFilter` option.

**Additional context**
The use case in our case is that Scala developers use [scala-steward](https://github.com/fthomas/scala-steward) so we would like to skip projects managed by sbt manager, to prevent duplicate PRs.

**Comment by rarkins** [comment]
If you know the full list of enabled managers then that would work, however it could be confusing to your end users if they are wondering why any new manager is disabled.

Maybe easier if we add a `disabledManagers` option when you only want to disable a small number.

If you use a `config.js` or `config.json` in your bot container then you could disable `sbt` quite easily.

**Comment by augi** [comment]
Yes, `disabledManagers` option would be more straightforward for us.

We are using Renovate distributed as Docker image, and run it in k8s. So it is much easier for us to setup all the stuff via environment variables than via a file that has to be mounted etc.

**Comment by rarkins** [comment]
Another approach which would work right now:

- Create your own preset config in a repo and have it disable `sbt`
- Make it your `onboardingConfig` so that all repos you onboard inherit it

You can configure `RENOVATE_ONBOARDING_CONFIG` as a JSON string in env.
