### ISSUE TITLE
PR merged even though checks failed

### ISSUE THREAD

**Issue by steebchen** [renovatebot/config-help#616]
config: https://github.com/prisma/prisma2-e2e-tests/blob/master/renovate.json

### Which Renovate are you using?

WhiteSource Renovate App
### Which platform are you using?
GitHub.com

### What would you like to do?

Prevent renovate from merging PRs whose checks fail. This one failed but renovate still merged it: https://github.com/prisma/prisma2-e2e-tests/pull/304

**Comment by rarkins** [comment]
Renovate will automerge if GitHub reports all tests have passed, and none are pending or failed. If you log into the dashboard and locate the log for the run when the automerge happened, you should be able to see a logged copy of what GitHub reported the status checks as. It's strongly recommended to use required status checks if any of your existing checks don't reliably post "pending" statuses while they are in progress.

**Comment by steebchen** [comment]
I can't seem to access logs older than 3 days (the PR I'm looking for happened 5 days ago), plus I don't know how to get the ID run. We're using GitHub Actions for the checks so I'm not quite sure how they work together with renovate. I understand our best bet is to introduce required status checks, but for this specific project it has a few implications which unfortunately make other things harder

**Comment by steebchen** [comment]
But to clarify: are you saying the only reliable way to make sure nothing gets merged is introducing required checks? We do want to do that in the future, just not quite ready yet.

**Comment by rarkins** [comment]
When I looked at a currently open PR that was recently pushed minutes earlier, I could see that the number of checks was 17 and then kept growing gradually. `frameworks (nestjs)` showed no results at all (i.e. not pending). The problem is, at some snapshot in time, every single existing check run had passed, while that nestjs one had either not started or not posted a pending status. GitHub's API responded with "all tests have passed". Unless you set required status checks, GitHut itself has no idea what is "expected". It has no concept like "22 of 22 tests have passed.. but this repo averages 30 so maybe wait a bit" - it simply says "22 tests have passed, zero are pending".

**Comment by steebchen** [comment]
Ah, that makes a lot of sense. I now understand what the problem is. Thanks for clarifying. It seems that with GitHub Actions the only reliable way then is to enforce required checks, since they just post the checks asynchronously.

**Comment by rarkins** [comment]
Are your actions triggered only by PR, or at time of branch push/commit? You could configure `prCreation=not-pending` which would mean:
- Renovate first pushes a branch, does not create a PR
- Next time it runs, if branch status is non-pending (e.g. all have passed, or at least one has failed), then the PR will be created
- Automerging won't happen until after the PR is created

Be aware:
- This solution isn't perfect: there's still a chance of a race condition, however it should be much lower
- This will slow down the total time from commit to automerge by around an hour or so, as it requires more runs/steps on Renovate's side

**Comment by steebchen** [comment]
Thanks for the hint. I'll think we just go for required checks and accept the implications. I think it's fine when we allow admins to do stuff, as renovate wouldn't be able to merge while admins can still decide to merge the PR.
