### ISSUE TITLE
Limit amount of github notifications

### ISSUE THREAD

**Issue by aureooms** [renovatebot/config-help#621]
Would it be possible to tell renovate to only generate/keep notifications of failed PR's? Is that possible with GitHub's API? My workflow is to have renovate automerge all passing PR's. I'd rather not be notified if everything runs smoothly. I only care if something goes wrong.

**Comment by rarkins** [comment]
It’s not really got anything to do with Renovate - it’s a GitHub thing. Renovate already assigns only failing PRs but if you’re watching a repo then you probably get notified anyway.

**Comment by aureooms** [comment]
Ok. Thanks! Do I understand correctly that there is no way to ignore specifically those pull requests that pass with GitHub notifications settings?
