### ISSUE TITLE
How to disable automerge by packageRules

### ISSUE THREAD

**Issue by okitan** [renovatebot/config-help#622]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

I have [`renovate.json`](https://github.com/okitan/renovate-sandbox/blob/master/renovate.json) which hopes:

- Do Not automerge aws-cdk and aws-sdk.
- other dependencies to be automerged.

```renovate.json
  "npm": {
    "extends": [":automergeMinor", ":unpublishSafe"],
    "packageRules": [
      {
        "extends": "monorepo:aws-cdk",
        "automerge": false
      },
      {
        "packageNames": ["@aws-sdk/client-auto-scaling-node"],
        "automerge": false,
        "description": "this is preview version of it and easy to be broken"
      }
    ]
  },
```

But minorepo:aws-cdk is marked `as automerge: true`

```
DEBUG: Checking #3 for automerge(branch="renovate/aws-cdk-monorepo")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/aws-cdk-monorepo")
DEBUG: PR is not ready for merge(branch="renovate/aws-cdk-monorepo")
```

### What would you like to do?

How can I disable per library automerge by packageRules?

**Comment by rarkins** [comment]
Can you reproduce this in a public repo? (for debugging with CLI)

As a start, I would normally recommend you don't embed packageRules within the `npm {}` object and instead use `"managers": ["npm"]` within the rules.

**Comment by okitan** [comment]
public repo is here.
https://github.com/okitan/renovate-sandbox

**Comment by okitan** [comment]
It was resolved by myself.

In case overriding `:automergeMinor` presets, `automerge: false` is insufficient.
It needs both `automerge` and `"updateTypes": ["minor", "patch", "pin", "digest"]` .

https://github.com/okitan/renovate-sandbox2/blob/master/renovate.json#L10-L11
results https://github.com/okitan/renovate-sandbox2/pull/1 not merged

Thanks,
