### ISSUE TITLE
Github Token Not Found for Release Note retrieval

### ISSUE THREAD

**Issue by fr1zle** [renovatebot/config-help#623]
**What Renovate type are you using?**

We are running renovate as a Kubernetes CronJob (self-hosted) against Bitbucket Server.

**Describe the bug**

We do see the following warning logs and the corresponding note on the opened PRs:

```
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=<repo name>, branch=renovate/angular)
       "manager": "npm",
       "depName": "@angular/animations", 
       "sourceUrl": "https://github.com/angular/angular"
```

Although we do configure a github token in the global config.js:

```javascript
  hostRules: [
    {
      domainName: "github.com",
      encrypted: {
        token: "secret token",
      },
    },
  ],
```

**Did you see anything helpful in debug logs?**

Sadly, no (debug) logs regarding release notes are displayed besides the warn log mentioned above.

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#githubcom-token-for-release-notes

**Comment by fr1zle** [comment]
Thats good to know. I guess this has to be the "raw" / unecrypted token then?

BTW: The Warning generated on the Pull Requests links to this page: https://docs.renovatebot.com/install-gitlab-app/#configuring-a-token-for-githubcom-hosted-release-notes where the environment variable is not mentioned.

**Comment by viceice** [comment]
Yes, unencrypted.

Yes, the warning shows the docu for the app. @rarkins  maybe we should add there some references for self-hosting users

**Comment by fr1zle** [comment]
This did the trick! Thanks for helping out so quickly and thanks for the great project!

**Comment by viceice** [comment]
🤔 the `hostRule` should work too:

![image](https://user-images.githubusercontent.com/1798109/80480757-83835500-8951-11ea-98f0-55ab62c59c28.png)

Dis you have configured a `privateKey`? The normal app encryption does not work for self-hosted renovate. You would need your own encryption key.

see https://docs.renovatebot.com/self-hosted-configuration/#privatekey

**Comment by fr1zle** [comment]
Oh, yeah, did not do that. Maybe this was the issue. Having this as environment variable does the trick now, though :-)
