### ISSUE TITLE
Updating grouped npm dependencies and updating lockfile?

### ISSUE THREAD

**Issue by fr1zle** [renovatebot/config-help#624]
I am trying to configure a mixed project (maven + npm) to update grouped dependencies (angular). The `package.json` file is updated just fine, sadly the `package-lock.json` is not updated.

Updating of package-lock.json works fine for other, non-grouped dependency upgrades. 

This is the config i am using:

```json
{
  "extends": ["config:base"],
  "npm": {
    "enabled": true,
    "npmrc": "<private npm registry>",
    "rangeStrategy": "bump",
    "packageRules": [
      {
        "packagePatterns": ["^@angular/", "^@angular-devkit/"],
        "groupName": "Angular",
        "updateLockFiles": true
      },
      {
        "updateTypes": ["minor", "patch"],
        "automerge": true
      }
    ]
  }
}

```

### Which Renovate are you using?

Renovate Open Source CLI (self-hosted)

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

There was nothing relevant in the logs

### What would you like to do?

I would like to group all angular dependencies into a single commit / PR. package.json and package-lock.json should both be updated since our CI uses `npm ci` to build PRs.

**Comment by viceice** [comment]
* the `packageRules` should be in config root object.
* npm is enabled by default
* npmrc should be at root

**Comment by fr1zle** [comment]
I updated the config to your recommandations and used the angular monorepo preset , but still the package-lock is not updated:

```json
{
  "extends": [
    "config:base",
    "group:angularcliMonorepo",
    "group:angularMonorepo"
  ],
  "npmrc": "<npmrc>",
  "npm": {
    "enabled": true,
    "rangeStrategy": "bump"
  },
  "packageRules": [
    {
      "updateTypes": ["minor", "patch"],
      "automerge": true
    }
  ]
}
```

npm is enabled explicitly since its disabled in the global configuration.
<img width="755" alt="grafik" src="https://user-images.githubusercontent.com/311019/80516527-e5f54900-8983-11ea-949c-29960692c34c.png">
<img width="400" alt="grafik" src="https://user-images.githubusercontent.com/311019/80516555-f0afde00-8983-11ea-9f93-7de6490dee22.png">

**Comment by rarkins** [comment]
Please log at debug level for a run when a PR is created or rebased. You should see it attempting to update the package-lock.json.

**Comment by fr1zle** [comment]
Okay, apparently one transitive dependency emits a warning log during the lockfile update since it has been deprecated. Since this is a transitive dependency i assume setting `ignoreScripts` to `true` would be the correct way to disable this?

**Comment by rarkins** [comment]
I can’t be sure based on your description. Deprecation warnings usually don’t cause failures.

**Comment by fr1zle** [comment]
I deleted the branch & PR again and tried to run the CLI locally with debug on. Now it seems to update the package-lock.json just fine without any artifiact update errors...

Thanks again for the help and the great product!
