### ISSUE TITLE
How to increase version of NPM libraries?

### ISSUE THREAD

**Issue by rvillane** [renovatebot/config-help#629]
### Which Renovate are you using?
Renovate Open Source CLI

### Which platform are you using?
GitHub Enterprise

### What would you like to do?
Question, is it possible to automatically increase the version in package.json file when renovate opens a PR? At moment I'm doing this manually.

**Comment by rarkins** [comment]
Try https://docs.renovatebot.com/configuration-options/#bumpversion

**Comment by rvillane** [comment]
nice, exactly what I needed, thanks
