### ISSUE TITLE
Split commits for same dependency based on scope

### ISSUE THREAD

**Issue by ppmathis** [renovatebot/config-help#630]
### Which Renovate are you using?
Renovate Open Source CLI
WhiteSource Renovate App

### Which platform are you using?
GitHub.com
Gitea (self-hosted)

### What would you like to do?
When working in a monorepo like https://github.com/snapserv/infrastructure, I use the semantic commit scope for specifying which sub-project/module the commit affects. To still keep a clean history, I would like to avoid commits which affect multiple sub-projects/modules at once.

As an example referring to the repository above, when I update the Dockerfile for `mariadb`, I would use a commit like `feat(mariadb): support fancy emoji passwords`. While this works great in a manual setup, Renovate defaults to using `chore(deps): update <name of dependency>` as its commit message and throws updates for the same dependency into the same commit as well.

After reading https://docs.renovatebot.com/configuration-options/#semanticcommitscope, I expected that setting `semanticCommitScope` to `{{parentDir}}` would change the behavior of Renovate to no longer mash all changes into one commit.

**Actual behavior:** Renovate reads the name of the last affected directory within a commit (based on alphabetical sort order) and uses that name as its semantic commit scope. This can be seen here, as while https://github.com/snapserv/infrastructure/commit/93bc50e3d7850f1bfcd13c8b78b85361db04f6d1 does contain the scope **synapse**, all changes for updating the same dependency are still within one commit.

**Expected behavior:** [The commit linked above](https://github.com/snapserv/infrastructure/commit/93bc50e3d7850f1bfcd13c8b78b85361db04f6d1) should not have been one commit but 10 commits, each for its respective scope:

- *chore(acme-dns): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(gitea): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(hugo): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(mariadb): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(netbox): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(nginx): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(oauth2-proxy): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(postgres): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(redis): update quay.io/snapserv/base-alpine docker tag to v1.1.13*
- *chore(synapse): update quay.io/snapserv/base-alpine docker tag to v1.1.13*

While I expected 10 separate commits, they still should all have appeared within one single branch. This would allow maintaining a proper, clean history in a mono repository while still not flooding the end user with pull requests.

[The Renovate configuration file](https://github.com/snapserv/infrastructure/blob/master/renovate.json) can be found within the repository and is mostly based on the default configuration aside from `semanticCommitScope` and a few auto-merge/docker-related options. Unfortunately I was not able to find any option which would result in the desired behavior.

**Comment by rarkins** [comment]
Renovate always performs one commit per branch - you'll never see 10 separate commits per branch. If you would like to separate them into separate PRs, it means they need to be in separate branches. You can probably achieve that by influencing the `branchPrefix`:

```
  "branchPrefix": "renovate/{{parentDir}}-"
```

**Comment by ppmathis** [comment]
This does seem to work, thank you! I noticed however that auto-merging only merges a single branch each time. Based on how often the GitHub App triggers (hourly), an update now takes ages to propagate to all modules. The [updated configuration can be found at the same place](https://github.com/snapserv/infrastructure/blob/master/renovate.json).

Based on your previous comment in https://github.com/renovatebot/renovate/issues/4052#issuecomment-510754512, this seems like a deliberate design decision - however in my specific use case, where a conflict is no longer possible, this obviously makes the auto-merge process a very slow and tedious process.

Could a flag be introduced for attempting to auto-merge all branches and abort only if there actually is a conflict?

**Comment by rarkins** [comment]
> Based on how often the GitHub App triggers (hourly)

It runs hourly plus based on webhooks, and one such webhook is whenever an automerge happens. i.e. it runs more often than hourly in situations like this

The delay is because automerging may trigger *rebasing* of the remaining PRs. If you look up the logs for your repo, you might be able to confirm if that's what's causing the delay.

FYI we are unlikely to automerge multiple PRs per run for multiple reasons including that our internal state needs refreshing/updating once the master branch changes. But it's possible we could remove the restriction that PRs must be up to date with master, assuming you haven't enabled that as a restriction on GitHub itself.

**Comment by ppmathis** [comment]
> The delay is because automerging may trigger _rebasing_ of the remaining PRs. If you look up the logs for your repo, you might be able to confirm if that's what's causing the delay.

This is indeed the reason for the huge delay. After a branch gets automerged, Renovate exits but gets retriggered again using a webhook. Renovate then updates the branch and assuming that https://github.com/renovatebot/renovate/issues/4052#issuecomment-510771032 is still true, there is no sane way for Renovate to get a notification that all status checks (even though it is just one in my case - Travis) have now passed. So Renovate waits for the next hourly run and the whole story repeats.

I've just checked the behavior in a separate repository where no status checks are required for automerging and >10 merges were made in a matter of minutes. I assume that as long as there is no proper webhook for Renovate to detect when a branch (commit) passed all status checks, there is no easy workaround?

**Comment by rarkins** [comment]
> I assume that as long as there is no proper webhook for Renovate to detect when a branch (commit) passed all status checks, there is no easy workaround?

That's right. However I've been thinking about a solution where the webhook handler queries back to GitHub to get the combined status of a commit so that it can decide whether to run or not.
