### ISSUE TITLE
Assign reviewers randomly and automerge when approved

### ISSUE THREAD

**Issue by halfzebra** [renovatebot/config-help#631]
Thanks for Renovate! 👍
Very happy to use it at work and for public repos!

### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Couldn't find relevant information in the logs

### What would you like to do?

I would like to automerge approved PRs towards the protected `master` branch, but only for `minor` and `patch` updates. What I have tried is to set up the config like this:

```json
{
  "extends": ["config:base"],
  "schedule": [
    "after 10pm every weekday",
    "before 5am every weekday",
    "every weekend"
  ],
  "reviewers": [
    "some-developer",
    "another-developer"
  ],
  "reviewersSampleSize": 1,
  "packageRules": [
    {
      "updateTypes": ["minor", "patch"],
      "automerge": true
    }
  ]
}
```

As a result, the updates with `minor` and `patch` are not getting any reviewers assigned.

Is it even possible to achieve?
What is it that I'm doing wrong?

**Comment by rarkins** [comment]
Renovate skips setting an Assignee or any Reviewers for PRs that are configured to automerge. They only get assigned if any of the checks fail.

**Comment by halfzebra** [comment]
Thanks for your reply! 🙌 

Can I get it to automerge even to protected branches without the approval somehow?

**Comment by rarkins** [comment]
No, because GitHub blocks that. But if the automerge is blocked only because of approvals then install https://github.com/apps/renovate-approve and it will automatically approve all of Renovate's automerging PRs

**Comment by halfzebra** [comment]
That's exactly what I was looking for, thanks! 👍
