### ISSUE TITLE
How can I find out why Renovate closes the Pull Request?

### ISSUE THREAD

**Issue by emmenko** [renovatebot/config-help#632]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

I tried but it keeps showing me the "Please authenticate" page. 🤷‍♂️

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/1110551/80952403-e5343b00-8df9-11ea-86b5-572887ffc29b.png">

### What would you like to do?

Recently I noticed that the (scheduled) Pull Request opened by Renovate suddenly gets closed, and I can't figure out the reason why is that. Even if I manually reopen it, it then gets closed again.

For example:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/1110551/80951361-0eec6280-8df8-11ea-85a0-a7de9c79e0a5.png">

Any help would be appreciated, thanks.

**Comment by emmenko** [comment]
Ping

**Comment by rarkins** [comment]
Renovate generally doesn't "know" why a PR needs closing - it just knows which PRs should exist, and closes any that shouldn't (unless you disable that feature and clean up PRs yourself).

Sometimes it can occur because a datasource was unavailable temporarily, and was not treated as an essential "datasource failure" to abort the run. In such cases you should expect to see a new PR opened once the datasource responds the next time.

If you compare the debug logs between runs then the differences may give you a hint as to why it wasn't kept open. If the dashboard still isn't working for you then please raise that as a separate issue in https://github.com/renovatebot/app-support

**Comment by emmenko** [comment]
Thanks for the feedback. The weird thing is that recently it seems to happen "consistently" across some of our repositories.
Also from the screenshot above you can see that when the ZEIT Now (Vercel) deployments failed, the PR got closed by the Renovate bot. Was it just a coincidence?

> If the dashboard still isn't working

Tried again, it's working now 👌

**Comment by rarkins** [comment]
> Was it just a coincidence?

I would *think* it's just a coincidence, but things like this have surprised me before. I recommend:
- Look at the exact time stamp for when it was autoclosed
- Match that timestamp against the logs in the dashboard to find the right job
- Look at that job's logs for that branch
- If still unclear, download and compare the job's logs with the job *before* it, as hopefully that might give a hint

**Comment by emmenko** [comment]
Alright, thanks a lot for the feedback. I'll try to find out more in the logs when I have some time.

**Comment by emmenko** [comment]
@rarkins Hi, so I've been trying to look at the logs, as Mondays we have the scheduled update and the issue this occurs.

I'm starting to wonder if the problem is somehow related to having a scheduled update time. In the logs I see this:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/1110551/81594088-aafe0700-93c0-11ea-84b1-a172abce1f0a.png">

> Does not match schedule because 63391 is later than 18000

I can't find any other useful logs that might explain the behavior.

I could try removing the schedule and observe if the issue still occurs. Do you think it would help?

PS: my renovate config is like this

```json
{
  "extends": [
    "config:base",
    ":pinOnlyDevDependencies",
    "schedule:weekly"
  ],
  "separateMajorMinor": true,
  "groupName": "all dependencies",
  "groupSlug": "all",
  "packageRules": [
    {
      "packagePatterns": [
        "*"
      ],
      "groupName": "all dependencies",
      "groupSlug": "all"
    }
  ],
  "lockFileMaintenance": {
    "enabled": true
  },
  "labels": ["🤖 Type: Dependencies"],
  "ignoreDeps": []
}
```

**Comment by rarkins** [comment]
That log doesn't show any Pull Request being closed, does it? I can't search it easily because it's a screenshot

**Comment by emmenko** [comment]
Example PR: https://github.com/commercetools/commercetools-docs-kit/pull/432

Logs: https://app.renovatebot.com/dashboard#github/commercetools/commercetools-docs-kit/175489642

This one maybe? (I admit I'm a bit confused to what I should look for)

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/1110551/81594880-e0efbb00-93c1-11ea-8b57-4132a92e44a1.png">

**Comment by rarkins** [comment]
Seems that something is going wrong with the mix of `lockFileMaintenance`. Here's what I suggest for your config:

```json
{
  "extends": [
    "config:base",
    ":pinOnlyDevDependencies",
    "schedule:weekly"
  ],
  "separateMajorMinor": true,
  "packageRules": [
    {
      "packagePatterns": [
        "*"
      ],
      "updateTypes": ["minor", "patch"],
      "groupName": "all dependencies",
      "groupSlug": "all"
    }
  ],
  "lockFileMaintenance": {
    "enabled": true
  },
  "labels": ["🤖 Type: Dependencies"],
  "ignoreDeps": []
}
```

**Comment by rarkins** [comment]
BTW I am also removing the rule that seems to be misfiring for you. But I recommend you don't combine major updates into that all updates.

**Comment by emmenko** [comment]
Great, thanks a lot for looking into it and for the suggestion! 🙏

I’ll let you know how that goes

**Comment by emmenko** [comment]
Things look good now with the updated config. Thanks again for the help! 🙏
