### ISSUE TITLE
Schedule automerge, but raise PRs outside of schedule

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/config-help#638]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

We're looking to allow Renovate to raise PRs for updates at any time. However, we'd like to restrict automerging to outside of office hours. Is this possible?

**Comment by rarkins** [comment]
Not possible right now unfortunately. Please subscribe to https://github.com/renovatebot/renovate/issues/4866 to track any future implementation
