### ISSUE TITLE
BitBucket Server config still attempting to connect to GitHub

### ISSUE THREAD

**Issue by jimcullenaus** [renovatebot/config-help#641]
**What Renovate type are you using?**

docker `renovate/renovate` run locally.

**Describe the bug**

I am attempting to use renovatebot to connect to my company's server. On my local machine (or more precisely, an Ubuntu VM which *is* capable of connecting to my company's server), I am running:

```bash
docker run --rm -v "/home/jim/config.js:/usr/src/app/config.js" renovate/renovate --log-level=debug
```

my config.js is as follows:

```js
module.exports = {
  "hostRules": [
    {
      "hostType": "bitbucket-server",
      "domainName": "bitbucket.<my-company's-eTLD+1>",
      "timeout": 10000,
      "username": "<my.username>",
      "password": "<my password>"
    }
  ]
};
```

Instead of getting a successful result, or seeing an error explaining a failed connection or something expected, I get an error that seems to imply it is still trying to connect to GitHub, in spite of the "bitbucket-server" hostType and the domain name.

> You must configure a GitHub personal access token

**Did you see anything helpful in debug logs?**

Not really.

![image](https://user-images.githubusercontent.com/6212837/81257190-fc7f5c80-9075-11ea-9d61-ba903fc11ea3.png)

**To Reproduce**

I have made no code changes. Full instructions of the steps I went throuh are in the bug description.

**Additional context**

Seems as though the config file is not being used correctly, since the connection is still trying to go to GitHub instead of the BitBucket server specified.

**Comment by rarkins** [comment]
You don't configure with `hostRules`. It should be `platform`, `endpoint`, `username` and `password`. See https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#bitbucket-server

**Comment by jimcullenaus** [comment]
Thanks rarkins, that definitely *helped*, but didn't solve the problem. Config now reads

```js
module.exports = {
  "platform": "bitbucket-server",
  "username": "<my.username>",
  "password": "<bitbucket token on my account>",
  "endpoint": "https://bitbucket.<my-company's-eTLD+1>",
  "hostRules": [
    {
      "hostType": "bitbucket-server",
      "domainName": "bitbucket.<my-company's-eTLD+1>",
      "timeout": 10000,
      "username": "<my.username>",
      "password": "<bitbucket token on my account>"
    }
  ]
};
```

It's connecting to the correct server and recognising at least some of the correct repos. Unfortunately it then seems to try to connect over the *default* account in some ways (but the correct account in others). Some lines near the top of the debug output include

```
DEBUG: Adding trailing slash to endpoint
DEBUG: Using default gitAuthor: Renovate Bot <bot@renovateapp.com>
```

![renovatelogs](https://user-images.githubusercontent.com/6212837/81621843-d9b4c580-9432-11ea-8280-a4206b3c5e99.png)

**Comment by rarkins** [comment]
Remove the hostRules and capture logs again. Please also capture in text form not screenshot.

**Comment by jimcullenaus** [comment]
Unfortunately as I mentioned I am running this in a VM not directly on my local machine. I cannot copy/paste the text out of the VM despite having followed the instructions that are supposed to enable it.

However, after running the command again with `hostRules` removed from my `config.js`, I appear to get identical logs.

![renovatelogs2](https://user-images.githubusercontent.com/6212837/81755538-67101c80-94fc-11ea-89ae-62bf5276006e.png)

**Comment by rarkins** [comment]
Sorry but you’ll need to capture the full debug logs (from start to finish) in text format. If you want one of us to spend the time helping you then you should spend the time to get text logs. Please reopen once you can do that.

**Comment by jimcullenaus** [comment]
Okay, I'm currently rerunning the command sending the full logs to a file, and when it's done I'll spend some more time trying to find a way to break the file out of the VM. It's only a small fraction oft he way done so far and it's at 1 MB. What is your preferred host for large text files?

**Comment by jimcullenaus** [comment]
Preferably one that can be somewhat private, as my work would not be happy with exposing the names of all our services, which is included in the logs.

PS, up to 11 MB now and counting.

**Comment by jimcullenaus** [comment]
Found the problem by looking at server-side logs. We use Active Directory for our accounts, so the account I was using did not exist as far as the API was concerned.

**Comment by rarkins** [comment]
That's great. If you need to upload files in future:
- GitHub's gists work quite well
- Naturally do any "sanitizing" you need, e.g. search/replace the org name and any repo names that are sensitive

Of course we never *need* the whole log. The problem is we don't know which lines/sections before we start looking through.
