### ISSUE TITLE
Re-boarding not working

### ISSUE THREAD

**Issue by agusalex** [renovatebot/config-help#642]
**What Renovate type are you using?**
Renovate on GitHub,  self-hosted

**Describe the bug**
We have many repos that were already onboarded and their pull request closed. As per documentation, I did everything that was required in the "Nuke Everything and re-board" section to no avail since then several days have passed and the bot hasn't shown up.

**Did you see anything helpful in debug logs?**
I cannot access the logs as it is not self-hosted and I'm not the repo owner.

**To Reproduce**

The repo is private and owned by my organization. The bot had created a "Configure Renovate" pull request before. I followed the documentation but to no avail.
Here are the steps that were followed:
![image](https://user-images.githubusercontent.com/15642727/81205647-624de480-8fa1-11ea-92c1-c425e80e3e02.png)

**Additional context**
--

**Comment by rarkins** [comment]
Looks like it doesn't have anything to do with re-boarding and instead is a gradle issue.

I'm not a gradle user but found plenty of results when Googling it. e.g. some answers said JDK 11 wasn't supported until Gradle 5, etc.

If you think it's a Renovate problem, we will probably need a reproduction repo to be able to fix it.
