### ISSUE TITLE
Onboarding commit message seems to ignore semantic versioning settings in config/preset

### ISSUE THREAD

**Issue by diagonalfish** [renovatebot/config-help#643]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

Does not appear to show much about the preset or how the semantic versioning settings are being used.

### What would you like to do?

I've been working to get Renovate working on a private Github EE org.  We use semantic-release on all of our application/library repos, and pull requests cannot be merged unless semantic-release is happy with the commit messages (which means they must be prefixed properly). My setup has a renovate.js being used by the CLI application, and an onboarding config which just contains an 'extends' line for a preset located elsewhere in git.

**renovate.js**:
```
module.exports = {
  endpoint: 'https://git.org.com/api/v3/',
  platform: 'github',
  trustLevel: 'high',
  logLevel: 'info',
  onboarding: true,
  onboardingConfig: {
    "extends": ["local>private-org/renovate-presets:base"],
  },
  repositories: [
    'private-org/private-repo-1',
    'private-org/private-repo-2'
  ],
};
```
Here's the preset: **private-org/renovate-presets/base.json**:
```
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
        "config:base",
        ":semanticCommits",
        ":semanticCommitScopeDisabled",
        ":semanticCommitTypeAll(Update)"
    ],
    "enabledManagers": [
        "gomod"
    ],
    "postUpdateOptions": [
        "gomodTidy"
    ],
    "rebaseWhen": "behind-base-branch",
    "separateMajorMinor": false,
    "groupName": "all"
}
```
The problem is that the onboarding commit message is still just "Add renovate.json", ignoring the semantic versioning settings in the preset.  What am I doing wrong?

Thanks!

**Comment by rarkins** [comment]
Can you do this?
- Make sure you're using the latest Renovate version
- Expose LOG_LEVEL=debug in the environment (note: do it using env and not via CLI or config.js)
- Capture a full run (including the onboarding commit) at this debug level
- Sanitize it however you need and then post it so we can check it

**Comment by rarkins** [comment]
OK, I think I see now. The settings in the onboarding config affect *all PRs created after onboarding is completed* but not *the onboarding PR itself*. If you add `"semanticCommits": true` to your `renovate.js` then that should hopefully work for the onboarding PR (but also carry through to all repos you onboard too, FWIW).

**Comment by diagonalfish** [comment]
Yeah, that did it.  I was hoping to keep all config options that weren't specific to the operation of the tool in the preset, but this is OK as long as it can be overridden further down :)

Thanks for taking a look!
