### ISSUE TITLE
Reached PR creation limit or per run commits limit - skipping branch creation

### ISSUE THREAD

**Issue by vorburger** [renovatebot/config-help#645]
https://issues.apache.org/jira/browse/FINERACT-962

### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

https://app.renovatebot.com/dashboard#github/vorburger/fineract/174772690

> (branch="renovate/com.google.guava-guava-29.x")
DEBUG: Reached PR creation limit or per run commits limit - skipping branch creation(branch="renovate/com.google.guava-guava-29.x")

### What would you like to do?

I'd like to use Renovate ideally directly on https://github.com/apache/fineract. I believe this may be difficult, as per https://issues.apache.org/jira/browse/INFRA-19586. Shame really - not sure why you need WRITE access - if you could just be configured to READ and raise PRs...

As a less ideal fallback solution, I've attempted to set it up on the fork this Apache repo, at https://github.com/vorburger/fineract/pulls.  It did create https://github.com/vorburger/fineract/pull/2, but is ignoring https://github.com/vorburger/fineract/pull/22, and not raising PRs, so far.

https://issues.apache.org/jira/browse/FINERACT-962

**Comment by vorburger** [comment]
Wait actually I can't have that required `renovate.json` file on the default `develop` branch of that repo... I'd like to use `[FINERACT-962_renovatebot.com](https://github.com/vorburger/fineract/tree/FINERACT-962_renovatebot.com)` as the "base branch" - how/where do I change that?

**Comment by rarkins** [comment]
@vorburger I posted to your Jira - you should check out https://github.com/apps/forking-renovate for non-write access.

Renovate applies some hourly and total rate limits so as not to overwhelm new projects with too many PRs. You can remove all limits with this config:

```
{
  "prHourlyLimit": 0,
  "prConcurrentLimit": 0
}
```

Let me know if the above solves it, or there's more to do

**Comment by vorburger** [comment]
@rarkins thanks! Let me close this so you have one issue less here, and engage over in our JIRA.
