### ISSUE TITLE
Tricky regex issue matching slashes and question marks

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/config-help#646]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I have some `kustomization.yaml` files which look like this:

```yaml
---
bases:
  - github.com/fluxcd/flux/deploy?ref=1.19.0
  - github.com/foo/bar?ref=v1.0.1
patchesStrategicMerge:
  - patch.yaml
```

The bases are in the format `hostname.tld/org/repo/path/to/folder?ref=<tag>` or `hostname.tld/org/repo?ref=<tag>`.

I have written some regex which matches this:

```regexp
- github.com\/(?<depName>.*?\/.*?)(?:\/|\?).*?ref=(?<currentValue>.*?)\n
```

This is my `renovate.json`:
```json
{
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["^kustomization.yaml$"],
      "matchStrings": [
        "- github.com\/(?<depName>.*?\/.*?)(?:\/|\?).*?ref=(?<currentValue>.*?)\n"
      ],
      "datasourceTemplate": "github-tags"
    }
  ]
}
```

This doesn't pass config validation because the backslash escaping the question mark also escapes the JSON. So, I attempted each of the following _matchStrings_

```regexp
- github.com\/(?<depName>.*?\/.*?).*?ref=(?<currentValue>.*?)\n
- github.com\/(?<depName>.*?\/.*?)(?:\/|\?).*?ref=(?<currentValue>.*?)\n
- github.com\/(?<depName>.*?\/.*?)(?:\/|\?).*?ref=(?<currentValue>.*?)\s
- github.com\/(?<depName>.*?\/.*?)(?:\/|\\?).*?ref=(?<currentValue>.*?)\s
- github.com\/(?<depName>.*?\/.*?)(?:\/|\\?).*?ref=(?<currentValue>.*?)\\s
- github.com\/(?<depName>.*?\/.*?)(?:\/|\?).*?ref=(?<currentValue>.*?)\\s
- github.com\/(?<depName>.*?\/.*?)(?:\/|\\?).*?ref=(?<currentValue>.*?)\n
- github.com\\/(?<depName>.*?\\/.*?)(?:\\/|\?).*?ref=(?<currentValue>.*?)\n
- github.com\\/(?<depName>.*?\\/.*?)(?:\\/|\?).*?ref=(?<currentValue>.*?)\\n
- github.com\\\/(?<depName>.*?\\\/.*?)(?:\\\/|\\?).*?ref=(?<currentValue>.*?)\n
- github.com\\\/(?<depName>.*?\\\/.*?)(?:\\\/|\\?).*?ref=(?<currentValue>.*?)\\n
```

Renovate doesn't appear to match with any of these strings. It does, however, find the `kustomization.yaml` I'm using for testing.

Is there anything I'm missing here, or any regex escaping trickery going on behind the scenes?

**Comment by ChipWolf** [comment]
Suddenly and inexplicably working on the repo created to reproduce this issue.

**Comment by ChipWolf** [comment]
Yeah, it's working in one repo, but not the other. Perhaps a caching issue?

**Comment by rarkins** [comment]
There's currently no caching of extract results. I took that capability out as a precaution due to another issue, and I haven't added it back yet even though it turned out to not be the cause. FYI Job IDs only help us marginally unless the repos are public - we deliberately don't have any capabilities to use our access to clone repos locally - the only clones are the temporary ones on the app workers.

**Comment by rarkins** [comment]
The following logic should be done freshly every single run:
- Working out matching files
- Parsing each matched file

**Comment by rarkins** [comment]
One more thing: we have a `kustomize` manager and should ideally extend it to match what you have, if our current implementation is not enough.

**Comment by viceice** [comment]
Your regex is wrong, this should work
```js
/- github\.com\/(?<depName>.*?\/.*?)\?ref=(?<currentValue>.*?)\n/
```

And the escaped tring version for json:
```json
{
  "matchStrings": [
    "- github\\.com\\/(?<depName>.*?\\/.*?)\?ref=(?<currentValue>.*?)\\n"
  ]
}
```

https://regex101.com/r/jIvHuy/1

**Comment by viceice** [comment]
And a simpler one:
```json
{
  "matchStrings": [
    "- github\\.com\\/(?<depName>.*?)\\?ref=(?<currentValue>.*?)\\n"
  ]
}
```

**Comment by ChipWolf** [comment]
> One more thing: we have a `kustomize` manager and should ideally extend it to match what you have, if our current implementation is not enough.

I wasn't aware of this @rarkins. Now I'm looking into it, this should be enabled by default with the base config, shouldn't it? I don't see any evidence of it picking up my `kustomization.yaml`

The main query here is that I'm currently using the same regexp in [this repo](https://github.com/hrznstudio/playhrzn-k8s) and [this repo](https://github.com/chipwolf/renovate-646). Only the latter repo is working as expected. Any idea why that might be @rarkins?

@viceice neither of those examples take into account the base can be either `org/repo/path/to/folder` or `org/repo`. The regex seems to work fine on the [repo I created in attempt to recreate this issue](https://github.com/ChipWolf/renovate-646).
For example, it matches the entire string `fluxcd/flux/deploy`, whereas we need to capture `flucd/flux` as the _depName_. Hence the non-capturing group `(?:\/|\?)`

**Comment by rarkins** [comment]
> The main query here is that I'm currently using the same regexp in [this repo](https://github.com/hrznstudio/playhrzn-k8s) and [this repo](https://github.com/chipwolf/renovate-646). Only the latter repo is working as expected. Any idea why that might be @rarkins?

Is it possible that one of them hasn't had a job run recently, or something like that? It's a bit hard to tell because the config overall is very different, even if it seems like the regex manager config is unchanged.

**Comment by rarkins** [comment]
> I wasn't aware of this @rarkins. Now I'm looking into it, this should be enabled by default with the base config, shouldn't it? I don't see any evidence of it picking up my `kustomization.yaml`

The file name seems to match, so you should see that in your logs. But if the git repo pattern you have doesn't match the manager's pattern matching then you won't see any deps found.

**Comment by viceice** [comment]
> > One more thing: we have a `kustomize` manager and should ideally extend it to match what you have, if our current implementation is not enough.
> 
> I wasn't aware of this @rarkins. Now I'm looking into it, this should be enabled by default with the base config, shouldn't it? I don't see any evidence of it picking up my `kustomization.yaml`
> 
> The main query here is that I'm currently using the same regexp in [this repo](https://github.com/hrznstudio/playhrzn-k8s) and [this repo](https://github.com/chipwolf/renovate-646). Only the latter repo is working as expected. Any idea why that might be @rarkins?
> 
> @viceice neither of those examples take into account the base can be either `org/repo/path/to/folder` or `org/repo`. The regex seems to work fine on the [repo I created in attempt to recreate this issue](https://github.com/ChipWolf/renovate-646).
> For example, it matches the entire string `fluxcd/flux/deploy`, whereas we need to capture `flucd/flux` as the _depName_. Hence the non-capturing group `(?:\/|\?)`

```json
{
  "re" : "- github\\.com\\/(?<depName>.*?\\/.*?)(?:\\/.+?)*\\?ref=(?<currentValue>.*?)\\n"
}
```

https://regex101.com/r/jIvHuy/3

**Comment by viceice** [comment]
https://docs.renovatebot.com/modules/manager/kustomize/

🤔  Shouldn't `kustomize` work out of the box?

**Comment by ChipWolf** [comment]
playhrzn-k8s (note lines 97 and 466)
https://gist.github.com/ChipWolf/215133395a78cbd0a4300968c6ed8382

renovate-646 (note lines 61 and 523)
https://gist.github.com/ChipWolf/7f53300a4f406d8ceb82928e76740847

@rarkins

**Comment by ChipWolf** [comment]
@viceice I imagine it should, my logs have the following line

```
DEBUG: Matched 1 file(s) for manager kustomize: kustomization.yaml
```

I'm guessing the manager's regex isn't up-to-date

**Comment by viceice** [comment]
@ChipWolf  ok, i see our customize currently only supports git repos. See the double slash.
```yaml
bases:
- github.com/user/repo//deploy?ref=v0.0.1
```


*Does my last regex works?*

**Comment by ChipWolf** [comment]
Double slash syntax is no longer in a recent version of kustomize @viceice

**Comment by viceice** [comment]
@ChipWolf Do you know a reference for urls allowed in `bases` ?

**Comment by ChipWolf** [comment]
The only thing I can find is [this](https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#bases) @viceice, the JsonSchema is useless for field validation.

**Comment by ChipWolf** [comment]
I should probably mention here, `bases` is actually deprecated. `resources` replaces it. [The change](https://github.com/kubernetes-sigs/kustomize/commit/300dd108d5c505ff436f77138f457231566990b4) to allow URLs in `resources` is tagged but isn't yet in a stable release of kubernetes/kubectl.

**Comment by viceice** [comment]
renovatebot/renovate#6206 add support for renovating  `github.com` urls in `bases`

**Comment by ChipWolf** [comment]
@rarkins did you check this? https://github.com/renovatebot/config-help/issues/646#issuecomment-626709086

**Comment by rarkins** [comment]
@ChipWolf 

> @rarkins did you check this? [#646 (comment)](https://github.com/renovatebot/config-help/issues/646#issuecomment-626709086)

I don't understand what the point of those particular lines are. e.g. `DEBUG: Matched 1 file(s) for manager kustomize: flux/kustomization.yaml`. We knew the `kustomize` manager was matching files - the problem was it wasn't extracting dependencies.

**Comment by ChipWolf** [comment]
The lines I referenced show the same regex in both jobs but only the second extracted the dependency

**Comment by ChipWolf** [comment]
Fixed this, my fileMatch regex was incorrect, `^kustomization.yaml$` only matches files at the root b/c fileMatch checks the full path. It's now `(^|/)kustomization.yaml$` and works perfectly on the first repo.
