### ISSUE TITLE
Gitlab and merge request approvals

### ISSUE THREAD

**Issue by GuillaumeRahbari** [renovatebot/config-help#647]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitLab.com

### Have you checked the logs? Don't forget to include them if relevant

I checked them and here are the interesting part:

```
DEBUG: PR is configured for automerge(branch="renovate/reactrouter-monorepo")
DEBUG: PR is not ready for merge(branch="renovate/reactrouter-monorepo")
```

### What would you like to do?

My gitlab project is configured with a minimum of 1 merge request approval. So we can't merge without having at least one person to approve the Merge Request.
I configured renovate to automatically merge some PR (minor updates for example).
I was wondering if there is a way for renovate to approve its own MR ? I was using https://github.com/apps/renovate-approve on github. So maybe there is something similar on gitlab ? Or an other way to go around this ?

**Comment by rarkins** [comment]
Unfortunately we don't have any similar approver for GitLab. Apps on GitLab are much harder due to their lack of "app" interface/API.

**Comment by kevincox** [comment]
I don't quite understand the response. Are you saying that there is no way to approve via API on GitLab? If so we should file a feature request to track this.

Otherwise I don't see the issue. Immediately after pushing changes the bot could approve the MR.
