### ISSUE TITLE
automerge does not work

### ISSUE THREAD

**Issue by cy6erskunk** [renovatebot/config-help#648]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Checking #3 for automerge(branch="renovate/ava-3.x")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/ava-3.x")
```

### What would you like to do?

I want to auto-merge patch-level devDependencies updates. I've added
```json
{
    "depTypeList": ["devDependencies"],
    "updateTypes": ["patch"],
    "automerge": true
}
```
at the end of `packageRules` array [here](https://github.com/cy6erskunk/test-renovate-auotomerge/blob/master/renovate.json#L28) just in the same way as in some [other repo](https://github.com/cy6erskunk/svg-crowbar/blob/master/renovate.json#L5) where it works.
In this neewly created repository I only get
> 🚦 Automerge: Disabled by config. Please merge this manually once you are satisfied.

in this [PR](https://github.com/cy6erskunk/test-renovate-auotomerge/pull/3)

**Comment by rarkins** [comment]
separateMinorPatch=true

**Comment by cy6erskunk** [comment]
So, you mean that by default minor and patch level updates are treated like minor?

**Comment by rarkins** [comment]
Yes, by default non-major updates are not separated and are classified as type "minor". This is unfortunately for legacy reasons (many configs make this assumption).

**Comment by cy6erskunk** [comment]
And I would need to enable this option on the top level, right? 
I mean, this is not going to work:
```json
{
    "depTypeList": ["devDependencies"],
    "updateTypes": ["patch"],
    "automerge": true,
    "separateMinorPatch": true
}
```
?

**Comment by rarkins** [comment]
Yes, enable it at the top level

**Comment by cy6erskunk** [comment]
Thanks a lot, it works!
