### ISSUE TITLE
More than one open PR for the same dep?

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/config-help#652]
Is the app supposed to raise more than one PR for the same dependency?

Example: HRZNStudio/playhrzn-k8s#25 HRZNStudio/playhrzn-k8s#26

**Comment by rarkins** [comment]
Yes, default behavior is to allow one PR for the highest non-major (e.g. v8.6.0) and another PR for the highest major (e.g. v9). I think this is very sensible as sometimes you might be blocked from taking a major update but the minor or patch update is very important.

BTW if you enable `separateMultipleMajor` or `separateMinorPatch` then you may see even more PRs.

**Comment by ChipWolf** [comment]
Cool, thanks for the clarification
