### ISSUE TITLE
Should renovate close PRs when schedule changed?

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/config-help#653]
Hi,
I just added:
```
  "schedule": [
    "before 3am on the first day of the month"
  ]
```
to `renovate.json`
but the renovate PRs aren't closed.

However, I don't know whether renovate is supposed to close its PRs in such a situation or I should close them (if I don't want to merge them now).

**Comment by rarkins** [comment]
No, Renovate does not close PRs because of schedule. e.g you wouldn't want Renovate to start closing them at 4am onwards on the first day of the month.

If you close them:
- Rename the PR title first (e.g. append a ` - closed` suffix)
- Delete the branch after closing

**Comment by piotr-s-brainhub** [comment]
thanks
