### ISSUE TITLE
How to make one PR for multiple dependencies which share same version variable?

### ISSUE THREAD

**Issue by 1mdc** [renovatebot/config-help#658]
### Which Renovate are you using?

Github integration

### Which platform are you using?

GitHub.com

### What would you like to do?

In build.gradle, I have multiple dependencies share same version variable in gradle.properties. I see that renovate submits same PR multiple times for each dependency of the shared variable. Is there a config to make it submit once?

**Comment by rarkins** [comment]
Ideally this could be done automatically, but as a workaround you can create a `packageRules` entry with `groupName` to manually group them. You can identify packages by package names or patterns.

**Comment by 1mdc** [comment]
Sorry, I'm new to this. how do I configure packageRules to make it submits once for these dependencies:
```
dependencies {
    implementation "org.apache.kafka:kafka_2.11:$kafkaVersion"
    implementation "org.apache.kafka:kafka-clients:$kafkaVersion"
    implementation "org.apache.kafka:kafka-streams:$kafkaVersion"
}
```

**Comment by rarkins** [comment]
Easiest way would be to use packagePatterns. Please search the docs or closed issues in this repo for plenty of examples.
