### ISSUE TITLE
Can't figure out why PR says that automerge is disabled by config. 

### ISSUE THREAD

**Issue by farmas** [renovatebot/config-help#659]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant
Sample pull request:
https://github.com/uw-it-edm/content-services-ui/pull/914

https://app.renovatebot.com/dashboard#github/uw-it-edm/content-services-ui/177997718

### What would you like to do?

I am investigating if renovate would be a good fit for my team. My goal was to set it up to only create PR's for minor and patch versions of devDependencies (for now) of an angular application and to auto-merge those PR's.

My config can be seen here: https://github.com/uw-it-edm/content-services-ui/blob/6ff44e5fbcec491e4d12b811a19efb52a76acad2/.github/renovate.json

I thought this part of the config would do the trick:
```
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["minor, patch"],
      "automerge": true
    },
```

Additionally, I have setup the renovate autoapprove application for this repo and added app/renovate-approve in the CODEOWNERS file. My understanding was that renovate would create the PR, auto-approve it and since it is a codeowner it would be allowed to merge it into the base branch. However, all the PR say "Automerge: Disabled by config."

Please let me know if I am missing something or if there are other steps that I need to do to get this scenario to work.

Thanks!
Federico

**Comment by rarkins** [comment]
Try this instead:

```json
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["minor", "patch"],
      "automerge": true
    },
```

**Comment by farmas** [comment]
I can’t spot the difference between your suggestion and what I already have. Could you explain what I am missing?

Thanks for your reply!

**Comment by rarkins** [comment]
It's in the quotation marks:

```
wrong:      "updateTypes": ["minor, patch"],
right:      "updateTypes": ["minor", "patch"],
```

**Comment by farmas** [comment]
Oh man, my bad... <Insert face-palm emoticon here>

Thanks! I will see if that was the only issue.

**Comment by farmas** [comment]
Thank you, that solved the issue where renovate does recognize that the PR's should auto-merge. I will open a separate issue for the next hurdle.
