### ISSUE TITLE
kotlin dev releases are proposed

### ISSUE THREAD

**Issue by ikovalyov** [renovatebot/config-help#660]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

We're getting updates to the kotlin deps from

```
const val kotlinxCoroutinesRx2 = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.3.3"
```

to

```
const val kotlinxCoroutinesRx2 = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.3.6-mpp-dev-10"
```

How can we disable deps updates which has `dev` word in it?

Thanks.

**Comment by rarkins** [comment]
I'm not sure we have the ability to do that right now. Can you reproduce this in a public repo so that we have something to test against?

**Comment by ikovalyov** [comment]
hey, I'll try to create a sample repo for you :)
