### ISSUE TITLE
Why is an update from 7.1.1 to 7.1.6 treated as minor?

### ISSUE THREAD

**Issue by koba04** [renovatebot/config-help#661]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

- https://github.com/koba04/renovate-sandbox/pull/8
- https://app.renovatebot.com/dashboard#github/koba04/renovate-sandbox/178184922

The following is a part of dashboard log for the update.

```json
          {
            "depType": "devDependencies",
            "depName": "glob",
            "currentValue": "^7.1.1",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "7.1.1",
            "depIndex": 2,
            "updates": [
              {
                "fromVersion": "7.1.1",
                "toVersion": "7.1.6",
                "newValue": "^7.1.6",
                "newMajor": 7,
                "newMinor": 1,
                "updateType": "minor", // <--- minor?
                "isSingleVersion": false,
                "isRange": true,
                "releaseTimestamp": "2019-11-06T22:07:44.189Z",
                "canBeUnpublished": false,
                "isBump": true
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/isaacs/node-glob"
          },
```

### What would you like to do?

I'd like to auto-merge updates that are `patch` and `devDependencies`, but it isn't auto-merged.

The following is a setting to enable auto-merging.

https://github.com/koba04/renovate-sandbox/blob/master/renovate.json#L8-L18

```json
    "packageRules": [
      {
        "depTypeList": [
          "devDependencies"
        ],
        "updateTypes": [
          "patch"
        ],
        "automerge": true
      }
    ]
```

As I put the log, the update seems to be treated as `minor`.
This is an update from `7.1.1` to `7.1.6`, so it should be treated as `patch`, isn't it?

Thank you!

**Comment by rarkins** [comment]
Renovate’s default behaviour is to split between major and non-major. “Minor” is the term originally chosen for non-major. You can set separateMinorPatch=true to have both patch and minor separately

**Comment by koba04** [comment]
@rarkins Thank you!! It seems to work fine!!! 👏👏👏 
https://github.com/koba04/renovate-sandbox/pull/9
