### ISSUE TITLE
Renovate does not approve pull request and is unable to auto-merge

### ISSUE THREAD

**Issue by farmas** [renovatebot/config-help#662]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Sample pull request: https://github.com/uw-it-edm/content-services-ui/pull/914

### What would you like to do?

My goal is to set up to only create PR's for minor and patch versions of devDependencies (for now) of an angular application and to auto-merge those PR's.

Pull requests do say "Automerge: Enabled." and all checks pass, but it is still waiting for reviewer approval.

I have installed renovate-approve app on this repo and have added "* app/renovate-approve" in CODEOWNERS. Github repo is configured with:

- Require pull request reviews before merging: check
- Dismiss stale pull request approvals when new commits are pushed: check
- Require review from Code Owners: check

**Comment by rarkins** [comment]
The approval bots are working fine: https://github.com/renovatebot/renovate/pull/6279

Approving old PRs doesn't work - rename them and then close them to get a replacement approved.

**Comment by farmas** [comment]
I see, after I rename and close the current PR, will the replacement one be created until next Monday? (I have "schedule:weekly" specified in the config file).

**Comment by rarkins** [comment]
If you don't delete the branch, then it should be recreated outside of schedule.

**Comment by rarkins** [comment]
I recommend you enable `masterIssue` anyway so that you can create PRs on-demand when you want

**Comment by farmas** [comment]
Hello @rarkins, thanks for all your help. I am one step closer to getting this working. After closing the old pull request and making a new one via the master issue (really cool feature by the way), the new pull request got auto-approved. However, it is still not merged, it looks like it is waiting for a human to go in and click the Merge button.

Here is the sample pull request: https://github.com/uw-it-edm/content-services-ui/pull/925

**Comment by viceice** [comment]
You need to wait for the next renovate run, which is one hour after last run. You can trigger a new run via master issue advanced section

**Comment by farmas** [comment]
Thanks for your time. Auto-merging is working as expected.
