### ISSUE TITLE
automerge only merges 1 pr per run and master issue not created

### ISSUE THREAD

**Issue by gibbsonn** [renovatebot/config-help#664]
### Which Renovate are you using?
Renovate Open Source CLI
### Which platform are you using?
GitHub.com
Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant
Nothing relevant

### What would you like to do?

I'm trying to get a workflow where
* we have a feature branch just for renovate which will be the target of the renovate PR's
* renovate creates a PR per dependency and targets that branch and also creates a master issue PR. 
* Then a dev can review them and either close or approve (but not merge) as needed. 
* Renovate on a subsequent run will iterate through each of the PR's and resolve any conflicts and then merge any into the feature branch so that QA can test that branch later. 

Currently I'm trying to get auto merge and master issue running but it looks like renovate will only auto merge a single PR per repo run and then will abort that repo. Also the master issue isn't being created atm

My config is
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "rangeStrategy": "bump",
  "prHourlyLimit": 0,
  "automerge": true,
  "automergeType": "pr",
  "requiredStatusChecks": null,
  "masterIssue": true
}

**Comment by rarkins** [comment]
Aborting after an automerge is per design. Other branches could now have conflicts, we’d need to recalculate everything etc - so instead we abort

**Comment by gibbsonn** [comment]
Ah, I thought it would run renovates version of rebase for each branch automatically if it detected a merge conflict.

If we go with a single PR per dependency, we could have quite a few PR's created. Is it just a case of running renovate more frequently for this situation. Or is there an alternative approach?

**Comment by rarkins** [comment]
The app for GitHub.com automatically queues up another job every time there’s an automerge, so there you would see rapid rebased. Otherwise, keep a concurrent limit on how many open PRs you have if you plan on auto merging

**Comment by tony1377** [comment]
quick q - it looks like master issues aren't supported on azure atm, is that correct?

**Comment by rarkins** [comment]
Correct. Issue creation isn't supported: https://github.com/renovatebot/renovate/blob/680edf3d1ac15368a0b61f5e9f4842956e86ac06/lib/platform/azure/index.ts#L646

We'd naturally be open to something similar for AD as a dashboard at least even if the same "tick checkboxes to make Renovate do things" capability isn't possible.
