### ISSUE TITLE
Private, CI-Only registry leads to registry URL being embedded in package-lock.json

### ISSUE THREAD

**Issue by henricook** [renovatebot/config-help#665]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

Yes

### What would you like to do?

- I've got renovate running in Gitlab, works great. Onboarding PR was created in my React/NPM project, looked good and i've merged it.
- Developers use the public internet (base url: https://registry.npmjs.org) but on CI we have a private dependency proxy (http://proxy.infra.mycompany.local/registry.npmjs.org)
- In the first upgrade PR renovate created it updated _prettier_. This looked good mostly, the issue is that the new package-lock section looks like this:

**Before:**
```
    "prettier": {
      "version": "1.16.4",
      "resolved": "https://registry.npmjs.org/prettier/-/prettier-1.16.4.tgz",
      "integrity": "sha512-ZzWuos7TI5CKUeQAtFd6Zhm2s6EpAD/ZLApIhsF9pRvRtM1RFo61dM/4MSRUA0SuLugA/zgrZD8m0BaY46Og7g==",
      "dev": true
    },
```

**After:**
```
    "prettier": {
      "version": "1.19.1",
      "resolved": "http://proxy.infra.mycompany.local:8000/registry.npmjs.org/prettier/-/prettier-1.19.1.tgz",
      "integrity": "sha512-s7PoyDv/II1ObgQunCbB9PdLmUcBZcnWOcxDh7O0N/UwDEsHyqkW+Qh28jW+mVuCdx7gLB0BotYI1Y6uI9iyew==",
      "dev": true
    },
```

#### The problem

This means that if I merged this PR it would break for developers who can't access the CI dependency proxy (none of them can).

I'm setting the proxy as the registry before I run renovate with:

` npm config --global set registry "http://proxy.infra.mycompany.local:8000/registry.npmjs.org/" \`

Do you know how I can have renovate use the private proxy for its work, but keep registry.npmjs.org in its MRs?

**Comment by rarkins** [comment]
It’s npm itself which is updating the lock file, so there’s not much we can do here. We could maybe add a post-update feature to replace all urls with default but that’s pretty hacky

**Comment by henricook** [comment]
I don't know why I didn't think of that hack before, sounds ideal ;-)

I'll take some time to see if NPM can do something about it - thanks for such a quick response

**Comment by henricook** [comment]
I'm trying to add a `postUpgradeTask` to do this

I've set `trustLevel: "high"` and `allowedPostUpgradeCommands: ["^sed .+$"],` in my renovate's config.js

In my project i've added

```
"postUpgradeTasks": {
    "commands": ["sed -i 's#http://proxy.infra.mycompany.local:8000/registry.npmjs.org#https://registry.npmjs.org#ig' package-lock.json"],
    "fileFilters": ["package-lock.json"]
  }
```
Currently when I run renovate i'm getting this error **any idea what i'm doing wrong?**:
```
  "configError": {
         "configFile": "renovate.json",
         "validationError": "The renovate configuration file contains some invalid settings",
         "validationMessage": "Invalid configuration option: postUpgradeTasks"
       },
       "res": "created"
```

**Comment by rarkins** [comment]
Are you using an old version of Renovate?

I tested the `renovate.json` here with no problem: https://github.com/renovate-tests/npm30/blob/master/renovate.json

**Comment by henricook** [comment]
You're a hero Rhys, thanks. I followed [this guide](https://simplabs.com/blog/2019/04/24/dependency-updates-for-gitlab/) for easy setup, which seems to hard code to Renovate 15.0.0 - i'll bump now

**Comment by viceice** [comment]
@henricook  see [here](https://github.com/renovatebot/docker-renovate/blob/master/docs/gitlab.md) for running renovate on gitlab ci

**Comment by henricook** [comment]
Thanks @viceice - I suspect I saw this when I setup renovate up a month or so ago and discounted it because i'm only a lowly developer on my gitlab instance and don't have admin-level access to manually configure runners (as in the upper section of that link `Gitlab runner config`)

I've actually just got a node:10-buster-slim base image where i'm copying over a `package.json` + `package-lock.json` then configuring our private registry and running `npm ci`. That node:10 image is actually one we build locally because we bake all of our on-site proxy settings etc into the standard node:10 image, so it was there for to reuse.

I appreciate someone setting up renovate in an environment where they're:
  (a) not a gitlab admin 
  (b) have a complex gitlab-in-k8s setup 
  (c) have a compulsory proxy  
  (d) have a compulsory dependency cache 

.. is quite an unusual situation!

**Comment by viceice** [comment]
@henricook node 10 is no longer supported on renovate v20, so i suggest to use the dind version from our docs and remove the dind service. that should work if you only use npm clients

maybe you need to set `RENOVATE_BINARY_SOURCE=` so renovate uses the global npm and dont try docker side container. Let me know if it works, so i can add another sample to the docs

**Comment by henricook** [comment]
Seems to work so far but will upgrade to 11

Currently just getting around the compulsory github.com integration that came with version 20.x - got to get it working with my proxy

**Comment by henricook** [comment]
I'm not even sure there's a way for me to talk to the outside from our CI on a second look, is there any way to turn off the github integration @rarkins ?

Otherwise this might mean all my renovate work was for naught, i can't get our firewalling policy changed.

**Comment by viceice** [comment]
> Seems to work so far but will upgrade to 11
You need v12!

**Comment by henricook** [comment]
> > Seems to work so far but will upgrade to 11
> 
> You need v12!

:+1:

**Comment by rarkins** [comment]
> I'm not even sure there's a way for me to talk to the outside from our CI on a second look, is there any way to turn off the github integration @rarkins ?

What exactly do you mean? Changelog retrieval?

**Comment by henricook** [comment]
I don't have all the history but with version 15.0.0 installed this access to github.com didn't seem to be necessary. Now i've bumped to 20.0.0 to get `postUpgradeTasks` it needs github.com access. The easiest thing for me would be to turn it off, otherwise I need to figure out a way for my CI to speak to the outside world which I don't think is going to get sign off.

I appreciate my problems aren't your problems but any thoughts would be greatly valued

**Comment by viceice** [comment]
can you share debug logs where renovate needs github access and it fails?

**Comment by henricook** [comment]
Sure, it's just timing out trying to talk to api.github.com because it can't talk to my proxy (because proxy access isn't allowed in our CI env). Two secs

**Comment by henricook** [comment]
```
 INFO: getReleaseList error (repository=facebook/react)
       "err": {
         "name": "TimeoutError",
         "code": "ETIMEDOUT",
         "hostname": "api.github.com",
         "method": "GET",
         "path": "/repos/facebook/react/releases?per_page=100",
         "protocol": "https:",
         "url": "https://api.github.com/repos/facebook/react/releases?per_page=100",
         "gotOptions": {
           "path": "/repos/facebook/react/releases?per_page=100",
           "protocol": "https:",
           "hostname": "api.github.com",
           "hash": "",
           "search": "?per_page=100",
           "pathname": "/repos/facebook/react/releases",
           "href": "https://api.github.com/repos/facebook/react/releases?per_page=100",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate",
             "authorization": "***********"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [null],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "hostType": "github",
           "baseUrl": "https://api.github.com/",
           "gotTimeout": {"request": 60000}
         },
         "event": "request",
         "message": "Timeout awaiting 'request' for 60000ms",
         "stack": "TimeoutError: Timeout awaiting 'request' for 60000ms\n    at ClientRequest.request.once.error (/renovate/node_modules/got/source/request-as-event-emitter.js:176:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/renovate/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at Immediate.timeoutHandler (/renovate/node_modules/got/source/utils/timed-out.js:63:11)\n    at runCallback (timers.js:706:11)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\n    at process.topLevelDomainCallback (domain.js:126:23)"
       }
```

**Comment by viceice** [comment]
That's only a info message, renovate should go ahead and finish.

You can configure a short [timeout](https://docs.renovatebot.com/configuration-options/#timeout) for `github.com` with a `hostrule`, so it will not stuck 60 seconds

**Comment by henricook** [comment]
Oh interesting, it had looked to me like that was stopping MRs being updated... weird. I'll do a short timeout then try and debug again.

**Comment by henricook** [comment]
While that happens, are you open to an MR that'll "turn off" changelog fetching and hide all those log messages?

`config.fetchChangeLogs = false` (defaults to `true`) something like that?

**Comment by henricook** [comment]
It does look like packages that it's failing to getReleaseList for are then not being created as MRs. Nothing happens apart from the spammy github errors now on my runs and I know there should be MRs getting created.

**Comment by rarkins** [comment]
> While that happens, are you open to an MR that'll "turn off" changelog fetching and hide all those log messages?
> 
> `config.fetchChangeLogs = false` (defaults to `true`) something like that?
> 
> If so i'll add it to my OSS todo list

Definitely

**Comment by viceice** [comment]
> It does look like packages that it's failing to getReleaseList for are then not being created as MRs. Nothing happens apart from the spammy github errors now on my runs and I know there should be MRs getting created.

Can you please share the debug logs, so we can have a look whats happen?

**Comment by henricook** [comment]
Thanks, i'm going to delve into this myself hopefully over the next week or so - I'll let you know how it turns out!

**Comment by henricook** [comment]
I think we're good actually, just an old MR that had stopped updating even though the box was ticked. I renamed it and reran renovate and it created it properly, with my `postUpgradeTasks`

So apart from log spam (which i may raise a PR to approach with turning off changelog retrieval) I think i'm good go to! Thanks to you both again for your assistance
