### ISSUE TITLE
Using Github Installation App token not working

### ISSUE THREAD

**Issue by dominguezcelada** [renovatebot/config-help#669]
### Which Renovate are you using?
Renovate Open Source CLI (self-hosted)

### Which platform are you using?
GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

<details>
<summary>Logs</summary>
  "token": "***********",
       "err": {
         "name": "HTTPError",
         "hostname": "api.github.com",
         "method": "GET",
         "path": "/user",
         "protocol": "https:",
         "url": "https://api.github.com/user",
         "gotOptions": {
           "path": "/user",
           "protocol": "https:",
           "hostname": "api.github.com",
           "hash": "",
           "search": "",
           "pathname": "/user",
           "href": "https://api.github.com/user",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/vnd.github.machine-man-preview+json",
             "accept-encoding": "gzip, deflate",
             "authorization": "***********"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [null],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "hostType": "github",
           "baseUrl": "https://api.github.com/"
         },
         "statusCode": 401,
         "statusMessage": "Unauthorized",
         "headers": {
           "date": "Tue, 26 May 2020 13:47:57 GMT",
           "content-type": "application/json; charset=utf-8",
           "content-length": "83",
           "connection": "close",
           "server": "GitHub.com",
           "status": "401 Unauthorized",
           "x-github-media-type": "github.machine-man-preview; format=json",
           "x-ratelimit-limit": "60",
           "x-ratelimit-remaining": "59",
           "x-ratelimit-reset": "1590504477",
           "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
           "access-control-allow-origin": "*",
           "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
           "x-frame-options": "deny",
           "x-content-type-options": "nosniff",
           "x-xss-protection": "1; mode=block",
           "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
           "content-security-policy": "default-src 'none'",
           "vary": "Accept-Encoding, Accept, X-Requested-With",
           "x-github-request-id": "F5A3:8BEC:1F5116C:2508344:5ECD1E0D"
         },
         "body": {
           "message": "Bad credentials",
           "documentation_url": "https://developer.github.com/v3"
         },
         "message": "Response code 401 (Unauthorized)",
         "stack": "HTTPError: Response code 401 (Unauthorized)\n    at EventEmitter.<anonymous> (/Users/marc/mrf/myPlayground/renovate-test/node_modules/got/source/as-promise.js:74:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
DEBUG: Error authenticating with GitHub
       "err": {
         "message": "platform-failure",
         "stack": "Error: platform-failure\n    at handleGotError (/Users/marc/mrf/myPlayground/renovate-test/node_modules/renovate/dist/util/http/github.js:66:19)\n    at GithubHttp.request (/Users/marc/mrf/myPlayground/renovate-test/node_modules/renovate/dist/util/http/github.js:140:13)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }</details>

### What would you like to do?
We would like to use a Github Installation App token (for Github quota limit purposes).

When trying to use it, I get a HTTP 401 error because Renovate tries to connect to the following endpoint, which is not available on the list of [Github App Endpoints](https://developer.github.com/v3/apps/available-endpoints/):
`https://api.github.com/user`

It throws because of this:
https://github.com/renovatebot/renovate/blob/13842f655af0f6968fe7833c027305935024570d/lib/platform/github/index.ts#L103-L106

Researching on the source-code, we found out a global property called `appMode` which interacts with the API with the [Installation Token format](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation)

Commenting the quoted `throw new Error()` line and using the `global.appMode = true` it works but we would like to know:
- Is there something we are missing to use `appMode` out of the box?
- If what we point is a bug, would be as easy as adding a check like this?
```typescript
if(!global.appMode) {
   logger.debug({ err }, 'Error authenticating with GitHub');
   throw new Error('Init: Authentication failure');
}
```
- Also, is there a cleaner way to use `global.appMode` better than hardcoding it in our selfhosted `config.js`?:
```javascript
global.appMode = true;
module.exports = {
	binarySource: 'global',
	logLevel: 'debug',
	onboarding: false,
	persistRepoData: true,
	repositories: [`${process.env.REPO}`],
	token: process.env.GITHUB_TOKEN,
	privateKey: process.env.CDN_KEY
}
 
```

**Comment by rarkins** [comment]
I think you mean `global.appMode` instead of `globals.appMode` (i.e. drop the `s`).

I am open to accepting PRs to allow app tokens to work in place of personal access tokens, assuming we can do it cleanly.

Potentially it could be moved from a global to being an admin config option that can be passed via env, cli of config.js.

**Comment by dominguezcelada** [comment]
> I think you mean `global.appMode` instead of `globals.appMode` (i.e. drop the `s`).
> 
Fixed the typo 🙏 :)

**Comment by viceice** [comment]
[`/user`](https://developer.github.com/v3/users/#get-the-authenticated-user)  endpoint is there, your app needs the appropriate rights

**Comment by dominguezcelada** [comment]
> [`/user`](https://developer.github.com/v3/users/#get-the-authenticated-user) endpoint is there, your app needs the appropriate rights

Thanks for the answer. For Github User Token is available, but apparently for Github Apps, the list of available endpoints for `users` is a subset: https://developer.github.com/v3/apps/available-endpoints/#users

**Comment by viceice** [comment]
Strange, @rarkins Does the App something different? I thought it is calling `initPlatform` as usual?

**Comment by rarkins** [comment]
No, the app doesn't call `initPlatform()` for github - only gitlab.

**Comment by dominguezcelada** [comment]
Hi all,

Just to follow up on the issue, would the following solution be a valid patch to move forward until the re-design @rarkins is mentioning is discussed?

```javascript
if(!global.appMode) {
   logger.debug({ err }, 'Error authenticating with GitHub');
   throw new Error('Init: Authentication failure');
}
```

in https://github.com/renovatebot/renovate/blob/13842f655af0f6968fe7833c027305935024570d/lib/platform/github/index.ts#L103-L106

**Comment by rarkins** [comment]
@dominguezcelada if you think that solves it for you, but are you sure? Note I just started #6371 so let's close this and discuss there.

**Comment by dominguezcelada** [comment]
> @dominguezcelada if you think that solves it for you, but are you sure? Note I just started [renovatebot/renovate#6371](https://github.com/renovatebot/renovate/issues/6371) so let's close this and discuss there.

Point 6. on that issue would cover what I want to bypass :)
