### ISSUE TITLE
Why is not this PR automerged?

### ISSUE THREAD

**Issue by teppeis** [renovatebot/config-help#67]
This PR is patch update and I enable `: automergePatch` but it's not automerged.
PR: https://github.com/teppeis/bind.ts/pull/67
Config: https://github.com/teppeis/renovate-config

Previously, similar PRs have been automerged.
https://github.com/teppeis/bind.ts/pulls?q=is%3Apr+is%3Aclosed

This is related log from dashboard.
```
DEBUG: Checking #67 for automerge (dependencies=@types/node, branch=renovate/node-8.x)
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge
```

**Comment by rarkins** [comment]
Oh! Sorry, I changed something but forgot to update some presets. I would like to get your opinion first though. 

Users wanted a different way to apply rules for "bumped" ranges vs patch/minor/major updates, so now when we bump a range then the updateType is `bump` and not `patch` or `minor`. The `automergePatch` preset is just applying to ones where `updateType==="patch"` and not `updateType === 'bump'`.

Considering this I think it would be safe to update the `automergePatch` prefix to automerge both `patch` and `bump` updates, would you agree? Or would you prefer keeping it as-is and adding a new `automergeBump` preset?

**Comment by teppeis** [comment]
@rarkins Thanks.

Can I satisfy the following three at the same time?

A. I want to use `rangeStrategy=bump`
B. I want to update `^1.0.0` to `^1.0.1` with automerge
C. I want to update `^1.0.0` to `^1.1.0` without automerge (manually)

If both B and C have `updateType=bump`, I cannot distinguish them?

If cannot, I think it's better to separate major/minor/patch and pin/bump to different properties.
Because they are different concept.

**Comment by rarkins** [comment]
The logic I’m using is that if it’s within the current range then it’s not an upgrade at all and it’s a “bump”. Otherwise if it’s outside the current range/version then it’s one of major/minor or patch. 

If you need a difference in behaviour between 1.0.0->1.0.1 and 1.0.0->1.1.0 then it can only be achieved by setting tilde ~ instead of caret ^. Or using pinned versions rather than bumped ranges of course. For now I prefer not to make it any more complex until I understand a technical argument for using bumped ranges instead of pinned versions.

**Comment by teppeis** [comment]
This is my position.

#### Why use range instead of pin?

Because my repo is library, not app.
Using tilde may prevent from using newer deps in the future.

#### Why bump the range?

Because I want to narrow the version range that the library should support.
It avoid debugging with various combination of versions.
I can develop them on the premise of the latest version of functions and behaviors.

#### Why automerge only patch?

Because some libraries make bugs in minor upgrades.
I want to check the update before merge.

**Comment by rarkins** [comment]
@teppeis thanks for your description - I understand what you're trying to do now.

You might be interested in another idea I had for Renovate, aimed at library authors like yourself.

The idea is that you can define a "support policy" for dependency ranges, something like this:
- All patch versions less than 2 weeks old
- All minor versions less than 2 months old
- All major versions less than 6 months old

i.e. you drop support for all "old" major versions after 6 months, and for old minor versions after 2 months, and for "old" patch versions after 2 weeks. Obviously this would be customisable, even per-dependency (e.g. you could choose to extend support for certain dependencies for longer).

I was also thinking that we might support (optional) minimum/maximum quantities too, e.g. support at most 2 major versions, or 3 patches, minimum 2 minor versions, etc.

It sounds like you would want much shorter support periods than in my examples, although I think right now by using "bump" you're probably upgrading a bit quickly compared to most package authors. e.g. with automerge bump patch it means that you might be deprecating all old patches within only 1 hour of a new patch coming out, while most package authors not doing the same will be behind and this can cause duplications or conflicts in downstream packages.

**Comment by teppeis** [comment]
@rarkins Your new idea (support policy) is nice, but is it possible to configure them? 

For example,
```json
"packageRules": [
  {
    "updateTypes": ["patch"],
    "supportPolicy": "2 weeks"
  }
]
```

this doesn't work, because `updateTypes` cannot be `patch` (always `bump`) when `rangeStrategy=bump` and using `^` or `~` to specify the deps version.

> It sounds like you would want much shorter support periods than in my examples

Uhm.. my colleague likes this solution too.

> with automerge bump patch it means that you might be deprecating all old patches within only 1 hour of a new patch coming out, while most package authors not doing the same will be behind and this can cause duplications or conflicts in downstream packages.

I don't publish my package  every time dependency update and I use `unpublishSafe` for 24h delay.
I never faced such a conflict.

**Comment by teppeis** [comment]
@rarkins How about separating like this?

```js
"packageRules": [
  {
    "updateTypes": ["patch"], // (major|minor|patch)
    "updateRanges": ["inside"],  // (upper|lower|inside|pin)
    "automerge": true
  }
]
```

This spec satisfies the requirement of https://github.com/renovatebot/renovate/issues/1942.

After discussing with my team, we decided to give up using `rangeStrategy=bump` if the above spec is not accepted. I see `rangeStrategy=bump` is not recommended so much in Renovate from previous conversations.

**Comment by rarkins** [comment]
@teppeis can you describe and give examples of what you mean by upper/lower/inside/pin ?

**Comment by rarkins** [comment]
@teppeis so in your case you don't care if it's a bump or not - you just care if it's of type `patch`?

What I'm considering is to just emit an array of updateTypes instead of a single value, e.g. an update can be of type `patch` AND `bump` so you can apply the rule based on either.

**Comment by teppeis** [comment]
@rarkins 

> so in your case you don't care if it's a bump or not - you just care if it's of type patch?

Yes, exactly.

> What I'm considering is to just emit an array of updateTypes instead of a single value, e.g. an update can be of type patch AND bump so you can apply the rule based on either.

It's nice solution for me! Thanks!

**Comment by rarkins** [comment]
I have made a change so that Renovate still classifies bump updates as major/minor/patch, so this should now be working.

**Comment by teppeis** [comment]
@rarkins Thank you so much! Automerge works in my repo now!
