### ISSUE TITLE
automergeDev will only merge after 24 hours have passed

### ISSUE THREAD

**Issue by cynful** [renovatebot/config-help#670]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

```
" INFO: PR is not ready for merge (repository=org/renovate-config, dependencies=@org/semantic-release,renovate, branch=renovate/patch-patchreleases)
"
```
### What would you like to do?

I've enable automergeDev on some repositories.
The PR gets created just fine, but will not automerge because the repositories have checks that have yet to finish passing. So renovate will leave the PR open. This is desired behavior.

We run renovate every hour. So renovate should re-run on the repo and then automerge (an hour after the checks have passed). Instead renovate will merge after 24 hours.

I'm not sure what I'm missing in my configuration. Please help.

**Comment by rarkins** [comment]
You will need to log at debug level (e.g. LOG_LEVEL=debug) and verify what the logs are saying each run about the branches you expect to be automerging.
