### ISSUE TITLE
[Go] Web go not detected

### ISSUE THREAD

**Issue by waghanza** [renovatebot/config-help#671]
Hi,

Following https://github.com/the-benchmarker/web-frameworks/pull/2715, I have `webgo` reference in https://github.com/the-benchmarker/web-frameworks/blob/4b9c42be452e1c12d16fb7c13bd5f993437299e7/go/webgo/go.mod#L3

However, even the `go.mod` is detected (shown on dashboard), I have not any `PR` for this framework.

Regards,

**Comment by rarkins** [comment]
Renovate does not update indirect dependencies: https://github.com/renovatebot/renovate/issues/4586

**Comment by waghanza** [comment]
@bnkamalesh Thanks for your manual update, this issue was raise to `renovatebot`. It appears that `webgo` has not been updated automatically, so glad you've done it

**Comment by rarkins** [comment]
Can you clarify why it is declared as an indirect dependency?

**Comment by waghanza** [comment]
As far as I am concern I can not answer this. @bnkamalesh Any reason why ? 

Seems working without this flag, tho

**Comment by bnkamalesh** [comment]
@waghanza I think it was a mistake, and no reason otherwise.

**Comment by bnkamalesh** [comment]
> @bnkamalesh Thanks for your manual update, this issue was raise to `renovatebot`. It appears that `webgo` has not been updated automatically, so glad you've done it

Oh yes, did not notice this was on renovatebot repository. Came here directly from Github notification. Sorry about that.
