### ISSUE TITLE
Unable to reconfigure renovate

### ISSUE THREAD

**Issue by jjathman** [renovatebot/config-help#672]
**What Renovate type are you using?**

self-hosted renovate with Bitbucket server as the Git repository holder.

**Describe the bug**

Reading the documentation it looks like I should be able to create a PR with a title of "Reconfigure Renovate" and it will do some kind of validation on the `renovate.json` changes I have, but I am not seeing anything being done with it.

**Did you see anything helpful in debug logs?**

I've looked through the logs but I'm not sure what I should be looking for. Is there specific output related to these kinds of reconfigure PRs that can help me figure out what I've done wrong?

**Additional context**

I'm mostly looking for help here, I'm sure I just haven't configured something correctly but I don't really know what to look for in the debug output.

**Comment by rarkins** [comment]
You need to run the validation yourself manually, or add it as a check to your pipeline. The npm installation of Renovate comes with `renovate-config-validator`: https://github.com/renovatebot/renovate/blob/a1e025681cc5a60d47485f80efb595e76262ef10/package.json#L7

**Comment by rarkins** [comment]
BTW Renovate once used to attempt to validate user PRs with the name "Renovate" in the title or branch name, but it no longer does that directly - it was too inefficient and didn't work on forks.

**Comment by jjathman** [comment]
OK thanks for the help. Does this documentation need updating then to reflect that this isn't done automatically anymore? https://docs.renovatebot.com/reconfigure-renovate/

**Comment by rarkins** [comment]
Actually it seems like the validator was left out by mistake - please track https://github.com/renovatebot/docker-renovate/issues/31
