### ISSUE TITLE
Disable github-releases and github-tags datasources

### ISSUE THREAD

**Issue by philippe-granet** [renovatebot/config-help#675]
### Which Renovate are you using?
Renovate Open Source CLI

### Which platform are you using?
GitLab self-hosted

### What would you like to do?

I use Renovate in an enterprise network, on Gitlab hosted, with no Internet access and no proxy available, for security reasons.
Renovate generates more than 1000 warning logs for all our projects like this:
```
WARN: No github.com token has been configured. Skipping release notes retrieval (repository=my-repo)
       "manager": "maven",
       "depName": "com.fasterxml.jackson.core:jackson-annotations",
       "sourceUrl": "https://github.com/FasterXML/jackson-annotations"
```
I tried this but it doesn't disable warn logs:
```json
    "packageRules": [
        {
            "managers": ["maven", "npm"],
            "datasources": ["github-releases", "github-tags"],
            "enabled": false
        }]
```

**Comment by rarkins** [comment]
Release notes are fetched independently of datasources so can't be affected by `packageRules`. I added a new feature request to track this: https://github.com/renovatebot/renovate/issues/6385

BTW I suggest the following to make sure you don't miss any:

```
    "packageRules": [
        {
            "datasources": ["github-releases", "github-tags"],
            "enabled": false
        }]
```
