### ISSUE TITLE
Is lockFileMaintenance always enabled when schedule is set?

### ISSUE THREAD

**Issue by shisama** [renovatebot/config-help#677]
Does `"lockFileMaintenance"` happen to be enabled if `"schedule"` is set whether `"enabled"` is true or not?
Although `"lockFileMaintenance"` has been disabled, "lock file maintenance" PR was created in our repository.

```json
"lockFileMaintenance": {
  "enabled": false,
  "schedule": [
    "before 3am on the first day of the month"
  ]
},
```

### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

If the answer is 'yes', it is better to indicate it in the document (https://docs.renovatebot.com/configuration-options/#lockfilemaintenance).

**Comment by rarkins** [comment]
The answer is No: https://github.com/renovatebot/renovate/blob/01be64987b4bb35f7f0e2f0b291c7e6d4789332e/lib/config/definitions.ts#L1285
