### ISSUE TITLE
'includePaths' mandatory for monorepo's?

### ISSUE THREAD

**Issue by daern91** [renovatebot/config-help#68]
Hi,

We have a problem with this monorepo. 
https://github.com/commercetools/nodejs

How can we set up the config to have it search for `package.json` files in the whole repo? We have one in root folder and multiple more inside `./packages/${package}/` as well as `./integration-tests`

Below is our current `.renovaterc.json`.
```json
{
  "extends": [
    "config:base",
    ":pinOnlyDevDependencies",
    "group:monorepos",
    "schedule:weekly"
  ]
}
```

Thanks a lot for all help and work you do on renovate

**Comment by daern91** [comment]
Ahh, thanks for the dashboard hint. I think this is actually a problem on our end. 

Thanks for the quick reply and trevlig helg!

**Comment by rarkins** [comment]
Ingen orsak!
