### ISSUE TITLE
Multiple private registries with same encrypted token

### ISSUE THREAD

**Issue by paksu** [renovatebot/config-help#680]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com
### What would you like to do?

Our `.npmrc` looks like this
```
@ns1:registry=https://some-registry/npm/ns1/
@ns2:registry=https://some-registry/npm/ns2/
//https://some-registry/npm/ns1/:_auth=${NPM_TOKEN}
//https://some-registry/npm/ns2/:_auth=${NPM_TOKEN}
```
Does the renovate encrypted npm token mechanism support this if we placed the `npmrc` above in the renovate configurations with the encrypted npm token? 

Is it possible to have multiple registries that share the same encrypted secret so they both get replaced properly?

**Comment by JamieMagee** [comment]
I think you want [Encrypted entire .npmrc file into config](https://docs.renovatebot.com/private-modules/#encrypted-entire-npmrc-file-into-config) from the docs. Take a look at that and see if it works for you.

**Comment by paksu** [comment]
I would but it's too long for the encryption as there is a length limit

**Comment by viceice** [comment]
You can alternative use a hostRule with hostType=npm to configure credentials

**Comment by viceice** [comment]
See https://github.com/renovatebot/config-help/issues/678

**Comment by paksu** [comment]
@viceice If I read that correctly it would hardcode the url parameter to `_authToken` which won't work as we are using JFrog Artifactory were the token needs to be `_auth=` as in my example.

**Comment by paksu** [comment]
I was thinking if this replace should just be a global one https://github.com/renovatebot/renovate/blob/2515a89dabf88bd6d4cf06386053352ea4107f7e/lib/config/decrypt.ts#L56

**Comment by rarkins** [comment]
FYI: https://github.com/renovatebot/renovate/pull/6431

Does not solve the problem on its own. Ideally, shouldn't it be that if the user configures `npmToken` then we pass it as `NPM_TOKEN` in env?

**Comment by paksu** [comment]
I think that should work for me as I have the `.npmrc` in the renovate configurations, not committed as a file to the repo
