### ISSUE TITLE
clarification on stabilityDays

### ISSUE THREAD

**Issue by tony1377** [renovatebot/config-help#682]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Azure DevOps

### What would you like to do?

I'd like to clarify the expected behaviour of `stabilityDays:10` combined with `prCreation: "not-pending"`

I thought, if I had the config above, and if there was a library which publishes updates every day. 
Then renovate would create a PR for the published version of that lib which is no less than 10 days old. 

But it looks like renovate gets the latest published version (published yesterday), checks it's age against stablity days and see's that it's not 10 days old yet, so never creates a pr.

Is the behaviour I'm seeing expected? If so is there a configuration which allows me to achieve only getting pr's for releases which are x days old when there are newer versions avaialble?

**Comment by rarkins** [comment]
What you're seeing is the currently expected behavior. You could maybe work around it a little if you set separateMinorPatch=true, because then you'd get separate branches for patches vs minor and eventually each patch branch should go stable.

**Comment by tony1377** [comment]
So are you saying to have `separateMinorPatch=true` combined with `stabilityDays:10` and `prCreation: "not-pending"`?

Would that create this behaviour?

   - minor versions for libA
      - renovate only creates minor branch pr if latest minor is 10 days+ old
   - patch versions for libA
      - renovate - only creates patch branch pr if latest patch is 10 days+ old

If so, it would still have the above issue of never creating a pr for libA if they published minor and patch updates more frequently than 10 days right?

**Comment by rarkins** [comment]
That’s right. There’s also a “pr not pending timeout” to think about too I think.

**Comment by tony1377** [comment]
ok, thanks for the fast responses 👍
