### ISSUE TITLE
Config to prevent reusing branch and trustLevel questions

### ISSUE THREAD

**Issue by gibbsonn** [renovatebot/config-help#683]
### Which Renovate are you using?

Renovate Open Source CLI

### What would you like to do?

Currently if an existing pr for a lib minor version is present and a newer minor version for that lib is published, Renovate will update the existing PR with the new version. Is there a way to get Renovate to publish a new PR instead? 

For the `trustLevel` config option, what are the security implications of having the level at "high"?

**Comment by rarkins** [comment]
> Currently if an existing pr for a lib minor version is present and a newer minor version for that lib is published, Renovate will update the existing PR with the new version. Is there a way to get Renovate to publish a new PR instead?

Currently there is not. Renovate's default behaviour is to have up to 2 PRs per package: the highest major update, and the highest non-major update. You can increase this by opting into separating each major update (separateMultipleMajor) or separating Minor from Patch (separateMinorPatch). It sounds like you'd want a `separateMultipleMinor` feature, so please raise a feature request if so.

> For the `trustLevel` config option, what are the security implications of having the level at "high"?

Search through the code to be sure: https://github.com/renovatebot/renovate/search?q=global.trustLevel&unscoped_q=global.trustLevel

- variable substitution in .npmrc files
- passes full env to child processes
- allows scripts to run for npm/yarn/pnpm/composer
- enables post-upgrade tasks

**Comment by tony1377** [comment]
brilliant, thanks
