### ISSUE TITLE
packageRules priority

### ISSUE THREAD

**Issue by oomathias** [renovatebot/config-help#684]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

My `packageRules`:

```json
    [{
	  "commitMessagePrefix": "major",
      "depTypeList": ["dependencies"],
      "updateTypes": ["major"],
    },
    {
      "commitMessagePrefix": "minor",
      "groupName": "js dependencies (non-major)",
      "depTypeList": ["dependencies"],
      "updateTypes": ["minor", "patch"],
    },
    {
 	  "commitMessagePrefix": "native",
      "depTypeList": ["dependencies"],
      "packagePatterns": ["native"],
    }]
```

**Actual behaviour:**
- All majors deps have the "major" commit message (including native)
- All minors and patch are in the "minor" group (including native)

**Expected behaviour:**
- All major dependencies to create one PR each.
- All minor and patch dependencies to be grouped in one PR.
- All package containing native to create a PR each (overriding previous rules).

Can you confirm that each "packageRules" is totally isolated and that the latest one in the list takes priority?

<img width="688" alt="Screenshot 28" src="https://user-images.githubusercontent.com/465790/83871229-9eeb3800-a727-11ea-925c-7d2bc4ae3ae9.png">
<img width="643" alt="Screenshot 29" src="https://user-images.githubusercontent.com/465790/83871677-626c0c00-a728-11ea-96b9-d93cd4a2dea9.png">

Full config for reference, maybe something is actually misconfigured elsewhere.
```json
{
  "extends": [
    "config:base",
    ":masterIssue",
    ":disableRateLimiting",
    ":timezone(Europe/London)",
    ":enableVulnerabilityAlertsWithLabel(security)",
    ":maintainLockFilesWeekly",
    ":pinAllExceptPeerDependencies",
    ":assignee(@oomathias)",
    ":automergeBranch",
    ":automergeRequireAllStatusChecks"
  ],
  "semanticCommits": false,
  "stabilityDays": 3,
  "prCreation": "not-pending",
  "rangeStrategy": "auto",
  "commitMessageSuffix": "(run-e2e)",
  "masterIssueApproval": true,
  "packageRules": [
    {
      "commitMessagePrefix": "dev major -",
      "depTypeList": ["devDependencies"],
      "updateTypes": ["major"],
      "extends": ["schedule:earlyMondays"],
      "labels": ["dependencies", "dev"],
      "masterIssueApproval": false
    },
    {
      "groupName": "devDependencies (non-major)",
      "depTypeList": ["devDependencies"],
      "updateTypes": ["minor", "patch"],
      "extends": ["schedule:earlyMondays"],
      "labels": ["dependencies", "dev"],
      "masterIssueApproval": false,
      "automerge": true
    },
    {
      "commitMessagePrefix": "js major -",
      "depTypeList": ["dependencies"],
      "updateTypes": ["major"],
      "extends": ["schedule:earlyMondays"],
      "labels": ["dependencies", "js"]
    },
    {
      "groupName": "js dependencies (non-major)",
      "depTypeList": ["dependencies"],
      "updateTypes": ["minor", "patch"],
      "extends": ["schedule:earlyMondays"],
      "labels": ["dependencies", "js"],
      "masterIssueApproval": false
    },
    {
      "commitMessagePrefix": "native -",
      "depTypeList": ["dependencies"],
      "packagePatterns": ["native"],
      "extends": ["schedule:earlyMondays"],
      "labels": ["dependencies", "native"]
    },
    {
      "depTypeList": ["dependencies"],
      "packagePatterns": ["^@myorg/"],
      "extends": ["schedule:daily"],
      "labels": ["dependencies", "myorg"],
      "masterIssueApproval": false,
      "automerge": true
    },
    {
      "extends": ["packages:linters", "packages:test"],
      "packagePatterns": ["^@types/"],
      "masterIssueApproval": false,
      "automerge": true
    }
  ]
}
```

**Comment by rarkins** [comment]
> * All package containing native to create a PR each (overriding previous rules).

You didn't override the `groupName` you set earlier. So either use a `excludePackagePatterns` rule in the earlier rules where you set `groupName` or set `groupName` to `null` in your native rule.

**Comment by oomathias** [comment]
@rarkins Thanks you for the fast answers, it makes sense.

I assumed that only the last matching rule was applied (vs all applied in sequence).
I guess it's worth flagging in the documentation.

Resolving.

**Comment by rarkins** [comment]
It already says this in the docs:


Important to know: Renovate will evaluate all packageRules and not stop once it gets a first match. Therefore, you should order your packageRules in order of importance so that later rules can override settings from earlier rules if necessary.
