### ISSUE TITLE
is prCreation:not-pending supported on azure?

### ISSUE THREAD

**Issue by tony1377** [renovatebot/config-help#685]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?
Azure DevOps

### What would you like to do?

I'd like to know if `prCreation:"not-pending"` is supported on azure.

Looking through the code it seems like the function linked below is used to determine if a branch is "not-pending", but it looks like it's checking the branchStats.aheadCount which doesn't appear related to if the branch has all tests/builds completed successfully, so maybe I've got that wrong.

https://github.com/renovatebot/renovate/blob/master/lib/platform/azure/index.ts#L415

Do you know if this feature is supported in azure?

**Comment by viceice** [comment]
Build status checks are not yet supported on azure, so 'prCreation:"not-pending"' won't work as expected
