### ISSUE TITLE
Configure several hours window as a schedule?

### ISSUE THREAD

**Issue by cy6erskunk** [renovatebot/config-help#686]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Checking schedule(after 7am every weekday,before 9am every weekday, Europe/Helsinki)(branch="renovate/node-12.x")
DEBUG: Found timezone(branch="renovate/node-12.x")
{
  "timezone": "Europe/Helsinki"
}
DEBUG: Adjusting now for timezone(branch="renovate/node-12.x")
DEBUG: Checking 2 schedule(s)(branch="renovate/node-12.x")
DEBUG: Checking schedule "after 7am every weekday"(branch="renovate/node-12.x")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_a": [
          25200
        ],
        "d": [
          2,
          3,
          4,
          5,
          6
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: Does not match schedule because 3751 is earlier than 25200(branch="renovate/node-12.x")
DEBUG: Checking schedule "before 9am every weekday"(branch="renovate/node-12.x")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          32400
        ],
        "d": [
          2,
          3,
          4,
          5,
          6
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: Matches schedule before 9am every weekday(branch="renovate/node-12.x")
```

### What would you like to do?

We would like to configure renovate schedule like this:
```
after 7am every weekday,before 9am every weekday
```
so that it would create PRs between 7 am and 9 am only. But according to the logs, Renovate `OR`s elements in the schedule array. Is there any way to get something similar to `AND` behavior-wise? Some hacky approach maybe?

**Comment by rarkins** [comment]
If you check out our schedule tests you can find some examples e.g. https://github.com/renovatebot/renovate/blob/f652a8c7d6cd3f7316d91f8f0f7f0246b7bb0a8e/lib/workers/branch/schedule.spec.ts#L92

**Comment by cy6erskunk** [comment]
Oh, great! I was looking for more extensive examples in the docs but could not find them. I guess, it would make sense to have them documented?

**Comment by rarkins** [comment]
If there are any in the tests that you think would be good to add to the docs, a PR would be welcome. The source is here: https://github.com/renovatebot/renovate/blob/master/docs/usage/configuration-options.md#schedule

**Comment by cy6erskunk** [comment]
Now I can see that I do have documentation blindness 🤦 Sorry for bothering and thanks a lot for your help!
