### ISSUE TITLE
How to slecet specific package to be up-to-date

### ISSUE THREAD

**Issue by ehsan-tashkhisi** [renovatebot/config-help#688]
I want to specify a list of packages which I want to be up-to-date but not other packages

**Comment by rarkins** [comment]
Like this:

```json
{
  "packageRules": [{
    "packagePatterns": ["*"],
    "excludePackageNames": ["abc", "def"],
    "enabled": false
  }]
}
```

**Comment by ehsan-tashkhisi** [comment]
Thanks a lot, but I wonder if I can use complex RegularExpression or not
Something like this one:
packageRules: [
          {
               packagePatterns: "^(?!com\.googlecode\.libphonenumber).*$",
               enabled: false
          }
     ]

**Comment by rarkins** [comment]
Sure, but test it out during onboarding if possible to make sure you’ve got the pattern right.
