### ISSUE TITLE
Support for Basic Authenticaiton scheme for npm

### ISSUE THREAD

**Issue by nishants** [renovatebot/config-help#691]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Azure DevOps - **self hosted**

### Have you checked the logs? Don't forget to include them if relevant
Yes

### What would you like to do?

For the npm repositories, currently, Bearer authentication scheme is hardcoded: https://github.com/renovatebot/renovate/blob/5ba8570699b041ea273cfb33a5a574cce84bf072/lib/datasource/npm/get.ts#L87.

To allow using Basic authentication scheme, it would be nice to have a flag in configuration i.e. 
```
  repositories: ['Abc/XYZ'],
          hostRules:[ {
             "hostType": "npm",
             "token": "<token>"
             "authSchemeBasic":  true
           },
    {
```
For our private npm registry, we use the Base64 encoded token for authentication.

**Comment by viceice** [comment]
@nishants How do you generate your tokens? If you need basic auth it should be something like `'user:pass'.toBase64()` so you need to configure your `npmrc` as follows:

```ini
//npm.domain.com/:_auth:<token>
```

**Comment by viceice** [comment]
If you need more help please fill our issue [template](https://github.com/renovatebot/config-help/issues/new?labels=&template=config-help.md&title=)

**Comment by rarkins** [comment]
Prior to the line you highlighted, Renovate calls out to a function that takes Basic authentication into consideration: https://github.com/renovatebot/renovate/blob/5ba8570699b041ea273cfb33a5a574cce84bf072/lib/datasource/npm/get.ts#L79
