### ISSUE TITLE
Renovate re-writes description on every run

### ISSUE THREAD

**Issue by nishants** [renovatebot/config-help#692]
**What Renovate type are you using?**
Azure Devops Server **(self hosted)**

**Describe the bug**
If I change the pull request description manually, the renovate bot resets the description every time and manual changes are lost.

**Did you see anything helpful in debug logs?**
Nothing relevant.

**To Reproduce**
Change the description of the pull request created by renovate and run renovate again. The pull request description is reset and update is lost.

**Comment by rarkins** [comment]
What's your reason for changing the PR description?

**Comment by nishants** [comment]
Thanks @viceice 
Just to clarify, it resets description even if there are no manual changes in PR and neither any changes required by renovate?

@rarkins We have different people taking ownership of different modules and ensuring it is safe to merge the PR. Being able to update description would have been convenient.

**Comment by rarkins** [comment]
> Just to clarify, it resets description even if there are no manual changes in PR and neither any changes required by renovate?

It doesn't so much as reset it but it ensures it's correct according to the current state. There are multiple reasons why it may need to update it, including an update of changelogs, a newer version, etc.

Does Azure DevOps server support PR comments? Or when you review non-bot PRs do you also add or edit to your co-worker's descriptions too?

**Comment by nishants** [comment]
I get your point.  As mentioned in the comment above, we are talking about when there are no **changes required by renovate** (when no changelogs, versions are updated)

We add information like impacted areas in PR description for code reviews and testing. 

Thanks for your input.
