### ISSUE TITLE
Renovate Multi repo configuration

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#696]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

We have hosted renovate using kubarnettes image and configured for a repo, its working fine.

Now we would like to configure this to multiples repo & for each repo we want  renovate to look in to different branch & with different approvers. Could you please help us with this configuration?

Also, If we configure multiple repo, processing the repo would be sequential or parallel? Can  we implement multithreading? since we are planning to use renovate for more than 100 repos?

Thanks!!!

**Comment by rarkins** [comment]
> Now we would like to configure this to multiples repo & for each repo we want renovate to look in to different branch & with different approvers. Could you please help us with this configuration?

I recommend you have a `renovate.json` in each repository and it can specify `baseBranches` as well as `reviewers` in - please search the documentation for these.

Renovate runs sequentially. You could try running multiple pods but having non-overlapping `autodiscoverFilter` values.

**Comment by sakshan** [comment]
@rarkins @viceice 

We don want to spinup multiple pods. Can we do multithreading? i.e executing 10 repos at a time once complete take another 10 like that?

**Comment by viceice** [comment]
you can add all repos at once, renovate will process them in sequence
