### ISSUE TITLE
Execute Renovate paticular time in a day

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#697]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

We have configured Renovate in our enterprise using kubernetes. I know we have a schedule paramter in configuration file (renovate-cronjob) . But if want to run renovate particualr time everyday how to configure in this file? Could you please share any sample?

Thanks!!!

**Comment by rarkins** [comment]
Sorry, please explain in more detail about why Renovate's `schedule` doesn't satisfy your needs.

**Comment by sakshan** [comment]
@rarkins 

Could you please help me to shedule renovate to run particular time every day?

**Comment by viceice** [comment]
@sakshan Please follow docs [here](https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#kubernetes)   and then kubernetes schedule [format](https://pkg.go.dev/github.com/robfig/cron?tab=doc#hdr-CRON_Expression_Format)
