### ISSUE TITLE
How do I customize semanticCommitType depending on major/minor/patch update only for certain packages?

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/config-help#70]
For packages that we maintain, I want the `semanticCommitType` to be `feat` or `fix` depending on what the type of the update is. All other packages I want to use `chore`.

I tried this:
```json
{
  "$schema": "http://json.schemastore.org/renovate",
  "extends": ["config:base"],
  "timezone": "America/Los_Angeles",
  "schedule": ["on the 1st through 7th day of the month"],
  "lockFileMaintenance": {
    "schedule": ["on the 1st through 7th day of the month"]
  },
  "updateNotScheduled": true,
  "prCreation": "not-pending",
  "semanticCommits": true,
  "semanticCommitType": "chore",
  "rangeStrategy": "replace",
  "packageRules": [
    {
      "packagePatterns": ["^@sourcegraph/"],
      "packageNames": ["cxp"],
      "rangeStrategy": "bump",
      "schedule": [],
      "minor": {
        "semanticCommitType": "feat"
      },
      "patch": {
        "semanticCommitType": "fix"
      }
    },
    {
      "packagePatterns": ["^@types/"],
      "rangeStrategy": "pin",
      "automerge": true
    }
  ]
}
```
But Renovate applies `fix` to foreign packages instead of `chore`:

> <details>
> <summary>fix(deps): update dependency marked to ^0.4.0</summary>
> 
>   - Schedule: ["on the 1st through 7th day of the month"]
>   - Branch name: `renovate/marked-0.x`
>   - Upgrade [marked](https://github.com/markedjs/marked) to `^0.4.0`
>   - Upgrade [@types/marked](https://github.com/DefinitelyTyped/DefinitelyTyped) to `0.4.0`
> 
> 
> </details>
> 
> <details>
> <summary>fix(deps): update dependency omnicli to v0.1.13</summary>
> 
>   - Schedule: ["on the 1st through 7th day of the month"]
>   - Branch name: `renovate/omnicli-0.x`
>   - Upgrade omnicli to `0.1.13`
> 
> 
> </details>

**Comment by rarkins** [comment]
As you're extending `config:base`, it already includes some rules for semantic commit types that may be taking precedence (See [here](https://github.com/renovatebot/presets/blob/1101db36308405a9c25f1070bb58dbf58aedfbf1/packages/renovate-config-config/package.json#L24) and then [here](https://github.com/renovatebot/presets/blob/1101db36308405a9c25f1070bb58dbf58aedfbf1/packages/renovate-config-default/package.json#L135-L151). As a result you'll need to put your default in a package rule to override it. Could you try this instead?

```json
{
  "$schema": "http://json.schemastore.org/renovate",
  "extends": ["config:base"],
  "timezone": "America/Los_Angeles",
  "schedule": ["on the 1st through 7th day of the month"],
  "lockFileMaintenance": {
    "schedule": ["on the 1st through 7th day of the month"]
  },
  "updateNotScheduled": true,
  "prCreation": "not-pending",
  "semanticCommits": true,
  "rangeStrategy": "replace",
  "packageRules": [
    {
      "packagePatterns": [".*"],
      "semanticCommitType": "chore"
    },
    {
      "packagePatterns": ["^@sourcegraph/"],
      "packageNames": ["cxp"],
      "rangeStrategy": "bump",
      "schedule": [],
      "minor": {
        "semanticCommitType": "feat"
      },
      "patch": {
        "semanticCommitType": "fix"
      }
    },
    {
      "packagePatterns": ["^@types/"],
      "rangeStrategy": "pin",
      "automerge": true
    }
  ]
}
```

**Comment by felixfbecker** [comment]
I'll try that, thanks!

**Comment by felixfbecker** [comment]
Unfortunately, that didn't work. It created a PR for an `@sourcegraph` package that was a patch release, but it used `chore` as the commit type.

**Comment by rarkins** [comment]
Sorry, I see one more thing I missed the first time. Check out https://github.com/renovatebot/config-help/issues/67 for the reason why bump + minor/patch rules are not currently working. Anything "bumped" will get an update type of "bump" and not "patch" or "minor" but seeing as you're the second bump user to need this, it might be time for a refactor.

**Comment by rarkins** [comment]
I have made a change so that Renovate still classifies bump updates as major/minor/patch, so you should hopefully see the semantic commit prefix you are looking for.

**Comment by rarkins** [comment]
@felixfbecker can you confirm if current  behaviour is what you’re expecting?

**Comment by felixfbecker** [comment]
Seems to be working
