### ISSUE TITLE
"Repository is disabled - skipping" after onboarding MR closed and branch deleted

### ISSUE THREAD

**Issue by renestalder** [renovatebot/config-help#704]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```json
{"name":"renovate","hostname":"<strippedOut>","pid":108326,"level":40,"logContext":"Kce_67XRy","repository":"<strippedOut>","msg":"Unable to initialise git submodule at docs","time":"2020-06-16T11:24:51.329Z","v":0}
```
### What would you like to do?

Initalize Renovate on a repository.

it worked, the first time and created an onboarding merge request. It didn't fit my needs, so I deleted it including the branch. Now everytime I try to run it the same command again with the extended configuration, it tells me, the repository being disabled.

Config (renovate.js):

```js
require('dotenv').config();

module.exports = {
  endpoint: '<stripedOut',
  token: '<stripedOut>',
  platform: 'gitlab',
  logFileLevel: 'warn',
  logLevel: 'info',
  logFile: './renovate.log',
  onboarding: true,
  enabled: true,
  prHourlyLimit: 2,
  rangeStrategy: 'replace',
  schedule: ['after 10pm every weekday', 'every weekend', 'before 5am every weekday'],
  onboardingConfig: {extends: ['config:base']},
  commitMessagePrefix: 'chore',
  repositories: ['<stripedOut>'],
  labels: ['dependencies'],
  lockFileMaintenance: {enabled: true},
  packageRules: [
    {packagePatterns: ['^apollo'], groupName: 'Apollo dependencies'},
    {
      packagePatterns: ['^@nuxtjs', '^@nuxt', '^nuxt'],
      groupName: 'Nuxt dependencies'
    },
    {
      packagePatterns: ['^@nuxtjs', '^@nuxt', '^nuxt', 'vue', '^@vue'],
      groupName: 'Vue Core dependencies'
    },
    {
      packagePatterns: ['^@babel', '^babel'],
      groupName: 'Babel dependencies'
    },
    {
      packagePatterns: ['^@graphql-codegen', '^graphql', '@types/graphql'],
      groupName: 'GraphQL dependencies'
    },
    {
      packagePatterns: ['^jest', '^ts-jest', '@types/jest', 'vue-jest'],
      groupName: 'Jest dependencies'
    },
    {
      packagePatterns: ['^tslint', '^ts-jest', '^ts-'],
      groupName: 'TypeScript dependencies'
    }
  ]
};
```

Run by:

```sh
$ RENOVATE_CONFIG_FILE="./renovate.js" renovate
```

Output:

```sh
 INFO: Repository started (repository=<stripedOut>)
       "renovateVersion": "21.10.1"
 WARN: Unable to initialise git submodule at docs (repository=<stripedOut>)
 INFO: Repository is disabled - skipping (repository=<stripedOut>)
 INFO: Repository finished (repository=<stripedOut>)
       "durationMs": 5261
```

So what part did I get wrong?

**Comment by rarkins** [comment]
Add a configuration manually or rename the Configure Renovate MR

**Comment by renestalder** [comment]
@rarkins Thanks for the quick answer. The renaming of the MR indeed did the trick. Is this a special case that could be handled differently e.g. would it help when I open an issue on the renovate repository to ask for handling that with a more accurate message or is this simply me not understanding how everything works?

Also, assuming that I already created that configuration manually but have the `onboarding` properties active, are the rest of my settings even considered when starting the whole thing with an onboarding MR?

**Comment by rarkins** [comment]
> @rarkins Thanks for the quick answer. The renaming of the MR indeed did the trick. Is this a special case that could be handled differently e.g. would it help when I open an issue on the renovate repository to ask for handling that with a more accurate message or is this simply me not understanding how everything works?

Please don't open an issue, as this is intended behavior. Otherwise, users would have no way to ignore an onboarding MR if it keeps getting recreated every time it's closed. I think you should have seen a MR comment added *too*, to make it even clearer?

The message isn't inaccurate either - I recommend you log at DEBUG mode to get more details.

I don't understand the rest of your question. Best if you create a new issue with full details. Please run in DEBUG mode first in case there's any useful information there that you're missing.
