### ISSUE TITLE
Schedule for renovate

### ISSUE THREAD

**Issue by cynful** [renovatebot/config-help#706]
### Which Renovate are you using?

Renovate Open Source CLI

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I'm trying to configure renovate to only make PRs on the 3rd day of the month.
I've tried
```
  "schedule": ["before 3am on the third day of the month"],
```
and get a validation error.

Also as another question:
```
  "schedule": ["every month"],
```
validates correctly. What would the schedule be like? Is it just the first day of the month?

Thanks

**Comment by rarkins** [comment]
Can you try this?

```
  "schedule": ["before 3:00am on the third day of the month"],
```

We have a couple of tests like this:

```
    it('massages schedules', () => {
      expect(
        schedule.hasValidSchedule([
          'before 3am on the first day of the month',
        ])[0]
      ).toBe(true);
      expect(schedule.hasValidSchedule(['every month'])[0]).toBe(true);
    });
```

And here's the source code for the monthly shortcuts:

https://github.com/renovatebot/renovate/blob/c4a0940049dc43e571bdf5633b4cd712b8f3eb0d/lib/workers/branch/schedule.ts#L7-L10

**Comment by cynful** [comment]
I've tried with `3am` and `3:00am`, however when I run renovate-config-validator it still errors out. I also agree, and think that it has a problem with `third`

**Comment by cynful** [comment]
I just tried `before 3:00am on the 3 day of the month` and this succeeded 🎉
