### ISSUE TITLE
PRs only update package.json not package-lock.json

### ISSUE THREAD

**Issue by DevRCRun** [renovatebot/config-help#708]
### Which Renovate are you using?

Renovate Open Source CLI (via the npm package)

### Which platform are you using?

Azure DevOps (I am currently running renovate from my Win10 enterprise machine while testing)

### Have you checked the logs? Don't forget to include them if relevant

Yes, I'm running with --log-level=debug nothing immediately jumps out as wrong. 

Don't really want to try redacting the entire log and uploading here in case I miss something (internal project). Looking at the run it states

```
DEBUG: Writing package.json files (repository=snip, branch=renovate/sequelize-5.x)
       "packageFiles": ["package.json"]
DEBUG: Writing package-lock.json (repository=snip, branch=renovate/sequelize-5.x)
DEBUG: Writing any updated package files (repository=snip, branch=renovate/sequelize-5.x)
DEBUG: No updated lock files in branch (repository=snip, branch=renovate/sequelize-5.x)
DEBUG: No files to commit (repository=snip, branch=renovate/sequelize-5.x)
```

Azure devops is a complete pain, in that it won't actually let me delete the branch and the PR (I can only abandon the latter). If I delete the branch it does actually make it error, but I'm not sure if this is because I've just forced it into an inconsistent state? It does occur around lockfile generation so included here

```
DEBUG: Updating lock file only (repository=snip, branch=renovate/validator-13.x)
DEBUG: No node constraint found - using latest (repository=snip, branch=renovate/validator-13.x)
DEBUG: Executing command (repository=snip, branch=renovate/validator-13.x)
       "command": "npm install --package-lock-only --ignore-scripts --no-audit"
DEBUG: exec completed (repository=snip, branch=renovate/validator-13.x)
       "cmd": "npm install --package-lock-only --ignore-scripts --no-audit",
       "durationMs": 485,
       "stdout": "",
       "stderr": "Error: Failed to replace env in config: ${APPDATA}\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:415:13\n    at String.replace (<anonymous>)\n    at envReplace (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:411:12)\n    at parseField (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:389:7)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:330:24\n    at Array.forEach (<anonymous>)\n    at Conf.add (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:328:23)\n    at ConfigChain.addString (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\config-chain\\index.js:244:8)\n    at Conf.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:316:10)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\graceful-fs\\graceful-fs.js:115:16\nError: Failed to replace env in config: ${APPDATA}\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:415:13\n    at String.replace (<anonymous>)\n    at envReplace (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:411:12)\n    at parseField (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:389:7)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:330:24\n    at Array.forEach (<anonymous>)\n    at Conf.add (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:328:23)\n    at ConfigChain.addString (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\config-chain\\index.js:244:8)\n    at Conf.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\lib\\config\\core.js:316:10)\n    at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\graceful-fs\\graceful-fs.js:115:16\n"
DEBUG: package-lock.json hasn't changed (repository=snip, branch=renovate/validator-13.x)
DEBUG: No updated lock files in branch (repository=snip, branch=renovate/validator-13.x)
```

### What would you like to do?

Dependencies in package.json are pinned, both this and package-lock.json are committed to version control. When renovate files its PR, it only seems to be updating package.json (i.e. it is not making a change to package-lock.json). In my CI pipeline npm ci spots the mismatch and fails.

I see the option --update-lock-files but also note that it is true by default. Setting it on CLI --update-lock-files=true makes no difference to the behaviour I'm seeing

I've also tried the rebase label / tag, without success.

My apologies if I have simply misunderstood the config, your documentation "Should you Pin your Javascript Dependencies?" has been very useful to me, thank you.

**Comment by viceice** [comment]
You have a custom environment variable in one of your npmrc files, so you need to configure `trustLevel` to high, so renovate will pass it to the child process. Better solution is if you use the renovate docker image

**Comment by DevRCRun** [comment]
Thanks very much for the quick reply. I can confirm the same configuration indeed works without issue from the docker image. 

I have also tried --trustLevel=high but it did not seem to resolve the issue. 

The .npmrc in my user profile has https-proxy, prefix, cache and python values set.  The npm directory on user variable PATH is set to match prefix (outside the user profile). As we'll almost certainly run renovate on a Microsoft hosted pipelines agent on a linux image / via docker that's not a big deal. I realise node / npm on windows can be downright weird sometimes.

Thanks again

**Comment by DevRCRun** [comment]
I've unfortunately had to come back to this. I've removed the .npmrc file for the user (setting the relevant variables in the environment instead), there is no npmrc file for the project being scanned yet I'm still running into the error. 

There is of course "C:\Program Files\nodejs\node_modules\npm\npmrc" containing "prefix=${APPDATA}\npm" but I take it that's a default on windows and shouldn't be a problem?

Is there a way I can see which npmrc file is causing the issue?
