### ISSUE TITLE
Upgrade multiple versions present in a Docker tag

### ISSUE THREAD

**Issue by fullstackzach** [renovatebot/config-help#709]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

Hello!

Our organization's docker base image tags have multiple versions in them, e.g.
```
FROM <registry>/nodejs12:v12.17.0-alpine3.11@sha256:123456
```
In this example the first version `v12.17.0` is the version of Node included in the image. `3.11` is the version of the alpine OS included. Renovate will upgrade the first node version, for example to `v12.17.1`, but will not upgrade `3.11`  to `3.12`. 

I'm interested in having renovate upgrade both the OS and Node versions in the tag.

I read a little about changing the versioning scheme to 'loose' or to use a regex version manager, but I'm not certain how to configure that, or if thats what could solve for this case

**Comment by rarkins** [comment]
Would it be enough if Renovate doesn't *understand* what the parts mean, but can simply *sort* tags correctly?

**Comment by fullstackzach** [comment]
Yes! I think so.. I think sorting by the 3.11 version first and then the v12.17.0 one second makes sense

**Comment by rarkins** [comment]
That's a tough ask (reversing the order of significance of the pieces in the version)

**Comment by fullstackzach** [comment]
Got it.. I certainly understand thats an edge case and out of the norm. I don't think switching the order is an important requirement.  Multiple alpine images are published (3.10, 3.11, 3.12) with the same node version anyways, so if node v12.18.0 gets added, all of the alpine tags get published with that node version.

I think sorting by the first one (v12.17.0) then the second one (3.11) will work ok.

**Comment by rarkins** [comment]
We'll need to evaluate if the current `loose` versioning is loose enough!

**Comment by rarkins** [comment]
I had another idea on this. First of all, use `regex` versioning for the node part. i.e. `12.17.0` is the version, while `alpine3.11` is the "compatibility" part. This will mean the `dockerfile` manager will update to e.g. `v12.18.0-alpine3.11`.

Next, add a regex manager for updating the `3.11` part to `3.12`. You might need to use the `v12.17.0` part as "compatibility" there though, e.g. it updates to `v12.17.0-alpine3.12` first.

**Comment by fullstackzach** [comment]
Thanks Rhys! I will give the regex option a try. I tested with loose versioning with no luck. Renovate picked up a different linux distribution the registry offers, e.g. v12.17.0-rhel

**Comment by rarkins** [comment]
In fact regular Docker versioning *might* work, e.g. how it works for `-alpine` etc on Docker Hub. I'm not sure if the `v` throws any spanner in the works though. However the example regex versioning from our docs should be applicable if not.
