### ISSUE TITLE
[Q] Do we need GITHUB_TOKEN to get release notes when using with GitLab

### ISSUE THREAD

**Issue by swashata** [renovatebot/config-help#71]
Hi,

So I am using self-hosted Gitlab with self-hosted renovateapp. From the very beginning, I noticed there wasn't any release notes added to the MRs create by renovateapp.

Then just out of curiosity, I added a `GITHUB_TOKEN` and now the newly created MRs do have release notes.

So is this mandatory? If so, I would like to help in writing documentation. Is there any place for that?

**Comment by rarkins** [comment]
It wasn’t intended to be mandatory but we maybe did that accidentally when we refactored credentials handling a month ago. It has always been strongly recommended to have a GitHub token though, otherwise you hit GitHub’s rate limit for unauthenticated requests very quickly. It’s definitely a good idea if we can have a page for or including GitLab self hosting and include mention of the token.

**Comment by swashata** [comment]
Thanks. Just writing down the bare skeleton of the doc.

1. Create a user in your GitLab instance. Give it `developer` permission to repos you want to activate renovateapp. Also create a personal access token and keep it handy.

2. Create a `renovate-config.js` file in any directory. I have placed under `~` home.

```js
module.exports = {
  endpoint: "https://self-hosted.gitlab/api/v4/",
  token: "**gitlab_token**",
  platform: "gitlab",
  logFileLevel: "warn",
  logLevel: "info",
  logFile: "/home/user/renovate.log",
  onboarding: true,
  onboardingConfig: {
    extends: ["config:base"]
  },
  repositories: [
    "username/repo",
    "orgname/repo"
  ],
};
```

Here change the `logFile` and `repositories` to something appropriate. Also replate `gitlab-token` with the one created during step 1.

3. Now when running renovate, we need to tell it about the config file. We can do it through `RENOVATE_CONFIG_FILE` env variable. Since we will use cron, it is better to create a executable bash script. I have something like this

```bash
#!/bin/bash

export PATH="/home/user/.yarn/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
export RENOVATE_CONFIG_FILE="/home/user/renovate-config.js"
export GITHUB_TOKEN="**github-token**"

# Renovate
renovate
```

We need `GITHUB_TOKEN` for release notes to work properly. Let's place it under our home directory (note that sudo is not needed, neither would I recommend it).

a. `cd ~`.
b. `nano run-renovate.sh`
c. Paste the script above.
d. Save and give executable permission `chmod +x ./run-renovate.sh`.

To test things out, execute the command and see the results. `~/run-renovate.sh`.

4. Create a crontab for executing automatically.

```bash
crontab -e
```

and put the following (change the path to the executable script).

```bash
59 23 * * * /home/user/run-renovate.sh
```
