### ISSUE TITLE
How to configure renovate to ignore pinned dependencies

### ISSUE THREAD

**Issue by cambiph** [renovatebot/config-help#710]
### Which Renovate are you using?

Renovate Open Source CLI:
21.12.3 (Docker)

### Which platform are you using?

Self-hosted via renovate Docker app. Repositories to be processed are on Github.

### What would you like to do?

Current config:
```
module.exports = {
    "autodiscover": true,
    "autodiscoverFilter": "milieuinfo/webcomponent+(-vl-ui*|en-vl*)",
    "enabledManagers": ["npm"],
    "labels": ["dependencies", "renovate", "chore"],
    "masterIssue": true,
    "masterIssueAutoclose": true,
    "onboarding": false,
    "packageRules": [
        {
            "updateTypes": ["minor", "patch"],
            "automerge": true,
            "requiredStatusChecks": null
        }
    ],
    "rangeStrategy": "replace"
};
```

I want to achieve that only dependencies starting with a ^ are getting processed by renovate. This is because we pin dependencies to a specific version when we have problems with newer versions. As I understood from the renovate documentation, setting `rangeStrategy` to replcae would facilitate this, but it seems that I was wrong because renovate just upgraded `terser: 4.0.0` to `terser: 4.8.0`

Thanks in advance.
Regards

**Comment by rarkins** [comment]
Unfortunately I don't think we have a capability for this currently

**Comment by cambiph** [comment]
Ok, I will have to figure out something outside of renovate then, thx!

**Comment by viceice** [comment]
@cambiph Your only option is to add a package rule which disables the specific packages
