### ISSUE TITLE
In a monorepo: Opening 1 PR per service or per owner instead of one per dependency

### ISSUE THREAD

**Issue by christophe-dufour** [renovatebot/config-help#713]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub.com

### What would you like to do?

Hey guys,

We are working on a mono-repo where the structure looks like that:
```
src/services/
                group-1/
                       service-A/
                              go.mod
                       service-B/
                              go.mod
                       service-C/
                              go.mod
                group-2/
                       service-D/
                              go.mod
                       service-E/
                              go.mod
                       service-F/
                              go.mod

etc....
```

I would like for renovate to group PRs per services (one per `go.mod`) or per `group`(one per folder)
But I fail to find any configuration option allowing me to do that.
For, renovate open a PR for the whole mono-repo and that require some sync to make those PRs merged

**Comment by rarkins** [comment]
This is achievable using `packageRules` and `parentDir`. Hopefully at least one of these past issues here can be useful to getting you started: https://github.com/renovatebot/config-help/issues?q=is%3Aissue+parentDir+is%3Aclosed+

**Comment by christophe-dufour** [comment]
Hey @rarkins 

It works. Thx a lot

I'm sharing my configuration if it can help others later.

```
{
  "enabledManagers": ["gomod"],
  "semanticCommits": true,
  "semanticCommitType": "chore",
  "semanticCommitScope": "{{parentDir}}",
  "branchPrefix": "renovate/{{parentDir}}-",
  "commitMessagePrefix": "[{{parentDir}}]",
  "prHourlyLimit": 10,
  "prConcurrentLimit": 30,
  "packageRules": [
    {
      "paths": ["src/services/group-1"],
      "semanticCommits": false,
      "commitMessagePrefix": "[Solution domain]",
      "semanticCommitScope": "deps",
      "branchPrefix": "renovate/"
    }
  ]
}
```
