### ISSUE TITLE
renovate Config file Update

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#714]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

I would like to update the renovate config file programatically. Once I provoide repo name as insput, the new repo name should add with the existing repo names in config file. But when I parse the yaml file using yq I see yaml file has module. exports which is not able to update using yq. Is there a way to update ? or can we have a configuration file in different format? Could you please help on this?

kind: ConfigMap
apiVersion: v1
metadata:
  name: js-configmap
data:
  config.js: |
    module.exports = {
      platform: 'github',
      endpoint: 'https://github.com/api/v3',
      logLevel: 'debug',
      includeForks: true,
      repositories: ['sakshan/repo1']
     };

**Comment by rarkins** [comment]
You can use a `config.json` file instead of `config.js`.

**Comment by sakshan** [comment]
Could you plese share a sample for that?

**Comment by rarkins** [comment]
{}

**Comment by sakshan** [comment]
Can you check below one is correct configuration?


kind: ConfigMap
apiVersion: v1
metadata:
name: js-configmap
data:
config.json: 
{
platform: 'github',
endpoint: 'https://github.com/api/v3',
logLevel: 'debug',
includeForks: true,
repositories: ['sakshan/repo1']
}

**Comment by rarkins** [comment]
That’s not valid JSON. Use jsonlint.com

**Comment by sakshan** [comment]
Updated Json. Do I need to keep module.exports? 

kind: ConfigMap
apiVersion: v1
metadata:
name: js-configmap
data:
config.json:
{
"platform": "github",
"endpoint": "https://github.com/api/v3",
"logLevel": "debug",
"includeForks": true,
"repositories": "['sakshan/repo1']"
}

**Comment by rarkins** [comment]
Module.exports is for JS. Not needed for JSON

**Comment by sakshan** [comment]
I tried to apply below yaml

kind: ConfigMap
apiVersion: v1
metadata:
  name: json-configmap
data:
  config.json: 
     {
      "platform": "github",
      "endpoint": "https://github.com/api/v3",
      "logLevel": "debug",
      "includeForks": true,
      "repositories": ['sss/sdfsdf']
      }


I am getting error 

 renovatejson-configmap.yaml 
for: "renovatejson-configmap.yaml": unrecognized type: string


Could you please help me out here ?

**Comment by rarkins** [comment]
Please try to ask a Kubernetes expert on your team. It’s not a Renovate error
