### ISSUE TITLE
Automerge minor and patch doesn't seem to be auto merging

### ISSUE THREAD

**Issue by MeStrak** [renovatebot/config-help#715]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

I checked the logs and can see that some things are auto merging, but there are still many minor updates which aren't autmerged.

### What would you like to do?

I've setup renovate and renovate-approve on my repo: https://github.com/Sanofi-IADC/whispr.

Auto merging is configured for minor updates, patches, etc. but doesn't seem to be working in all cases. They have been auto approved, but then the auto merge wasn't done.

I can see in the logs that some automerges have worked, but not alll.

I've previously used the same configuration file on another project and it worked. Am I missing something in the expected behaviour?

Thanks!

**Comment by MeStrak** [comment]
Actually I think that this might be because I have a GitHub action which isn't running, and the merge is probably failing because of that. I'm checking that now.

**Comment by MeStrak** [comment]
Ok so it wasn't related to the Github actions thing, we still have this issue.

**Comment by rarkins** [comment]
The debug logs contain information on whether GitHub's API is returning "blocked" or if certain status checks are still pending. Pick one particular branch that's showing as enabled for automerge and is auto-approved and search the logs for it.

**Comment by MeStrak** [comment]
Thanks, I think it was just some of them were stuck due the the GitHub actions issue. All sorted now.
