### ISSUE TITLE
"rebaseWhen" not working with "branch"?

### ISSUE THREAD

**Issue by j0nm1** [renovatebot/config-help#717]
### Which Renovate are you using?

Renovate Docker (`renovate/renovate:21.6.3`)

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

` DEBUG: Branch is stale and needs rebasing (repository=<REMOVED>, branch=fix/renovate/com.vladmihalcea-hibernate-types-52-2.x)`

### What would you like to do?

I tried to setup the repo with the following config:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "automerge": true,
  "automergeType": "branch",
  "semanticCommitScope": "deps",
  "semanticCommitType": "chore",
  "semanticCommits": true,
  "ignorePaths": [
    "src/client/package.json",
    "src/client/package-lock.json"
  ],
  "branchPrefix": "fix/renovate/",
  "rebaseWhen": "conflicted"
}
```
The problem is that renovate does not seem to respect the `"rebaseWhen"` setting. It rebases all branches when one dependency is updated, although it only should rebase when there is a conflict. Am I missing something or is `"rebaseWhen"` unsupported in combination with `"automergeType": "branch"`?

**Comment by rarkins** [comment]
When branch automerging is enabled, Renovate ensures that branches are up-to-date with the base branch, so it takes precedence over rebaseWhen.

**Comment by j0nm1** [comment]
Thanks for the clarification!
