### ISSUE TITLE
Renovate stopped working

### ISSUE THREAD

**Issue by jmeiss** [renovatebot/config-help#72]
HI,

Everything was working properly until few days/weeks ago. One day I just noticed that we stoped receiving PR from renovatebot.

I tried to uninstall/reinstall.
I tried to remove the `renovate.json` file.
I tried to rename the `Configure Renovate` PR.

But nothing changed. There's still no new PR.

I had a look at https://renovatebot.com/dashboard where I can see the 2 repos and I can even see several jobs that ran few minutes or few hours ago for some of them but when I click on the job ID to look at the jobs, the XHR returns a 404 error with that response: `{"message":"log file not found"}`

I could copy/paste our `renovate.json` file but it was the one created with the `Configure Renovate` PR and even when I delete it, there's no new PR.

Does anybody have an idea on how we could fix this?

**Comment by rarkins** [comment]
@jmeiss are these on your personal account or an org?

**Comment by jmeiss** [comment]
It's on an organisation account and I subscribed to your Organisation plan

**Comment by rarkins** [comment]
I can’t see you as a public member of any org so can you let me know which one it is, or email support@renovatebot.com if it’s confidential?

**Comment by jmeiss** [comment]
@rarkins it's on the Fluicity organisation and I was mainly trying to fix it on the fluicity-mobile repo but we have the same issue with the fluicity-backend repo

**Comment by rarkins** [comment]
@jmeiss according to GitHub’s API, the fluicity account actually has a “Personal Plan” subscribed, so it’s not showing up as enabled for the private org repositories. GitHub only fixed the UI error that enabled mixed up personal/org plans a week ago, to prevent mistakes. 

An email was sent to the billing address for the fluicity Org but it looks like that’s some type of automated/unattended address so maybe no human saw it yet. The org owner will need to go to https://github.com/marketplace/renovate to switch to an Org plan and it should enable automatically within an hour after that. Please feel free to email if any problems!

**Comment by jmeiss** [comment]
@rarkins you are right, the billing address is related to the software we use for our accountability which is the reason why I never received this email. Thx for the information, I will have to optimise that.

I thought I switched to an Org plan several times since when I try to apply for an Org plan, I'm getting an alert `You already have Renovate installed.`. When I install it again (after making sure that the billing account is Fluicity and not my personal account), there's no way for me to check which plan I subscribed to :/

**Comment by jmeiss** [comment]
I just added myself as a `Billing Manager` and I just received this email:

```
This email is to inform you that we’ve received the following error trying to bill your credit card:

Declined

Your marketplace subscriptions have been reverted to their previous state.
```

Now it makes sense why it wasn't working! So the problem is not coming from Renovate but from Spendesk who declines the payment.

Sorry for the noise and thanks a lot for your help!!

**Comment by rarkins** [comment]
No problem! Good to know all the different ways it can go wrong for next time..

**Comment by jmeiss** [comment]
I've updated the payment method and the payment has been successful. Do you think you can have a look to make sure everything well setup? Since I haven't received any PR yet, even after renaming the `Configure Renovate` PR.

**Comment by rarkins** [comment]
Sure, I can check a little later once I’m back to a keyboard. It *should* get picked up in the complete refresh we do server side once per hour

**Comment by jmeiss** [comment]
Awesome! I hope to be the one telling you that it works again :)

**Comment by jmeiss** [comment]
It works again! Thanks a lot for your help @rarkins !

**Comment by rarkins** [comment]
Awesome. Thanks for being a customer!
