### ISSUE TITLE
Creating a Jira ticket for each MR

### ISSUE THREAD

**Issue by rdicroce** [renovatebot/config-help#720]
### Which Renovate are you using?

None yet. I'm still trying to map out how Renovate would fit into our workflow. If we adopt Renovate, we'd be using the open-source, self-hosted version.

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

My team is using GitLab for SCM and code reviews, but issues are tracked in Jira. So when Renovate generates a MR, I'd like to simultaneously open a Jira ticket and reference the ticket ID in the commit message. We're working on integrating GitLab with Jira so we can use Jira smart commits, and that would allow us to also automatically update the Jira ticket when the MR is merged.

Judging from https://github.com/renovatebot/renovate/issues/3796, it looks like Renovate does not support Jira at all right now, and even if that issue were implemented, it would only apply to the BitBucket platform. My next thought was to use postUpgradeTasks to execute a custom script to create the ticket, but I don't know how I'd propagate the ticket ID into the commitBody template.

So, do you have any ideas for how to accomplish this?

**Comment by rarkins** [comment]
A ticket per MR is not something we have planned, and I think you'd get tired of all the noise. Some people have a long-running Jira issue that they then populate in the PR body as it's quite easy to add custom information.

**Comment by rdicroce** [comment]
Ultimately our plan is to generate release notes from Jira. A "master ticket" approach doesn't really work with that. There would just be a ticket in every release that says "Dependency upgrades" which isn't very helpful. I want the release notes to specifically say what was upgraded. A ticket per MR is also useful for QA to know exactly what's in the latest build, and for linking other tickets in the event that a dependency upgrade creates a bug. And I don't think noise would be that much of a problem - it's not going to be any noisier than the MRs themselves, and we'd probably run Renovate once a week or so.

**Comment by rarkins** [comment]
You're welcome to raise a feature request in the main Renovate repo, but you might find it challenging to make it complete enough without a working knowledge of how Renovate actually works. You'd need to think about things like how/when tickets are created, how/when they are closed, and of course an answer for edge cases and any race conditions that night come up.
