### ISSUE TITLE
go updater fails with unknown revision

### ISSUE THREAD

**Issue by novas0x2a** [renovatebot/config-help#721]
**What Renovate type are you using?**

Self-hosted, renovate/pro:0.18.5

**Describe the bug**

All Go updates to my repo (not just ones related to the sops module) with:

> Artifact update problem
```
Command failed: go get -d ./...
go: finding go.mozilla.org/sops/v3 v3.5.0
go: go.mozilla.org/sops/v3@v3.5.0: unknown revision go.mozilla.org/sops/v3.5.0
go: error loading module requirements
```

**Did you see anything helpful in debug logs?**

It looks like everything helpful in the debug logs ended up in the message above.

**To Reproduce**

This is a private repo. However, I suspect that any repo that depends on sops will have the same problem. (go get does not have this problem, so this is likely a behavior difference between renovate and go upstream). I can't expose a public repo for this due to org restrictions, but I'm guessing that this go.mod will reproduce the problem:

```
module mycoolmodule

go 1.14

require (
	go.mozilla.org/sops/v3 v3.5.0
)
```

**Additional context**

sops has a meta redirect (go.mozilla.org/sops/v3 -> https://github.com/mozilla/sops) and I'm guessing renovate doesn't follow that correctly.

**Comment by rarkins** [comment]
Please see https://github.com/whitesource/renovate-on-prem

```
❯ docker run --rm whitesource/renovate go version
go version go1.14.4 linux/amd64
```
