### ISSUE TITLE
Questions about rebasing open PRs

### ISSUE THREAD

**Issue by hisener** [renovatebot/config-help#722]
### Which Renovate are you using?

Renovate Open Source CLI (using the docker image `renovate/renovate:21.13.3-slim`)

### Which platform are you using?

GitHub.com (without GitHub App)

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

I am using self-hosted renovate. I have some questions about rebasing strategies:

1. Is it possible to run renovate to just rebase open upgrades without creating new PRs? I have checked `prConcurrentLimit` but its default value is 0, IIUC it's not an option.
2. Is it possible to rebase one specific upgrade PR?

Thanks in advance.

**Comment by rarkins** [comment]
FYI although our options are named `prConcurrentLimit` and `prHourlyLimit`, we actually check these limits at *branch* creation, not PR creation.

If limits are reached, or all PRs are unscheduled, then you should not see any new *branches* created, but you may see PRs created if the branch already existed and e.g. status checks passed. You will see any existing PRs rebased as necessary even if limits are reached or schedules are not met.

> 2. Is it possible to rebase one specific upgrade PR?

Can you tick the rebase/retry checkbox?

**Comment by hisener** [comment]
> FYI although our options are named prConcurrentLimit and prHourlyLimit, we actually check these limits at branch creation, not PR creation.

> If limits are reached, or all PRs are unscheduled, then you should not see any new branches created, but you may see PRs created if the branch already existed and e.g. status checks passed. You will see any existing PRs rebased as necessary even if limits are reached or schedules are not met.

Check. So it is not possible to run renovate in a "rebase-only" mode? But I wonder how GitHub app handles that case. 🤔 

> Can you tick the rebase/retry checkbox?

I use the self-hosted renovate and that checkbox doesn't do anything. Well, it is expected because we don't interact with the GitHub app.

**Comment by rarkins** [comment]
The checkbox won't *trigger* a run if you use the CLI but it *will* be considered the next time Renovate runs.

**Comment by hisener** [comment]
Good one. So if I create Renovate run by listening GitHub pull_request edit webhook, then it will rebase the branch. But it might still create extra PRs, right?

**Comment by rarkins** [comment]
Yes, it will do a "usual" repo run. You could apply an artificial schedule perhaps, to try to avoid that. BTW https://github.com/whitesource/renovate-on-prem should work fine on github.com and supports webhook listening already. It doesn't do *rebase only* runs though (none of the Renovate offerings do however)

**Comment by hisener** [comment]
What do you mean by "artificial schedule"? Can you elaborate?

**Comment by rarkins** [comment]
I mean force override a schedule from the bot side to deliberately stop any PR creation that run

**Comment by hisener** [comment]
Thanks, will try.
