### ISSUE TITLE
Renovate restarts from begining if any error

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#723]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

We have renovate configured with kubarnetes file. If renovate finds error in any of the repo it skips to next repo which is good but at the end its starting from first since there is an error in some repo. Please advice how to stop this.

**Comment by rarkins** [comment]
Renovate doesn't restart itself - you must be restarting it via your kubernetes somehow. Make sure restart=false
