### ISSUE TITLE
lots of opened and closed PRs on python project 

### ISSUE THREAD

**Issue by djmitche** [renovatebot/config-help#724]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

As of yesterday, renovate seems to be confused about taskcluster/tc-admin -- it suddenly opened a bunch of PRs, then autoclosed them, and is now opening them again.  For example, for certifi -- https://github.com/taskcluster/tc-admin/pulls?q=is%3Apr+author%3Arenovate-bot++certifi

It looks like this is due to the landing of the new `requirements.txt` support, but I am not sure (a) why it's upgrading to multiple versions and (b) why it's autoclosing those.

**Comment by rarkins** [comment]
I was able to get enough logs to work out what went wrong:

1. We released a new feature that supports "hashed" requirements.txt files
2. Your repo saw new PRs created as a result
3. Somehow, a worker instance running an *older* version of Renovate processed your repo, had no capability to parse hashed requirements files, so the new PRs all got autoclosed
4. For subsequent runs, a new instance ran and recreated the PRs

I've checked the particular instance that ran the older version and it was already up to date without any manual intervention. I'm not sure what cause it to be slow updating, so sorry for the noise.
