### ISSUE TITLE
Registry error

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#729]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

We have configured multiple repos in renovate. For one of the repo we are not seeing any PR's so I digged in to logs. I found below message

 WARN: Datasource failure (repository=reponame)
 INFO: Registry error - skipping (repository=reponame)
 INFO: Repository finished (repository=reponame)

**Comment by rarkins** [comment]
Debug logs

**Comment by sakshan** [comment]
Here is the debug logs

 "datasource": "gradle-version",
       "lookupName": "gradle",
       "err": {
         "name": "RequestError",
         "code": "ETIMEDOUT",
         "host": "services.gradle.org",
         "hostname": "services.gradle.org",
         "method": "GET",
         "path": "/versions/all",
         "protocol": "https:",
         "url": "https://services.gradle.org/versions/all ",
         "gotOptions": {
           "path": "/versions/all",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "services.gradle.org",
           "port": null,
           "hostname": "services.gradle.org",
           "hash": null,
           "search": null,
           "query": null,
           "pathname": "/versions/all",
           "href": "https://services.gradle.org/versions/all ",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate ",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [null],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "hostType": "gradle-version",
           "gotTimeout": {"request": 60000}
         },
         "message": "connect ETIMEDOUT 104.18.191.9:443",
         "stack": "RequestError: connect ETIMEDOUT 104.18.191.9:443\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:417:26)\n    at ClientRequest.emit (events.js:322:22)\n    at ClientRequest.EventEmitter.emit (domain.js:482:12)\n    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:310:20)\n    at TLSSocket.EventEmitter.emit (domain.js:482:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"

**Comment by viceice** [comment]
Look at the logs, it's not a renovate issue.

**Comment by sakshan** [comment]
I thinl renovate is throwing time out error

**Comment by viceice** [comment]
60secs timeout is not enough for you? Configure it, read the docs.

**Comment by sakshan** [comment]
@viceice 

Incresed the time out. I am still seeing the same error. Please advice.

**Comment by rarkins** [comment]
Look up with ETIMEDOUT means. Something is blocking Renovate from accessing https://services.gradle.org/versions/all. It's not Renovate's problem

**Comment by sakshan** [comment]
@rarkins 

Changed gradle version to gradle-5.4.zip, its working as expected. But its not working with  gradle-5.6.1-bin.zip.
