### ISSUE TITLE
Docker renovate tmp directory bug

### ISSUE THREAD

**Issue by adalgrim** [renovatebot/config-help#731]
**Describe the bug**

Latest (Digest: sha256:d0275544af2af73c61bcabf936ec3bf8bf61c560b525ad24c37f288a5262b46c) version of Docker Renovate is not working with default base dir option.

**Did you see anything helpful in debug logs?**

`FATAL: Fatal error: ENOENT: no such file or directory, mkdir '/tmp/renovate'
       "err": {
         "errno": -2,
         "code": "ENOENT",
         "syscall": "mkdir",
         "path": "/tmp/renovate",
         "message": "ENOENT: no such file or directory, mkdir '/tmp/renovate'",
         "stack": "Error: ENOENT: no such file or directory, mkdir '/tmp/renovate'"
       }
`

**Comment by adalgrim** [comment]
I found the problem. It isn't directly related to renovate but maybe this will help somebody.

It seems that there is a problem with Docker for Mac 2.3.0.3 and osxfs. Downgrade to 2.2.0.5 solved the problem.

**Comment by rarkins** [comment]
FWIW I ran under Docker for Mac 2.3.0.3 too
