### ISSUE TITLE
Suppress artifact error bitbucket build status

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/config-help#732]
### Which Renovate are you using?

Other (please write below)
Renovate Open Source CLI via npm install

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

Yes

### What would you like to do?

In bitbucket server after the 21 release we now get a artifacts error due to lerna not being installed (makes sense, I saw the release notes). We generally have CI for all of these repositories so instead of renovate checking for lerna, just having the CI be green should be enough to know the PR is good to merge. However, after adding `"suppressNotifications": ["artifactErrors"],` to my renovate config, I'm still getting a bitbucket build status failure
![Screen Shot 2020-07-02 at 12 18 19 PM](https://user-images.githubusercontent.com/3490825/86401115-90c50480-bc5e-11ea-90d2-935b666cb489.png)

My basic question is how to do I suppress this bitbucket status failure from being added by renovate?

**Comment by viceice** [comment]
This is because you can't suppress  a fatal error in renovate. If you would merge the PR it will fail your main branch because the lockfile don't match the expected versions in your package.json

**Comment by k2snowman69** [comment]
sounds good, installing Lerna as a dependency on my renovate runner! Thanks!

**Comment by viceice** [comment]
You can alternatively use our recommended docker mode, them Lena wold be automatically installed as required.
