### ISSUE TITLE
Trying to encrypt npmrc which is too long according to https://app.renovatebot.com/encrypt

### ISSUE THREAD

**Issue by paazmaya** [renovatebot/config-help#737]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

No access to them

### What would you like to do?

Increase the maximum input size for the encryption tool.

The `npmrc` in question looks something like this, the tokens are not included:

```
@finnair:registry=https://nexus.development.tool.clouds.finnair.com/nexus/repository/npm/
@fcom:registry=https://nexus.development.tool.clouds.finnair.com/nexus/repository/npm/
@finnairoyj:registry=https://npm.pkg.github.com
always-auth=true
//npm.pkg.github.com/:_authToken=......
//nexus.development.tool.clouds.finnair.com/nexus/repository/npm/:_auth=.....
email=needs-to-be-included-here@finnair.com
```

**Comment by rarkins** [comment]
Unfortunately this may be a use case we don't have a solution for just yet. Normally you could configure just an encrypted `npmToken` with an unencrypted `npmrc` however I notice that you have two tokens, so a single token wouldn't work.

**Comment by viceice** [comment]
for the `_authToken` lines he can use `hostRules`

```json
{
  "hostType": "npm",
  "baseUrl": "npm.pkg.github.com",
  "enrcypted": { "token": "...." }
}

**Comment by rarkins** [comment]
I note there's both `_authToken=` and `_auth` usage there and I think we support `_authToken` only right now

**Comment by viceice** [comment]
Nope, for the auth part (if only one of them) he can use the encryped [`npmToken`](https://docs.renovatebot.com/private-modules/#add-an-encrypted-npm-token-to-renovate-config).

```json
{
  "encrypted": {
    "npmToken": ..."
  },
  "npmrc": "@finnair:registry=https://nexus.development.tool.clouds.finnair.com/nexus/repository/npm/\n//nexus.development.tool.clouds.finnair.com/nexus/repository/npm:_auth=${NPM_TOKEN}"
}
```
⬆️ need to add all registries

**Comment by paazmaya** [comment]
Thank you for the help, I got the authentication with several registries sorted out!
Little did I realise how powerful could https://docs.renovatebot.com/configuration-options/#hostrules be...
