### ISSUE TITLE
Renovate automerge not working properly

### ISSUE THREAD

**Issue by MatsAnd** [renovatebot/config-help#742]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I want patches, pins and digests to be automerged, as well as devDependencies, peerDependencies and optionalDependencies, but I can't get it to automerge as I have configured.

[Example PR](https://github.com/vtfk/configs/pull/4):

![image](https://user-images.githubusercontent.com/13292913/86614463-57203080-bfb3-11ea-9535-89d8eb3b324d.png)

My current configuration:
```json
"renovate-config": {
    "default": {
      "extends": [
        "config:base"
      ],
      "separateMultipleMajor": true,
      "separateMinorPatch": true,
      "ignoreUnstable": true,
      "timezone": "Europe/Oslo",
      "assigneesFromCodeOwners": true,
      "assigneesSampleSize": 1,
      "labels": ["dependencies"],
      "vulnerabilityAlerts": {
        "labels": ["security"]
      },
      "commitBody": "Dependency update (patch)",
      "packageRules": [
        {
          "updateTypes": ["patch", "pin", "digest"],
          "automerge": true
        },
        {
          "depTypeList": ["devDependencies", "peerDependencies", "optionalDependencies"],
          "automerge": true
        }
      ]
    }
  }
```

### Have you checked the logs? Don't forget to include them if relevant
[Relevant logs](https://app.renovatebot.com/dashboard#github/vtfk/configs/199265574):

```
DEBUG: Checking if we can automerge branch(branch="renovate/pin-dependencies")
DEBUG: mergeStatus=no automerge(branch="renovate/pin-dependencies")
```

```
DEBUG: Checking #4 for automerge(branch="renovate/pin-dependencies")
  {
    "automerge": true,
    "automergeType": "pr",
    "automergeComment": "automergeComment"
  }
DEBUG: PR is configured for automerge(branch="renovate/pin-dependencies")
DEBUG: PR is not ready for merge(branch="renovate/pin-dependencies")
  {
    "canMergeReason": "mergeStateStatus = UNKNOWN"
  }
```

**Comment by rarkins** [comment]
GitHub is returning mergeStateStatus=UNKNOWN for the PR, meaning it can't be merged. How many times/logs in a row have you observed this happening?

Ref: https://developer.github.com/v4/enum/mergestatestatus/

**Comment by MatsAnd** [comment]
A couple of times - please take a look at our the logs [here](https://app.renovatebot.com/dashboard#github/vtfk/configs). I have a couple of other repos with the same "UNKNOWN" status as well.

In the latest log, it now says "state: pending" and "PR is not ready for merge (branch status is yellow)", but [the PR](https://github.com/vtfk/configs/pull/4) is actually green and ready to merge..

**Comment by rarkins** [comment]
List which exact job IDs and which exact message in each you wish to point out. Renovate logs which status checks are pending - you should look for that too.

Please also understand that the status checks may be yellow at the time Renovate runs and then turn green before you look at them.

**Comment by rarkins** [comment]
Also, narrow it down to one repository at a time.

**Comment by MatsAnd** [comment]
Ok, to narrow it down, take a look at this log: [vtfk/azf-svarut/199317167](https://app.renovatebot.com/dashboard#github/vtfk/azf-svarut/199317167) (Linked to this [PR](https://github.com/vtfk/azf-svarut/pull/7#issue-444914233))

**Comment by rarkins** [comment]
Do you have any tests?

![image](https://user-images.githubusercontent.com/6311784/86627420-986f0b00-bfc8-11ea-99eb-1d8104b56b08.png)

The above just means there's no conflicts - it doesn't mean there are any passing tests. If you want to automerge without tests (usually not a good idea, because you don't know if the update has completely broken things) then set `requiredStatusChecks=null` in your `renovate.json` (ref: https://docs.renovatebot.com/configuration-options/#requiredstatuschecks)

**Comment by MatsAnd** [comment]
No, there is currently no tests in these repo's, I'l try add that setting and see if that helps! 👍

**Comment by MatsAnd** [comment]
One question tho - why isn't "no tests" the same as "all tests passed"?

**Comment by rarkins** [comment]
Because there's no way to know the difference between:
- Repository has no tests
- Repository has tests but they haven't started yet
- Repository has tests but the webhook was lost in a GitHub outage so they'll never run

Also, it's usually a bad idea to be upgrading dependencies without testing them, so we won't prioritize ease of use for that case and sacrifice reliability for the other two cases.
