### ISSUE TITLE
autoMerge field || whole config is not being used by renovate in private repo in Github Enterprise project

### ISSUE THREAD

**Issue by varora1406** [renovatebot/config-help#744]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

```
...............
DEBUG: findFile(renovate.json)
DEBUG: config file exists
DEBUG: ensureIssueClosing(Action required: Add a Renovate config)
......................
...........................
DEBUG: Checking if we can automerge branch(branch="renovate/tslib-2.x")
DEBUG: mergeStatus=no automerge(branch="renovate/tslib-2.x")
DEBUG: Ensuring PR(branch="renovate/tslib-2.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/tslib-2.x")
......................
.............................
DEBUG: Created Pull Request #45(branch="renovate/tslib-2.x")
DEBUG: Checking #45 for automerge(branch="renovate/tslib-2.x")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/tslib-2.x")
```
### What would you like to do?
My config file has below code
```
{
"packageRules": [
    {
      "updateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    }
  ]
}
```
I have tried with `./.github/renovate.json` and `.renovaterc.json`, both files indviually.
I am sure this is bug with renovate.

My project is private project, in Github Enterprise Organization

**Comment by rarkins** [comment]
Please reproduce in a public repo and I'll take a look. i.e. use same/similar config and some basic config that reproduces the non-automerge problem.

**Comment by varora1406** [comment]
https://github.com/varora1406/ecmascript-library-template is available to get checked

**Comment by varora1406** [comment]
I checked again, and it's working fine in public repo.
but not working fine at private repo.

can you check below config in a private repo at your end?
```
{
  "packageRules": [
    {
      "updateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    }
   ]
}
```

**Comment by varora1406** [comment]
I think I got it, it's working fine now.
But for the record, for some days this was not working fine in public repository as well
