### ISSUE TITLE
How to ignore update of group:storybookMonorepo ?

### ISSUE THREAD

**Issue by hanocha** [renovatebot/config-help#75]
Hi.

We want to ignore update of `monorepo:storybook`, but we can't find how to config it on the document.
How to configure to ignore update of monorepo?

**Comment by rarkins** [comment]
You want to disable automatic updates of all storybook packages forever?

**Comment by hanocha** [comment]
@rarkins Thank you for your rapid response!
No, I don't. I want to disable automatic update temporarily, to wait next stable release of storybook.

**Comment by hanocha** [comment]
Oh, I see. 🤔 
So now we are using storybook `4.0.0-alpha.14`, so we receive new PR with `alpha` versions, right?

And I'd like to confirm that, if we want to pin the version of storybook with `4.0.0-alpha.14`, can we use configure like that?

```
"packageRules": [
  {
    "packagePatterns": ["^@storybook/"],
    "updateTypes": ["pin"]
  }
]
```
