### ISSUE TITLE
How to setup automerge for self-hosted bitbucket server

### ISSUE THREAD

**Issue by literat** [renovatebot/config-help#750]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

Yes, I have not found ani mention about auto merge.

### What would you like to do?

I would like to setup automerge for patch and minor dependencies which passes the tests. Whole CI setup uses a Jenkins. Renovate CLI is also running using Jenkins as scheduled job.

Whole procces should be something like:
- jenkins runs the renovate cli job
- renovate creates branch and PR for dependencies (happening now)
- jenkins run tests for each branch (happening now)
- renovate automerges the branch when tests are ok

Configuration for Renovate CLI:
```
{
  "extends": [
    ":prConcurrentLimit10"
  ],
  "branchPrefix": "dependencies/",
  "commitMessagePrefix": "Deps: ",
  "enabledManagers": ["npm"],
  "rangeStrategy": "update-lockfile",
  "persistRepoData": true,
  "schedule": ["on monday"],
  "packageRules": [
    {
      "updateTypes": ["minor", "patch"],
      "automerge": true
    }
  ]
}
```

Configuration of repo:
```
{
  "extends": [
    ":prConcurrentLimit10"
  ],
  "branchPrefix": "dependencies/",
  "commitMessagePrefix": "Deps: ",
  "packageRules": [
    {
      "packageNames": [ "node" ],
      "enabled": false
    },
    {
      "packagePatterns": [ "eslint" ],
      "groupName": "eslint"
    },
    {
      "packagePatterns": [ "jest" ],
      "groupName": "jest"
    },
    {
      "packagePatterns": [ "react" ],
      "groupName": "react"
    },
    {
      "packagePatterns": [ "babel" ],
      "groupName": "babel"
    },
    {
      "updateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true,
      "automergeType": "pr"
    }
  ],
  "enabledManagers": ["npm"],
  "rangeStrategy": "update-lockfile",
  "persistRepoData": true,
  "schedule": ["on monday"]
}
```

Any advice how to do it better is welcome. Thank you.

**Comment by viceice** [comment]
Please include `DEBUG` logs

**Comment by rarkins** [comment]
Looks fine to me

**Comment by literat** [comment]
[renovate-debug.log](https://github.com/renovatebot/config-help/files/4918172/renovate-debug.log)

**Comment by viceice** [comment]
@literat You need to configure [`gitAuthor`](https://docs.renovatebot.com/self-hosted-configuration/#gitauthor)

if you run renovate cli on a jenkins job, jenkins will override git author with environment variables, so you need to make sure they match otherwise  renovate will always think the commit is modified by another user and does nothing.

**Comment by viceice** [comment]
```
DEBUG: PR has been edited (repository=fp/fp-admin, branch=dependencies/commitlint-cli-9.x-lockfile)
       "prNo": 348
```

**Comment by viceice** [comment]
https://github.com/renovatebot/config-help/issues/674#issuecomment-636048911

**Comment by literat** [comment]
Great. Thanks for cool advice!

And what about the automerge which is currently not working? The setup you linked in a comment is working and tested solution for automerge?

**Comment by viceice** [comment]
yes, I'm using that setup for dayli work. You need to override the jenkins env and set gitAuthor so they match and automerge will work.

**Comment by literat** [comment]
Ok, thank you very much. :-)

**Comment by literat** [comment]
I have still some problems with automerge and I can't figure out where the problem is. Confused from `"canMergeReason": undefined`.

I have edited gitAuthor and there is no `PR has been edited` in this repo.

```
DEBUG: yarn.lock needs updating (repository=iis/kukad, branch=dependencies/babel)
DEBUG: Updated 1 lock files (repository=iis/kukad, branch=dependencies/babel)
       "updatedArtifacts": ["yarn.lock"]
DEBUG: 1 file(s) to commit (repository=iis/kukad, branch=dependencies/babel)
DEBUG: Committing files to branch dependencies/babel (repository=iis/kukad, branch=dependencies/babel)
 INFO: Branch created (repository=iis/kukad, branch=dependencies/babel)
       "commitHash": "53ef575"
DEBUG: Ensuring PR (repository=iis/kukad, branch=dependencies/babel)
DEBUG: There are 0 errors and 0 warnings (repository=iis/kukad, branch=dependencies/babel)
DEBUG: getBranchPr(dependencies/babel) (repository=iis/kukad, branch=dependencies/babel)
DEBUG: findPr(dependencies/babel, "undefined", "open") (repository=iis/kukad, branch=dependencies/babel)
DEBUG: getPrList() (repository=iis/kukad, branch=dependencies/babel)
DEBUG: returning cached PR list (repository=iis/kukad, branch=dependencies/babel)
DEBUG: DID NOT Found PR from branch #dependencies/babel (repository=iis/kukad, branch=dependencies/babel)
DEBUG: Removing duplicate release notes (repository=iis/kukad, branch=dependencies/babel)
       "depName": "@babel/core"
DEBUG: Removing duplicate release notes (repository=iis/kukad, branch=dependencies/babel)
       "depName": "@babel/register"
DEBUG: getBranchStatus(dependencies/babel, requiredStatusChecks=true) (repository=iis/kukad, branch=dependencies/babel)
DEBUG: branch status check result (repository=iis/kukad, branch=dependencies/babel)
       "commitStatus": {"successful": 0, "inProgress": 0, "failed": 0}
DEBUG: getPrBody(This PR contains the following updates:) (repository=iis/kukad, branch=dependencies/babel)
DEBUG: Creating PR (repository=iis/kukad, branch=dependencies/babel)
       "prTitle": "Deps: Update babel to v7.10.5"
DEBUG: createPr(dependencies/babel, title=Deps: Update babel to v7.10.5) (repository=iis/kukad, branch=dependencies/babel)
DEBUG: fetching default reviewers (repository=iis/kukad, branch=dependencies/babel)
 INFO: PR created (repository=iis/kukad, branch=dependencies/babel)
       "pr": 216,
       "prTitle": "Deps: Update babel to v7.10.5"
DEBUG: getBranchStatus(dependencies/babel, requiredStatusChecks=true) (repository=iis/kukad, branch=dependencies/babel)
DEBUG: branch status check result (repository=iis/kukad, branch=dependencies/babel)
       "commitStatus": {"successful": 0, "inProgress": 0, "failed": 0}
DEBUG: getBranchStatus() result (repository=iis/kukad, branch=dependencies/babel)
       "branchStatus": "yellow",
       "branchName": "dependencies/babel"
DEBUG: Skipping assignees and reviewers as automerge=true (repository=iis/kukad, branch=dependencies/babel)
DEBUG: Created Pull Request #216 (repository=iis/kukad, branch=dependencies/babel)
DEBUG: Ensuring comment "⚠️ Artifact update problem" in #216 is removed (repository=iis/kukad, branch=dependencies/babel)
DEBUG: Found 0 comments (repository=iis/kukad, branch=dependencies/babel)
DEBUG: Checking #216 for automerge (repository=iis/kukad, branch=dependencies/babel)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=iis/kukad, branch=dependencies/babel)
DEBUG: PR is not ready for merge (repository=iis/kukad, branch=dependencies/babel)
       "canMergeReason": undefined
```

**Comment by viceice** [comment]
See your log:
```
DEBUG: branch status check result (repository=iis/kukad, branch=dependencies/babel)
       "commitStatus": {"successful": 0, "inProgress": 0, "failed": 0}
DEBUG: getBranchStatus() result (repository=iis/kukad, branch=dependencies/babel)
       "branchStatus": "yellow",
       "branchName": "dependencies/babel"
```
`branchStatus=yellow`, you have no reported build status, so renovate will not automerge by default.
`requiredStatusChecks` is enabled by default, so you need to configure it to `null` to override.
This is not recommend, so please add some ci to report build status for automerge to work.

**Comment by literat** [comment]
Ok. I understand that renovate needs to know if the tests passed. But I do not know, how to do that. BB gets notified if ci pipeline passes or fails. I see build status in open PR in BB. So how should I configure renovate to know about jenkins pipeline status. Or how the process works?

Renovate runs every hour. CI build took few minutes to finish. So in another run renovate checks build statuses and automerges the branches?

**Comment by viceice** [comment]
> Ok. I understand that renovate needs to know if the tests passed. But I do not know, how to do that. BB gets notified if ci pipeline passes or fails. I see build status in open PR in BB. So how should I configure renovate to know about jenkins pipeline status. Or how the process works?

If you see the status in bitbucket, renovate will see them too.

> Renovate runs every hour. CI build took few minutes to finish. So in another run renovate checks build statuses and automerges the branches?

Yes, that the way it works.

**Comment by literat** [comment]
Hi, I have still few issues with automerge. It seems that git author match and everything match but branch did not merge.

```
INFO: DRY-RUN: Would update PR #225 (repository=iis/kukad, branch=dependencies/bootstrap-4.x-lockfile)
DEBUG: Checking #225 for automerge (repository=iis/kukad, branch=dependencies/bootstrap-4.x-lockfile)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=iis/kukad, branch=dependencies/bootstrap-4.x-lockfile)
DEBUG: getBranchStatus(dependencies/bootstrap-4.x-lockfile, requiredStatusChecks=true) (repository=iis/kukad, branch=dependencies/bootstrap-4.x-lockfile)
DEBUG: branch status check result (repository=iis/kukad, branch=dependencies/bootstrap-4.x-lockfile)
       "commitStatus": {"successful": 1, "inProgress": 0, "failed": 0}
DEBUG: Automerging #225 (repository=iis/kukad, branch=dependencies/bootstrap-4.x-lockfile)
 INFO: DRY-RUN: Would merge PR #225 (repository=iis/kukad, branch=dependencies/bootstrap-4.x-lockfile)
```

I do not understand that DRY-RUN. Only configuration which does not match is schedule. Can it have an effect on automerge?

Thank you.

**Comment by viceice** [comment]
@literat you need to disable [`dryRun`](https://docs.renovatebot.com/self-hosted-configuration/#dryrun)

**Comment by literat** [comment]
> @literat you need to disable [`dryRun`](https://docs.renovatebot.com/self-hosted-configuration/#dryrun)

Dry run is not enabled. Branches and PRs are created. By default dryRun is false (as I see in docs).

**Comment by literat** [comment]
Ok, another run of Jenkins job helps and brach has been automerged. But I am still confused.

**Comment by viceice** [comment]
if you check [requiredStatusChecks](https://docs.renovatebot.com/configuration-options/#requiredstatuschecks). If you repos have those, renovate will need at least two runs to automerge.

[prCreation](https://docs.renovatebot.com/configuration-options/#prcreation) also changes the needed runs.

**Comment by literat** [comment]
Thank you for explanation. Both options are set to default. So minimal count of runs to automerge is at least two.
