### ISSUE TITLE
Specify a list of enabled packages

### ISSUE THREAD

**Issue by meg-hegde** [renovatebot/config-help#753]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

Bitbucket Server

### What would you like to do?

I would like to able to run Renovate on a repository for just one or two packages.
I can see a number of methods in the configuration options to exclude packages or package patterns, and a way to enable a package manager, but I can’t seem to find a way to enable a specific package. Is there any way of passing a list of enabled packages/package patterns to the Renovate configuration, please?

**Comment by viceice** [comment]
See [`packageRules`](https://docs.renovatebot.com/configuration-options/#packagerules)
