### ISSUE TITLE
Unexpected behavior of automerge and labeling

### ISSUE THREAD

**Issue by ilyalavrenov** [renovatebot/config-help#758]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

This is likely user error, but we're having some difficulty configuring consistent behavior of automerge and labels on PRs.

Here is our config, `automergeDev` extends `default`:
```
{
  "renovate-config": {
    "default": {
      "extends": [
        "config:base",
        ":preserveSemverRanges",
        ":rebaseStalePrs",
        ":semanticCommits",
        ":semanticCommitTypeAll(chore)",
        ":prHourlyLimit4"
      ],
      "rangeStrategy": "bump",
      "labels": [
        "renovate",
        "dependencies"
      ],
      "packageRules": [
        {
          "depTypeList": [
            "dependencies",
            "packages"
          ],
          "semanticCommitType": "fix"
        },
        {
          "depTypeList": [
            "devDependencies",
            "dev-packages"
          ],
          "labels": [
            "renovate",
            "dependencies",
            "deptypedev"
          ],
          "groupName": "devDependencies",
          "separateMajorMinor": true,
          "separateMinorPatch": false
        },
        {
          "updateTypes": [
            "patch"
          ],
          "groupName": "patchReleases"
        }
      ],
      "separateMinorPatch": true
    },
    "automergeDev": {
      "extends": [
        "@orgname"
      ],
      "packageRules": [
        {
          "depTypeList": [
            "devDependencies",
            "dev-packages"
          ],
          "labels": [
            "automerge",
            "renovate",
            "dependencies",
            "deptypedev"
          ],
          "automerge": true,
          "groupName": "automergeDev",
          "separateMinorPatch": true,
          "requiredStatusChecks": []
        }
      ]
    }
  }
}
```
and an example of the PRs that sometimes get created for repos using `automergeDev`: 
![](https://i.imgur.com/gIXG188.png)

This PR has dev and non-dev dependencies but they are batched together into the same PR, rather than separating the dev dependencies into their own `groupName` PR. Because of this, the PR never actually automerges due to the presence of non-dev dependencies, even though it has a `automerge` label. If there are only dev dependencies being updated, it automerges just fine.

How can I separate out the automergeable packages into their own PR so that automerge works as expected? The expected result is
- any repo that uses the `automergeDev` preset will have all dev dependency updates separate from normal dependencies, and automatically merge those PRs. Normal dependencies and dev dependencies should not be in the same PR.
- only the above PRs have the labels `automerge` and `deptypedev` (ie no `deptypedev` label unless all dependencies in the PR are dev dependencies)

thank you!

**Comment by rarkins** [comment]
The main thing you should do is ensure that dev dependencies aren't captured by both the rules you define. 

If dependencies in the same PR have different labels then Renovate will pick the labels from whichever dependency is first in the list. 

Your second rule looks like it will automerge major releases too.
