### ISSUE TITLE
Use setup.cfg as package file instead of setup.py

### ISSUE THREAD

**Issue by meg-hegde** [renovatebot/config-help#762]
### Which Renovate are you using?

Renovate Open Source CLI

Other (please write below)

### Which platform are you using?

Bitbucket Server

### What would you like to do?

I would like to use setup.cfg instead of setup.py as the package file for a Python repo. I am able to ignore setup.py by setting RENOVATE_IGNORE_PATHS, however I am not sure how to set setup.cfg as the correct package file. I have tried setting RENOVATE_FILE_MATCH as 'setup.cfg', and I've also tried setting RENOVATE_PACKAGE_FILE as 'setup.cfg', but neither of these have worked.

If setup.cfg is not supported, can I get around this issue by copying the contents of setup.cfg into a package.json file?

**Comment by rarkins** [comment]
Setup.cfg is not currently supported and you can't work around it. There's a feature request in the main repo you can subscribe to in order to be notified when it's supported

**Comment by meg-hegde** [comment]
Thank you, I'll subscribe to that.
