### ISSUE TITLE
nodejs monorepo - Renovate not updating package dependencies

### ISSUE THREAD

**Issue by Tielem** [renovatebot/config-help#763]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Yes/not directly relevant.

### What would you like to do?

I installed Renovate in a fork of a project, which is a nodejs monorepo, to manage some deprecated and outdated dependencies. You can see the fork here - https://github.com/Tielem/gatsby-typescript

The roadblock that I'm encountering: Renovate correctly pinned and updated the devDependencies both of the root project and the packages in the monorepo. However, it seems to be ignoring the (runtime) dependencies of the different packages in the monorepo. Is this intended behavior? Can I resolve this somehow? I want Renovate to update/manage those too.

**Comment by rarkins** [comment]
Please give a specific example of one dependency you think should be updated but is not. And also locate any logs referring to that dependency and paste them here.

**Comment by Tielem** [comment]
@rarkins For the logs, do you suggest the full output? Or can I link them somehow? They are pages long

**Comment by rarkins** [comment]
"any logs referring to that dependency"

**Comment by viceice** [comment]
@Tielem post the full `DEBUG` log to a gist and add a link here

**Comment by rarkins** [comment]
Pick a dependency. Search it in the logs. Copy paste relevant lines

**Comment by Tielem** [comment]
OK, there is a series of dependencies for which no updates are being provided by Renovate on the repository right now

```
yarn outdated v1.22.4
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package                                Current Wanted Latest Workspace                     Package Type URL
@graphql-codegen/core                  1.13.1  1.17.0 1.17.0 gatsby-plugin-graphql-codegen dependencies https://github.com/dotansimha/graphql-codegen#readme
@graphql-codegen/plugin-helpers        1.13.1  1.17.0 1.17.0 gatsby-plugin-graphql-codegen dependencies https://github.com/dotansimha/graphql-code-generator#readme
@graphql-codegen/typescript            1.13.1  1.17.0 1.17.0 gatsby-plugin-graphql-codegen dependencies https://github.com/dotansimha/graphql-code-generator#readme
@graphql-codegen/typescript-operations 1.13.1  1.17.0 1.17.0 gatsby-plugin-graphql-codegen dependencies https://github.com/dotansimha/graphql-code-generator#readme
@graphql-toolkit/code-file-loader      0.10.2  0.10.7 0.10.7 gatsby-plugin-graphql-codegen dependencies https://github.com/ardatan/graphql-toolkit#readme
@graphql-toolkit/common                0.10.2  0.10.7 0.10.7 gatsby-plugin-graphql-codegen dependencies https://github.com/ardatan/graphql-toolkit#readme
@graphql-toolkit/core                  0.10.2  0.10.7 0.10.7 gatsby-plugin-graphql-codegen dependencies https://github.com/ardatan/graphql-toolkit#readme
@graphql-toolkit/graphql-file-loader   0.10.2  0.10.7 0.10.7 gatsby-plugin-graphql-codegen dependencies https://github.com/ardatan/graphql-toolkit#readme
@graphql-toolkit/graphql-tag-pluck     0.10.2  0.10.7 0.10.7 gatsby-plugin-graphql-codegen dependencies https://github.com/ardatan/graphql-toolkit#readme
@graphql-toolkit/json-file-loader      0.10.2  0.10.7 0.10.7 gatsby-plugin-graphql-codegen dependencies https://github.com/ardatan/graphql-toolkit#readme
@graphql-toolkit/url-loader            0.10.2  0.10.7 0.10.7 gatsby-plugin-graphql-codegen dependencies https://github.com/ardatan/graphql-toolkit#readme
Done in 1.76s.
```

I'm looking at @graphql-codegen/core as the "main" dependency I expect to be updated.

Something I noticed in the the gatsby-plugin-graphql-codegen "workspace" is that Renovate didn't remove the '^' on the "dependencies" in package.json

```
  "dependencies": {
    "@graphql-codegen/core": "^1.13.1",
    "@graphql-codegen/plugin-helpers": "^1.13.1",
    "@graphql-codegen/typescript": "^1.13.1",
    "@graphql-codegen/typescript-operations": "^1.13.1",
    "@graphql-toolkit/code-file-loader": "^0.10.2",
    "@graphql-toolkit/common": "^0.10.2",
    "@graphql-toolkit/core": "^0.10.2",
    "@graphql-toolkit/graphql-file-loader": "^0.10.2",
    "@graphql-toolkit/graphql-tag-pluck": "^0.10.2",
    "@graphql-toolkit/json-file-loader": "^0.10.2",
    "@graphql-toolkit/url-loader": "^0.10.2",
    "fs-extra": "^9.0.0",
    "lodash.debounce": "^4.0.8"
  },
```
(https://github.com/Tielem/gatsby-typescript/blob/master/packages/gatsby-plugin-graphql-codegen/package.json)

I thought this was standard when Renovate pinned the dependencies? Should I pin them manually?

This is a gist of the last log from renovatebot - https://gist.github.com/Tielem/4471c388006eef0f50fe089b5b8818e8

```
          {
            "depName": "@graphql-codegen/core",
            "depType": "dependencies",
            "updates": [],
            "depIndex": 0,
            "warnings": [],
            "sourceUrl": "https://github.com/dotansimha/graphql-code-generator",
            "datasource": "npm",
            "currentValue": "^1.13.1",
            "lockedVersion": "1.13.1",
            "prettyDepType": "dependency",
            "sourceDirectory": "packages/graphql-codegen-core"
          },
```

I played around a bit with the renovate.json config file during the day, expecting it might contain an error. Currently it is the default config

**Comment by rarkins** [comment]
Please read about "rangeStrategy" in the docs as it answers some of your questions

**Comment by Tielem** [comment]
@rarkins Thank you. I managed to configure renovate to do what I wanted. The specific documentation for rangeStrategy may need 1-2 nice examples though
