### ISSUE TITLE
Weekly PR

### ISSUE THREAD

**Issue by Zelgadis87** [renovatebot/config-help#764]
### Which Renovate are you using?
WhiteSource Renovate App

### Which platform are you using?

GitLab.com

### Have you checked the logs? Don't forget to include them if relevant

Not relevant.

### What would you like to do?

I would like to automatically bump all non-major dependencies of my project once a week to reduce dependency upgrade noise. Right now I almost have the optimal solution for me:
```"packageRules": [
    {
      "updateTypes": [
        "patch",
        "minor"
      ],
      "groupName": "minor",
      "automerge": true,
      "automergeType": "pr",
      "schedule": [ "on saturday before 8am" ]
    }
```

I almost surprised this even works, so great kudos to Renovate for making this possible!

I would like to ask the following questions regarding this setup:
- Since I'm currently using the hosted Renovate App, I would like some suggestions on how to set up this weekly schedulation. I've given 8 hours on a Saturday morning to the "schedule" option, so that Renovate can have the time to pick up the project, create the PR, wait for the pipeline to complete (usually 5 mins) and automerge. Since I obviously have no control on when Renovate runs, I tried with an interval of 8 hours (which currently seems to be working fine). For your experience, am I at risk of skipping weeks of updates with this configuration?
- Opposite to the previous point, if on a Saturday morning before 8am a dependency gets updated, I would get a second PR with a single dependency update, which I'm trying to avoid. Is there any option I could set for a more rigorous once-a-week setup? Would you suggest moving to a self-hosted setup to achieve better control on the schedulation?
- Would it be possible to configure the PR to be created anytime in the week, but only automerged once a week? This would allow a more granular control over what is happening (eg, pipelines start failing from a particular commit onward) and would allow more transparency over the weekly update process.

Thanks, and keep up the great work!

**Comment by rarkins** [comment]
> * I've given 8 hours on a Saturday morning to the "schedule" option, so that Renovate can have the time to pick up the project, create the PR, wait for the pipeline to complete (usually 5 mins) and automerge.

Currently, scheduling controls only when MRs are *created* (technically, it's when the branch is created, which is not always the same as when the MR is created, depending on config).

So your window needs to be enough to create all MRs you need. If you implement no hourly or concurrent limits, then the first time Renovate runs in the window should result in them all being created. However if you want them to be automerged, it means every other MR remaining would need to be rebased afterwards. e.g. if you have 5 MRs outstanding then there will be 5 pipelines run the first time they're all created, then 4 rebased/rerun after the first is automerged, then 3, 2, 1.

Also, automerge doesn't currently happen automatically/instantly after the pipeline is complete - we don't have any webhook listener that can tell when a branch is passing and ready for automerge. Instead, you'll see Renovate running ~hourly on schedule or any time an action you take triggers another run (e.g. you merge a MR manually, or request a rebase).

> * For your experience, am I at risk of skipping weeks of updates with this configuration?

You shouldn't be at risk unless you have a prHourlyLimit set e.g. it has a setting of 2 if you inherit `config:base` preset.

> * Opposite to the previous point, if on a Saturday morning before 8am a dependency gets updated, I would get a second PR with a single dependency update, which I'm trying to avoid. Is there any option I could set for a more rigorous once-a-week setup? Would you suggest moving to a self-hosted setup to achieve better control on the schedulation?

The answer is yes, you'll get a second PR but no, self-hosted won't really change that.

> * Would it be possible to configure the PR to be created anytime in the week, but only automerged once a week?

Currently scheduling only controls when MRs are created and not when they're automerged.

If after using Renovate for a while then you have some concrete ideas for more fine-grained controls, please feel free to raise a feature request in the main repo. We definitely need to improve this eventually, however it's a pretty complicated thing to do (there are many edge cases..)

**Comment by MeStrak** [comment]
I have some similar questions, although not exactly the same, related to this project: https://github.com/Sanofi-IADC/whispr/.

We have semantic release configured, which bumps our app version and performs a release any time there is a merge to master for fix and feat commits (a few other commit types are also covered).

My goal:
- Max one release per week for minor dependency updates
- Don't perform a new release for every minor dependency merge, instead group those dependencies and merge them as one branch so that we only trigger one release

I thought that `"group:allNonMajor"` and `"schedule:earlyMondays"` would achieve the desired result, but this weekend we had automatic releases based on separate branches created for minor dependency updates.

I'm not sure if I have something mis-configured or if this is the intended behaviour. Is there a way to force this behaviour to group all minor updates into a single branch before the merge to master?

This is our renovate config
```
{
  "extends": [
    "config:base",
    ":rebaseStalePrs",
    "group:allNonMajor",
    "schedule:earlyMondays",
    ":automergeMinor",
    ":automergeTesters",
    ":automergeLinters",
    ":automergeTypes",
    ":automergePatch",
    ":semanticCommits"
  ],
  "semanticCommitScope": "dependency maintenance"
}
```

**Comment by Zelgadis87** [comment]
@rarkins thanks for the detailed answer! 

> > * For your experience, am I at risk of skipping weeks of updates with this configuration?
> 
> You shouldn't be at risk unless you have a prHourlyLimit set e.g. it has a setting of 2 if you inherit `config:base` preset.

Perfect!

> 
> > * Opposite to the previous point, if on a Saturday morning before 8am a dependency gets updated, I would get a second PR with a single dependency update, which I'm trying to avoid. Is there any option I could set for a more rigorous once-a-week setup? Would you suggest moving to a self-hosted setup to achieve better control on the schedulation?
> 
> The answer is yes, you'll get a second PR but no, self-hosted won't really change that.

I mentioned self-hosted because I could then run Renovate on the project once a day, although maybe it's way too much for this use case. I'm not sure it will work, given what you said about having to run again for automerge to kick in. Oh well, I'll live with 2 PRs.. :)

> 
> > * Would it be possible to configure the PR to be created anytime in the week, but only automerged once a week?
> 
> Currently scheduling only controls when MRs are created and not when they're automerged.
> 
> If after using Renovate for a while then you have some concrete ideas for more fine-grained controls, please feel free to raise a feature request in the main repo. We definitely need to improve this eventually, however it's a pretty complicated thing to do (there are many edge cases..)

I have been using Renovate for a few months on a relatively stable project. I have reached this weekly setup because it was absolutely impossible for us to maintain all the automatic PRs we were getting before. This setup has been in place for the past two weeks now, and we find it quite perfect for us. Automerging on schedule would shed some more light on the whole process (combined with master issue) and improve the situation even more, but for now we have had no problems. 

I think the absolute best for us would be to create PRs as soon as possible (major releases get 1 PR each, minor+patch get 1 aggregated PR), reference them in the master issue, automerge grouped minor updates once a week (eg, saturday morning) assuming all checks are successful, leave manual intervention for major deps or problematic weekly updates.

I'll be sure to leave a more detailed feedback once the system has been live for a few more weeks!  
Thanks for the great product and support!

**Comment by rarkins** [comment]
> I'm not sure it will work, given what you said about having to run again for automerge to kick in.

Yes, you'd need to run it if you want to either (a) automerge, or (b) rebase any existing branches after others have merged. So that's the long answer as to why it wouldn't make a difference - running it once won't really work.

> Can the PR title be customizable with placeholders in any way? I was thinking about naming the PR something like "Weekly updates 20/07/2020"

We don't have a date but it would be technically feasible to create it. The main problem would be that Renovate would want to bump the date each day, if you don't merge them. It would be much more challenging to have the date fixed.

**Comment by Zelgadis87** [comment]
> > I'm not sure it will work, given what you said about having to run again for automerge to kick in.
> 
> Yes, you'd need to run it if you want to either (a) automerge, or (b) rebase any existing branches after others have merged. So that's the long answer as to why it wouldn't make a difference - running it once won't really work.
> 

Makes perfect sense! 🙂 

> > Can the PR title be customizable with placeholders in any way? I was thinking about naming the PR something like "Weekly updates 20/07/2020"
> 
> We don't have a date but it would be technically feasible to create it. The main problem would be that Renovate would want to bump the date each day, if you don't merge them. It would be much more challenging to have the date fixed.

I was thinking maybe about the date the PR gets created, but I'm not sure you are able to retrieve that value, rethinking about it. 
In my specific case the PR gets created and merged theoretically on the same date (until an automerge specific schedulation gets implemented, as talked above), so I wouldn't have any auto bumps, but it feels like an incredibly narrow use case. 
Thanks for thinking it through tho, really appreciated.

Thanks again @rarkins for the great work and the support!
I'm closing the issue as you have answered perfectly all my questions 💯

**Comment by viceice** [comment]
@rarkins we have `Pr.createdAt` available
