### ISSUE TITLE
Invalid configuration option: dependencyDashboard

### ISSUE THREAD

**Issue by stefee** [renovatebot/config-help#765]
**What Renovate type are you using?**

GitHub App

**Describe the bug**

The `dependencyDashboard` field is not recognised even though it appears in the documentation.

<img width="925" alt="Screenshot 2020-07-20 at 14 45 41" src="https://user-images.githubusercontent.com/18026180/87944756-b728d380-ca97-11ea-8603-0d02f959eb6a.png">

**Relevant debug logs**

**To Reproduce**

Add `"dependencyDashboard": true` to `renovate.json`

**Additional context**

**Comment by viceice** [comment]
@rarkins Is the change not yet published to the app?

@stefee You can use the old `masterIssue` prefix instead of `dependencyDashboard` for all master issue config options as workaround.

**Comment by viceice** [comment]
Ok look like the app is on renovate v21.26.2 while the new `dependencyDashboard` namings come with [v21.28.0](https://github.com/renovatebot/renovate/releases/tag/21.28.0)

**Comment by rarkins** [comment]
Sorry, it hasn't gone live yet. Maybe later today or sometime tomorrow.

**Comment by stefee** [comment]
Thanks, we can wait 👍
