### ISSUE TITLE
pip_requirements setup

### ISSUE THREAD

**Issue by Fandekasp** [renovatebot/config-help#77]
Until we migrate to Pipfile, we are still using 2 files for python requirements named "requirements.txt" and "requirements-dev.txt".

By default, the -dev one is ignored by renovatebot.

I tried to edit the config file as follow:
```json
{
  "extends": [
    "config:base"
  ],
  "pip_requirements": [
      "requirements.txt",
      "requirements-dev.txt"
  ]
}
```
but renovate opened a new issue with:

File: `renovate.json`
Error type: The renovate configuration file contains some invalid settings
Message: Invalid configuration option: `pip_requirements.0`, Invalid configuration option: `pip_requirements.1`

How should I fix this configuration ?

**Comment by rarkins** [comment]
I think you're probably looking for:

```
{
  "extends": [
    "config:base"
  ],
  "pip_requirements": {
	"fileMatch": [
      "requirements.txt",
      "requirements-dev.txt"
    ]
  }
}
```

i.e. put that list inside `fileMatch` in your config

**Comment by rarkins** [comment]
@Fandekasp did that work?

**Comment by Fandekasp** [comment]
@rarkins it did! Many thanks :)
