### ISSUE TITLE
packageRules configuration, patterns, exclude version pattern from bumping

### ISSUE THREAD

**Issue by amadi21** [renovatebot/config-help#772]
### Which Renovate are you using?

Docker image on OpenShift: renovate/renovate:21.32.3-slim

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

Yes, I did.

### What would you like to do?

While reading the documentation about packageRules, I thought packagePatterns includes the packages I want to match. On the other hand, in excludePackagePatterns, the packages I want to exclude. That's what the logic said, but unfortunately, I didn't achieve my goal in this way.

For example, if my groupId is `com.example.test` and I want to match artifacts from this group (without any other groupId, including dependencies from maven repo), I had to set:
`{"packagePatterns": ["*"], "excludePackagePatterns": ["com.example.test*"], "enabled": false}`
I don't understand why it works like this. What am I doing wrong?

Next problem, in my maven projects I have the following version:
`<version>1.0.0-SNAPSHOT</version>`

This is the main version of the application, not dependencies. I would like the bot not to bump any version with the suffix -SNAPSHOT, but unfortunately I haven't been able to do it for over 2 hours. Is there a way to do that, if so, how?

**Comment by rarkins** [comment]
You need to use regex patterns

**Comment by amadi21** [comment]
I tried with matchCurrentVersion but didn't work. It only worked if I gave the full version..

**Comment by rarkins** [comment]
What you provided above is not a regex. Provide a public reproduction if you need us to look at anything

**Comment by amadi21** [comment]
This is my config.js:
```
module.exports = {
  endpoint: "https://mybitbucketurl",
  username: 'user',
  password: 'pass',
  platform: 'bitbucket-server',
  enabledManagers: ['maven'],
  repositories: ['myproject/myrepo'],
  logLevel: 'debug',
  packageRules: [
    {
      "managers": ["maven"],
      "registryUrls": ["https://myartifactoryurl/content/groups/mygroup/"]
    },
    {
      "packagePatterns": ["*"],
      "excludePackagePatterns": ["com.example.test*"],
      "enabled": false
    },
    {
      "matchCurrentVersion": "!/.*-SNAPSHOT$/"
    }
  ],
  "hostRules": [
    {
      "hostType": "maven",
      "endpoint": "https://myartifactoryurl/content/groups/mygroup/",
      "username": "user",
      "password": "pass"
    }
  ]
};
```
To be clear, the user and password will be injected securely after successful configuration :)

With this configuration works matching packages that contain `com.example.test`, without packages from maven repo and others, for example `com.example.aaa`. Is working dependency checking in my artifactory. This is, partly, what I want. I'm not sure if the configuration is correct becuase it seems illogical to me, but it works. If it's wrong, tell me, please.

matchCurrentVersion parameter, unfortunately, doesn't work. I suggested the regex described in the allowedVersions parameter.

**Comment by rarkins** [comment]
> I had to set:
> `{"packagePatterns": ["*"], "excludePackagePatterns": ["com.example.test*"], "enabled": false}`
> I don't understand why it works like this. What am I doing wrong?

This will disable all packages except those containing `com?example?tes` (your regex could be improved, but probably works ok). Why do you think it's wrong and what were you trying to do?

> Next problem, in my maven projects I have the following version:
> `<version>1.0.0-SNAPSHOT</version>`
> 
> This is the main version of the application, not dependencies. I would like the bot not to bump any version with the suffix -SNAPSHOT, but unfortunately I haven't been able to do it for over 2 hours. Is there a way to do that, if so, how?

You need to add the `"enabled": false` line to the rule. Currently you're simply matching but with no "action".

**Comment by amadi21** [comment]
> This will disable all packages except those containing com?example?tes (your regex could be improved, but probably works ok). Why do you think it's wrong and what were you trying to do?

I changed my regex to the one you gave me. I could try with escaping dots, I guess it would be ok.

Why I think it's wrong? Let me give you my point of view.

Referring to documentation:
`packagePatterns` - Package name patterns to match. [...] Use this field if you want to have one or more package names patterns in your package rule.
`excludePackagePatterns` - Package name patterns to exclude. [...] Use this field if you want to have one or more package name patterns excluded in your package rule.

I understand it so that in packagePatterns I give the packages I want to match to the analysis (turn on) rather than disable. In excludePackagePatterns, on the other hand, the packages that I want to exclude from the previously selected in packagePatterns. I talked to my teammate and he was surprised too that the documentation suggests something completely different from what you wrote above. It seems illogical, unintuitive to us.

What I want to achieve:
- use my own artifactory (done)
- consider only packages containing com.example.test without the others, also without packages publicly available on the Internet, in maven repo (done)
- do not bump the version where the current version contains a suffix -SNAPSHOT (not done)

I have three old versions:
1. main version, for example 1.0.0-SNAPSHOT
2. a version of the dependency from maven repo that I don't want to bump
3. a version of the dependency for which a newer version is available in my artifactory

I added a line `"enabled": false`, so there should be one pull request (to bump version 3. from the above list), but no one has been created.

The configuration looks like this now:
```
module.exports = {
  endpoint: "https://mybitbucketurl",
  username: 'user',
  password: 'pass',
  platform: 'bitbucket-server',
  enabledManagers: ['maven'],
  repositories: ['myproject/myrepo'],
  logLevel: 'debug',
  packageRules: [
    {
      "managers": ["maven"],
      "registryUrls": ["https://myartifactoryurl/content/groups/mygroup/"]
    },
    {
      "packagePatterns": ["*"],
      "excludePackagePatterns": ["com?example?test"],
      "enabled": false
    },
    {
      "matchCurrentVersion": "!/.*-SNAPSHOT$/",
      "enabled": false
    }
  ],
  "hostRules": [
    {
      "hostType": "maven",
      "endpoint": "https://myartifactoryurl/content/groups/mygroup/",
      "username": "user",
      "password": "pass"
    }
  ]
};
```

**Comment by viceice** [comment]
The patterns are Javascript regex patterns, so to match a start pattern you should use `"^com\.example\.test"`.

**Comment by rarkins** [comment]
I think you'll find the following to be more logical:

```js
module.exports = {
  endpoint: "https://mybitbucketurl",
  username: 'user',
  password: 'pass',
  platform: 'bitbucket-server',
  enabledManagers: ['maven'],
  repositories: ['myproject/myrepo'],
  logLevel: 'debug',
  packageRules: [
    {
      "managers": ["maven"],
      "registryUrls": ["https://myartifactoryurl/content/groups/mygroup/"]
    },
    {
      "description": "Disable all packages from updating",
      "packagePatterns": ["*"],
      "enabled": false
    },
    {
      "description": "Re-enable com.example.test packages",
      "packagePatterns": ["^com\\.example\\.test"],
      "enabled": true
    },
    {
      "description": "Disable snapshot versions from updating",
      "matchCurrentVersion": "!/.*-SNAPSHOT$/",
      "enabled": false
    }
  ],
  "hostRules": [
    {
      "hostType": "maven",
      "endpoint": "https://myartifactoryurl/content/groups/mygroup/",
      "username": "user",
      "password": "pass"
    }
  ]
};
```

**Comment by amadi21** [comment]
Yeah, it's much clearer now, thanks! :)

Unfortunately, the bot is still trying to update snapshot versions.

**Comment by rarkins** [comment]
Please run at log level debug and capture the "packageFiles with updates" log message. Copy/paste the JSON for the particular package you think is being mistakenly updated.

**Comment by amadi21** [comment]
The application is called aaa-placeholder and has 5 modules:
1. aaa-placeholder-api
2. aaa-placeholder-impl
3. aaa-placeholder-server
4. aaa-placeholder-test
5. aaa-placeholder-web

The snapshot version is both in the main pom and in the pom of each of these modules. Attempting to update the version is only in these 5 modules.

Example JSON for one of them:
```
{
  "datasource": "maven",
  "packageFile": "aaa-placeholder-api/pom.xml",
  "deps": [
    {
      "datasource": "maven",
      "depName": "com.example.test:aaa-placeholder",
      "currentValue": "2.59.0.0-SNAPSHOT",
      "fileReplacePosition": 347,
      "registryUrls": ["https://repo.maven.apache.org/maven2 "],
      "depIndex": 0,
      "updates": [
        {
          "fromVersion": "2.59.0.0-SNAPSHOT",
          "toVersion": "2.59.112.0",
          "newValue": "2.59.112.0",
          "newMajor": 2,
          "newMinor": 59,
          "updateType": "minor",
          "isSingleVersion": true
        }
      ],
      "warnings": [],
      "sourceUrl": null
    }
  ],
  "parent": "pom.xml"
}
```

**Comment by rarkins** [comment]
Try this: `"matchCurrentVersion": "-SNAPSHOT$",`

**Comment by amadi21** [comment]
It didn't help. JSON looks the same as before.

**Comment by rarkins** [comment]
Sorry, my mistake. Try `"matchCurrentVersion": "/-SNAPSHOT$/",`

**Comment by amadi21** [comment]
Still the same :/

**Comment by rarkins** [comment]
We'll need a reproduction repo to debug any further. Please try to replicate on GitHub.com using any public package

**Comment by amadi21** [comment]
I created repo https://github.com/amadi21/aaa-placeholder
I added a dependency (hystrix) on a version with a suffix -SNAPSHOT

**Comment by rarkins** [comment]
Thanks, that helped. I had forgotten that `allowedVersions` supports regex, but `matchCurrentVersion` does not. The above is not going to work because of that. I've created a feature request for it in the main repo: https://github.com/renovatebot/renovate/issues/6810

In the meantime you'd need to disable such dependencies by name, or by exact version.

**Comment by amadi21** [comment]
I excluded certain specific versions and now it works. That's enough for me now, we'll move on to `matchCurrentVersion` as soon as it starts supporting regex.

Thank you for all your answers, for your help and for creating a feature request. I look forward to this option working :)
