### ISSUE TITLE
No pull requests created after setting up Gitlab repo

### ISSUE THREAD

**Issue by Clumsy-Coder** [renovatebot/config-help#773]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitLab.com

### Have you checked the logs? Don't forget to include them if relevant

No logs present

### What would you like to do?

Config file (json5)

```json5
{
  extends: ['@teppeis'],
  automerge: true,
  npm: {
    enabled: true,
  },
}

```

steps done:
1. Log into renovate dashboard (gitlab login)
2. Connect to a repo (install/uninstall repo option)
3. Wait for something to happen. (so far, nothing)

**Comment by rarkins** [comment]
https://docs.renovatebot.com/install-gitlab-app/#detecting-new-projects

Please reopen if you have not received an MR within the next 2 hours
