### ISSUE TITLE
Log format configuration

### ISSUE THREAD

**Issue by morremeyer** [renovatebot/config-help#774]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

Not relevant for this question.

### What would you like to do?

We’re running renovate in our own Kubernetes Clusters an collecting all logs. Currently, renovate logs all events as multiline logs:

```
 INFO: Ignoring event with no repository
       "payload": {
         "event_name": "project_create",
         "created_at": "2020-07-22T12:34:01Z",
         "updated_at": "2020-07-22T12:34:01Z",
         "name": "testbundle",
         "path": "testbundle",
         "path_with_namespace": "[REDACTED]/testbundle",
         "project_id": 1337,
         "owner_name": "[REDACTED]",
         "owner_email": "",
         "project_visibility": "private"
       }
```

To make them searchable better, I want to have the log output on a single line so our logging system (promtail + loki) can deal with that easily.

I have not found any information on how to configure the logging format besides the mention of `logFormat="json"` in some documentation (e.g. https://docs.renovatebot.com/self-hosted-configuration/#logcontext).

Is it missing from the docs, am I missing something?

I’m glad about any help :)

**Comment by rarkins** [comment]
Set LOG_FORMAT=json in env and you should see each line logged is a stringified JSON object. It seems we need to add this to documentation somewhere - a PR would be welcome

**Comment by morremeyer** [comment]
I just deployed that and it works fine, thanks for the quick help!

I will make a PR to the documentation, but won’t get around to that in the next few days. stay tuned.
