### ISSUE TITLE
gitlabci-include manager does not pick up file despite matching regex

### ISSUE THREAD

**Issue by morremeyer** [renovatebot/config-help#775]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```
 INFO: Processing repository (repository=[OMITTED]/testbundle)
       "priority": 100,
       "reason": "scheduled"
 INFO: Processing gitlab hostRules (repository=[OMITTED]/testbundle)
 INFO: Repository started (repository=[OMITTED]/testbundle)
       "renovateVersion": "21.6.6"
 INFO: Dependency extraction complete (repository=[OMITTED]/testbundle)
       "baseBranch": "master",
       "stats": {
         "managers": {"dockerfile": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }
 INFO: Repository finished (repository=[OMITTED]/testbundle)
       "durationMs": 5696
```

### What would you like to do?

We’re using [copier](https://pypi.org/project/copier/) to template configurations which are put into git repositories in the end. One of those is a GitLab CI Config in a file named `.gitlab-ci.yml.tmpl`:

```yaml
stages:
  - test
  - build

include:
  - project: syseleven/gitlab-ci-templates
    file: YamlLint.yml
    ref: 1.6.1
  - project: syseleven/gitlab-ci-templates
    file: DockerLint.yml
    ref: 1.6.1
  - project: syseleven/gitlab-ci-templates
    file: DockerBuild-kaniko.yml
    ref: 1.6.1
[%- if extensions_chart %]
  - project: syseleven/gitlab-ci-templates
    file: HelmLint.yml
    ref: 1.6.1

helm-lint:
  variables:
    HELM_PATH: [[ helm_chart_name ]]-extension/
[%- endif %]
```

We want the includes to be updated by renovate, too. That’s why we extended the `renovate.json` in the `testbundle` repository with the file above:

```yaml
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":docker",
    ":prHourlyLimitNone",
    ":rebaseStalePrs",
    ":label(renovate)"
  ],
  "gitlabci-include": {
    "fileMatch": [
      "^\\.gitlab-ci\\.yml\\.tmpl$"
    ]
  }
}
```

However, as can be seen in the logs above, the `gitlabci-include` manager does not yet pick up the file.

Is there something I am missing about where I need to configure the `fileMatch` or something similar? Could it be that renovate can’t parse the file correctly because it is not an „actual gitlab-ci.yml“ file?

**Comment by rarkins** [comment]
Please log at debug level (LOG_LEVEL=debug in env) so that you can see if the file was matched or not. There are two possibilities:
- file name was not matched
- file name was matched, but no dependencies were found, so the file was skipped

**Comment by rarkins** [comment]
BTW gitlabci-include does use a YAML parser to extract dependencies so the most likely problem is point 2 above

**Comment by morremeyer** [comment]
@rarkins Thanks for your input, we’ll make that file a valid YAML and see if that works :)

**Comment by morremeyer** [comment]
That was indeed the issue, thanks for looking into it!

**Comment by rarkins** [comment]
How did you manage to keep using templates while maintaining a valid YAML structure? I'm curious if you can share in case it helps others in future

**Comment by morremeyer** [comment]
We didn’t as templating this file was already up for discussion with us, so we didn’t explore that route further.
