### ISSUE TITLE
[Question] How to split major updates of different depencies in the same packageRule?

### ISSUE THREAD

**Issue by ClementParis016** [renovatebot/config-help#776]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

No

### What would you like to do?

I would like to group some related packages updates together but still split major updates of each in separate branches.
Precisely, I have the following `packageRule`:
```json
{
  "enabled": true,
  "groupName": "React Router",
  "packagePatterns": ["react-router"],
  "packageNames": ["history"],
  "reviewers": ["ClementParis016"],
  "assignees": ["ClementParis016"]
},
```
Now, there is a new major version of `history` and a new major version of `react-router-hash-link` so Renovate creates a PR that include both updates together.
What I would like instead is Renovate to create separate PRs for each major update of these dependencies (so here one for `history` and one for `react-router-hash-link`) but still group the non-major updates of these deps together in a single PR.
I've tried setting `"separateMajorMinor": true` and `"separateMultipleMajor": true` at the root level but that doesn't change anything.

How can I achieve that, is it even possible?

Thanks in advance!

**Comment by viceice** [comment]
See [`updateTypes`](https://docs.renovatebot.com/configuration-options/#updatetypes)

**Comment by ClementParis016** [comment]
Thanks but I'm not sure I get it 🤔 
As in I should create separate package rules for each dependency with `updateTypes: ['major']` and keep the grouped one with `updatesTypes: ['minor', 'patch']`?

**Comment by viceice** [comment]
simply add `updatesTypes: ['minor', 'patch']` to your grouping rule only, so by default renovate will open seperate pr for reach dependency

**Comment by viceice** [comment]
if you want more help please provide a more complete config

**Comment by ClementParis016** [comment]
That's clear, thanks for your help :)
