### ISSUE TITLE
Authenticate to private composer repository in Gitlab

### ISSUE THREAD

**Issue by bytestream** [renovatebot/config-help#779]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Packagist repository not found (repository=vendor/package)
       "regUrl": "https://gitlab.vendor.com/api/v4/group/2/-/packages/composer/packages.json"

DEBUG: Dependency lookup failure: not found (repository=vendor/package, dependency=vendor/core)
DEBUG: Response code 404 (Not Found) (repository=vendor/package)
       "err": {
         "name": "HTTPError",
         "host": "packagist.org",
         "hostname": "packagist.org",
```

### What would you like to do?

Authentication is required to access the private composer registry - https://docs.gitlab.com/ee/user/packages/composer_repository/#installing-a-package

I've already setup `.composer/auth.json` which is used by the `composer` CLI package but this does not seem to be used.

I had the same issue with NPM (https://docs.renovatebot.com/private-modules/) but I resolved that by setting the npm config.

I have tried using `hostRules` (https://docs.renovatebot.com/configuration-options/#hostrules) but not had any luck.

**Comment by rarkins** [comment]
You'll need to make sure (a) the registry is detected and included in registryUrls, and (b) you have credentials for that in hostRules. Don't use the auth.json for now.

Please paste in your config here as well as the matching log (relevant parts).

**Comment by bytestream** [comment]
a. Yes it's included in the `registryUrls`
```
"registryUrls": [
               "https://www.phpclasses.org/",
               "https://gitlab.vendor.com/api/v4/group/2/-/packages/composer/packages.json",
               "https://packagist.org"
             ],
             "managerData": {"composerJsonType": "project"}
           }
```

b. I added hostRules in several formats but this one seems most correct:
```
{
            hostType: "packagist",
            domainName: "gitlab.vendor.com",
            username: "___token___",
            password: process.env.GITLAB_TOKEN
}
```

The above matches what is defined in `auth.json` which is working in the same CI environment.

The problem is this debug line:
```
DEBUG: Packagist repository not found (repository=vendor/package)
       "regUrl": "https://gitlab.vendor.com/api/v4/group/2/-/packages/composer/packages.json"

DEBUG: Dependency lookup failure: not found (repository=vendor/package, dependency=vendor/core)
DEBUG: Response code 404 (Not Found) (repository=vendor/package)
       "err": {
         "name": "HTTPError",
         "host": "packagist.org",
         "hostname": "packagist.org",
         "method": "GET",
```

Where in the code does it write `Packagist repository not found`? How does it determine the repository is not found?

**Comment by bytestream** [comment]
Looking at the code, it's this function that produces the `Packagist repository not found` message: https://github.com/renovatebot/renovate/blob/456245aabe465529d6623dafd8aa32ed152f5365/lib/datasource/packagist/index.ts#L51

```js
var URL = require('url');

var regUrl = "https://gitlab.vendor.com/api/v4/group/2/-/packages/composer/packages.json";
console.log(
  URL.resolve(regUrl.replace(/\\/?$/, '/'), 'packages.json')
);
// https://gitlab.vendor.com/api/v4/group/2/-/packages/composer/packages.json/packages.json
```

That URL would explain the 404.

Renovate should not be adding `packages.json` if it already exists

**Comment by bytestream** [comment]
@rarkins this should be transfered to `renovate` repo and marked as bug?
