### ISSUE TITLE
Dependency php/php-src has unsupported value php-7.3.20

### ISSUE THREAD

**Issue by chaospuppy** [renovatebot/config-help#780]
**What Renovate type are you using?**

Self-hosted renovate 20.25.4 container inspecting local Gitea repositories.

**Describe the bug**

Using the gitlab-releases datasourceTemplate within a regexManager, I am getting a skipped dependency.

**Relevant debug logs**

"DEBUG: Dependency php/php-src has unsupported value php-7.3.20"

"regex": [                                                                                                                    
           {                                                                                                                                            
             "packageFile": "Dockerfile",                                                                                          
             "manager": "regex",                                                                                                                                                                                
             "deps": [                                                                                                                                                 
               {                                                                                                                    
                 "depName": "php/php-src",                                                                                  
                 "currentValue": "php-7.3.20",                                                                              
                 "datasource": "github-releases",                                                                
                 "replaceString": "version=\"php-7.3.20\"",                                                                                    
                 "depIndex": 0,                                                                                    
                 "updates": [],                                                                       
                 "warnings": [],                                                                                                                                                          
                 "skipReason": "unsupported-value"
               }
             ],
             "matchStrings": ["version=\"(?<currentValue>.*?)\""]
           }
         ]

**To Reproduce**

https://repo1.dsop.io/dsop/opensource/php/php73/-/tree/7.3.20 contains the files/code involved (Self-Hosted renovatebot here as well).

**Additional context**

Commonly, github releases follow the convention of github.com/org/product/archive/[1.0.0.tar.gz|v1.0.0.tar.gz].  PHP github releases do not (appended 'php-' to <version>).

**Comment by rarkins** [comment]
The value you *extract* must be a valid version, e.g. 7.3.20. The error you see/report in this issue is expected and intended.

But once you get past that, the problem as you notice is that the releases from the php repo aren’t themselves valid versions. I don’t think we currently have a way to handle that, but if you can create a simple reproduction in a public github.com repo then it will be useful to us when we attempt to solve it

**Comment by chaospuppy** [comment]
Thanks for getting back to me on this.  If I can find the time to set up a test repo, I'll ping you here.
