### ISSUE TITLE
Run Renovate on a previously disabled repository

### ISSUE THREAD

**Issue by richardcornelissen** [renovatebot/config-help#781]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Yes, only logs are for a run setting the repository as disabled, which by now have been deleted. See below.

#### Job on dashboard

| Job ID    | Result   | Date       |
| --------- | -------- | ---------- |
| 205715219 | disabled | 3 days ago |

#### Logs (`INFO` and higher)

```
INFO: Repository started
{
  "renovateVersion": "21.33.2"
}
WARN: Unable to initialise git submodule at ios/fastlane
WARN: Unable to initialise git submodule at android/fastlane
INFO: Comment added
{
  "issueNo": 67,
  "topic": "Renovate is disabled"
}
INFO: Repository is disabled - skipping
INFO: Repository finished
{
  "durationMs": 14498
}
```

### What would you like to do?

I'm trying to configure renovate on one of our repositories which was previously disabled due to an old `renovate/configure` branch from 2 years ago with an un-merged closed PR.

As advised in the comment on the original configure PR:

- I've renamed the original `renovate/configure` PR and ensured the branch is deleted (7 days ago)
- I've manually committed a `renovate.json` config file to the base branch (5 days ago)

Issue #78 specified the disabled repo check should run daily, but so far the repository has not been checked again.

Hope you can help and thanks in advance

**Comment by rarkins** [comment]
Should now be fixed, sorry for any inconvenience caused by the wait.

**Comment by richardcornelissen** [comment]
Thanks @rarkins 👌
