### ISSUE TITLE
AutoMerge not working

### ISSUE THREAD

**Issue by Disane87** [renovatebot/config-help#784]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

My intension is to allow renovate to update the deps automatically and merge all pr into the dev branch, but this isn't working. I already checked the other opened (now closed) issues but all of them are not working.

I want to allow renovate to automerge all minor and patch version into my dev branch.

My config:

```json
{
   "extends":[
      "config:base"
   ],
   "labels":[
      "dependencies"
   ],
   "masterIssue":true,
   "masterIssueAutoclose":true,
   "patch":{
      "automerge":true
   },
   "pin":{
      "automerge":true
   },
   "minor":{
      "automerge":true
   },
   "digest":{
      "automerge":true
   },
   "baseBranches":[
      "dev"
   ]
}
```

**Comment by viceice** [comment]
logs? branch protection?

**Comment by Disane87** [comment]
> logs? branch protection?

The dev branch is not protected. Which part of the logs do you need? I didn't attached them because I don't know which part.

**Comment by viceice** [comment]
```
DEBUG: getBranchStatus(renovate/font-awesome)(branch="renovate/font-awesome")
DEBUG: branch status check result(branch="renovate/font-awesome")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/font-awesome")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
```

needs successful status checks for automerge

**Comment by viceice** [comment]
https://docs.renovatebot.com/configuration-options/#requiredstatuschecks

**Comment by rarkins** [comment]
It's pretty simple:


DEBUG: PR is configured for automerge(branch="renovate/typescript-eslint-monorepo")
DEBUG: getBranchStatus(renovate/typescript-eslint-monorepo)(branch="renovate/typescript-eslint-monorepo")
DEBUG: branch status check result(branch="renovate/typescript-eslint-monorepo")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/typescript-eslint-monorepo")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
DEBUG: PR is not ready for merge (branch status is yellow)(branch="renovate/typescript-eslint-monorepo")

**Comment by rarkins** [comment]
"requiredStatusChecks": null

**Comment by Disane87** [comment]
> "requiredStatusChecks": null

Thank you! Added this and now observe the outcome :-)

**Comment by Disane87** [comment]
It works, thank you all!
