### ISSUE TITLE
Remove appended "docker-" from docker datasource branch name

### ISSUE THREAD

**Issue by chaospuppy** [renovatebot/config-help#787]
Self-Hosted renovate 20.25.4

Renovate Open Source CLI

### Which platform are you using?

Gitea Self-Hosted

### Relevant logs

Following log snippets show creation of two PRs created for supposedly grouped resources (packagePatterns: ["fluent/fluent-bit"]). 

PR #1 (renovate/*docker-*\<groupName\> branch): 

DEBUG: 3 file(s) to commit (repository=tim/fluent-bit, branch=renovate/docker-fluent)
DEBUG: Committing files to branch renovate/docker-fluent (repository=tim/fluent-bit, branch=renovate/docker-fluent)                                             
 INFO: Branch created (repository=tim/fluent-bit, branch=renovate/docker-fluent)
       "commitHash": "4b01aeb"
DEBUG: Ensuring PR (repository=tim/fluent-bit, branch=renovate/docker-fluent)
DEBUG: There are 0 errors and 0 warnings (repository=tim/fluent-bit, branch=renovate/docker-fluent)
DEBUG: getBranchPr(renovate/docker-fluent) (repository=tim/fluent-bit, branch=renovate/docker-fluent)
DEBUG: findPr(renovate/docker-fluent, undefined, open) (repository=tim/fluent-bit, branch=renovate/docker-fluent)
DEBUG: Creating PR (repository=tim/fluent-bit, branch=renovate/docker-fluent)     
       "prTitle": "Update fluent"                                                   

PR #2 (with renovate/\<groupName\> branch): 

DEBUG: 1 file(s) to commit (repository=tim/fluent-bit, branch=renovate/fluent)
DEBUG: Committing files to branch renovate/fluent (repository=tim/fluent-bit, branch=renovate/fluent)
 INFO: Branch created (repository=tim/fluent-bit, branch=renovate/fluent)
       "commitHash": "8605282"
DEBUG: Ensuring PR (repository=tim/fluent-bit, branch=renovate/fluent)
DEBUG: There are 0 errors and 0 warnings (repository=tim/fluent-bit, branch=renovate/fluent)
DEBUG: getBranchPr(renovate/fluent) (repository=tim/fluent-bit, branch=renovate/fluent)
DEBUG: findPr(renovate/fluent, undefined, open) (repository=tim/fluent-bit, branch=renovate/fluent)
DEBUG: Creating PR (repository=tim/fluent-bit, branch=renovate/fluent)
       "prTitle": "Update dependency fluent/fluent-bit to v1.5.2"

### What would you like to do?

Have all dependencies grouped into a single PR, regardless of the datasource the dependencies are retrieved from.  This is currently prevented by the appending of "docker-" onto the branch name for PR's coming from the docker datasource.  changing managerBranchPrefix in renovate.json doesn't help. 

### Recreate the problem

Run self-hosted renovate against this repo https://github.com/chaospuppy/fluent-bit.git

**Comment by rarkins** [comment]
Try putting the managerBranchPrefix setting inside a package rule, Eg that matches datasource=docker

**Comment by chaospuppy** [comment]
That worked, thank you!  I might suggest adding the managerBranchPrefix attribute under the "packageRules" section in the configuration documentation, or making a note in the existing managerBranchPrefix documentation mentioning its usability in packageRules.  Thanks again!

**Comment by rarkins** [comment]
Pretty much every option is valid in packageRules. The subsection is only for those for which they can *only* be in rules
