### ISSUE TITLE
Renovate not generating any composer updates

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/config-help#788]
**What Renovate type are you using?**

GitHub App

**Describe the bug**

Renovate is not generating any updates, even though I know several packages have updates available.

**Relevant debug logs**

https://app.renovatebot.com/dashboard#github/momentumstudioltd/laravel-template/209809348

**To Reproduce**

No idea, I guess copy my config?

**Additional context**

For example, `laravel/framework` is currently on version `v7.22.4` but Renovate is locking my project at `v7.18.0` for no apparent reason.

**Comment by Jamesking56** [comment]
So is it best to pin dependencies now?

**Comment by rarkins** [comment]
It's always been best and our recommendation if you are writing an app. But usually keep as a range if you're publishing a library.

**Comment by Jamesking56** [comment]
So I've switched to pinning and had a pin PR generated, but now getting this:

> ### :warning: Artifact update problem
> 
> Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.
> 
> :recycle: Renovate will retry this branch, including artifacts, only when one of the following happens:
> 
>  - any of the package files in this branch needs updating, or 
>  - the branch becomes conflicted, or
>  - you check the rebase/retry checkbox if found above, or
>  - you rename this PR's title to start with "rebase!" to trigger it manually
> 
> The artifact failure details are included below:
> 
> ##### File name: composer.lock
> 
> ```
> Command failed: docker run --rm --name=renovate_composer --label=renovate_child -v "/mnt/renovate/gh/momentumstudioltd/laravel-template":"/mnt/renovate/gh/momentumstudioltd/laravel-template" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -e COMPOSER_CACHE_DIR -w "/mnt/renovate/gh/momentumstudioltd/laravel-template" renovate/composer bash -l -c "composer update barryvdh/laravel-ide-helper facade/ignition fideloper/proxy fruitcake/laravel-cors fzaninotto/faker guzzlehttp/guzzle laravel/framework laravel/tinker mockery/mockery momentumstudio/coding-standards nunomaduro/collision nunomaduro/larastan phpstan/phpstan-strict-rules phpunit/phpunit --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader"
> Loading composer repositories with package information
> 
>                                                                                                                 
>   [Composer\Downloader\TransportException]                                                                      
>   The 'https://momentum-studio.repo.repman.io/packages.json' URL could not be accessed: HTTP/1.1 403 Forbidden  
>                                                                                                                 
> 
> update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
> 
> 
> ```

Not sure why this is happening as I have verified the token is correct and I've encrypted it using https://app.renovatebot.com/encrypt

**Comment by rarkins** [comment]
How have you configured it? And how does the auth.json need to look like for Composer to use it?

**Comment by Jamesking56** [comment]
> How have you configured it? And how does the auth.json need to look like for Composer to use it?

You can see in my shareable config here the `hostRules` I've set for it:

https://github.com/renovatebot/config-help/issues/788#issuecomment-666539365 

This is how I expect the output of `auth.json` to look like:

```
{
    "bitbucket-oauth": {},
    "github-oauth": {},
    "gitlab-oauth": {},
    "gitlab-token": {},
    "http-basic": {
        "momentum-studio.repo.repman.io": {
            "username": "token",
            "password": "<raw token here>"
        }},
    "bearer": {}
}

```

**Comment by rarkins** [comment]
Is this host used only for Composer it also other types too?

**Comment by Jamesking56** [comment]
Just Composer @rarkins

**Comment by rarkins** [comment]
Added feature request: https://github.com/renovatebot/renovate/issues/6901
