### ISSUE TITLE
question: difference between rangeStrategy=replace and rangeStrategy=update-lockfile on in-range updates

### ISSUE THREAD

**Issue by casca** [renovatebot/config-help#789]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

I've read the [Configuration Options documentation](https://docs.renovatebot.com/configuration-options/#rangestrategy) and I don't understand what the difference is between `rangeStrategy=replace` and `rangeStrategy=update-lockfile` when in-range updates are available (assuming I'm using npm/yarn). Is `replace` going to ignore in-range updates?

**Comment by rarkins** [comment]
Replace will ignore in-range updates

**Comment by casca** [comment]
Thank you for the information.
