### ISSUE TITLE
Re-using `groupName`

### ISSUE THREAD

**Issue by hbetts** [renovatebot/config-help#79]
In a hypothetical mono-repository project I have four packages:
- `package-a`
- `package-b`
- `package-c`
- `package.d`

They all share a common configuration:

```json
{
  "extends": [
    "@hbetts/renovate-config"
  ],
  "automerge": true,
  "packageRules": [
    {
      "paths": [
        "packages/package-c",
        "packages/package-d"
      ],
      "automerge": false,
      "groupName": "no-automerge-{{groupName}}"
    }
  ]
}
```

Each package has a single dependency on ESLint version 4, which has been superseded by version 5.

My goal is for Renovate to create a single branch for ESLint version 5 for `package-a` and `package-b`, and then a second branch for ESLint version 5 for `package-c` and `package-d`.

Furthermore, I would like Renovate to automatically merge the first branch if all status checks pass, while the second branch should be filed as a pull request, even if status checks pass.

Lastly, I would like to use the name of the upgraded package in the `groupName` field, assuming this is the appropriate approach to take, while also using the `groupName` field to keep the branches between auto-mergeable projects, and those that aren't auto-merged, separate.

**Comment by hbetts** [comment]
The reason I am separating out packages within the mono-repository is because I want to adopt the practice of auto-merging all upgrades that pass status checks. However, not all packages within my mono-repository (or a few others that I help with) have sufficient tests to offer confidence that an upgrade can be auto-merged.

Therefore, I am working on creating a configuration that can allow me to disable auto-merging for all packages at first, and then, as I add unit tests, and increase my confidence in a package's test suite, I can remove the package from the `paths` list, thereby turning on auto-merging.

**Comment by hbetts** [comment]
As an example, I put together the following repository - https://github.com/hbetts/test/pulls

**Comment by rarkins** [comment]
Can you describe also what branch names you would expect and what about other dependencies in the same repo?

**Comment by hbetts** [comment]
I would expect to see two branches when ESLint is the only dependency:
- `renovate/eslint-5.x`
- `renovate/no-automerge-eslint-5.x`

If there was another outdated package, for example `got`, then I might see:
- `renovate/eslint-5.x`
- `renovate/no-automerge-eslint-5.x`
- `renovate/got-9.x`
- `renovate/no-automerge-got-9.x`

**Comment by hbetts** [comment]
@rarkins I switched to `branchPrefix`, and I am now seeing a `renovate/no-automerge-eslint-5.x` branch. 

So far looks like exactly what I was looking for! 👍 

Thank you @rarkins!
