### ISSUE TITLE
Different configuration for different packages in my monorepo

### ISSUE THREAD

**Issue by roni-frantchi** [renovatebot/config-help#790]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

Is it possible to have different configuration for different packages in my monorepo (driven by yarn workspaces)?  
As in - I would like to to have automerge turned on for any minor dependency bump on any of my monorepo package dependencies (`service-a`, `service-b`), but would like any of my `frontend` package dependencies to be automerged for patch versions only.

**Comment by rarkins** [comment]
Look at packageRules.paths. Lots of packageRules examples in closed issues in this repo and a few probably include paths

**Comment by roni-frantchi** [comment]
Thanks @rarkins - doesn't `paths` of `packageRules` intended for the **target** dependency rather than that of the dependent source?..

**Comment by rarkins** [comment]
Can you elaborate your earlier question with details/directory structure?

**Comment by roni-frantchi** [comment]
Sure.  
So we have the following yarn workspaces monorepo structure:
```
|+service-a
  |-package.json  
|+service-b
  |-package.json  
.
.
.
|+service-n
  |-package.json  
|-package.json
|-yarn.lock
```

What I'd like to achieve, is to allow automerge for minor semver bumps on any dependencies of all services in the entire monorepo.  
**But**, for a particular `service-x`, I'd like to only automerge patch semver bumps.  

So if `service-a`'s package.json looks like:
```
"dependencies": {
  "foo": "2.0.0"
}
```
And `service-x`'s package.json looks like:
```
"dependencies": {
  "bar": "1.0.0"
}
```
It will automerge an upgrade of the `foo` dependency to `2.1.0` as it's required by `service-a` which allow automerge for minors.  
But for a release of `bar` of version 1.1, it will **not** automerge the pr, because `service-x` does not allow to automerge upgrades of minor versions, only patch.

**Comment by viceice** [comment]
@roni-frantchi [paths](https://docs.renovatebot.com/configuration-options/#paths) are for matching a packageRule against paths in your repo.

**Comment by rarkins** [comment]
Rule 1: set automerge=true for minor updates for first paths

Rule 2: set separateMinorPatch=true for second paths

Rule 3: set automerge=true for patch updates for second paths

**Comment by roni-frantchi** [comment]
> @roni-frantchi paths are for matching a packageRule against paths in your repo.

Did not realize that 🤕 

Thanks guys. Much appreciated.
