### ISSUE TITLE
renovate for gitlab-runner docker

### ISSUE THREAD

**Issue by zeug-it** [renovatebot/config-help#797]
**What Renovate type are you using?**

self-hosted

**Describe the bug**

I try to renovate a dockerfile for gitlab runner images gitlab/gitlab-runner:ubuntu-v13.2.1

But renovate does not find a later version

**Comment by viceice** [comment]
you need a packageRule:

```json
      {
            "packageNames": [
                "gitlab/gitlab-runner"
            ],
            "versionScheme": "regex:^(?<compatibility>.*)-v(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)?$"
      }
        
```

**Comment by zeug-it** [comment]
Works like a charm - many thanks
