### ISSUE TITLE
Configuration Update Kill Renovate

### ISSUE THREAD

**Issue by aray12** [renovatebot/config-help#80]
I added renovate to our repo and it was working great but then I wanted to update the configuration to add labels, etc. After I did that renovate stopped working. Currently PR's aren't updating. I didn't follow the pattern initially to include `renovate` in the PR or branch name, but now I am trying to trick it with those techniques and I am not getting the configuration validation check

Do I need to completely reset?

**Comment by rarkins** [comment]
Try logging in to https://renovatebot.com/dashboard and see what the logs there show

**Comment by aray12** [comment]
Got it. Thanks for the quick help!!
