### ISSUE TITLE
Why having depTypeList is not enough to stop pinning node in engines?

### ISSUE THREAD

**Issue by moroshko** [renovatebot/config-help#800]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub.com

### What would you like to do?

I'd like to stop getting PRs like [this one](https://github.com/moroshko/react-scanner/pull/7).
I don't want to pin or upgrade engines.

I thought that my config would do it because it has `"depTypeList": ["dependencies", "devDependencies"]`, but apparently it's not enough. What am I missing?

```
{
  "extends": ["config:base"],
  "schedule": "every weekend",
  "rangeStrategy": "pin",
  "packageRules": [
    {
      "packagePatterns": ["*"],
      "depTypeList": ["dependencies", "devDependencies"],
      "minor": {
        "groupName": "all non-major dependencies",
        "groupSlug": "all-minor-patch"
      }
    }
  ]
}
```

**Comment by rarkins** [comment]
depTypeList is for matching. It's not an instruction. We are about to rename it to matchDepTypes for clarity. 

Your rangeStrategy config at the top level applies to every dependency. Put it inside packageRulea if you want it to apply to only a subset of extracted packages.

**Comment by moroshko** [comment]
@rarkins Could you clarify the difference between matching and instruction?

Should this config do it?
```
{
  "extends": ["config:base"],
  "schedule": "every weekend",
  "packageRules": [
    {
      "rangeStrategy": "pin",
      "packagePatterns": ["*"],
      "depTypeList": ["dependencies", "devDependencies"],
      "minor": {
        "groupName": "all non-major dependencies",
        "groupSlug": "all-minor-patch"
      }
    }
  ]
}
```

**Comment by rarkins** [comment]
The `packagePatterns` rule is unnecessary because it will match all packages by default anyway. Also, I prefer to write the rules with the matchers first and instructions second, e.g.

```json
{
  "extends": ["config:base"],
  "schedule": "every weekend",
  "packageRules": [
    {
      "depTypeList": ["dependencies", "devDependencies"],
      "updateTypes": ["minor"],
      "rangeStrategy": "pin",
      "groupName": "all non-major dependencies",
      "groupSlug": "all-minor-patch"
    }
  ]
}
```

I also flattened the `minor` object as it's much more understandable to use `updateTypes`.

**Comment by moroshko** [comment]
I see what you did here. This would update only the minor updates, right?

My intent was to separate major updates from minor+patch updates.

Is this the most idiomatic way to achieve this?

```
{
  "extends": ["config:base"],
  "schedule": "every weekend",
  "packageRules": [
    {
      "depTypeList": ["dependencies", "devDependencies"],
      "updateTypes": ["minor", "patch"],
      "rangeStrategy": "pin",
      "groupName": "minor and patch",
    },
    {
      "depTypeList": ["dependencies", "devDependencies"],
      "updateTypes": ["major"],
      "rangeStrategy": "pin",
      "groupName": "major",
    }
  ]
}
```

**Comment by rarkins** [comment]
Yes, although I don't recommend grouping major updates together because of their tendency to be breaking

**Comment by moroshko** [comment]
What would you recommend doing with major updates?

If all I do is this, I won't get major updates, right? I'd like to get notified though about major updates.
```
{
  "extends": ["config:base"],
  "schedule": "every weekend",
  "packageRules": [
    {
      "depTypeList": ["dependencies", "devDependencies"],
      "updateTypes": ["minor", "patch"],
      "rangeStrategy": "pin",
      "groupName": "minor and patch",
    }
  ]
}
```

**Comment by rarkins** [comment]
With the above config, you will get major updates on weekends, one PR per dependency (unless they already fall into our default groupings inherited from `config:base`).

My advice:
1. Don't group them, because of the high chance they each have breaking changes and you don't want to fix them all in one PR
2. Use the Dependency Dashboard Approval feature for major. i.e. you have an issue you can view all the outstanding major updates at any time, and when you're ready to deal with them you tick the checkbox the PR is created

**Comment by moroshko** [comment]
Awesome, thanks a lot for your help and patience!
