### ISSUE TITLE
How to use matchStrings with obscure dockerhub tag strategies?

### ISSUE THREAD

**Issue by tobybellwood** [renovatebot/config-help#801]
### Which Renovate are you using?
WhiteSource Renovate App

### Which platform are you using?
GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

e.g. https://app.renovatebot.com/dashboard#github/tobybellwood/SampleFiles/214090069

### What would you like to do?

We publish images to DockerHub in the form `amazeeio/php:7.3-cli-drupal-v1.8.1` (apologies for the semver :scream: ...)

If we schedule automated updates, we get suggested to use `amazeeio/php:7.4-cli-drupal-v1.8.1` (instead of `amazeeio/php:7.3-cli-drupal-v1.8.2` - an upgrade to PHP isn't what we wanted, just the latest image bump...

Knowing it's completely our fauly, I've configured a RegexManager
```
  "regexManagers": [
    {
      "fileMatch": ["(^|/)Dockerfile.php$"],
      "matchStrings": ["FROM (?<depName>.*?):[0-9,.]*-(cli-drupal|cli|fpm)-v(?<currentValue>.*)"],
      "datasourceTemplate": "docker",
      "versioningTemplate": "semver"
    }
```

But whilst the bot finds the currentValue ok, it can't iterate it (presumably because of all the gubbins in between depName and currentValue.  What is the best way to tell renovatebot to keep this stuff the same, and just look for the nextValue - should it all fold into the depName?  Should I group the "prefix" in regex and call it something specific?

I'm already looking at ways to create new naming schemes that aren't so :angry: - but would appreciate any steer you may have?

```
    "regex": [
      {
        "deps": [
          {
            "depName": "amazeeio/php",
            "updates": [],
            "depIndex": 0,
            "warnings": [],
            "sourceUrl": null,
            "datasource": "docker",
            "versioning": "semver",
            "currentValue": "1.8.1",
            "replaceString": "FROM amazeeio/php:7.3-fpm-v1.8.1",
            "dockerRegistry": "https://index.docker.io",
            "dockerRepository": "amazeeio/php"
          }
        ],
        "manager": "regex",
        "packageFile": "Dockerfile.php",
        "matchStrings": [
          "FROM (?.*?):[0-9,.]*-(cli-drupal|cli|fpm)-v(?.*)"
        ]
      }
    ],
```

**Comment by rarkins** [comment]
You need to capture the entire tag as currentValue and then also use a regex versioning pattern to account for the complicated structure. Check out the docs for versioning as there's an example of regex there.

**Comment by tobybellwood** [comment]
Nice!!

Hadn't considered that as an option when reading the docs - I don't even need the RegexManager as I can do it all from a PackageRule!

:partying_face: :tada: :fireworks: 

```
  "packageRules": [
    {
      "datasources": ["docker"],
      "packageNames": ["amazeeio/php"],
      "versioning": "regex:^(?<compatibility>.*)-v(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?$"
    },
```
