### ISSUE TITLE
Renovatebot opening and closing same PR multiple times a day

### ISSUE THREAD

**Issue by jongrim** [renovatebot/config-help#803]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

Yes - I did not find any logs that say _why_ this is happening

### What would you like to do?

Renovatebot is opening valid PRs and then autocloses them less than an hour later. Yesterday, it opened a PR to update a Node version in a `.nvmrc` file 4 times and closed it each time. From some of my searching, I've found indications that [autoclosing is a config driven event](https://github.com/renovatebot/renovate/issues/2848#issuecomment-439852041), but I cannot identify anything in our configuration that should lead to these PRs being closed.

Our configuration:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "prHourlyLimit": 2,
  "prConcurrentLimit": 10,
  "labels": ["renovatebot"],
  "vulnerabilityAlerts": {
    "labels": ["security"]
  },
  "ignoreDeps": [
    "github.com/dgryski/go-rendezvous",
    "golang.org/x/net",
    "golang.org/x/sys",
    "apollo-boost",
    "apollo-client"
  ],
  "ignorePaths": ["blackhat"],
  "schedule": ["after 7pm and before 5:00am"],
  "timezone": "America/New_York",
  "packageRules": [
    {
      "packageNames": ["aws-sdk"],
      "extends": ["schedule:monthly"]
    },
    {
      "packagePatterns": ["^@types"],
      "groupName": "types packages",
      "extends": ["schedule:monthly"]
    }
  ]
}
```

Is there any guidance that can be given to help determine why these PRs are being created and closed so often?

**Comment by rarkins** [comment]
This is most often caused by external hosts that are available then not available, then available, etc. Each time they're not available, Renovate interprets that as no updates available, so no branch necessary, and deletes it (closing the associated PR).

For `.nvmrc` I believe we look that up based on github.com tags, so I'm wondering if you've configured a Personal Access Token for github.com so that you don't hit rate limits?

**Comment by jongrim** [comment]
ah - I wasn't sure where it was checking for node versions. We actually haven't set a github.com token yet so this sounds plausible. I'll get our team to set one and see if that resolves the issue. Thanks!

**Comment by rarkins** [comment]
https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#githubcom-token-for-release-notes

**Comment by jongrim** [comment]
Thanks! I'm still waiting on our ops team to get the github token added, but this seems very likely the issue, so I'm going to close the issue. I can always reopen later if we can't solve it. Thanks again!

**Comment by viceice** [comment]
@rarkins maybe we can log a warning when we get rate limited by GitHub and have no token?

**Comment by rarkins** [comment]
I forget exactly which error message they reject with though, and hopefully it's consistent.
