### ISSUE TITLE
Nuget prerelease packages

### ISSUE THREAD

**Issue by brechtvhb** [renovatebot/config-help#804]
docker (latest)

Renovate Open Source CLI

### Which platform are you using?

Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

              {
                 "depType": "nuget",
                 "depName": "xxx.Locations.Events.Data",
                 "currentValue": "1.1.0-dev0009",
                 "datasource": "nuget",
                 "depIndex": 6,
                 "updates": [],
                 "warnings": [
                   {
                     "depName": "xxx.Locations.Events.Data",
                     "message": "Failed to look up dependency xxx.Locations.Events.Data"
                   }
                 ]
               }

### What would you like to do?

Renovate is not finding my prerelease nuget packages, see the error above.
I would like to update my prerelease packages if there are any. I do not want to automaticly update from release to pre release packages. For example from 1.8.3 to 1.9.0-dev0009.

**Comment by rarkins** [comment]
The warning indicates they completely failed to look up and not that there's anything specific to prevent-releases. Where are the dependencies hosted and is authentication needed? Do other dependency lookups work?

**Comment by brechtvhb** [comment]
Yes, other non pre-release packages work. Both are hosted on (the same) azure devops artifact.

Here's an example in the logs

              {
                 "depType": "nuget",
                 "depName": "xxx.ServiceDiscovery.Events",
                 "currentValue": "1.4.0",
                 "datasource": "nuget",
                 "depIndex": 21,
                 "updates": [],
                 "warnings": []
               },

**Comment by brechtvhb** [comment]
Could it be that my configuration is causing the issue?

      {
        "packagePatterns": [ "SI.*" ],
        "updateTypes": ["patch", "minor"],
		"versioning": "nuget",		
        "groupName": "Microservices"
      },	


Do I have to specify another update type than patch and minor to get prerelases to work?

**Comment by rarkins** [comment]
Try removing all config and then capturing one run at debug level logging

**Comment by brechtvhb** [comment]
Removing all config did not help. I mailed you the logs with configuration enabled.

**Comment by brechtvhb** [comment]
This is probably due to limitations in Nuget / .NET tooling. It seems that pre releases are not supported yet in command line scripts. Fix imminent though.

see:
https://github.com/dotnet/sdk/issues/12131
https://github.com/NuGet/Home/issues/912
https://github.com/dotnet/sdk/issues/9037

**Comment by rarkins** [comment]
@viceice would the changes to our nuget datasource have any impact on this?

**Comment by viceice** [comment]
@rarkins I don't think so. Shouldn't change anything.

@brechtvhb can you please share your configs?  Where are you hosting your prerelease packages?

**Comment by brechtvhb** [comment]
@viceice I emailed you the config file.
Nuget packages are being hosted on azure devops artifacts.

**Comment by viceice** [comment]
reduced config
```json
{
    "platform": "azure",
    "endpoint": "https://dev.azure.com/**corp**/",
    "token": "***",
    "repositories": ["Applications/SI.XxxxXxx", "Applications/Progressive.YyyyYyy"],
    "gitAuthor": "RenovateBot <renovate@**corp**.com>",
    "onboarding": true,
    "dryRun": true,
    "logLevel": "debug",
    "branchPrefix": "feature/renovate-",
    "packageRules": [
       {
        "packagePatterns": [ "Progressive.*" ],
        "updateTypes": ["patch", "minor"],
        "versioning": "nuget",
        "groupName": "Common"
      },
      {
        "packagePatterns": [ "SI.*" ],
        "updateTypes": ["patch", "minor"],
        "versioning": "nuget",
        "groupName": "Microservices"
      },
      {
        "packagePatterns": [ "Microsoft.*" ],
        "updateTypes": ["patch", "minor"],
        "groupName": "Microsoft"
      },
      {
        "depTypeList": [
          "devDependencies"
        ],
        "enabled": false
      },
      {
        "paths": ["package.json"],
        "updateTypes": [],
        "groupName": "frontend",
        "enabled": false
      },
      {
        "datasources": [
          "docker"
        ],
        "packagePatterns": [
          "^mcr.microsoft.com/dotnet/core/"
        ],
        "groupName": ".NET Core Docker containers"
      }
    ],
    "nuget": {
      "registryUrls": [
        "https://pkgs.dev.azure.com/**corp**/_packaging/**corp**/nuget/v3/index.json",
        "https://api.nuget.org/v3/index.json"
      ]
    },
    "hostRules": [
      {
        "hostType": "nuget",
        "endpoint": "https://pkgs.dev.azure.com/**corp**",
        "username": "",
        "password": "***"
      },
      {
        "domainName": "github.com",
        "token": "***"
      } 
    ],
    "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}
```

**Comment by viceice** [comment]
@brechtvhb Do you have any additional config in the repos? By default renovate would never propose an update from a stable to a unstable release

**Comment by viceice** [comment]
here we are filtering unstable:
https://github.com/renovatebot/renovate/blob/53ca91301f6a36c0c87e7d6b06b1bd8c9ec1b283/lib/workers/repository/process/lookup/filter.ts#L140

you can use [`ignoreUnstable`](https://docs.renovatebot.com/configuration-options/#ignoreunstable) in your settings to allow prerelease updates
https://github.com/renovatebot/renovate/blob/53ca91301f6a36c0c87e7d6b06b1bd8c9ec1b283/lib/workers/repository/process/lookup/filter.ts#L123

**Comment by brechtvhb** [comment]
No I don't have any extra config in the repos.

I do not wish to update from a stable to an unstable release. But I would want to update my prereleases if my project is using an older prerelease package.
Eg: from  version 1.2.0-dev0002 to 1.2.0-dev0009.

what  I see in the logs is that renovate detects stable releases but doesn't find prereleases.

               {
                 "depType": "nuget",
                 "depName": "xxxx",
                 "currentValue": "2.3.0",
                 "datasource": "nuget",
                 "depIndex": 14,
                 "updates": [],
                 "warnings": []
               },


               {
                 "depType": "nuget",
                 "depName": "xxxx,
                 "currentValue": "1.2.0-dev0007",
                 "datasource": "nuget",
                 "depIndex": 16,
                 "updates": [],
                 "warnings": [
                   {
                     "depName": "xxxx",
                     "message": "Failed to look up dependency xxxx"
                   }
                 ]

But as mentioned in a previous comment it could be that the root cause of the problem is in the nuget / .net tooling.
(https://github.com/renovatebot/config-help/issues/804#issuecomment-673048730)

**Comment by rarkins** [comment]
Renovate's default functionality should be that unstable -> unstable updates are raised if both share the same major.minor.patch (e.g. as in your text above).

"Failed to look up dependency xxxx" has nothing to do with that though - it indicates that Renovate literally failed to look up any versions at all, or had an exception while doing so

**Comment by viceice** [comment]
I have an idea now, renovate doesn't use any dotnet tooling for finding versions. I think we do some mistake on the api call, so we simply don't find any prerelease on azure.

I think this is related to https://github.com/renovatebot/renovate/pull/6943

**Comment by brechtvhb** [comment]
Problem got fixed by the PR you mentioned renovatebot/renovate#6943
