### ISSUE TITLE
Renovate for Node Repo

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#805]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

We are planning to use renovate for node application in our organization. We would like to know what are the prerequisite for npm application? will renovate work for npm & yarn?  from which version it will support? What are the other prerequisite?

**Comment by rarkins** [comment]
If you're running the CLI, you'll need to make sure you already have the versions of `npm` and `yarn` you need pre-installed. Renovate does not bundle them with its distribution.

**Comment by sakshan** [comment]
Thanks @rarkins.  We have few js repos we wanted to use renovate for those to check latest dependency & raise PR? Before that we wanted to know the node repo we have is supported by renovate? so what version of npm ,yarn and node js we should maintain?  what are the prerequisite we should have in our application?

**Comment by rarkins** [comment]
You should use the versions of tools that you regularly use in your repo
