### ISSUE TITLE
Declining renovate/config PR

### ISSUE THREAD

**Issue by Mvbraathen** [renovatebot/config-help#806]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Cloud

### What would you like to do?
I have a renovate/config PR that I made package bumps in and now the pr is stale and won't update. I am just wondering if I can use the rename and decline technique described in the docs to receive a new config pr from renovate-bot?

**Comment by rarkins** [comment]
Yes, rename then close the onboarding PR, also making sure to delete the branch.

**Comment by Mvbraathen** [comment]
Thank you for a very quick response! 🥇
