### ISSUE TITLE
[Q] Disable upgrading node version

### ISSUE THREAD

**Issue by ravangen** [renovatebot/config-help#81]
I am trying to configure renovate to _not_ update the version of `node` defined in the `engines` section of `package.json`. I am running code on AWS Lambda which [supports specific versions of Node.js](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

I've tried the [`node`](https://renovatebot.com/docs/configuration-options/#node) configuration option without much luck, perhaps there is a different setting to use?

`renovate.json`:
```javascript
{
  "extends": [
    "config:base",
    ":rebaseStalePrs",
    ":pinDigestsDisabled",
    "schedule:earlyMondays",
    "group:allNonMajor"
  ],
  "node": {
    "enabled": false
  }
}

```

`package.json`:
```javascript
{
  ...
  "engines": {
    "node": "8.10.0",
    "npm": ">=5.6.0"
  }
}
```

Thanks

**Comment by ravangen** [comment]
Thanks! I'll give that a go.

In my case I use a "package manager" (`nvm`) and have `engines` defined, so I'll keep both sections.

**Comment by bahmutov** [comment]
Hmm, I am trying to do the same thing: pin and keep updating my Node dependencies in `package.json` files, but keep range in `engines`

```
  {
  "engines": {
    "node": ">=4.0.0"
  }
}
```
I have set the [renovate.json](https://github.com/bahmutov/test-renovate-monorepo/blob/master/renovate.json)  to

```json
{
  "extends": [
    "config:base"
  ],
  "automerge": false,
  "rangeStrategy": "pin",
  "packageRules": [
    {
      "packageNames": [
        "node"
      ],
      "enabled": false
    }
  ]
}
```
and now no PRs from RenovateBot to https://github.com/bahmutov/test-renovate-monorepo/pulls :(

Would be nice to disable `engines node` updates since this minimum version is for end users and not the latest Node required

**Comment by ravangen** [comment]
@bahmutov I would suggest opening a separate question as it is different enough from the original. You can still reference this one, but I fear your question may be lost or not found by the next person.

**Comment by rarkins** [comment]
@bahmutov looks like your repo was just rate limited for previous hour, e.g.

```
{"branch":"renovate/ramda-0.x","dependencies":["ramda"],"msg":"Reached PR creation limit - skipping branch creation","time":"2018-12-27T19:38:52.557Z"}
```

**Comment by rarkins** [comment]
Also some are blocked by previous PRs that you closed unmerged. You can set `"masterIssue": true` if you want greater visibility in a repo

**Comment by bahmutov** [comment]
Nice! I see updates now for dependencies, while `engines: node` stays the same as range, thank you @rarkins
