### ISSUE TITLE
Can't ignore dependency

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#811]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

Ignore a dependency when onboarding a repo in Renovate.

 I've changed the configuration file to include

```
  "ignoreDeps": [
    "docker.elastic.co/elasticsearch/elasticsearch",
    "@​elastic/elasticsearch"
  ],
```

The onboarding PR correctly removed the PR to bump the first in the PR description but it still shows the second:

![image](https://user-images.githubusercontent.com/20181/90419049-44227500-e0b6-11ea-90f8-5e643b16a0e5.png)

**Comment by rarkins** [comment]
Has Renovate run since you updated the config? (check the dashboard). Otherwise, please reproduce in a public repo so I can take a look

**Comment by simoneb** [comment]
Yes it has because the bump to the first dependency `"docker.elastic.co/elasticsearch/elasticsearch"` has been removed from the onboarding PR description, but the second is still there.

**Comment by simoneb** [comment]
@rarkins job id is #217911402 if that's of any help
