### ISSUE TITLE
registryUrls don't work for packagist/composer manager

### ISSUE THREAD

**Issue by maksimru** [renovatebot/config-help#812]
**What Renovate type are you using?**

Self-hosted renovate, github platform, packagist/composer manager

**Describe the bug**

1) RegistryUrls simply don't work for packagist/composer. Many large organizations don't use repositories section in composer.json file, instead of it they are using global composer config.json (Windows: %userprofile%\.composer\config.json
Linux: ~/.composer/config.json). See jfrog artifactory docs https://www.jfrog.com/confluence/display/JFROG/PHP+Composer+Repositories (Replacing the Default Repository)
2) We don't have an option to disable packagist using packageRules in self-hosted solutions, it is important because large organizations are enforced to use their own registries, packagist can be restricted / unavailable. Right now it can be achieved only by adding packagist=>false to repositories section of composer.json. See an example of repository https://github.com/maksimru/composer-private-repository-test

**Relevant debug logs**

```shell
DEBUG: http statistics (repository=maksimru/composer-private-repository-test)
       "hostStats": [
         "api.github.com, 10 requests, 487ms average",
         "packagist.org, 1 request, 293ms average"
       ],
```

No requests to registry https://lazyrepository.imfast.io/composer/demo, it doesn't use it at all

**To Reproduce**

Problem can be reproduced very easily  using following config, targeting to https://github.com/maksimru/composer-private-repository-test

```js
module.exports = {
  baseBranches: ['master'],
  enabledManagers: ["composer", "npm"],
  branchPrefix: 'deps/',
  semanticCommits: true,
  dryRun: true,
  gitAuthor: 'Renovate Bot <renovate-bot@route4me.com>',
  logLevel: 'debug',
  onboarding: false,
  requireConfig: false,
  platform: 'github',
  includeForks: false,
  rangeStrategy: 'bump',
  packageRules: [
    {
      "datasources": ["packagist"],
      "updateTypes": ["patch", "minor"],
      "registryUrls": [
        "https://lazyrepository.imfast.io/composer/demo"
      ]
    }
  ]
};
```

**Additional context**

Issue can be solved with https://github.com/renovatebot/renovate/pull/6992

Recommendations and ideas are welcome

**Comment by viceice** [comment]
We are in progress of rename the matchers to be more clearly, see https://github.com/renovatebot/renovate/pull/6939

**Comment by rarkins** [comment]
The final working *rules* are pretty logical IMO. i.e.

- For datasource packagist, use registryUrls X
- For datasource packagist, disable major updates

**Comment by maksimru** [comment]
@rarkins @viceice few more questions, in case of existing composer.lock file it is using composer update for lock file generation
1) does it write registryUrls to global config.json to give it access to external repositories
2) does it disable packagist via config.json in case if we have hostRules with denied packagist
3) does it respect configured updateTypes, i mean does it update lock file to exact same version as found by renovatebot?

**Comment by rarkins** [comment]
1. No, there is no packageRules -> config.json link. We generally really prefer to avoid writing files out if we can too. Env or CLI params are much preferred where possible
2. No, there is no hostRules -> config.json link.
3. Renovate first updates the `composer.json` and then uses `composer update` to update the `composer.lock`. You can see how the composer command is created here: https://github.com/renovatebot/renovate/blob/cc8652e38c7f62de53ad83d5f66cc5e67e44e8f7/lib/manager/composer/artifacts.ts#L118-L132

**Comment by maksimru** [comment]
I think I can make PR for first 2 issues, composer has very limited ENV vars support. If we want to be able to update composer.lock with private registries we have to add them to global config.json, I don't think we have any other choice

**Comment by rarkins** [comment]
As you're running self-hosted, you can probably add your own `config.json` to the server/container that you run on as a workaround. Can you first create two *issues* for each of the problems in the main repo, and start the PRs once we agree on the best implementation approach. I'll close this issue now.

**Comment by rarkins** [comment]
BTW I'm curious why these settings can't be added to each repo's `composer.json` though, if they don't contain credentials?
