### ISSUE TITLE
Manually force start depcheck for a certain repository

### ISSUE THREAD

**Issue by lucaschen** [renovatebot/config-help#814]
**What would you like Renovate to be able to do?**

Allow the developer to manually force Renovate to re-check dependencies. Currently the wait time for our use cases is approximately 30 minutes; it would be good to be able to manually start that depcheck process once we have published a package.

**Comment by lucaschen** [comment]
Apologies, I don't see a way to trigger a job from the dashboard – is there something here that I'm missing?

**Comment by viceice** [comment]
What renovate type are you using?

**Comment by lucaschen** [comment]
Apologies – Renovate with GitHub.

**Comment by rarkins** [comment]
It's at the bottom: 
![image](https://user-images.githubusercontent.com/6311784/90592098-0ff9a200-e1e5-11ea-8a1d-171a14280d5d.png)

**Comment by lucaschen** [comment]
Yep, I saw that 🙂

Is there any way I can trigger it for a repository without having to resort to using an open PR?

**Comment by viceice** [comment]
this should also be available on dependencyDashboard

**Comment by rarkins** [comment]
The screenshot is actually from the dashboard. Example: https://github.com/renovatebot/renovate/issues/2958

**Comment by lucaschen** [comment]
Apologies, I was referring to this dashboard here: https://app.renovatebot.com/dashboard

The reason I would prefer this is so that I can trigger a re-check for any repository in which I've enabled Renovate, without necessarily having to re-check an open PR (which might not exist).

**Comment by rarkins** [comment]
It's not possible today, but you can enable dependencyDashboard in your config to access the capability from an in-repo issue

**Comment by lucaschen** [comment]
Thanks @rarkins. I'm currently getting this:

![image](https://user-images.githubusercontent.com/2109121/90717022-c9459e00-e2f1-11ea-833e-4adef8af7f60.png)

Is it possible to show that checkbox even when no updates appear to be pending?

**Comment by rarkins** [comment]
@lucaschen yes, please create an issue for that in the main repo and we'll try to get it done soon
