### ISSUE TITLE
Configure update frequency / scheduling for a specific Maven dependency

### ISSUE THREAD

**Issue by monperrus** [renovatebot/config-help#815]
One Java library is pushing new versions very often, and this triggers too many Renovate PRs.

For this specific dependency (`org.mockito:mockito-core`) only, we would like to have a PR at most once a week.

I don't find the information in https://docs.renovatebot.com/presets-schedule/

How to do this?

Related to #551 and #552.

**Comment by viceice** [comment]
https://docs.renovatebot.com/configuration-options/#packagerules
![image](https://user-images.githubusercontent.com/1798109/90596797-0fb2d400-e1f0-11ea-8e30-8fcb2e5145f1.png)

**Comment by rarkins** [comment]
This rule means that Renovate will only create PRs for it during that scheduled time. Currently, Renovate will still *update* the existing PR at any time if it's still open and a newer version is released. But once you merge it, you won't get a new PR until the next scheduled time.

**Comment by viceice** [comment]
Right, an other alternative is to use `dependencyDashboardApproval`.

https://docs.renovatebot.com/configuration-options/#dependencydashboardapproval

**Comment by monperrus** [comment]
Thanks for the fast answer.

Is this configuration correct: 
https://github.com/renovatebot/renovate/pull/7026?

**Comment by rarkins** [comment]
Yes, that's right

**Comment by monperrus** [comment]
Perfect, thanks.

Then we would have something like this: https://github.com/INRIA/spoon/pull/3539

```diff
 {
   "extends": [
     "config:base"
  ],
+  "packageRules": [
+    {
+      "packageNames": ["org.mockito:mockito-core"],
+      "schedule": ["weekly"]
+    }
+   ]
 }
```

Any way to validate it works before committing to master?

**Comment by rarkins** [comment]
Not really anything foolproof. In Renovate we use `dependencyDashboard` and `dependencyDashboardApproval` (selectively) in order to see a full list of PRs including those pending scheduling or approval. But you'd need to configure that *first* before then adding in your packageRules to confirm.

**Comment by monperrus** [comment]
OK, thanks.

**Comment by monperrus** [comment]
JSON config was incorrect :) we just received

> There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.
>
> File: renovate.json
> Error type: The renovate configuration file contains some invalid settings
> Message: Invalid packageRules[0].schedule: Invalid schedule: Failed to parse "weekly"``

Trying with `schedule:weekly`

**Comment by rarkins** [comment]
Sorry! Please check out the documentation for "schedule" on docs.renovatebot.com for some examples. "schedule:weekly" is a preset name that needs to be within an "extends" array

**Comment by monperrus** [comment]
Got it working with `"schedule": ["on monday"]`

**Comment by monperrus** [comment]
It would be great to do some kind of schema validation inside PRs. Hotfixes on master are not really comfortable :)

Thanks for your help Rhys

**Comment by viceice** [comment]
you can run the config validator from your ci scripts

```sh
npx -p renovate renovate-config-validator
```

**Comment by rarkins** [comment]
We do have a JSON schema too however it can't capture/validate the "free text" nature of the parsing library we lean on.

**Comment by monperrus** [comment]
> npx -p renovate renovate-config-validator

Nice, thanks!

**Comment by monperrus** [comment]
Works perfectly now, and I love the " :date: date Schedule: "on monday" (UTC)." in the PR description, see https://github.com/INRIA/spoon/pull/3543

Thanks all for your help.
