### ISSUE TITLE
When renovate-config-validator is configured with travis, it fails because of one NPM env variable.

### ISSUE THREAD

**Issue by nimmoadam** [renovatebot/config-help#817]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

**travis logs**

```
The previous command failed, possibly due to a malformed secure environment variable.
177For more information, see https://docs.travis-ci.com/user/encryption-keys.
178$ export TRAVIS_SIGNED_JWT=[secure]
179
180Setting environment variables from .travis.yml
181$ export NPM_TOKEN=${NPM_AUTH}
182
183Error: Failed to replace env in config: ${process.env.NPM_TOKEN}
.
.
Error: npm.load() required
199    at Object.get (/home/travis/.nvm/versions/node/v12.13.1/lib/node_modules/npm/lib/npm.js:59:13)
200    at process.errorHandler (/home/travis/.nvm/versions/node/v12.13.1/lib/node_modules/npm/lib/utils/error-handler.js:205:32)
201    at process.emit (events.js:210:5)
202    at process._fatalException (internal/process/execution.js:150:25)
203nvm is not compatible with the npm config "prefix" option: currently set to ""
204Run `nvm use --delete-prefix v12.13.1 --silent` to unset it.
```

### What would you like to do?

Trying to add "**renovate-config-validator**" for each PR created. To ensure, there are no issues with the configuration when a new PR is created. Later, I will extend it to add a dry-run for each PR.

Problem is, in **config.js** - I have an entry like (for npm authntication)
> npmrc: `registry=<REGISTRY-ADDRESS>\nalways-auth=true\n_auth=${process.env.NPM_TOKEN}`

Because of this variable **${process.env.NPM_TOKEN}**, the travis build fails. Can you please help in resolving this? 

Thanks!

**Comment by viceice** [comment]
please post your `config.js`. I'm pretty sure you have an error in it.

**Comment by nimmoadam** [comment]
@viceice The bot scans repo and it works perfectly. 

**config.js**

```
module.exports = {
  endpoint: 'https://github.ibm.com/api/v3/',
  npmrc: registry=<REGISTRY-ADDRESS>\nalways-auth=true\n_auth=${process.env.NPM_TOKEN},
  repositories: [
    'ONE',
    'TWO'
  ],
};
```

**npmrc**
```
_auth='${process.env.NPM_TOKEN}'
registry=<REGISTRY-ADDRESS>
always-auth=true
```

**Comment by viceice** [comment]
there is indeed something wrong

config.js
```js
module.exports = {
  endpoint: 'https://github.ibm.com/api/v3/',
  npmrc: `registry=<REGISTRY-ADDRESS>\nalways-auth=true\n_auth=${process.env.NPM_TOKEN}`,
  repositories: [
    'ONE',
    'TWO'
  ],
};
```
missing template quotes

npmrc
```ini
_auth=${NPM_TOKEN}
registry=<REGISTRY-ADDRESS>
always-auth=true
```
Wrong env reference

**Comment by nimmoadam** [comment]
@viceice I do have template quote already. Sorry when I shared it here - I removed it by mistake, when removing the registry address.

Also, the same config actually works. Renovate bot scans all the repositories that are added in config.js

**Comment by viceice** [comment]
do you have the `.npmrc` file you posted above written to disk? remove it, it is wrong!

**Comment by viceice** [comment]
can you share the relevant parts of your travis config

**Comment by viceice** [comment]
if you add a `.npmrc` to disk, you need to write like:

```ini
_auth=${NPM_TOKEN}
registry=<REGISTRY-ADDRESS>
always-auth=true
```

npmrc is a ini file, not a javascript, so you need the npm specific variable substitution options.
https://docs.npmjs.com/files/npmrc

**Comment by nimmoadam** [comment]
@viceice Okay. Got it.. I will remove .npmrc file. 

**travis file**

```
language: node_js
node_js: lts/*
env:
  - NPM_TOKEN=${NPM_AUTH}
before_install:
  - npm i -g npm@latest
install: npm i -g renovate
script: 
  - if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] ; then renovate-config-validator ; fi
```

**Comment by nimmoadam** [comment]
@viceice I have deleted the .npmrc file .. and the travis file that am using is in above comment. 

config.js has
> npmrc: `registry=<REGISTRY-ADDRESS>\nalways-auth=true\n_auth=${process.env.NPM_TOKEN}`,

So the issue with that still persists. 
Error is that it fails to replace process.env.NPM_TOKEN

```
Setting environment variables from repository settings
168$ export RENOVATE_TOKEN=[secure]
169$ export USERNAME=[secure]
170$ export PASSWORD=[secure]
171$ export NPM_AUTH=[secure]
172$ export NPM_TOKEN=[secure]
173$ export process.env.NPM_TOKEN=[secure]
174The previous command failed, possibly due to a malformed secure environment variable.K
176Please be sure to escape special characters such as ' ' and '$'.
177For more information, see https://docs.travis-ci.com/user/encryption-keys.

181
182Setting environment variables from .travis.yml
183$ export NPM_TOKEN=${NPM_AUTH}
184
185Error: Failed to replace env in config: ${process.env.NPM_TOKEN}
188    at /home/travis/.nvm/versions/node/v12.13.1/lib/node_modules/npm/lib/config/core.js:415:13
```

**Comment by nimmoadam** [comment]
Hi @viceice Thanks. 

1. Yes, I am using **`** (template string). It is not single quote. 
2. I figured out from where this is coming. "export process.env.NPM_TOKEN=[secure]".
It was added as one of the travis variable. For testing I added and missed removing it. It works now. 

Thank you. This can be closed.
