### ISSUE TITLE
Details about updates contained in a lockfile maintenance PR

### ISSUE THREAD

**Issue by frangio** [renovatebot/config-help#826]
Lockfile maintenance PRs seem to include no details about the updates that are contained in them. Example in my repo [here](https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/139).

I would love to see at least the same table of updates that is shown in normal update PRs. It would be even better if it contained the release notes too.

Is this a configuration issue or a limitation of lockfile maintenance?

Thank you.

**Comment by rarkins** [comment]
It's not data we currently gather - we just let npm/yarn do their work, and it may potentially update hundreds of dependencies altogether (direct and transitive).
