### ISSUE TITLE
renovate on http files or complex github tags

### ISSUE THREAD

**Issue by michael-todorovic** [renovatebot/config-help#828]
Hello,
I'm building a docker image with kubectl. I can monitor:

- https://storage.googleapis.com/kubernetes-release/release/stable.txt (from [official doc](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-with-curl-on-linux))
- https://github.com/kubernetes/kubectl/releases (with kubernetes-.*)

As I didn't find a way to get the info from a remote http file, I tried to get it working with github-releases:

```
"regexManagers": [
      {
        "fileMatch": ["^Dockerfile$"],
        "matchStrings": ["ARG KUBECTL_VERSION=\"kubernetes-(?<currentValue>.*?)\"\n"],
        "depNameTemplate": "kubectl",
        "lookupNameTemplate": "kubernetes/kubectl",
        "datasourceTemplate": "github-releases",
        "versioningTemplate": "^kubernetes-(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"
      }
    ]
```

And I get this in the debug logs 

```
           {
             "packageFile": "Dockerfile",
             "manager": "regex",
             "deps": [
               {
                 "depName": "kubectl",
                 "lookupName": "kubernetes/kubectl",
                 "currentValue": "1.18.0",
                 "datasource": "github-releases",
                 "versioning": "^kubernetes-(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)$",
                 "replaceString": "ARG KUBECTL_VERSION=\"kubernetes-1.18.0\"\n",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": "https://github.com/kubernetes/kubectl"
               }
             ],
             "matchStrings": [
               "ARG KUBECTL_VERSION=\"(kubernetes-(?<currentValue>.*?))\"\n"
             ]
           }
         ]
       }
DEBUG: branchifyUpgrades (repository=mtodorovic/sre-tools)
DEBUG: 0 flattened updates found:  (repository=mtodorovic/sre-tools)
DEBUG: Returning 0 branch(es) (repository=mtodorovic/sre-tools)
```

How can I make renovate understand it has to add `kubernetes-` in front of the version?

Thanks!

**Comment by viceice** [comment]
see 
https://github.com/VisualOn/docker-images/blob/32459339590c53f36028cb9d71f25d57ef3a9f6d/docker/kubectl/Dockerfile#L10-L11
and
https://github.com/VisualOn/docker-images/blob/32459339590c53f36028cb9d71f25d57ef3a9f6d/renovate.json#L70-L78

deployed to https://hub.docker.com/r/visualon/kubectl

🙃

**Comment by michael-todorovic** [comment]
Wow, I didn't think to get the version from kubernetes :D

Thanks for your quick answer, this is working :tada:
