### ISSUE TITLE
Renovate is not running any longer

### ISSUE THREAD

**Issue by jenniesyip** [renovatebot/config-help#83]
Hi @rarkins,

I have been using Renovate since Feb 2018 successfully. It was enabled for our organization and my repo was added. Then the Onboarding PR was created and I made some configurations. It would run consistently weekly every Monday, and then I updated the schedule for it to run every 2 weeks on Monday. 

Our last set of Renovate PRs created was on July 2nd. Not sure what has happened since then, but we have received no new PRs for updating any of our dependencies since then. I have confirmed that there are some dependencies, like Lerna, which have had major updates since July. 

How can I debug my repo to see why Renovate is no longer running? I tried the following solutions:
- Nuking the config and re-onboarding (nothing happened for hours) — I also renamed the original on-boarding PR as directed
- Reconfiguring Renovate via PR (and removing the schedule to see if it would trigger updates, but nothing happened again). 

I am not sure what else I can do. Thanks for your help in advance!

**Update:**
I saw in other issues that I could login to the dashboard to see logs, but when I click on any Jobs, they just keep showing a loader with no data:

https://renovatebot.com/dashboard#udacity/veritas-design-system/16683240

![image](https://user-images.githubusercontent.com/1864971/44367360-5d22cc00-a484-11e8-9a46-baea8ba4f63c.png)

What does `no-plan` in the `Result` column mean in the table?

**Comment by rarkins** [comment]
Hi @jenniesyip I took a look at this to work out why it's saying 'no-plan'. It seems that although the "udacity" account is an Organization one, it has been signed up with a "Personal Plan" instead. The GitHub UI now stops this from happening but there was a period when the admin could sign an Organization up for a Personal Plan. This explains why the plan is not being detected. 

Your options would be:
- Get the udacity org admin to switch from Personal Plan to Organisation Starter plan, or
- Move this repository under your personal GitHub account and use a Personal Plan there

**Comment by jenniesyip** [comment]
@rarkins Thank you for checking on this for us! Our admin switched it and it works now.

**Comment by rarkins** [comment]
Thanks for letting me know, and thanks for being a customer!
