### ISSUE TITLE
Enable Managers

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#832]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

We would like to use enabledManagers option as mentioned here. Could you please let us know how to configure this in renovate? in which file we have to configure?

**Comment by viceice** [comment]
https://docs.renovatebot.com/configuration-options

**Comment by rarkins** [comment]
It's an array, and can be configured in the repo's Renovate.json or the boys config if you want it applied to every repo. You can get the list from https://docs.renovatebot.com/modules/manager/

**Comment by sakshan** [comment]
Can you share some sample for the bot config? how to configure in bot config?

**Comment by sakshan** [comment]
Thanks!!!
