### ISSUE TITLE
Error in renovate - not creating PR

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#833]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant

yes. we are getting below error for one of our repo and its not creating PR.

"message": "fatal: cannot lock ref 'refs/heads/renovate/org.quartz-scheduler-quartz-1.x': 'refs/heads/renovate' exists; cannot create 'refs/heads/renovate/org.quartz-scheduler-quartz-1.x'\n",
--
  | "stack": "Error: fatal: cannot lock ref 'refs/heads/renovate/org.quartz-scheduler-quartz-1.x': 'refs/heads/renovate' exists; cannot create 'refs/heads/renovate/org.quartz-scheduler-quartz-1.x'\n\n    at GitExecutorChain.onFatalException

(/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:66:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:58:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"

**Comment by rarkins** [comment]
It seems like someone has created a branch called `renovate` and that blocks git from creating any branch like `renovate/abc`. You should delete that branch and retry
