### ISSUE TITLE
renovate to manage sonarqube version

### ISSUE THREAD

**Issue by nimmoadam** [renovatebot/config-help#834]
Which Renovate are you using?

**Renovate Open Source CLI**

Which platform are you using?

**GitHub Enterprise**

Is there a way to use renovate bot to manage sonar version.? If yes, how do we do it? 

Also, I am aware that renovate bot supports only specific languages, but is there a way to use renovate bot to manage some packages, that are used inside a shell script?

Sonarqube is used for inspecting code quality. So, we are having separate shell script for running the sonar scan. In the shell script, the sonarqube scanner's version number is called out. So, if we want to update that using renovate bot - how can we do?

There is a file called sonar.sh and the version is mentioned as follows:
> SONAR_SCANNER_VERSION=3.2.0.1227

This is the place where we get different versions of sonarqube - https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/

Since this task (https://github.com/renovatebot/config-help/issues/794) is closed am opening a new one! 

Help on this please.

**Comment by rarkins** [comment]
No, it's not possible at this point because we don't have any "datasource" to retrieve these values, e.g. like we do with npm packages or github tags. It's the type of thing we'd like to do in future though.

**Comment by nimmoadam** [comment]
@rarkins 
Thanks. Then, I believe there is no other way to scan and update the sonarquber version, unless it comes from the datasource. 

If yes, then we can close this task and please update whenever that is available .
