### ISSUE TITLE
Artifact job has no access to private repositories

### ISSUE THREAD

**Issue by peternijssen** [renovatebot/config-help#838]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git@sub.domain.com:project/project.git
Directory: /tmp/renovate/repos/gitlab/project/project
Output:
git@domain.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### What would you like to do?

Both my composer.json file as my package.json file, contains libraries to git repositories in our private gitlab instance.

Composer.json
```
...
    "repositories": [
        {
            "type": "git",
            "url": "git@sub.domain.com:project/project.git"
        }
    ],
    "require": {
        "php": "^7.4",
        "project/project": "^0.11.0",
    },
...
```

Package.json
```
...
    "dependencies": {
        "bootstrap-multiselect": "git+ssh://git@sub.domain.com:project/project.git#1.2.1",
    }
...
```

Unfortunately, I receive the error above each time in the artifact job of the pipeline.

I tried setting the host rules within Gitlab CI, but that doesn't seem to solve it.

```
renovate:
  image:
    name: renovate/renovate
    entrypoint: [""]
  <<: *default-ssh-before
  stage: validate
  needs: []
  allow_failure: true
  variables:
    RENOVATE_GIT_AUTHOR: "Peter Nijssen <peter@domain.com>"
    RENOVATE_HOST_RULES: '{"hostName":"sub.domain.com","token":"${SSH_PRIVATE_KEY}"}'
  script:
    - >
      renovate
      --platform "gitlab"
      --endpoint "${CI_API_V4_URL}"
      --git-author "${RENOVATE_GIT_AUTHOR}"
      "${CI_PROJECT_PATH}"
```

What am I missing?

**Comment by viceice** [comment]
renovate doesn't support fetching git repos via ssh. There is currently no possibillity to pass ssh keys. If you clone via https composer hostrule might work.

**Comment by viceice** [comment]
as workaround you can try to start ssh key-agent  and lod key before running renovate.

Which kind of renovate are you using? npm package, docker full or slim image, helm chart ?

**Comment by peternijssen** [comment]
Thanks @viceice for answering so quickly. In the before script, I load the ssh key-agent like I do with regular jobs. 

```
  before_script:
    # SSH ACCESS TO GITLAB REPOSITORIES
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 'sub.domain.com' >> $HOME/.ssh/known_hosts
```

This works for normal jobs that I run with Gitlab CI (The script also comes from Gitlab itself) but unfortunately it doesn't solve the issue. That's why I tried with the host rules, but no luck either.

I am using the docker image `renovate/renovate`

**Comment by viceice** [comment]
can you please share some more debug logs of renovate, so we can see where it fails?

**Comment by peternijssen** [comment]
Would love to, but I cannot view the logs from the job `renovate/artifacts` as it's marked as an external job and I can't click it to view. So the only logs that I get are within the comments, added to the MR that fail. The comment in the end only leads to the error described in the issue.

Or will I get more logs within the comment when I enable the debug mode or so?

**Comment by viceice** [comment]
nope, you should go to the project pipeline, where you renovate job is running. there you should see the renovate log, which is gone to stdout by default.

you should also add `LOG_LEVEL='debug'` to the renovate env to see more verbose logging

**Comment by peternijssen** [comment]
<img width="1006" alt="Screenshot 2020-08-31 at 17 07 49" src="https://user-images.githubusercontent.com/688048/91735417-92eb0700-ebac-11ea-94f9-bf865f560eef.png">

I can't click on the external renovate job. So I am unable to get logs from that job. So unfortunately I can't see what's going on within that job and what it outputs. I can do so for other jobs.

**Comment by viceice** [comment]
why this is external? how do you run renovate? isn't it a normal gitlab pipeline?

**Comment by peternijssen** [comment]
I've added the job to the description of the issue. The result of that job is several merge requests to update dependencies, which the pipeline is shown in the screenshot above. I nowhere configured the external job. I thought renovate did this.

**Comment by viceice** [comment]
there is some pice missing. yout job definition says `name: renovate` with  `stage: validate`. you need to go to the renovate repo, not to the repo you want to update.

so please go to the gitlab project where the pipeline for renovate is configured. there should be pipelines with the configured renovate job

**Comment by peternijssen** [comment]
There are no errors within the actual renovate job itself. It runs all of the checks just fine, creates merge requests with dependency updates, so that all goes according to plan.

It's the countless merge requests it creates that have failed pipelines, in which renovate creates an artifact job on it's own.

**Comment by peternijssen** [comment]
Here is someone public pipeline, showing you, that you are unable to get the logs of the `renovate/artifacts` job; https://gitlab.com/opencontent/opencity/-/pipelines/116214429

**Comment by rarkins** [comment]
It's not a job, it's when Renovate sets a branch status: https://github.com/renovatebot/renovate/blob/bffebcc33119fcac4749a441c884e3f7c2627ae1/lib/platform/gitlab/index.ts#L548-L591

**Comment by rarkins** [comment]
There are no additional logs attached to that status, you need to retrieve them from the machine that ran Renovate.

**Comment by viceice** [comment]
as i said, you need to add 

> nope, you should go to the project pipeline, where you renovate job is running. there you should see the renovate log, which is gone to stdout by default.
> 
> you should also add `LOG_LEVEL='debug'` to the renovate env to see more verbose logging

Please enable enable debug log on the renovate job, then delete pr and branch, start a manual run and paste the renovate log here (please sanitize private infos before)

**Comment by peternijssen** [comment]
Whichever way you want to take it, the actual problem is within the description. If it's impossible to fetch the repositories through SSH, then 2 out of 4 dependency files cannot be used together with renovate unfortunately.

**Comment by peternijssen** [comment]
Will try out the debugging tomorrow

**Comment by viceice** [comment]
I think i see the problem, you need to configure [`trustLevel`)(https://docs.renovatebot.com/self-hosted-configuration/#trustlevel) to `high`. Otherwise renovate will not pass the ssh-agent env to composer call. so git cant find the agent.

**Comment by peternijssen** [comment]
Will try that out tomorrow. Thanks!

**Comment by peternijssen** [comment]
Thank you both for your help. In the end the trustLevel solved the issue. Thank you for your patience!
