### ISSUE TITLE
ignorePath with a glob pattern example?

### ISSUE THREAD

**Issue by Aghassi** [renovatebot/config-help#84]
I'm looking to have renovate ignore a whole directory, except for some subdirectories. Currently I have 

```
  "ignorePaths": [
    "generators/*/!(.circleci)"
  ]
```

For the yeoman generator I'm working on. However, this doesn't seem to be picking up my sub `.circleci` directory in the `generators` folder. I'm notoriously bad with glob patterns when it comes to exclusions, so I'd love a pointer as to how I'm doing this wrong 😅

**Comment by rarkins** [comment]
I'm not a glob expert myself. Here's the source code where `ignorePaths` is evaluated: https://github.com/renovatebot/renovate/blob/efff72a5e1cc6f5c49dcdc7f6b713f8ed1668a4a/lib/workers/repository/extract/file-match.js#L20-L30

As you can see, it uses `minimatch`.

What exact file names were you using? It works as I'd expect here:

```
minimatch('generators/abc/def', 'generators/*/!(.circleci)'); // true
minimatch('generators/abc/.circleci', 'generators/*/!(.circleci)'); // false
minimatch('generators/abc/.circleci/def', 'generators/*/!(.circleci)'); // false
```

**Comment by rarkins** [comment]
I just noticed you wrote:
> my sub .circleci directory in the generators folder

Do you mean directly in the folder, not under a subfolder?

```
minimatch('generators/.circleci', 'generators/*/!(.circleci)'); // false
minimatch('generators/abc', 'generators/*/!(.circleci)'); // false <-- Should be true
minimatch('generators/abc/def', 'generators/*/!(.circleci)'); // true
```

This seems not quite right either:
```
minimatch('generators/.circleci', 'generators/!(.circleci)'); // false
minimatch('generators/abc', 'generators/!(.circleci)'); // true
minimatch('generators/abc/def', 'generators/!(.circleci)'); // false <-- Should be true
```

**Comment by Aghassi** [comment]
No I mean under a sub directory. So in this case I can have multiple folders in the `generator` folder (yeoman generators in this case).

ex:
generators/app
generators/lib
generators/cli

etc.

And each of those may have a `.circlci` folder that I want monitored. So I'm curious how I would ensure that just the `circleci` folder is monitor. Otherwise, think of it like a monorepo, I would get all the package.json files in those sub folders if there are templates and such. I'd like to avoid that.

**Comment by rarkins** [comment]
So then it's like this?

generators/app/.circleci/foo.yaml <-- Renovate
generators/app/package.json <-- Do not renovate
generators/app/hello/Dockerfile <-- Do not renovate

I think the issue actually is probably not the `ignorePaths` but actually the `fileMatch` for CircleCI:

```js
    default: {
      fileMatch: ['^.circleci/config.yml$'],
    },
```

I might change this default but in the meantime you can add to it with this config:

```
  "circleci": {
    "fileMatch": ["(^|/).circleci/config.yml$"]
  }
```

**Comment by Aghassi** [comment]
Awesome, that worked. Thank you 😄
