### ISSUE TITLE
Artifact Update Problem

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#840]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

In one of our repo we are seeing below error. Any error in configuration?

⚠️ Artifact update problem
Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻️ Renovate will retry this branch, including artifacts, only when one of the following happens:

any of the package files in this branch needs updating, or
the branch becomes conflicted, or
you check the rebase/retry checkbox if found above, or
you rename this PR's title to start with "rebase!" to trigger it manually
The artifact failure details are included below:

File name: package-lock.json

**Comment by rarkins** [comment]
Check your bot logs
