### ISSUE TITLE
semanticCommitType for patch not respected

### ISSUE THREAD

**Issue by evanstoddard23** [renovatebot/config-help#842]
**What Renovate type, platform and version are you using?**

GitHub hosted app

**Describe the bug**

Renovate config: json```{
  "extends": [
    "config:base",
    ":timezone(America/Chicago)",
    ":semanticCommits"
  ],
  "packageRules": [
    {
      "updateTypes": ["patch"],
      "automerge": false,
      "semanticCommitType": "fix"
    },
    {
      "updateTypes": ["minor"],
      "automerge": false,
      "semanticCommitType": "feat"
    },
    {
      "updateTypes": ["major"],
      "automerge": false,
      "semanticCommitType": "feat"
    }
  ],
  "assigneesFromCodeOwners": true
}```

Renovate created 

Type | Update | Change
-- | -- | --
github.com/xxxx | github | patch | v3.2.0 -> v3.2.1

with commit message: "@renovate-bot
feat(deps): update terraform xxxx"

Commit message should be fix(deps): instead of feat(deps): according to the config

**Relevant debug logs**

**To Reproduce**

**Additional context**

**Comment by rarkins** [comment]
Renovate’s default behaviour is to treat minor and patch updates as the same. If you want to separate behaviour then set separateMinorPatch=true in your config.

**Comment by evanstoddard23** [comment]
@rarkins any way to have minor and patch in the same branch/pr but with different semantic commit types for their respective commits?

**Comment by rarkins** [comment]
Not that I can think of. Without separation they are both classified as "minor" (ie we use minor in this sense as meaning "non-major" and not meaning minor in the strict definition). With separation, minor and patch updates for the same package will be given different branch names, ie in order to separate them.
