### ISSUE TITLE
Globally set repo-specific config in bot's config.js

### ISSUE THREAD

**Issue by arxeiss** [renovatebot/config-help#844]
### Which Renovate are you using?

Renovate Open Source Docker image (full one ie. `renovate/renovate:latest`)

### Which platform are you using?

GitLab.com

### What would you like to do?

My thoughts were:  What I will put into my `config.js` when setting up Renovate Bot, it will be used as default config for all repos as well. But it seems that it is not.<br>
So in my case the `extends`, `prHourlyLimit` and `enabledManagers` setting in the following bot config file are useless and they must be in `renovate.json` file, not globally set in `config.js`.

Or is there a way how to set up bot to use this as base config for all repos, except publishing custom preset and `extends` it in `renovate.json`?

> **Edit**: Just now I have noticed what documentation says next to `extends` "Note: does not work if configured in config.js". But that does not change my thoughts about prHourlyLimit and enabledManagers

Here is my bot config and repo config file:

Renovate bot **config.js:**

```js
module.exports = {
  extends: ["config:base"],
  prHourlyLimit: 10,
  enabledManagers: [ "npm", "docker-compose", "dockerfile", "gitlabci", "composer" ],
  platform: "gitlab",
  logFile: "renovate.log.json",
  baseBranches: ["master"],
  repositories: [ "pavel.kutac/renovate-bot" ],
};
```
The initial repo-specific **renovate.json**:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}
```

**Comment by viceice** [comment]
you should use a shared config and use https://docs.renovatebot.com/self-hosted-configuration/#onboardingconfig to push that to all your repos with onboarding pr
