### ISSUE TITLE
Number of PRs open concurrently too low

### ISSUE THREAD

**Issue by jugglingthebits** [renovatebot/config-help#847]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

![grafik](https://user-images.githubusercontent.com/3235163/92380377-646baf80-f109-11ea-9fb7-fefd234c67db.png)

![grafik](https://user-images.githubusercontent.com/3235163/92380346-5584fd00-f109-11ea-9fdd-965d2536fda9.png)

### What would you like to do?

I am trying to see 10 renovate PRs concurrently, but only observing 3 - although there are much more than 10 outdated dependencies. Renovate keeps stopping at having only 3 PRs open at a time. As far as I can tell, Renovate can see the updates, but skips them with the log message `Reached PR limit - skipping branch creation`. I cannot tell why - from my point of view, it could also be a bug.

Here is my config:
![grafik](https://user-images.githubusercontent.com/3235163/92380443-7baa9d00-f109-11ea-99c8-c7a72b3d0902.png)

**Comment by rarkins** [comment]
Sorry, a recent change to count concurrent branches instead of PRs caused this. We are restoring the old approach in https://github.com/renovatebot/renovate/pull/7199
