### ISSUE TITLE
Encrypted Token from HostRules not used

### ISSUE THREAD

**Issue by etwillbefine** [renovatebot/config-help#848]
### Which Renovate are you using?

Other (please write below)
Self-Hosted

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Adding trailing slash to endpoint
FATAL: You must configure a GitHub personal access token
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "xSsStNSlz",
           "msg": "You must configure a GitHub personal access token"
         }
       ]
```

### What would you like to do?

Use an encrypted Token for GitHub.

Here is my Config:

```
{
  ...
  "platform": "github",
  "extends": ["config:base"],
  "endpoint": "https://api.github.com",
  "privateKeyPath": "/usr/src/app/decrypt.key",
  "repositories": ["my-repo1"],
  "hostRules": [
     {"domainName": "github.com", "encrypted": {"token": "***********"}}
  ],
}
```

See also https://github.com/renovatebot/config-help/issues/518 which was closed. 

I dont think using `GITHUB_` env is the right solution to the Problem. According to the Renovate Docs my Config should work: https://docs.renovatebot.com/install-gitlab-app/#configuring-the-token 
I am using my own private key and **do not** use the encrypt page from Renovate. 

Is there any Information missing in the Docs or something I havnt configured properly? 
I enabled debug Output and cant find any Log related to failed decrypting for example. 
When going through the Codebase I also cant find a place where hostRules are actually decrypted before `initPlatform` is called which throws an Error if there is no `token` field configured. 

Is this Host Rules config only intended to be used to fetch Dependencies?  In that case I'd suggest an Update on the Docs.

> Currently the purpose of hostRules is to configure credentials for host authentication. You tell Renovate how to match against the host you need authenticated, and then you also tell it which credentials to use.

**Comment by viceice** [comment]
if you use github platform, you need to configure the token on toplevel config or env `GITHUB_TOKEN`

```js
{
...
  encrypted: { token: "xxxx" }
...
}
```

**Comment by etwillbefine** [comment]
Still the same

```
     "gitAuthor": "Renovate Bot <apps+renovate@goci.io>",
     "platform": "github",
     "endpoint": "https://api.github.com",
     "privateKeyPath": "/usr/src/app/decrypt.key",
     "trustLevel": "low",
     "encrypted": {"token": "***********"},
     "repositories": ["my-repo1"],
     "hostRules": [],
     "binarySource": "docker",
     "logLevel": "debug"
   }
DEBUG: Adding trailing slash to endpoint
FATAL: You must configure a GitHub personal access token
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "D2TnCv6Jf",
           "msg": "You must configure a GitHub personal access token"
         }
       ]
```

**Comment by rarkins** [comment]
I think we've got some wires crossed due to you running this self-hosted and it not being clear whether it's client/repository side configuration or server/bot configuration.

If you mean the token for the platform like GitHub then it must be in the bot's config in `RENOVATE_TOKEN` or cli `--token` or in the `token` field of your `config.js`. You can't configure the token in the repository's config - we need the token *before* we access the repository.

Meanwhile, `encrypted` objects are supported only for the client-side config. If you want to pass the token "secretively" on your bot side then I suggest `RENOVATE_TOKEN` before you run the bot.

If you conclude that any of the documentation was confusing or misleading then feel free to raise any PRs improving that - pretty much everything is in the `docs/` folder in the main repo.

**Comment by etwillbefine** [comment]
Thanks for your explanation. Indeed I completely mixed two different set of configurations. Now some other things make more sense as well. I think it's just me starting to get to know renovate. 

But I think some other people (see issue #518) are basically landing on the page how to use a personal GitHub token with gitlab (so to fetch go dependencies for example). Maybe these docs just need to be a little bit more specific. I'll prepare a one liner which would have helped me in the Docs tomorrow.
