### ISSUE TITLE
[Question] Dynamic PR notes

### ISSUE THREAD

**Issue by sychd** [renovatebot/config-help#849]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### What would you like to do?

Hello! Could you please tell, is it available to have dynamic notes for PR? 
Use-case: I plan to add `postUpgradeTask` that will rise ticket and want to append the link to that ticket to the PR.
Generally, it would be cool to have such dynamic prefixes for commit messages also.
I see it like:
```
{
...
"getCustomPrNotes": "./script-that-returns-custom-notes"
...
}
```

I've searched for that ability but unfortunately found nothing. Maybe here is some workaround or this feature is planned?

**Comment by rarkins** [comment]
You may be able to use [prBodyNotes](https://docs.renovatebot.com/configuration-options/#prbodynotes) for this purpose. However it's not dynamic.

**Comment by sychd** [comment]
Thanks for response
Yes, I saw this config property, but, unfortunately it does not suit the case because it is static

**Comment by rarkins** [comment]
OK, feel free to raise a feature request in the main repo describing how you would need it to work
