### ISSUE TITLE
SeparateMajorMinor and groups

### ISSUE THREAD

**Issue by 0xR** [renovatebot/config-help#85]
I want to use both groups and separate major minor, but it doesn't seem to work.

This is my config:
```json
{
    "packageRules": [
         {
            "packagePatterns": [
                "jquery",
                "lodash",
                "backbone"
            ],
            "groupName": "clientside"
        }
    ]
}
```

But it still updates major and minor in the same branch.

I know there is a workaround, but I can't get that work. I tried this:

```json
{
    "packageRules": [
         {
            "packagePatterns": [
                "jquery",
                "lodash",
                "backbone"
            ],
            "groupName": "clientside",
             "minor": {
                 "groupName": "clientside-minor",
                 "automerge": false
              }
         }
    ]
}
```

I also tried the same with `"major"`

**Comment by rarkins** [comment]
In the current implementation, the presence of a `groupName` short-circuits the logic for `separateMajorMinor`, so you need a slight tweak to get it to work by putting all `groupName`'s inside major/minor objects:

```json
{
    "packageRules": [
         {
            "packagePatterns": [
                "jquery",
                "lodash",
                "backbone"
            ],
			"major": {
	            "groupName": "clientside major", 
			},
            "minor": {
               "groupName": "clientside",
           }
         }
    ]
}
```

I'm not sure exactly what you wanted to do with `automerge` so I have left it out of the above.

**Comment by 0xR** [comment]
I'll try that. I wanted to automerge minor. So that should have been `automerge: true`

**Comment by rarkins** [comment]
OK, that makes more sense :)

**Comment by rarkins** [comment]
@0xR how did you go? FYI this has been solved in `renovate`, which you can get if you pull `renovate/pro:latest` from Docker Hub.
