### ISSUE TITLE
custom changes after npm upgrade

### ISSUE THREAD

**Issue by pi0** [renovatebot/config-help#852]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub.com

### What would you like to do?

Hi! Thanks again for awesome renovate bot :heart:  it made life much easier for Nuxt.js projects

One issue we currently have for [create-nuxt-app](https://github.com/nuxt/create-nuxt-app) repository, is that we also need renovate updating test snapshots for versions and include change in PR. It is as easy as running `npm run test -u` but manual process is to checkout PR branch and manually do. I looked at configuration but wasn't sure maybe there is a way to make renovate automatically running such command?

Example PR: https://github.com/nuxt/create-nuxt-app/pull/580

**Comment by rarkins** [comment]
Check out https://docs.renovatebot.com/configuration-options/#postupgradetasks

**Comment by pi0** [comment]
Thanks for quick response @rarkins, I tried [this](https://github.com/nuxt/create-nuxt-app/blob/master/renovate.json#L11) but seems not triggered for https://github.com/nuxt/create-nuxt-app/pull/607 ([logs](https://app.renovatebot.com/dashboard#github/nuxt/create-nuxt-app/228872251)). Is it because public instance is not high trust? Should we use a selfhost version for this?

**Comment by rarkins** [comment]
The hosted instance is not high trust. For now we prefer not to have the risk of arbitrary code running. Perhaps you can use a GitHub action for the post update, or perhaps our own GitHub action if you want to self host?

**Comment by pi0** [comment]
Good idea for GH action. I've created this workflow which seems working fine for PRs as well: https://github.com/nuxt/create-nuxt-app/blob/master/.github/workflows/snapshot.yml 

Only downside is that github trusts it's own commits and not running tests :D (like https://github.com/nuxt/create-nuxt-app/pull/610)

Thanks again for help. I would be happy to document it somewhere if wanted otherwise maybe later-on just making a tweet.

**Comment by rarkins** [comment]
That would be great. I think they aim that actions can't trigger other actions "easily" to prevent avalanches, but a PAT added to the action would work.
