### ISSUE TITLE
Renovate - Artifact update problem

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#857]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

Seeing this issue after renovate. Any problem in configuration? 

⚠️ Artifact update problem
Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻️ Renovate will retry this branch, including artifacts, only when one of the following happens:

any of the package files in this branch needs updating, or
the branch becomes conflicted, or
you check the rebase/retry checkbox if found above, or
you rename this PR's title to start with "rebase!" to trigger it manually
The artifact failure details are included below:

File name: package-lock.json

**Comment by sakshan** [comment]
@rarkins 

Could you please explain about the above issue?

**Comment by rarkins** [comment]
Duplicate of #840. The questions you've been asking are generally of low information/details and don't demonstrate that you're trying to do much troubleshooting of your own, so future questions like this will continue to be closed without answer if they are equally lacking in details.
