### ISSUE TITLE
Different schedule for lockFileMaintenance vs package.json updates?

### ISSUE THREAD

**Issue by broksonic21** [renovatebot/config-help#858]
I had previously tried to turn lockFileMaintenance on, but it seemed to always run with the same schedule as the package.json

what's the right way to update this to have lockFileMaintenance once a week, but package.json updates daily?

```
{
  "extends": [
    "config:base",
    ":prHourlyLimit4",
    ":prConcurrentLimit10",
    "group:all",
    ":onlyNpm",
    ":enableVulnerabilityAlertsWithLabel(Vulnerability)",
    ":noUnscheduledUpdates"
  ],
  "automerge": true,
  "rangeStrategy": "bump",
  "timezone": "America/New_York",
  "schedule": ["after 6am and before 10am every weekday"],
  "enabledManagers": ["npm"],
  "includePaths": ["package.json"],
  "labels": ["renovate"]
}
```

**Comment by rarkins** [comment]
You can search this repo for examples of configuring `lockFileMaintenance`. For example: https://github.com/renovatebot/config-help/issues/677

**Comment by broksonic21** [comment]
that seems to work - thanks!
