### ISSUE TITLE
Feature Request: configure truncation of long branch names

### ISSUE THREAD

**Issue by denver-HJS** [renovatebot/config-help#859]
### Which Renovate are you using?

Renovate Open Source CLI

Other (please write below)

### Which platform are you using?

Bitbucket Cloud

### What would you like to do?

I hope I found the right place 😄 [The information](https://docs.renovatebot.com/configuration-options/#branchname) about `branchName` sent me here.

I was wondering if there can be a new configuration added like `branchNameMaxLength` or `branchNameTruncateAt`. My particular use case is that my build system has a character limit on the branch names it will accept. This particular branch name exceeds the limit: `renovate-major-typescript-eslint-monorepo`

So it would be really helpful to me if I could truncate it to `renovate-major-typescript-eslint-monore` (or wherever the limit resides)

**Comment by rarkins** [comment]
Can you add your ideas and requirements to https://github.com/renovatebot/renovate/issues/5390 ?

**Comment by rarkins** [comment]
BTW if you have *really* short branch length allowances then I'd suggest changing `renovate-` branchPrefix to `rnv-` or even `r-` to begin with.
