### ISSUE TITLE
Ignore all updates except whitelisted

### ISSUE THREAD

**Issue by 0xR** [renovatebot/config-help#86]
I'm onboarding renovatebot across many repositories. To stay on the safe side I want to start of with a whitelist of dependencies that should be updated.

Is there any way to do this?

`ignoreDeps` doesn't seem to accept a wildcard

**Comment by rarkins** [comment]
I think the easiest way with current functionality would be using two `packageRules`, e.g.

```json
{
	"packageRules": [
		{
			"packagePatterns": ["*"],
			"enabled": false
		},
		{
			"packageNames": ["jquery", "backbone"],
			"enabled": true
		}
	]
}
```

Renovate applies all matching package rules in the order they are defined, so this will function to first disable all and then enable the ones in the second list.
