### ISSUE TITLE
Add Assignee to PR on GitHub

### ISSUE THREAD

**Issue by fxnm** [renovatebot/config-help#861]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

https://app.renovatebot.com/dashboard#github/fxnm/CommandLineTesting/230266253

### What would you like to do?

I was trying to add a user (in this example me but i want to be able to add more people if needed) to a PR form the bot. But it doesnt assigne me in this case to the PR.

Config:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "assignees": [
    "47592197+fxnm@users.noreply.github.com"
  ],
  "labels": [
    "dependency"
  ]
}
```

PR:
![Screenshot_2020-09-13 Update dependency org projectlombok lombok to v1 18 12 by renovate · Pull Request #10 · fxnm CommandL](https://user-images.githubusercontent.com/47592197/93029316-79b97000-f61a-11ea-92dd-fe79cf9fdd46.png)

**Comment by rarkins** [comment]
On GitHub, `assignees` should contain usernames, e.g. `fxnm`

**Comment by fxnm** [comment]
thank you so much, it worked
