### ISSUE TITLE
Group merge requests by path instead of container image

### ISSUE THREAD

**Issue by oyxnaut** [renovatebot/config-help#862]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

There is no error in the logs, because there is no erroneous behaviour. Simply a question regarding configuration.

### What would you like to do?

Hi,
we're using a mono-repo in gitlab for our deployments/configs. In this repo, there are several docker-compose.yml files, and I'd like to know if it's possible to group merge requests by path, instead of container image.
Example of status quo: Currently, we get one merge request for all redis 6.0.5 -> 6.0.8 updates, one for all mariadb updates, etc. This would be fine if everyone on the team was responsible for all services, and knows dependency constraints like "Don't use postgresql >= 11 for deployment X".
Example of what I'd like to do: Instead of the above, I'd like to group merge requests by path. I.e. we have two docker-compose.yml files, one residing in $repoRoot/foo/docker-compose.yml, and one in $repoRoot/bar/docker-compose.yml. If at all possible, I'd like to have one merge request for all updatable images in foo/docker-compose.yml, and one for all updatable images in bar/docker-compose.yml, even if both docker-compose.yml files use (to stick with the redis example) redis:6.0.5.

**Comment by rarkins** [comment]
You can probably achieve this by configuring the following:

```
{
  "additionalBranchPrefix": "{{{parentDir}}}-"
}
```

In your above example, `foo` and `bar` are your parentDir values.The result would be branches named like `renovate/foo-redis-6.x` and `renovate/bar-redis-6.x`. Maybe test it out in a demo repo first to make sure it's working as you expect. 

Search this repo's closed issues to find more discussions on `parentDir`

**Comment by oyxnaut** [comment]
Thank you for your quick reply.
Unfortunately setting `"additionalBranchPrefix": "{{{parentDir}}}-"` by itself didn't have the desired effect. However, adding `"branchTopic": "{{{parentDir}}}/{{{depNameSanitized}}}-{{{newMajor}}}{{#if isPatch}}.{{{newMinor}}}{{/if}}.x{{#if isLockfileUpdate}}-lockfile{{/if}}"` did the trick, and adding `"commitMessagePrefix": "{{{parentDir}}}:"` makes it much simpler to see what's going on in the merge requests. (Note that branchTopic is just the default value prefixed with `{{{parentDir}/`.)

**Comment by rarkins** [comment]
I filed a bug for this: https://github.com/renovatebot/renovate/issues/7281
