### ISSUE TITLE
Automerge with renovate-approve happens outside the window defined by the schedule

### ISSUE THREAD

**Issue by halfzebra** [renovatebot/config-help#863]
Hello friends! Thanks for working on Renovate! 🙌 

### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I'm using Renovate App with renovate-approve bot and it looks like sometimes PRs are merged up to 6 hours after the window defined by the `schedule` configuration option.

I'd like merges to occur during the office hours so it's easier to react to possible issues sneaking through tests.

Is there a way to limit when merging is allowed?

Is there an opportunity for Renovate to add this kind of feature?
I'm up for making a PR if this feature is technically possible. 🤷‍♂️

**Comment by rarkins** [comment]
Hi @halfzebra if you can jump into https://github.com/renovatebot/renovate/issues/4866 with any feedback or ideas I'd be happy to help you get any PR progressed! Will close this issue in the meantime
