### ISSUE TITLE
Automerge patch(branch)

### ISSUE THREAD

**Issue by teambetjent** [renovatebot/config-help#868]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Cloud

### What would you like to do?

I want to automerge patch upgrades via branch, and reading the docs lead me to believe that the following way would enable this: 

```
packageRules: [
 {
      updateTypes: ['patch', 'pin'],
      automerge: true,
      automergeType: 'branch',
    },
],
```
Am i missing something, or doing it the wrong way? Running npx -p renovate renovate-config-validator does not trigger any errors. The PR created by renovate-bot outputs the following: 

🚦 Automerge: Disabled by config. Please merge this manually once you are satisfied.

**Comment by rarkins** [comment]
Try adding `separateMinorPatch: true` to your config.

**Comment by drewfreyling** [comment]
For context why is `separateMinorPatch: true` needed to solve this?

**Comment by viceice** [comment]
Otherwise patch updates are classified as minor update.
