### ISSUE TITLE
Dependencies are not updated

### ISSUE THREAD

**Issue by Joge97** [renovatebot/config-help#87]
I have setup the renovate bot as a github app. The setup worked fine. The devDependencies have been successfully upgraded, but no pull request for upgrading the dependencies has been generated.

Repository:

https://github.com/Joge97/require-from-app-root

Configuration:

```json
{
  "extends": [
    "config:base",
    "config:js-lib",
    ":semanticCommitScope(dependencies)"
  ],
  "baseBranches": [
    "develop"
  ],
  "updateLockFiles": true
}
```

The dependency @types/node was not upgraded.

**Comment by Joge97** [comment]
I already checked them. They seem do be okay.

<details>
<summary>Logs of last run</summary>
INFO: Renovating repository
DEBUG: assignPlatform
DEBUG: initRepo("Joge97/require-from-app-root")
DEBUG: Resetting platform config
DEBUG: GET repos/Joge97/require-from-app-root [retries=5]
DEBUG: Joge97/require-from-app-root owner = Joge97
DEBUG: Joge97/require-from-app-root default branch = master
DEBUG: Prefetching prList and fileList
DEBUG: Retrieving PR list
DEBUG: GET repos/Joge97/require-from-app-root/pulls?per_page=100&state=all [retries=5]
DEBUG: GET repos/Joge97/require-from-app-root/git/trees/master?recursive=true [retries=5]
DEBUG: Retrieved fileList with length 10
DEBUG: Retrieved 7 Pull Requests
DEBUG: resetMemCache()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: renovate.json exists
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
DEBUG: GET repos/Joge97/require-from-app-root/contents/renovate.json?ref=master [retries=5]
INFO: renovate.json config
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "baseBranches": [
      "develop"
    ],
    "updateLockFiles": true
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "baseBranches": [
      "develop"
    ],
    "updateLockFiles": true
  }
}
DEBUG: renovate.json migrated config
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "baseBranches": [
      "develop"
    ],
    "updateLockFiles": true
  }
}
DEBUG: checkBaseBranch()
DEBUG: config.repoIsOnboarded=true
DEBUG: detectSemanticCommits()
DEBUG: getCommitMessages
DEBUG: GET repos/Joge97/require-from-app-root/commits [retries=5]
DEBUG: Semantic commits detection: angular
INFO: angular semantic commits detected
DEBUG: POST graphql [retries=5]
DEBUG: No vulnerability alerts found
DEBUG: processRepo()
INFO: baseBranches
{
  "baseBranches": [
    "develop"
  ]
}
DEBUG: baseBranch: develop
DEBUG: Setting baseBranch to develop
DEBUG: Setting baseBranch to develop
DEBUG: GET repos/Joge97/require-from-app-root/git/trees/develop?recursive=true [retries=5]
DEBUG: extractAndUpdate()
DEBUG: getPackageFiles(bazel)
DEBUG: GET repos/Joge97/require-from-app-root/git/trees/develop?recursive=true [retries=5]
DEBUG: Retrieved fileList with length 9
DEBUG: Retrieved fileList with length 9
DEBUG: Using file match: (^|/)WORKSPACE$ for manager bazel
DEBUG: getPackageFiles(buildkite)
DEBUG: Using file match: \.buildkite/.+\.yml$ for manager buildkite
DEBUG: getPackageFiles(circleci)
DEBUG: Using file match: ^.circleci/config.yml$ for manager circleci
DEBUG: getPackageFiles(composer)
DEBUG: composer is disabled
DEBUG: getPackageFiles(docker-compose)
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: getPackageFiles(dockerfile)
DEBUG: Using file match: (^|/)Dockerfile$ for manager dockerfile
DEBUG: getPackageFiles(gitlabci)
DEBUG: Using file match: ^.gitlab-ci.yml$ for manager gitlabci
DEBUG: getPackageFiles(kubernetes)
DEBUG: getPackageFiles(meteor)
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: getPackageFiles(npm)
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Matched 1 file(s) for manager npm
{
  "matchedFiles": [
    "package.json"
  ]
}
DEBUG: GET repos/Joge97/require-from-app-root/contents/package.json?ref=develop [retries=5]
DEBUG: npm.extractDependencies(package.json)
DEBUG: GET repos/Joge97/require-from-app-root/contents/yarn.lock?ref=develop [retries=5]
DEBUG: Detecting Lerna and Yarn Workspaces
DEBUG: Finding locked versions
DEBUG: Retrieving/parsing yarn.lock
DEBUG: getPackageFiles(nvm)
DEBUG: Using file match: ^.nvmrc$ for manager nvm
DEBUG: getPackageFiles(pip_requirements)
DEBUG: Using file match: (^|\/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: getPackageFiles(travis)
DEBUG: travis is disabled
DEBUG: getPackageFiles(nuget)
DEBUG: Using file match: (^|/)*\.csproj$ for manager nuget
DEBUG: Found 1 package file(s)
DEBUG: manager.fetchUpdates()
DEBUG: lookupUpdates
{
  "depName": "@types/node",
  "currentValue": "^7.0.18"
}
DEBUG: lookupUpdates
{
  "depName": "app-root-dir",
  "currentValue": "^1.0.2"
}
DEBUG: lookupUpdates
{
  "depName": "rimraf",
  "currentValue": "2.6.2"
}
DEBUG: lookupUpdates
{
  "depName": "tslint",
  "currentValue": "5.11.0"
}
DEBUG: lookupUpdates
{
  "depName": "typescript",
  "currentValue": "3.0.1"
}
DEBUG: npmjs res.headers for scoped package
{
  "package": "@types/node",
  "latest": "10.9.2",
  "headers": {
    "date": "Tue, 28 Aug 2018 12:12:17 GMT",
    "content-type": "application/json; charset=UTF-8",
    "set-cookie": [
      "__cfduid=dc6ec669d9dc6852ddc1a08ac754634d81535458337; expires=Wed, 28-Aug-19 12:12:17 GMT; path=/; domain=.registry.npmjs.org; HttpOnly"
    ],
    "cf-cache-status": "HIT",
    "cache-control": "public, max-age=300",
    "cf-ray": "4516af731957bb60-SEA",
    "etag": "\"b853d3d70ff698cd5544cb9c4ee1b608\"",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "last-modified": "Sat, 25 Aug 2018 01:06:41 GMT",
    "vary": "Accept-Encoding",
    "server": "cloudflare",
    "content-encoding": "gzip",
    "age": "1"
  }
}
INFO: 1 result(s): ^10.0.0 (@types/node)
DEBUG: packageFiles with updates
{
  "config": {
    "npm": [
      {
        "packageFile": "package.json",
        "manager": "npm",
        "deps": [
          {
            "depType": "dependencies",
            "depName": "@types/node",
            "versionScheme": "semver",
            "currentValue": "^7.0.18",
            "purl": "pkg:npm/%40types/node",
            "prettyDepType": "dependency",
            "lockedVersion": "7.0.18",
            "updates": [
              {
                "fromVersion": "7.0.69",
                "toVersion": "10.9.2",
                "newValue": "^10.0.0",
                "newMajor": 10,
                "newMinor": 9,
                "updateType": "major",
                "isSingleVersion": false,
                "isRange": true,
                "releaseTimestamp": "2018-08-25T01:06:23.991Z",
                "canBeUnpublished": false
              }
            ],
            "warnings": [],
            "repositoryUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped",
            "releases": [
              "7.0.69",
              "8.0.0",
              "8.0.1",
              "8.0.2",
              "8.0.3",
              "8.0.4",
              "8.0.5",
              "8.0.6",
              "8.0.7",
              "8.0.8",
              "8.0.9",
              "8.0.10",
              "8.0.11",
              "8.0.12",
              "8.0.13",
              "8.0.14",
              "8.0.15",
              "8.0.16",
              "8.0.17",
              "8.0.18",
              "8.0.19",
              "8.0.20",
              "8.0.21",
              "8.0.22",
              "8.0.23",
              "8.0.24",
              "8.0.25",
              "8.0.26",
              "8.0.27",
              "8.0.28",
              "8.0.29",
              "8.0.30",
              "8.0.31",
              "8.0.32",
              "8.0.33",
              "8.0.34",
              "8.0.35",
              "8.0.36",
              "8.0.37",
              "8.0.38",
              "8.0.39",
              "8.0.40",
              "8.0.41",
              "8.0.42",
              "8.0.43",
              "8.0.44",
              "8.0.45",
              "8.0.46",
              "8.0.47",
              "8.0.48",
              "8.0.49",
              "8.0.50",
              "8.0.51",
              "8.0.52",
              "8.0.53",
              "8.0.54",
              "8.0.55",
              "8.0.56",
              "8.0.57",
              "8.0.58",
              "8.5.0",
              "8.5.1",
              "8.5.2",
              "8.5.3",
              "8.5.4",
              "8.5.5",
              "8.5.6",
              "8.5.7",
              "8.5.8",
              "8.5.9",
              "8.5.10",
              "8.9.0",
              "8.9.1",
              "8.9.2",
              "8.9.3",
              "8.9.4",
              "8.9.5",
              "8.10.0",
              "8.10.1",
              "8.10.2",
              "8.10.3",
              "8.10.4",
              "8.10.5",
              "8.10.6",
              "8.10.7",
              "8.10.8",
              "8.10.9",
              "8.10.10",
              "8.10.11",
              "8.10.12",
              "8.10.13",
              "8.10.14",
              "8.10.15",
              "8.10.16",
              "8.10.17",
              "8.10.18",
              "8.10.19",
              "8.10.20",
              "8.10.21",
              "8.10.22",
              "8.10.23",
              "8.10.24",
              "8.10.25",
              "8.10.26",
              "8.10.27",
              "8.10.28",
              "9.3.0",
              "9.4.0",
              "9.4.1",
              "9.4.2",
              "9.4.3",
              "9.4.4",
              "9.4.5",
              "9.4.6",
              "9.4.7",
              "9.6.0",
              "9.6.1",
              "9.6.2",
              "9.6.3",
              "9.6.4",
              "9.6.5",
              "9.6.6",
              "9.6.7",
              "9.6.8",
              "9.6.9",
              "9.6.10",
              "9.6.11",
              "9.6.12",
              "9.6.13",
              "9.6.14",
              "9.6.15",
              "9.6.16",
              "9.6.17",
              "9.6.18",
              "9.6.19",
              "9.6.20",
              "9.6.21",
              "9.6.22",
              "9.6.23",
              "9.6.24",
              "9.6.25",
              "9.6.26",
              "9.6.27",
              "9.6.28",
              "9.6.29",
              "9.6.30",
              "10.0.0",
              "10.0.1",
              "10.0.2",
              "10.0.3",
              "10.0.4",
              "10.0.5",
              "10.0.6",
              "10.0.7",
              "10.0.8",
              "10.0.9",
              "10.0.10",
              "10.1.0",
              "10.1.1",
              "10.1.2",
              "10.1.3",
              "10.1.4",
              "10.3.0",
              "10.3.1",
              "10.3.2",
              "10.3.3",
              "10.3.4",
              "10.3.5",
              "10.3.6",
              "10.5.0",
              "10.5.1",
              "10.5.2",
              "10.5.3",
              "10.5.4",
              "10.5.5",
              "10.5.6",
              "10.5.7",
              "10.5.8",
              "10.7.0",
              "10.7.1",
              "10.7.2",
              "10.9.0",
              "10.9.1",
              "10.9.2"
            ]
          },
          {
            "depType": "dependencies",
            "depName": "app-root-dir",
            "versionScheme": "semver",
            "currentValue": "^1.0.2",
            "purl": "pkg:npm/app-root-dir",
            "prettyDepType": "dependency",
            "lockedVersion": "1.0.2",
            "updates": [],
            "warnings": [],
            "repositoryUrl": "https://github.com/philidem/node-app-root-dir",
            "releases": [
              "1.0.2"
            ]
          },
          {
            "depType": "devDependencies",
            "depName": "rimraf",
            "versionScheme": "semver",
            "currentValue": "2.6.2",
            "purl": "pkg:npm/rimraf",
            "prettyDepType": "devDependency",
            "lockedVersion": "2.6.2",
            "updates": [],
            "warnings": [],
            "repositoryUrl": "https://github.com/isaacs/rimraf",
            "releases": [
              "2.6.2"
            ]
          },
          {
            "depType": "devDependencies",
            "depName": "tslint",
            "versionScheme": "semver",
            "currentValue": "5.11.0",
            "purl": "pkg:npm/tslint",
            "prettyDepType": "devDependency",
            "lockedVersion": "5.11.0",
            "updates": [],
            "warnings": [],
            "repositoryUrl": "https://github.com/palantir/tslint",
            "releases": [
              "5.11.0"
            ]
          },
          {
            "depType": "devDependencies",
            "depName": "typescript",
            "versionScheme": "semver",
            "currentValue": "3.0.1",
            "purl": "pkg:npm/typescript",
            "prettyDepType": "devDependency",
            "lockedVersion": "3.0.1",
            "updates": [],
            "warnings": [],
            "repositoryUrl": "https://github.com/Microsoft/TypeScript",
            "homepage": "http://typescriptlang.org/",
            "releases": [
              "3.0.1"
            ]
          }
        ],
        "packageJsonName": "require-from-app-root",
        "packageJsonVersion": "0.0.0",
        "packageJsonType": "library",
        "yarnLock": "yarn.lock",
        "skipInstalls": true
      }
    ]
  }
}
DEBUG: branchifyUpgrades
DEBUG: 0 updates found
DEBUG:
{
  "upgradeNames": []
}
DEBUG: Returning 0 branch(es)
DEBUG: config.repoIsOnboarded=true
INFO: Processing 0 branch(es)
INFO: PR hourly limit remaining: 2
DEBUG: Enforcing prConcurrentLimit (20)
DEBUG: 0 PRs are currently open
INFO: PR concurrent limit remaining: 20
DEBUG: branchPrefix: renovate/
DEBUG: Found 0 Renovate PRs
{
  "renovatePrs": []
}
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: branchList
{
  "branchList": []
}
DEBUG: GET repos/Joge97/require-from-app-root/git/refs/heads/renovate/ [retries=5]
DEBUG: No renovate branches found
DEBUG: ensureIssueClosing()
DEBUG: GET repos/Joge97/require-from-app-root/issues?filter=created&state=open [retries=5]
INFO: Finished repository
</details>

**Comment by rarkins** [comment]
I think this is probably related to `@types/node` specifically. We have some rules to avoid major updates to Node.js versions by default, and it's possible `@types/node` is caught up in that because we try to group it with `node` upgrades normally.

What were you expecting? e.g. to update `@types/node` to the very latest 10.x?

**Comment by rarkins** [comment]
Yes, confirmed it's part of the default `config:base` rules: https://github.com/renovatebot/presets/blob/9348982aeea267e3e3ee8e597374ad9efc93b5ce/packages/renovate-config-config/package.json#L33

If you want to override it, add this:
```json
      "packageRules": [
        {
          "packageNames": [
            "@types/node"
          ],
          "major": {
            "enabled": true
          }
        }
      ]
```

**Comment by Joge97** [comment]
I have tried updating the config as described in the documentation, but i does not seam like, that the renovate bot recognizes the pull request.

https://github.com/Joge97/require-from-app-root/pull/9

<details>
<summary>Logs</summary>
INFO: Renovating repository
DEBUG: assignPlatform
DEBUG: initRepo("Joge97/require-from-app-root")
DEBUG: Resetting platform config
DEBUG: GET repos/Joge97/require-from-app-root [retries=5]
DEBUG: Joge97/require-from-app-root owner = Joge97
DEBUG: Joge97/require-from-app-root default branch = master
DEBUG: Prefetching prList and fileList
DEBUG: Retrieving PR list
DEBUG: GET repos/Joge97/require-from-app-root/pulls?per_page=100&state=all [retries=5]
DEBUG: GET repos/Joge97/require-from-app-root/git/trees/master?recursive=true [retries=5]
DEBUG: Retrieved fileList with length 10
DEBUG: Retrieved 9 Pull Requests
DEBUG: resetMemCache()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: renovate.json exists
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
DEBUG: GET repos/Joge97/require-from-app-root/contents/renovate.json?ref=master [retries=5]
INFO: renovate.json config
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "baseBranches": [
      "develop"
    ],
    "updateLockFiles": true
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "baseBranches": [
      "develop"
    ],
    "updateLockFiles": true
  }
}
DEBUG: renovate.json migrated config
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "baseBranches": [
      "develop"
    ],
    "updateLockFiles": true
  }
}
DEBUG: checkBaseBranch()
DEBUG: config.repoIsOnboarded=true
DEBUG: detectSemanticCommits()
DEBUG: getCommitMessages
DEBUG: GET repos/Joge97/require-from-app-root/commits [retries=5]
DEBUG: Semantic commits detection: angular
INFO: angular semantic commits detected
DEBUG: POST graphql [retries=5]
DEBUG: No vulnerability alerts found
DEBUG: processRepo()
INFO: baseBranches
{
  "baseBranches": [
    "develop"
  ]
}
DEBUG: baseBranch: develop
DEBUG: Setting baseBranch to develop
DEBUG: Setting baseBranch to develop
DEBUG: GET repos/Joge97/require-from-app-root/git/trees/develop?recursive=true [retries=5]
DEBUG: extractAndUpdate()
DEBUG: getPackageFiles(bazel)
DEBUG: GET repos/Joge97/require-from-app-root/git/trees/develop?recursive=true [retries=5]
DEBUG: Retrieved fileList with length 10
DEBUG: Using file match: (^|/)WORKSPACE$ for manager bazel
DEBUG: getPackageFiles(buildkite)
DEBUG: Using file match: \.buildkite/.+\.yml$ for manager buildkite
DEBUG: getPackageFiles(circleci)
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci
DEBUG: getPackageFiles(composer)
DEBUG: composer is disabled
DEBUG: getPackageFiles(docker-compose)
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: getPackageFiles(dockerfile)
DEBUG: Using file match: (^|/)Dockerfile$ for manager dockerfile
DEBUG: getPackageFiles(gitlabci)
DEBUG: Using file match: ^.gitlab-ci.yml$ for manager gitlabci
DEBUG: getPackageFiles(kubernetes)
DEBUG: getPackageFiles(meteor)
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: getPackageFiles(npm)
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Matched 1 file(s) for manager npm
{
  "matchedFiles": [
    "package.json"
  ]
}
DEBUG: GET repos/Joge97/require-from-app-root/contents/package.json?ref=develop [retries=5]
DEBUG: Retrieved fileList with length 10
DEBUG: npm.extractDependencies(package.json)
DEBUG: GET repos/Joge97/require-from-app-root/contents/yarn.lock?ref=develop [retries=5]
DEBUG: Detecting Lerna and Yarn Workspaces
DEBUG: Finding locked versions
DEBUG: Retrieving/parsing yarn.lock
DEBUG: getPackageFiles(nvm)
DEBUG: Using file match: ^.nvmrc$ for manager nvm
DEBUG: getPackageFiles(pip_requirements)
DEBUG: Using file match: (^|\/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: getPackageFiles(travis)
DEBUG: travis is disabled
DEBUG: getPackageFiles(nuget)
DEBUG: Using file match: (^|/)*\.csproj$ for manager nuget
DEBUG: Found 1 package file(s)
DEBUG: manager.fetchUpdates()
DEBUG: lookupUpdates
{
  "depName": "@types/node",
  "currentValue": "^7.0.18"
}
DEBUG: lookupUpdates
{
  "depName": "app-root-dir",
  "currentValue": "^1.0.2"
}
DEBUG: lookupUpdates
{
  "depName": "rimraf",
  "currentValue": "2.6.2"
}
DEBUG: lookupUpdates
{
  "depName": "tslint",
  "currentValue": "5.11.0"
}
DEBUG: lookupUpdates
{
  "depName": "typescript",
  "currentValue": "3.0.3"
}
DEBUG: npmjs res.headers for scoped package
{
  "package": "@types/node",
  "latest": "10.9.3",
  "headers": {
    "date": "Thu, 30 Aug 2018 12:14:40 GMT",
    "content-type": "application/json; charset=UTF-8",
    "set-cookie": [
      "__cfduid=dfdcee4cc166a03156e82ec33bbb0e9141535631280; expires=Fri, 30-Aug-19 12:14:40 GMT; path=/; domain=.registry.npmjs.org; HttpOnly"
    ],
    "cf-cache-status": "HIT",
    "cache-control": "public, max-age=300",
    "cf-ray": "45272db06fc52a2b-SEA",
    "etag": "\"0040b88117958a92505f2c9825f55d98\"",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "last-modified": "Tue, 28 Aug 2018 20:21:07 GMT",
    "vary": "Accept-Encoding",
    "server": "cloudflare",
    "content-encoding": "gzip",
    "age": "1"
  }
}
INFO: 1 result(s): ^10.0.0 (@types/node)
DEBUG: packageFiles with updates
{
  "config": {
    "npm": [
      {
        "packageFile": "package.json",
        "manager": "npm",
        "deps": [
          {
            "depType": "dependencies",
            "depName": "@types/node",
            "versionScheme": "semver",
            "currentValue": "^7.0.18",
            "purl": "pkg:npm/%40types/node",
            "prettyDepType": "dependency",
            "lockedVersion": "7.0.18",
            "updates": [
              {
                "fromVersion": "7.0.69",
                "toVersion": "10.9.3",
                "newValue": "^10.0.0",
                "newMajor": 10,
                "newMinor": 9,
                "updateType": "major",
                "isSingleVersion": false,
                "isRange": true,
                "releaseTimestamp": "2018-08-28T20:20:42.334Z",
                "canBeUnpublished": false
              }
            ],
            "warnings": [],
            "repositoryUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped",
            "releases": [
              "7.0.69",
              "8.0.0",
              "8.0.1",
              "8.0.2",
              "8.0.3",
              "8.0.4",
              "8.0.5",
              "8.0.6",
              "8.0.7",
              "8.0.8",
              "8.0.9",
              "8.0.10",
              "8.0.11",
              "8.0.12",
              "8.0.13",
              "8.0.14",
              "8.0.15",
              "8.0.16",
              "8.0.17",
              "8.0.18",
              "8.0.19",
              "8.0.20",
              "8.0.21",
              "8.0.22",
              "8.0.23",
              "8.0.24",
              "8.0.25",
              "8.0.26",
              "8.0.27",
              "8.0.28",
              "8.0.29",
              "8.0.30",
              "8.0.31",
              "8.0.32",
              "8.0.33",
              "8.0.34",
              "8.0.35",
              "8.0.36",
              "8.0.37",
              "8.0.38",
              "8.0.39",
              "8.0.40",
              "8.0.41",
              "8.0.42",
              "8.0.43",
              "8.0.44",
              "8.0.45",
              "8.0.46",
              "8.0.47",
              "8.0.48",
              "8.0.49",
              "8.0.50",
              "8.0.51",
              "8.0.52",
              "8.0.53",
              "8.0.54",
              "8.0.55",
              "8.0.56",
              "8.0.57",
              "8.0.58",
              "8.5.0",
              "8.5.1",
              "8.5.2",
              "8.5.3",
              "8.5.4",
              "8.5.5",
              "8.5.6",
              "8.5.7",
              "8.5.8",
              "8.5.9",
              "8.5.10",
              "8.9.0",
              "8.9.1",
              "8.9.2",
              "8.9.3",
              "8.9.4",
              "8.9.5",
              "8.10.0",
              "8.10.1",
              "8.10.2",
              "8.10.3",
              "8.10.4",
              "8.10.5",
              "8.10.6",
              "8.10.7",
              "8.10.8",
              "8.10.9",
              "8.10.10",
              "8.10.11",
              "8.10.12",
              "8.10.13",
              "8.10.14",
              "8.10.15",
              "8.10.16",
              "8.10.17",
              "8.10.18",
              "8.10.19",
              "8.10.20",
              "8.10.21",
              "8.10.22",
              "8.10.23",
              "8.10.24",
              "8.10.25",
              "8.10.26",
              "8.10.27",
              "8.10.28",
              "9.3.0",
              "9.4.0",
              "9.4.1",
              "9.4.2",
              "9.4.3",
              "9.4.4",
              "9.4.5",
              "9.4.6",
              "9.4.7",
              "9.6.0",
              "9.6.1",
              "9.6.2",
              "9.6.3",
              "9.6.4",
              "9.6.5",
              "9.6.6",
              "9.6.7",
              "9.6.8",
              "9.6.9",
              "9.6.10",
              "9.6.11",
              "9.6.12",
              "9.6.13",
              "9.6.14",
              "9.6.15",
              "9.6.16",
              "9.6.17",
              "9.6.18",
              "9.6.19",
              "9.6.20",
              "9.6.21",
              "9.6.22",
              "9.6.23",
              "9.6.24",
              "9.6.25",
              "9.6.26",
              "9.6.27",
              "9.6.28",
              "9.6.29",
              "9.6.30",
              "10.0.0",
              "10.0.1",
              "10.0.2",
              "10.0.3",
              "10.0.4",
              "10.0.5",
              "10.0.6",
              "10.0.7",
              "10.0.8",
              "10.0.9",
              "10.0.10",
              "10.1.0",
              "10.1.1",
              "10.1.2",
              "10.1.3",
              "10.1.4",
              "10.3.0",
              "10.3.1",
              "10.3.2",
              "10.3.3",
              "10.3.4",
              "10.3.5",
              "10.3.6",
              "10.5.0",
              "10.5.1",
              "10.5.2",
              "10.5.3",
              "10.5.4",
              "10.5.5",
              "10.5.6",
              "10.5.7",
              "10.5.8",
              "10.7.0",
              "10.7.1",
              "10.7.2",
              "10.9.0",
              "10.9.1",
              "10.9.2",
              "10.9.3"
            ]
          },
          {
            "depType": "dependencies",
            "depName": "app-root-dir",
            "versionScheme": "semver",
            "currentValue": "^1.0.2",
            "purl": "pkg:npm/app-root-dir",
            "prettyDepType": "dependency",
            "lockedVersion": "1.0.2",
            "updates": [],
            "warnings": [],
            "repositoryUrl": "https://github.com/philidem/node-app-root-dir",
            "releases": []
          },
          {
            "depType": "devDependencies",
            "depName": "rimraf",
            "versionScheme": "semver",
            "currentValue": "2.6.2",
            "purl": "pkg:npm/rimraf",
            "prettyDepType": "devDependency",
            "lockedVersion": "2.6.2",
            "updates": [],
            "warnings": [],
            "repositoryUrl": "https://github.com/isaacs/rimraf",
            "releases": []
          },
          {
            "depType": "devDependencies",
            "depName": "tslint",
            "versionScheme": "semver",
            "currentValue": "5.11.0",
            "purl": "pkg:npm/tslint",
            "prettyDepType": "devDependency",
            "lockedVersion": "5.11.0",
            "updates": [],
            "warnings": [],
            "repositoryUrl": "https://github.com/palantir/tslint",
            "releases": []
          },
          {
            "depType": "devDependencies",
            "depName": "typescript",
            "versionScheme": "semver",
            "currentValue": "3.0.3",
            "purl": "pkg:npm/typescript",
            "prettyDepType": "devDependency",
            "lockedVersion": "3.0.3",
            "updates": [],
            "warnings": [],
            "repositoryUrl": "https://github.com/Microsoft/TypeScript",
            "homepage": "http://typescriptlang.org/",
            "releases": []
          }
        ],
        "packageJsonName": "require-from-app-root",
        "packageJsonVersion": "0.2.0",
        "packageJsonType": "library",
        "yarnLock": "yarn.lock",
        "skipInstalls": true
      }
    ]
  }
}
DEBUG: branchifyUpgrades
DEBUG: 0 updates found
DEBUG:
{
  "upgradeNames": []
}
DEBUG: Returning 0 branch(es)
DEBUG: config.repoIsOnboarded=true
INFO: Processing 0 branch(es)
INFO: PR hourly limit remaining: 2
DEBUG: Enforcing prConcurrentLimit (20)
DEBUG: 0 PRs are currently open
INFO: PR concurrent limit remaining: 20
DEBUG: branchPrefix: renovate/
DEBUG: Found 1 Renovate PRs
{
  "renovatePrs": [
    {
      "number": 9,
      "branchName": "chore/reconfigure-renovate",
      "sha": "e73b52023f9685ffde8e83fea5dba6da3bd28f80",
      "title": "chore(Renovate): enable @types/node upgrades",
      "state": "open",
      "createdAt": "2018-08-30T11:50:22Z",
      "closed_at": null,
      "sourceRepo": "Joge97/require-from-app-root"
    }
  ]
}
DEBUG: getPrFiles
{
  "prNo": 9
}
DEBUG: GET repos/Joge97/require-from-app-root/pulls/9/files [retries=5]
INFO: PR has renovate files
{
  "prNo": 9,
  "title": "chore(Renovate): enable @types/node upgrades",
  "renovateFiles": [
    "renovate.json"
  ]
}
DEBUG: GET repos/Joge97/require-from-app-root/git/trees/e73b52023f9685ffde8e83fea5dba6da3bd28f80?recursive=true [retries=5]
DEBUG: Retrieved fileList with length 10
DEBUG: GET repos/Joge97/require-from-app-root/contents/renovate.json?ref=e73b52023f9685ffde8e83fea5dba6da3bd28f80 [retries=5]
DEBUG: Validating config
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "updateLockFiles": true,
    "baseBranches": [
      "develop"
    ],
    "packageRules": [
      {
        "packageNames": [
          "@types/node"
        ],
        "major": {
          "enabled": true
        }
      }
    ]
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "updateLockFiles": true,
    "baseBranches": [
      "develop"
    ],
    "packageRules": [
      {
        "packageNames": [
          "@types/node"
        ],
        "major": {
          "enabled": true
        }
      }
    ]
  }
}
DEBUG: Ensuring comment "Renovate Configuration Errors" in #9 is removed
DEBUG: Getting comments for #9
DEBUG: GET repos/Joge97/require-from-app-root/issues/9/comments?per_page=100 [retries=5]
DEBUG: Found 0 comments
INFO: Setting PR validation status
{
  "status": "success",
  "description": "Renovate config is valid"
}
DEBUG: GET repos/Joge97/require-from-app-root/git/refs/heads/chore/reconfigure-renovate [retries=5]
DEBUG: GET repos/Joge97/require-from-app-root/commits/e73b52023f9685ffde8e83fea5dba6da3bd28f80/statuses [retries=5]
INFO: Setting branch status
{
  "branchName": "chore/reconfigure-renovate",
  "context": "renovate/validate",
  "state": "success"
}
DEBUG: POST repos/Joge97/require-from-app-root/statuses/e73b52023f9685ffde8e83fea5dba6da3bd28f80 [retries=5]
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: branchList
{
  "branchList": []
}
DEBUG: GET repos/Joge97/require-from-app-root/git/refs/heads/renovate/ [retries=5]
DEBUG: No renovate branches found
DEBUG: ensureIssueClosing()
DEBUG: GET repos/Joge97/require-from-app-root/issues?filter=created&state=open [retries=5]
INFO: Finished repository
</details>

**Comment by rarkins** [comment]
Based on that log, the packageRule is not there in your config:

```
{
  "config": {
    "extends": [
      "config:base",
      "config:js-lib",
      ":semanticCommitScope(dependencies)"
    ],
    "baseBranches": [
      "develop"
    ],
    "updateLockFiles": true
  }
}
```

Perhaps you need to update the `renovate.json` in the base branch (e.g. `master`) and not in `develop`? Renovate config must be in the default branch of a repo.

**Comment by Joge97** [comment]
Now everything worked fine. Thank you for your help.
