### ISSUE TITLE
GitHub package type

### ISSUE THREAD

**Issue by evanstoddard23** [renovatebot/config-help#870]
### Which Renovate are you using?
WhiteSource Renovate App

### Which platform are you using?
GitHub.com

### What would you like to do?
I'm trying to restrict enabled managers, however I don't see GitHub as an option[ here](https://docs.renovatebot.com/modules/manager/). Is there a way to enable only GitHub?

**Comment by viceice** [comment]
There is no github manager in Renovate. Can you please share some more information what you try to do?

**Comment by evanstoddard23** [comment]
I get PRs from Renovate with the "type" as "github". Is that tied to a specific manager?

**Comment by viceice** [comment]
For which file and which package did you got the pr?

**Comment by evanstoddard23** [comment]
It's a `.tf` file looking like this:

```hcl
module "alb" {
  - source = "git@github.com:xxxx.git?ref=v1.4.0"
  + source = "git@github.com:xxxx.git?ref=v1.5.0"
...```

**Comment by viceice** [comment]
Tf files are managed by Terraform manager

**Comment by evanstoddard23** [comment]
I also get PRs with the type as "terraform" looking like this:

This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [aws](https://registry.terraform.io/providers/hashicorp/aws) ([source](https://togithub.com/terraform-providers/terraform-provider-aws)) | terraform | major | `~> 2.0` -> `~> 3.0` |

**Comment by evanstoddard23** [comment]
So does the terraform package manager handle both? I guess what I'm confused by is the "Type" field in the PR description.

**Comment by viceice** [comment]
Yes, Terraform manager handle's multiple different dependencies.

https://github.com/renovatebot/renovate/blob/9c94b3c45b40c810f90c4f307eea6bbc63a3fcff/lib/manager/terraform/modules.ts#L32

**Comment by evanstoddard23** [comment]
Sweet, thanks for looking into this! Are there/could you point me to docs that explain what is meant by the "type" field of the PR?

**Comment by rarkins** [comment]
The type field refers to the depType field which is extracted by the package manager. Its meaning varies per-manager, e.g. for npm it's dependencies/devDependencies/peerDependencies. Table columns are configurable, so you can remove it if you don't like it.
