### ISSUE TITLE
preventing existing pr updates outside of schedule window & keeping those pr's up to date with target branch changes

### ISSUE THREAD

**Issue by gibbsonn** [renovatebot/config-help#875]
### Which Renovate are you using?
Renovate Open Source CLI v 21.3.0

### Which platform are you using?
Azure DevOps

### What would you like to do?

I'd like to make it so that renovate only updates existing PR's with latest version's published when it's inside the schedule window. When outside of the schedule window I'd like renovate to just keep the PR's updated with target branch by using `"rebaseWhen": "behind-base-branch"`

But when I have a config with schedule set and rebaseWhen set it will update the PR's with newly published versions outside of the schedule window.

And if I add in `"updateNotScheduled": false`, then this prevents `"rebaseWhen": "behind-base-branch"` from working outside of the schedule window.

Any suggestions on what config I need to achieve this?

**Comment by rarkins** [comment]
This is not configurable today. Partly it will depend on https://github.com/renovatebot/renovate/issues/4866 to be implemented.

Are you wishing for the following?
- If a newer version is released then don't update the PR
- If the PR falls behind the master commit then rebase it

**Comment by gibbsonn** [comment]
yes, when outside the window that's exactly what I'm aiming for

**Comment by rarkins** [comment]
For the indefinite future if there's a need to rebase then there any updates *will* also get included too. You see, we don't do a "real" git rebase, what we're actually doing is recreating the branch again from the newer commit. Whatever versions were on the origin branch is not part of our decision making. i.e. we can either leave the branch alone, or we can recreate it. I think it would be a while until we can try to use the existing branch as a source of truth when it comes to parsing versions.

**Comment by gibbsonn** [comment]
fair enough, thanks for the update 👍
