### ISSUE TITLE
Extends gitlab> doesn't work with sub group

### ISSUE THREAD

**Issue by jeff-cook** [renovatebot/config-help#876]
### Which Renovate are you using?
Renovate Open Source CLI
Other (please write below)
renovate/renovate:21.25.1

### Which platform are you using?

GitLab.com
### Have you checked the logs? Don't forget to include them if relevant

```
renovate_1  |  INFO: Throwing preset error
renovate_1  |        "validationError": "Cannot find preset's package (gitlab>group/subgroup/renovate-bot)"
renovate_1  | FATAL: Fatal error: config-validation
renovate_1  |        "err": {
renovate_1  |          "validationError": "Cannot find preset's package (gitlab>group/subgroup/renovate-bot)",
renovate_1  |          "message": "config-validation",
renovate_1  |          "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:221:35)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
renovate_1  |        }
renovate_1  | (node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'redisUrl' of undefined
renovate_1  |     at Object.cleanup (/usr/src/app/node_modules/renovate/dist/util/cache/package/index.js:68:16)
renovate_1  |     at Object.globalFinalize (/usr/src/app/node_modules/renovate/dist/workers/global/initialize.js:66:18)
renovate_1  |     at Object.start (/usr/src/app/node_modules/renovate/dist/workers/global/index.js:89:22)
renovate_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
### What would you like to do?

When using `RENOVATE_EXTENDS=gitlab>group/subgroup/renovate-bot` renovate can't find the config. 
However, it works with `RENOVATE_EXTENDS=gitlab>group/renovate-bot`

It looks like the subgroup path in GitLab is not supported by renovate extends option. https://docs.renovatebot.com/config-presets/

I could not find an open issue for this.

**Comment by jeff-cook** [comment]
Oh maybe the issue is a group name in upper case. 
`RENOVATE_EXTENDS=gitlab>GROUP/renovate-bot`
fails with `"Cannot find preset's package (gitlab>>GROUP/renovate-bot)"`

**Comment by rarkins** [comment]
The source code for fetching gitlab presets is here: https://github.com/renovatebot/renovate/blob/master/lib/config/presets/gitlab/index.ts

If that doesn't help, we'd need a public reproduction on gitlab.com so we can debug. Have you logged with debug-level logging to see if it tells you the URL that fails?
