### ISSUE TITLE
Renovate - AutoClosed PR's

### ISSUE THREAD

**Issue by Rahul-learn** [renovatebot/config-help#879]
### Which Renovate are you using?

Renovate Open Source CLI

 ### Which platform are you using?

GitHub Enterprise

### What would you like to do?

We are using opensource renovate in our organization. In the last execution Renovate autoclosed all the PR's created by renovate. There is no change in the configuration and repository. I am wondering what might cause this issue?

**Comment by rarkins** [comment]
Your debug logs will tell you.

**Comment by Rahul-learn** [comment]
We lost those logs where it autclosed the PR's. If I execute Renovate again, I am seeing below in logs

Retrieved closed PR list with graphql (repository=******)
       "prNumbers": [
         112,
         113,
         114,
         115,
         116,
         117,
         118,
         119,
         120,

**Comment by viceice** [comment]
Cause you provide very little information we can only guess your registry was down while renovate was running. So renovate will autoclose all PR.

As you are running self hosted renovate you can try configure `abortIgnoreStatusCodes` to stop renovate closing when registry is down.

**Comment by Rahul-learn** [comment]
Registry was up all the time. Now,I would like Renovate to recreate those PR's again during next execution but its not doing that. anything in the settings I have to update?

**Comment by viceice** [comment]
They should be automatically open when a new version is available. 

Can you provide a reproduction repo please.

Please share your renovate config (sanitize confidential data) and some dependency which caused an auto closed or.

**Comment by Rahul-learn** [comment]
Just a basic configuration
####config.json
{ "platform": "github", "endpoint": "https://github.*****.com/api/v3",
    "logLevel": "debug","repositories":
    ["org/repo"] }
####renovate.json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}

####Example:

Package | Update | Change
-- | -- | --
org.powermock:powermock-module-junit4 (source) | patch | 2.0.2 -> 2.0.7

####Autoclosed message
changed the title Update dependency org.powermock:powermock-module-junit4 to v2.0.7 Update dependency org.powermock:powermock-module-junit4 to v2.0.7 - autoclosed 5 days ago
closed this 5 days ago
deleted the renovate/org.powermock-powermock-module-junit4-2.x branch 5 days ago

**Comment by rarkins** [comment]
What do your new logs say about that dependency?

**Comment by Rahul-learn** [comment]
I am getting below error 

"errMessage": "Command failed: ./gradlew --init-script renovate-plugin.gradle renovate\nException in thread \"main\" java.lang.RuntimeException: Could not create parent directory for lock file /.gradle/wrapper/dists/gradle/****\n\tat

**Comment by rarkins** [comment]
It's related to Gradle - it has a permissions problem and/or a stuck lock file. Try deleting any storage you attached. Not something we can help you any further with.
