### ISSUE TITLE
Can't configure "at any time" schedule for internal packages

### ISSUE THREAD

**Issue by alexkaufman06** [renovatebot/config-help#880]
### Which Renovate are you using? "renovate": "^21.33.15"

WhiteSource Renovate App

### Which platform are you using?

Bitbucket Cloud

### Have you checked the logs? Don't forget to include them if relevant

Sep 23, 2020 @ 11:52:06.468 | {"id":"df65b9bf-beb9-44f8-abf2-ccade827f1f7","level":"info","message":" INFO: Repository finished (repository=test)\n       \"durationMs\": 20079\n","appId":"Unknown","timestamp":"2020-09-23T18:52:06.464Z"}
-- | --

  |   | Sep 23, 2020 @ 11:52:06.442 | {"id":"4e623c1d-fc25-4e59-bd42-b716663adf90","level":"info","message":" WARN: Error finding issues (repository=test)\n       \"err\": {\n         \"name\": \"HTTPError\",\n         \"hostname\": \"api.bitbucket.org\",\n         \"method\": \"GET\",\n         \"path\": \"/2.0/repositories/test/issues?q=title%3D%22Action%20Required%3A%20Fix%20Renovate%20Configuration%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n         \"protocol\": \"https:\",\n         \"url\": \"https://api.bitbucket.org/2.0/repositories/test/issues?q=title%3D%22Action%20Required%3A%20Fix%20Renovate%20Configuration%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n         \"gotOptions\": {\n           \"path\": \"/2.0/repositories/test/issues?q=title%3D%22Action%20Required%3A%20Fix%20Renovate%20Configuration%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n           \"protocol\": \"https:\",\n           \"hostname\": \"api.bitbucket.org\",\n           \"hash\": \"\",\n           \"search\": \"?q=title%3D%22Action%20Required%3A%20Fix%20Renovate%20Configuration%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22enovate_bot_sa%22\",\n           \"pathname\": \"/2.0/repositories/test/issues\",\n           \"href\": \"https://api.bitbucket.org/2.0/repositories/test/issues?q=title%3D%22Action%20Required%3A%20Fix%20Renovate%20Configuration%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n           \"retry\": {\n             \"methods\": {},\n             \"statusCodes\": {},\n             \"errorCodes\": {},\n             \"maxRetryAfter\": 60000\n           },\n           \"headers\": {\n             \"user-agent\": \"https://github.com/renovatebot/renovate\",\n             \"accept\": \"application/json\",\n             \"accept-encoding\": \"gzip, deflate\"\n           },\n           \"hooks\": {\n             \"beforeRequest\": [],\n             \"beforeRedirect\": [null],\n             \"beforeRetry\": [],\n             \"afterResponse\": [],\n             \"beforeError\": [],\n             \"init\": []\n           },\n           \"decompress\": true,\n           \"throwHttpErrors\": true,\n           \"followRedirect\": true,\n           \"stream\": false,\n           \"form\": false,\n           \"json\": true,\n           \"cache\": false,\n           \"useElectronNet\": false,\n           \"method\": \"GET\",\n           \"hostType\": \"bitbucket\",\n           \"baseUrl\": \"https://api.bitbucket.org/\",\n           \"auth\": \"renovate_bot_sa:***********\",\n           \"gotTimeout\": {\"request\": 60000}\n         },\n         \"statusCode\": 403,\n         \"statusMessage\": \"Forbidden\",\n         \"headers\": {\n           \"server\": \"nginx\",\n           \"vary\": \"Authorization\",\n           \"content-type\": \"application/json; charset=utf-8\",\n           \"x-oauth-scopes\": \"pullrequest:write\",\n           \"x-b3-traceid\": \"a95488187690d5cd\",\n           \"x-dc-location\": \"ash2\",\n           \"strict-transport-security\": \"max-age=31536000; includeSubDomains; preload\",\n           \"date\": \"Wed, 23 Sep 2020 18:52:06 GMT\",\n           \"x-served-by\": \"app-3002\",\n           \"etag\": \"\\\"430e2709edbceff6cefb79aef573a6b1\\\"\",\n           \"x-static-version\": \"2bb6abf92372\",\n           \"x-credential-type\": \"apppassword\",\n           \"x-render-time\": \"0.0240969657898\",\n           \"x-accepted-oauth-scopes\": \"issue\",\n           \"connection\": \"close\",\n           \"x-version\": \"2bb6abf92372\",\n           \"x-request-count\": \"4492\",\n           \"x-frame-options\": \"SAMEORIGIN\",\n           \"content-length\": \"172\"\n         },\n         \"body\": {\n           \"type\": \"error\",\n           \"error\": {\n             \"message\": \"Your credentials lack one or more required privilege scopes.\",\n             \"detail\": {\"granted\": [\"pullrequest:write\"], \"required\": [\"issue\"]}\n           }\n         },\n         \"message\": \"Response code 403 (Forbidden)\",\n         \"stack\": \"HTTPError: Response code 403 (Forbidden)\\n    at EventEmitter.<anonymous> (/app/node_modules/got/source/as-promise.js:74:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\"\n       }\n","appId":"Unknown","timestamp":"2020-09-23T18:52:06.440Z"}

  |   | Sep 23, 2020 @ 11:51:52.954 | {"id":"8b3b9e70-ec72-455d-a327-aef88e89d7d3","level":"info","message":" INFO: Dependency extraction complete (repository=test)\n       \"baseBranch\": \"master\",\n       \"stats\": {\n         \"managers\": {\n           \"dockerfile\": {\"fileCount\": 1, \"depCount\": 1},\n           \"npm\": {\"fileCount\": 1, \"depCount\": 18}\n         },\n         \"total\": {\"fileCount\": 2, \"depCount\": 19}\n       }\n","appId":"Unknown","timestamp":"2020-09-23T18:51:52.954Z"}

  |   | Sep 23, 2020 @ 11:51:50.416 | {"id":"a8f9fa3a-5c37-40bc-8fc7-1950664c8f1a","level":"info","message":" WARN: Error finding issues (repository=test)\n       \"err\": {\n         \"name\": \"HTTPError\",\n         \"hostname\": \"api.bitbucket.org\",\n         \"method\": \"GET\",\n         \"path\": \"/2.0/repositories/test/issues?q=title%3D%22Action%20required%3A%20Add%20a%20Renovate%20config%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n         \"protocol\": \"https:\",\n         \"url\": \"https://api.bitbucket.org/2.0/repositories/test/issues?q=title%3D%22Action%20required%3A%20Add%20a%20Renovate%20config%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n         \"gotOptions\": {\n           \"path\": \"/2.0/repositories/test/issues?q=title%3D%22Action%20required%3A%20Add%20a%20Renovate%20config%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n           \"protocol\": \"https:\",\n           \"hostname\": \"api.bitbucket.org\",\n           \"hash\": \"\",\n           \"search\": \"?q=title%3D%22Action%20required%3A%20Add%20a%20Renovate%20config%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n           \"pathname\": \"/2.0/repositories/test/issues\",\n           \"href\": \"https://api.bitbucket.org/2.0/repositories/test/issues?q=title%3D%22Action%20required%3A%20Add%20a%20Renovate%20config%22%20AND%20(state%20%3D%20%22new%22%20OR%20state%20%3D%20%22open%22)%20AND%20reporter.username%3D%22renovate_bot_sa%22\",\n           \"retry\": {\n             \"methods\": {},\n             \"statusCodes\": {},\n             \"errorCodes\": {},\n             \"maxRetryAfter\": 60000\n           },\n           \"headers\": {\n             \"user-agent\": \"https://github.com/renovatebot/renovate\",\n             \"accept\": \"application/json\",\n             \"accept-encoding\": \"gzip, deflate\"\n           },\n           \"hooks\": {\n             \"beforeRequest\": [],\n             \"beforeRedirect\": [null],\n             \"beforeRetry\": [],\n             \"afterResponse\": [],\n             \"beforeError\": [],\n             \"init\": []\n           },\n           \"decompress\": true,\n           \"throwHttpErrors\": true,\n           \"followRedirect\": true,\n           \"stream\": false,\n           \"form\": false,\n           \"json\": true,\n           \"cache\": false,\n           \"useElectronNet\": false,\n           \"method\": \"GET\",\n           \"hostType\": \"bitbucket\",\n           \"baseUrl\": \"https://api.bitbucket.org/\",\n           \"auth\": \"test:***********\",\n           \"gotTimeout\": {\"request\": 60000}\n         },\n         \"statusCode\": 403,\n         \"statusMessage\": \"Forbidden\",\n         \"headers\": {\n           \"server\": \"nginx\",\n           \"vary\": \"Authorization\",\n           \"content-type\": \"application/json; charset=utf-8\",\n           \"x-oauth-scopes\": \"pullrequest:write\",\n           \"x-b3-traceid\": \"0cadce1d6defb358\",\n           \"x-dc-location\": \"ash2\",\n           \"strict-transport-security\": \"max-age=31536000; includeSubDomains; preload\",\n           \"date\": \"Wed, 23 Sep 2020 18:51:50 GMT\",\n           \"x-served-by\": \"app-3027\",\n           \"etag\": \"\\\"430e2709edbceff6cefb79aef573a6b1\\\"\",\n           \"x-static-version\": \"2bb6abf92372\",\n           \"x-credential-type\": \"apppassword\",\n           \"x-render-time\": \"0.0233800411224\",\n           \"x-accepted-oauth-scopes\": \"issue\",\n           \"connection\": \"close\",\n           \"x-version\": \"2bb6abf92372\",\n           \"x-request-count\": \"1020\",\n           \"x-frame-options\": \"SAMEORIGIN\",\n           \"content-length\": \"172\"\n         },\n         \"body\": {\n           \"type\": \"error\",\n           \"error\": {\n             \"message\": \"Your credentials lack one or more required privilege scopes.\",\n             \"detail\": {\"granted\": [\"pullrequest:write\"], \"required\": [\"issue\"]}\n           }\n         },\n         \"message\": \"Response code 403 (Forbidden)\",\n         \"stack\": \"HTTPError: Response code 403 (Forbidden)\\n    at EventEmitter.<anonymous> (/app/node_modules/got/source/as-promise.js:74:19)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\"\n       }\n","appId":"Unknown","timestamp":"2020-09-23T18:51:50.415Z"}

  |   | Sep 23, 2020 @ 11:51:46.384 | {"id":"090b7ab0-1dd5-4efa-8f83-629027c3595c","level":"info","message":" INFO: Repository started (repository=test)\n       \"renovateVersion\": \"21.33.15\"\n","appId":"Unknown","timestamp":"2020-09-23T18:51:46.384Z"}

### What would you like to do?

I would like to set a schedule for all npm packages except have an "at any time" schedule for packages internal to my company. Here is my current `renovate.json` setup that isn't working.

`{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "branchPrefix": "renovate-",
    "hostRules": [
        {
            "domainName": "github.com",
            "token": "myToken (this was replaced for security reasons)"
        }
    ],
    "prConcurrentLimit": 6,
    "timezone": "America/Los_Angeles",
    "schedule": [
        "after 10pm every weekday",
        "before 5am every weekday",
        "every weekend"
    ],
    "packageRules": [
        {
            "depTypeList": [
                "dependencies"
            ],
            "rangeStrategy": "replace"
        },
        {
            "depTypeList": [
                "devDependencies"
            ],
            "rangeStrategy": "pin"
        },
        {
            "depTypeList": [
                "peerDependencies"
            ],
            "rangeStrategy": "widen"
        },
        {
            "packagePatterns": [
                "@myInternalPackages"
            ],
            "groupName": "internal",
            "schedule": [
                "at any time"
            ]
        },
        {
            "packagePatterns": [
                "mocha"
            ],
            "groupName": "mocha"
        },
        {
            "packagePatterns": [
                "chai"
            ],
            "groupName": "chai"
        }
    ]
}`

**Comment by rarkins** [comment]
Please reformat your post as it's currently unreadable

**Comment by alexkaufman06** [comment]
This one has a better description: https://github.com/renovatebot/config-help/issues/881
