### ISSUE TITLE
Have assignees from codeowners

### ISSUE THREAD

**Issue by GuillaumeRahbari** [renovatebot/config-help#882]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Here are the logs https://app.renovatebot.com/dashboard#github/PayFit/permissions/236160457
Here is the name of a branch example: renovate/jnsight-monorepo

### What would you like to do?

I have a github team and I would like for renovate to assign 1 member of the team as "github assignee" and 2 members of the team as "github reviewers" in 2 cases:
- when it is a major version and cannot be automatically merge (by config)
- when it is a PR (that should automatically be merged) that have a failing github pipeline.

I tried to achieve that with "github code owners".
Here is my configuration so far:
```json
{
  "extends": [
    "config:base",
    ":automergeRequireAllStatusChecks"
  ],
  "packageRule": [
     {
            "updateTypes": [
                "minor",
                "patch",
                "pin",
                "digest",
                "lockFileMaintenance"
            ],
            "automerge": true
        }
  ],
  "reviewers": ["team:user-access"],
  "assigneesFromCodeOwners": true,
  "assigneesSampleSize": 1
}
```

And here is our file .github/CODEOWNERS
```
/ @Payfit/user-access
``` 

For now it does add reviewers from the team but it does not add assignees and I don't quite understand why.

Hope it was clear enough and if you need more details don't hesitate !

**Comment by rarkins** [comment]
Renovate will only add assignees and reviewers upon *PR creation*, so not for any pre-existing PRs. Can you confirm that you were testing with *new* PRs?

**Comment by rarkins** [comment]
Also, are you using CODEOWNERS purely because of Renovate? If so then there's really no need - would be easier to simply configure assignees directly into Renovate config.

**Comment by GuillaumeRahbari** [comment]
No, indeed I was only testing with PR already created.

So you mean that my configuration is ok ? I just need to wait for a new PR and see what happens ?

But in this case, would renovate add reviewers and assignees only when pipeline is failing for example ?

And yes I'm using CODEOWNERS only for renovate. I did not find in the documentation a way to add a github team as an assignee (it seems it only can be a user or an email https://docs.renovatebot.com/configuration-options/#assignees)

**Comment by rarkins** [comment]
FYI if you have CODEOWNERS then github itself will assign based on that. The assignFromCodeowners feature was only intended for platforms which don't support automatic assigning, although in theory it would work without problem.

I don't use CODEOWNERS myself so am not 100% sure but I'd recommend not using it if it's only for Renovate. With your current config I think GitHub would automatically assign that team to every PR, not just Renovate's.

I believe you can assign teams to PRs too. Maybe just try with `@Payfit/user-access`? Could be useful to have a test repo so that you don't annoy teammates with too much noise during testing. Once you can confirm it works, we should update the docs so that it's clear.

**Comment by GuillaumeRahbari** [comment]
Ok, so I did what you suggested.

I created a new repository and added some old dependencies to see how renovate would behave.

Here are the new logs: https://app.renovatebot.com/dashboard#github/PayFit/test-renovate

Here is my configuration:
```json
{
  "extends": [
    "config:base",
    ":automergeRequireAllStatusChecks"
  ],
  "packageRule": [
     {
            "updateTypes": [
                "minor",
                "patch",
                "pin",
                "digest",
                "lockFileMaintenance"
            ],
            "automerge": true
        }
  ],
  "reviewers": ["team:user-access"],
  "assignees": ["team:user-access"],
  "assigneesSampleSize": 1,
}
```
I did not add CODEOWNERS in this repo.

And here is what I just go from the log: 
![image](https://user-images.githubusercontent.com/6448497/94245231-3e704880-ff1a-11ea-96cf-bc1c868270d0.png)

But in the PR there is no one assigned as reviewers or assignees 🤔

**Comment by rarkins** [comment]
I'm not sure you can have same assignee and reviewer, but that shouldn't prevent the assignee from working. I need to dig into the syntax. Are you sure you shouldn't have team:PayFit/user-access ?

**Comment by GuillaumeRahbari** [comment]
I'll try by changing the team name. But it worked before for the assignee part so I used the same. But anyway I'll try with team:PayFit/user-access

**Comment by GuillaumeRahbari** [comment]
It seems it did not change something https://app.renovatebot.com/dashboard#github/PayFit/test-renovate/236182543
I still get neither of them.

**Comment by GuillaumeRahbari** [comment]
I am not sure github allows to add a team as "assignees", when I try manually I can only select member but not team (but in the "reviewers" part github allows me to select a team).

Anyway, our need behind this was to assign randomly one member of the team, that's why we are trying to find a solution for assigning a team. But it may be not possible if github does not allow it :/

**Comment by rarkins** [comment]
Perhaps in the past we only experimented with team reviewers and I misremembered. If you explicitly create the list of assignees in your Renovate config and include `assigneeSampleSize`=1 then I can't see why it wouldn't work.

**Comment by GuillaumeRahbari** [comment]
Ok, 

I tried. By creating a list of assignees it seems to work. Renovate assign one person of the list in renovate PRs. But only on non-major updates and I don't know why. 
The drawback of that is that we have to handle people in the github team and also in the renovate config (update team when someone on vacation for example). Do you know if I can request a feature for something like this ?

But, for the reviewers, renovate says on the logs that he added some, but no one was added (on every PRs)

**Comment by rarkins** [comment]
> But only on non-major updates and I don't know why.

Can you simplify your use case by first testing without automerge? In such a scenario, the logic is simplest: assignees are added at PR creation, or not. When automerging is involved then the logic is more complex (e.g. assigning only if non-automerging or if the commit status fails)

> Do you know if I can request a feature for something like this ?

Yes, please create a feature request for that in the main repo. I think what you're after is to ask Renovate to "learn" the assignees list from a team name? Be sure to also note that you need it work alongside the `assigneesSampleSize` feature too.

> But, for the reviewers, renovate says on the logs that he added some, but no one was added (on every PRs)

This will need further reproduction and troubleshooting, sounds like kind of a different problem. e.g. could be permissions, could be a bug, etc.

**Comment by GuillaumeRahbari** [comment]
> Can you simplify your use case by first testing without automerge? In such a scenario, the logic is simplest: assignees are added at PR creation, or not. When automerging is involved then the logic is more complex (e.g. assigning only if non-automerging or if the commit status fails)

Ok I understand now and it explains why it worked when renovate created a new major PR. The other I had where old ones created before I made the change on my settings.

> Yes, please create a feature request for that in the main repo. I think what you're after is to ask Renovate to "learn" the assignees list from a team name? Be sure to also note that you need it work alongside the assigneesSampleSize feature too.

Yes exactly. I will do that then !

> This will need further reproduction and troubleshooting, sounds like kind of a different problem. e.g. could be permissions, could be a bug, etc.

Yeah I don't know why it is not working. Could it be that "assignees" and "reviewers" cannot work together ? Before today I only had the "reviewers" part in the config and it was working well I would say. Since today where I tried adding "assignees" as well it does not work anymore. Anyway I continue some tries in my side too. About "permissions", do I have a way to find out if it is this kind of problem ?

**Comment by rarkins** [comment]
There shouldn't be anything stopping both working together. But Eg maybe GitHub prevents their being an overlap. If GitHub returns a successful response code then it's weird to not work. If it's a rejection then we should log it and hopefully learn the reason.

**Comment by GuillaumeRahbari** [comment]
I think I found the issue. I'll confirm it as soon as possible, but in the repo I created for the tests I forgot to give the rights to the team "user-access". I was not able to add the team as reviewer myself (directly on the PR), so I guess renovate could not too.

But I'll confirm if it was indeed that as soon as renovate run !

**Comment by GuillaumeRahbari** [comment]
Yeah it was that ! Thanks a lot for the help !
