### ISSUE TITLE
Unable to onboard after renovate was disabled

### ISSUE THREAD

**Issue by valentijnscholten** [renovatebot/config-help#884]
- I onboarded a public repo using the PR, but nothing happened.
- Found out about https://app.renovatebot.com/dashboard ( hard to find with google etc, but noticed a link in the onboarding PR at some point). But the link is not showing anything: https://app.renovatebot.com/dashboard#github/%7B%7Bplatform%7D%7D/%7B%7Brepository%7D%7D
- Went to app.renovatebot.com manually and found some logs
- Log says repo is disabled because issues are disabled, which makes sense.
- Enabled issues
- No instructions found on how to trigger onboarding again, so uninstalled renovate app
- Install again
- Nothing happens
- Observe logs, it mentioned that a PR exists so does nothing
- PR comment says:
```
Renovate is disabled
Renovate is disabled due to lack of config. If you wish to reenable it, you can either (a) commit a config file to your base branch, or (b) rename this closed PR to trigger a replacement onboarding PR.
```
- Create renovate.json and push to dev branch (which is my default)
- Nothing happens for 10 minutes
- Renamed the PR
- Nothing happens for 10 minutes
- Found other issues stating that you also need to delete the renovate/config branch
- Deleted that branch
- Nothing happens still
- Found a report that states disabled repo's are only checked once per day.
- But also found instructions that removing the renovate.json file and branch and renaming the PR should trigger onboarding
- Nothing happens.

So now I am not sure if I should wait 1 day? or till midnight? or do I need to uninstall - install again? Contact support?

Maybe some "Run now" or "Retry on boarding" or something is helpful. Would be a shame if you have to wait for 24 hours if the plan was to try renovate this evening.

My onboarding PR: https://github.com/valentijnscholten/django-DefectDojo/pull/9
Issue inspired by #831, #78, #781

Valentijn

**Comment by valentijnscholten** [comment]
So 1-2 hours later, a new PR was created after all.
I updated its config to make sure no PRs would be created for updates, but only the dashboard.

```
{
  "extends": [
    "config:base"
  ],
  "dependencyDashboardApproval": true
}
```

When I make a mistake in the json there is an almost instant error message in the description/summary of the on boarding PR. But with valid json, it gest updated again and it says it will create 25 PRs under expected results.

**Comment by valentijnscholten** [comment]
ok, just noticed that the dasboard issue is already created, so it seems to be picking up the conifg. Maybe the expected results need to reflect that.

**Comment by valentijnscholten** [comment]
hmm despite the config to need approval for PRs, some of the updates are marked as "Open"
![image](https://user-images.githubusercontent.com/4426050/94373550-57d5e800-0106-11eb-96d7-bfccc1388159.png)
Although there are no PRs for these?
Checking the logs it says there are branches for these 5 updates, but I don't see these branches in my repo.

**Comment by rarkins** [comment]
Unfortunately the Dependency Dashboard gets its state out of sync sometimes. There's some open issues in the main repo about it which are essentially all duplicates. We need to do some major refactoring to get accurate results every time, so that's why it hasn't been fixed quickly. Closing this as the original topic is resolved.
