### ISSUE TITLE
Auto-merge did not merge

### ISSUE THREAD

**Issue by djmitche** [renovatebot/config-help#885]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

[I have](https://app.renovatebot.com/dashboard#github/taskcluster/tc-admin/236935571)

### What would you like to do?

I'd like to automerge.  [This PR did not](https://github.com/taskcluster/tc-admin/pull/156).  Logs:

```
(branch="renovate/pytest-6.x")
DEBUG: Checking #156 for automerge(branch="renovate/pytest-6.x")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/pytest-6.x")
DEBUG: PR is not ready for merge(branch="renovate/pytest-6.x")
```

the PR itself has some comments looking into the source for that, but I didn't figure out much, and in particular I'm missing a reason for the PR not being ready.  I have confirmed:
 * auto-merge is enabled
 * this is using the non-forking app
 * require-status-checks is not enabled in the GitHub branches UI
 * all checks passed
 * branch is mergeable
 * there are no negative reviews (or any reviews)

**Comment by rarkins** [comment]
I'm not sure if our Dashboard lost an additional field or what, but there's some additional info in the last message when I check the *latest* log right now. Here's the raw message:

```
{"level":20,"branch":"renovate/pytest-6.x","canMergeReason":"mergeStateStatus = BLOCKED","msg":"PR is not ready for merge","time":"2020-09-28T06:13:33.207Z"}
```

That `BLOCKED` comes from this field in GitHub's API: https://developer.github.com/v4/enum/mergestatestatus/

Unfortunately it's not descriptive but it's the reason we don't attempt the automerge (GitHub prefers we don't "hammer" their API attempting to merge branches that aren't actually mergeable).

FYI in case you were attempting to try it, the `mergeStateStatus` field in Pull Requests requires a feature flag so unfortunately you can't query it using the GraphQL Explorer.

**Comment by djmitche** [comment]
Ah, I had looked at that but in typical GitHub style it's basically undocumented, as far as what "BLOCKED" means.  But it looks like, yes, it includes review status.

**Comment by rarkins** [comment]
I'm taking a guess that it means if you use `CODEOWNERS` then it essentially blocks automerge.

We *do* have https://github.com/apps/renovate-approve and https://github.com/apps/renovate-approve2 to automatically approve Renovate PRs for those who require 1 or 2 reviewers to merge PRs, *however* I think `CODEOWNER` takes precedence over that *and* unfortunately GitHub doesn't support adding apps as code owners.

I'm wondering whether to create another "real" user account and the Approve app can approve as both itself (the app) as well as this real user account. Then you could add the real user as a code owner and it might finally work, but it might also require that you add the real account with write access too, which is moderately undesirable.

**Comment by djmitche** [comment]
Even without any reviewers assigned:
```
DEBUG: PR is not ready for merge(branch="renovate/pytest-6.x")
{
  "canMergeReason": "mergeStateStatus = BLOCKED"
}
```
I've verified that this repo does not have "require reviews" enabled, but it did have "Restrict who can push to matching branches" .  I'll try adding "renovate" to that list.

**Comment by djmitche** [comment]
> I'm wondering whether to create another "real" user account and the Approve app can approve as both itself (the app) as well as this real user account. Then you could add the real user as a code owner and it might finally work, but it might also require that you add the real account with write access too, which is moderately undesirable.

An alternative is just to make the `setup.py`, `package.json`, etc. files *not* have any CODEOWNER.  That will probably work in the case of this repo, anyway.

GitHub really doesn't make this easy!

**Comment by rarkins** [comment]
> I've verified that this repo does not have "require reviews" enabled, but it did have "Restrict who can push to matching branches" . I'll try adding "renovate" to that list.

Ha, yes this could be another reason it's BLOCKED. I believe you *can* add an app to this field..

**Comment by djmitche** [comment]
So I did so and requested a rebase, and renovate obliged 23 minutes ago.  No auto-merge, and more curiously all of the recent logs for this repo have disappeared:

![image](https://user-images.githubusercontent.com/28673/94446431-a28f4880-0176-11eb-85e1-00503aff2f60.png)

**Comment by rarkins** [comment]
Hmm. I was cleaning out some years old job log IDs from the DB in recent hours but it wasn't meant to be removing any recent ones :-/

Are there ones missing that you saw previously or is it possible they newer ones just haven't been written ?

**Comment by djmitche** [comment]
Existing logs that I had seen (from <3 hours ago) are gone.

**Comment by rarkins** [comment]
The main DB had the following jobs for your repo around the time of writing:
![image](https://user-images.githubusercontent.com/6311784/94450345-7347fe00-01ad-11eb-81e6-80a6b03d33bb.png)

But the API is served from a read replica so it's perhaps out of sync somehow.

**Comment by rarkins** [comment]
I cleared out over 100 million old jobs from the primary cluster so maybe the replica is busy clearing those out and refuses to sync the new ones yet. Not sure how it could have *lost* any though.

**Comment by djmitche** [comment]
Well, logs question aside, this seems to have worked.  In the end:
 * ensure that branch protection allows `renovate` to push changes to the main/master branch
 * ensure that branch protection does not require reviews before merging
 * ensure that no reviewers are automatically added for renovate changes
