### ISSUE TITLE
PR's merged outside of "scheduled" configuration

### ISSUE THREAD

**Issue by JeremyKirkham** [renovatebot/config-help#887]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

We've setup renovate across all our repos, and are using the `schedule` config to only open and merge PR's during business hours, so that we have developers available in case of bugs from merged libraries. However, it doesn't appear that renovate's configuration is honouring what we set.

Our config in question looks like:
```
  "timezone": "Australia/Melbourne",
  "schedule": "after 8am and before 6pm every weekday",
```

**Comment by JeremyKirkham** [comment]
Reading the documentation for the `schedule` configuration it specifically says `Times of day/week to limit branch creation to`. Does the actual merging of PR's also respect the `schedule` configuration?

**Comment by rarkins** [comment]
Currently it does not. Please follow https://github.com/renovatebot/renovate/issues/4866 in the main repo so you can see once it's done.
