### ISSUE TITLE
dashboard: how to get alert / notification if new updates are awaiting approval

### ISSUE THREAD

**Issue by valentijnscholten** [renovatebot/config-help#890]
I am using dependencyDashboardApproval. So no PRs get created until approved on the dashboard. 

Can I get an alert / notification when new updates are added that need approval?

I am subscribed to the dashboard issue, but I don't think GitHub is sending notifications when the description is updated by renovate. Maybe renovate should add a comment? Comment could be deleted afterwards. 

Or on the next update remove the old comment and place a new one. The comment could contain some handy info like "last run of renovate" etc.

**Comment by rarkins** [comment]
That's not a supported feature and not something we'd want to do for github.com as we already consume a lot of API calls and adding/deleting a comment each time would be 2 more per-repo.

**Comment by valentijnscholten** [comment]
ok.
