### ISSUE TITLE
docs: high level explanation of how renovates PRs are working / designed

### ISSUE THREAD

**Issue by valentijnscholten** [renovatebot/config-help#891]
Hi,

I could be blind or my google-fu might be lacking today, but is there any high level explanation on how renovate PRs work?

Of course I found the documentation and all the configuration options, but couldn't find any description of how it works in general.
The most general info is placed on the github.com app homepage.

If you work with renovate everyday, my questions are probably going to sound stupid, but here they are.
I tried to answer them by just messing around with the package files and the dashboard. But I have no idea when renovate runs and there is no button or similar to trigger a run. 
It would take quite a while to find all the answers. Also the app.renovatebot.com log file page seems broken currently as it just keeps showing the three dotted loading symbol, so I can't really see what's going on currently.

Questions:

Question: what happens if there is both a minor/patch update available and a majord update available?
Assumption: 2 PRs will get created one for the minor and one for the major?

Question: what happens if I close a PR?
Assumption: When closing a PR for a minor update it will ignore that minor update, but will create a new PR for the next minor update? 
Assumption: When closing a PR for a major update it will ignore that major update allgother? So even when a new minor inside that majord update appears, it will NOT create a new PR?

Question: how can I ignore a specific major update?
Assumption: close the PR for that major update? But how to do it if minor/majors are not separate PRs?

Question: how can I ignore a specific minor update, but still get a PR for the next minor update? i.e. ignore update 4.2->4.3, but get a PR when 4.4 arrives?
Assumption: ?

While writing these questions, I found some answers or part of answers in the configurationoptions page. But they are on page 80 or 102. Reading 102 pages just get a feel for how it works is not ideal :-)

Maybe some extra info on each PR stating: "If you don't want to upgrade to vX, just close the PR and all vX.xx will be ignored" or "If you don't want to upgrade to v4.3, just close the PR and we will craete a new one when 4.4 arrives" (or we will reopen it when 4.4 arrives). Or is the idea to just leave it open for renovate to keep updating it? And then make myself a watcher on all those PRs to stay in the loop?

I am coming from dependabot where most interaction happens in the PRs themselves where you can mention the bot and ignore minor/major, etc. 

Valentijn

**Comment by rarkins** [comment]
> Hi,
> 
> I could be blind or my google-fu might be lacking today, but is there any high level explanation on how renovate PRs work?
> 
> Of course I found the documentation and all the configuration options, but couldn't find any description of how it works in general.
> The most general info is placed on the github.com app homepage.
> 
> If you work with renovate everyday, my questions are probably going to sound stupid, but here they are.
> I tried to answer them by just messing around with the package files and the dashboard. But I have no idea when renovate runs and there is no button or similar to trigger a run.
> It would take quite a while to find all the answers. Also the app.renovatebot.com log file page seems broken currently as it just keeps showing the three dotted loading symbol, so I can't really see what's going on currently.
> 
> Questions:
> 
> Question: what happens if there is both a minor/patch update available and a majord update available?
> Assumption: 2 PRs will get created one for the minor and one for the major?

Correct. See the separateMajorMinor separateMultipleMajor and separateMinorPatch options

> Question: what happens if I close a PR?
> Assumption: When closing a PR for a minor update it will ignore that minor update, but will create a new PR for the next minor update?
> Assumption: When closing a PR for a major update it will ignore that major update allgother? So even when a new minor inside that majord update appears, it will NOT create a new PR?

Closing an update e.g. from 1.0.0 to 1.1.0 means that 1.1.0 is ignored. Renovate will post a comment telling you this. If 1.1.1 or 1.2.0 comes out, then you'll get a new PR. Whereas if you get a PR from 1.0.0 to 2.0.0 then closing it will ignore *all* v2 versions. However if you later manually update e.g. to v2.1.0 or something like that then Renovate will start sending you updates for minor v2 versions when available

> Question: how can I ignore a specific major update?
> Assumption: close the PR for that major update? But how to do it if minor/majors are not separate PRs?

Answered above

> Question: how can I ignore a specific minor update, but still get a PR for the next minor update? i.e. ignore update 4.2->4.3, but get a PR when 4.4 arrives?
> Assumption: ?

For non-major updates, the ignoring is per exact version. So you can ignore 4.3.0 but if there's 4.3.1 then you'll get another PR.

For more explicit and permanent ignoring, you can use the configuration option `allowedVersions`.

> While writing these questions, I found some answers or part of answers in the configurationoptions page. But they are on page 80 or 102. Reading 102 pages just get a feel for how it works is not ideal :-)

All documentation is part of the open source repo too so once you've settled in then you're certainly welcome to kick off a "Most important things to know" doc that we can link to from the onboarding.

> Maybe some extra info on each PR stating: "If you don't want to upgrade to vX, just close the PR and all vX.xx will be ignored" or "If you don't want to upgrade to v4.3, just close the PR and we will craete a new one when 4.4 arrives" (or we will reopen it when 4.4 arrives). Or is the idea to just leave it open for renovate to keep updating it? And then make myself a watcher on all those PRs to stay in the loop?

The PRs already have text similar to what you stated. e.g. a live PR:

![image](https://user-images.githubusercontent.com/6311784/94516137-6cf56880-0225-11eb-8c48-231c8e29aaf8.png)

A closed/ignored PR:

![image](https://user-images.githubusercontent.com/6311784/94516170-81d1fc00-0225-11eb-9bb0-be8faf637565.png)

I recommend that instead of closing to ignore, you are better off to use the Dependency Dashboard so that you have full visibility, which I think you already discovered. e.g. in the Renovate repo we require approval for all major PRs, which is much superior to opening them immediately they are released and either (a) sitting on them for weeks or months, or (b) closing them and needing to reopen later.

> I am coming from dependabot where most interaction happens in the PRs themselves where you can mention the bot and ignore minor/major, etc.

As a general rule I don't like the "chat-based" approach for this type of stuff. e.g. if you are to ignore packages permanently then it's best to have it in your repo config instead of colleagues having to figure out why there's no updates for a certain dependency and it's because someone chatted with the bot about it in a closed PR months or years ago.

**Comment by valentijnscholten** [comment]
Thanks for the explanation, there are different approaches each with the pros and cons :-)
For me the logs are not appearing since yesterday, is this a know issue?
https://app.renovatebot.com/dashboard#github/valentijnscholten/django-DefectDojo
Currently my dashboard says "WARNING: Error pruning branch" and it seems to be stuck / not updating the dashboard.

**Comment by rarkins** [comment]
Can you take a screenshot of what you mean by "my dashboard says"?

**Comment by valentijnscholten** [comment]
![image](https://user-images.githubusercontent.com/4426050/94564097-d9915700-0267-11eb-95c9-16f2b532b9cb.png)

**Comment by valentijnscholten** [comment]
full screen:
![image](https://user-images.githubusercontent.com/4426050/94564135-e8780980-0267-11eb-878b-8cc807464037.png)

**Comment by valentijnscholten** [comment]
But I am now removing everything related to renovate and will try again

**Comment by viceice** [comment]
Did you have enabled any branch protection on GitHub?

**Comment by rarkins** [comment]
Could just be coincidence. I searched the bot's logs and only four occurrences in the past hour. I checked out the logs for one of them and found that the branch that was deleted was merged by the user around the same time.

**Comment by rarkins** [comment]
It would only be a concern if that WARN didn't go away after the next run

**Comment by valentijnscholten** [comment]
To try and get a fresh start, I did:
- remove renovate.json
- remove renovate/config branch
- rename dashboard
- uninstall renovate app

And then:
- reinstall renovate app

But no onboarding PR gets created. Logs are still not showing.

Just renamed the previous onboarding PR, maybe that helps.

**Comment by valentijnscholten** [comment]
> Did you have enabled any branch protection on GitHub?
> 
> Looks like renovate isn't allowed to delete branches.

no

**Comment by viceice** [comment]
Yes, renaming onboarding pr should do the trick. Maybe you need to disable and enable the app again.

Or @rarkins  can queue an explicit run.

**Comment by valentijnscholten** [comment]
any plans for a "Run now" button or "On board now" button? Despite all your hard work, it's now a not so nice onboarding.

**Comment by viceice** [comment]
Normally you have a checkbox on the dependency dashboard to trigger a new run. 🙃

**Comment by rarkins** [comment]
This help issue has reached the end of its original purpose.

**Comment by valentijnscholten** [comment]
> any plans for a "Run now" button or "On board now" button? Despite all your hard work, it's now a not so nice onboarding.
That didn't seem to be working anymore, so I tried to reinstall.

> Normally you have a checkbox on the dependency dashboard to trigger a new run. 🙃
I can try, but not sure if a run is triggered without logs.

> I haven't enjoyed your onboarding that much either, to be frank. I'm done!
I understand, but I thought reporting problems is usually appreciated as it can help make the onboarding easier.
