### ISSUE TITLE
Does adding hostRules override or extend the base configuration?

### ISSUE THREAD

**Issue by Xendar** [renovatebot/config-help#892]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

According to the documentation we can add custom hostRules, e.g. for Maven:
```
{
    "maven": {
        "enabled": true
    },
    "hostRules": [{
        "hostType": "maven",
        "endpoint": "https://artifactoryurl1/",
        "username": "artifactoryusername",
        "password": "artifactorypassword"
    }, {
        "hostType": "maven",
        "endpoint": "https://artifactoryurl2/",
        "username": "artifactoryusername",
        "password": "artifactorypassword"
    }],
    "packageRules": [{
        "managers": ["maven"],
        "registryUrls": ["https://artifactoryurl1/", "https://artifactoryurl2/"]
    }]
}
```

However what is not clear to me is:

- Does it extend or override the default host rule for Maven?
- With the configuration above, will Renovate search for
  - Updates on both artifactoryurl1 and artifactoryurl2?
  - Updates on artifactoryurl1, artifactoryurl2 and repo.maven.apache.org (according to [common.ts](https://github.com/renovatebot/renovate/blob/9730079d0c824e3d7240a48871a25cad4a74609f/lib/datasource/maven/common.ts#L3)?
- Should I want to search a package on only artifactoryurl1 and repo.maven.apache.org, what is the syntax? `"registryUrls": ["https://artifactoryurl1/", "https://repo.maven.apache.org"]`?

**Comment by rarkins** [comment]
> ### Which Renovate are you using?
> Renovate Open Source CLI
> 
> ### Which platform are you using?
> Bitbucket Server
> 
> ### Have you checked the logs? Don't forget to include them if relevant
> N/A
> 
> ### What would you like to do?
> According to the documentation we can add custom hostRules, e.g. for Maven:
> 
> 
> ```
> {
>     "maven": {
>         "enabled": true
>     },
>     "hostRules": [{
>         "hostType": "maven",
>         "endpoint": "https://artifactoryurl1/",
>         "username": "artifactoryusername",
>         "password": "artifactorypassword"
>     }, {
>         "hostType": "maven",
>         "endpoint": "https://artifactoryurl2/",
>         "username": "artifactoryusername",
>         "password": "artifactorypassword"
>     }],
>     "packageRules": [{
>         "managers": ["maven"],
>         "registryUrls": ["https://artifactoryurl1/", "https://artifactoryurl2/"]
>     }]
> }
> ```

This is a little out of date, but should still work. I recommend you use `hostName` in `hostRules` now instead of `endpoint`.
 
> However what is not clear to me is:
> 
> * Does it extend or override the default host rule for Maven?

The package rule does.

> * With the configuration above, will Renovate search for
>   
>   * Updates on both artifactoryurl1 and artifactoryurl2?

Yes

>   * Updates on artifactoryurl1, artifactoryurl2 and repo.maven.apache.org (according to [common.ts](https://github.com/renovatebot/renovate/blob/9730079d0c824e3d7240a48871a25cad4a74609f/lib/datasource/maven/common.ts#L3)?

No, because it's not in `registryUrls`

> * Should I want to search a package on only artifactoryurl1 and repo.maven.apache.org, what is the syntax? `"registryUrls": ["https://artifactoryurl1/", "https://repo.maven.apache.org"]`?

Use a more specific `packageRules` after the one above that specifies which `packageNames` should have a different set of `registryUrls`

**Comment by Xendar** [comment]
Okay, I made it work this way:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "onboardingConfig": {
    "extends": [
      "config:base"
    ]
  },
  "hostRules": [
    {
      "hostType": "maven",
      "hostName": "https://repository.mycompany.net/mvn-public/"
    }
  ],
  "java": {
    "packageRules": [
      {
        "packagePatterns": [
          "^com.mycompany."
        ],
        "registryUrls": [
          "https://repository.mycompany.net/mvn-public/"
        ]
      },
      {
        "packagePatterns": [
          "^com.mycompany.mytool"
        ],
        "enabled": false
      }
    ]
  }
}
```

1. Declaring a custom hostRule with private Artifactory
2. First package rule to declare that all packages starting with the company's groupId would be searched with the custom registry
3. Second package rule to disable the search for the tool's own artifacts

All confirmed in debug mode 👍

**Comment by rarkins** [comment]
I'm don't think that the first host rule is doing anything because both `hostType` and `hostName` are *matching* fields and don't actually "configure" anything once they match. But if you need to add auth then that's how you'd do it (e.g. add a `token` field so that object).

I also recommend removing the `java` object and putting that inside the `packageRules` instead (you can configure languages=["java"] or managers=["maven"] within the package rule).

**Comment by Xendar** [comment]
> I'm don't think that the first host rule is doing anything because both `hostType` and `hostName` are _matching_ fields and don't actually "configure" anything once they match. But if you need to add auth then that's how you'd do it (e.g. add a `token` field so that object).

Understood, I have some questions for authentication but I'll open a separate ticket :)
 
> I also recommend removing the `java` object and putting that inside the `packageRules` instead (you can configure languages=["java"] or managers=["maven"] within the package rule).

Actually I did it this way in order to avoid repeating the language/manager for each package rule, but if this is the recommended way then I'll update it as suggested, thanks!
