### ISSUE TITLE
Custom Version Bumps

### ISSUE THREAD

**Issue by bmaginni** [renovatebot/config-help#899]
### Which Renovate are you using?
23.36.4

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant
N/A

### What would you like to do?

If I'm targeting a Feature branch, I would like to be able to set a specific "custom" version based on the latest release version discovered for a Dependency.

e.g. 

t0
-repo
---depA v1.0.0
---depB v1.0.0

featurebranch
---depA v1.1.0-SNAPSHOT
---depB v1.0.0

t1
-repo
---depA v1.1.0
---depB v1.0.0

Apply renovate...
(I'd like it to be able discover that there is a new version v1.1.0
As I'm targeting my featurebranch, instead of incrementing to v.1.2.0 I'd like it to bump to v1.2.0-SNAPSHOT)

featurebranch
---depA v1.2.0-SNAPSHOT
---depB v1.0.0

I may be asking a lot, but curious as to if it is at all possible
Thanks

**Comment by viceice** [comment]
Use [`baseBranchList`](https://docs.renovatebot.com/configuration-options/#basebranchlist) and [`ignoreUnstable`](https://docs.renovatebot.com/configuration-options/#ignoreunstable) in [`packageRules`](https://docs.renovatebot.com/configuration-options/#packagerules)

**Comment by bmaginni** [comment]
Maybe I'm missing something from the docs

In the scenario I outlined v1.2.0-SNAPSHOT won't exist anywhere at renovate execution time.
I would like to take the latest release version found by renovate i.e. v1.1.0 

From that I look at my target branch (active feature-branch) and determine that my v1.1.0-SNAPSHOT is no longer valid and needs incremented to v.1.2.0-SNAPSHOT and then once checked in it will be built with that version

**Comment by viceice** [comment]
Then i don't understand your requirements. Can you please write some more information. A sample repo would be helpful too.

What version in which file you want to `bump` ? A dependency, your own version ? maven, npm, nuget, ...?

**Comment by bmaginni** [comment]
I'd like the ability to choose what version to update with
master branch now has depA with v1.1.0
my feature branch (taken before last release when depA was v1.0.0) could have
CASE
a) depA v1.1.0-SNAPSHOT (if I'm making changes) or
b) depA v.1.0.0

When I try to rebase my feature branch, I'd like to choose to update feature branch to
CASE
a) move depA to v1.2.0-SNAPSHOT
b) move depA to v1.1.0

I appreciate its difficult to discuss these things without diagrams or examples

**Comment by viceice** [comment]
Can you provide some debug logs? Looks like renovate don't find any update on your custom registry.

**Comment by bmaginni** [comment]
Appreciate the assistance.
The logs are large, any particular sections you are interested in?
Some extracts from the logs, I've had to redact details

`DEBUG: Found 44 new releases for com.repo:repo in repository https://mavenproxy// (repository=repo)
`

` {
             "datasource": "maven",
             "packageFile": "repo/pom.xml",
             "deps": [
               {
                 "datasource": "maven",
                 "depName": "com.repo",
                 "currentValue": "4.2.0-SNAPSHOT",
                 "fileReplacePosition": 608,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "depIndex": 0,
                 "updates": [
                   {
                     "fromVersion": "4.2.0-SNAPSHOT",
                     "toVersion": "4.5.1",
                     "newValue": "4.5.1",
                     "newMajor": 4,
                     "newMinor": 5,
                     "updateType": "minor",
                     "isSingleVersion": true
                   }
                 ],
                 "warnings": [],
                 "fixedVersion": "4.2.0-SNAPSHOT",
                 "dependencyUrl": "com/repo"
               }
`
Not finding the 4.6.0-SNAPSHOT that exists in the location
https://mavenproxy..../4.6.0-SNAPSHOT/

Is there a hook in order to conditionally select versions as mentioned in previous comment
e.g. if existing version = SNAPSHOT, replace with latest SNAPSHOT

**Comment by bmaginni** [comment]
Hi Guys, are you able to comment any further on the issue, I see it will be closed soon

**Comment by viceice** [comment]
@bmaginni I think you can use [ignoreUnstable](https://docs.renovatebot.com/configuration-options/#ignoreunstable) in a package rule scoped with [baseBranchList](https://docs.renovatebot.com/configuration-options/#basebranchlist).

**Comment by rarkins** [comment]
I didn't fully understand the question but I agree that if you want Renovate to consider unstable releases then you need to set ignoreUnstable=false
