### ISSUE TITLE
How to test schedule wordings?

### ISSUE THREAD

**Issue by voxpelli** [renovatebot/config-help#90]
I was trying to schedule something at the first Monday every month, but my wording failed repeatedly. Would it be possible to test the schedule-parser online somewhere? So one can understand how/if it interprets ones wording?

**Comment by rarkins** [comment]
Renovate uses the library “later” to parse schedules. So a quick/dirty way to test would be to require later on npm.runkit.com and parse your schedule there. I would like to add a more interactive way to do this on the website but it’s not there yet. 

Basically it needs to return a day of month or day of week to work. Not sure it’s possible to be as sophisticated as the first *Monday* if the month - our “schedule:monthly” preset just does the first *day*.

**Comment by felixfbecker** [comment]
Related: https://github.com/renovatebot/config-help/issues/94#issuecomment-419078415
