### ISSUE TITLE
renovate main repo and forked repos with different settings

### ISSUE THREAD

**Issue by tbugfinder** [renovatebot/config-help#900]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

My repository structure contains are root repo and several forks of it. Root repo set the baseline for all repos and I'd like to process the baseline with `renovate`. In addition I'd like to process forked repos with `renovate` but in those cases it shouldn't target the settings which are defined in the root repo. How could I implement this requirement?
If I create the file `renovate.json` in the root repo it gets synched to all forks later.

**Comment by rarkins** [comment]
FYI Renovate won't run on forks unless you configured includeForks=true.

One trick you could use is to use different file names. E.g. use .renovaterc.json in the main repo and renovate.json in the forks. Renovate will use the "first" file it finds and it looks in a specific order with renovate.json first

**Comment by tbugfinder** [comment]
Hi @rarkins 
thank you - I'll try that. Just to understand correctly:
This means that I'd have to integrate renovate into each repo one-by-one and set `includeForks=false` within the main repo or would `includeForks=true` apply only those settings specified in the main repo to forked repos?
Currently we sync forked and main repo using "merge upstream".

**Comment by rarkins** [comment]
You'll need to work out if the workflow suits you, all I'm saying is that if you have two config files in a repo then only one will be used. So it's possible to have the parent repo use one config file and forks override it using renovate.json.

**Comment by tbugfinder** [comment]
Works - that's really excellent!
As per my understanding this page doesn't list the order of the files being read - is there another one ? https://docs.renovatebot.com/configuration-options/

**Comment by tbugfinder** [comment]
Just for reference in case of someone is looking for that:
read RENOVATE_PASSWORD ; export RENOVATE_PASSWORD
export RENOVATE_PLATFORM=bitbucket-server
export RENOVATE_ENDPOINT=https://<URL>
export RENOVATE_USERNAME=username@domain
