### ISSUE TITLE
apply precommit hooks before PR/MR

### ISSUE THREAD

**Issue by tbugfinder** [renovatebot/config-help#902]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant

N/A
### What would you like to do?

Hi, I'd like to apply precommit hooks before the PR is created and it should also include files changed by those cycles of precommit hooks. I tried to find that in the docs but only got to `allowedPostUpgradeCommands`.

**Comment by rarkins** [comment]
This feature is not supported but there probably should be a feature request for it already in the main repo as it's been discussed before.

**Comment by tbugfinder** [comment]
will try
https://docs.renovatebot.com/configuration-options/#postupgradetasks given in https://github.com/renovatebot/renovate/issues/5004
