### ISSUE TITLE
How to ignore .node-version from being pinned with my configuration?

### ISSUE THREAD

**Issue by rfgamaral** [renovatebot/config-help#904]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I've recently reviewed my `renovate.json` configuration for a bunch of my projects and ended up with this:

```yml
{
  "extends": [
    "config:base",
    ":automergeBranch",
    ":automergeDigest",
    ":automergeMinor",
    ":automergeRequireAllStatusChecks",
    ":dependencyDashboard",
    ":disablePeerDependencies",
    ":disableRateLimiting",
    ":enableVulnerabilityAlerts",
    ":label(dependencies)",
    ":pinAllExceptPeerDependencies",
    ":timezone(Europe/Lisbon)",
    "schedule:earlyMondays"
  ],
  "postUpdateOptions": [
    "yarnDedupeHighest"
  ]
}
```

This new configuration started creating the following on my repositories:

![image](https://user-images.githubusercontent.com/96476/95187649-4efaab80-07c3-11eb-96ad-deb5bb00c97b.png)

I've looked at the logs and this refers to a `.node-version` file I have on the root of my projects ([example](https://github.com/rfgamaral/ricardoamaral.net/blob/master/.node-version)) and I believe the setting that started this was `pinAllExceptPeerDependencies`.

I've looked through the documentation but I can't figure out how can I add an override setting to the configuration above to ignore the `.node-version` file. I'd appreciate any help in figuring out the best solution for this.

**Comment by viceice** [comment]
https://docs.renovatebot.com/modules/manager/nodenv/

```json
{
  "nodenv": {
    "enabeld": false
  }
}
```

**Comment by rfgamaral** [comment]
That fixed it, thank you :)

**Comment by viceice** [comment]
You can also use `rangeStrategy` to suggest updates without pinning, eg use `bump`.

https://docs.renovatebot.com/configuration-options/#rangestrategy
