### ISSUE TITLE
How to debug configuration development?

### ISSUE THREAD

**Issue by 0xR** [renovatebot/config-help#91]
I'm looking into building a shared config and I want some quick feedback on whether I made a typo.

Is there a way to print out the config after `extends` are resolved? 

That would be more useful than pushing the config and waiting for renovate to react to it. Would I ever find out if I made a typo?

**Comment by 0xR** [comment]
Does this run when renovate is scheduled? (every hour)
Or does the webhook pick this up immediately?

Op di 4 sep. 2018 om 12:20 schreef Rhys Arkins <notifications@github.com>:

**Comment by rarkins** [comment]
The webhook doesn’t pick it up right now but it should be a pretty simple rule to add.

**Comment by rarkins** [comment]
So it will run as scheduled OR if a webhook triggers it for some other reason

**Comment by 0xR** [comment]
Hmm, I'm looking for something much faster than: type, save, commit, push, wait an hour

**Comment by rarkins** [comment]
Added feature request: https://github.com/renovatebot/pro/issues/25

**Comment by rarkins** [comment]
I forgot: when you install Renovate from CLI (`npm i -g renovate`), it actually comes with a second command `renovate-config-validator` that you can run from within any repository to validate its config.
