### ISSUE TITLE
no PRs, "no-token" in log list

### ISSUE THREAD

**Issue by djmitche** [renovatebot/config-help#911]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Yes, https://app.renovatebot.com/dashboard#github/taskcluster/taskcluster

### What would you like to do?

We've stopped getting renovate PRs, it seems.  Looking at the logs, I see "no-token" for most of them.  What does that mean?  The latest "done" log is from a day ago and did not do anything due to it not being before 2am.  Is the lack of PRs due to successful runs only occuring outside of the "before 2am" window?

**Comment by djmitche** [comment]
Huh, well, now it's posted a few PRs!

Maybe this was a transient issue?  Feel free to close :)

**Comment by djmitche** [comment]
OK, that might have been luck.  We've gotten more "no-token" logs since then.  Also, it flied three more PRs but there is room for four, and at least https://github.com/taskcluster/taskcluster/pull/3506 should have triggered an update to ajv.

**Comment by rarkins** [comment]
I've figured out the problem - `taskcluster` is installed into both `renovate` and `forking-renovate` and sometimes it seems it's picking the wrong GitHub installation ID for requesting a token. Now I need to figure out where/why.

**Comment by djmitche** [comment]
The taskcluster *org* is, yes, but the repos are distinct (I think you knew that but I just double-checked)

**Comment by rarkins** [comment]
Yes, that's right and it's valid to do so. We had one query which was mistakenly doing a join against the "first" org entry so was getting the wrong "installation ID" for requesting the token.
