### ISSUE TITLE
not getting assigned from codeowners

### ISSUE THREAD

**Issue by evanstoddard23** [renovatebot/config-help#913]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I'd like to get assigned pull request using the relevant code owners if it not auto-mergeable or is and fails status checks. With this config, I never get assigned.

```json
{
  "extends": [
    "config:base",
    ":timezone(America/Chicago)",
    ":semanticCommits"
  ],
  "packageRules": [
    {
      "updateTypes": ["patch"],
      "automerge": true,
      "semanticCommitType": "fix"
    },
    {
      "updateTypes": ["minor"],
      "automerge": true,
      "semanticCommitType": "feat"
    },
    {
      "updateTypes": ["major"],
      "automerge": false,
      "semanticCommitType": "feat"
    }
  ],
  "assigneesFromCodeOwners": true,
  "rebaseWhen": "behind-base-branch",
  "separateMinorPatch": true
}

```

**Comment by evanstoddard23** [comment]
Only auto-review, which is happening.

**Comment by rarkins** [comment]
Can you set up a public repo with that config to reproduce on a new PR? And does GitHub allow someone to be assignee if they are already auto assigned as reviewer?
