### ISSUE TITLE
[Help] Config schedule

### ISSUE THREAD

**Issue by jpmartinspt** [renovatebot/config-help#917]
### Which Renovate are you using?
WhiteSource Renovate App

### Which platform are you using?
GitHub.com

### What would you like to do?
I'm using the config bellow and some of the websites and was expecting all PR's to be filled every 3 months except for our internal dependencies that should be filled at any time. The issue is that I'm currently seeing some dev dependencies PR's popping up at any time, so I was wondering if you could give me any pointers on what could be wrong/missing with the config.

```
{
    "extends": [
        ":automergeDisabled",
        ":autodetectPinVersions",
        ":combinePatchMinorReleases",
        ":separateMajorReleases",
        ":separateMultipleMajorReleases",
        ":ignoreModulesAndTests",
        ":ignoreUnstable",
        ":prImmediately",
        ":prHourlyLimitNone",
        ":prConcurrentLimit20",
        ":updateNotScheduled",
        "helpers:disableTypesNodeMajor"
    ],
    "packageRules": [
        {
            "groupName": "all dependencies",
            "groupSlug": "all",
            "packagePatterns": ["*"],
            "schedule": ["every 3 months"]
        },
        {
            "groupName": "internal dependencies",
            "groupSlug": "internal",
            "packagePatterns": [
                "^@canonical",
                "^canonicalwebteam",
                "^vanilla-framework"
            ],
            "schedule": ["at any time"]
        },
        {
            "depTypeList": ["devDependencies"],
            "extends": [":automergeMinor"]
        }
    ]
}
```

**Comment by rarkins** [comment]
Can you provide more specifics when you say "some dev dependencies PR's popping up at any time"? e.g. can you locate a branch name and a timestamp of when the PR was created?

If the branch `renovate/all` is still active then Renovate will reuse it and create a PR, so be sure to delete the branch once merged.

**Comment by jpmartinspt** [comment]
If you look at https://github.com/canonical-web-and-design/snapcraft.io/pulls things seem to work more or less as expected, minors were grouped in a single PR and each major has it's on PR, but I was expecting the PRs to all have been opened within the same day and it seems like they are still being opened when a dependency as been released, for example https://github.com/canonical-web-and-design/snapcraft.io/pull/3119 opening seems to coincide with the day that version of webpack was release. Does that help/make sense?

**Comment by rarkins** [comment]
Was it your intention that the "all dependencies" PR would include major as well? Note: I don't recommend that (too hard to manage when one or more updates in the same PR contain breaking changes).

**Comment by jpmartinspt** [comment]
No, but it only has minors and patches, right?

**Comment by jpmartinspt** [comment]
You are absolutely right `"every 3 months"` does not do what I thought it would! But since I have written the config there seems to be a new schedule preset [`schedule:quarterly`](https://docs.renovatebot.com/presets-schedule/) that does exactly what I want!
Thanks for your help and time, I'll give this a go.
