### ISSUE TITLE
New onboarding PR not being triggered

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/config-help#918]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

https://app.renovatebot.com/dashboard#github/omgnetwork/argo-cd-image

Last log is here:
https://app.renovatebot.com/dashboard#github/omgnetwork/argo-cd-image/246058556

```
DEBUG: Found PR #8
DEBUG: Found closed onboarding PR
DEBUG: Repo is not onboarded and no merged PRs exist
```

### What would you like to do?

Attempted to follow these instructions: https://github.com/omgnetwork/argo-cd-image/pull/8#issuecomment-707713914
> Renovate is disabled
Renovate is disabled due to lack of config. If you wish to reenable it, you can either (a) commit a config file to your base branch, or (b) rename this closed PR to trigger a replacement onboarding PR.

I renamed the PR - and renovate hasn't come back with a new onboarding PR for 20+ hours now

Have I done something wrong, or is there a bug here?

**Comment by viceice** [comment]
deleted onboarding branch? deleted renovate config from repo default branch?

**Comment by mikebryant** [comment]
I deleted the renovate config from the repository's default branch, I wanted to trigger onboarding again (to test the org-wide preset support)

The bot responded with the comment about renaming the closed PR, which I did - but then nothing has happened since

**Comment by rarkins** [comment]
Can you check again?

**Comment by mikebryant** [comment]
Onboarding PR has just shown up, and I see the log here: https://app.renovatebot.com/dashboard#github/omgnetwork/argo-cd-image

Thanks :)
