### ISSUE TITLE
How to manage a project with both Maven and Gradle builds?

### ISSUE THREAD

**Issue by Xendar** [renovatebot/config-help#919]
### Which Renovate are you using?

Self hosted bot using Docker image in a Jenkins pipeline

### Which platform are you using?

Bitbucket Server

### What would you like to do?

I have a project that has both Maven and Gradle builds scripts. Renovate manages to process both of them, but they are managed it seems independently.

As an example I have a MapStruct dependency:

Root POM:

```
<properties>
  <mapstruct.version>1.4.0.Final</mapstruct.version>
</properties>

<dependencyManagement>
  <dependencies>
      <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct</artifactId>
        <version>${mapstruct.version}</version>
      </dependency>
  </dependencies>
</dependencyManagement>

<build>
  <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <release>11</release>
          <showWarnings>true</showWarnings>
          <showDeprecation>true</showDeprecation>
          <annotationProcessorPaths>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${mapstruct.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
</build>
```

build.gradle:

```
dependencies {
  constraints {
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
  }
}
```

gradle.properties:

```
mapstructVersion=1.4.0.Final
```

Now that a version `1.4.1.Final` is out, Renovate generates 3 PRs for me (my `renovate.json` does not contain anything in particular for this dependency):

![mapstruct gradle annotation processor](https://user-images.githubusercontent.com/24693144/95966641-ab854880-0e0b-11eb-8a48-bcce734834c7.jpg)

![mapstruct gradle](https://user-images.githubusercontent.com/24693144/95966648-acb67580-0e0b-11eb-933c-9c719ac408b6.jpg)

![mapstruct maven](https://user-images.githubusercontent.com/24693144/95966652-ad4f0c00-0e0b-11eb-9006-0e7687b6dcf5.jpg)

There is one thing, about the Gradle PRs, where the existing version is considered to be the name of the variable instead of its value (that may be a bug?).
But in the context of this ticket, I was wondering if there is a way to have a single PR to update both Maven and Gradle dependencies at the same time?

**Comment by rarkins** [comment]
If you think they should always be grouped and updated together and everyone would want that then you could submit a PR to add them to https://github.com/renovatebot/renovate/blob/master/lib/config/presets/internal/monorepo.ts

Otherwise, you can write you own `packageRules` and rely on `packagePatterns` for matching.

The `mapstructVersion` above looks like a bug. @zharinov ?

**Comment by zharinov** [comment]
> The `mapstructVersion` above looks like a bug. @zharinov ?

Looks so, though earlier we already fixed something similar

**Comment by rarkins** [comment]
@Xendar can you reproduce the mapStruct bug in a public repo?

**Comment by Xendar** [comment]
> If you think they should always be grouped and updated together and everyone would want that then you could submit a PR to add them to https://github.com/renovatebot/renovate/blob/master/lib/config/presets/internal/monorepo.ts

Well, I think it could make sense, but maybe it should be driven by some configuration parameter, I'll try to have a look and better understand how it works

> Otherwise, you can write you own `packageRules` and rely on `packagePatterns` for matching.

True, however, that would oblige me to write rules for each and every dependency groups in my project, and I have lots of them :(

> @Xendar can you reproduce the mapStruct bug in a public repo?

Good point (as I cannot share mine which is internal to my company), I'll try to put it in place!

**Comment by Xendar** [comment]
Hello @rarkins @zharinov 
I created a public repo with a super simple configuration: https://github.com/Xendar/renovate-bot-gradle-deps
And configured Renovate, we just need it to run now to hopefully reproduce the issue :)

**Comment by zharinov** [comment]
Thanks for repo, unfortunately I wasn't able to reproduce it

**Comment by Xendar** [comment]
> Thanks for repo, unfortunately I wasn't able to reproduce it

Yes I saw :'(
Would you have any idea on what factor could introduce this kind of behaviour? Else I'll try to add more elements to see what could do it

**Comment by zharinov** [comment]
I found related issue, will refresh corresponding PR soon: https://github.com/renovatebot/renovate/issues/7300

**Comment by Xendar** [comment]
> 
> 
> I found related issue, will refresh corresponding PR soon: [renovatebot/renovate#7300](https://github.com/renovatebot/renovate/issues/7300)

Going through the issue I may have found why my repo did not reproduce the issue. I did a commit to try to reproduce it :)

**Comment by rarkins** [comment]
@Xendar @zharinov let's close out this config help issue and open a bug in the main repo if you need
