### ISSUE TITLE
Renovate PRO gets 401 unauthorized from github.com while token is valid

### ISSUE THREAD

**Issue by 0xR** [renovatebot/config-help#92]
I'm running renovate PRO in docker compose and I have GITHUB_COM_TOKEN configured (checked by running `env` inside the container). 
Manually testing this token works (used postman). What is weird is that the error message gets a different rate limit than my manual test gets. Seems to me that the token is not being picked up.

Should I use a different env variable than GITHUB_COM_TOKEN?
It is in the documentation: https://renovatebot.com/docs/pro/configuration-github/
```
 /usr/src/app $ env | grep COM
GITHUB_COM_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

```
server_1  |  INFO: Bad credentials (repository=$private-repo$, dependencies=winston, branch=renovate/winston-3.x)
server_1  |        "err": {
server_1  |          "name": "GitHubError",
server_1  |          "host": "api.github.com",
server_1  |          "hostname": "api.github.com",
server_1  |          "method": "GET",
server_1  |          "path": "/repos/winstonjs/winston/tags?per_page=100",
server_1  |          "protocol": "https:",
server_1  |          "url": "https://api.github.com/repos/winstonjs/winston/tags?per_page=100",
server_1  |          "statusCode": 401,
server_1  |          "statusMessage": "Unauthorized",
server_1  |          "headers": {
server_1  |            "server": "GitHub.com",
server_1  |            "date": "Tue, 04 Sep 2018 12:01:38 GMT",
server_1  |            "content-type": "application/json; charset=utf-8",
server_1  |            "content-length": "83",
server_1  |            "connection": "close",
server_1  |            "status": "401 Unauthorized",
server_1  |            "x-github-media-type": "github.v3; format=json",
server_1  |            "x-ratelimit-limit": "60",
server_1  |            "x-ratelimit-remaining": "41",
server_1  |            "x-ratelimit-reset": "1536062903",
server_1  |            "access-control-expose-headers": "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval",
server_1  |            "access-control-allow-origin": "*",
server_1  |            "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
server_1  |            "x-frame-options": "deny",
server_1  |            "x-content-type-options": "nosniff",
server_1  |            "x-xss-protection": "1; mode=block",
server_1  |            "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
server_1  |            "content-security-policy": "default-src 'none'",
server_1  |            "x-runtime-rack": "0.016849",
server_1  |            "x-github-request-id": "58B8:7C2E:7101E67:E236E6D:5B8E7422"
server_1  |          }
server_1  |        },
server_1  |        "message": "Bad credentials (401)",
server_1  |        "rateLimit": "60",
server_1  |        "body": {
server_1  |          "message": "Bad credentials",
server_1  |          "documentation_url": "https://developer.github.com/v3"
server_1  |        }
server_1  |  INFO: Failed to fetch Github tags (repository=$private-repo$, dependencies=winston, branch=renovate/winston-3.x)
server_1  |        "sourceRepo": "winstonjs/winston"
```

**Comment by rarkins** [comment]
Which version of `renovate/pro` are you running?

401 Bad Credentials usually comes when the token is *wrong* rather than missing or out of requests.

**Comment by rarkins** [comment]
We did a major refactor of credentials handling in the Renovate core code between Pro 0.12.1 and 0.13.0. I was pretty sure I got all the Pro integration right, but maybe something is off. If you are able to test the same with both and see if 0.12.1 works, that would certainly narrow things down.

**Comment by 0xR** [comment]
I started running on renovate/pro:latest, is this not advised?

```
/usr/src/app $ ./node_modules/.bin/renovate --version
13.51.9
```

**Comment by rarkins** [comment]
No, that's actually even better, as I can then push fixes to the main Renovate and they'll flow through quickly. Be sure to ask me to push a stable version release if/when you are satisfied with testing and want something locked down.

I'm pushing a patch to Renovate just now that will print a masked token in the log when getting Bad Credentials - showing first 2 and last 2 characters only. That should make it possible to know for sure if the right one is actually being tried. I'll let you know here when it's ready to pull a new `renovate/pro:latest`.

**Comment by rarkins** [comment]
Please pull the very latest `renovate/pro` now, it includes `renovate@13.58.11` which includes a debug of the masked token if there's Bad credentials exception. This should let us confirm if the correct token is being used for github.com or not.

**Comment by dylang** [comment]
I am using `renovate@13.63.2` and I see it using the `GITHUB_TOKEN` (our enterprise token) on `api.github.com` and failing. We also have a `GITHUB_COM_TOKEN` configured.

**Comment by dylang** [comment]
It also seems to be hitting our enterprise server api for repos that are on `github.com`.

**Comment by 0xR** [comment]
I forgot about this issue, but I have debug info now!

```
"token": "v1***************************************9c",
```

is being used, but this is not my token. My token is not even of the same length, mine is 3 characters longer. And it does not look like `v1.*9c`.

**Comment by rarkins** [comment]
Just a quick note: @dylang is using Renovate OSS/CLI while @0xR is using Renovate Pro. It may be a common issue, but not necessarily so because token handling has some differences.

@0xR tokens starting with `v1` are the ephemeral ones generated for the app, so that means it's trying to use the GHE token for github.com. That's why it gets a "wrong token" type of response with low rate limit.

Can you double check the `renovate` version inside the container you're running?

**Comment by 0xR** [comment]
`13.59.5`

**Comment by 0xR** [comment]
let me know if I can do more to debug this

**Comment by rarkins** [comment]
@0xR thanks for the offer. I'm doing a refactor of the endpoints/hostRules logic today and will notify you here once it's ready to pull a fresh renovate/pro for testing.

**Comment by rarkins** [comment]
While working on the refactor I think I finally worked out what was going wrong with changelog tokens. I hope it should now be fixed in `renovate@13.64.11`, which should now be part of `renovate/pro:latest` on Docker Hub too. If anyone is able to test it before I can, please let me know. I need to rebuild my GHE instance first unfortunately - it is not very dev-friendly.

**Comment by 0xR** [comment]
I'm running this
```
/usr/src/app $ ./node_modules/.bin/renovate --version
13.64.17
```
But this breaks renotate entirely. It can't login to my github anymore:
```
server_1  |  INFO: jobScheduler running [scheduler]
server_1  |  INFO: Bad credentials
server_1  |        "token": null,
server_1  |        "err": {
server_1  |          "name": "GitHubError",
server_1  |          "host": "github.corp.company.com",
```

**Comment by rarkins** [comment]
@0xR thanks for the heads-up. Can you try pulling `latest` again and check it's OK? It should be getting `renovate@13.66.0` bundled.

**Comment by rarkins** [comment]
FYI on Pro releases:

- “latest” tag now points to latest *stable* image
- “next” tag (new) points to latest *unstable* version, which includes very latest Renovate core version from npm

**Comment by 0xR** [comment]
ah great, I did not know I was running the unstable version :joy:

I'll look into the latest version monday.

**Comment by rarkins** [comment]
Yeah, it was documented but still too prone to confusion so I decided to make the change. See you Monday!

**Comment by 0xR** [comment]
That has solved, renovate is working again and I get release notes!
