### ISSUE TITLE
Group together all `x.y.*` updates for dependencies

### ISSUE THREAD

**Issue by vegerot** [renovatebot/config-help#920]
### Which Renovate are you using?

WhiteSource Renovate

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

I would like to group together all `x.*.*` updates for devDependencies, and separately group together all `x.y.*` updates for dependencies.

My current attempt looks like
```JSON
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "packageRules": [
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["patch", "minor"],
      "groupName": "devDependencies (non-major)"
    },
    {
      "depTypeList": ["dependencies"],
      "updateTypes": ["patch"],
      "groupName": "Dependencies (patch)"
    }
  ]
}
```

This works for `devDependencies`, but is not doing the right thing for `dependencies`.  Renovate is making separate MRs for every `dependency` update.  Any help would be appreciated.

**Comment by rarkins** [comment]
You need to add `"separateMinorPatch": true` either to your entire config or specifically for `dependencies`, otherwise all non-major updateTypes will be treated as "minor".

**Comment by vegerot** [comment]
Thank you so much!  Love renovate!
