### ISSUE TITLE
Install renovate-approve on Github Enterprise

### ISSUE THREAD

**Issue by chamoisla** [renovatebot/config-help#921]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

I would like to install the renovate-approve bot on a Github Enterprise server. Where can I find guidance for installation?

**Comment by rarkins** [comment]
The source is here: https://github.com/renovatebot/renovate-approve-bot

It's a Probot app so you can look into the ways to host Probot
