### ISSUE TITLE
Split PRs based on path rules

### ISSUE THREAD

**Issue by jono-paymark** [renovatebot/config-help#922]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

Yes, my current config produces an error.

`Invalid configuration option: packageRules[0].additionalBranchPrefix`

### What would you like to do?

I have a repo which contains Kubernetes manifests for different environments.
Something like this:
```
dev/**/item.yaml
preprod/**/item.yaml
prod/**/item.yaml
**/dev-**.yaml
**/preprod-**.yaml
**/prod-**.yaml
```
(yeah it's a bit messy - I could tidy it a bit if needed)

By design, there are often identical items between environments. When Renovate sees an update, it dutifully creates a single PR and proposes an update across all locations.
My goal is to split the PR by environment. Instead of one PR, Renovate would create three, one for each environment. I suppose this is a bit like a monorepo.

It looks like the branch name is the decider of what's in a PR, so I created this:
```
    "packageRules": [
        {
            "paths": ["**/dev-**", "**/dev/**"],
            "additionalBranchPrefix": "dev-",
            "commitMessagePrefix": "[dev]"
        },
        {
            "paths": ["**/preprod-**", "**/preprod/**"],
            "additionalBranchPrefix": "preprod-",
            "commitMessagePrefix": "[preprod]"
        },
        {
            "paths": ["**/prod-**", "**/prod/**"],
            "additionalBranchPrefix": "prod-",
            "commitMessagePrefix": "[prod]"
        }
    ]   
```
However I've learned from the logs that `additionalBranchPrefix` can't be set inside packageRules.

Would you have suggestions on how I could split PRs based on path rules?

**Comment by rarkins** [comment]
What's the log message you receive? I don't recall a reason why they shouldn't be allowed in package rules

**Comment by jono-paymark** [comment]
I've included a snippet of the log output above, here's the full error:

```
       "errors": [
         {
           "depName": "Configuration Error",
           "message": "Invalid configuration option: packageRules[0].additionalBranchPrefix"
         },
         {
           "depName": "Configuration Error",
           "message": "Invalid configuration option: packageRules[1].additionalBranchPrefix"
         },
         {
           "depName": "Configuration Error",
           "message": "Invalid configuration option: packageRules[2].additionalBranchPrefix"
         }
       ]
```

**Comment by Jonnymcc** [comment]
`additionalBranchPrefix` appears to be a top level key. This is what worked for me and might work for your case too.
```
	{
  "extends": [
    "config:base"
  ],
  "additionalBranchPrefix": "{{baseDir}}-",
...
```

**Comment by jono-paymark** [comment]
Thanks for the suggestion. I think my best bet will be to rearrange the files a bit so that relevant files are always in an appropriately named directory. It'd be nice to have a way to do this on path patterns but I think this will do.

**Comment by jono-paymark** [comment]
Just to follow-up: It turns out I was using an older version of the whitesource/renovate image, doh!
The original configuration actually works. I have a new problem that I'm only getting three PRs at a time (`Reached PR limit - skipping branch creation`) which I'll investigate and raise separately if I need to.
Thanks for the analysis.
