### ISSUE TITLE
Fail dependency lookup github private repo from another org

### ISSUE THREAD

**Issue by Jonnymcc** [renovatebot/config-help#925]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

During `terraform-provider.getDependencies()` it returns a 404. The module exists in a private repo under a different org.

### What would you like to do?

I tried creating a personal access token and added it under the "extends" block with `:githubComToken`. I would expect this to provide that app access to those repos under the other org.

**Comment by rarkins** [comment]
How is the dependency looked up -  via API?

If you define a host rule with baseUrl equal to the other repo or org and the token then it should be used in preference over the app token for your org.

**Comment by Jonnymcc** [comment]
It is using `https://api.github.com/repos` and the repository config looks like this...
```
{
  "fileName": "renovate.json",
  "config": {
    "hostRules": [
      {
        "domainName": "github.com",
        "encrypted": {
          "token": "***********"
        }
      }
    ],
    "extends": [
      "config:base"
    ]
  }
}
```
What permissions should the PAT have? Just repo scope I'm guessing.

**Comment by rarkins** [comment]
Don't use domainName or it will mess up everything else if it takes effect. Use `"baseUrl": "https://api.github.com/repos/some-org/"`

**Comment by rarkins** [comment]
Please show me the config you tried (redacted of course..). I think that log message is actually a *mistake* and may show at all times even when an app token is in use

**Comment by Jonnymcc** [comment]
I also tried using the "encrypted" key, but the dependency still didn't work.
```
{
  "extends": [
    "config:base"
  ],
  "prConcurrentLimit": "5",
  "additionalBranchPrefix": "{{baseDir}}-",
  "packageRules": [
    {
      "datasources": ["github-tags"],
      "versioning": "regex:^[vr]?(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?$"
    }
  ],
  "hostRules": [
    {	
      "domainName": "github.com",
      "token": "REDACTED"
    }
  ]
}
```

**Comment by rarkins** [comment]
Please see https://github.com/renovatebot/config-help/issues/925#issuecomment-710270643 and try again. If not working, paste the new redacted config again

**Comment by Jonnymcc** [comment]
Tried this and it also did not work. For private repos, do I need to give the PAT repo permission?
```

{
  "extends": [
    "config:base"
  ],
  "prConcurrentLimit": "5",
  "additionalBranchPrefix": "{{baseDir}}-",
  "packageRules": [
    {
      "datasources": ["github-tags"],
      "versioning": "regex:^[vr]?(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?$"
    }
  ],
  "hostRules": [
    {	
      "baseUrl": "https://api.github.com/repos/REDACTED/",
      "encrypted": {
        "token": "REDACTED"
      }
    }
  ]
}
```

**Comment by rarkins** [comment]
I think it needs repo permissions to access private repos. You can verify it works by using curl or some similar tool and verifying it can fetch the private `https://api.github.com/repos/ORG/REPO/tags`

**Comment by Jonnymcc** [comment]
So it does need repo permissions. And when I curl using the token it does return tags. 🤔

**Comment by rarkins** [comment]
@viceice I still think this should work, because our hostRules resolution gives priority to matching baseUrls over hostnames and domainnames. Need to think how to either (a) reproduce it, or (b) log auth/token use without flooding the logs due to hundreds or thousands of requests per run. Maybe we could keep a little state and log *once* per repo any time auth is associated with a particular host?

**Comment by viceice** [comment]
I think it would help to have logs with latest config.

I'm also pretty sure it should work.

@rarkins how did the app pass the github token? Maybe it is somehow preferred over the user hostRule?
