### ISSUE TITLE
Renovate not updating all .tf files together when there's templating in some

### ISSUE THREAD

**Issue by MartinPetkov** [renovatebot/config-help#927]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

No, the app is installed for the org (GoogleCloudPlatform) and I can't log in as it.

### What would you like to do?

[Our repo](https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/) does Go templating to generate Terraform configs, and we've checked in both the .tf templates and the .tf generated files to use as examples. Prior to https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/604, it would update both the files under templates/ and the files under examples/generated/ in the same PR. However, after that PR, it only updates the examples, not the templates - see https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/610. My guess is that there's a packageRule that groups both "regex" and "terraform" managers, but the fileMatch was only applied to the "terraform" manager and not the "regex" one.

**Comment by viceice** [comment]
Your config is wrong. Move the fileMatch to regexManager config.

Your regex manager config has missing required fileMatch option.

**Comment by rarkins** [comment]
Please see https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/614 for what I think is hopefully the proper solution

Explanation:

- regex managers should have a `fileMatch` field. We'll update our docs in case that's not clear plus add a validation check to catch it
- When you added a global `fileMatch` field previously it meant Renovate passed the `.tf` file content to every single package manager (not just terraform and regex, but also npm, nuget, etc). It causes an increase in both processing time as well as errors, so we're also going to add a validation rule to block that type of config in future as well. It would also mean that all other package managers would be essentially blocked/disabled in the repo by this `fileMatch` value
