### ISSUE TITLE
PR indicate's "Automerge: Disabled by config" when explicit enabled though packageRules

### ISSUE THREAD

**Issue by sppatel** [renovatebot/config-help#928]
### Which Renovate are you using?

Renovate Open Source CLI 22.21.3

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant
```
INFO: Branch created (repository=***, branch=renovate/***-1.x)
       "commitHash": "508958c"
 INFO: PR created (repository=***, branch=renovate/***-1.x)
       "pr": 367,
       "prTitle": "fix(deps): update dependency ***/*** to v1.6.23"
 INFO: Repository finished (repository=***)
       "durationMs": 99618
```
### What would you like to do?

I have automerge set for a packagePatterns I have and and the PR is getting created but the PR description shows "Automerge: Disabled by config"

My configuration is.. (sorry that some stuff is *** out for privacy) but if there is something I can check in the extended configurations that might be causing the automerge to be disabled I can look for it.  But given that the packageRules should be overriding - not sure why its saying its disabled.

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["***", "***"],
  "labels": ["dependencies :package:"],
  "packageRules": [
    {
      "updateTypes": ["major"],
      "labels": ["major :mega:"]
    },
    {
      "packagePatterns": ["/^@something/[a-z]+-rbac$/"],
      "automerge": true,  <--- Not working
      "rangeStrategy": "pin"
    }
  ]
}
```

**Comment by rarkins** [comment]
Remove the prefix and suffix `/`, i.e.

```
  "packagePatterns": ["^@something/[a-z]+-rbac$"],
```

**Comment by viceice** [comment]
Please post debug logs. Are you sure your regex correctly matches the targeted packages?

**Comment by sppatel** [comment]
Got it fixed.  Appreciate the quick response.
