### ISSUE TITLE
Automerge not working on GitLab - branchStatus: yellow reason not clear

### ISSUE THREAD

**Issue by mterrel** [renovatebot/config-help#933]
**What Renovate type, platform and version are you using?**

Hosted Renovate on GitLab

**Describe the bug**

Automerge is not working for our open source project, [AdaptJS](https://gitlab.com/unboundedsystems/adapt/) on GitLab. The debug logs indicate that the branch status is yellow, but there's not enough information to figure out what to examine next to troubleshoot.

So the primary request here is for more detailed information on what might be keeping the branch from being automerged. 
Assuming that the `branchStatus: yellow` is what's keeping the branch from being merged, either a text description of what items might cause `branchStatus: yellow` would work or also more info in the debug log as to what exactly caused that condition.

**Relevant debug logs**

[This debug log](https://app.renovatebot.com/dashboard#gitlab/unboundedsystems/adapt/249228690) shows a branch (branch = `renovate/node-10.x`) that I believe should have been automerged, but was not.

The relevant portion seems to be:
```
DEBUG: Checking if we can automerge branch(branch="renovate/node-10.x")
DEBUG: mergeStatus=no automerge(branch="renovate/node-10.x")
DEBUG: Ensuring PR(branch="renovate/node-10.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/node-10.x")
DEBUG: getBranchPr(renovate/node-10.x)(branch="renovate/node-10.x")
DEBUG: Got res with 1 results(branch="renovate/node-10.x")
DEBUG: getPr(374)(branch="renovate/node-10.x")
DEBUG: getBranchStatus(renovate/node-10.x)(branch="renovate/node-10.x")
DEBUG: Got res with 16 results(branch="renovate/node-10.x")
DEBUG: Found existing PR(branch="renovate/node-10.x")
DEBUG: getBranchStatus(renovate/node-10.x)(branch="renovate/node-10.x")
DEBUG: Got res with 16 results(branch="renovate/node-10.x")
DEBUG: Processing existing PR(branch="renovate/node-10.x")
DEBUG: getBranchStatus(renovate/node-10.x)(branch="renovate/node-10.x")
DEBUG: Got res with 16 results(branch="renovate/node-10.x")
DEBUG: getBranchStatus() result(branch="renovate/node-10.x")
{
  "branchStatus": "yellow",
  "branchName": "renovate/node-10.x"
}
DEBUG: Merge Request renovatebot/renovate#374 does not need updating(branch="renovate/node-10.x")
DEBUG: Checking renovatebot/renovate#374 for automerge(branch="renovate/node-10.x")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/node-10.x")
DEBUG: PR is not ready for merge(branch="renovate/node-10.x")
```

**To Reproduce**

I realize the existing open source repo isn't minimal, but it is public and does repro the issue. I'm happy to make changes to help troubleshoot the issue.

**Additional context**

The merges are to `master`, which is a protected branch, but Renovate-bot has Maintainer permissions.

**Comment by rarkins** [comment]
It's working as expected. Automerges are performed whenever Renovate runs, not instantly.
