### ISSUE TITLE
packagerules confusion

### ISSUE THREAD

**Issue by evanstoddard23** [renovatebot/config-help#934]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

According to [the docs](https://docs.renovatebot.com/configuration-options/#packagerules) " you can mix together both packageNames and packagePatterns in the same package rule and the rule will be applied if _either_ match". Later on there's this example:

Use this field to restrict rules to a particular package manager. e.g.

```
{
  "packageRules": [
    {
      "packageNames": ["node"],
      "managers": ["dockerfile"],
      "enabled": false
    }
  ]
}
```

Does this do packageNames || managers, or does it do packageNames && managers?

**Comment by viceice** [comment]
This will do package names and managers.

But it would do package names or package patterns.

**Comment by rarkins** [comment]
`packageNames` and `packagePatterns` are the only "OR" logic I can recall we have. Everything else is AND

**Comment by evanstoddard23** [comment]
The excludePackageNames/Patterns use AND logic, right?

**Comment by viceice** [comment]
🤔 they are OR too

**Comment by rarkins** [comment]
That one's a bit of a mind bender.

Explanation one: if either exclude rule is matched then the rule isn't matched. 

Explanation two: exclude any excludePackageNames AND any excludePackagePatterns

So not sure if it's correct to say AND or OR due to its negation but hopefully the explanations make sense
