### ISSUE TITLE
automerge not working, and weird group names

### ISSUE THREAD

**Issue by vegerot** [renovatebot/config-help#936]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

I want to: 

- automerge all patch devDependency updates
- group all minor devDependency updates into one MR
- group all patch dependency updates into one MR
- make individual MRs for every minor and major dependency update

This is the config I wrote to do this:
```JSON
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "separateMinorPatch": true,
  "packageRules": [
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["patch"],
      "groupName": "devDependencies (patch)",
      "automerge": true
    },
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["minor"],
      "groupName": "devDependencies (minor)"
    },
    {
      "depTypeList": ["dependencies"],
      "updateTypes": ["patch"],
      "groupName": "Dependencies (patch)"
    }
  ]
}
```

This is what the result looks like:

![image](https://user-images.githubusercontent.com/5297725/96877983-528b6500-1448-11eb-8f87-200831846975.png)

**Comment by viceice** [comment]
remove the update type grom group name, as renovate will autoadd it to pr title

**Comment by vegerot** [comment]
@viceice will this also make the automerge start working again?

**Comment by viceice** [comment]
you need to check the debug logs for the cause

**Comment by vegerot** [comment]
Thanks!  How can I check the logs in a privately hosted GitLab instance?

**Comment by viceice** [comment]
in your pr should be a link to the renovate app [dashboard](https://app.renovatebot.com/dashboard)

**Comment by rarkins** [comment]
One of these two answers is incorrect:

![image](https://user-images.githubusercontent.com/6311784/96898091-9d7c9b00-148f-11eb-92ae-e5a23fc5d9e0.png)

**Comment by vegerot** [comment]
@rarkins my apologies.  When I click on the user that opened the MR I see 
![image](https://user-images.githubusercontent.com/5297725/96903619-0f3eef80-1464-11eb-8db8-67d578b2ebd0.png) .  And when I click on the repo I see 
![image](https://user-images.githubusercontent.com/5297725/96903660-1e25a200-1464-11eb-97ab-df837e5fe363.png.  Which is why I thought we were using WhiteSource Renovate.

**Comment by rarkins** [comment]
No problem. But in that case you'll need to retrieve the logs from wherever it's run. And I recommend running with LOG_LEVEL=debug in env it --log-level=debug in CLI to capture the debug logs you'll need

**Comment by vegerot** [comment]
I don't think I have easy access to the logs.  In either case, can you see anything wrong with 

```JSON
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "separateMinorPatch": true,
  "packageRules": [
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["patch"],
      "automerge": true
    },
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["minor"],
    },
    {
      "depTypeList": ["dependencies"],
      "updateTypes": ["patch"],
    }
  ]
}
```

When it comes to the format of the config?  If you can't find anything with the auto merge from this, I will have to see about getting those logs.

Thanks!

**Comment by viceice** [comment]
nope, config seems correct, most of the time automerge is failing because of branch protections

**Comment by rarkins** [comment]
Can you take a screenshot of the PR details? It will say if it's configured to automerge or not

**Comment by vegerot** [comment]
It does say it should AutoMerge 

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/5297725/96911430-d7897500-146e-11eb-921c-c3ac8b7a659d.png">

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/5297725/96911487-e6702780-146e-11eb-981a-3b6be9f30812.png">

**Comment by viceice** [comment]
Automerge don't work if pr needs approval!

**Comment by vegerot** [comment]
Oh, thanks!  Did not notice that!  Is there a way to let Renovate approve itself for patch updates?

**Comment by viceice** [comment]
nope, you need something else. for github we have an auto-approve-bot

**Comment by vegerot** [comment]
Thank you!
