### ISSUE TITLE
Widen peer dependencies and bump dev dependencies

### ISSUE THREAD

**Issue by mmkal** [renovatebot/config-help#937]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Not sure they're relevant

### What would you like to do?

I want renovate to open a PR which widens the peer dependencies for packages declared as them, but also bumps those same packages as `devDependencies` - otherwise my tests aren't actually validating that what I'm going to publish will work with the new range.

Example: https://github.com/mmkal/slonik-tools/pull/257

In that PR, `slonik` was widened to allow v23 - but v23 contained a breaking change that _did_ require code changes from my package(s). I'd expected this entry to have been affected at the same time: https://github.com/mmkal/slonik-tools/blob/a45911219569b99fd8a202b01b0ed58002596580/package.json#L58. IMO it should be the default behaviour, because it's a bit dangerous that builds can go green even though they might be falsely advertising compatibility with new versions. But I'd be fine to manually configure renovate to bump things together. `:widenPeerDependencies` is a bit of a black box to me though.

renovate.json at time of writing: https://github.com/mmkal/slonik-tools/blob/a45911219569b99fd8a202b01b0ed58002596580/renovate.json

**Comment by rarkins** [comment]
> IMO it should be the default behaviour, because it's a bit dangerous that builds can go green even though they might be falsely advertising compatibility with new versions.

What you describe is the default behavior, but your packageRules overrode that.

Move your slonic package rule last, or add an `excludePackagePatterns` field to your devDependencies grouping so that slonic packages aren't included in it. 

Look at the branch names of https://github.com/mmkal/slonik-tools/pull/256 and https://github.com/mmkal/slonik-tools/pull/257 and you can see what's going on

**Comment by mmkal** [comment]
Thanks @rarkins!
