### ISSUE TITLE
Index-url authentication issue

### ISSUE THREAD

**Issue by MyDigitalLife** [renovatebot/config-help#940]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

renovate_1  | DEBUG: Found 1 package file(s) (repository=test-repo)
renovate_1  |  INFO: Dependency extraction complete (repository=test-repo)
renovate_1  |        "baseBranch": "master",
renovate_1  |        "stats": {
renovate_1  |          "managers": {"pip_requirements": {"fileCount": 1, "depCount": 1}},
renovate_1  |          "total": {"fileCount": 1, "depCount": 1}
renovate_1  |        }
renovate_1  | DEBUG: Datasource unauthorized (repository=test-repo)
renovate_1  |        "datasource": "pypi",
renovate_1  |        "lookupName": "boto3",
renovate_1  |        "url": "https://artifactory.server/artifactory/api/pypi/pypi/simple/boto3"
renovate_1  | DEBUG: Failed to look up dependency boto3 (repository=test-repo, packageFile=requirements.txt, dependency=boto3)
renovate_1  | DEBUG: Package releases lookups complete (repository=test-repo)
renovate_1  |        "baseBranch": "master"
renovate_1  | DEBUG: packageFiles with updates (repository=test-repo)
renovate_1  |        "config": {
renovate_1  |          "pip_requirements": [
renovate_1  |            {
renovate_1  |              "packageFile": "requirements.txt",
renovate_1  |              "manager": "pip_requirements",
renovate_1  |              "deps": [
renovate_1  |                {
renovate_1  |                  "depName": "boto3",
renovate_1  |                  "currentValue": "==1.15.16",
renovate_1  |                  "datasource": "pypi",
renovate_1  |                  "fromVersion": "1.15.16",
renovate_1  |                  "depIndex": 0,
renovate_1  |                  "updates": [],
renovate_1  |                  "warnings": [
renovate_1  |                    {
renovate_1  |                      "depName": "boto3",
renovate_1  |                      "message": "Failed to look up dependency boto3"
renovate_1  |                    }
renovate_1  |                  ],
renovate_1  |                  "fixedVersion": "1.15.16"
renovate_1  |                }
renovate_1  |              ],
renovate_1  |              "registryUrls": [
renovate_1  |                "https://username:${TOKEN}@artifactory.server/artifactory/api/pypi/pypi/simple"
renovate_1  |              ]
renovate_1  |            }
renovate_1  |          ]
renovate_1  |        }

### What would you like to do?

In our requirments.txt we have this at the top:
--index-url https://username:${TOKEN}@artifactory.server/artifactory/api/pypi/pypi/simple
This is to make sure when can run our pip install localy without having to fix extra settings, we just need our token in the env vars. The requirement for the username and token was only added recently and is introducing an issues. Because we now need the credentials I configured the renovate bot to have these credentials. But the requirments.txt is overwriting those settings and I can't find a way to fix this. Is there a way to ignore the --index-url in the requiments.txt for renovate without having to remove it from the file?

**Comment by rarkins** [comment]
I'm not sure there's currently a way. Can you determine what is the exact URL that Renovate queries to artifactory? e.g. is the `${TOKEN}` part resolved to empty string or sent as part of the string?

**Comment by MyDigitalLife** [comment]
Its sends ${token} as part of the string. When I remove the --index-url from the file it uses the one specific in the renovate cli config and the token is displayed in the logs.

**Comment by rarkins** [comment]
What do you mean by `the one specific in the renovate cli` ?

**Comment by rarkins** [comment]
You could try this:

```json
{
  "hostRules": [{
    "baseUrl": "https://artifactory.server/artifactory/api/pypi/pypi/simple",
    "username": "......",
    "password": "......"
  }],
  packageRules": [{
    "datasources": ["pypi"],
    "registryUrls": ["https://artifactory.server/artifactory/api/pypi/pypi/simple"]
  }]
}
```

You could possibly split the `packageRules` into the repo's `renovate.json` while keeping the `hostRules` in the bot's `config.js`. The end result should hopefully be:

- index-url is extracted like today, but then overridden by the packageRules
- hostRules are used to authenticate with Artifactory using Basic authentication headers

**Comment by MyDigitalLife** [comment]
Doesn't seem to work. Its still using the index-url extracted url and not being overridden by the hostRules. There might need a change to add a force rule for the hostRules. Is that something that would work?

**Comment by rarkins** [comment]
> Doesn't seem to work. Its still using the index-url extracted url and not being overridden by the hostRules.

If you can reproduce in a public repo then I'll take a look. You just need the `requirements.txt` and `packageRules`. No need to add `hostRules` until the `registryUrls` overwriting is working.

> There might need a change to add a force rule for the hostRules. Is that something that would work?

It's not an idea solution when overriding the `registryUrls` is what we really need.

**Comment by MyDigitalLife** [comment]
I can share how my renovate.json now looks in the repo I'm testing on:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "packageRules": [
    {
      "datasources": [
        "pypi"
      ],
      "registryUrls": [
        "https://artifactory.server/artifactory/api/pypi/pypi/simple"
      ]
    }
  ]
}
```
And the requirement.txt:
```
--index-url https://username:${password}@artifactory.server/artifactory/api/pypi/pypi/simple
boto3==1.15.16
```

But the logs still show the incorrect url in "registryUrls":
```
renovate_1  | DEBUG: packageFiles with updates (repository=test-repo)
renovate_1  |        "config": {
renovate_1  |          "pip_requirements": [
renovate_1  |            {
renovate_1  |              "packageFile": "requirements.txt",
renovate_1  |              "manager": "pip_requirements",
renovate_1  |              "deps": [
renovate_1  |                {
renovate_1  |                  "depName": "boto3",
renovate_1  |                  "currentValue": "==1.15.16",
renovate_1  |                  "datasource": "pypi",
renovate_1  |                  "fromVersion": "1.15.16",
renovate_1  |                  "depIndex": 0,
renovate_1  |                  "updates": [],
renovate_1  |                  "warnings": [
renovate_1  |                    {
renovate_1  |                      "depName": "boto3",
renovate_1  |                      "message": "Failed to look up dependency boto3"
renovate_1  |                    }
renovate_1  |                  ],
renovate_1  |                  "fixedVersion": "1.15.16"
renovate_1  |                }
renovate_1  |              ],
renovate_1  |              "registryUrls": [
renovate_1  |                "https://username:${password}@artifactory.server/artifactory/api/pypi/pypi/simple"
renovate_1  |              ]
renovate_1  |            }
renovate_1  |          ]
renovate_1  |        }
```

**Comment by MyDigitalLife** [comment]
Taking a closer look it does looks like something changed. Logs without the package rule:
```
renovate_1  | DEBUG: Datasource unauthorized (repository=test-repo)
renovate_1  |        "datasource": "pypi",
renovate_1  |        "lookupName": "boto3",
renovate_1  |        "url": "https://username:%24%7Bpassword%7D@artifactory.server/artifactory/api/pypi/pypi/simple/boto3"
```

With the package rule:
```
renovate_1  | DEBUG: Datasource unauthorized (repository=test-repo)
renovate_1  |        "datasource": "pypi",
renovate_1  |        "lookupName": "boto3",
renovate_1  |        "url": "https://artifactory.server/artifactory/api/pypi/pypi/simple/boto3"
```

But its not picking up the username and password from the config.js for the cli.

**Comment by rarkins** [comment]
Does that server support `Authorization` headers? Assuming the `hostRules` is being matched correctly, here's how it's applied: https://github.com/renovatebot/renovate/blob/9f31b2a82753ffe78bc5805e4f2c6733031cb1a6/lib/util/http/auth.ts#L44-L47

**Comment by rarkins** [comment]
Note that the username:password will *not* be put into the URL itself - it will be put into an `Authorization` header with Basic auth

**Comment by MyDigitalLife** [comment]
Yes, where using antifactory and it supports the Authorization  header so what shouldn't be the issue, checked in in the browser and it works. 

This is what my config.js looks like atm:
```
{
...
    hostRules: [
...
        {
            hostType: "pypi",
            hostName: "artifactory.server/artifactory/api/pypi/pypi/simple",
            username: process.env.PYTHON_USERNAME,
            password: process.env.PYTHON_PASSWORD
        }
    ],
};
```

**Comment by rarkins** [comment]
that's not a valid `hostName`, so it definitely won't match

**Comment by MyDigitalLife** [comment]
I replaced the hostname with a dummy hostname. But in the real config.js the hostname is a valid hostname is correct.

**Comment by rarkins** [comment]
if it has `/artifactory/api/pypi/pypi/simple` in it then it's an invalid hostname

**Comment by rarkins** [comment]
Why did you choose not to configure it like I suggested it above?

```
  "hostRules": [{
    "baseUrl": "https://artifactory.server/artifactory/api/pypi/pypi/simple",
    "username": "......",
    "password": "......"
  }],
```

**Comment by rarkins** [comment]
If it's a baseUrl, it needs to start with a `https://` prefix and can include a full path. If it's a hostname, it needs to be a proper hostname, e.g. `artifactory.server`

**Comment by MyDigitalLife** [comment]
I was trying some more things as it wasn't working. Just changed it back to your example and now its working! Thanks for your help!
