### ISSUE TITLE
Docker ECR dependencies kustomize

### ISSUE THREAD

**Issue by Jonnymcc** [renovatebot/config-help#942]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: ECR getAuthorizationToken error
DEBUG: Using Basic auth for docker registry kong-ingress-controller
DEBUG: Failed to get authHeaders for getTags lookup
DEBUG: Failed to look up dependency
```

### What would you like to do?

We use a lot of images from ECR. Is there a way to configure auth for Docker?

**Comment by rarkins** [comment]
Unfortunately not supported yet, please follow https://github.com/renovatebot/renovate/issues/3968
