### ISSUE TITLE
(question): numeric versioning

### ISSUE THREAD

**Issue by lukasmrtvy** [renovatebot/config-help#943]
Can renovate handle numeric versioning? I have tags ( master ) in my trunk based git repository in format: `1-master`, `2-master`. Of course releases braches have proper semver. Can renovate version based on number(and some suffix)? ( if is higher, then update .. )
Thanks

**Comment by rarkins** [comment]
If you don't need to *match* suffixes the you could possibly just try `loose` versioning. But if you need to match, try [regex versioning](https://docs.renovatebot.com/modules/versioning/#regular-expression-versioning)

Use package rule to configure it, e.g.

```json
{
  "packageRules": [{
    "packageNames": ["foo"].
    "versioning": "loose"
  }]
}
```

**Comment by lukasmrtvy** [comment]
Thanks,
maybe https://github.com/renovatebot/renovate/issues/2488 would be also interesting for me..
In trunkbaseddevelopment, release branches are using semver, but master branch itselft should not use semver so I am looking for some versioning ( databased, numeric ) which can be detected and maintained by renovate.
