### ISSUE TITLE
monthly updates are not working .

### ISSUE THREAD

**Issue by Ranjith072** [renovatebot/config-help#944]
### Which Renovate are you using?

Renovate Open Source CLI
WhiteSource Renovate App

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

i have a configuration like this for updating the the aws packages monthly but they are never updated .
please let me know if there is anything that i am missing here .
```json
  "packageRules": [
    {
      "packageNames": ["awscli", "aws-sdk", "boto3", "boto3-stubs", "botocore"],
      "extends": ["schedule:monthly"],
      "groupName": "aws packages"
    }
  ]
```

**Comment by viceice** [comment]
Please provide the debug logs. You maybe need to wait for first day of the month before 3am

https://github.com/renovatebot/renovate/blob/c33da16aba2e3fff357ead02c79343ca614f827a/lib/config/presets/internal/schedule.ts#L16-L19

**Comment by viceice** [comment]
Also please format your code.

**Comment by rarkins** [comment]
Yes, you'll need the debug logs for when you ran it during this time: `"before 3am on the first day of the month"`

**Comment by Ranjith072** [comment]
{
  "extends": [
    "config:base"
  ],
  "automergeType": "branch",
  "automerge": true,
  "masterIssue": true,
  "major": {
    "automerge": false
  },
  "pin": {
    "automerge": true
  },
  "pinDigests": true,
  "packageRules": [
    {
      "packageNames": ["awscli", "aws-sdk", "boto3", "boto3-stubs", "botocore"],
      "extends": ["schedule:monthly"],
      "groupName": "aws packages"
    },
    {
      "packagePatterns": [
        "^org\\.jetbrains\\.kotlinx:"
      ],
      "versionScheme": "semver"
    }
  ],
  "lockFileMaintenance": {
    "enabled": true
  },
  "ignorePaths": [
      "sql-server-dependency/Dockerfile"
  ],
  "stabilityDays": 3,
  "prNotPendingHours": 74,
  "timezone": "Europe/Oslo",
  "semanticCommits": true
}
here is the full renovate.json file which is formatted . and also the issues not for only this month it has never worked at all.

**Comment by rarkins** [comment]
Having `stabilityDays` with the AWS SDK is bad idea because they often release daily and so it will never reach stability.

**Comment by Ranjith072** [comment]
at least it should create a PR for these packages right ?i do not any PR's at all for these packages scheduled monthly.

**Comment by Ranjith072** [comment]
unable to find the old logs on the dashboard as i could find only for few days ,is there any way to test this ?

**Comment by rarkins** [comment]
I suggest you remove the `prNotPendingHours` and `stabilityDays` setting for your monthly packages before the start of the next month.

**Comment by Ranjith072** [comment]
u mean something like this ? "packageRules": [
    {
      "packageNames": ["awscli", "aws-sdk", "boto3", "boto3-stubs", "botocore"],
      "extends": ["schedule:monthly"],
      "stabilityDays": 0,
      "prNotPendingHours": 0,
      "groupName": "aws packages"
    },
    {
      "packagePatterns": [
        "^org\\.jetbrains\\.kotlinx:"
      ],
      "versionScheme": "semver"
    }
  ]
