### ISSUE TITLE
[Question] Private repository on a gradle project - self hosted renovate bot

### ISSUE THREAD

**Issue by parisapo** [renovatebot/config-help#949]
### Which Renovate are you using?

I am using the `github bot` but I want to verify that the self hosted versions is worth investing.

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

No - trying to verify if this capability exist

### What would you like to do?

This more of a confirmation than a question. According this [https://github.com/renovatebot/config-help/issues/222](issue) If you have a Java / Gradle based repository , that happens to define a corp private registry for `private dependencies`, renovate bot will skip this part of the config, resulting to not being able to check updates residing to this
repo. 
 
Example: 

``` groovy
repositories {
    maven {
        credentials {
            username = maven_user
            password = maven_password
        }
        url = mavel_url
    }
    mavenCentral()
}
```
After a short question on twitter, I got the impression there is a work around if you use the `self` hosted version of renovate bot. As far as I understand renovate is a docker container, that internally invokes its gradle tooling. I am curious on what would be the solution so that you make `renovate` pick the above 3 properties from an env, and when it `compiles` the gradle part defining the external repository not to fail or ignore.

Many thanks for any tips or confirmation that anyway this is not supported now and we would have to wait for a new release or a future version.

**Comment by viceice** [comment]
you need to add the credentials to a hostRule fro renovate too, as renovate is not capable to read the credentials from gradle properties.

So i would suggest you the following workflow:
* add credentials to github secrets
* create a workflow (cron)
  * prepare tools (node, java)
  * generate `~/.gradle/gradle.properties` with secrets
  * generate `config.js` from secrets (hostRules)
  * run renovate with `npx renovate ${{ github.repository }}`

Maybe needs more config options, see docs.

**Comment by parisapo** [comment]
Many thanks
