### ISSUE TITLE
Groupings no longer work after gitlab settings change

### ISSUE THREAD

**Issue by vegerot** [renovatebot/config-help#954]
### Which Renovate are you using?

WhiteSource Renovate App (unsure.  See https://github.com/renovatebot/config-help/issues/936#issuecomment-714589748 )

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

I want to do the same thing I wanted to do back in https://github.com/renovatebot/config-help/issues/936 .  To reiterate:

> I want to: 
> 
> - automerge all patch devDependency updates
> - group all minor devDependency updates into one MR
> - group all patch dependency updates into one MR
> - make individual MRs for every minor and major dependency update

I was [advised](https://github.com/renovatebot/config-help/issues/936#issuecomment-714515006) to change my config to 

```JSON
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "separateMinorPatch": true,
  "packageRules": [
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["patch"],
      "automerge": true
    },
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["minor"]
    },
    {
      "depTypeList": ["dependencies"],
      "updateTypes": ["patch"]
    }
  ]
}
```

So I did.  A bit after that, I changed my GitLab repo config to use the [semi-linear merge strategy](https://docs.gitlab.com/ee/user/project/merge_requests/reviewing_and_managing_merge_requests.html#semi-linear-history-merge-requests).  And now none of my groups are grouping.

Right now my MRs on GitLab look like 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/5297725/97633331-50a64080-1a0a-11eb-88f4-1ea7ad453aef.png"> (and there's a lot more where that came from!)

Anyways, I would like to do what I said at the top.  Have minor devDependencies grouped together, have patch Dependencies grouped together, and have individual MRs for each minor/major Dependency update.

@viceice and @rarkins were very helpful before, thanks!

**Comment by viceice** [comment]
You missed the `groupName` option in your package rules.

**Comment by vegerot** [comment]
@viceice thanks!  In that case, I must have misunderstood what you meant here (https://github.com/renovatebot/config-help/issues/936#issuecomment-714515006), because that's what I had before, no?

**Comment by viceice** [comment]
Sorry, maybe I mean asked that too before. See following docs link for explanation

https://docs.renovatebot.com/configuration-options/#groupname

**Comment by vegerot** [comment]
So I did read that.  Are you saying that you were incorrect in your suggestion (https://github.com/renovatebot/config-help/issues/936#issuecomment-714515006) before?  If I do add the `groupName` field, how do I stop it from making names like `(patch) (patch)` like in https://github.com/renovatebot/config-help/issues/936 ?

**Comment by viceice** [comment]
Ok, sorry again, my suggestion was not clear. I mean remove the `(patch)` and  `(minor)` string from `groupName`. Renovate will / should take care of not grouping minor and patch together, because you use `separateMinorPatch`.

Renovate will automatically add the `updateType` to `prTitle`, see:
https://github.com/renovatebot/renovate/blob/9aff7a955ffa586c84b35bacbd14ce995b91b2d3/lib/workers/repository/updates/generate.ts#L239-L249

So my new suggestion is to try the following config:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "separateMinorPatch": true,
  "packageRules": [
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["patch"],
      "groupName": "devDependencies",
      "automerge": true
    },
    {
      "depTypeList": ["devDependencies"],
      "updateTypes": ["minor"],
      "groupName": "devDependencies"
    },
    {
      "depTypeList": ["dependencies"],
      "updateTypes": ["patch"],
      "groupName": "Dependencies"
    }
  ]
}
```

**Comment by rarkins** [comment]
I'm actually not sure they'll go into separate groups if the groupName is the same

**Comment by viceice** [comment]
See my links above, I think they will go to different branches and so to different pr

**Comment by rarkins** [comment]
I think you're right, here's an example: https://github.com/rarkins/test2/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by vegerot** [comment]
Thanks both of you!  Will update this issue after trying the suggestion

**Comment by vegerot** [comment]
Works like a charm!
