### ISSUE TITLE
Bitbucket server: onboarding PR doesn't include default reviewer

### ISSUE THREAD

**Issue by rdepke** [renovatebot/config-help#955]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server

### Have you checked the logs? Don't forget to include them if relevant
I checked, but I don't think they are relevant at the moment. I happily provide them if you tell what part is of interest.

### What would you like to do?
I want to set up renovate for our project. Our code is hosted on Bitbucket server and we have around 80 repositories and default reviewers are different on a repository basis.

What I got so far:

- create onboarding PRs

- If onboarded all following PRs include the correct default reviewers.

What I want to achieve no:

- Onboarding PRs include default reviewers.

```
{
  "logLevel" : "debug",
  "platform": "_bitbucket-server_",
  "endpoint": "https://_my.bitbucket.server_/",
  "username": "aUser",
  "repositories": ["_PROJECT/repository_"],
  "maven": {
        "enabled": true
    },
    "hostRules": [{
        "hostType": "maven",
        "endpoint": "https://_nexus.server_/repository/maven/"
    }],
    "packageRules": [{
        "managers": ["maven"],
        "registryUrls": ["https://_nexus.server_/repository/maven/"]
    }]
}

```

```objects:
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: renovate
  spec:
    schedule: '@daily'
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: renovate
                image: renovate/renovate:${RENOVATE_VERSION}
                env: 
                  - name: HTTPS_PROXY
                    value: http://_some.corp.proxy_:80
                  - name: NO_PROXY
                    value: 127.0.0.1,localhost,
                  - name: RENOVATE_CONFIG_FILE
                    value: '/opt/renovate/config.json'
                  - name: RENOVATE_GIT_AUTHOR 
                    value: '_User_ <_User@company.com_>'
                  - name: RENOVATE_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: bitbucket-access
                        key: password
                volumeMounts:
                  - name: config-volume
                    mountPath: /opt/renovate/
                  - name: work-volume
                    mountPath: /tmp/renovate/
            restartPolicy: Never
            volumes:
              - name: config-volume
                configMap:
                  name: renovate-config
              - name: work-volume
                emptyDir: {}
```

Please adivse if there is problem with my configuration or if I miss something regarding default reviewers. I put reducted configuration into **_**

**Comment by viceice** [comment]
Where did you configure the default reviewer?

**Comment by rdepke** [comment]
The default reviewers are configured in Bitbucket per repository.  
https://_host_/plugins/servlet/default-reviewers/projects/_project_/repos/_repository_

**Comment by viceice** [comment]
have you configured [bbUseDefaultReviewers](https://docs.renovatebot.com/configuration-options/#bbusedefaultreviewers)?

**Comment by rdepke** [comment]
This should be default to true, so no.
I just added the parameter to verify this, but it doesn't make any difference.

**Comment by viceice** [comment]
We need the debug logs when the pr was created.
did you see this message in logs?
https://github.com/renovatebot/renovate/blob/517f5ecfb91ce3473da6c87cc0ae0cdddcb92c2c/lib/platform/bitbucket-server/index.ts#L772

**Comment by viceice** [comment]
Ok, i know the issue. Please track renovatebot/renovate#7613

**Comment by rdepke** [comment]
Thank you for your support.
