### ISSUE TITLE
Docker datasource, maven versioning, ansible manager togheter ?

### ISSUE THREAD

**Issue by lukasmrtvy** [renovatebot/config-help#956]
Can I use **docker datasource** with **maven versioning** with **ansible manager** together?
I want to update docker image in ansible task to new version according to maven versioning scheme.

Related:
https://docs.renovatebot.com/modules/datasource/#docker-datasource 
https://docs.renovatebot.com/modules/manager/ansible/
https://docs.renovatebot.com/modules/versioning/#maven-versioning

Thanks

**Comment by viceice** [comment]
sure, configure a packagerule.

Please fill the issue template. ⚠️
