### ISSUE TITLE
excludePackagePatterns not working as expected?

### ISSUE THREAD

**Issue by Meemaw** [renovatebot/config-help#958]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

I've configured `excludePackagePatterns` (https://github.com/insights-io/Insight/blob/master/.github/renovate.json#L8), but I still seem to get the updates for the package: e.g. https://github.com/insights-io/Insight/pull/817

**Comment by viceice** [comment]
You need to add `enablef=false` to your package rule.

Also add `^` to the patterns start to match package name only from beginning. Otherwise you'll match `xxx.io.quarkus` package names too

**Comment by rarkins** [comment]
I think what you probably need is this:

```
  "packageRules": [
    {
      "managers": ["gradle"],
      "packagePatterns": ["^io.quarkus"],
      "enabled" false
    }
  ]
```

The first two lines are what matches the packages, and third line is the action to take (disabling it)

**Comment by Meemaw** [comment]
Fixed, thanks 👍
