### ISSUE TITLE
How to add the Update, Age, Adoption and Tests columns to the Renovate config?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/config-help#959]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

I don't think the logs are relevant for what I'm trying to do.

### What would you like to do?

I saw that the Renovate repository has way prettier pull requests, that have more information than I'm currently getting from the bot.

I want to have a PR that looks like this (From a PR at your Renovate repository):

![wanted-pull-request](https://user-images.githubusercontent.com/34918129/97778797-e9a79980-1b79-11eb-90a4-27e45cf3e2fe.png)

But instead I get PRs that look like this:

![current-pull-request](https://user-images.githubusercontent.com/34918129/97778814-0fcd3980-1b7a-11eb-9f11-d2c5632bea9e.png)

I don't know if the **Update**, **Age**, **Adoption** and **Tests** fields are available in the free offering of Renovate bot?
I found this https://docs.renovatebot.com/configuration-options/#prbodydefinitions, that seems to be related maybe?

## My current Renovate config:

```json
{
  "extends": ["config:base", ":label(dependencies)"],
  "lockFileMaintenance": {
    "enabled": true
  },
  "dependencyDashboard": true
}
```

**Comment by viceice** [comment]
@HonkingGoose they are in early development and currently only available for our own repos. 😉

**Comment by HonkingGoose** [comment]
Ah, that's why I couldn't find this in the Renovate docs... :smile: 

I'll admire those nice PRs from a distance then at your Renovate repo, and wait until those pretty PRs grace my repositories as well. :smile: 

I'll close this issue, as this is not a configuration problem.

**Comment by rarkins** [comment]
I'll expose this as a preset soon, I don't mind others using it as long as you're aware it's in beta and could change at any time

**Comment by rarkins** [comment]
@HonkingGoose this is now available for public beta. See https://resources.whitesourcesoftware.com/news-whitesource/merge-confidence-feature for details. In short, add `“extends”: [“github>whitesource/merge-confidence:beta”]` to your config

**Comment by HonkingGoose** [comment]
Thanks for the follow-up @rarkins! :+1: 

I'll go try this out on my repositories.
