### ISSUE TITLE
Use single PR for all dependencies, but split it if checks fail

### ISSUE THREAD

**Issue by Leksat** [renovatebot/config-help#961]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I've configured Renovate to update all dependencies in a single PR with this: https://docs.renovatebot.com/faq/#use-a-single-branchpr-for-all-dependency-upgrades

But what I really like to achieve is:
- Renovate updates all dependencies in a single PR
- If automated checks fail on the PR, Renovate closes it and creates a separate PR for each dependency

Is this possible?

Thanks!

**Comment by viceice** [comment]
This is currently not possible. see renovatebot/renovate#1342

**Comment by Leksat** [comment]
Thank you!
