### ISSUE TITLE
Renovate Not Detecting go.mod, go.sum

### ISSUE THREAD

**Issue by evanstoddard23** [renovatebot/config-help#962]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I would like Renovate to work with updates to Go packages. Currently I get PRs for terraform and GitHub actions, but none for Go, even though I have a go.mod and go.sum in a subdirectory in my repo.

```json
{
  "extends": ["config:base", ":timezone(America/Chicago)", ":semanticCommits"],
  "packageRules": [
    {
      "updateTypes": ["patch"],
      "managers": ["terraform"],
      "semanticCommitType": "fix"
    },
    {
      "updateTypes": ["minor"],
      "managers": ["terraform"],
      "semanticCommitType": "feat"
    },
    {
      "updateTypes": ["major"],
      "managers": ["terraform"],
      "semanticCommitType": "feat!"
    },
    {
      "updateTypes": ["patch", "minor"],
      "automerge": true
    },
    {
      "paths": ["test/**"],
      "semanticCommitType": "chore"
    }
  ],
  "assigneesFromCodeOwners": true,
  "rebaseWhen": "behind-base-branch",
  "separateMinorPatch": true,
  "prHourlyLimit": 2
}
```

**Comment by viceice** [comment]
Please check the debug logs from app dashboard.

It would also help, if you provide a minimal reproduction repo.

**Comment by rarkins** [comment]
If you have any package files in test folders, it's ignored by this preset: https://docs.renovatebot.com/presets-default/#ignoremodulesandtests (which comes from `config:base`).

You can add this to config to disable that preset:

```
  "ignorePresets": [":ignoreModulesAndTests"]
```

**Comment by evanstoddard23** [comment]
@rarkins that worked, thank you! I'm having another issue with this config (lmk if I should open a separate GH issue). I'm expecting my terraform dependencies under my test directory to get updates using the chore type, but am instead getting feat. This quote from the docs is what has me confused: 

> Renovate will evaluate all packageRules and not stop once it gets a first match. Therefore, you should order your packageRules in order of importance so that later rules can override settings from earlier rules if necessary.

```json
{
  "extends": ["config:base", ":timezone(America/Chicago)", ":semanticCommits"],
  "ignorePresets": [":ignoreModulesAndTests"],
  "postUpdateOptions": ["gomodTidy"],
  "packageRules": [
    {
      "updateTypes": ["patch"],
      "managers": ["terraform"],
      "semanticCommitType": "fix"
    },
    {
      "updateTypes": ["minor", "major"],
      "managers": ["terraform"],
      "semanticCommitType": "feat"
    },
    {
      "updateTypes": ["patch", "minor"],
      "automerge": true
    },
    {
      "paths": ["test/**"],
      "extends": [":semanticCommitTypeAll(chore)"]
    }
  ],
  "assigneesFromCodeOwners": true,
  "rebaseWhen": "behind-base-branch",
  "separateMinorPatch": true
}
```

**Comment by viceice** [comment]
Do not use `semanticCommitTypeAll` in a package rule, as nested packaged rules are not supported. 

Simply use `"​semanticCommitType​"​: ​"​chore"​` in your tests rule

**Comment by rarkins** [comment]
I created https://github.com/renovatebot/renovate/issues/7649 to look into supporting that type of nested package rule + preset

**Comment by evanstoddard23** [comment]
Updated my config to this:

```json
{
  "extends": ["config:base", ":timezone(America/Chicago)", ":semanticCommits"],
  "ignorePresets": [":ignoreModulesAndTests", ":prHourlyLimit2"],
  "postUpdateOptions": ["gomodTidy"],
  "packageRules": [
    {
      "updateTypes": ["patch"],
      "managers": ["terraform"],
      "semanticCommitType": "fix"
    },
    {
      "updateTypes": ["minor", "major"],
      "managers": ["terraform"],
      "semanticCommitType": "feat"
    },
    {
      "paths": ["test/**"],
      "semanticCommitType": "chore"
    },
    {
      "updateTypes": ["patch", "minor"],
      "automerge": true
    },
    {
      "managers": ["github-actions", "gomod"],
      "schedule": ["before 9am on monday"]
    }
  ],
  "assigneesFromCodeOwners": true,
  "rebaseWhen": "behind-base-branch",
  "separateMinorPatch": true
}

```

But I'm still getting Terraform updates under the test directory with type `feat`

**Comment by rarkins** [comment]
Maybe the paths glob is somehow not matching. Can you reproduce this with same config in a public repo?

**Comment by evanstoddard23** [comment]
@rarkins I replicated the issue here: https://github.com/evanstoddard23/renovate-test/pull/1

**Comment by rarkins** [comment]
@evanstoddard23 can you see if merging https://github.com/evanstoddard23/renovate-test/pull/2 makes a difference? There may be a specificity issue I hadn't expected.

**Comment by evanstoddard23** [comment]
@rarkins looks like that did the trick!

**Comment by rarkins** [comment]
Glad to hear it. Unfortunately seems to be a legacy specificity issue. We consider rules with *updateTypes* to be the most specific you can be and so they are given preference regardless of ordering. We're going to need to do a breaking change before too long to revert that concept and instead just operate based on order.
