### ISSUE TITLE
Organisation wide configuration and schedule changes

### ISSUE THREAD

**Issue by msimperi** [renovatebot/config-help#964]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Repository X using organisation wide configuration, last time executed.
![image](https://user-images.githubusercontent.com/2699541/97957513-03ccbc00-1db4-11eb-94e6-71d1cca50d72.png)

Organisation wide configuration repository has been updated and executed.
![image](https://user-images.githubusercontent.com/2699541/97957543-1941e600-1db4-11eb-8189-46198cb7cb5d.png)

### What would you like to do?

I added first default configuration value that run dependency updates "early mondey". With this I configured repository X and it started to wait "monday morning". Now I changed organisation wide schedule to be "weekdays" and before that no preset scehdule.

I'm not able to see repository X executed even the main configuration has changed few times. Does the organisation wide configuration change trigger also repository X runs? It seems now that it does not.

**Comment by viceice** [comment]
Look like caching is defering runs, try to use the trigger run checkbox from `dependencyDashboard`, that should reevaluate all configs

**Comment by msimperi** [comment]
Sadly I didn't have that one already enable for repository X. I enabled it now in base configuration, but it still does not seem to trigger repository x run...

**Comment by rarkins** [comment]
Repos in onboarding stage aren't checked hourly

**Comment by msimperi** [comment]
The repository was not anymore in on-boarding stage. I have accepted the PR already, but it seems that the main-config change on schedule do not activate automatically in repository x using that main config.

**Comment by msimperi** [comment]
Here are techinical job ids: 254966587 and 255393657.

**Comment by viceice** [comment]
can you paste the relevant logs here, as we can't easily view your logs without being a member of your repo

**Comment by rarkins** [comment]
And FYI there is no chain reaction where commits to a base config in repo X are detected and trigger all downstream repos to run

**Comment by msimperi** [comment]
I made a small change to target repository and was able to trigger re-run for it. Now it seems to work correctly. I also created dashboard issue to trigger runs again if needed manually.

Thanks @viceice and @rarkins for the help!
