### ISSUE TITLE
Renovate not checking repository once per hour (even during night)

### ISSUE THREAD

**Issue by msimperi** [renovatebot/config-help#967]
WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

I have few identical configuration between repositories. Using same renovate.json file. Somehow the other repository renovate checks are executed once per hour and in this example case these jobs are not executed that often (might be 10h between executions)

256227743 (automatically executed)
256672519 (manually triggered)
256698025 (manually started)

![image](https://user-images.githubusercontent.com/2699541/98357756-59ac9880-202e-11eb-8298-ed640272cd1f.png)

```
repo/renovate.json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["local>myorganisation/renovate-config"],
  "packageRules": [
    {
      "updateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    }
  ]
}

myorganisation/renovate-config/renovate.json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "enabled": true,
  "extends": [
    "config:base",
    ":pinAllExceptPeerDependencies",
    ":semanticPrefixChore",
    "schedule:nonOfficeHours"
  ],
  "timezone": "Europe/Helsinki",
  "dependencyDashboard": true,
  "labels": ["dependencies"],
  "rebaseWhen": "behind-base-branch",
  "vulnerabilityAlerts": {
    "labels": ["security"]
  },
  "packageRules": [
    {
      "packageNames": ["aws-sdk"],
      "schedule": ["after 9pm on sunday"]
    }
  ],
}
```

### What would you like to do?

I would like to see that renovate is once per hour checking is there something to do. The schedule could be limited to "non-office hours", but last night I don't see any runs in the repository.

Could some of my org repositories be renovate checks be stuck? I'm still able to trigger manually the run, but how I would like it to work.

**Comment by rarkins** [comment]
This repo is classified as onboarding in the DB, meaning it's not scheduled hourly and instead only when edits to the `renovate.json` in the onboarding PR are received.

**Comment by rarkins** [comment]
Looks to be enabled now, I think you should see jobs run most hours.

**Comment by msimperi** [comment]
I think few repositories started to run normally now. I see still one repository that executed this job 256677544 one day ago and didn't continue running. Is it possible that @rarkins you check that also? It has also identical configuration.
