### ISSUE TITLE
How do I set the bot to automerge branches?

### ISSUE THREAD

**Issue by Drillan767** [renovatebot/config-help#968]
### Which Renovate are you using?

WhiteSource Renovate App

Renovate Pro

### Which platform are you using?

GitHub.com

### What would you like to do?

Here is my current configuration (in a file named renovate.json, at the root of my project):

```json
{
    "extends": [
        "config:base"
    ],
    "schedule": ["every weekend"],
    "automerge": true,
    "automergeType": "branch",
    "major": {
        "automerge": false
    }
}
```

I simply would like the bot to work once every weekend, to create a branch with all the updates it found and auto merge it by itself. However, with this configuration, I find myself with unmerge pull request, and the description says "automerge is disabled".

I can't either find or figure out an example of how to setup that. However, it looks like the "schedule" part works well.

Thanks in advance

**Comment by rarkins** [comment]
Can you reproduce in a public repo so I can check it out?

**Comment by Drillan767** [comment]
Sure, here is one of the repos that has renovate in it: https://github.com/Drillan767/Overlord

**Comment by rarkins** [comment]
I don't see any Renovate PRs in that repo.

**Comment by Drillan767** [comment]
Well it seems to actually work, I checked the commits and the only PRs I found were for major version changes, and some things have been pushed as branches by the bot. I guess I'm closing the issue now.
