### ISSUE TITLE
How to run the Docker version of Renovate to only rebase existing PRs and not raise new ones?

### ISSUE THREAD

**Issue by risafj** [renovatebot/config-help#972]
### Which Renovate are you using?
Renovate Open Source CLI
Or rather, its Docker image (https://hub.docker.com/r/renovate/renovate/)

### Which platform are you using?
GitHub.com

### What would you like to do?

I'm using the `renovate/renovate` Docker image and executing it periodically on CircleCI as a scheduled job.

This is working just fine, but there are times when I only want to trigger rebases (and automerges) on existing PRs, but not raise new PRs for further package updates.
If I were using the official GitHub plugin, I'm guessing this can be achieved by ticking the checkbox that says `If you want to rebase/retry this PR, check this box in the PR`. But how can I achieve this while using the Docker image?

NOTE: My Renovate config is set to `"rebaseWhen": "behind-base-branch"`, so existing PRs will be rebased correctly if I run `docker run renovate/renovate` - my problem is that new PRs will also be raised.

Copy-pasting my config just in case:
```json
{
  "extends": [
    "config:base"
  ],
  "baseBranches": ["master"],
  "schedule": "at any time",
  "enabledManagers": ["npm"],
  "rebaseWhen": "behind-base-branch",
  "patch": {
    "automerge": true
  }
}
```

Thank you for any help in advance!

**Comment by rarkins** [comment]
If you configure a schedule then the current behavior is that existing branches will be rebased if behind but no new ones will be created.

**Comment by risafj** [comment]
@rarkins Thank you so much for the quick response 👍🏻  Just to be clear, do you mean I can: 

1. Change the schedule to something like `"schedule": "after 9am and before 6pm on Monday"`
2. Run `docker run renovate/renovate` between Monday 9am-6pm
    - -> Renovate will rebase, automerge, and also raise new PRs
3. Run `docker run renovate/renovate` any time that's not between Monday 9am-6pm
    - ->  Renovate will only rebase and automerge

If so, that would be great.

**Comment by rarkins** [comment]
Yes, that's how it should work

**Comment by risafj** [comment]
Awesome, thank you so much!
