### ISSUE TITLE
Cannot merge some patch dependencies

### ISSUE THREAD

**Issue by fclairamb** [renovatebot/config-help#974]
WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Yes you can find them here: https://app.renovatebot.com/dashboard#github/habx/ui-table/259137788

### What would you like to do?

I'd like to automatically merge all patch `dependencies` (except one). It works fine on other repositories but not on [this one](https://github.com/habx/ui-table) and I don't get why:

The [following config](https://github.com/habx/ui-table/blob/dev/.github/renovate.json) defines contains this `packageRule`:
```json
    {
      "updateTypes": [
        "patch"
      ],
      "depTypeList": [
        "dependencies",
        "peerDependencies"
      ],
      "automerge": true,
      "labels": [
        "habx-automerge"
      ]
    },
```

But then for [this PR](https://github.com/habx/ui-table/pull/674) I will get the following PR status:
> 🚦 Automerge: Disabled by config. Please merge this manually once you are satisfied.

And [the logs](https://app.renovatebot.com/dashboard#github/habx/ui-table/259137788) show something even stranger:
```json
        "deps": [
          {
            "depType": "dependencies",
            "depName": "@testing-library/react",
            "currentValue": "^11.1.1",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "lockedVersion": "11.1.1",
            "depIndex": 0,
            "warnings": [],
            "fixedVersion": "11.1.1",
            "sourceUrl": "https://github.com/testing-library/react-testing-library",
            "updates": [
              {
                "fromVersion": "11.1.1",
                "toVersion": "11.1.2",
                "newValue": "^11.1.2",
                "newMajor": 11,
                "newMinor": 1,
                "updateType": "minor",
                "isSingleVersion": false,
                "isRange": true,
                "releaseTimestamp": "2020-11-11T09:05:57.624Z",
                "canBeUnpublished": true,
                "isBump": true
              }
            ]
          }
   ]
```

Which I suspect is the source of the issue because it shows `"updateType": "minor"` when it seems it should set to `patch`.

Can you help me figure this out?

**Comment by rarkins** [comment]
Add separateMinorPatch=true to your config

**Comment by viceice** [comment]
https://docs.renovatebot.com/configuration-options/#separateminorpatch
