### ISSUE TITLE
Getting value of null error with Azure Devops

### ISSUE THREAD

**Issue by jlkweb12** [renovatebot/config-help#977]
### Which Renovate are you using?

Renovate Open Source CLI

Version : 23.82.0

### Which platform are you using?

Azure DevOps

### What would you like to do?

I am using the following configs to execute renovate. I am using a self hosted Azure Devops 2020 version.

"config": {
         "endpoint": "https://[selfhostedADOURL].com",
         "token": "***********",
         "platform": "azure",
         "logFileLevel": "debug",
         "logLevel": "debug",
         "onboarding": true,
         "onboardingConfig": {"extends": ["config:base"]},
         "hostRules": [],
         "dryRun": true,
         "autodiscover": true
       }

No matter what config I try, I am getting:

FATAL: Fatal error: Cannot read property 'value' of null
       "err": {
         "message": "Cannot read property 'value' of null",
         "stack": "TypeError: Cannot read property 'value' of null\n    at /usr/lib/node_modules/renovate/node_modules/azure-devops-node-api/VsoClient.js:124:52\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 60,
           "logContext": "pprOF5ccp",
           "err": {
             "message": "Cannot read property 'value' of null",
             "stack": "TypeError: Cannot read property 'value' of null\n    at /usr/lib/node_modules/renovate/node_modules/azure-devops-node-api/VsoClient.js:124:52\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
           },
           "msg": "Fatal error: Cannot read property 'value' of null"
         }
       ]

What am I missing?

**Comment by jlkweb12** [comment]
Upon further investigation, it looks like a token will not work for our setup. Can basic auth be used?

**Comment by rarkins** [comment]
Please follow #971
