### ISSUE TITLE
Best config options for self-hosted on internal AWS instance and private repos

### ISSUE THREAD

**Issue by nickdoesdesign** [renovatebot/config-help#98]
Hi there,

Our system will be self hosting, so we have the renovate/renovate repo cloned onto an AWS instance. We want that to watch specific private npm modules that are mission critical, and create pull requests in the repos for the consumers of said packages.

My questions:
1) Do I need to create a new git user just for that self-hosted machine running renovate, and then add that user to each of the consumers? 

2) What config option is for the hosted machine to point at our private NPM modules to watch for updates there?

2) Do I need to add a global renovate.json to that hosted machine? Or is it just the consumers that need to have that entry? Mix of both? 

3) which part needs the encrypted token for our private npm modules? The hosted machine, or the consumer repos?

Thanks in advance, and thanks for creating the one piece of software I've found that may actually handle our dependency hell!

**Comment by rarkins** [comment]
Check out https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md for starters

1. As recommended there, create a dedicated GitHub user for the bot and add it to every repo you need. Run the bot with `—autodiscover` to service them all. 

2. Bot does not *need* its own config but you might want to configure `onboardingConfig` to save copy lasting common settings to each repo

3. Not necessary to encrypt or have it on repo if hosting your own bot. Easiest is to copy a `.npmrc` to the home dir of the server. Alternatively add it unencrypted to bot’s own config

**Comment by nickdoesdesign** [comment]
Awesome, thanks!

**Comment by nickdoesdesign** [comment]
@rarkins where should the config file as described in the self-hosting doc live?

**Comment by rarkins** [comment]
@nickdoesdesign 	see https://github.com/renovatebot/renovate/blob/master/docs/configuration.md - it's `config.js` by default
