### ISSUE TITLE
Create pull requests per updated files

### ISSUE THREAD

**Issue by suzuki-shunsuke** [renovatebot/config-help#985]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I want to split pull requests per updated files.
I try to use [additionalBranchPrefix](https://docs.renovatebot.com/configuration-options/#additionalbranchprefix),
but it seems that `parentDir` is not full path but the parent directory name, and if the parent directory name is same, the updates are included in the same pull request.

https://github.com/suzuki-shunsuke/test-renovate-2/blob/c69b1a5bf7e55d1f116da8b733f82fa51b790f02/renovate.json

```json
{
  "packageRules": [
    {
      "managers": ["terraform"],
      "additionalBranchPrefix": "{{parentDir}}-",
      "packagePatterns": [".*"]
    }
  ]
}
```

directory structure

```
services/
  foo/
    staging/
      provider.tf
    production/
      provider.tf
  bar/
    staging/
      provider.tf
    production/
      provider.tf
```

provider.tf

```tf
provider "aws" {
  version = "~> 2.50.0"
}
```

There are four provider.tf and I want to update them by separated pull requests.
But actually foo/staging/provider.tf and bar/staging/provider.tf are upgraded in the same pull request.

* https://github.com/suzuki-shunsuke/test-renovate-2/pull/9
* https://github.com/suzuki-shunsuke/test-renovate-2/pull/10

**Comment by rarkins** [comment]
Try baseDir instead of parentDir. Ref: https://docs.renovatebot.com/templates/

**Comment by suzuki-shunsuke** [comment]
Thank you for your reply.
I tried `baseDir` and it works well.
This is what I want!

https://github.com/suzuki-shunsuke/test-renovate-2/pull/13
https://github.com/suzuki-shunsuke/test-renovate-2/pull/14
https://github.com/suzuki-shunsuke/test-renovate-2/pull/15
https://github.com/suzuki-shunsuke/test-renovate-2/pull/16

Thanks a lot!
