### ISSUE TITLE
Bitnami compatibility tags detected as unstable

### ISSUE THREAD

**Issue by morremeyer** [renovatebot/config-help#990]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

The relevant parts of the debug log are:

**For the `helm-values` manager**:

```
           {
             "packageFile": "mysql/values.yaml",
             "manager": "helm-values",
             "deps": [
               {
                 "depName": "bitnami/mysql",
                 "currentValue": "8.0.22-debian-10-r23",
                 "datasource": "docker",
                 "replaceString": "8.0.22-debian-10-r23",
                 "depIndex": 0,
                 "updates": [
                   {
                     "fromVersion": "8.0.22-debian-10-r23",
                     "toVersion": "8.0.22",
                     "newValue": "8.0.22",
                     "newMajor": 8,
                     "newMinor": 0,
                     "updateType": "minor",
                     "isSingleVersion": true
                   }
                 ],
                 "warnings": [],
                 "fixedVersion": "8.0.22-debian-10-r23",
                 "dockerRegistry": "https://index.docker.io",
                 "dockerRepository": "bitnami/mysql"
               }
             ]
           }
``` 

### What would you like to do?

I’m using bitnami images in multiple places, e.g. `bitnami/mysql` in my helm `values.yaml` files. As the helm charts use compatibility tags, I want to keep them specific.

However, renovate seems to detect the compatibility tags as unstable tags, e.g. in a MR with the following diff:

``` 
 image:
   repository: bitnami/mysql
-  tag: 8.0.22-debian-10-r23
+  tag: 8.0.22
```

According to the [Version compatibility docs](https://docs.renovatebot.com/docker/#version-compatibility), this should not happen. I am guessing that renovate does not recognize the bitnami-style compatibility tags as such and assumes they are unstable tags. 

This guess is mainly due to the description how unstable versions are detected in the [ignoreUnstable documentation](https://docs.renovatebot.com/configuration-options/#ignoreunstable).

Can somebody help me out how to correctly configure this as the scheme is `8.0.22-debian-10-r23` -> `${software_version}-debian-${debian_version}-r${release_version}`?

**Comment by viceice** [comment]
Workaround is to assign `docker` versioning to `helm-values` manager, this will refuse that update.

Renovate currently won't be able to update `release_version` number.
