### ISSUE TITLE
Does Renovate support custom package dependency types?

### ISSUE THREAD

**Issue by nbartos** [renovatebot/config-help#991]
### Which Renovate are you using?
None yet

### Which platform are you using?
Bitbucket Server

### What would you like to do?
We have a custom package dependency system. The latest version for each package is determined by making a HTTP query and sorting the result of a regex search. The package version used is pinned in a custom yaml file. Does Renovate support custom dependency systems such as this?

**Comment by rarkins** [comment]
No, this is not currently supported. First step would be https://github.com/renovatebot/renovate/issues/6223 where we'd support simple cases like JSON endpoints initially.
