### ISSUE TITLE
Automerge *before* updating branch

### ISSUE THREAD

**Issue by wolfgang42** [renovatebot/config-help#992]
**What would you like Renovate to be able to do?**

I have a repository where I run Renovate on a very slow schedule (weekly) relative to one of the project's dependencies (which updates several times a day). I've noticed that as a result the dependency updates aren't being automerged; since Renovate sees a new version every time it seems to prefer updating the branch rather than merging it, so the upgrades never make it to master.

It would be very useful if there was a way to tell Renovate to do the merge if tests have passed, *before* trying to update the branch again, so it doesn't get forever stuck in a cycle of constant updates.

**Did you already have any implementation ideas?**

No, not really.

**Comment by rarkins** [comment]
For your GitLab schedule, run Renovate every hour (or at least much more often), so that it has the chance to automerge. Then use Renovate's built-in schedules to control when it creates branches/MRs.

**Comment by wolfgang42** [comment]
That...seems incredibly obvious in hindsight. I've been trying to figure out what's causing this issue for a while now and by the time I'd figured it out I had thought it must be _some_ issue with Renovate and totally overlooked the simple option. Thanks for your patience, I'll close this issue and go fix my schedule now :)
