### ISSUE TITLE
Bot overwrites changes on configure PR

### ISSUE THREAD

**Issue by giokara-oqton** [renovatebot/config-help#997]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

1 host error warning with message "A pull request already exists for ...:renovate/configure."

### What would you like to do?

After a "Configure Renovate" PR is created with a default renovate.json file, I would like to change the configuration as [described in the docs here](https://docs.renovatebot.com/configure-renovate/#no-risk-onboarding). After committing and pushing the changes, the bot force pushes and restores the original configuration file.

How can the overwrite by the bot be avoided?

**Comment by rarkins** [comment]
Please describe the exact steps to reproduce

**Comment by giokara-oqton** [comment]
Unfortunately the only steps undertaken are the ones described above. The exact warning message in the logs is the one below, hopefully this helps:

```
WARN: Host error
{
  "hostType": "github",
  "err": {
    "name": "HTTPError",
    "timings": {
      "start": 1606310392812,
      "socket": 1606310392812,
      "lookup": 1606310392816,
      "connect": 1606310392825,
      "secureConnect": 1606310392834,
      "upload": 1606310392835,
      "response": 1606310393297,
      "end": 1606310393297,
      "phases": {
        "wait": 0,
        "dns": 4,
        "tcp": 9,
        "tls": 9,
        "request": 1,
        "firstByte": 462,
        "download": 0,
        "total": 485
      }
    },
    "message": "Response code 422 (Unprocessable Entity)",
    "stack": "HTTPError: Response code 422 (Unprocessable Entity)\n    at Request.<anonymous> (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "options": {
      "headers": {
        "user-agent": "Renovate Bot (GitHub App 2740)",
        "accept-encoding": "gzip, deflate",
        "accept": "application/vnd.github.machine-man-preview+json",
        "authorization": "***********",
        "content-type": "application/json",
        "content-length": "61186"
      },
      "url": "https://api.github.com/repos/*****/******/pulls",
      "username": "",
      "password": "",
      "method": "POST",
      "http2": false
    },
    "response": {
      "statusCode": 422,
      "statusMessage": "Unprocessable Entity",
      "body": {
        "message": "Validation Failed",
        "errors": [
          {
            "resource": "PullRequest",
            "code": "custom",
            "message": "A pull request already exists for *****:renovate/configure."
          }
        ],
        "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"
      },
      "headers": {
        "date": "Wed, 25 Nov 2020 13:19:53 GMT",
        "content-type": "application/json; charset=utf-8",
        "content-length": "246",
        "connection": "close",
        "server": "GitHub.com",
        "status": "422 Unprocessable Entity",
        "x-github-media-type": "github.v3; param=machine-man-preview; format=json",
        "x-ratelimit-limit": "6850",
        "x-ratelimit-remaining": "6404",
        "x-ratelimit-reset": "1606310555",
        "x-ratelimit-used": "446",
        "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
        "access-control-allow-origin": "*",
        "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
        "x-frame-options": "deny",
        "x-content-type-options": "nosniff",
        "x-xss-protection": "1; mode=block",
        "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
        "content-security-policy": "default-src 'none'",
        "vary": "Accept-Encoding, Accept, X-Requested-With",
        "x-github-request-id": "C90A:8243:860625:A34A09:5FBE59F8"
      },
      "httpVersion": "1.1"
    }
  }
}
INFO: External host error causing abort - skipping
```

**Comment by rarkins** [comment]
Describe exactly what you mean by 'After committing and pushing the changes'. Did you force push? Did you add a commit on top? Was it your own identity?

**Comment by giokara-oqton** [comment]
Tried two approaches to be exact:
1. In a terminal (using my own SSH key):
- Checkout the `renovate/configure` branch.
- Make some changes to the `renovate.json` file (added the option "rebaseWhen": "conflicted").
- Commit the changes: `git add renovate.json && git commit -m "Update renovate.json"`.
- Push the changes `git push origin renovate/configure`.

2. Using my own account, on github.com:
- Go to the repository, find the related "Configure Renovate" PR.
- In the PR, go to "Files changed" tab.
- Select the three dots in the top-right corner of the `renovate.json` file.
- Select "Edit file".
- Make some changes to the file (added the option "rebaseWhen": "conflicted").
- In the bottom of the page, select "Commit directly to the `renovate/configure` branch".
- Press on "Commit changes".

**Comment by rarkins** [comment]
Thanks for that detail. I will test if I can reproduce it myself.

**Comment by rarkins** [comment]
I am not seeing the same behavior in https://github.com/rarkins/update-onboarding/pull/1

I added a second commit using the github web UI, and you can see it has detected my commit and updated the PR body to say:

![image](https://user-images.githubusercontent.com/6311784/100241672-3e012780-2f34-11eb-8cfc-63474849331e.png)

It hasn't (yet) overwritten it.

Can you reproduce this in a demo public repo?

**Comment by giokara-oqton** [comment]
I have not been able to reproduce it. There were previous attempts to use the renovate bot in the repo, which were probably the cause of the issue. After a different person restarted the onboarding procedure, this got resolved.
